<!-- START of: finna - search/home/home-2.phtml -->
<div>
  <h2>Usein kysyttyä</h2>
</div>
<div>
  <div class="info-col">
    <div class="infobox">
    <h3>Peruuta varauksesi</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sodales erat eget enim ultrices ornare. Sed mollis blandit cursus. Pellentesque auctor vehicula enim. <p>
    <p><a class="btn btn-primary" role="button" href="">Esimerkkihaku</a>
    </div>
  </div>
  <div class="info-col">
    <div class="infobox">
      <h3>Uusi lainat </h3>
      <p><a class="btn btn-primary" role="button" href="<?=$this->url('myresearch-checkedout')?>" title="Kirjaudu sisään"><i class="fa fa-sign-in"></i> Kirjaudu sisään </a> kirjastokortilla </p>
      <p>Klikkaa uusi kaikki lainat -painiketta.</p>
      <p>Kaikki uusittavissa olevat lainasi uusitaan.</p>
    </div>
  </div>

  <div class="info-col">
    <div class="infobox">
      <h3>Missä voin käyttää Helmet-kirjastokorttia?</h3>
      <p>Voit käyttää Helmet-kirjastokorttia Espoossa, Helsingissä, Kauniaisissa ja Vantaalla kuin omassa lähikirjastossasi. Voit lainata, varata, uusia, palauttaa ja hoitaa asioitasi missä 
      kirjastossa tahansa kaupunkien rajoista välittämättä.</p>
    </div>
  </div>
  <p>Lisää <a href="<?=$this->url('content-page', ['page' => 'help'])?>">usein kysyttyjä kysymyksiä</a></p>
</div>
<!-- END of: finna - search/home/home-2.phtml -->


