<!-- START of: finna - search/home/home-1.phtml -->
<div>
  <div class="row" id="nosto-finnakortit">
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Suosittelemme juuri nyt</h2> 
           </div>
            <img src="/themes/custom/images/kirjat-nosto.jpg">
            <p>Selaa kirjavinkkejä ja tutustu Helmet-kirjastojen teemaviikkoihin ja kampanjoihin.</p>
            <p><a href="">Siirry suosituksiin</a></p>
        </div> 
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Uutiset</h2> 
           </div>
            <img src="/themes/custom/images/oulukirjasto-nosto.jpg">
            <p>Lue uusimmat uutiset ja tiedotteet Helmet-kirjaston palvelujen käytöstä.</p>
            <p><a href="<?=$this->url('content-page', ['page' => 'uutiset'])?>">Lue uutisia kirjastoista</a></p>
        </div> 
    </div>    
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Kirjallisuus</h2>   
           </div>
            <img src="/themes/custom/images/kirjasto-nosto.jpg">
            <p>Tähän kuvaus teemasivun sisällöstä. Tähän kuvaus teemasivun sisällöstä.</p>
            <p><a href="<?=$this->url('content-page', ['page' => 'kirjallisuus'])?>">Lisää kirjallisuudesta</a></p>
        </div> 
    </div>    
<div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Musiikki</h2> 
           </div>
            <img src="/themes/custom/images/musiikki-nosto.jpg">
            <p>Tähän kuvaus teemasivun sisällöstä. </p>
            <p><a href="<?=$this->url('content-page', ['page' => 'musiikki'])?>">Lisää musiikista</a></p>
        </div> 
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Työtilat ja laitteet</h2> 
           </div>
            <img src="/themes/custom/images/tyotilat-nosto.jpg">
            <p>Tähän kuvaus teemasivun sisällöstä. </p>
            <p><a href="<?=$this->url('content-page', ['page' => 'tyotilat-ja-laitteet'])?>">Lisää työtiloista ja laitteista</a></p>
        </div> 
    </div>    
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Monikielinen kirjasto</h2>  
           </div>
            <img src="/themes/custom/images/monikielinen-nosto.jpg">
            <p>Tähän kuvaus teemasivun sisällöstä. </p>
            <p><a href="<?=$this->url('content-page', ['page' => 'monikielinen-kirjasto'])?>">Monikielinen kirjasto</a></p>
        </div> 
    </div>    
    <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="finnafi-card">
           <div class="theme-card-title">
              <h2>Lapset</h2> 
           </div>
            <img src="/themes/custom/images/lapset-nosto.jpg">
            <p>Tähän kuvaus teemasivun sisällöstä. </p>
            <p><a href="<?=$this->url('content-page', ['page' => 'lapset'])?>">Lapsille</a></p>
       </div> 
    </div>    

  </div>
</div>  





<!-- END of: finna - search/home/home-1.phtml -->
