<? $this->headTitle($this->translate('Lapset')); $this->content()->setHeading($this->translate('Lapset'));?>
<p>mitä *piip* miks mikääääään ei näy</p>
<div class="row">
  <div class="col-sm-4">
      <p>Tervetuloa lasten kirjastoon</p></div>
  <div class="col-sm-4">Toinen elementti</div>
  <div class="col-sm-4">Kolmas elementti</div>
</div>

<h2>Lukudiplomit</h2>
<h2>Lukuvalmentaja Junior</h2>

<h2>Päiväkoti- ja kouluyhteistyö</h2>
