<? $this->headTitle($this->translate('Kundregisterbeskrivning')); $this->content()->setHeading($this->translate('Kundregisterbeskrivning'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>EU:s allmänna dataskyddsförordning (2016/679)</p>
        <p>25.5.2018</p>
      </div>
     <div id="namn" class="content-section">
        <h2>1. Registrets namn</h2>
        <p>Helmet-bibliotekens användarregister</p>
      </div>
      <div id="uppratthallare" class="content-section">
        <h2>2. Registerupprätthållare</h2>
        <p>Esbo: Esbo stad</p>
        <p>Helsingfors: chefen för bibliotekstjänsterna</p>
        <p>Grankulla: Grankulla stad</p>
        <p>Vanda: undervisningsnämnden</p>
      </div>
      <div id="ansvariga" class="content-section">
        <h2>3. Registeransvariga</h2>
        <p>Esbo: chefen för bibliotekstjänsterna</p>
        <p>Helsingfors: chefen för bibliotekstjänsterna</p>
        <p>Grankulla: biblioteksdirektören</p>
        <p>Vanda: chefen för bibliotekstjänsterna</p>
      </div>
      <div id="contact-person" class="content-section">
        <h2>4. Registrets kontaktpersoner</h2>
        <p>Esbo: biblioteksservicechef. Esbo stadsbibliotek</p>
        <p>Helsingfors: servicechef. Helsingfors stadsbibliotek. Böle bibliotek</p>
        <p>Grankulla: informatiker. Grankulla stadsbibliotek</p>
        <p>Vanda: specialbiblioteksfunktionär, Vanda stadsbibliotek</p>
        <h3>Kontaktuppgifter</h3>
        <p>Esbo stad<br>
        Registratorskontoret i Esbo<br>
        PB 1<br>
        02070 ESBO STAD</p>
        
        <p>Helsingfors stad<br>
        Registratorskontoret<br>
        PB 10 (Norra Esplanaden 11 – 13)<br>
        00099 Helsingfors stad</p>
        
        <p>Grankulla stad<br>
        Registratorskontoret<br>
        PB 52 (Grankullavägen 10)<br>
        02701 Grankulla</p>
        
        <p>Vanda stad<br>
        Registratorskontoret<br>
        Stationsvägen 7<br>
        01300 Vanda</p>
      </div>
      <div id="purpose" class="content-section">
        <h2>5. Ändamål och rättsliga grunder för behandling av personuppgifter</h2>
        <p>Ändamålet för behandlingen av registrets personuppgifter är arrangerandet av bibliotekstjänster. Biblioteken använder registret för 
        att övervaka utlåningen, för indrivning, för statistiska ändamål, för information, för nättjänster och mobila tjänster, för meröppna 
        bibliotek, för övriga bibliotekstjänster, samt för identifiering av biblioteksanvändarna.</p>
        <p>Juridisk grund för behandlingen:</p>
        <p> EU:s allmänna dataskyddsförordning, artikel 6. punkt c) Behandlingen är nödvändig för att fullgöra en rättslig förpliktelse som 
        åvilar den personuppgiftsansvarige.</p>
        <p>Central lagstiftning:</p>
        <p>EU:s allmänna dataskyddsförordning (2016/679)<br>
        Lag om allmänna bibliotek (1492/2016)<br>
        Lag om offentlighet i myndigheters verksamhet (621/1999)<br>
        Dataskyddslag (1050/2018)</p>
      </div>
      <div id="innehall" class="content-section">
        <h2>6. Registrets innehåll</h2>
        <p>I registret sparas följande uppgifter om de registrerade:</p>
        <ul class="list-bullets">
            <li>namn, personnummer, användarnummer, PIN-kod krypterad adress, telefonnummer, e-postadress, födelsedatum, användargrupp (t.ex. barn, vuxen, användare av hemtjänsten, institution)</li>
            <li>för statistik: kön</li>
            <li>för postning: språkval och försändningssätt</li>
            <li>låneövervakningsuppgifter, giltiga lån och reserverat material</li>
            <li>outredda frågor (t.ex. obetalda avgifter) och därmed förknippade anmärkningar</li>
        </ul>
        <p>På motsvarande sätt registreras personuppgifterna för den som fungerar som ansvarig person för en person som inte fyllt 15 år, 
        eller för en inrättning eller ett samfund.</p>
        <p>En del av registeruppgifterna är tillgängliga för användaren på adressen www.helmet.fi. För att se de egna uppgifterna behövs ett 
        användarnummer och en personlig PIN-kod.</p>
      </div>
        <div id="overatelse" class="content-section">
        <h2>7. Normal överlåtelse av personuppgifter</h2>
        <p>Vart och ett stadsbibliotek sköter indrivningen av ickereturnerat material som de äger. Uppgifter om registrerade vuxna personer som 
        har lån som inte returnerats trots att 60 dygn gått sedan förfallodagen överlämnas till indrivning en gång i veckan som linjeöverföring. 
        Uppgifterna består av den registrerades namn, adress, telefonnummer och personbeteckning samt förfallodag, titel och pris på det 
        ickereturnerade materialet.</p>
        <p>Registrets personuppgifter behandlas av producenterna av följande tjänster som biblioteket erbjuder sina användare:</p>
        <ul class="list-bullets">
            <li>producenter av bibliotekssystemets program</li>
            <li>producenter av bibliotekssystemets service</li>
            <li>producenter av utlånings- och returneringsapparaterna</li>
            <li>producenter av meröppna bibliotek</li>
            <li>producenter av nättjänster</li>
            <li>producenter av mobila tjänster</li>
            <li>producenter av betaltjänster via nätet</li>
            <li>producenter av e-material</li>
            <li>producenter av apparater för användarbruk</li>
        </ul>
        <p>Anonymiserad data kan överföras:</p>
        <ul class="list-bullets">
            <li>för rekommendationstjänster</li>
            <li>för statistik och forskning</li>
        </ul>
        <p>Biblioteken har gjort upp avtal med nämnda tjänster. </p>
        <p>Personuppgifterna i registret kan lämnas ut till instanser som enligt lag har rätt att få uppgifterna, till exempel stadens 
        socialvård med stöd av barnskyddslagen eller polisen med stöd av polislagen.</p>
      </div>
     <div id="forvaringstid" class="content-section">
        <h2>8. Förvaringstid av informationen</h2>
        <p>Om en användare förhandregistrerat sina uppgifter via bibliotekets nättjänst men inte avhämtat sitt bibliotekskort avlägsnas 
        informationen efter tre månader.</p>
        <p>Biblioteket kan avlägsna uppgifter om en användare ur registret om de inte använts på tre år och inte anknyter till outredda frågor 
        (t.ex. obetalda avgifter). Avlägsnandet utförs en gång om året.</p>
      </div>
      <div id="kallor" class="content-section">
        <h2>9. Källor till personuppgifterna</h2>
        <p>Biblioteksanvändaren ger uppgifterna. Användaren kan även själv uppdatera en del av registrets uppgifter via bibliotekets nättjänst 
        på adressen www.helmet.finna.fi. Uppdateringen förutsätter användarnummer och en personlig PIN-kod.</p>
        <p>De (adress)uppgifter användaren uppgett kan jämföras med och uppdateras enligt uppgifterna i befolkningsdatasystemet.</p>
      </div>
      <div id="information" class="content-section">
        <h2>10. Information till den registrerade </h2>
        <p>Användaren får ett bibliotekskort där det bl.a. finns information om den webbadress där man hittar registerbeskrivningen, 
        användningsreglerna samt stadsbibliotekens kontaktuppgifter.</p>
        <p>Registerbeskrivningen och användningsreglerna finns att få på alla bibliotek inom Esbo, Grankulla, Helsingfors och Vanda 
        stadsbibliotek.</p>
      </div>
   </div>
</div>
