<? $this->headTitle($this->translate('Kundens ansvar för biblioteksavgifterna')); $this->content()->setHeading($this->translate('Kundens ansvar för biblioteksavgifterna'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Enligt bibliotekets låneregler är du som innehavare av kortet ansvarig för allt material som lånats på kortet samt för alla avgifter som uppkommit. 
        <strong>Ifall bibliotekskortet försvunnit är du ansvarig för alla lån och avgifter som registrerats innan anmälan gjorts att kortet försvunnit.</strong> Ifall ditt bibliotekskort 
        försvunnit eller stulits anmäl detta omedelbart till biblioteket.</p>
        <p>Gör en brottsanmälan om ditt kort har missbrukats och uppge samtidigt den materiella skada som uppstått. Kontakta det stadsbibliotek, vars material har lånats med ditt bibliotekskort.</p>
        <p>Kontrollera om din försäkring täcker den materiella skadan. Sök ersättning och betala skulden till biblioteket. Bibliotekets tillgodohavande kan även betalas på avbetalning enligt 
        de villkor biblioteket fastställer.</p>
      </div>
     <div id="sok-befrielse" class="content-section">
        <h2>Sök befrielse från att betala skulden</h2>
        <p>Du kan ansöka om befrielse från eller en nedsättning av de avgifter biblioteket kräver dig på genom att göra en fritt formulerad ansökan.</p>
        <p>Ur ansökan bör framgå den sökandes eller eventuell borgensmans namn, personbeteckning, adress och telefonnummer. Dessutom krävs uppgifter om det material och de avgifter 
        biblioteket kräver in samt en redogörelse för vad som hänt och eventuella motiveringar för ansökan. Från fall till fall kan det krävas utredning över sökandes ekonomiska 
        situation, arbetslöshet, sjukdom eller över andra omständigheter den sökande vill åberopa.</p>
        <p>Vid brott och då kortet missbrukats bifogas till ansökan om befrielse en kopia av brottsanmälan samt av försäkringsbolagets beslut. Ifall stölden skett i skolan/ på arbetsplatsen 
        bifogas rektors/arbetsgivarens utlåtande om hur förvaringen av personlig egendom är ordnad och vilka direktiv som getts.</p>
        <p>Beslut om befrielse görs från fall till fall. Beslutet är beroende av omständigheterna och av övriga faktorer som inverkar på ärendet och är antingen befriande, delvis 
        befriande eller ett avslag. Sökande får beslutet skriftligen.</p>
      </div>
      <div id="esbo" class="content-section">
        <h2>Esbo</h2>
        <p>All personal vid Esbo stadsbibliotek kan själva avgöra om materialets betalningsbefrielse upp till 30 euro.</p>
        <p>Alla betalningsbefrielseansökningar som är över 30 euro behandlas centrerat för alla Esbo-biblioteken av Edwin Tong. Edwin Tong nås i första hand via epost 
        <a href="mailto:edwin.tong@espoo.fi">edwin.tong@espoo.fi</a> och han ger ytterligare information om t.ex. eventuella nödvändiga dokument. Om du behöver prata om saken omedelbart per 
        telefon kan du ringa kontorstid till numret <a href="tel:0438252911">043 825 2911</a> och ha bibliotekskortets nummer nära till hands.</p>
      </div>
      <div id="helsingfors" class="content-section">
        <h2>Helsingfors</h2>
        <p>Ansökan riktas till Helsingfors stadsbibliotek.</p>
        <p>Tilläggsinformation fås från huvudbibliotekets inkassoavdelning, som sköter dessa ärenden. Tel. <a href="tel:0931085307">09 31085307</a>.</p>
        <p>Ansökan om befrielse skickas till följande adress:</p>
        <p>Helsingfors stads registratorskontor<br>
        Stadsbibliotek<br>
        PB 10<br>
        00099 HELSINGFORS STAD</p>
        <p>E-postadress: <a href="mailto:helsinki.kirjaamo@hel.fi">helsinki.kirjaamo@hel.fi</a>.<br>
        I E-postens fält för ämne skriv först KIR och sedan ämnet</p>
      </div>
      <div id="grankulla" class="content-section">
        <h2>Grankulla</h2>
        <p>Ansökan riktas till Grankulla bibliotek. Ansökan skickas till adressen:</p>
        <p>Grankulla stad<br>
        Registraturen<br>
        Grankulla stadsbibliotek<br>
        Grankullavägen 10<br>
        02700 Grankulla</p>
        <p>E-post: <a href="mailto:kirjaamo@kauniainen.fi">kirjaamo@kauniainen.fi</a></p>
      </div>
      <div id="vanda" class="content-section">
        <h2>Vanda</h2>
        <p>Ansökningar som gäller befrielse skickas till adressen:</p>
        <p>E-post: <a href="mailto:kirjasto.perinta@vantaa.fi">kirjasto.perinta@vantaa.fi</a>.</p>
        <p>Adressen:</p>
        <p>Perintä / Tikkurilan kirjasto / Aineiston elinkaari<br>
        PL 20<br>
        01030 Vantaan kaupunki</p>
        <p>Telefonnumer: <a href="tel:0505707776">050 570 7776</a>.</p>
      </div>
   </div>
</div>
