<p><img alt="h_asiakas.jpg" border="0" src="/download/noname/{9148F415-FBCC-477D-81E2-1306C8DD77E3}/10922">
</p><p></p><p>
  <a href="/fi-FI/content/115445/1" target="_top">Selkokielinen kirjaston esittely</a>
</p><p></p>
<ul class="bullet-list">
  <li>
    <a href="/fi-FI/content/37/1" target="_top">Kirjastokortti ja lainaaminen</a>
  </li>
  <li>
    <a href="/fi-FI/content/163229/1" target="_top">Käyttösäännöt selkokielellä</a>
    <span face="">&nbsp;</span>
  </li>
  <li>
    <a href="/fi-FI/content/37540/1" target="_top">Käyttösäännöt yleiskielellä</a>
  </li>
  <li>
    <a href="/fi-FI/Kirjastot_ja_palvelut/Omatoimikirjastot" target="_top">Omatoimikirjastojen käyttösäännöt</a>
  </li>
  <li>
    <a href="http://www.helmet.fi/fi-FI/Info/Asiakkaana_kirjastossa/Asiakastietokoneiden_kayttosaannot(943)">Asiakaskoneiden käyttösäännöt</a>
  </li>
  <li>
    <span face="">
      <a href="/fi-FI/content/105340/1" target="_top">Henkilöllisyystodistukset</a>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span>
  </li>
  <li>
    <a href="/fi-FI/content/37588/1" target="_top">Laina-ajat ja maksut</a>
  </li>
  <li>
    <a href="/fi-FI/content/9917/1" target="_top">Asiakkaan vastuu kirjastomaksuista</a>
  </li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietosuojaseloste_fin.html" target="_blank">Helmet-verkkokirjaston tietosuojaseloste (asiakasrekisteriseloste)</a>
  </li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietojarjestelmaseloste_fin.html" target="_blank">Julkisuuslain mukainen tietojärjestelmäseloste</a>
  </li>
  <li>
    <a href="https://www.helmet.fi/fi-FI/Info/Tietosuoja_ja_tietoa_sivustosta">Helmet.fi-sivuston tietosuojaseloste</a>
  </li>
</ul><p></p><ul>
  <li>
    <a href="https://youtube.com/playlist?list=PLB53fg1hM2JMGfVnmYlpOYsUJ3PBqOsjH" target="_blank">Ohjevideot Helmet-Youtubessa</a>
  </li>
</ul><p></p><h2>Tietoa muilla kielillä</h2><ul>
  <li>
    <a href="/fi-FI/content/243086/1" target="_top">Helmet-kirjaston selkokieliset käyttösäännöt viroksi käännettyinä</a>
  </li>
  <li>
    <a href="/fi-FI/content/99081/1" target="_top">Helmet-kirjaston esittely arabian kielellä</a>
  </li>
  <li>
    <a href="/download/noname/{597D0BB2-1513-4248-98E1-C3C5A9CEB278}/102894">Helmet-kirjaston selkokieliset käyttösäännöt arabiaksi käännettyinä (Word)</a>
  </li>
  <li>
    <a href="/fi-FI/content/93551/1" target="_top">Helmet-kirjaston esittely persian kielellä</a>
  </li>
  <li>
    <a href="/download/noname/{7ED0364F-1D68-4C77-8C1D-A64A7FC2CAAD}/101740">Helmet-kirjaston selkokieliset käyttösäännöt farsiksi käännettyinä (Word)</a>
  </li>
  <li>
    <a href="/fi-FI/content/99112/1" target="_top">Helmet-kirjaston esittely somalin kielellä</a>
  </li>
  <li>
    <a href="/download/noname/{873D4365-9329-41F5-AEEB-755513280189}/101459">Helmet-kirjaston selkokieliset käyttösäännöt somaliksi käännettyinä (PDF)</a>
  </li>
  <li>
    <a href="/fi-FI/content/234210/1" target="_top">Helmet-kirjaston esittely ukrainan kielellä</a>
  </li>
</ul>
