<img alt="h_asiakas.jpg" border="0" src="/download/noname/{9148F415-FBCC-477D-81E2-1306C8DD77E3}/10922">
</p><h2></h2><ul>
  <li>
    <a href="/sv-FI/content/175/3" target="_top">Bibliotekskort och lån</a>
  </li>
  <li>
    <a href="/sv-FI/content/166304/3" target="_top">Användningsregler på lättläst svenska</a>
  </li>
  <li>
    <a href="/sv-FI/content/37596/3" target="_top">Användningsregler på standardsvenska</a>
  </li>
  <li>
    <a href="/sv-FI/Bibliotek_och_tjanster/Meroppna_bibliotek" target="_top">Användningsregler för meröppetbiblioteken</a>
  </li>
  <li>
    <a href="/sv-FI/content/105341/3" target="_top">Identitetsbevis</a>
  </li>
  <li>
    <a href="/sv-FI/content/37611/3" target="_top">Lånetider och avgifter</a>
  </li>
  <li>
    <a href="/sv-FI/content/9918/3" target="_top">Kundens ansvar för biblioteksavgifterna</a>
  </li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietosuojaseloste_swe.html" target="_blank">Dataskyddsbeskrivning för&nbsp;webbibliotekstjänsten Helmet&nbsp;(kundregisterbeskrivning)</a>
  </li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietojarjestelmaseloste_swe.html" target="_blank">Registerbeskrivning av informationssystemet enligt offentlighetslagen</a>
  </li>
  <li>
    <a href="/sv-FI/content/989/3" target="_top">Dataskyddsbeskrivning för Helmet.fi</a>
  </li>
</ul><p>
  <br>
  <a href="https://youtube.com/playlist?list=PLB53fg1hM2JMGfVnmYlpOYsUJ3PBqOsjH" target="_blank">​Videoanvisningar på Helmets Youtube-kanal</a>
