<? $this->headTitle($this->translate('Asiakkaan vastuu kirjastomaksuista')); $this->content()->setHeading($this->translate('Asiakkaan vastuu kirjastomaksuista'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Kirjaston käyttösääntöjen mukaan olet kirjastokortin haltijana vastuussa kaikesta kortillasi lainatusta aineistosta ja kertyneistä maksuista. <strong>Kirjastokortin 
        katoamistapauksessa olet vastuussa kaikesta ennen katoamisilmoitusta tehdyistä lainoista ja maksuista</strong>. Jos kirjastokorttisi katoaa tai se varastetaan, tee siitä 
        viipymättä ilmoitus kirjastoon.</p>
        <p>Jos korttiasi on väärinkäytetty, tee rikosilmoitus ja anna tiedot aiheutetusta vahingosta. Ota yhteyttä siihen kaupunginkirjastoon, jonka aineistoa kortillasi on lainattu.</p>
        <p>Tarkista kattaako vakuutuksesi vahingon. Hae korvaus ja maksa kirjaston saatavat. Kirjaston saatavat voit maksaa myös osamaksulla kirjaston asettamin ehdoin.</p>
      </div>
     <div id="hae-vapautusta" class="content-section">
        <h2>Näin haet vapautusta maksuista</h2>
        <p>Kirjaston perimästä maksusta voit hakea vapautusta tai maksun alentamista vapaamuotoisella hakemuksella. Hakemuksessa tulee olla hakijan ja mahdollisen vastuuhenkilön nimi, 
        henkilötunnus, osoite ja puhelinnumero. Lisäksi vaaditaan tieto kirjaston perimästä aineistosta ja maksuista, selostus tapauksesta sekä hakemuksen perustelut. Tapauskohtaisesti 
        vaaditaan selvitykset taloudellisesta tilanteesta, työttömyydestä, sairaudesta yms. seikoista, joihin hakija haluaa vedota.</p>
        <p>Väärinkäyttö- ja rikostapauksissa vapautushakemukseen liitetään jäljennös rikosilmoituksesta ja vakuutusyhtiön päätös. Mikäli varkaus on tapahtunut koulussa/työpaikalla mukaan 
        liitetään rehtorin/työnantajan lausunto siitä, miten henkilökohtaisen omaisuuden säilytys on järjestetty ja mitä ohjeita on annettu.</p>
    </div>
    <div id="espoo" class="content-section">
        <h2>Espoo</h2>
        <p>Kaikkien Espoon kirjastojen vakituinen henkilökunta voi päättää alle 30 euroon asti aineistoa koskevista maksuvapautuksista.</p>
        <p>Yli 30 € koskevat maksuvapautuspyynnöt hoitaa kaikkien Espoon kirjastojen osalta Edwin Tong. Edwin Tongiin saa yhteyden ensisijaisesti sähköpostilla 
        <a href="mailto:edwin.tong@espoo.fi">edwin.tong@espoo.fi</a> ja hän antaa lisätietoa esim. mahdollisesti tarvittavista asiapapereista.</p>
        <p>Jos koet, että sinun on välttämätöntä saada keskustella asiasta ensin puhelimitse, soita virka-aikana numeroon <a href="tel:0438252911">043 825 2911</a> 
        ja pidä kirjastokorttisi numero saatavilla.</p>
    </div>
    <div id="helsinki" class="content-section">
        <h2>Helsinki</h2>
        <p>Hakemus osoitetaan Helsingin kaupunginkirjastolle. Vapautusta koskeva päätös on tapauskohtainen. Se on joko vapauttava, osittain vapauttava tai kielteinen riippuen 
        olosuhteista ja muista asiaan vaikuttavista tekijöistä. Päätöksestä ilmoitetaan hakijalle kirjallisesti.</p>
        <p>Lisätietoja saat pääkirjaston perinnästä numerosta 09 31085307.</p>
        <p>Vapautuksia koskevat hakemukset lähetetään osoitteeseen:</p>
        <p>Helsingin kaupunki<br>
        Kirjaamo<br>
        Kaupunginkirjasto<br>
        PL 10<br>
        00099 Helsingin kaupunki</p>
        <p>Sähköpostilla: <a href="mailto:helsinki.kirjaamo@hel.fi">helsinki.kirjaamo@hel.fi</a></p>
        <p>Sähköpostin Aihe-kentän alkuun tulee kirjoittaa KIR ja sitten vasta aihe.</p>
    </div>
    <div id="kauniainen" class="content-section">
        <h2>Kauniainen</h2>
        <p>Hakemus osoitetaan Kauniaisten kaupunginkirjastolle.</p>
        <p>Vapautusta koskeva päätös on tapauskohtainen. Se on joko vapauttava, osittain vapauttava tai kielteinen riippuen olosuhteista ja muista asiaan vaikuttavista tekijöistä. 
        <p>Päätöksestä ilmoitetaan hakijalle kirjallisesti.</p>
        <p>Vapautuksia koskevat hakemukset lähetetään osoitteeseen:</p>
        <p>Kauniaisten kaupunki<br>
        Kirjaamo<br>
        Kauniaisten kaupunginkirjasto<br>
        Kauniaistentie 10<br>
        02700 Kauniainen</p>
        <p>S-posti: <a href="mailto:kirjaamo@kauniainen.fi">kirjaamo@kauniainen.fi</a></p>
    </div>
    <div id="vantaa" class="content-section">
        <h2>Vantaa</h2>
        <p>Vapautusta koskeva päätös on tapauskohtainen, se on joko vapauttava, osittain vapauttava tai kielteinen riippuen olosuhteista ja muista asiaan vaikuttavista tekijöistä.
        Vapautuksia koskevat hakemukset lähetetään osoitteeseen:</p>
        <p>Sähköposti: <a href="mailto:kirjasto.perinta@vantaa.fi">kirjasto.perinta@vantaa.fi</a></p>
        <p>Postiosoite:</p>
        <p>Perintä / Tikkurilan kirjasto<br>
        PL 20<br>
        01030 Vantaan kaupunki</p>
        <p>Lisätietoja saa Vantaan perinnän numerosta <a href="tel:0505707776">050 570 7776</a>.</p>
      </div>
   </div>
</div>
