<img alt="h_asiakas.jpg" border="0" src="/download/noname/{9148F415-FBCC-477D-81E2-1306C8DD77E3}/10922">
</p><p></p>
<ul>
  <li>
    <a href="/en-US/content/950/2" target="_top">Library card and loans</a>
  </li>
  <li>
    <a href="http://www.helmet.fi/Preview/en-US/Info/Using_the_library/HelMet_library_user_regulations(37616)" target="_top">User regulations</a>
  </li>
  <li>
    <a href="/en-US/Libraries_and_services/Selfservice_libraries" target="_top">User regulations for self-service libraries</a> &nbsp;&nbsp;</li>
  <li>
    <a href="/en-US/content/105342/2" target="_top">Identity cards</a>
  </li>
  <li>
    <a href="http://www.helmet.fi/Preview/en-US/Info/Using_the_library/Loan_periods_and_fees(37613)">Loan periods and fees&nbsp;</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
  <li>
    <a href="/en-US/content/9919/2" target="_top">Customer's responsibility for library fees</a>
  </li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietosuojaseloste.html" target="_blank">Privacy statement of Helmet online library service (customer register)</a>&nbsp;</li>
  <li>
    <a href="https://luettelo.helmet.fi/screens/tietojarjestelmaseloste.html" target="_blank">Description of information system provided by act on the openness of government activities</a>
  </li>
  <li>
    <a href="/en-US/content/988/2" target="_top">Privacy statement of Helmet.fi website</a>
  </li>
</ul>