<? $this->headTitle($this->translate('Asiakasrekisteriseloste')); $this->content()->setHeading($this->translate('Asiakasrekisteriseloste'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>EU:n yleinen tietosuoja-asetus (2016/679)</p>
        <p>25.5.2018</p>
      </div>
     <div id="nimi" class="content-section">
        <h2>1. Rekisterin nimi</h2>
        <p>Helmet-kirjastojen asiakasrekisteri</p>
      </div>
      <div id="pitaja" class="content-section">
        <h2>2. Rekisterinpitäjä</h2>
        <p>Espoo: Espoon kaupunki</p>
        <p>Helsinki: kirjastopalvelujen johtaja</p>
        <p>Kauniainen: Kauniaisten kaupunki</p>
        <p>Vantaa: opetuslautakunta</p>
      </div>
      <div id="vastuuhenkilo" class="content-section">
        <h2>3. Rekisterin vastuuhenkilö</h2>
        <p>Espoo: kirjastopalveluiden johtaja</p>
        <p>Helsinki: kirjastopalvelujen johtaja</p>
        <p>Kauniainen: kirjastonjohtaja</p>
        <p>Vantaa: kirjastopalveluiden johtaja</p>
      </div>
      <div id="yhteyshenkilo" class="content-section">
        <h2>4. Rekisterin yhteyshenkilö</h2>
        <p>Espoo: kirjastopalvelupäällikkö, Espoon kaupunginkirjasto</p>
        <p>Helsinki: palveluesimies, Helsingin kaupunginkirjasto, Pasilan kirjasto</p>
        <p>Kauniainen: informaatikko, Kauniaisten kaupunginkirjasto</p>
        <p>Vantaa: erikoiskirjastovirkailija, Vantaan kaupunginkirjasto</p>
        <h3>Yhteystiedot</h3>
        <p>Espoon kaupunki<br>
        Espoon kirjaamo<br>
        PL 1<br>
        02070 ESPOON KAUPUNKI</p>
        <p>Helsingin kaupunki<br>
        Kirjaamo<br>
        PL 10 (Pohjoisesplanadi 11-13)<br>
        00099 Helsingin kaupunki</p>
        <p>Kauniaisten kaupunki<br>
        Kirjaamo<br>
        PL 52 (Kauniaistentie 10)<br>
        02701 Kauniainen</p>
        <p>Vantaan kaupunki<br>
        Kirjaamo<br>
        Asematie 7<br>
        01300 Vantaa</p>
      </div>
      <div id="kasittelyn-tarkoitus" class="content-section">
        <h2>5. Henkilötietojen käsittelyn tarkoitukset ja käsittelyn oikeusperuste</h2>
        <p>Rekisterin henkilötietojen käsittelyn tarkoituksena on kirjastopalveluiden järjestäminen. 
        Kirjastot käyttävät rekisteriä lainauksenvalvontaan, perintään, tilastointiin, viestintään, verkko- ja mobiilipalveluiden, 
        omatoimikirjastojen ja muiden kirjastopalveluiden tarjoamiseen sekä käyttäjien tunnistautumiseen.</p>
        <p>Käsittelyn oikeusperuste:</p>
        <p>EU:n yleisen tietosuoja-asetuksen 6 artiklan c-kohta, käsittely on tarpeen rekisterinpitäjän lakisääteisen velvoitteen noudattamiseksi.</p>
        <p>Keskeinen lainsäädäntö:</p>
        <p>EU:n yleinen tietosuoja-asetus (679/2016)<br>
        Laki yleisistä kirjastoista (1492/2016)<br>
        Laki viranomaisten toiminnan julkisuudesta (621/1999)<br>
        Tietosuojalaki (1050/2018)</p>
      </div>
      <div id="tietosisalto" class="content-section">
        <h2>6. Rekisterin tietosisältö</h2>
        <p>Rekisteriin tallennetaan rekisteröidystä seuraavat tiedot:</p>
        <ul class="list-bullets">
            <li>nimi, henkilötunnus, asiakastunnus, tunnusluku salattuna, osoite, puhelinnumero, sähköpostiosoite, syntymäaika, asiakasryhmä (esim. lapsi, aikuinen, kotipalveluasiakas, laitos)</li>
            <li>tilastollista käsittelyä varten: sukupuoli</li>
            <li>asiakaspostin lähettämistä varten: kielivalinta ja lähetystapa</li>
            <li>lainauksenvalvonnan tapahtumatiedot, tiedot voimassaolevista lainoista ja varatusta aineistosta</li>
            <li>selvittämättömät asiat (esim. maksamattaomat maksut) ja niihin liittyvät huomautukset</li>
        </ul>
        <p>Alle 15-vuotiaan lapsen vastuuhenkilönä toimivan henkilön sekä laitoksen tai muun yhteisön yhteyshenkilönä toimivan henkilön henkilötiedot 
        rekisteröidään vastaavasti.</p>
        <p>Osa rekisteritiedoista on asiakkaan käytössä kirjastojen verkkopalvelussa osoitteessa helmet.finna.fi. Asiakas tarvitsee asiakastunnuksen ja 
        henkilökohtaisen tunnusluvun tietojensa katseluun.</p>
      </div>
        <div id="luovutukset" class="content-section">
        <h2>7. Henkilötietojen säännönmukaiset luovutukset</h2>
        <p>Kukin kaupunginkirjasto huolehtii omistamansa palauttamattoman aineiston perinnästä. Perintätoimistolle luovutetaan linjasiirtona kerran 
        viikossa tiedot täysi-ikäisistä rekisteröidyistä, joiden lainaama aineisto on palauttamatta 60 vuorokauden kuluttua eräpäivästä. Tiedosto 
        sisältää rekisteröidyn nimen, osoitteen, puhelinnumeron ja henkilötunnuksen sekä eräpäivä-, nimeke- ja hintatiedot palauttamattomasta aineistosta.</p>
        <p>Henkilötietoja käsittelevät kirjaston tarjoamien ja asiakkaan käyttöön ottamien palveluiden toimittajat:</p>
        <ul class="list-bullets">
            <li>kirjastojärjestelmän ohjelmistotoimittaja</li>
            <li>kirjastojärjestelmän käyttöpalvelun toimittaja</li>
            <li>lainaus- ja palautusautomaattien toimittajat</li>
            <li>omatoimikirjastojen toimittajat</li>
            <li>verkkopalveluiden toimittajat</li>
            <li>mobiilipalveluiden toimittajat</li>
            <li>verkkomaksupalvelun toimittaja</li>
            <li>e-aineistojen toimittajat</li>
            <li>asiakaskäyttöön tarkoitettujen laitteiden toimittajat</li>
        </ul>
        <p>Anonymisoitua käyttödataa luovutetaan:</p>
        <ul class="list-bullets">
            <li>suosittelupalveluiden toteuttamiseen</li>
            <li>tilastointiin ja tutkimukseen</li>
        </ul>
        <p>Edellä mainituista palveluista on solmittu sopimukset toimittajien kanssa.</p>
        <p>Rekisterin henkilötietoja voidaan luovuttaa tahoille, joilla on lain mukaan oikeus 
        saada tiedot, esimerkiksi kaupungin sosiaalihuollolle lastensuojelulain perusteella tai poliisille poliisilain perusteella.</p>
      </div>
     <div id="sailytys" class="content-section">
        <h2>8. Tietojen säilytysajat</h2>
        <p>Asiakkaan ennakkotietoina kirjaston verkkopalvelussa rekisteröimät henkilötiedot poistetaan kolmen kuukauden kuluttua, jos 
        asiakas ei ole noutanut kirjastokorttiaan.</p>
        <p>Rekisteristä poistetaan asiakastiedot, joita asiakas ei ole käyttänyt kolmeen vuoteen ja joihin ei liity selvittämättömiä asioita 
        (esim. maksamattomia maksuja). Poistot tehdään kerran vuodessa.</p>
      </div>
      <div id="tietolahteet" class="content-section">
        <h2>9. Henkilötietojen tietolähteet</h2>
        <p>Tiedot saadaan asiakkaalta. Asiakas voi myös itse päivittää osan rekisterin asiakastiedoista kirjastojen verkkopalvelussa 
        osoitteessa helmet.finna.fi.</p>
        <p>Päivittäminen edellyttää, että asiakkaalla on asiakastunnus ja henkilökohtainen tunnusluku.</p>
        <p>Asiakkaan antamat (osoite)tiedot voidaan tarkistaa ja päivittää väestötietojärjestelmästä.</p>
      </div>
      <div id="informointi" class="content-section">
        <h2>10. Rekisteröidyn informointi</h2>
        <p>Asiakkaalle annettavassa kirjastokortissa on tieto verkkosivusta, josta on linkki rekisteriselosteeseen, käyttösääntöihin 
        sekä kaupunginkirjastojen yhteystietoihin.</p>
        <p>Rekisteriselosteen ja käyttösäännöt voi pyytää mistä tahansa Espoon, Helsingin, Kauniaisten tai Vantaan kaupunginkirjaston toimipisteestä.</p>
        <p></p>
      </div>
   </div>
</div>
