<? $this->headTitle($this->translate('Customer register')); $this->content()->setHeading($this->translate('Customer register'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>EU General Data Protection Regulation (2016/679)</p>
        <p>25.5.2018</p>
      </div>
     <div id="name" class="content-section">
        <h2>1. Name of register</h2>
        <p>Customer register of the Helmet libraries</p>
      </div>
      <div id="controller" class="content-section">
        <h2>2. Register controller</h2>
        <p>Espoo: City of Espoo</p>
        <p>Helsinki: Director of Library Services</p>
        <p>Kauniainen: City of Kauniainen</p>
        <p>Vantaa: Education Committee</p>
      </div>
      <div id="responsible" class="content-section">
        <h2>3. Person responsible for the data file</h2>
        <p>Espoo: Director of Library Services</p>
        <p>Helsinki: Director of Library Services</p>
        <p>Kauniainen: Chief Librarian</p>
        <p>Vantaa: Director of Library Services</p>
      </div>
      <div id="contact-person" class="content-section">
        <h2>4. Contact person for the data file</h2>
        <p>Espoo: Library Service Manager, Espoo City Library</p>
        <p>Helsinki: Head of Public Services, Helsinki City Library, Pasila Library</p>
        <p>Kauniainen: Informatician, Kauniainen City Library</p>
        <p>Vantaa: Special Library Assistant, Vantaa City Library</p>
        <h3>Contact information:</h3>
        <p>City of Espoo<br>
        Registrar's Office<br>
        PO BOX 1<br>
        FI-02070 CITY OF ESPOO</p>
        <p>City of Helsinki<br>
        Registrar's Office<br>
        PO BOX 10 (Pohjoisesplanadi 11-13)<br>
        FI-00099 City of Helsinki</p>
        <p>City of Kauniainen<br>
        Registrar's Office<br>
        PO BOX 52 (Kauniaistentie 10)<br>
        FI-02701 City of Kauniainen</p>
        <p>City of Vantaa<br>
        Registrar's Office<br>
        Asematie 7<br>
        FI-01300 City of Vantaa</p>
      </div>
      <div id="purpose" class="content-section">
        <h2>5. Purpose and legal grounds for processing personal data</h2>
        <p>Personal data recorded in the register is processed for the purpose of organising library services. Libraries use the register for 
        the purposes of monitoring circulation, debt collection, statistics, communications, providing online and mobile services as well as 
        self-service library and other library services and user identification.</p>
        <p>Legal grounds for processing personal data:</p>
        <p>According to article 6, point c, of the EU General Data Protection Regulation, processing is necessary for compliance with a legal 
        obligation to which the controller is subject.</p>
        <p>Central legislation:</p>
        <p>EU General Data Protection Regulation (679/2016)<br>
        Public Libraries Act (1492/2016)<br>
        Act on the Openness of Government Activities (621/1999)<br>
        Data Protection Act (1050/2018)</p>
      </div>
      <div id="data-content" class="content-section">
        <h2>6. The register’s data content</h2>
        <p>The following personal information will be recorded in the data file:</p>
        <ul class="list-bullets">
            <li>name, personal ID, customer ID, encrypted PIN code, address, phone number, e-mail address, date of birth, customer group (e.g. child, adult, home service customer, institution)</li>
            <li>for statistic purposes: gender</li>
            <li>for sending out customer mail: language selection and preferred mode of communication</li>
            <li>circulation events, information on current loans and reserved items</li>
            <li>unresolved issues (e.g. open payments) and related notifications</li>
        </ul>
        <p>Personal data of a person acting as the person responsible for a child under the age of 15 and of a person acting as the 
        contact person of an institution or other community will be recorded in a corresponding manner.</p>
        <p>Customers can access some of the data via the library online service at helmet.fi. Customers will need a user ID and a personal PIN 
        code to view their personal data.</p>
      </div>
        <div id="sharing" class="content-section">
        <h2>7. Regular sharing of the personal data</h2>
        <p>Each City Library sees to the debt collection on loaned items that have not been returned. Data on registered adults who have not y
        returned loaned items within 60 days from the due date will be handed over to a debt collection agency once a week as a line transfer. 
        The transferred file will include the name, address, phone number and personal ID of the person registered, as well as the due date and 
        title and price information of the unreturned items.</p>
        <p>Personal data will be processed by the following suppliers of services that are provided by the library and used by the customer:</p>
        <ul class="list-bullets">
            <li>library management system software provider</li>
            <li>library management system’s hosting service provider</li>
            <li>self check-out and return machines’ providers</li>
            <li>self-service library systems’ providers</li>
            <li>online service providers</li>
            <li>mobile service providers</li>
            <li>online payment service provider</li>
            <li>e-material providers</li>
            <li>providers of devices and equipment intended for customer use</li>
        </ul>
        <p>Anonymised data will be used for:</p>
        <ul class="list-bullets">
            <li>recommendation services</li>
            <li>statistical and research purposes</li>
        </ul>
        <p>Contracts have been signed for the aforementioned services with the service providers.</p>
        <p>Personal data in the data file may be disclosed to parties who have a legal right to obtain the data, such as the city’s social 
        welfare under the Child Welfare Act or the police under the Police Act.</p>
      </div>
     <div id="retention" class="content-section">
        <h2>8. Data retention time</h2>
        <p>Personal details submitted in advance by the customer in the library’s customer register via the library online service will be 
        removed if the customer has not picked up their library card in three months.</p>
        <p>Personal details that have not been used by the customer for three years and that do not involve unresolved issues 
        (e.g. open payments) will be removed from the customer register. Data is removed from the register once a year.</p>
      </div>
      <div id="information-sources" class="content-section">
        <h2>9. Information sources for personal data</h2>
        <p>Personal data is acquired from the customer. The customer can update some of their personal data themself in the library’s 
        customer register via the library online services at helmet.finna.fi. Updating the data requires that the customer has a user ID and PIN code.</p>
        <p>(Address) Details provided by the customer can be verified and updated through the Finnish Population Information System.</p>
      </div>
      <div id="informing" class="content-section">
        <h2>10. Informing the people registered </h2>
        <p>The library card provided to the customer includes information on the website that features links to the description of the personal 
        data file, user regulations and contact information of the City Libraries.</p>
        <p>Description of the personal data file and user regulations can be requested from any library in Espoo, Helsinki, Kauniainen or Vantaa.</p>
      </div>
   </div>
</div>

