<? $this->headTitle($this->translate("Customer's responsibility for library fees")); $this->content()->setHeading($this->translate("Customer's responsibility for library fees"));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>According to library rules, as the holder of a library card you are responsible for all materials borrowed with the library card and for the accumulated fees. In the event of losing 
        your library card, you are responsible for all loans and fees prior to invalidation of the card. If you lose your library card or it is stolen, inform the library immediately.</p>
        <p>In case your library card is misused, report the offence to the police and give all relevant information concerning the offence. Please contact that city’s library, from which the
        material you have loaned with your library card originates (Espoo City Library, Helsinki City Library, Kauniainen City Library or Vantaa City Library).</p>
        <p>Check whether your insurance covers the damage. Apply for compensation and pay due fees to the library. You can pay due fees also in instalments according to the conditions set by the library.</p>
        <p>You can apply for exemption from paying the due fees.</p>
      </div>
     <div id="apply-for-exemption" class="content-section">
        <h2>Apply for exemption from paying the due fees</h2>
        <p>You can ask for exemption from library's collected fees or for a reduction on library's fees with an informal letter of application. The application must state the name of the 
        applicant and a possible guarantor, social security number, address and telephone number. In addition all relevant information on materials and fees collected by the library, 
        description of the events as well as reasons for the application. Library can request case-specifically a declaration of one's financial situation, unemployment, sickness or any 
        other such matters on which the applicant appeals to.</p>
        <p>In cases of misuse and criminal case a copy of the report of the offence and the resolution of the insurance company must be included in the application. In case the theft 
        has taken place at school or workplace a declaration by the headmaster or by the employer must be given as to the way in which personal property is stored, safeguarded and what 
        are the relevant guidelines.</p>
        <p>Resolution of the exemption is case specific. It is either an acquittal, a partial acquittal or negative 
        depending on each individual situation and other relevant matters. The decision is given in writing to the applicant.</p>
      </div>
      <div id="espoo" class="content-section">
        <h2>Espoo</h2>
        <p>Exemptions under 30 € can be decided in all libraries in Espoo.</p>
        <p>If you want to apply for exemptions from charges over 30 €, please contact Edwin Tong, <a href="mailto:edwin.tong(at)espoo.fi">edwin.tong(at)espoo.fi</a>, for details. 
        If you want to discuss the issue by phone, call <a href="tel:0438252911">043 825 2911</a> during office hours. Be prepared to give the number on your library card.</p>
      </div>
      <div id="helsinki" class="content-section">
        <h2>Helsinki</h2>
        <p>The application is to be directed to Helsinki City Library. 
        Additional information is given from the central collecting office. Telephone number is: <a href="tel:0931085307">09 310 85307</a>.</p>
        <p>Address for the exemption applications is:</p>
        <p>Helsingin kaupunki<br>
        Kirjaamo<br>
        Kaupunginkirjasto<br>
        PL 10<br>
        00099 Helsingin kaupunki</p>
        <p>Per email: <a href="mailto:helsinki.kirjaamo@hel.fi">helsinki.kirjaamo@hel.fi</a>. In the subject field, please type KIR before the subject.</p>
      </div>
      <div id="kauniainen" class="content-section">
        <h2>Kauniainen</h2>
        <p>The application is to be directed to Kauniainen City Library. Address for the exemption applications is:</p>
        <p>Kauniaisten kaupunki<br>
        Kirjaamo<br>
        Kauniaisten kaupunginkirjasto<br>
        Kauniaistentie 10<br>
        02700 Kauniainen</p>
        <p>E-mail: <a href="mailto:kirjaamo@kauniainen.fi">kirjaamo@kauniainen.fi</a></p>
      </div>
      <div id="vantaa" class="content-section">
        <h2>Vantaa</h2>
        <p>Send the application for exemption to:</p>
        <p>Perintä / Tikkurilan kirjasto<br>
        PL 20<br>
        01030 Vantaan kaupunki</p>
        <p>Telephone number:<a href="tel:0505707776">050 570 7776</a>.</p>
        <p>e-mail: <a href="mailto:kirjasto.perinta@vantaa.fi">kirjasto.perinta@vantaa.fi</a></p>
      </div>
   </div>
</div>


