<? $this->headTitle($this->translate("Kirjastojen blogit")); $this->content()->setHeading($this->translate("Kirjastojen blogit"));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Pääkaupunkiseudun kirjastoilla on omia blogeja, joista voit etsiä lukuvinkkejä ja kirjasuosituksia tai tutustua 
        kirjastojen toimintaan.</p>
      </div>
     <div id="kirjallisuudesta" class="content-section">
        <h2>Kirjallisuudesta</h2>
        <h3><a href="http://kirjavasatama.espoonkirjastot.fi/blogi/espoonfantasia/" target="_blank" aria-label="Espoon fantasia. 
        Linkki aukeaa uudessa ikkunassa.">Espoon fantasia</a></h3>
        <p>Espoon kaupunginkirjaston fantasiaryhmäläiset ovat fantasia- ja tieteiskirjallisuuteen erikoistuneita asiantuntijoita. Blogissa he 
        avaavat työtään niin asiakkaille kuin kirjastokollegoille. He puhuvat työkseen kirjoista, joten täällä on pinoittain kirjavinkkejä.</p>
        <h3><a href="http://kirjavasatama.espoonkirjastot.fi/lukijalta-lukijalle/" target="_blank" 
        aria-label="Lukijalta lukijalle. Linkki aukeaa uudessa ikkunassa.">Lukijalta lukijalle</a></h3>
        <p>Espoon kaupunginkirjasto kokoaa yhteen juttuja kirjoittajille ja lukijoille. Lukijalta lukijalle on paikka hyville kirjoille sekä 
        muihin kirjoihin liittyville aiheille. Kirjoittamisestakin puhutaan. Betalukija-palvelussa lukemisen ammattilaiset lukevat 
        kirjastotyönsä ohessa harrastajakirjoittajien tekstejä ja antavat niistä palautetta.</p>
        
        <h3><a href="http://kirjasto.one/lukupiiri/" target="_blank" 
        aria-label="Lukupiiri.net -Kirjastojen lukupiirejä. Linkki aukeaa uudessa ikkunassa.">Lukupiiri.net -Kirjastojen lukupiirejä</h3></a>
        <p>Blogi kokoaa yhteen Vantaan kirjastoissa toimivien lukupiirien kuulumisia. Jutuissa esitellään kokoontumisten tulevia kirjoja ja 
        kerrotaan, mitä piiriläiset ovat kirjoista miettineet.</p>
        <h3><a href="http://kirjasto.one/suosittelija-blogi/" target="_blank" 
        aria-label="Suosittelija-blogi. Linkki aukeaa uudessa ikkunassa.">Suosittelija-blogi</a></h3>
        <p>Vantaan kaupunginkirjaston ylläpitämässä blogissa suositellaan kirjoja ja erilaisia verkkoaineistoja ajankohtaisista aiheista. 
        Blogia ei ole päivitetä enää.</p>
        <h3><a href="http://kirjasto.one/kirjallisuusterapia/" target="_blank" 
        aria-label="Tarinoiden lumo - Kirjallisuusterapiaa Vantaan kirjastoissa. Linkki aukeaa uudessa ikkunassa.">Tarinoiden lumo - 
        Kirjallisuusterapiaa Vantaan kirjastoissa</a></h3>
        <p>Blogista löydät kirjallisuusterapeuttisia lukusuosituksia, erilaisia kirjoituksia aiheesta sekä tietoa Vantaan kirjastoissa järjestettävistä '
        kirjallisuusterapeuttisista kirjoitus- ja lukupiireistä.</p>
        <h3><a href="http://kirjasto.one/runoklubi/" target="_blank" aria-label="Tiksin runoklubi. Linkki aukeaa uudessa ikkunassa.">Tiksin runoklubi</h3></a>
        <p>Tikkurilan kirjastossa kokoontuvan Runoklubin blogissa kerrotaan tulevista ja menneistä runotapahtumista sekä julkaistaan osallistujien 
        runoja.</p>
      </div>
      <div id="kirjastomaailmasta" class="content-section">
        <h2>Kirjastomaailmasta</h2>
        <h3><a href="http://kirjavasatama.espoonkirjastot.fi/" target="_blank" aria-label="Kirjava satama. Linkki aukeaa uudessa ikkunassa.">
        Kirjava satama. Espoon kaupunginkirjasto kokeilee ja katsoo tulevaisuuteen</a></h3>
        <p>Kirjastolaiset luotaavat kirjastoilmiöitä kahdessa blogiosiossa, 
        <a href="http://kirjavasatama.espoonkirjastot.fi/blogi/kirjaston-toiminta-ja-tulevaisuus/" target="_blank" 
        aria-label="Kirjaston toiminta ja tulevaisuus. Linkki aukeaa uudessa ikkunassa.">Kirjaston toiminta ja tulevaisuus</a> ja 
        <a href="http://kirjavasatama.espoonkirjastot.fi/blogi/designing-tomorrow-together/" target="_blank"
        aria-label="Designing tomorrow together. Linkki aukeaa uudessa ikkunassa.">Designing tomorrow together</a>. Jälkimmäinen on kokonaan 
        englanninkielinen ja suunnattu kansainvälisille yhteistyökumppaneille. Muitakin vieraita kieliä voi esiintyä.</p>
      </div>
   </div>
</div>


