<? $this->headTitle($this->translate('Digital support')); $this->content()->setHeading($this->translate('Digital support'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="what-is" class="content-section">
        <h2>What is digital support?</h2>   
        <p>Do you need help with various devices, programs or online services?</p>
        <p>Digital support is available in every library. You can ask for help in any library or participate in digital support events in the libraries and online.</p>
      </div>
      <div id="we-can-help" class="content-section">
        <h2>We can help you with the following:</h2>
        <ul class="list-bullets">
          <li>basic use of computers, the most common programs and the Internet</li>
          <li>use of tablet computers and smartphones</li>
          <li>searching for information</li>
          <li>using social media</li>
          <li>editing and saving digital images</li>
          <li>using e-books and other digital materials</li>
          <li>using the library’s online services</li>
          <li>using various other online services</li>
        </ul>
        <p>Digital support is available to anyone free of charge.</p>
        <p>We encourage everyone to learn and try new things. We will help you with your everyday problems with the digital world. 
        However, do not reveal your usernames and passwords to us. Our digital advisers will not write applications, make purchases or transfer money for you. 
        You are always responsible for your device and software during guidance.</p><p>Enter ry provides ICT tutoring for seniors. 
        <a href="https://www.entersenior.fi/yhdistys/en/" target="_blank">Sign up for tutoring through the Enter ry website</a>.</p>
      </div>
      <div id="appointment" class="content-section">
        <h2>Digital support by appointment</h2>
        <h3>Espoo</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/espoo/" target="_blank" aria-label="Enter ry's peer-to-peer digital support in Espoo. Link opens in a new window.">
        Enter ry's peer-to-peer digital support in Espoo.</a></p>
        <h3>Helsinki</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/helsinki/" target="_blank" aria-label="Enter ry's peer-to-peer digital support in Helsinki. Link opens in a new window.">
        Enter ry's peer-to-peer digital support in Helsinki.</a></p>
        <p>Book an appointment for digital support in Helsinki.</p>
        <ul class="list-bullets">
            <li><a href="https://outlook.office365.com/owa/calendar/Itkeskuksenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Itäkeskus Library. Link opens in a new window.">Itäkeskus Library</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto2@helsinginkaupunki.onmicrosoft.com/bookings/s/ljf7ZkG9kkOTx39NT2A_ng2" target="_blank"
            aria-label="Kallio Library. Link opens in a new window.">Kallio Library</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto1@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Pasila Library. Link opens in a new window.">Pasila Library</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Vuosaarenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank"
            aria-label="Pasila Library. Link opens in a new window.">Vuosaari Library</a></li>
        </ul>
        <h3>Kauniainen</h3>
        <p>Kauniainen City Library provides help with digital devices Mon–Fri. Book an appointment in advance by calling the library, tel. 050 411 6504 (1 hour / customer) or 
        check for drop in possibilities on the <a href="https://www.helmet.fi/en-US/Libraries_and_services/Kauniainen_library/Events">events page</a>.</p>
        <h3>Vantaa</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/vantaa/" target="_blank" aria-label="Enter ry's peer-to-peer digital support in Vantaa. Link opens in a new window.">
        Enter ry's peer-to-peer digital support in Vantaa.</a></p>
       </div>

       <div id="learn" class="content-section">
        <h2>Learn digital skills Online</h2>
        <p><a href="http://www.kirjastot.fi/digiopastus" target="_blank">Digital support websites under Kirjastot.fi</a> (in Finnish).</p>
       </div>
   </div>
</div>

