<? $this->headTitle($this->translate('Digistöd')); $this->content()->setHeading($this->translate('Digistöd'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="vad-ar" class="content-section">
        <h2>Vad är digistöd?</h2>   
        <p>Behöver du hjälp med att använda olika apparater, program och nättjänster?</p>
        <p>Du får stöd både genom att ställa frågor på biblioteket och på särskilda kurser eller andra program. Alla bibliotek ger digistöd.</p>
      </div>
      <div id="hjalp" class="content-section">
        <h2>Vad kan du få hjälp med?</h2>
        <p>Biblioteket visar hur olika apparater och elektroniska tjänster fungerar. Vi ger handledning i bl.a.</p>
        <ul class="list-bullets">
            <li>användning av dator, surfplatta och smarttelefon</li>
        	<li>användning av program, applikationer och internet</li>
        	<li>informationssökning</li>
        	<li>bibliotekets nättjänster och e-material</li>
        	<li>sociala medier och användning av e-post</li>
        	<li>att sköta ärenden på nätet på ett allmänt plan</li>
        </ul>
        <p>Bibliotekets digistöd är gratis och vem som helst kan delta.</p>
        <p>Vi hjälper dig med vardagens digitala problem. Vi uppmuntrar alla att lära sig och att pröva nytt.</p>
        <p>Digihandledarna sköter inga ansökningar, inköp eller bankärenden åt dig. Kom även ihåg att alla koder och nyckeltal är personliga. 
        Under handledningen är ansvaret för kundens egna apparater alltid hos kunden själv.</p>
     </div> 
     <div id="tidsbokning" class="content-section">
        <h2>Digistöd med tidsbokning</h2>
        <h3>Esbo</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/espoo/" target="_blank" aria-label="Enter ry:s närhandledning i Esbo. Länken öppnas i ett nytt fönster.">Enter ry:s närhandledning i Esbo</a></p>
        <h3>Grankulla</h3>
        <p>Närdigistöd med tidsbokning i Grankulla: Grankulla bibliotek ger digistöd vardagar. Boka tid på förhand på numret 050 411 6504 (1 h / kund).</p>
        <h3>Helsingfors</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/helsinki/" target="_blank" aria-label="Enter ry:s närhandledning i Helsingfors. Länken öppnas i ett nytt fönster.">
        Enter ry:s närhandledning i Helsingfors</a></p>
        <p>Närdigistöd med tidsbokning i Helsingfors</p>
        <ul class="list-bullets">
            <li><a href="https://outlook.office365.com/owa/calendar/Itkeskuksenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Östra centrums bibliotek. Länken öppnas i ett nytt fönster.">Östra centrums bibliotek</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto2@helsinginkaupunki.onmicrosoft.com/bookings/s/ljf7ZkG9kkOTx39NT2A_ng2" target="_blank"
            aria-label="Berghälls bibliotek. Länken öppnas i ett nytt fönster.">Berghälls bibliotek</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto1@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank"
            aria-label="Böle bibliotek. Länken öppnas i ett nytt fönster.">Böle bibliotek</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Vuosaarenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank"
            aria-label="Nordsjö bibliotek. Länken öppnas i ett nytt fönster.">Nordsjö bibliotek</a></li>
        </ul>
        <h3>Vanda</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/vantaa/" target="_blank" aria-label="Enter ry:s närhandledning i Vanda. Länken öppnas i ett nytt fönster.">
        Enter ry:s närhandledning i Vanda</a></p>
      </div>
      <div id="lar-sjalv" class="content-section">
        <h2>Lär dig på egen hand</h2>
        <p><a href="https://www.biblioteken.fi/digihandledning" target="_blank">Sidan för digital handledning på webbplatsen Biblioteken.fi.</a></p>
      </div>
   </div>
</div>
