<? $this->headTitle($this->translate('Digituki')); $this->content()->setHeading($this->translate('Digituki'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="mika-on-digituki" class="content-section">
        <h2>Mikä on digituki?</h2>   
        <p>Tarvitsetko apua erilaisten laitteiden, ohjelmien ja verkkopalveluiden käytössä?</p>
        <p>Digitukea annetaan sekä suoraan kirjastosta kysymällä että erikseen järjestetyissä tapahtumissa. Jokaisessa kirjastossa annetaan digitukea. </p>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/kesa/" target="_blank" 
        aria-label="Enter ry järjestää Helsingissä kesä- ja elokuussa 2023 digiopastusta ilman ajanvarausta, linkki aukeaa uudessa ikkunassa.">Enter ry järjestää Helsingissä kesä- ja elokuussa 2023 digiopastusta ilman ajanvarausta</a>. 
        Kesäopastus järjestetään Kampin palvelukeskuksessa.</p>
      </div>
      <div id="millaisissa-asioissa" class="content-section">
        <h2>Millaisissa asioissa voi saada opastusta?</h2>
        <p>Opastusta saa laitteiden ja verkkopalveluiden käytössä. Esimerkiksi:</p>
        <ul class="list-bullets">
            <li>tietokoneen, tabletin ja älypuhelimen käyttö</li>
            <li>ohjelmien, sovellusten ja internetin käyttö sekä tiedon etsiminen</li>
            <li>kirjaston verkkopalveluiden ja e-aineistojen käyttö</li>
            <li>sosiaalisen median ja sähköpostin käyttö</li>
            <li>sähköisen asioinnin verkkopalveluiden käyttö yleisesti</li>
         </ul>
         <p>Digituki on maksutonta, ja siihen voi osallistua kuka vain.</p>
         <p>Rohkaisemme oppimaan ja kokeilemaan. Autamme arjen digipulmissa, mutta tunnukset ja avainluvut ovat henkilökohtaisia. Digineuvojat eivät tee puolestasi hakemuksia,
         ostoja tai tilisiirtoja. Opastuksen aikana vastuu omasta laitteesta ja ohjelmistoista säilyy aina asiakkaalla itsellään.</p>
      </div>
      <div id="ajanvaraus" class="content-section">
        <h2>Digituki ajanvarauksella</h2>
        <h3>Espoo</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/espoo/" target="_blank" aria-label="Enter ry:n lähiopastukset Espoossa. Linkki aukeaa Enter ry:n sivulle.">
        Enter ry:n lähiopastukset Espoossa</a></p>
        <h3>Helsinki</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/helsinki/" target="_blank" aria-label="Enter ry:n lähiopastukset Helsingissä. Linkki aukeaa Enter ry:n sivulle.">
        Enter ry:n lähiopastukset Helsingissä</a></p>
        <p>Lähidigitukea järjestetään Helsingissä ajanvarauksella seuraavissa kirjastoissa:</p>
        <ul class="list-bullets">
            <li><a href="https://outlook.office365.com/owa/calendar/Itkeskuksenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Itäkeskuksen kirjaston varauskalenteri. Linkki aukeaa uudessa ikkunassa.">Itäkeskuksen kirjasto</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto2@helsinginkaupunki.onmicrosoft.com/bookings/s/ljf7ZkG9kkOTx39NT2A_ng2" target="_blank" 
            aria-label="Kallion kirjaston varauskalenteri. Linkki aukeaa uudessa ikkunassa." >Kallion kirjasto</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Kallionkirjasto1@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Pasilan kirjaston varauskalenteri. Linkki aukeaa uudessa ikkunassa.">Pasilan kirjasto</a></li>
            <li><a href="https://outlook.office365.com/owa/calendar/Vuosaarenkirjasto@helsinginkaupunki.onmicrosoft.com/bookings/" target="_blank" 
            aria-label="Vuosaaren kirjaston varauskalenteri. Linkki aukeaa uudessa ikkunassa.">Vuosaaren kirjasto</a></li>
        </ul>
        <h3>Vantaa</h3>
        <p><a href="https://www.entersenior.fi/opastus/lahiopastus/vantaa/" target="_blank" aria-label="Enter ry:n lähiopastukset Vantaalla. Linkki aukeaa Enter ry:n sivulle.">
        Enter ry:n lähiopastukset Vantaalla</a></p>
        <h3>Kauniainen</h3>
        <p>Lähidigitukea ajanvarauksella: Kauniaisten kirjasto antaa digitukea arkisin. Varaa aika etukäteen etukäteen numerosta 050 411 6504 (1 h / asiakas)</p>
      </div>
      <div id="opiskele-itse" class="content-section">
        <h2>Opiskele itse digitaitoja</h2>
        <p><a href="https://www.makupalat.fi/fi/kokoelma/digiopastusta" target="_blank">Digiopastus-kokoelma Makupalat-sivulla</a></p> 
      </div>
   </div>
</div>