<? $this->headTitle($this->translate('E-kirjasto')); $this->content()->setHeading($this->translate('E-kirjasto'));?>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="infobox">
            <h2>Kirjat ja äänikirjat</h2>
            <h3><a href="https://www.ellibslibrary.com/helmet" target="_blank" aria-label="Ellibs. Linkki avautuu uudessa ikkunassa.">Ellibs</a></h3>
            <p>Ellibs-palvelusta löydät ensisijaisesti suomen- ja ruotsinkielistä kirjallisuutta. Mukana on myös pieni kokoelma englanninkielistä kirjallisuutta.</p>
            <h3><a href="http://helmet.lib.overdrive.com/" target="_blank" aria-label="Overdrive - ulkomaiset e-kirjat. Linkki avautuu uudessa ikkunassa.">
            Overdrive - ulkomaiset e-kirjat</a></h3>
            <p>Tähän pieni esittely Overdriven ulkomaisesta valikoimasta</p>
            <h3><a href="https://helmet.overdrive.com/collection/1279745" target="_blank" aria-label="Overdrive - ruotsalaiset e-Kirjat. Linkki avautuu uudessa ikkunassa.">
            Overdrive - ruotsin e-kirjat</a></h3>
            <p>Tähän pieni esittely Overdriven ruotsinkielisestä valikoimasta</p>
            <h3><a href="https://helsinkilib.naxosspokenwordlibrary.com/" target="_blank" aria-label="Naxos Spoken World Library. Linkki avautuu uudessa ikkunassa.">
            Naxos Spoken World Library</a></h3>
            <p>Tähän pieni esittely Naxos Spoken World Library valikoimasta</p>
            <h3><a href="https://www.celia.fi/" target="_blank" aria-label="Celia. Linkki avautuu uudessa ikkunassa.">
            Celia</a></h3>
            <p>Celia tarjoaa äänikirjoja lukemisesteisille. Voit rekisteröityä Celian käyttäjäksi kirjastossa. <a href="">Lue lisää Celian käyttöönotosta.</a></p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="infobox">
            <h2>Lehdet</h2>
            <h3><a href="https://helmet.emagz.fi/ext/login/helmet" target="_blank" aria-label="ePress. Linkki avautuu uudessa ikkunassa.">ePress</a></h3>
            <p>Epress-palvelu (ennen eMagz) sisältää yli 80 kotimaista aikakauslehteä ja muutaman sanomalehden kuten Anna, Kotiliesi, Suomen Kuvalehti, 
            Tekniikan Maailma, Maaseudun Tulevaisuus ja Iltalehti. Voit lukea lehtiä missä vain.</p>
            <h3><a href="https://www.pressreader.com/catalog" target="_blank" aria-label="PressReader. Linkki avautuu uudessa ikkunassa.">PressReader</a></h3>
            <p>PressReader tarjoaa tuhansia aikakaus- ja sanomalehtiä noin 120 maasta ja 60 kielellä. Saatavilla ovat muun muassa sanomalehdet The Guardian, 
            Svenska Dagbladet ja The Washington Post, sekä aikakauslehdet T3, Auto Express ja Mollie Makes. Voit lukea lehtiä missä vain.</p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="infobox">
            <h2>Musiikki</h2>
            <h3><a href="https://connect.liblynx.com/wayfless/medicitv?lcard=helmet" target="_blank" aria-label="Medici.tv. Linkki avautuu uudessa ikkunassa.">Medici.tv</a></h3>
            <p>Medici.tv:n videopalvelussa voit katsella tuhansia huippulaatuisia videoita konserteista, oopperoista ja baleteista sekä dokumentteja ja opetusmateriaalia.</p>
            <h3><a href="http://helsinkilib.naxosmusiclibrary.com/" target="_blank" aria-label="Naxos Music Library. Linkki avautuu uudessa ikkunassa.">Naxos Music Library</a></h3>
            <p>Naxos Music Library (NML) on maailman suurin klassisen musiikin online-kirjasto. Palvelusta löytyy tällä hetkellä lähes 190 000 cd-levyllistä musiikkia ja yli 2,8 miljoonaa klassisen musiikin kappaletta.</p>
            <h3><a href="http://helsinkilib.naxosmusiclibrary.com/Jazz" target="_blank" aria-label="Naxos Music Library. Linkki avautuu uudessa ikkunassa.">Naxos Music Library Jazz</a></h3>
            <p>Naxos Music Library Jazz on verkossa käytettävä jazzmusiikin kokoelma, josta löytyy yli 200 000 kappaletta.</p>
            <h3><a href="http://helsinkilib.naxosmusiclibrary.com/World" target="_blank" aria-label="Naxos Music Library World. Linkki avautuu uudessa ikkunassa.">Naxos Music Library World</a></h3>
            <p>Tähän esittelyteksti.</p>
            <h3><a href="https://kirjastot.rockway.fi/helmet" target="_blank" aria-label="Rockway. Linkki avautuu uudessa ikkunassa.">Rockway</a></h3>
            <p>Opiskele soittoa, laulua ja äänittämistä olit sitten aloittelija tai jo pidemmälle edistynyt soittaja. Tarjolla on 69 videokurssia eri aihepiireistä, kitaransoitosta laulutekniikkaan.</p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="infobox">
            <h2>Kielikurssit</h2>
            <h3><a href="https://promentor.kirjastokurssit.fi/login" target="_blank" aria-label="Promentor. Linkki avautuu uudessa ikkunassa.">Promentor</a></h3>
            <p>Promentorin kurssivalikoimassa on alkeis- ja jatkokursseja, jotka soveltuvat itsenäiseen opiskeluun. Eniten valikoimaa on kotimaisissa kielissä sekä englannissa. 
            Kielivalikoimassa ovat: suomi, englanti, ruotsi, espanja, saksa, venäjä, italia ja ranska.</p>
            <h3><a href="http://helsinkilib.naxosspokenwordlibrary.com/" target="_blank" aria-label="Naxos Spoken Word Library. Linkki avautuu uudessa ikkunassa.">Naxos Spoken Word Library</a></h3>
            <p>E-äänikirjoihin erikoistunut Naxos Spoken Word Library sisältää kymmeniä äänikirjamuotoisia kielikursseja. Löydät kurssit valikosta "Language"-otsikkoa napauttamalla.</p>
            <h3><a href="https://helmet.overdrive.com/" target="_blank" aria-label="OverDrive. Linkki avautuu uudessa ikkunassa.">OverDrive</a></h3>
            <p>E-kirjapalvelu OverDrivessa on laaja valikoima kielten opiskeluun tarkoitettuja e-kirjoja ja äänikirjoja.</p>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="infobox">
            <h2>Tietokannat</h2>
            <h3><a href="http://eebo.chadwyck.com/home" target="_blank" aria-label="EEBO - Early English Books Online. Linkki avautuu uudessa ikkunassa.">EEBO - Early English Books Online</a></h3>
            <p>Digitoitua englanninkielistä kirjallisuutta vuosilta 1473–1700. Tätä tietokantaa voit käyttää vain kirjaston tietokoneella.</p>
            <h3><a href="http://helsinkilib.naxosmusiclibrary.com/" target="_blank" aria-label="Naxos Music Library. Linkki avautuu uudessa ikkunassa.">Naxos Music Library</a></h3>
            <p>Klassisen musiikin verkkopalvelu ja tietopankki. Voit käyttää tietokantaa mistä vain kirjautumalla kirjastokortin numerolla.</p>
            <h3><a href="https://www.ne.se/portalanslutning/kort/finelib" target="_blank" aria-label="Nationalencyklopedin. Linkki avautuu uudessa ikkunassa.">Nationalencyklopedin</a></h3>
            <p>Ruotsalainen tietosanakirja. Voit käyttää ylläolevaa linkkiä mistä tahansa. <a href="http://www.ne.se/" target="_blank" 
            aria-label="Nationalencyklopedin Helsingin, Espoon ja Vantaan tietokoneilta. Linkki avautuu uudessa ikkunassa.">Vantaan, Espoon ja Helsingin kirjaston tietokoneille on oma linkki</a> 
            ja <a href="http://www.ne.se/" target="_blank" aria-label="Nationalencyklopedin Kauniaisten tietokoneilta. Linkki avautuu uudessa ikkunassa.">Kauniaisille oma.</a></p>
            <h3><a href="https://www.sanakirja.fi/" target="_blank" aria-label="NetMOT-sanakirjasto. Linkki avautuu uudessa ikkunassa.">NetMOT-sanakirjasto</a></h3>
            <p>Korkealaatuisia sanakirjoja eri kielillä (muun muassa englanti, ruotsi, saksa, ranska, espanja ja viro).</p>
        </div>
    </div>
</div>