<? $this->headTitle($this->translate('Acquisition request')); $this->content()->setHeading($this->translate('Acquisition request'));?>
<p>Are we missing something in our collections? Make an acquisition request.</p>

<form action="https://app.helmet-kirjasto.fi/forms/index.php?site=hankintaehdotus&amp;lang=en" method="post">
	<div class="form-group">
	<fieldset>
	    <legend>Choose a library for acquisition request *</legend>
	        <input type="radio" name="library" id="Espoo" value="Espoo" required="">   <label for="Espoo">Espoo</label> <br>
	        <input type="radio" name="library" id="Helsinki" value="Helsinki" required="">   <label for="Helsinki">Helsinki</label> <br>
	        <input type="radio" name="library" id="Kauniainen" value="Kauniainen" required="">   <label for="Kauniainen">Kauniainen</label> <br>
	        <input type="radio" name="library" id="Vantaa" value="Vantaa" required="">   <label for="Vantaa">Vantaa</label> <br>
	        <input type="radio" name="library" id="Elib" value="Elib" required="">   <label for="Elib">E-Lib</label> <br>
	</fieldset>
	</div>
	<div class="form-group">
	    <label for="author" class="control-label">Author *
	        <input type="text" class="form-control" id="author" name="author" value="" required="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="title" class="control-label">Title *
	        <input type="text" class="form-control" id="title" name="title" value="" required="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="type" class="control-label">Type of material (e.g. book, CD, DVD, periodical etc.) *
	        <input type="text" class="form-control" id="type" name="type" value="" required="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="misc" class="control-label">Other information (e.g. Publisher, language, ISBN, year of publication)
	        <input type="text" class="form-control" id="misc" name="misc" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="email" class="control-label">Your e-mail address for possible contact
	        <input type="text" class="form-control" id="email" name="email" value="">
	    </label>
	</div>
	<div class="form-group">
	<label for="motivation" class="control-label">The reason(s) for your request
	<textarea class="form-control" style="max-width: 100%;" id="motivation" name="motivation" rows="5" cols="40"></textarea>
	</label>
	</div>
	<div class="form-group">
	<label for="info_source" class="control-label">Where did you get the information from?
	<textarea class="form-control" style="max-width: 100%;" id="info_source" name="info_source" rows="5" cols="40"></textarea>
	</label>
	</div>
	
	<input type="hidden" name="lang" value="en">
	
	<p><label>Please fill in all required fields marked with an asterisk (*).<br>
	<input type="submit" class="btn btn-primary" name="submit" value="Submit the request">
	</label></p>
	
</form>

