<? $this->headTitle($this->translate('Helsingin kirjastojen palvelut kouluille')); $this->content()->setHeading($this->translate('Helsingin kirjastojen palvelut kouluille'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helsingissä on 37 kirjastoa ja kaksi kirjastoautoa, joista jokaiseen luokat ovat lämpimästi tervetulleita. 
        <a href="https://kultus.fi/cms-page/kulttuurikasvatus/kulttuuripolulla-kulttuuria-kaikille/perusopetuksen-kulttuuripolku" target="_blank" 
        aria-label="Helsingin kulttuuripolku. Linkki aukeaa uudessa ikkunassa.">Kulttuuripolun</a> osana kirjastot tarjoavat kaikille 1.-, 3.- ja 7.-luokkalaisille ohjatun ryhmäkäynnin. 
        Lisäksi kirjastot tarjoavat kouluille muita palveluita, ja ryhmät voivat vierailla kirjastoissa myös itsenäisesti. Kirjastot ottavat mielellään vastaan myös toiveita 
        ja ehdotuksia yhteistyölle.</p>
      </div>
     <div id="kulttuuripolku" class="content-section">
        <h2>Kulttuuripolku 1., 3. ja 7. luokille</h2>
        <h3>1. luokat: Kirjastostartti</h3>
        <p>Ohjattu tutustumiskäynti kirjastoon tai ekaluokkalaisjuhla, jonka yhteydessä oppilaat saavat Helmet-kirjastojen ekaluokkalaiskampanjan kirjan omakseen. Luokat kutsutaan 
        kirjastokäynnille ensimmäisen kouluvuoden aikana. Kirjastostartti voidaan tarvittaessa toteuttaa etätapahtumana. </p>
        <h3>3. luokat: Kirjavinkkaus</h3>
        <p>Kirjavinkkaus, jossa oppilaat tutustuvat kiinnostaviin kirjoihin kirjaston henkilökunnan opastuksella. Luokat kutsutaan kirjastokäynnille kolmannen kouluvuoden aikana. 
        Vinkkaus voidaan tarvittaessa hoitaa myös etäyhteyden välityksellä.</p>
        <h3>7. luokat: Rivien välistä -tapahtuma</h3>
        <p>Rivien välistä -vinkkaustapahtuma kutsuu kaikki helsinkiläiset 7.luokat lukemisen ja kirjavinkkien pariin loppusyksystä 2023. Tapahtuma sijoittuu neljälle viikolle ja luokat 
        voivat valita heille parhaiten sopivan esityspaikan ja ajankohdan. Tapahtumat järjestetään Kanneltalossa, Maunula-talossa, Malmitalolla ja Oodin Reginassa 31.10.–24.11. välisenä 
        aikana. Ruotsinkielinen vinkkaus järjestetään koulujen lähikirjastoissa.</p>
      </div>
      <div id="lahikirjastot" class="content-section">
        <h2>Lähikirjastot</h2>
        <p>Kirjastot tarjoavat kouluille myös muita palveluita kirjastojen resurssien mukaan. Koulujen lähikirjastot viestivät palveluistaan sekä koulujen kirjastoyhteysopettajien 
        kautta että sähköpostitse suoraan opettajille. 
      </div>
      <div id="kirjastokortti" class="content-section">
        <h2>Kirjastokortti</h2>
        <p>Oppilas voi saada kirjastokortin luokkakäynnin yhteydessä näyttämällä huoltajan täyttämän 
        <a href="/themes/custom/files/kirjastokorttihakemus.pdf" target="_blank">kirjastokorttihakemuksen (PDF)</a>. Mikäli toiveena on 
        kirjastokortin tekeminen useammalle oppilaalle, olettehan etukäteen yhteydessä kirjastoon.</p>
        <p>Oppilas voi saada kirjastokortin myös vierailemalla kirjastossa huoltajan kanssa tai tuomalla lomakkeen itse kirjastoon. Mikäli kortti tehdään vapaa-ajalla, 
        oppilas tarvitsee mukaansa Kela-kortin tai muun henkilöllisyystodistuksen. 15–17-vuotiaat eivät tarvitse lomaketta tai huoltajan lupaa kortin tekemiseen.</p>
        <p>Opettaja voi hankkia luokalle myös luokan yhteisen kirjastokortin. Kortin voi tehdä kirjastovierailun yhteydessä, ja tekemiseen tarvitaan takaajan eli opettajan 
        henkilöllisyystodistus. Kortti on voimassa vuoden. Luokkakortin lainat eivät mene perintään.</p>
      </div>
      <div id="kirjakassit-ja-lukupiirit" class="content-section">
        <h2>Kirjakassit, lukupiirikirjat ja lukidiplomi</h2>
        <p>Kirjastot kokoavat kouluille kirjakasseja eri teemoista toiveiden mukaan. Kirjastot auttavat myös esimerkiksi lukupiirikirjojen valinnassa ja isompien kirjavarausten 
        käytännön järjestelyissä. Lisätietoja lähikirjastosta.</p>
        <h3>Helmet-lukudiplomi</h3>
        <p>Lukudiplomi innostaa lukemaan! Diplomin ohjeet löytyvät osoitteesta <a href="https://kirjasto.one/lukudiplomi/" target="_blank">kirjasto.one/lukudiplomi</a>.</p>
      </div>
      <div id="lukuvalmentaja-junior" class="content-section">
        <h2>Lukuvalmentaja Junior</h2>
        <p><a href="/Content/lukuvalmentaja-junior">Lukuvalmentaja Junior</a> on lasten- ja nuortenkirjallisuuteen keskittynyt palvelu, joka auttaa löytämään lukijan toiveiden mukaisia kirjoja. Palvelun tavoitteena on 
        tukea ensisijaisesti lasten ja nuorten vapaa-ajan lukemisharrastusta, mutta opettajat voivat halutessaan pyytää palvelusta vinkkejä yksittäiselle oppilaalle tai tilata 
        lukuvalmennuksen tietystä teemasta opettajille.</p>
      </div>
      <div id="skidipeli" class="content-section">
        <h2>Skidipeli – lukutaitoseikkailu 4.luokille</h2>
        <p>4. luokat kutsutaan jälleen keväällä 2024 pelaamaan Skidipeliä! Skidipeli on jättimäinen lautapeli ja taideinstallaatio, jossa pelaajat seikkailevat itse pelinappuna 
        suurella pelilaudalla. Pelin tiimellyksessä tutustutaan paitsi omaan kotikaupunkiin, myös erilaisiin lukutaitoihin. Pelit järjestetään keväällä 2024 Pasilan ja Itäkeskuksen 
        kirjastoissa. Tapahtumiin ilmoittautumisesta tiedotetaan kouluja erikseen. Lue myös <a href="https://issuu.com/blombma/docs/opettajan_opas_skidipeli_hel_smoy"
        target="_blank" aria-label="Skidipelin opettajanopas. Linkki aukeaa uudessa ikkunassa.">Skidipelin opettajanopas</a>. Lisätietoja sähkopostilla: 
        <a href="mailto:piia.bagman@hel.fi">piia.bagman@hel.fi</a> tai <a href="mailto:johanna.n.martikainen@hel.fi">johanna.n.martikainen@hel.fi</a>.
      </div>
      <div id="lukemisesteisille" class="content-section">
        <h2>Celia-äänikirjat lukemisesteisille</h2>
        <p> <a href="https://www.celianet.fi/" target="_blank" aria-label="Celia-äänikirjapalvelu. Linkki aukeaa uudessa ikkunassa.">Celia-äänikirjapalvelu</a> 
        palvelee niitä lukijoita, joille painetun kirjan lukeminen on syystä tai toisesta hankalaa. Celia-tunnusten kautta oppilaat saavat käyttöönsä laajan ääni- ja e-kirjavalikoiman.
        Oppilaat rekisteröidään Celian asiakkaaksi pääosin koulujen erityisopettajien kautta, mutta asiakkaaksi voi rekisteröityä myös lähes kaikissa Helsingin kirjastoissa.</p>
        <p>Helmet-kirjastot tekevät yhteistyötä Celian kanssa. Ekaluokkalaiskampanjakirja löytyy Celia-äänikirjana, ja Celia-kirjat on huomioitu myös Helmet-lukudiplomissa.</p>
      </div>
      <div id="yhteystiedot" class="content-section">
        <h2>Yhteystiedot</h2>
        <p>Oman kirjaston kouluyhteistyöasioissa voit olla yhteydessä suoraan lähikirjastoon. Mikäli sinulla on kysymyksiä koko Helsingin kaupunginkirjaston kouluyhteistyötä
        koskien, voit olla yhteydessä:</p>
        <h3>Alakouluyhteistyö</h3>
        <p>Piia Bågman, <a href="mailto:piia.bagman@hel.fi">piia.bagman@hel.fi</a><br>
        Nanna Martikainen, <a href="mailto:johanna.n.martikainen@hel.fi">johanna.n.martikainen@hel.fi</a></p>
        <h3>Yläkouluyhteistyö</h3>
        <p>Outi Hokkinen,  <a href="mailto:outi.hokkinen@hel.fi">outi.hokkinen@hel.fi</a><br>
        Nanna Martikainen, <a href="mailto:johanna.n.martikainen@hel.fi">johanna.n.martikainen@hel.fi</a></p>
        <h3>Svenskspråkigt skolsamarbete</h3>
        <p>Cecilia Eriksson <a href="mailto:cecilia.eriksson@hel.fi">cecilia.eriksson@hel.fi</a></p>
      </div>
   </div>
</div>







