<? $this->headTitle($this->translate('Helsingin kaupunginkirjaston palvelut varhaiskasvatuksen ja esiopetuksen ryhmille')); $this->content()->setHeading($this->translate('Helsingin kaupunginkirjaston palvelut varhaiskasvatuksen ja esiopetuksen ryhmille'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Varhaiskasvatuksen ja esiopetuksen ryhmät ovat tervetulleita kirjastoon lukemaan ja lainaamaan sekä osallistumaan kirjastossa järjestettäviin esityksiin ja tapahtumiin. Tapahtumiin 
        ilmoittaudutaan pääsääntöisesti <a href="https://kultus.fi/cms-page/oppimateriaalit/ylakoulu-ja-toinen-aste/helsingin-kaupunginkirjasto-tulostettavat-lukudiplomipohjat" target="_blank"
        aria-label="Kultus.fi. Linkki aukeaa uudessa ikkunassa.">Kultus.fi</a> -sivuston kautta. Ryhmille voidaan järjestää myös omia räätälöityjä kirjastovierailuja ja etätuokioita. Lisätietoa 
        kirjaston palveluista ryhmille voi tiedustella oman lähikirjastosi päiväkotiyhteyshenkilöltä. Yhteyshenkilöt löytyvät kunkin kirjaston omilta Helmet.finna.fi-sivuilta 
        Yhteystiedot-osiosta.</p>
      </div>
     <div id="satutuokiot" class="content-section">
        <h2>Satutuokiot</h2>
        <p>Satutuokioissa uppoudutaan tarinoiden maailmaan ja ruokitaan lukuintoa. Ne kehittävät mielikuvitusta, tunnetaitoja ja sanavarastoa.</p>
      </div>
      <div id="mediatuokiot" class="content-section">
        <h2>Mediatuokiot</h2>
        <p>Mediatuokioissa yhdistetään tarinat ja kirjat johonkin mediaelementtiin ja tutustutaan esimerkiksi koodaamiseen sekä erilaisiin mediasovelluksiin. Mediatuokiot sopivat parhaiten 
        5–8-vuotiaille.  </p>
      </div>
      <div id="tyopajat" class="content-section">
        <h2>Työpajat</h2>
        <p>Keskustakirjasto Oodi sekä osa lähikirjastoista tarjoavat monenlaisia työpajoja ja ohjattuja vierailuja varhaiskasvatuksen ryhmille. Työpajojen aiheet vaihtelevat tarinoista ja 
        sanataiteesta koodaukseen ja kädentaitoihin. Myös osa lähikirjastoista tarjoaa työpajoja eri aiheista.</p>
      </div>
      <div id="kirjakassit" class="content-section">
        <h2>Kirjakassit päiväkodeille</h2>
        <p>Kirjaston henkilökunta voi pyynnöstä koota tiettyyn aiheeseen liittyviä kirjakasseja erilaisten teemojen käsittelyn tueksi. Kirjastoon kannattaa olla yhteydessä vähintään pari 
        viikkoa ennen kuin tarvitsette aineistoa.</p>
      </div>
      <div id="satudiplomi" class="content-section">
        <h2>Satudiplomi</h2>
        <p>Helmet-kirjastot haluavat kannustaa päiväkotien lapsiryhmiä yhteisiin lukuhetkiin Satudiplomin avulla. Satudiplomin saa, kun kuuntelee tai lukee kymmenen (10) kirjaa. 
        Edistymistä voi seurata merkitsemällä ryhmän lukemat kirjat hauskaan, väritettävään Lukulokkiin. Diplomin suorittaneet ryhmät saavat kirjastosta kunniakirjan 
        <a href="https://kirjasto.one/lukudiplomi/index.php?dipl=15" target="_blank" aria-label="Satudiplomi-sivustolta. Linkki aukeaa uudessa ikkunassa.">Satudiplomi-sivustolta</a> 
        löytyvässä kirjalistassa on monipuolisia ja viihdyttäviä kirjavinkkejä yhteisiin lukuhetkiin sekä suuntaa antavat ikäsuositukset. Kirjat voi myös valita vapaasti listan ulkopuolelta. 
        Diplomin voi suorittaa suomeksi, ruotsiksi, englanniksi ja venäjäksi. Satudiplomia voi hyödyntää myös kotikielen tukemiseen, joten kirjan voi halutessaan lukea millä tahansa kielellä. 
        Valmiissa kirjalistassa on mahdollisuus eri kieliversioiden hakemiseen kirjaston kokoelmasta.</p>
        <p>Lisää tietoa satudiplomista saat kaikista Helmet-kirjaston toimipisteistä.</p>
      </div>
      <div id="kirjastokortti" class="content-section">
        <h2>Kirjastokortti</h2>
        <p>Opettaja voi hankkia ryhmälleen myös ryhmän yhteisen kirjastokortin. Kortin voi tehdä kirjastovierailun yhteydessä, ja tekemiseen tarvitaan takaajan henkilöllisyystodistus. 
        Kortti on voimassa vuoden. Ryhmäkortin lainat eivät mene perintään.</p>
      </div>
      <div id="lukuvalmentaja-junior" class="content-section">
        <h2>Lukuvalmentaja Junior</h2>
        <p><a href="/Content/lukuvalmentaja-junior">Lukuvalmentaja Junior</a> on lasten- ja nuortenkirjallisuuteen keskittynyt palvelu, joka auttaa löytämään lukijan toiveiden mukaisia kirjoja. Palvelun tavoitteena on tukea ensisijaisesti 
        lasten ja nuorten vapaa-ajan lukemisharrastusta, mutta myös opettajat ja kasvattajat voivat halutessaan pyytää palvelusta vinkkejä yksittäiselle lapselle tai tilata itselleen 
        lukuvalmennuksen tietystä teemasta.</p>
      </div>
   </div>
</div>

