<? $this->headTitle($this->translate('Kaukopalvelu')); $this->content()->setHeading($this->translate('Kaukopalvelu'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="mika-on-kaukopalvelu" class="content-section">
        <h2>Mikä on kaukopalvelu?</h2>   
        <p>Kaukopalvelu on kirjastojen välistä toimintaa, ja sen avulla voit hyödyntää koko kirjastoverkkoa. Jos etsimääsi teosta ei ole hankittu Helmet-kirjastoon tai 
        pääkaupunkiseudun tieteellisiin kirjastoihin, se voidaan tilata sinulle kaukolainaksi muualta.</p>
        <p>Kaukolainaksi tilataan kirjoja, levyjä, nuotteja, elokuvia ja mikrofilmejä. Lehtien vuosikertoja ei yleensä saa lainaksi, vaan niistä tilataan yksittäisiä artikkelikopioita. 
        Kirjastot eivät kuitenkaan tilaa kaukolainana aineistoa, joka on saatavissa jostakin pääkaupunkiseudun tieteellisestä kirjastosta tai erikoiskirjastosta. 
        <strong>Jos etsimäsi teos on lainassa, tee silloin tavallinen varaus. Kaukopalvelua ei ole tarkoitettu paikallisten varausten ohittamiseen.</strong></p>
        <p>Voit tehdä kaukopalvelupyynnön netissä tai kirjastossa. Pyyntö edellyttää, että Helmet-korttisi on voimassa ja sinulla on lainausoikeus.</p>
        <p>Kaukopalvelu on maksullista, tarkemmat tiedot ks. <a href="#maksut">Kaukopalvelumaksut</a>. 
        Kaukolaina tai kopiot toimitetaan mahdollisuuksien mukaan toivomaasi noutokirjastoon. Kaukolainoissa noudatetaan aina omistajakirjaston asettamia laina-aikoja ja muita käyttöehtoja. 
        Kaikkea aineistoa ei saa kaukolainaksi ja osa annetaan vain lukusalikäyttöön, esim. opinnäytteet tai harvinaiset kirjat.</p>
        <p>Kurssikirjojen kaukolainaamisessa on rajoituksia, ja korkeakoulukirjastot lainaavat niitä yleensä vain omille opiskelijoilleen. 
        Kurssikirjatilauksissa voidaan kuitenkin poiketa kaukopalvelun yleisperiaatteista, sillä kirja voidaan tilata oman korkeakoulusi kirjastosta kaukolainaksi, vaikka sitä olisi myös pääkaupunkiseudun kirjastojen kokoelmissa.</p>
        <p>Jos olet opiskelija, merkitse lomakkeeseen opiskelupaikkasi ja mielellään myös opiskelijanumerosi – se nopeuttaa tilauksen käsittelyä</p>
        <p>Kaukolainojen tiedot eivät toistaiseksi näy Helmet-verkkokirjaston asiakastiedoissa eikä niitä voi uusia itse. Kätevimmin voit pyytää uusimista sähköpostilla.</p>
      </div>
     <div id="maksut" class="content-section">
        <h2>Kaukopalvelumaksut</h2>
        <h3>Espoon kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li>kaukolaina Suomesta 7 €</li>
            <li>artikkelikopiot/tulosteet: 0,85 €/kopio/tuloste tai lähettävän kirjaston veloittama hinta</li>
        </ul>
        <h3>Helsingin kaupunginkirjasto</h3>
        <ul class="list-bullets">
          <li>Kaukolaina Suomesta ja Pohjoismaista 4 €/kpl</li>
          <li>British Librarysta tilattu laina 25 €/kpl</li>
          <li>Muualta ulkomailta tilattu laina 14-25 €/kpl</li>
          <li>Kopiot: lähettäjäkirjaston perimä maksu tai vähintään 4 €</li>
        </ul>
        <h3>Kauniaisten kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li>lähettävän kirjaston kaukopalvelumaksu / minimimaksu 4 €</li>
        </ul>
        <h3>Vantaan kaupunginkirjasto</h3>
        <ul class="list-bullets">
          <li>Tilaus kotimaasta: 7 € / nide</li>
          <li>Tilaus ulkomailta: laskun mukaan, vähintään 7 € / nide</li>
          <li>Valokopioiden tilaus: laskun mukaan</li>
          <li>Valokopion postitus tai faxin lähetys: 0,80 € / sivu, vähintään 5,05 €</li>
        </ul>
      </div>
      <div id="kirjastoille" class="content-section">
        <h2>Kaukopalvelu kirjastoille</h2>
        <p>Helmet-kirjastojen kaukopalvelu hoidetaan keskitetysti Pasilassa ja varauksen noutopaikaksi merkitään aina Pasila/kaukopalvelu kirjastoille riippumatta siitä, 
        missä kirjastossa aineisto on. Varaukset kohdistuvat ensisijaisesti Helsingin aineistoon, mutta kaikki aineisto on käytettävissä. Lainoja voi uusia viisi kertaa, jos aineistoon 
        ei ole varauksia. Kaukolainatilauksen voi tehdä suoraan tietokantaan <a href="/">https://www.helmet.finna.fi/</a> tai sähköpostilla 
        <a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a>.</p>
        <p>Artikkelipyynnöt ja sanomalehtien mikrofilmitilaukset pyydämme lähettämään sähköpostilla. Mikrofilmejä lainaamme kerrallaan korkeintaan 5 rullaa /nimeke.</p>
        <p>Monikielisen kirjaston siirtokokoelmapyynnöt lähetetään sähköpostilla 
        <a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></p>
        <p>Kaukolainat ovat maksuttomia yleisille kirjastoille, muilta kirjastoilta veloitamme 7 € / laina. Kopiot maksavat 1 € / sivu.</p>
        <p>Keskuskirjasto myös välittää lainoja ja kopioita ulkomaisista kirjastoista. Lainan välitys Pohjoismaista maksaa 10 €, muualta Euroopasta 15–30 € / laina. 
        Kopioiden hinnat määräytyvät lähettäjäkirjaston hinnaston mukaan.</p>
        <h3>Yhteystiedot:</h3>
        <p><a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></p>
        <p><a href="tel:0931085432">(09) 3108 5432</a> (Helmet-kaukolainat)<br>
        <a href="tel:0931085433">(09) 3108 5433</a> (välitykset ulkomailta)</p>
        <p>Helsingin kaupunginkirjasto<br>
        Kaukopalvelu<br>
        PL 52401<br>
        00099 HELSINGIN KAUPUNKI</p>
      </div>
      <div id="venajankielinen" class="content-section">
        <h2>Venäjänkielisen kirjaston kaukopalvelu</h2>
        <p>Kaikki Suomessa pääkaupunkiseudun (Helsinki, Espoo, Vantaa, Kauniainen) ulkopuolella asuvat voivat käyttää Venäjänkielisen kirjaston maksutonta kaukopalvelua ja lainata 
        Venäjänkielisen kirjaston kirjoja, elokuvia tai puheäänitteitä. <strong>Lainaamme sekä venäjän- että ukrainankielistä aineistoa.</strong></p>
        <p>Seuraavalla tavalla voitte ilmoittautua Venäjänkielisen kirjaston kaukopalvelun asiakkaaksi:
        <ol class="list-numbers">
            <li>Menkää lähikirjastoonne. Ottakaa henkilöllisyystodistuksenne mukaan. Täyttäkää ilmoittautumislomake yhdessä kirjaston työntekijän kanssa. 
            Tulostakaa lomake, kun olette täyttänyt sen.</li>
            <li>Kirjaston työntekijä tarkistaa henkilöllisyytenne, allekirjoittaa lomakkeen ja leimaa sen kirjaston leimalla.</li>
            <li>Lomakkeesta otetaan teille oma kopio. Kirjasto toimittaa allekirjoitetun lomakkeen Espoon Venäjänkieliseen kirjastoon.</li>
            <li>Venäjänkielisessä kirjastossa teille tehdään Helmet kirjastokortti. Saatte kirjastokortin numeron ja nelinumeroisen tunnusluvun, joilla voitte varata kirjoja ja uusia 
            lainojanne Helmet.fi palvelussa.</li>
            <li>Numero ja tunnusluku lähetetään teille ilmoittautumislomakkeen sähköpostiosoitteeseen.Voitte vaihtaa tunnusluvun HelMet.fi-palvelussa. Jos uusi tunnuslukunne unohtuu 
            tai yhteystietoihinne tulee jokin muutos, ottakaa yhteys <a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a>.</li>
        </ol>
        <p>Tämän jälkeen voitte tilata HelMet.fi-sivustolta aineistoa kaukolainattavaksi omilla tunnuksillanne. Tietokannasta voi etsiä teoksia sekä kyrillisin että 
        latinalaisin kirjaimin <strong>Noutopaikaksi merkitään Venäjänkielinen kirjasto.</strong> Vaihtoehtoisesti voi lähettää toivomuksen sähköpostilla osoitteeseen
        <a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a>, omat yhteystietonne tulee näkyä viestissänne.</p>
        <p>Aineiston nouto ja palautus tapahtuu joko postin pakettiautomaatin tai oman lähikirjaston kautta.</p>
        <p>Kun lainattu aineisto on noudettavissa Postin pakettiautomaatista, saatte kännykkään koodin, jolla voitte noutaa paketin valitusta pakettiautomaatista. 
        Lainat palautetaan samassa pussissa, jossa ne tulivat. Saatu koodi pitää säilyttää, sillä maksuttomassa palautuksessa käytetään tätä samaa koodia.</p>
        <p>Postin pakettiautomaattipalveluun voi tutustua ja löytää itselleen parhaiten sopivan pakettiautomaatin osoitteessa <a href="http://www.posti.fi/pakettiautomaatti" 
        target="_blank">www.posti.fi/pakettiautomaatti</a></p>
        <p>Jos haluatte asioida lähikirjaston kautta, kirjastostanne ilmoitetaan, kun kaukolaina-aineisto on saapunut noudettavaksi. Lainat palautetaan lähikirjastoon samassa pussissa, 
        jossa ne lähetettiin.</p>
        <p>Laina-aika on 6 viikkoa.</p><p>
        <p>Kirjasto ei luovuta tietoja ulkopuolisille. Asiakkaalla on oikeus tarkistaa, mitä tietoja hänestä on tallennettu.</p>
        <p>Tiedustelut: <a href="tel:0438257993">043 8257993</a> tai <a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a><br><br>
        <a href="/themes/custom/files/ilmoittautuminen-ukrainankielisen-kirjallisuuden-kaukolaina-asiakkaaksi.pdf" target="_blank">Ilmoittautuminen ukrainankielisen kirjallisuuden kaukolaina-asiakkaaksi (PDF)</a>
        (tulosta ja täytä)</p>
        <p><a href="/themes/custom/files/ilmoittautumislomake-venäjänkielisen-kirjaston-asiakkaaksi.pdf">Ilmoittautumislomake venäjänkielisen kirjaston asiakkaaksi (PDF)</a></p>
        <p><a href="/themes/custom/files/venäjänkielinen-kaukopalvelu-asiakkaille.pdf">Venäjänkielisen kaukopalvelun tulostettava esite (suomeksi) (PDF)</a></p>
        <p><a href="/themes/custom/files/venäjänkielinen-kaukopalvelu-asiakkaille-RUS.pdf">Venäjänkielisen kaukopalvelun tulostettava esite (venäjäksi) (PDF)</a></p>
      </div>
      <div id="yhteystiedot" class="content-section">
        <h2>Kaukopalvelun yhteystiedot</h2>
        <h3>Espoon kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@espoo.fi">kaukopalvelu@espoo.fi</a></li>
            <li>puh. <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
        <h3>Helsingin kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></li>
            <li>puh. <a href="tel:0931085433">09 310 85433</a></li>
        </ul>
        <h3>Kauniaisten kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@kauniainen.fi">kaukopalvelu@kauniainen.fi</a></li>
            <li>puh. <a href="tel:0504116514">050 411 6514</a></li>
        </ul>
        <h3>Vantaan kaupunginkirjasto</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kauko.palvelu@vantaa.fi">kauko.palvelu@vantaa.fi</a></li>
            <li>puh. <a href="tel:0505707776">050 570 7776</a></li>
        </ul>
        <h3>Venäjänkielinen kirjasto</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a></li>
            <li>puh. <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
      </div>
      <div id="tee-kaukopalvelupyynto" class="content-section">
        <h2>Tee kaukopalvelupyyntö</h2>
        <a href="<?=$this->url('feedback-form', ['id' => 'Kaukopalvelu'])?>">Tee Kaukopalvelupyyntö</a>
        <p>Tarkista ensin <a href="/">Helmet-hausta</a>, <a href="https://finna.fi/" target="_blank" 
        aria-label="Finnasta. Linkki aukeaa uuteen ikkunaan.">Finnasta</a> tai 
        <a href="http://melinda.kansalliskirjasto.fi/F/?func=find-b-0&con_lng=fin&local_base=fin01_opac" target="_blank" 
        aria-label="Melinda-tietokannasta. Linkki aukeaa uuteen ikkunaan.">Melinda-tietokannasta</a>, löytyykö tarvitsemasi julkaisu pääkaupunkiseudun kirjastoista. Kaukolainatilausta ei tehdä, 
        jos julkaisu on jonkin pääkaupunkiseudun kirjaston kokoelmissa.</p>
        <p>Kaukopalvelupyyntö on sitova.  Sitoudut maksamaan kaukolainamaksun (ks. kaukopalvelumaksut). Kopioista veloitetaan lähettävän kirjaston hinnaston mukaan. 
        Myös noutamattomasta kaukolainasta veloitetaan.</p>
        <p>Tilattu aineisto toimitetaan valitsemaasi Helmet-kirjaston toimipaikkaan ja sen saapumisesta ilmoitetaan sähköpostitse tai puhelimitse. Aineisto on palautettava samaan kirjastoon, 
        josta se noudettiin (huom. Espoossa kaukolainan voi palauttaa mihin tahansa espoolaiseen kirjastoon).</p>
        
        <form action="https://app.helmet-kirjasto.fi/forms/index.php?site=kaukopalvelupyynto&amp;lang=fi" method="post">
        <br>
        <h3>Tilaajan tiedot</h3>
        <div class="form-group">
    	    <label for="card" class="control-label">Kirjastokortin numero *
    	        <input type="text" class="form-control" id="card" name="card" value="" required="">
    	    </label>
	    </div>
		<div class="form-group">
	        <label for="name" class="control-label">Nimi *
	            <input type="text" class="form-control" id="name" name="name" value="" required="">
	        </label>
	    </div>
		<div class="form-group">
	        <label for="addr" class="control-label">Osoite *
	            <input type="text" class="form-control" id="addr" name="addr" value="" required="">
	        </label>
	    </div>
	    <div class="form-group">
	        <label for="zipcity" class="control-label">Postinumero ja postitoimipaikka *
	            <input type="text" class="form-control" id="zipcity" name="zipcity" value="" required="">
	        </label>
	    </div>
    	<div class="form-group">
	        <label for="email" class="control-label">Sähköposti
	            <input type="text" class="form-control" id="email" name="email" value="">
	        </label>
	    </div>
	    <div class="form-group">
	        <label for="phone" class="control-label">Puhelin
	            <input type="text" class="form-control" id="phone" name="phone" value="">
	        </label>
	    </div>
		<div class="form-group">
	        <label for="lib" class="control-label">Valitse Helmet-kirjasto, josta haluat noutaa lainasi/valokopiosi *
	    	    <select id="lib" class="form-control" name="lib" onchange="onSelect()" required="">
	            <option value="">Valitse kirjasto</option>
        	       <optgroup label="Espoo">
        	        <option name="Entressen kirjasto" value="Entressen kirjasto">Entresse</option> 
        	        <option name="Haukilahden kirjasto" value="Haukilahden kirjasto">Haukilahti</option> 
        	        <option name="Ison Omenan kirjasto" value="Ison Omenan kirjasto">Ison Omenan kirjasto</option> 
        	        <option name="Kalajärven kirjasto" value="Kalajärven kirjasto">Kalajärvi</option> 
        	        <option name="Karhusuon kirjasto" value="Karhusuon kirjasto">Karhusuo</option> 
        	        <option name="Kauklahden kirjasto" value="Kauklahden kirjasto">Kauklahti</option> 
        	        <option name="Laajalahden kirjasto" value="Laajalahden kirjasto">Laajalahti</option> 
        	        <option name="Laaksolahden kirjasto" value="Laaksolahden kirjasto">Laaksolahti</option> 
        	        <option name="Lippulaivan kirjasto" value="Lippulaivan kirjasto">Lippulaiva</option> 
        	        <option name="Nöykkiön kirjasto" value="Nöykkiön kirjasto">Nöykkiö</option> 
        	        <option name="Otaniemen kirjasto" value="Otaniemen kirjasto">Otaniemi</option> 
        	        <option name="Saunalahden kirjasto" value="Saunalahden kirjasto">Saunalahti</option> 
        	        <option name="Sellon kirjasto" value="Sellon kirjasto">Sello</option> 
        	        <option name="Suurpellon kirjasto" value="Suurpellon kirjasto">Suurpelto</option> 
        	        <option name="Tapiolan kirjasto" value="Tapiolan kirjasto">Tapiola</option> 
        	        <option name="Viherlaakson kirjasto" value="Viherlaakson kirjasto">Viherlaakso</option> 
        	      </optgroup>
        	      <optgroup label="Helsinki">
        	        <option name="Arabianrannan kirjasto" value="Arabianrannan kirjasto">Arabianranta</option> 
        	        <option name="Etelä-Haagan kirjasto" value="Etelä-Haagan kirjasto">Etelä-Haaga</option> 
        	        <option name="Herttoniemen kirjasto" value="Herttoniemen kirjasto">Herttoniemi</option> 
        	        <option name="Itäkeskuksen kirjasto" value="Itäkeskuksen kirjasto">Itäkeskus</option> 
        	        <option name="Jakomäen kirjasto" value="Jakomäen kirjasto">Jakomäki</option> 
        	        <option name="Jätkäsaaren kirjasto" value="Jätkäsaaren kirjasto">Jätkäsaari</option> 
        	        <option name="Kalasataman kirjasto" value="Kalasataman kirjasto">Kalasatama</option> 
        	        <option name="Kallion kirjasto" value="Kallion kirjasto">Kallio</option> 
        	        <option name="Kannelmäen kirjasto" value="Kannelmäen kirjasto">Kannelmäki</option> 
        	        <option name="Kontulan kirjasto" value="Kontulan kirjasto">Kontula</option> 
        	        <option name="Käpylän kirjasto" value="Käpylän kirjasto">Käpylä</option> 
        	        <option name="Laajasalon kirjasto" value="Laajasalon kirjasto">Laajasalo</option> 
        	        <option name="Lauttasaaren kirjasto" value="Lauttasaaren kirjasto">Lauttasaari</option> 
        	        <option name="Malmin kirjasto" value="Malmin kirjasto">Malmi</option> 
        	        <option name="Malminkartanon kirjasto" value="Malminkartanon kirjasto">Malminkartano</option> 
        	        <option name="Maunulan kirjasto" value="Maunulan kirjasto">Maunula</option> 
        	        <option name="Munkkiniemen kirjasto" value="Munkkiniemen kirjasto">Munkkiniemi</option> 
        	        <option name="Myllypuron kirjasto" value="Myllypuron kirjasto">Myllypuro</option> 
        	        <option name="Keskustakirjasto Oodi" value="Keskustakirjasto Oodi">Oodi</option> 
        	        <option name="Oulunkylän kirjasto" value="Oulunkylän kirjasto">Oulunkylä</option> 
        	        <option name="Paloheinän kirjasto" value="Paloheinän kirjasto">Paloheinä</option> 
        	        <option name="Pasilan kirjasto" value="Pasilan kirjasto">Pasila</option> 
        	        <option name="Pitäjänmäen kirjasto" value="Pitäjänmäen kirjasto">Pitäjänmäki</option> 
        	        <option name="Pohjois-Haagan kirjasto" value="Pohjois-Haagan kirjasto">Pohjois-Haaga</option> 
        	        <option name="Puistolan kirjasto" value="Puistolan kirjasto">Puistola</option> 
        	        <option name="Pukinmäen kirjasto" value="Pukinmäen kirjasto">Pukinmäki</option> 
        	        <option name="Rikhardinkadun kirjasto" value="Rikhardinkadun kirjasto">Rikhardinkatu</option> 
        	        <option name="Roihuvuoren kirjasto" value="Roihuvuoren kirjasto">Roihuvuori</option> 
        	        <option name="Suomenlinnan kirjasto" value="Suomenlinnan kirjasto">Suomenlinna</option> 
        	        <option name="Suutarilan kirjasto" value="Suutarilan kirjasto">Suutarila</option> 
        	        <option name="Tapanilan kirjasto" value="Tapanilan kirjasto">Tapanila</option> 
        	        <option name="Tapulikaupungin kirjasto" value="Tapulikaupungin kirjasto">Tapulikaupunki</option> 
        	        <option name="Töölön kirjasto" value="Töölön kirjasto">Töölö</option> 
        	        <option name="Vallilan kirjasto" value="Vallilan kirjasto">Vallila</option> 
        	        <option name="Viikin kirjasto" value="Viikin kirjasto">Viikki</option> 
        	        <option name="Vuosaaren kirjasto" value="Vuosaaren kirjasto">Vuosaari</option> 
        	      </optgroup>
        	      <optgroup label="Kauniainen">
        	        <option name="Kauniaisten kirjasto" value="Kauniaisten kirjasto">Kauniainen</option> 
        	      </optgroup>
        	      <optgroup label="Vantaa">
        	        <option name="Hiekkaharjun kirjasto" value="Hiekkaharjun kirjasto">Hiekkaharju</option> 
        	        <option name="Kivistön kirjasto" value="Kivistön kirjasto">Kivistö</option> 
        	        <option name="Koivukylän kirjasto" value="Koivukylän kirjasto">Koivukylä</option> 
        	        <option name="Lumon kirjasto" value="Lumon kirjasto">Lumo</option> 
        	        <option name="Länsimäen kirjasto" value="Länsimäen kirjasto">Länsimäki</option> 
        	        <option name="Martinlaakson kirjasto" value="Martinlaakson kirjasto">Martinlaakso</option> 
        	        <option name="Myyrmäen kirjasto" value="Myyrmäen kirjasto">Myyrmäki</option> 
        	        <option name="Pointin kirjasto" value="Pointin kirjasto">Point</option> 
        	        <option name="Tikkurilan kirjasto" value="Tikkurilan kirjasto">Tikkurila</option> 
        	    </optgroup>
        	  </select>
	        </label>
	    </div>
	<div class="form-group">
	    <label for="misc" class="control-label">Lisätietoja, esim. opiskelupaikka ja opiskelijanumero<br>
	    <small>(Merkitse tähän opiskelupaikka jos tilaat kurssikirjan. Korkeakoulukirjastot lainaavat kurssikirjoja yleensä vain omille opiskelijoilleen.)</small>
	        <input type="text" class="form-control" id="misc" name="misc" value="">
	    </label>
	</div>
	<div class="form-group">
	    <fieldset>
	        <legend>Toimitustapa *</legend>
	        <input type="radio" name="delivery" id="laina" value="laina" checked="" required="">   
	        <label for="laina">laina (kirja, mikrojäljenne, dvd tms.)</label><br>
	        <input type="radio" name="delivery" id="valokopio" value="valokopio" required="">
	       <label for="valokopio">valokopio</label> 
	    </fieldset>
	</div>
	<br>
    <h3>Tilattavan aineiston tiedot (täytä soveltuvin osin)</h3>
	<div class="form-group">
	    <label for="author" class="control-label">Teoksen tekijä(t)
	        <input type="text" class="form-control" id="author" name="author" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="title" class="control-label">Teoksen/lehden nimi
	        <input type="text" class="form-control" id="title" name="title" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="edition" class="control-label">Painos/painovuosi
	        <input type="text" class="form-control" id="edition" name="edition" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="volume" class="control-label">Volyymi/numero
	        <input type="text" class="form-control" id="volume" name="volume" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="isbn" class="control-label">ISBN/ISSN-numero
	        <input type="text" class="form-control" id="isbn" name="isbn" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="article_author" class="control-label">Artikkelin tekijä
	        <input type="text" class="form-control" id="article_author" name="article_author" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="article_title" class="control-label">Artikkelin nimi
	        <input type="text" class="form-control" id="article_title" name="article_title" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="pages" class="control-label">Sivut
	        <input type="text" class="form-control" id="pages" name="pages" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="mcopy" class="control-label">Mikrojäljenne (anna myös mahdolliset arkistonumerot)
	        <input type="text" class="form-control" id="mcopy" name="mcopy" value="">
	    </label>
	</div>
	<div class="form-group">
	    <label for="exp_date" class="control-label">Tarvitaan viimeistään
	        <input type="text" class="form-control" id="exp_date" name="exp_date" value="">
	    </label>
	</div>
	<div class="form-group">
	<fieldset>
	    <legend>Saa tilata (<a href="#maksut">ks. maksut</a>) *</legend>
	    <input type="radio" name="allow_order" id="vain kotimaasta / pohjoismaista" value="vain kotimaasta / pohjoismaista" checked="" required="">
	    <label for="vain kotimaasta / pohjoismaista">vain kotimaasta / pohjoismaista</label> <br>
	    <input type="radio" name="allow_order" id="ulkomailta" value="ulkomailta" required=""><label for="ulkomailta">muualta ulkomailta</label>
	</fieldset>
	</div>
	<input type="hidden" name="lang" value="fi">
	<p><label>Täytä vähintään tähdellä (*) merkityt kentät. <br>
	<input type="submit" class="btn btn-primary" name="submit" value="Lähetä kaukopalvelupyyntö">
	</label></p>
    </form>
    </div>    
   </div>
</div>
