<? $this->headTitle($this->translate('Interlibrary loans')); $this->content()->setHeading($this->translate('Interlibrary loans'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="what-is" class="content-section">
        <h2>What are interlibrary loans?</h2>   
        <p>Interlibrary service is a process of sharing resources between libraries. Interlibrary loans open the resources of the complete library network for you. 
        If the material you need is not acquired in Helmet libraries or in the scientific or special libraries in the Metropolitan area, you can request it as an interlibrary loan from 
        elsewhere.</p>
        <p>You can request books, sound recordings, movies, sheet music and microfilms as interlibrary loans. Volumes of periodicals are usually not sent as interlibrary loans. 
        Instead, photocopies of articles from the periodicals can be requested. A book or other material belonging to the collections of some library in the Metropolitan area cannot be 
        requested as an interlibrary loan, even if it is on loan at the moment.
        <strong>If the item you are looking for is on loan, you have to make an ordinary reservation. Interlibrary loans are not meant to bypass local reservations.</strong></p>
        <p>You are able to request an interlibrary loan if you have a Helmet library card and your user rights are valid. 
        You can make the request on the interlibrary loan request form or at the nearest library.</p>
        <p>By placing an interlibrary loan request you agree to pay the interlibrary loan fee (<a href="#fees">cf. interlibrary loan fees</a>). 
        Ordered materials are send to your chosen Helmet library if possible. Interlibrary loans are always subject to the loan periods and other user rules set by the owning library. 
        Some materials are not sent as interlibrary loans, and some are only to be used in the reading rooms of the receiving library.</p>
        <p>Coursebooks are not easily accessible and most university libraries only lend them to their own students. Therefore, please mention at the bottom of the request form where you study.</p>
        <p>So far it is not possible to see your interlibrary loans in Your record at Helmet web library and you cannot renew them as self-service. 
        Please request for renewals by email.</p>
      </div>
     <div id="fees" class="content-section">
        <h2>Fees for interlibrary loans</h2>
        <h3>Espoo City Library</h3>
        <ul class="list-bullets">
          <li>Interlibrary loan from Finland 7 €</li>
          <li>Copy/print: 0,85 €/copy/print or as billed by sending library</li>
        </ul>
        <h3>Helsinki City Library</h3>
        <ul class="list-bullets">
          <li>Interlibrary loan from Finland or other nordic countries 4 €</li>
          <li>Interlibrary loan from the British Library 25 €</li>
          <li>Interlibrary loan from other countries 14-25 €</li>
          <li>Copying: as billed by sending library / at least 4 €</li>
        </ul>
        <h3>Kauniainen Library</h3>
        <ul class="list-bullets">
          <li>Interlibrary fees: as billed by sending library / at least 4 €</li>
        </ul>
        <h3>Vantaa City Library</h3>
        <ul class="list-bullets">    
          <li>Interlibrary loan from Finland: 7 €</li>
          <li>Interlibrary loan from abroad: as billed by sending library / at least 7 €</li>
          <li>Copying: as billed</li>
          <li>Sending copies or sending a fax: 0,80 € / page, at least 5,05 €</li>
        </ul>
      </div>
      <div id="contact-details" class="content-section">
        <h2>Interlibrary service contact information</h2>
        <h3>Espoo City Library</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kaukopalvelu@espoo.fi">kaukopalvelu@espoo.fi</a></li>
          <li>tel. <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
        <h3>Helsinki City Library</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></li>
          <li>tel. <a href="tel:0931085433">09 310 85433</a></li>
        </ul>
        <h3>Kauniainen City Library</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kaukopalvelu@kauniainen.fi">kaukopalvelu@kauniainen.fi</a></li>
          <li>tel. <a href="tel:0504116514">050 411 6514</a></li>
        </ul>
        <h3>Vantaa City Library</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kauko.palvelu@vantaa.fi">kauko.palvelu@vantaa.fi</a></li>
          <li>tel.<a href="tel:0505707776"> 050 570 7776</a></li>
        </ul>
        <h3>Russian Library</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a></li>
          <li>tel. <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
      </div>
      <div id="loan-request" class="content-section">
        <h2>Interlibrary loan request</h2>
        <p>Before placing an interlibrary loan request, please check <a href="/">Helmet</a>, 
        <a href="https://finna.fi/?lng=en-gb" target="_blank" aria-label="Finna. The link opens in a new window.">Finna</a>, and 
        <a href="http://melinda.kansalliskirjasto.fi/F/YJ1C6GDFK4Y7VMNYVR5YKR86Y8YU1JF1CGFIJGH1SSETKH9VMR-16790?func=option-update-lng&amp;file_name=find-b&amp;F2=pc-latin&amp;P_CON_LNG=ENG&amp;local_base=fin01_opac" target="_blank"
        aria-label="Melinda. Link opens in a new window.">
        Melinda</a> catalogues whether the required publication is available in the Helsinki Metropolitan area libraries. Interlibrary loans cannot be made if the 
        required publication is available in any Helsinki Metropolitan area libraries.</p>
        <p>Interlibrary loan request is binding, in other words, by placing an interlibrary loan request you agree to pay the interlibrary 
        loan fee (cf. interlibrary loan fees). The fee for a photocopy is set by the sending library. You will also be charged for 
        uncollected interlibrary loans.</p>
        <p>Ordered materials are send to your chosen HelMet –library and you will be informed when it has arrived by either e-mail or by telephone. Borrowed materials must be 
        returned to the library where they have been checked out (N.B. in Espoo borrowed interlibrary loans can be returned to any library).</p>
        <form action="https://app.helmet-kirjasto.fi/forms/index.php?site=kaukopalvelupyynto&amp;lang=en" method="post">
        <br>
        <h2>Orderer Information</h2>
    	<div class="form-group">
    	    <label for="card" class="control-label">Library card number *
    	        <input type="text" class="form-control" id="card" name="card" value="" required="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="name" class="control-label">Name *
    	        <input type="text" class="form-control" id="name" name="name" value="" required="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="addr" class="control-label">Street address *
    	        <input type="text" class="form-control" id="addr" name="addr" value="" required="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="zipcity" class="control-label">Post number and post office *
    	        <input type="text" class="form-control" id="zipcity" name="zipcity" value="" required="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="email" class="control-label">E-mail
    	        <input type="text" class="form-control" id="email" name="email" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="phone" class="control-label">Telephone
    	        <input type="text" class="form-control" id="phone" name="phone" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="lib" class="control-label">Pickup Library: choose the Helmet branch library from which you wish to pick up your loan/copy *
    	    <select id="lib" class="form-control" name="lib" onchange="onSelect()" required="">
    	      <option value="">Choose a library</option>
    	      <optgroup label="Espoo">
    	        <option name="Entresse Library" value="Entresse Library">Entresse</option> 
    	        <option name="Haukilahti Library" value="Haukilahti Library">Haukilahti</option> 
    	        <option name="Iso Omena Library" value="Iso Omena Library">Iso Omena Library</option> 
    	        <option name="Kalajärvi Library" value="Kalajärvi Library">Kalajärvi</option> 
    	        <option name="Karhusuo Library" value="Karhusuo Library">Karhusuo</option> 
    	        <option name="Kauklahti Library" value="Kauklahti Library">Kauklahti</option> 
    	        <option name="Laajalahti Library" value="Laajalahti Library">Laajalahti</option> 
    	        <option name="Laaksolahti Library" value="Laaksolahti Library">Laaksolahti</option> 
    	        <option name="Lippulaiva library" value="Lippulaiva library">Lippulaiva</option> 
    	        <option name="Nöykkiö Library" value="Nöykkiö Library">Nöykkiö</option> 
    	        <option name="Otaniemi library" value="Otaniemi library">Otaniemi</option> 
    	        <option name="Saunalahti Library" value="Saunalahti Library">Saunalahti</option> 
    	        <option name="Sello Library" value="Sello Library">Sello</option> 
    	        <option name="Suurpelto Library" value="Suurpelto Library">Suurpelto</option> 
    	        <option name="Tapiola Library" value="Tapiola Library">Tapiola</option> 
    	        <option name="Viherlaakso Library" value="Viherlaakso Library">Viherlaakso</option> 
    	       </optgroup>
    	       <optgroup label="Helsinki">
    	        <option name="Arabianranta Library" value="Arabianranta Library">Arabianranta</option> 
    	        <option name="Etelä-Haaga Library" value="Etelä-Haaga Library">Etelä-Haaga</option> 
    	        <option name="Herttoniemi Library" value="Herttoniemi Library">Herttoniemi</option> 
    	        <option name="Itäkeskus Library" value="Itäkeskus Library">Itäkeskus</option> 
    	        <option name="Jakomäki Library" value="Jakomäki Library">Jakomäki</option> 
    	        <option name="Jätkäsaari Library" value="Jätkäsaari Library">Jätkäsaari</option> 
    	        <option name="Kallio Library" value="Kallio Library">Kallio</option> 
    	        <option name="Kannelmäki Library" value="Kannelmäki Library">Kannelmäki</option> 
    	        <option name="Kontula Library" value="Kontula Library">Kontula</option> 
    	        <option name="Käpylä Library" value="Käpylä Library">Käpylä</option> 
    	        <option name="Laajasalo Library" value="Laajasalo Library">Laajasalo</option> 
    	        <option name="Lauttasaari Library" value="Lauttasaari Library">Lauttasaari</option> 
    	        <option name="Malmi Library" value="Malmi Library">Malmi</option> 
    	        <option name="Malminkartano Library" value="Malminkartano Library">Malminkartano</option> 
    	        <option name="Maunula Library" value="Maunula Library">Maunula</option> 
    	        <option name="Munkkiniemi Library" value="Munkkiniemi Library">Munkkiniemi</option> 
    	        <option name="Myllypuro Library" value="Myllypuro Library">Myllypuro</option> 
    	        <option name="Helsinki Central Library Oodi" value="Helsinki Central Library Oodi">Oodi</option> 
    	        <option name="Oulunkylä Library" value="Oulunkylä Library">Oulunkylä</option> 
    	        <option name="Paloheinä Library" value="Paloheinä Library">Paloheinä</option> 
    	        <option name="Pasila Library" value="Pasila Library">Pasila</option> 
    	        <option name="Pitäjänmäki Library" value="Pitäjänmäki Library">Pitäjänmäki</option> 
    	        <option name="Pohjois-Haaga Library" value="Pohjois-Haaga Library">Pohjois-Haaga</option> 
    	        <option name="Puistola Library" value="Puistola Library">Puistola</option> 
    	        <option name="Pukinmäki Library" value="Pukinmäki Library">Pukinmäki</option> 
    	        <option name="Rikhardinkatu Library" value="Rikhardinkatu Library">Rikhardinkatu</option> 
    	        <option name="Roihuvuori Library" value="Roihuvuori Library">Roihuvuori</option> 
    	        <option name="Suomenlinna Library" value="Suomenlinna Library">Suomenlinna</option> 
    	        <option name="Suutarila Library" value="Suutarila Library">Suutarila</option> 
    	        <option name="Tapanila Library" value="Tapanila Library">Tapanila</option> 
    	        <option name="Tapulikaupunki Library" value="Tapulikaupunki Library">Tapulikaupunki</option> 
    	        <option name="Töölö Library" value="Töölö Library">Töölö</option> 
    	        <option name="Vallila Library" value="Vallila Library">Vallila</option> 
    	        <option name="Viikki Library" value="Viikki Library">Viikki</option> 
    	        <option name="Vuosaari Library" value="Vuosaari Library">Vuosaari</option> 
    	        <option name="Kalasatama Library" value="Kalasatama Library">kalasatama</option> 
    	      </optgroup>
    	      <optgroup label="Kauniainen">
    	        <option name="Kauniainen library" value="Kauniainen library">Kauniainen</option> 
    	      </optgroup>
    	      <optgroup label="Vantaa">
    	        <option name="Hiekkaharju Library" value="Hiekkaharju Library">Hiekkaharju</option> 
    	        <option name="Kivistö Library" value="Kivistö Library">Kivistö</option> 
    	        <option name="Koivukylä Library" value="Koivukylä Library">Koivukylä</option> 
    	        <option name="Lumo Library" value="Lumo Library">Lumo</option> 
    	        <option name="Länsimäki Library" value="Länsimäki Library">Länsimäki</option> 
    	        <option name="Martinlaakso Library" value="Martinlaakso Library">Martinlaakso</option> 
    	        <option name="Myyrmäki Library" value="Myyrmäki Library">Myyrmäki</option> 
    	        <option name="Point library" value="Point library">Point</option> 
    	        <option name="Tikkurila Library" value="Tikkurila Library">Tikkurila</option> 
    	    </optgroup>
    	    </select>
    	</label>
    	</div>
    	<div class="form-group">
    	    <label for="misc" class="control-label">Your place of study and student number and/ or other additional information
    	        <input type="text" class="form-control" id="misc" name="misc" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	<fieldset>
    	    <legend>Method of Delivery *</legend>
    	        <input type="radio" name="delivery" id="laina" value="laina" checked="" required="">   <label for="laina">Loan</label> <br>
    	        <input type="radio" name="delivery" id="valokopio" value="valokopio" required="">   <label for="valokopio">Photocopy</label>
    	</fieldset>
    	</div>
        <h3> Material Ordered (Fill in the relevant parts)</h3>
    	<div class="form-group">
    	    <label for="author" class="control-label">Author(s)
    	        <input type="text" class="form-control" id="author" name="author" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="title" class="control-label">Title
    	        <input type="text" class="form-control" id="title" name="title" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="edition" class="control-label">Edition / Date of printing
    	        <input type="text" class="form-control" id="edition" name="edition" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="volume" class="control-label">Volume / Issue
    	        <input type="text" class="form-control" id="volume" name="volume" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="isbn" class="control-label">ISBN / ISSN
    	        <input type="text" class="form-control" id="isbn" name="isbn" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="article_author" class="control-label">Article writer(s)
    	        <input type="text" class="form-control" id="article_author" name="article_author" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="article_title" class="control-label">Name of the article
    	        <input type="text" class="form-control" id="article_title" name="article_title" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="pages" class="control-label">Pages
    	        <input type="text" class="form-control" id="pages" name="pages" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="mcopy" class="control-label">Microfiche (archive numbers, if available)
    	        <input type="text" class="form-control" id="mcopy" name="mcopy" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="exp_date" class="control-label">Needed by (please give a date; after this date, the request will expire)
    	        <input type="text" class="form-control" id="exp_date" name="exp_date" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	<fieldset>
    	    <legend>Can be ordered (<a href="#fees">please see Fees</a>) *</legend>
    	        <input type="radio" name="allow_order" id="vain kotimaasta / pohjoismaista" value="vain kotimaasta / pohjoismaista" checked="" required="">   
    	        <label for="vain kotimaasta / pohjoismaista">Only from Finland / from the Nordic countries</label> <br>
    	        <input type="radio" name="allow_order" id="ulkomailta" value="ulkomailta" required="">   <label for="ulkomailta">From abroad</label>
    	</fieldset>
    	</div>
    	<input type="hidden" name="lang" value="en">
    	<p><label>Please fill in all required fields marked with an asterisk (*).<br>
    	<input type="submit" class="btn btn-primary" name="submit" value="Submit the request">
    	</label></p>
        </form>
   </div>
</div>

