<? $this->headTitle($this->translate('Fjärrlån')); $this->content()->setHeading($this->translate('Fjärrlån'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="vad-ar" class="content-section">
        <h2>Vad är ett fjärrlån?</h2>   
        <p>Fjärrlåneservicen låter dig dra nytta av biblioteksnätet i hela världen. Du kan beställa böcker, skivor, noter, filmer och mikrofilmer som fjärrlån. 
        I allmänhet kan du inte få hela tidskriftsårgångar som fjärrlån, endast kopior av enskilda artiklar. 
        Huvudregeln är att endast sådant material som inte finns i den egna hemortens bibliotek kan beställas som fjärrlån.
        <strong>Om verket du söker är utlånat, reservera på vanligt sätt. Fjärrlånetjänsten är inte avsedd att vara ett sätt att kringgå de lokala reservationerna.</strong>
        </p>
        <p>Du kan göra din fjärrlånebeställning på webben eller i biblioteket, förutsatt att du har ett Helmet-bibliotekskort som är i kraft och att du har rätt att låna.</p>
        <p>Att beställa ett fjärrlån är avgiftsbelagt, se närmare vid avgifter. Vi levererar fjärrlånen eller kopiorna till det bibliotek där du vill hämta materialet. 
        Fjärrlånen följer alltid lånetiderna och övriga regler som det sändande biblioteket har uppsatt. 
        Allt material kan inte fås som fjärrlån och en del kan endast läsas i bibliotekets läsesal, t.ex. avhandlingar och sällsynta böcker.</p>
        <p>Kursboksbibliotek lånar i allmänhet ut sina böcker endast till sina egna studerande. 
        Däremot kan den som studerar i en högskola på annan ort fjärrlåna kurslitteratur från sin egen högskola, trots att boken finns i biblioteken i huvudstadsregionen. 
        Detta är emot fjärrlånens huvudprinciper.</p>
        <p>Om du är student, skriv i blanketten var du studerar och gärna också ditt nummer för att göra behandlingen snabbare.</p>
        <p>Tillsvidare syns fjärrlånen inte i Helmet-nätbibliotekets kunduppgifter, och du kan inte förnya dem själv. Det är enklast att skicka e-post då du vill förnya ditt fjärrlån.</p>
      </div>
     <div id="avgifter" class="content-section">
        <h2>Fjärrlåneavgifter</h2>
        <h3>Esbo stadsbibliotek</h3>
        <ul class="list-bullets">
          <li>fjärrlån från Finland 7 €</li>
          <li>artikelkopior/utskrifter: 075 €/kopia/utskrift eller den avgift det sändande biblioteket debiterar</li>
        </ul>
        <h3>Grankulla stadsbibliotek</h3>
        <ul class="list-bullets">
            <li>den fjärrlåneavgift det sändande biblioteket debiterar eller minst 4 €</li>
        </ul>
        <h3>Helsingfors stadsbibliotek</h3>
        <ul class="list-bullets">
          <li>fjärrlån från Finland och andra nordiska länder 4 €/st.</li>
          <li>lån beställt från British library, 25 €/st.</li>
          <li>lån beställt från övriga bibliotek i utlandet 14 - 25 €/st.</li>
          <li>kopior: den avgift det sändande biblioteket debiterar eller minst 4 €</li>
        </ul>
        <h3>Vanda stadsbibliotek</h3>
        <ul class="list-bullets">
          <li>Beställning från hemlandet 7 € / band</li>
          <li>Beställning från utlandet: enligt räkning, minst 7 € / band</li>
          <li>Beställning av kopior: enligt räkning</li>
          <li>Avsändning av kopia per post eller per fax: 0,80 € /sida, minst 5,05 €</li>
        </ul>
      </div>
      <div id="for-bibliotek" class="content-section">
        <h2>Fjärrlån för bibliotek</h2>
        <p>Till andra bibliotek kan vi fjärrlåna material som biblioteken inte har i sina egna samlingar. Gör beställningen direkt i databasen <a href="/">
        https://www.helmet.finna.fi/</a> eller per e-post <a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a>.</p>
        <p>Fjärrlånetjänsten för Helmet-bibliotekens sköts centralt i Böle bibliotek. Ange därför Böle/fjärrlån för bibliotek som avhämtningsställe då du reserverar materialet. 
        Reserveringarna träffar i första hand material som hör till Helsingfors stadsbibliotek, men allt material i Helmet-katalogen står till förfogande. Ett lån kan förnyas 
        fem gånger ifall verket inte är reserverat.</p><p>Var vänlig och sänd beställningar av artiklar eller mikrofilmade dagstidningar via e-post. Vi lånar ut högst fem 
        mikrofilmrullar per titel.</p>
        <p>Anhållan om cirkulerande samlingar från det Flerspråkiga biblioteket sänds på adressen <a href="mailto:kaukopalvelu@hel.fi">
        kaukopalvelu@hel.fi</a></p>
        <p>Vi sänder fjärrlånen gratis till allmänna bibliotek, av andra bibliotek tar vi en avgift på 7€ /lån.</p>
        <p>Kopiorna kostar 1 € pr sida.</p>
        <p>Centralbiblioteket förmedlar också lån från utländska bibliotek. Ett lån från de nordiska länderna kostar 10 €, från det övriga Europa 15 – 30 €.</p>
        <p>Avgiften för kopior varierar enligt det sändande bibliotekets taxa.</p>
        <h3>Kontaktuppgifter:</h3>
        <p><a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></p>
        <p><a href="tel:0931085432">09-310 85432</a> (fjärrlån från Helsingfors stadsbiblioteks samlingar)<br>
        <a href="tel:0931085433">09-310 85433</a> (fjärrlån förmedlade från utlandet)</p>
        <p>Helsingfors stadsbibliotek<br>
        Fjärrlån<br>
        PB 52401<br>
        00099 HELSINGFORS STAD</p>
      </div>
      <div id="kontaktuppgifter" class="content-section">
        <h2>Fjärrlåneservice kontaktuppgifter</h2>
        <h3>Esbo stadsbibliotek</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@espoo.fi">kaukopalvelu@espoo.fi</a></li>
            <li>tfn <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
        <h3>Helsingfors stadsbibliotek</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@hel.fi">kaukopalvelu@hel.fi</a></li>
            <li>tfn <a href="tel:09 310 85433">0931085433</a></li>
        </ul>
        <h3>Grankulla stadsbibliotek</h3>
        <ul class="list-bullets">
            <li><a href="mailto:kaukopalvelu@kauniainen.fi">kaukopalvelu@kauniainen.fi</a></li>
            <li>tfn <a href="tel:0504116514">050 411 6514</a></li>
        </ul>
        <h3>Vanda stadsbibliotek</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kauko.palvelu@vantaa.fi">kauko.palvelu@vantaa.fi</a></li>
          <li>tfn <a href="tel:0505707776">050 570 7776</a></li>
        </ul>
        <h3>Ryskspråkigt bibliotek</h3>
        <ul class="list-bullets">
          <li><a href="mailto:kauko.rus@espoo.fi">kauko.rus@espoo.fi</a></li>
          <li>tfn <a href="tel:0981657603">09 816 57603</a></li>
        </ul>
      </div>
      <div id="begaran" class="content-section">
        <h2>Begäran om fjärrlån</h2>
        <p>Se först efter i katalogerna <a href="/">Helmet</a>, <a href="https://finna.fi/?lng=sv" target="_blank" 
        aria-label="Finna. Länken öppnas i ett nytt fönster.">Finna</a>
        eller <a href="http://melinda.kansalliskirjasto.fi/F/YJ1C6GDFK4Y7VMNYVR5YKR86Y8YU1JF1CGFIJGH1SSETKH9VMR-16228?func=option-update-lng&amp;file_name=find-b&amp;F2=pc-latin&amp;P_CON_LNG=SWE&amp;local_base=fin01_opac" 
        target="_blank" aria-label="Melinda. Länken öppnas i ett nytt fönster.">
        Melinda</a> om publikationen du söker finns i huvudstadsregionens bibliotek. Fjärrlånet beställs inte om publikationen finns i något bibliotek i huvudstadsregionen.
        <p>Fjärrlåneansökan är bindande. Du förbinder dig att betala en avgift för fjärrlånet (se fjärrlåneavgifter). För kopior debiteras enligt det sändande bibliotekets taxa. 
        Vi debiterar också för fjärrlån som inte avhämtas.</p>
        <p>Det beställda material levereras till det bibliotek du vill inom HelMet. Vi meddelar om dess ankomst per e-post eller 
        telefon. Materialet skall återlämnas till det bibliotek där det hämtades. (obs inom Esbo stadsbibliotek kan du lämna tillbaka ditt fjärrlån till vilket bibliotek du vill).</p>

            <form action="https://app.helmet-kirjasto.fi/forms/index.php?site=kaukopalvelupyynto&amp;lang=sv" method="post">
            <br>
            <h3>Uppgifter om beställaren</h3>
        	<div class="form-group">
        	    <label for="card" class="control-label">Bibliotekskortets nummer *
        	        <input type="text" class="form-control" id="card" name="card" value="" required="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="name" class="control-label">Namn *
        	        <input type="text" class="form-control" id="name" name="name" value="" required="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="addr" class="control-label">Adress *
        	        <input type="text" class="form-control" id="addr" name="addr" value="" required="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="zipcity" class="control-label">Postnummer och -anstalt *
        	        <input type="text" class="form-control" id="zipcity" name="zipcity" value="" required="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="email" class="control-label">E-post
        	        <input type="text" class="form-control" id="email" name="email" value="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="phone" class="control-label">Telefon
        	        <input type="text" class="form-control" id="phone" name="phone" value="">
        	    </label>
        	</div>
        	<div class="form-group">
        	    <label for="lib" class="control-label">Välj det HelMet-bibliotek där du vill hämta ditt lån/dina kopior *
        	    <select id="lib" class="form-control" name="lib" onchange="onSelect()" required="">
        	      <option value="">Välj bibliotek</option>
        	      <optgroup label="Esbo">
        	        <option name="Bastviks bibliotek" value="Bastviks bibliotek">Bastvik</option> 
        	        <option name="Björnkärrs bibliotek" value="Björnkärrs bibliotek">Björnkärr</option> 
        	        <option name="Bredviks bibliotek" value="Bredviks bibliotek">Bredvik</option> 
        	        <option name="Dalsviks bibliotek" value="Dalsviks bibliotek">Dalsvik</option> 
        	        <option name="Entressebiblioteket" value="Entressebiblioteket">Entresse</option> 
        	        <option name="Gröndals bibliotek" value="Gröndals bibliotek">Gröndal</option> 
        	        <option name="Gäddviks bibliotek" value="Gäddviks bibliotek">Gäddvik</option> 
        	        <option name="Hagalunds bibliotek" value="Hagalunds bibliotek">Hagalund</option> 
        	        <option name="Iso Omena bibliotek" value="Iso Omena bibliotek">Iso Omena bibliotek</option> 
        	        <option name="Kalajärvi bibliotek" value="Kalajärvi bibliotek">Kalajärvi</option> 
        	        <option name="Köklax bibliotek" value="Köklax bibliotek">Köklax</option> 
        	        <option name="Lippulaivabiblioteket" value="Lippulaivabiblioteket">Lippulaiva</option> 
        	        <option name="Nöykis bibliotek" value="Nöykis bibliotek">Nöykis</option> 
        	        <option name="Otnäs bibliotek" value="Otnäs bibliotek">Otnäs</option> 
        	        <option name="Sellobiblioteket" value="Sellobiblioteket">Sello</option> 
        	        <option name="Storåkerns bibliotek" value="Storåkerns bibliotek">Storåkern</option> 
        	      </optgroup>
        	      <optgroup label="Helsingfors">
        	        <option name="Arabiastrandens bibliotek" value="Arabiastrandens bibliotek">Arabiastranden</option> 
        	        <option name="Berghälls bibliotek" value="Berghälls bibliotek">Berghäll</option> 
        	        <option name="Bocksbacka bibliotek" value="Bocksbacka bibliotek">Bocksbacka</option> 
        	        <option name="Busholmens bibliotek och infocenter" value="Busholmens bibliotek och infocenter">Busholmen</option> 
        	        <option name="Böle bibliotek" value="Böle bibliotek">Böle</option> 
        	        <option name="Degerö bibliotek" value="Degerö bibliotek">Degerö</option> 
        	        <option name="Drumsö bibliotek" value="Drumsö bibliotek">Drumsö</option> 
        	        <option name="Fiskehamnens bibliotek" value="Fiskehamnens bibliotek">Fiskehamn</option> 
        	        <option name="Gamlas bibliotek" value="Gamlas bibliotek">Gamlas</option> 
        	        <option name="Gårdsbacka bibliotek" value="Gårdsbacka bibliotek">Gårdsbacka</option> 
        	        <option name="Hertonäs bibliotek" value="Hertonäs bibliotek">Hertonäs</option> 
        	        <option name="Jakobacka bibliotek" value="Jakobacka bibliotek">Jakobacka</option> 
        	        <option name="Kasbergets bibliotek" value="Kasbergets bibliotek">Kasberget</option> 
        	        <option name="Kottby bibliotek" value="Kottby bibliotek">Kottby</option> 
        	        <option name="Kvarnbäckens bibliotek" value="Kvarnbäckens bibliotek">Kvarnbäcken</option> 
        	        <option name="Malms bibliotek" value="Malms bibliotek">Malm</option> 
        	        <option name="Malmgårds bibliotek" value="Malmgårds bibliotek">Malmgård</option> 
        	        <option name="Mosabacka bibliotek" value="Mosabacka bibliotek">Mosabacka</option> 
        	        <option name="Munksnäs bibliotek" value="Munksnäs bibliotek">Munksnäs</option> 
        	        <option name="Månsas bibliotek" value="Månsas bibliotek">Månsas</option> 
        	        <option name="Nordsjö bibliotek" value="Nordsjö bibliotek">Nordsjö</option> 
        	        <option name="Norra Haga bibliotek" value="Norra Haga bibliotek">Norra Haga</option> 
        	        <option name="Helsingfors centrumbibliotek Ode" value="Helsingfors centrumbibliotek Ode">Ode</option> 
        	        <option name="Parkstads bibliotek" value="Parkstads bibliotek">Parkstad</option> 
        	        <option name="Richardsgatans bibliotek" value="Richardsgatans bibliotek">Richardsgatan</option> 
        	        <option name="Skomakarböle bibliotek" value="Skomakarböle bibliotek">Skomakarböle</option> 
        	        <option name="Sockenbacka bibliotek" value="Sockenbacka bibliotek">Sockenbacka</option> 
        	        <option name="Stapelstadens bibliotek" value="Stapelstadens bibliotek">Stapelstaden</option> 
        	        <option name="Sveaborgs bibliotek" value="Sveaborgs bibliotek">Sveaborg</option> 
        	        <option name="Svedängens bibliotek" value="Svedängens bibliotek">Svedängen</option> 
        	        <option name="Södra Haga bibliotek" value="Södra Haga bibliotek">Södra Haga</option> 
        	        <option name="Tölö bibliotek" value="Tölö bibliotek">Tölö</option> 
        	        <option name="Vallgårds bibliotek" value="Vallgårds bibliotek">Vallgård</option> 
        	        <option name="Viks bibliotek" value="Viks bibliotek">Vik</option> 
        	        <option name="Åggelby bibliotek" value="Åggelby bibliotek">Åggelby</option> 
        	        <option name="Östra centrums bibliotek" value="Östra centrums bibliotek">Östra centrum</option> 
        	      </optgroup>
        	      <optgroup label="Grankulla">
        	        <option name="Grankulla bibliotek" value="Grankulla bibliotek">Grankulla</option> 
        	      </optgroup>
        	      <optgroup label="Vanda">
        	        <option name="Björkby bibliotek" value="Björkby bibliotek">Björkby</option> 
        	        <option name="Dickursby bibliotek" value="Dickursby bibliotek">Dickursby</option> 
        	        <option name="Kivistö bibliotek" value="Kivistö bibliotek">Kivistö</option> 
        	        <option name="Lumos bibliotek" value="Lumos bibliotek">Lumo</option> 
        	        <option name="Myrbacka bibliotek" value="Myrbacka bibliotek">Myrbacka</option> 
        	        <option name="Mårtensdals bibliotek" value="Mårtensdals bibliotek">Mårtensdal</option> 
        	        <option name="Points bibliotek" value="Points bibliotek">Point</option> 
        	        <option name="Sandkulla bibliotek" value="Sandkulla bibliotek">Sandkulla</option> 
        	        <option name="Västerkulla bibliotek" value="Västerkulla bibliotek">Västerkulla</option> 
        	    </optgroup>
        	    </select>
        	</label>
        	</div>
        	<div class="form-group">
        	    <label for="misc" class="control-label">Studieplats och studentnummer eller övriga tilläggsuppgifter <br><small>(Fyll i fältet om du beställer en kursbok. Högskolebiblioteken lånar vanligen ut kursböcker endast till sina egna studerande.)</small>
        	        <input type="text" class="form-control" id="misc" name="misc" value="">
        	    </label>
        	</div>
        	<div class="form-group">
        	<fieldset>
        	    <legend>Leveranssätt *</legend>
        	        <input type="radio" name="delivery" id="laina" value="laina" checked="" required="">   <label for="laina">lån (bok, mikrokopia, dvd el.dyl.)</label> <br>
        	        <input type="radio" name="delivery" id="valokopio" value="valokopio" required="">   <label for="valokopio">fotokopia</label>
        	</fieldset>
        	</div>
        <h3>Uppgifter om materialet du beställer (fyll i de uppgifter som kan tillämpas)</h3>
    	<div class="form-group">
    	    <label for="author" class="control-label">Författare
    	        <input type="text" class="form-control" id="author" name="author" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="title" class="control-label">Verkets/Tidningens namn
    	        <input type="text" class="form-control" id="title" name="title" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="edition" class="control-label">Upplaga/tryckår
    	        <input type="text" class="form-control" id="edition" name="edition" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="volume" class="control-label">Volym/nummer
    	    <input type="text" class="form-control" id="volume" name="volume" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="isbn" class="control-label">ISBN/ISSN
    	    <input type="text" class="form-control" id="isbn" name="isbn" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="article_author" class="control-label">Artikelförfattare
    	    <input type="text" class="form-control" id="article_author" name="article_author" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="article_title" class="control-label">Artikelns namn
    	    <input type="text" class="form-control" id="article_title" name="article_title" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="pages" class="control-label">Sidor
    	    <input type="text" class="form-control" id="pages" name="pages" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="mcopy" class="control-label">Mikrokopia (ange även kopians arkivnummer)
    	    <input type="text" class="form-control" id="mcopy" name="mcopy" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	    <label for="exp_date" class="control-label">Behövs senast
    	    <input type="text" class="form-control" id="exp_date" name="exp_date" value="">
    	    </label>
    	</div>
    	<div class="form-group">
    	<fieldset>
    	    <legend>Får beställas (<a href="#avgifter">se avgifterna</a>) *</legend>
    	        <input type="radio" name="allow_order" id="vain kotimaasta / pohjoismaista" value="vain kotimaasta / pohjoismaista" checked="" required="">   
    	        <label for="vain kotimaasta / pohjoismaista">bara inom landet / från Norden</label> <br>
    	        <input type="radio" name="allow_order" id="ulkomailta" value="ulkomailta" required="">   <label for="ulkomailta">från övriga bibliotek i utlandet</label>
    	</fieldset>
    	</div>
	    <input type="hidden" name="lang" value="sv">
	   	<p><label>Fält markerade med * är obligatoriska.<br>
    	<input type="submit" class="btn btn-primary" name="submit" value="Skicka">
    	</label></p>
	    </form>
      </div>
   </div>
</div>