<? $this->headTitle($this->translate('Helmet-bibliotekets regler på lätt språk')); $this->content()->setHeading($this->translate('Helmet-bibliotekets regler på lätt språk'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Det här är bibliotekets lättlästa regler.<br>
        Reglerna berättar hur du får använda biblioteket.</p>
        <p>När du vill använda biblioteket är det viktigt<br>
        att du känner till bibliotekets regler<br>
        och att du följer reglerna.</p>
        <p><a href="/Content/kayttosaannot?lng=sv">Här hittar du en längre version av bibliotekets regler</a>,<br>
        men den är inte lättläst.</p>
      </div>
     <div id="vad-ar-helmet" class="content-section">
        <h2>Vad är Helmet?</h2>
        <p>Helmet-biblioteken finns i Helsingfors, Esbo,<br>
        Grankulla och Vanda.<br>
        Helmet är städernas gemensamma bibliotekstjänst.<br><br>
        Helmet är en förkortning av<br>
        ”Helsinki Metropolitan Area Libraries”,<br>
        som betyder bibliotek i huvudstadsregionen.</p>
        <p>Helmet-biblioteken har ett gemensamt användarregister<br>
        och använder samma bibliotekssystem.<br>
        Det betyder att du kan använda alla Helmet-bibliotek<br>
        med samma bibliotekskort.</p>
        <p>Helmet-biblioteken är öppna för alla.<br>
        Du kan läs och låna böcker,<br>
        använda bibliotekets tjänster och lokaler.<br>
        När du använder biblioteket har du också ansvar för<br>
        bibliotekets material, apparater och lokaler.<br>
        Du måste använda dem på rätt sätt<br>
        och följa bibliotekets regler.</p>
        <p>Till bibliotekets material hör till exempel böcker,<br>
        filmer och CD-skivor.</p>
        <h3>Kom ihåg att följa bibliotekets regler</h3>
        <p>När du får ett eget bibliotekskort<br>
        måste du följa bibliotekets regler.<br>
        Om reglerna ändras måste du följa de nya reglerna.<br>
        Alla som använder biblioteket måste följa bibliotekets regler.</p>
        <p>Om till exempel en skola eller ett boende har kort,<br>
        ser en ansvarsperson till att alla som använder kortet<br>
        följer bibliotekets regler.<br>
        Ansvarspersonen är oftast någon som jobbar på skolan<br>
        eller boendet.</p>
        <p>Du hittar bibliotekets regler på bibliotekets webbplats<br>
        på adressen <a href="/Content/asiakkaana-kirjastossa?lng=sv">www.helmet.finna.fi/Content/asiakkaana-kirjastossa?lng=sv</a>
        <p>Där kan du också läsa om hur du kan använda<br>
        bibliotekets apparater.</p>
      </div>
      <div id="bibliotekskort" class="content-section">
        <h2>Bibliotekskort och pinkod</h2>
        <h3>Bibliotekskort</h3>
        <p>Ett bibliotekskort är ett personligt kort som du använder<br>
        till exempel när du vill låna något på biblioteket.<br>
        Kortet är ofta ett litet kort av plast,<br>
        men det kan också vara ett nummer<br>
        eller en streckkod i din telefon.</p>
        <p>När du har ett bibliotekskort kan du låna böcker<br>
        och annat material på biblioteket.</p>
        <p>Du kan få ett eget kort<br>
        på alla Helmet-bibliotek och bokbussar.<br>
        Med kortet får du en pinkod<br>
        som du behöver när du använder kortet.<br>
        Det första kortet du får är gratis.</p>
        
        <h3>Bibliotekskortet är personligt</h3>
        <p>Bibliotekskortet är personligt.<br>
        Ingen annan än du får använda det.<br>
        Du får inte ge ditt kort åt någon annan,<br>
        inte heller då du använder meröppna bibliotek.<br>
        På det meröppna biblioteket finns det ingen personal på plats,<br>
        så du måste låna och returnera böcker på egen hand.</p>
        <p>Om du märker eller tror att någon annan använder ditt kort<br>
        ska du be om hjälp av personalen på biblioteket.</p>
        <p>Du har ansvar för det du lånar på biblioteket.<br>
        Du får inte skada eller tappa bort det du lånar.</p>
        <p>Till exempel skolor och boenden<br>
        kan också ha lånekort.<br>
        Då kan de som jobbar där använda kortet.<br>
        En ansvarsperson på skolan eller boendet<br>
        ger lov att använda kortet.</p>
        
        <h3>Hur får man ett bibliotekskort?</h3>
        <p>Om du vill ha ett kort ska du gå till ett bibliotek<br>
        eller en bokbuss.<br>
        Där ska du visa ett identitetsbevis med foto<br>
        och meddela din adress och din personbeteckning.</p>
        <p>Du måste ha en adress i Finland för att få ett kort.<br>
        Om du inte har en finländsk personbeteckning<br>
        är ditt kort i kraft bara ett år i taget.<br>
        Då måste du varje år gå till biblioteket och be om<br>
        att få ditt kort förnyat.</p><p>Också barn under 15 år kan få ett kort,<br>
        men de måste ha en skriftlig tillåtelse av sin målsman.<br>
        Målsman är till exempel barnets mamma eller pappa.<br>
        Barnet ska vara på plats vid ansökan om kortet.<br>
        Barnets målsman har ansvar för det barnet lånar.<br>
        Om barnet till exempel tappar bort en bok från biblioteket<br>
        måste barnets målsman betala för boken.</p>
        <p>Om till exempel en skola eller ett boende har ett kort<br>
        måste det finnas en ansvarsperson som har ansvar för kortet.<br>
        Ansvarspersonen ser till att bibliotekskortet används rätt.<br>
        Sådana kort är i kraft ett år i taget.</p>
        <h3>Meddela biblioteket om du tappar ditt kort</h3>
        <p>Om ditt kort försvinner<br>
        ska du genast meddela det till biblioteket.<br>
        Om skolans eller boendets kort försvinner<br>
        meddelar ansvarspersonen det till biblioteket.</p>
        <p>Om biblioteket är stängt kan du ringa 09 3108 5309<br>
        och berätta för telefonsvararen att du tappat ditt kort.</p>
        <p>Om du meddelar att ditt kort har försvunnit<br>
        stänger biblioteket av ditt kort.<br>
        Efter det behöver du inte ta ansvar för<br>
        vad någon annan gör med ditt kort.</p>
        
        <h3>Pinkod</h3>
        <p>Du behöver en pinkod när du använder bibliotekets tjänster på nätet,<br>
        bibliotekets automater, bibliotekets datorer<br>
        eller det meröppna biblioteket.</p><p>Du behöver koden till exempel då<br>
        du lånar böcker med en låneautomat.<br>
        Utan kod kan du inte använda automaten.</p>
        <p>Du får din kod på biblioteket eller på bokbussen<br>
        när du visar ditt identitetsbevis.</p>
        
        <h3>Meddela dina personuppgifter till biblioteket</h3>
        <p>Det är viktigt att biblioteket har rätt kontaktuppgifter till dig.<br>
        Om din adress, din mejladress eller ditt namn ändras,<br>
        ska du meddela det till biblioteket.</p>
        <p>Du kan kolla dina kontaktuppgifter<br>
        om du loggar in på bibliotekets webbplats<br>
        på adressen <a href="/">www.helmet.finna.fi</a>.<br>
        Där finns en sida med dina kontaktuppgifter.</p>
        <p>Biblioteket har ett register med kontaktuppgifter<br>
        till alla användare, alltså alla som har ett lånekort.<br>
        I registret finns också ansvarspersonernas kontaktuppgifter.</p>
        <p>När biblioteket sparar kontaktuppgifterna<br>
        måste biblioteket följa lagen.<br>
        Lagen säger att biblioteket får spara användarnas personbeteckning.<br>
        Du har rätt att veta vilken information biblioteket sparar om dig.<br>
        Du får veta det om du går till bibliotekets kundtjänst<br>
        och visar ditt identitetsbevis.<br>
        Om du är målsman till ett barn under 15 år som har lånekort,<br>
        kan du ta reda på information om barnets lån,<br>
        till exempel om barnet har glömt att lämna tillbaka lånen.<br>
        Då får du också information om avgifter.<br>
        Om du är ansvarsperson till exempel för skolans kort<br>
        kan du se information om skolan och skolans lån.</p>
        <p>Biblioteket har en registerbeskrivning som berättar<br>
        vilka personuppgifter biblioteket sparar, varför biblioteket sparar dem<br>
        och hur biblioteket skyddar dem.<br>
        Du kan läsa registerbeskrivningen på bibliotekets webbplats<br>
        på adressen <a href="/Content/asiakkaana-kirjastossa?lng=sv">www.helmet.finna.fi/Content/asiakkaana-kirjastossa?lng=sv</a>.</p>
      </div>
      <div id="att-lana" class="content-section">
        <h2>Att låna, returnera och förnya lån</h2>
        <h3>Att låna</h3>
        <p>Du kan ha högst 100 lån på samma gång.<br>
        Lånetiden är 1–28 dygn.<br>
        Lånetiden är olika lång för olika material.<br>
        Du hittar mera info om lånetiderna<br>
        på adressen <a href="/Content/laina-ajat-ja-maksut?lng=sv">https://helmet.finna.fi/Content/laina-ajat-ja-maksut?lng=sv</a>.</p>
        <p>Det du lånar på biblioteket har en förfallodag.<br>
        Förfallodag är den dag<br>
        då du senast måste lämna tillbaka det du lånat.<br>
        Förfallodagen står på kvittot du får<br>
        när du lånar något.</p><p>Det finns åldersgränser för lån av spel och filmer.<br>
        Du får bara låna en film eller ett spel<br>
        om du är tillräckligt gammal för det.<br>
        Om åldersgränsen för ett spel är 15 år<br>
        måste du vara 15 år eller äldre för att få låna det.<br>
        I Finland är det KAVI och MEKU som bestämmer om åldersgränserna.<br>
        KAVI är Nationella audiovisuella institutet<br>
        och MEKU enheten för mediefostran och bildprogram.</p>
        
        <h3>Att returnera</h3>
        <p>Lämna tillbaka det du lånat senast på förfallodagen.<br>
        Du kan lämna tillbaka dina lån<br>
        på alla Helmet-bibliotek.</p>
        <p>Du kan välja att få ett kvitto<br>
        när du lämnar tillbaka det du lånat.</p>
        <p>När förfallodagen närmar sig<br>
        kan du få ett meddelande om det två dygn innan.<br>
        Du får meddelandet per mejl<br>
        om biblioteket har din mejladress.</p>
        <p>En del bibliotek har en returlucka.<br>
        Då kan du lämna tillbaka det du lånat<br>
        också då biblioteket är stängt.<br>
        Bibliotekets personal märker att du lämnat tillbaka ditt lån<br>
        först nästa dag biblioteket är öppet.</p>
        
        <h3>Att förnya ett lån</h3>
        <p>Du kan förnya dina lån, alltså låna samma material igen,<br>
        fem gånger i rad.<br>
        Du kan förnya dina lån på biblioteket, i bokbussen<br>
        eller på internet på adressen <a href="/">www.helmet.finna.fi</a>.<br>
        Om du förnyar lånen på internet måste du logga in.<br>
        Då behöver du bibliotekskortets nummer och din pinkod.</p>
        <p>Du kan inte förnya dina lån, till exempel en bok du lånat<br>
        om någon annan har reserverat samma bok.</p>
        <p>Om du har förlorat din lånerätt<br>
        kan du inte heller förnya ditt lån.</p>
        <p>Du kan ändå inte förnya lånet av alla böcker eller annat material.<br>
        Till exempel Bestseller-material och en del föremål<br>
        kan du låna bara en gång.</p>
      </div>
      <div id="att-reservera" class="content-section">
        <h2>Att reservera och fjärrlåna</h2>
        <h3>Att reservera</h3>
        <p>Om du vill kan du reservera material,<br>
        till exempel en bok.<br>
        Reservera betyder att du meddelar att du vill låna boken<br>
        och vill att personalen sparar den åt dig.</p>
        <p>Du kan reservera boken på biblioteket<br>
        eller på internet på adressen <a href="/">www.helmet.finna.fi</a><br>
        Om du reserverar på internet måste du logga in.<br>
        Då behöver du numret på ditt bibliotekskort<br>
        och din pinkod.</p>
        <p>Du kan reservera 100 böcker eller andra material samtidigt.<br>
        Du får ett meddelande när du kan hämta det du reserverat<br>
        på biblioteket.<br>
        Meddelandet kan komma per post eller mejl.</p>
        <p>Vissa material kan du inte reservera,<br>
        till exempel föremål som verktyg eller skridskor.<br>
        Då måste du gå till biblioteket för att låna dem.</p>
        
        <h3>Fjärrlån</h3>
        <p>Du kan också reservera material<br>
        som inte finns på Helmet-biblioteket.<br>
        Då kan biblioteket fjärrlåna det från ett annat bibliotek<br>
        i Finland eller utomlands.<br>
        Fjärrlånet måste du betala för.</p>
        <p>Om materialet du vill låna<br>
        finns på ett annat bibliotek i huvudstadsregionen,<br>
        till exempel i ett universitets bibliotek,<br>
        går det inte att fjärrlåna.<br>
        Då måste du gå till biblioteket som har materialet<br>
        och be om att få låna det där.</p>
      </div>
      <div id="avgifter" class="content-section">
        <h2>Avgifter</h2>
        <p>För det mesta kostar det ingenting att använda biblioteket.<br>
        Men om du lämnar tillbaka det du lånat för sent,<br>
        måste du betala en förseningsavgift,<br>
        alltså en liten summa pengar.</p>
        <p>Om du tappar bort det du lånat<br>
        måste du ersätta det, alltså betala för det.</p>
        <p>Om du inte hämtar material i tid som du har reserverat<br>
        måste du betala en avgift.</p>
        <p>Vissa av bibliotekets tjänster måste man också betala för,<br>
        till exempel om du fjärrlånar något.</p>
        <p>Du kan läsa mera om vad som kostar<br>
        på adressen <a href="/Content/laina-ajat-ja-maksut?lng=sv" target="_top">https://helmet.finna.fi/Content/laina-ajat-ja-maksut?lng=sv</a>.</p>
        <p>Om något du lånar skadar dina apparater,<br>
        ansvarar biblioteket inte för det.<br>
        Det betyder att biblioteket inte betalar<br>
        till exempel om du lånar ett spel<br>
        och spelet söndrar din dator eller din kompis dator.</p>
        
        <h3>Förseningsavgift</h3>
        <p>Om dina lån är försenade,<br>
        alltså om du inte har lämnat tillbaka det du lånat i tid,<br>
        skickar biblioteket två påminnelser till dig.</p>
        <p>Den första påminnelsen skickar biblioteket till dig<br>
        14 dygn efter förfallodagen.<br>
        Den andra påminnelsen skickar biblioteket till dig<br>
        28 dygn efter förfallodagen.<br>
        Den första påminnelsen kan du få per mejl om du vill.</p>
        <p>När du får påminnelsen<br>
        måste du genast lämna tillbaka det du lånat<br>
        och betala förseningsavgiften.</p>
        
        <h3>Vad händer om du inte betalar din förseningsavgift?</h3>
        <p>Om du inte lämnar tillbaka materialet<br>
        och inte heller betalar förseningsavgiften<br>
        för biblioteket saken vidare till en indrivningsbyrå,<br>
        men bara om du är över 18 år.<br>
        Biblioteket för saken vidare till indrivningsbyrån<br>
        ungefär 60 dygn efter förfallodagen.<br>
        Då tvingas du betala en ännu större summa.</p>
        <p>Du kan läsa mera om indrivning<br>
        på adressen <a href="/Content/laina-ajat-ja-maksut?lng=sv" target="_top">https://helmet.finna.fi/Content/laina-ajat-ja-maksut?lng=sv</a>.</p>
        
        <h3>Att förlora sin lånerätt</h3>
        <p>Om du inte betalar dina avgifter till biblioteket<br>
        kan du förlora din lånerätt.<br>
        Det betyder att du inte får låna något på biblioteket.</p>
        <p>Du kan förlora din lånerätt om</p>
        <ul class="list-bullets">
          <li>dina lån är försenade mer än 28 dygn</li>
          <li>om du har tappat bort något du lånat på biblioteket</li>
          <li>om du har skadat något du lånat på biblioteket</li>
          <li>om du har låtit bli att betala så många avgifter</li>
        </ul>
        <p>att du nått maximigränsen för det.</p>
        <p>Det finns ett undantag till den här regeln:<br>
        Om du har skuldsanering<br>
        och din skuld till biblioteket är med i din betalningsplan<br>
        får du fortsätta låna på biblioteket.<br>
        Du kan läsa mera om maximigränsen<br>
        på adressen <a href="/Content/laina-ajat-ja-maksut?lng=sv" target="_top">https://helmet.finna.fi/Content/laina-ajat-ja-maksut?lng=sv</a>.</p>
        
        <h3>Att få tillbaka sin lånerätt</h3><p>Du får tillbaka din lånerätt när</p>
        <ul class="list-bullets">
          <li>du lämnar tillbaka det försenade lånet</li>
          <li>du betalar för det material du skadat eller tappat bort</li>
          <li>du betalar dina avgifter till biblioteket</li>
        </ul>
        <p>Om biblioteket har fört saken vidare till en indrivningsbyrå<br>
        måste du betala till indrivningsbyrån<br>
        och indrivningsbyrån betalar sedan till biblioteket.<br>
        Till slut kontrollerar biblioteket att betalningen är rätt.<br>
        Om allt är i sin ordning<br>
        får du låna igen.</p>
      </div>
      <div id="forlora-nyttjanderatt" class="content-section">
        <h2>Att förlora sin nyttjanderätt</h2><p>Om du inte följer reglerna<br>
        kan du förlora din nyttjanderätt,<br>
        alltså din rätt att använda biblioteket.<br>
        Då får du inte alls använda biblioteket.<br>
        Det kallas också för att bli avstängd från biblioteket.</p>
        <p>Du kan bli avstängd från biblioteket<br>
        till exempel om du söndrar något på biblioteket,<br>
        om du beter dig mycket illa på biblioteket,<br>
        eller om du skadar andra människor på biblioteket.<br>
        Du kan bli avstängd från biblioteket i högst 30 dagar.</p>
        <p>Då gör biblioteket ett skriftligt beslut om avstängningen.<br>
        Innan du blir avstängd från biblioteket<br>
        har du rätt att berätta din version av det som hänt<br>
        och du kan ansöka om att bibliotekets beslut ska ändras.</p>
        <p>Om du blir avstängd från biblioteket<br>
        antecknar biblioteket det i sitt kundregister.<br>
        Biblioteket tar bort anteckningen från kundregistret<br>
        när du får använda biblioteket igen.</p>
      </div>
      <div id="hur-fungerar-regler" class="content-section">
        <h2>Hur fungerar bibliotekets regler?</h2>
        <p>Också bokbussarna, anstaltsbiblioteken<br>
        och bibliotekens hemservice följer de här reglerna,<br>
        om det är möjligt.<br>
        Reglerna ändras bara genom ett officiellt beslut.</p>
        <p>De här reglerna gäller från 1.2.2023<br>
        och reglerna gäller tills vidare.<br>
        De gamla reglerna från 1.2.2021 gäller inte mera.<br>
        Reglernas uppsägningstid är sex månader.</p>
      </div>
      <div id="mera-info" class="content-section">
        <h2>Mera info</h2>
        <ul class="list-bullets">
            <li><a href="https://helmet.finna-pre.fi/Content/laina-ajat-ja-maksut?lng=sv">Lånetider och avgifter</a></li>
            <li><a href="https://helmet.finna-pre.fi/Content/kaukopalvelu?lng=sv">Fjärrlån</a></li>
            <li><a href="https://helmet.finna-pre.fi/Content/kayttosaannot?lng=sv">Användningsregler (låneregler)</a></li>
        </ul>
      </div>
   </div>
</div>