<? $this->headTitle($this->translate('Helmet-kirjaston käyttösäännöt selkokielellä')); $this->content()->setHeading($this->translate('Helmet-kirjaston käyttösäännöt selkokielellä'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Tervetuloa Helmet-kirjastojen käyttäjäksi!</p>
        <p>Kun haluat käyttää kirjastoa,<br>
        on tärkeää,<br>
        että tiedät nämä käyttösäännöt ja noudatat niitä.</p>
      </div>
     <div id="helmet" class="content-section">
        <h2>Mikä on Helmet?</h2>
        <p>Helmet-kirjastot toimivat<br>
        Helsingissä, Espoossa, Kauniaisissa ja Vantaalla.<br>
        Helmet on kaupunkien yhteinen kirjastopalvelu.</p><p>Helmet-lyhenne tulee sanoista<br>
        ”Helsinki Metropolitan Area Libraries”,<br>
        suomeksi ”pääkaupunkiseudun kirjastot”.</p><p>Helmet-kirjastoilla on<br>
        yhteinen asiakasrekisteri ja kirjastojärjestelmä.<br>
        Se tarkoittaa,<br>
        että voit käyttää kaikkia Helmet-kirjastoja,<br>
        kun sinulla on Helmet-kirjastokortti.</p><p>Helmet-kirjastot ovat kaikille avoimia.<br>
        Voit lukea ja lainata kirjoja<br>
        ja käyttää palveluita ja kirjaston tiloja.<br>
        Kun olet kirjaston käyttäjä,<br>
        myös sinä olet vastuussa<br>
        kirjaston aineistoista, välineistä ja tiloista.<br>
        Niitä ei saa käyttää väärin.</p>
      </div>
      <div id="noudata-saantoja" class="content-section">
        <h2>Muista noudattaa kirjaston sääntöjä</h2>
        <p>Kun saat oman kirjastokortin,<br>
        sitoudut noudattamaan kirjaston sääntöjä.<br><br>
        Samat säännöt koskevat myös yhteyshenkilöä.<br>
        Yhteyshenkilö on<br>
        koulun, päiväkodin tai yhteisön työntekijä,<br>
        jolla on yhteisön kirjastokortti.<br>
        Yhteyshenkilö vastaa siitä,<br>
        että kaikki yhteisön työntekijät<br>
        käyttävät kirjastokorttia oikein.</p>
      </div>
      <div id="kirjastokortti" class="content-section">
        <h2>Kirjastokortti ja tunnusluku</h2>
        <h3>Kirjastokortti</h3>
        <p>Kun sinulla on kirjastokortti,<br>
        sinulla on oikeus lainata kirjastosta<br>
        kirjoja tai muuta aineistoa.</p>
        <p>Saat oman kirjastokortin<br>
        mistä tahansa Helmet-kirjastosta tai kirjastoautosta.</p>
        <p>Kirjastokortin mukana saat tunnusluvun,<br>
        jonka avulla kortti toimii.<br>
        Ensimmäinen kirjastokortti on ilmainen.</p>
        <h3>Kirjastokortti on henkilökohtainen</h3>
        <p>Kirjastokortti on henkilökohtainen.<br>
        Sitä ei saa käyttää kukaan muu.<br>
        Et saa antaa korttia muille silloinkaan,<br>
        kun käytät omatoimikirjastoa.<br>
        Omatoimikirjastossa ei ole paikalla kirjaston työntekijää,<br>
        vaan asiakas lainaa ja palauttaa<br>
        kirjat ja muun aineiston itsenäisesti.</p>
        <p>Jos huomaat tai pelkäät,<br>
        että joku toinen käyttää kirjastokorttiasi,<br>
        pyydä apua kirjaston työntekijöiltä.</p>
        <p>Kun lainaat kirjastosta kirjoja<br>
        tai muuta aineistoa, olet vastuussa niistä.<br>
        Ne täytyy palauttaa hyvässä kunnossa takaisin.</p>
        <p>Jos kirjastokortti on jonkin yhteisön<br>
        yhteinen kortti,<br>
        sitä voivat käyttää myös sen muut työntekijät.<br>
        Kortista on vastuussa yhteyshenkilö,<br>
        hän antaa luvan kortin käyttöön.</p>
        <p>Jos huomaat tai pelkäät,<br>
        että joku toinen käyttää luvatta kirjastokorttiasi,<br>
        pyydä apua kirjaston työntekijöiltä.</p>
        <p>Kun lainaat kirjastosta kirjoja tai muuta aineistoa,<br>
        olet vastuussa niistä.<br>
        Ne täytyy palauttaa hyvässä kunnossa takaisin.</p>
        
        <h3>Miten kirjastokortin saa?</h3>
        <p>Saat kirjastokortin,<br>
        kun todistat henkilöllisyytesi<br>
        ja ilmoitat osoitteesi.<br>
        Saat oman kirjastokortin<br>
        mistä tahansa Helmet-kirjastosta tai kirjastoautosta.</p>
        <p>Saat kirjastokortin vain,<br>
        jos sinulla on osoite Suomessa.<br>
        Sinun täytyy myös näyttää henkilötodistus,<br>
        jossa on valokuvasi ja henkilötunnuksesi.<br>
        Kirjastossa käyvät seuraavat henkilötodistukset:</p>
        <ul class="list-bullets">
          <li>EU-maiden henkilötodistukset</li>
          <li>passi</li>
          <li>suomalainen ajokortti</li>
          <li>kuvallinen KELA-kortti, alle 18-vuotiailta myös kuvaton KELA-kortti</li>
          <li>Suomessa sijaitsevan vastaanottokeskuksen asukaskortti</li>
          <li>Maahanmuuttoviraston myöntämä oleskelulupakortti.</li>
        </ul>
        <p>Jos sinulla ei ole suomalaista henkilötunnusta,<br>
        kirjastokorttisi on voimassa vuoden kerrallaan.</p>
        <p>Alle 15-vuotias lapsi saa kirjastokortin vain,<br>
        jos hänen huoltajansa suostuu siihen.<br>
        Huoltaja on yleensä isä tai äiti,<br>
        joskus myös muu vastuuhenkilö.<br>
        Huoltajan täytyy antaa kirjallinen suostumus siihen,<br>
        että lapselle voi antaa oman kirjastokortin.<br>
        Lapsella tulee olla mukana henkilötodistus.<br>
        Lapsen täytyy olla paikalla kirjastossa,<br>
        kun kirjastokorttia haetaan.<br>
        Huoltaja on vastuussa lainoista,<br>
        kun alle 15-vuotias lainaa jotakin kirjastosta.<br>
        Jos nuori esimerkiksi kadottaa kirjaston kirjan,<br>
        huoltajan täytyy korvata se.</p>
        <p>Kirjastokortin voi saada myös yhteisö.<br>
        Yhteisöllä täytyy olla yhteyshenkilö,<br>
        joka on vastuussa kortin käytöstä.<br>
        Yhteyshenkilö huolehtii siitä,<br>
        että yhteisön työntekijät<br>
        käyttävät kirjastokorttia oikein.<br>
        Yhteisöjen kirjastokortit ovat voimassa<br>
        vuoden kerrallaan.</p>
        
        <h3>Ilmoita kirjastokortin katoamisesta kirjastoon</h3>
        <p>Jos kirjastokorttisi katoaa,<br>
        ilmoita siitä heti kirjastoon.<br>
        Jos kadoksissa on<br>
        yhteisön yhteinen kirjastokortti,<br>
        katoamisesta ilmoittaa yhteyshenkilö.</p>
        <p>Jos kirjasto on kiinni,<br>
        voit ilmoittaa kortin katoamisesta puhelinvastaajaan.<br>
        Soita silloin numeroon 09 3108 5309.</p>
        <p>Kun ilmoitat kirjastokortin kadonneeksi,<br>
        kirjasto poistaa sen käytöstä.<br>
        Jos joku toinen yrittää lainata kortillasi<br>
        katoamisilmoituksen jälkeen,<br>
        et ole enää vastuussa lainoista.</p>
        
        <h3>Tunnusluku</h3>
        <p>Kirjastokorttiin tarvitaan tunnusluku.<br>
        Sen avulla voit käyttää</p>
        <ul class="list-bullets">
          <li>kirjaston verkkopalveluja</li>
          <li>automaatteja</li>
          <li>tietokoneita</li>
          <li>omatoimikirjastoa.</li>
        </ul>
        <p>Tarvitset tunnusluvun esimerkiksi silloin,<br>
        kun lainaat aineistoa lainausautomaatilla,<br>
        Ilman tunnuslukua et voi käyttää automaattia.</p>
        <p>Tunnusluvun saat kirjastosta tai kirjastoautosta,<br>
        kun näytät henkilötodistuksen.<br>
        Tunnuslukua ei saa sähköpostilla tai puhelimessa.</p>
        
        <h3>Ilmoita omat tietosi kirjastoon</h3>
        <p>Pidä huolta siitä,<br>
        että yhteystietosi ovat oikein kirjaston asiakasrekisterissä.<br>
        Jos osoitteesi, sähköpostiosoitteesi tai nimesi muuttuu,<br>
        ilmoita siitä kirjastoon.<br>
        Voit tarkistaa omat tietosi,<br>
        kun kirjaudut Helmet-sivustolle osoitteessa <a href="/">www.helmet.finna.fi</a>.</p>
        <p>Toimi näin:</p>
        <ol class="list-numbers">
          <li>Osoitteessa www.helmet.finna.fi näet etusivun,</li>
          <li>jonka oikeassa yläkulmassa lukee Kirjaudu.</li>
          <li>Klikkaa kohtaa Kirjaudu.</li>
          <li>Tämän jälkeen näet kaksi tekstikenttää.</li>
          <li>Kirjoita ensimmäiseen kirjastokorttisi numero</li>
          <li>ja toiseen tunnuslukusi eli PIN-koodisi.</li>
        </ol>
        <p>Nyt olet kirjautuneena kirjaston verkkopalveluun.<br>
        Sieltä löydät yhteystietosi Omat tiedot -sivulta.</p>
        <p>Kaikkien lainaajien henkilötiedot ovat<br>
        kirjaston asiakasrekisterissä.<br>
        Siellä ovat myös<br>
        vastuuhenkilöiden ja yhteyshenkilöiden tiedot.</p>
        <p>Kirjasto vastaa siitä,<br>
        että kirjastolle ilmoitetut tiedot<br>
        ovat asiakasrekisterissä oikein.</p>
        <p>Kirjasto noudattaa asiakasrekisterin pitämisessä<br>
        henkilötietolakia.<br>
        Henkilötietolain mukaan kirjastolla on<br>
        oikeus rekisteröidä asiakkaan henkilötunnus.</p>
        <p>Sinulla on oikeus tarkistaa,<br>
        mitä tietoja sinusta on kirjaston asiakasrekisterissä.<br>
        Saat tiedot kirjaston asiakaspalvelusta,<br>
        kun näytät henkilötodistuksesi.<br>
        Jos olet alle 15-vuotiaan lapsen huoltaja,<br>
        voit nähdä hänen tietonsa,<br>
        esimerkiksi tiedon myöhästyneistä lainoista.<br>
        Saat myös tiedot maksamattomista maksuista.<br>
        Jos olet yhteisön yhteyshenkilö,<br>
        sinulla on oikeus tarkistaa yhteisön tiedot.</p>
        <p>Jos haluat lisää tietoa asiakasrekisteristä,<br>
        saat sitä rekisteriselosteesta.<br>
        Asiakasrekisteriseloste on nähtävissä kirjastoissa.<br>
        Lisäksi se on Helmet-sivustolla<br>
        osoitteessa <a href="/Content/asiakasrekisteriseloste">https://helmet.finna.fi/Content/asiakasrekisteriseloste</a><br>
        Asiakasrekisteriseloste ei ole selkokielinen.</p>
      </div>
      <div id="lainaaminen" class="content-section">
        <h2>Lainaaminen, palauttaminen ja uusiminen</h2>
        <h3>Lainaaminen</h3>
        <p>Laina-ajat ovat 1–28 vuorokautta.<br>
        Eri aineistoissa on erilaiset laina-ajat.<br>
        Löydät tarkemmat laina-ajat<br>
        osoitteessa <a href="/Content/laina-ajat-ja-maksut">https://helmet.finna.fi/Content/laina-ajat-ja-maksut</a>.<br>
        Sinulla voi olla samaan aikaan enintään 100 lainaa.</p>
        <p>Kun lainaat kirjoja tai muuta materiaalia,<br>
        saat lainalle aina eräpäivän.<br>
        Eräpäivä on päivä,<br>
        jolloin aineisto pitää viimeistään palauttaa.<br>
        Eräpäivät näkyvät eräpäiväkuitissa,<br>
        jonka saat lainauksen yhteydessä.</p>
        <p>Elokuvia tai pelejä ei lainata asiakkaalle,<br>
        joka ei täytä ikärajoja.<br>
        Esimerkiksi alle 15-vuotias ei voi lainata<br>
        elokuvia tai pelejä,<br>
        joiden ikäraja on 15 vuotta.<br>
        Ikärajoista Suomessa päättävät<br>
        Kansallinen audiovisuaalinen instituutti Kavi<br>
        sekä Mediakasvatus- ja kuvaohjelmayksikkö MEKU.</p>
        
        <h3>Palauttaminen</h3>
        <p>Palauta lainasi viimeistään eräpäivänä.<br>
        Sinun ei tarvitse palauttaa aineistoa<br>
        samaan kirjastoon, josta lainasit sen.<br>
        Voit palauttaa lainsit mihin tahansa Helmet-kirjastoon.<br><br>
        Jos haluat, saat palautuksesta kuitin.</p>
        <p>Joissakin kirjastoissa on käytössä palautusluukku.<br>
        Lainat voi palauttaa luukun kautta silloin,<br>
        kun kirjasto on kiinni.<br>
        Kirjasto merkitsee aineiston palautetuksi<br>
        seuraavana aukiolopäivänä.<br>
        Jos jotakin esimerkiksi katoaa palautusluukusta,<br>
        joudut korvaamaan kadonneen aineiston.</p>
        <p>Kun eräpäivä lähestyy,<br>
        voit saada siitä ilmoituksen<br>
        kaksi vuorokautta ennen eräpäivää.<br>
        Saat ilmoituksen sähköpostiin,<br>
        jos kirjastolla on sähköpostiosoitteesi.<br>
        Sinun täytyy kuitenkin ilmoittaa kirjastoon,<br>
        että haluat ilmoituksia sähköpostiisi.</p>
        <h3>Uusiminen</h3>
        <p>Voit uusia lainasi eli lainata saman aineiston uudestaan<br>
        viisi kertaa peräkkäin.<br>
        Lainoja voi uusia kirjastossa, kirjastoautossa<br>
        tai internetissä osoitteessa <a href="/">www.helmet.finna.fi</a>.<br>
        Siellä sinun täytyy kirjautua Omat tiedot -sivulle.<br>
        Tarvitset kirjautumiseen kirjastokortin numeron ja tunnusluvun.</p>
        <p>Et voi uusia lainoja,<br>
        jos joku toinen on tehnyt varauksen samasta aineistosta.<br>
        Et voi uusia lainoja myöskään silloin,<br>
        jos olet menettänyt lainausoikeutesi.</p>
        <p>Kaikkea aineistoa ei kuitenkaan voi uusia.<br>
        Esimerkiksi Bestseller-aineistoa ei voi uusia<br>
        ja useimpia lainattavia esineitä ei voi lainata uudestaan.</p>
      </div>
      <div id="varaaminen" class="content-section">
        <h2>Varaaminen ja kaukolainat</h2>
        <h3>Voit varata kirjaston aineistoja</h3>
        <p>Jos haluat varata aineistoa,<br>
        voit tehdä varauksen kirjastossa.<br>
        Varauksia voi tehdä myös kirjaston internetsivuilla<br>
        osoitteessa <a href="/">www.helmet.finna.fi</a>.<br>
        Siellä sinun täytyy ensin kirjautua omiin tietoihisi.<br>
        Tarvitset kirjautumiseen<br>
        oman kirjastokorttisi numeron ja tunnusluvun.<br>
        (Katso kirjautumisohjeet näiden sääntöjen osiosta<br>
        Ilmoita omat tietosi kirjastoon.)</p>
        <p>Sinulla voi olla samaan aikaan 100 varausta.<br>
        Saat ilmoituksen,<br>
        kun voit hakea varaamasi aineiston kirjastosta.<br>
        Ilmoitus voi tulla kirjeellä,<br>
        sähköpostilla tai tekstiviestillä.</p>
        <p>Kaikkea aineistoa ei voi kuitenkaan varata,<br>
        esimerkiksi tavaroita, kuten työkaluja tai luistimia.<br>
        Molempia voi lainata kirjastosta.</p>
        
        <h3>Kaukolainat</h3>
        <p>Jos haluat varata aineistoa,<br>
        jota ei löydy Helmet-kirjastoista,<br>
        kirjasto voi kaukolainata sen muualta Suomesta tai ulkomailta.</p>
        <p>Kaukolainat ovat maksullisia.</p>
        <p>Kirjastot eivät kaukolainaa aineistoa,<br>
        jonka saa muista pääkaupunkiseudun kirjastoista,<br>
        esimerkiksi jostakin tieteellisestä kirjastosta<br>
        tai erikoiskirjastosta.</p>
      </div>
      <div id="maksut" class="content-section">
        <h2>Kirjaston maksut</h2>
        <p>Kirjaston käyttö ei yleensä maksa mitään.<br>
        Jos kuitenkin palautat aineistoa myöhässä,<br>
        sinun täytyy maksaa myöhästymismaksu.<br>
        Jos et hae varaamaasi aineistoa,<br>
        sinun täytyy maksaa siitä maksu.<br>
        Ja jos kadotat kirjaston omaisuutta,<br>
        sinun täytyy korvata se.<br>
        Myös erityispalveluista täytyy maksaa,<br>
        esimerkiksi kaukolainoista.</p>
        <p>Voit tarkistaa,<br>
        millaisia maksuja kirjastossa on.<br>
        Löydät kaikki maksut osoitteessa <a href="/Content/laina-ajat-ja-maksut#yhteiset-maksut">https://helmet.finna.fi/Content/laina-ajat-ja-maksut</a>.<br>
        <p>Jos lainaamasi aineisto vahingoittaa laitteitasi,<br>
        kirjasto ei vastaa siitä,<br>
        Kirjasto ei siis maksa korvausta laitteesi vahingoista.<br>
        Kirjasto ei myöskään maksa vahingoista,<br>
        jos vahingossa rikot jotakin kirjaston työkaluilla.</p>
        
        <h3>Myöhästymismaksu ja korvaaminen</h3>
        <p>Jos palautat lainasi myöhässä,<br>
        sinun täytyy maksaa myöhästymismaksu.<br>
        Maksua kertyy jokaiselta myöhästymispäivältä,<br>
        kunnes maksujen enimmäismäärä on täynnä.</p>
        <p>Lasten- ja nuortenosaston aineistosta<br>
        ei kuitenkaan tarvitse maksaa myöhästymismaksua.</p>
        <p>Myöhästymismaksu täytyy maksaa<br>
        myös siinä tapauksessa,<br>
        että et voi uusia lainoja jonkin teknisen häiriön takia.</p>
        <p>Tekninen häiriö on esimerkiksi se,<br>
        että internet ei toimi.</p>
        <p>Jos kadotat tai vahingoitat kirjaston omaisuutta,<br>
        sinun täytyy korvata se.<br>
        Löydät tarkat ohjeet aineiston korvaamisesta<br>
        osoitteessa <a href="/Content/laina-ajat-ja-maksut#yhteiset-maksut">https://helmet.finna.fi/Content/laina-ajat-ja-maksut</a>.</p>
        <h3>Myöhästyneet lainat ja maksut</h3>
        <p>Jos lainasi ovat myöhässä,<br>
        saat niistä kaksi muistutusta.<br>
        Ensimmäinen muistutus tulee<br>
        14 vuorokauden päästä eräpäivästä.<br>
        Toinen muistutus tulee<br>
        28 vuorokauden kuluttua eräpäivästä.<br>
        Ensimmäinen muistutus on mahdollista saada sähköpostilla.</p>
        <p>Kun saat muistutuksen,<br>
        sinun täytyy palauttaa aineisto kirjastoon<br>
        ja maksaa myöhästymismaksut.</p>
        
        <h3>Mitä tapahtuu, jos et maksa maksujasi?</h3>
        <p>Jos et maksa maksujasi kirjastolle,<br>
        kirjasto käyttää perintätoimistoa.<br>
        Maksut menevät kirjastolta perintätoimistoon,<br>
        kun eräpäivästä on kulunut noin 60 päivää.</p>
        <p>Vain aikuisen velat voivat mennä perintään.<br>
        Jos asiakas on alle 18-vuotias,<br>
        velat eivät mene perintään,</p>
        <p>Jos tarvitset lisätietoa perinnästä,<br>
        löydät tietoa osoitteessa <a href="https://helmet.finna-pre.fi/Content/laina-ajat-ja-maksut#yhteiset-maksut">https://helmet.finna.fi/Content/laina-ajat-ja-maksut</a>.</p>
        
        <h3>Lainausoikeuden menettäminen</h3>
        <p>Jos et maksa velkaasi kirjastolle,<br>
        voit saada kirjaston käyttökiellon.<br>
        Menetät silloin lainausoikeutesi<br>
        eli et saa lainata aineistoa kirjastosta.</p>
        <p>Menetät lainausoikeutesi, jos</p>
        <ul class="list-bullets">
          <li>lainasi ovat myöhässä yli 28 vuorokautta</li>
          <li>olet kadottanut kirjaston aineistoa</li>
          <li>olet vahingoittanut kirjaston aineistoa</li>
          <li>olet maksimimäärän velkaa kirjastolle.</li>
        </ul>
        <p>Voit tarkistaa osoitteessa <a href="https://helmet.finna-pre.fi/Content/laina-ajat-ja-maksut#yhteiset-maksut">https://helmet.finna.fi/Content/laina-ajat-ja-maksut</a>,<br>
        mikä on velan maksimimäärä.</p>
        <p>Tähän sääntöön on yksi poikkeus:<br>
        Jos olet velkajärjestelyssä<br>
        ja velkasi kirjastolle on mukana maksuohjelmassa,<br>
        et menetä lainausoikeuttasi kirjastoon.</p>
        
        <h3>Lainausoikeuden palauttaminen</h3><p>Saat lainausoikeuden takaisin, kun</p>
        <ul class="list-bullets">
          <li>palautat myöhästyneen aineiston kirjastoon</li>
          <li>korvaat kadonneen tai vahingoittuneen aineiston</li>
          <li>maksat velkasi kirjastolle.</li>
        </ul>
        <p>Jos velkasi ovat perinnässä,<br>
        velka-asian hoitaa perintätoimisto.<br>
        Silloin sinun täytyy maksaa velka perintätoimistolle<br>
        ja perintätoimisto maksaa velan kirjastolle.<br>
        Lopuksi kirjasto tarkistaa maksun.<br>
        Jos kaikki on kunnossa,<br>
        saat taas lainata kirjastosta.</p>
      </div>
      <div id="kayttokielto" class="content-section">
        <h2>Kirjaston käyttökielto</h2>
        <p>Voit menettää oikeuden käyttää kirjastoa,<br>
        jos et noudata kirjaston käyttösääntöjä.<br>
        Käyttökielto voi tulla esimerkiksi silloin,<br>
        jos aiheutat häiriötä kirjastossa,<br>
        vaarannat turvallisuuden kirjastossa<br>
        tai vahingoitat kirjaston omaisuutta.<br>
        Käyttökielto on väliaikainen.<br>
        Se voi kestää enintään 30 päivää.</p>
        <p>Kirjasto tekee käyttökiellosta virallisen päätöksen.<br>
        Sinulla on oikeus valittaa päätöksestä<br>
        ja hakea muutosta siihen.<br>
        Ennen kun joudut käyttökieltoon,<br>
        sinulla on myös oikeus kertoa oma näkökulmasi asiaan.</p>
        <p>Jos saat käyttökiellon,<br>
        siitä tulee merkintä kirjaston asiakasrekisteriin.<br>
        Kirjasto poistaa merkinnän,<br>
        kun saat käyttöoikeuden takaisin.</p>
      </div>
      <div id="miten-kayttosaannot-toimivat" class="content-section">
        <h2>Miten käyttösäännöt toimivat?</h2>
        <p>Näitä käyttösääntöjä muutetaan vain siten,<br>
        että muutoksesta tehdään virallinen päätös.<br>
        Myös kirjastoautot, laitoskirjastot ja kirjastojen kotipalvelu<br>
        noudattavat näitä käyttösääntöjä,<br>
        jos se vain on mahdollista.</p>
        <p>Nämä käyttösäännöt ovat voimassa 1.2.2023 alkaen.<br>
        Ne ovat voimassa toistaiseksi.<br>
        Sääntöjen irtisanomisaika on kuusi kuukautta.<br>
        Nämä käyttösäännöt kumoavat vanhat säännöt,<br>
        jotka kirjasto hyväksyi 1.2.2021.</p>
      </div>
      <div id="lisatiedot" class="content-section">
        <h2>Lisätiedot</h2>
        <ul class="list-bullets">
            <li><a href="/Content/laina-ajat-ja-maksut">Laina-ajat ja maksut</a></li>
            <li><a href="/Content/kaukopalvelu">Kaukopalvelu</a></li>
            <li><a href="/Content/kayttosaannot">Yleiskieliset käyttösäännöt</a></li>
        </ul>
      </div>
   </div>
</div>
