<? $this->headTitle($this->translate('Helmet Library user regulations')); $this->content()->setHeading($this->translate('Helmet Library user regulations'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helmet is an abbreviation of the words Helsinki Metropolitan Area Libraries.</p>
        <p>Helmet library service consists of Espoo, Helsinki, Kauniainen and Vantaa City Libraries. Helmet libraries have a shared customer register and library system.</p>
        <p>Helmet libraries are open for everybody. Anyone who follows the customer regulations is allowed to use the libraries’ collections, services and customer facilities. 
        You are obliged to use library materials, media and facilities in an appropriate way.</p>
        <p>When you receive a library card (a customer registration number) or when you accept becoming a contact person, you are committed to follow these user regulations and the 
        potential changes of the regulations.</p>
      </div>
     <div id="library-card" class="content-section">
        <h2>Library card and pin code</h2>
        <p>Library card is a card or a customer registration number in some other form approved by the library (later in this text referred to as library card).</p>
        <p>You can get a personal library card, the right to borrow and a PIN code at any Helmet library or mobile library. The first library card is free of charge. 
        You will get the library card when you state your address and present a valid ID card with a photograph and personal identity number accepted by the library. 
        To be able to receive a library card you need an address in Finland. If you do not have a Finnish personal identity number, your library card is valid for twelve months at a time.</p>
        <p>Children under 15 can have a library card with a written consent by a guardian or other statutory representative (later representative) and by presenting an ID card. 
        The child must be present when picking up the library card. The representative is responsible for the loans on the library card of a child under 15 years, as well as for the 
        child’s use of other services, equipment and facilities of the library.</p>
        <p>A day care centre, school, other institution or community can have a library card for twelve months at a time. A contact person is appointed for the card. This person will 
        oversee that the card is used appropriately.</p>
        <p>The library card is personal. This also applies to using the library’s self-service. You are responsible for the items that have been borrowed with your library card. 
        Lending by the automatic lending machine is protected with your PIN code.</p>
        <p>You must inform the library immediately if your library card disappears. This responsibility also concerns the contact person. If you have lost your library card, 
        you can call the telephone number 09 3108 5309 when the libraries are closed and leave a message in the answerphone. You are not responsible for the material that has been 
        borrowed with the lost library card after you have informed the library that the library card is missing. A library card that has been reported lost will be removed from use.</p>
        <p>Along with the library card you will need a PIN code, if you wish to use the library’s self-service machines, web services, customer computers or self-service libraries. You will 
        get the PIN code from the library or mobile library when you present a valid ID card approved by the library. The PIN code will not be given by e-mail or phone.</p>
        <p>Please keep your contact information up-to-date. You must notify the library without delay about the changes of your address, email address and your name. You can check your 
        contact information on the website <a href="/">www.helmet.finna.fi</a>.</p>
        <p>The relationship between the library and the customer is confidential.</p>
        <p>The library is responsible for the accuracy of the customer register. The personal Information 
        on the borrower and the representative is recorded in the libraries’ customer register. The library is responsible for keeping the customer register up to date according to 
        the law in force.</p>
        <p>In accordance with the Personal Data Act, the library has the right to record the customer’s personal identity number into the register. 
        <a href="/Content/asiakasrekisteriseloste?lng=en-gb">The register report</a> is on view at the libraries.</p>
        <p>You are entitled to check the information recorded about you in the library’s customer register. You will be shown the information in question at the library’s customer 
        service desk when you prove your identity by presenting a valid ID card accepted by the library. The representative of a person younger than 15 years of age is entitled to get 
        information about the guarantee’s overdue loans and unpaid fees. The contact person of an institution or community is entitled to check the information about the institution or 
        community in question.</p>
      </div>
      <div id="loans" class="content-section">
        <h2>Loans, returns and renewals</h2>
        <p>You may have simultaneously 100 loans. The loan period varies from 1 day to 28 days. You will find specific information about the loan periods in the appendix of the user 
        regulations. Movies and games will not be lent to a customer who does not fulfill the age limits approved by Kansallisen Audiovisuaalisen Instituutin Mediakasvatus- ja 
        kuvaohjelmayksikkö MEKU (Media education and visual program unit of National Audiovisual Institute).</p>
        <p>Due dates are on the check-out receipt. Please return your loans on the due date at the latest. You can return the material to any Helmet library during its opening hours. 
        If you wish you can get a receipt of the return. Some libraries have so-called returning boxes. The items returned via the returning box are registered as returned on the 
        next opening day of the library.</p>
        <p>You will receive a notification of an approaching due date 48 hours in advance, if you have a functioning email address in the library’s client register.</p>
        <p>You can renew your loans five (5) times at the library, mobile library or in Your record at www.helmet.finna.fi. It is not possible to renew the loans if the material has 
        been reserved or if you have lost your right to borrow. There may be restrictions in renewing the loans. E.g. bestsellers and most objects that are to be borrowed cannot be renewed.</p>
        <p>The first reminder of overdue loans will be sent 14 days after the due date, the second reminder 28 days after the due date. The first reminder can also be received by email. 
        The Helmet library system also sends reminders on unpaid payments in order to avoid the expiration of the debt.</p>
        <p>You will lose the right to borrow</p>
        <ul class="list-bullets">
            <li>if your loans are more than 28 days overdue</li>
            <li>if you have lost or damaged the material of the library</li>
            <li>if you fail to pay your overdue fees when they have amounted to or exceeded the sum indicated in the payments appendix</li>
        </ul>
        <p>An exception to the above is a borrower who has started the process of a loan arrangement and whose debt to the library belongs to the freezing of payments. In the case of a 
        debt like this, the debtor may not be targeted by the loss of borrowing rights due to a delay in payment.</p>
        <p>You will regain your borrowing rights</p>
        <ul class="list-bullets">
            <li>by returning the items that are overdue</li>
            <li>by compensating for lost or damaged items</li>
            <li>by paying the accumulated fees</li>
        </ul>
        <p>If the payment has been transferred to a collection office the borrowing rights are restored only after the collection office has made the payment to the library’s 
        account and the library has checked the payment.</p>
      </div>
      <div id="reservations" class="content-section">
        <h2>Reservations and interlibrary loans</h2>
        <p>You can reserve material either at the library or by logging in <a href="/">www.helmet.finna.fi</a>.</p>
        <p>You may not have more than 100 pending reservations at the same time. You will receive a notification about reservations that can be picked up by a text message, email or letter. 
        There may be restrictions in reserving materials.</p>
        <p>Most libraries have a self-service pick-up shelf for reservations. The protection of customers’ data will be taken into consideration when arranging the pick-up of reservations.</p>
        <p>You can order an item as an interlibrary loan from elsewhere in Finland or abroad, if the item is not available in the collections of any Helmet library. The service is 
        subject to a charge. If, however, the material in question is available in some scientific or special library in the metropolitan area, it cannot be ordered as an interlibrary loan.</p>
      </div>
      <div id="fees" class="content-section">
        <h2>Fees</h2>
        <p>In general, using the library is free of charge. However, fees will be charged for items returned or renewed after the due date, reservations that are not picked up, 
        and for certain special services. The most important fees charged by the libraries are listed in the appendix of the user regulations.</p>
        <p>The overdue fee will accrue every calendar day after the due date until it reaches the maximum amount. No overdue fee will be charged for materials from the children’s 
        and teens’ departments. The overdue fee will be charged even if you fail to renew the loans due to a break in the internet connection or some other technical problem.</p>
        <p>For a reservation that has been delivered to the pick-up shelf but not picked up by the customer, customers aged 18 or older will be charged a fee. The fee will be 
        charged even if the pick-up notification has not arrived due to a delivery error, a fault in telecommunications, or another reason.</p>
        <p>You must compensate for lost or damaged material. Instructions to compensate for material are to be found in the appendix of the user regulations. NB. The library is not 
        responsible for damages which the recordings you have borrowed possibly have caused to your appliances or for those damages caused to a third person by using the library appliances.</p>
        <p>The library uses a collection office to collect outstanding payments. The outstanding payments are transferred from the Helmet library system to the collection office 
        used by each city library in question approximately 60 days after the due date. The collection concerns material borrowed by a person 18 years of age or older. More information 
        on collection can be found in the appendix of the user regulations.</p>
      </div>
      <div id="loss-of-rights" class="content-section">
        <h2>Loss of user rights</h2>
        <p>Your right to use the library may be denied for a certain period of time, should you repeatedly ignore the personnel’s warnings and keep causing significant disturbance 
        for the library operations, endangering safety or harming property.</p>
        <p>Denial of user rights may be up to 30 days. A office-holder's decision is made concerning the denial of user rights. You may claim for a revised decision according to the 
        Local Government Act. Before being denied user rights, you have the right to be heard. A note of the denial will appear in the library’s client register and the note is 
        removed when the time limit expires.</p>
      </div>
      <div id="application" class="content-section">
        <h2>The application and validity of the user regulations</h2>
        <p>These user regulations are applied at the city libraries in Espoo, Helsinki, Kauniainen, and Vantaa after the city libraries in the respective cities have approved the regulations. 
        The amendment of the regulations requires identical decisions. The mobile libraries, institutional libraries and the home services of libraries apply these user regulations when 
        applicable.</p>
        <p>These user regulations repeal the user regulations approved on 1st February 2021. These user regulations will enter into force on 1st February 2023 and will be valid until 
        further notice. The period of notice is six (6) months.</p>
      </div>
      <div id="appendix" class="content-section">
        <h2>Appendix for and more information on the user regulations</h2>
        <ul class="list-bullets">
            <li><a href="/Content/laina-ajat-ja-maksut?lng=en-gb">Loan periods and fees</a></li>
            <li><a href="/Content/omatoimikirjaston-kayttosaannot?lng=en-gb">User regulations for self-service libraries </a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb">User regulations for customer computers</a></li>
        </ul>
      </div>
   </div>
</div>


