<? $this->headTitle($this->translate('Helmet-kirjaston käyttösäännöt')); $this->content()->setHeading($this->translate('Helmet-kirjaston käyttösäännöt'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <h2>Tervetuloa Helmet-kirjastojen käyttäjäksi!</h2>   
        <p>Helmet-lyhenne tulee sanoista Helsinki Metropolitan Area Libraries. Helmet on Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjastojen yhteinen kirjastopalvelu. 
        Helmet-kirjastoilla on yhteinen asiakasrekisteri ja kirjastojärjestelmä.</p>
        <p>Helmet-kirjastot ovat kaikille avoimia. Niiden kokoelmia, palveluita ja yleisötiloja voivat käyttää kaikki, jotka noudattavat käyttösääntöjä. Olet osaltasi vastuussa 
        kirjaston kokoelmien, välineiden ja tilojen tarkoituksenmukaisesta käytöstä.</p>
        <p>Olet sitoutunut noudattamaan näitä käyttösääntöjä ja niihin tehtäviä muutoksia saadessasi kirjastokortin (asiakastunnuksen kirjastojärjestelmään) 
        tai suostuessasi yhteyshenkilöksi.</p>
      </div>
     <div id="kirjastokortti" class="content-section">
        <h2>Kirjastokortti ja tunnusluku</h2>
        <p>Kirjastokortti on kortti tai muussa kirjaston hyväksymässä muodossa oleva asiakastunnus (jäljempänä tässä tekstissä asiakastunnuksesta käytetään vain sanaa kirjastokortti).</p>
        <p>Henkilökohtaisen kirjastokortin, lainausoikeuden ja tunnusluvun saat mistä tahansa Helmet-kirjastosta tai kirjastoautosta. Ensimmäinen kirjastokortti on maksuton. Kortin saat, 
        kun ilmoitat osoitteesi ja esität kirjaston hyväksymän voimassa olevan henkilötodistuksen, jossa on valokuva ja henkilötunnus. Kirjastokortin myöntämiseen tarvitaan Suomessa oleva 
        osoite. Jos sinulla ei ole suomalaista henkilötunnusta, kirjastokorttisi on voimassa vuoden kerrallaan.</p>
        <p>Alle 15-vuotias saa kirjastokortin huoltajan tai muun lakimääräisen edustajan (myöhemmin käytetään sanaa vastuuhenkilö) kirjallisella suostumuksella ja henkilötodistuksen 
        esittämällä. Lapsen tulee olla paikalla korttia haettaessa. Alle 15-vuotiaan kohdalla kirjastokortilla lainatusta aineistosta sekä kirjaston muiden palvelujen, 
        laitteiden ja tilojen käytöstä vastaa vastuuhenkilö.</p>
        <p>Päiväkoti, koulu, muu laitos tai yhteisö saa kirjastokortin vuodeksi kerrallaan. Kortille asetetaan yhteyshenkilö, joka pitää huolta siitä, että korttia käytetään 
        tarkoituksenmukaisella tavalla.</p>
        <p>Kirjastokortti on henkilökohtainen. Henkilökohtaisuus koskee myös kirjaston omatoimikäyttöä. Olet vastuussa siitä aineistosta, joka kirjastokortillasi lainataan. 
        Lainausautomaatilla lainaus on suojattu tunnusluvulla.</p>
        <p>Kirjastokortin katoamisesta on ilmoitettava kirjastoon välittömästi. Tämä koskee myös vastuuhenkilöä. Kirjastokortin katoamisesta voi jättää ilmoituksen puhelinvastaajaan 
        kirjastojen ollessa suljettuna soittamalla puhelinnumeroon <a href="tel:0931085309">09 3108 5309</a>. Et ole vastuussa siitä aineistosta, joka on lainattu kadonneella kortilla sen jälkeen, kun katoamisilmoitus 
        on tehty. Kadonneeksi ilmoitettu kirjastokortti poistetaan käytöstä.</p>
        <p>Kirjastokorttiin tarvitaan tunnusluku, jos haluat käyttää kirjaston automaatteja, verkkopalveluja, asiakastietokoneita tai omatoimikirjastoa. Tunnusluvun saat 
        kirjastosta tai kirjastoautosta esittämällä kirjaston hyväksymän voimassaolevan henkilötodistuksen. Tunnuslukua ei anneta sähköpostilla tai puhelimessa.</p>
        <p>Pidäthän yhteystietosi ajan tasalla. Sinun on ilmoitettava osoitteen, sähköpostiosoitteen ja nimen muutoksista viipymättä kirjastoon. Yhteystietosi voit tarkastaa 
        kirjautumalla omiin tietoihisi <a href="/">www.helmet.finna.fi</a>-sivulla.</p>
        <p>Kirjaston ja asiakkaan välinen suhde on luottamuksellinen. Kirjasto vastaa asiakasrekisterinsä oikeellisuudesta. Lainaajan ja vastuuhenkilön henkilötiedot tallennetaan kirjaston 
        asiakasrekisteriin. Kirjaston vastuulla on, että asiakasrekisteri on kulloinkin voimassa olevien lakien mukainen. Henkilötietolain mukaan kirjastolla on oikeus 
        rekisteröidä asiakkaan henkilötunnus. <a href="/Content/asiakasrekisteriseloste">Rekisteriseloste</a> on nähtävillä kirjastoissa.</p>
        <p>Sinulla on oikeus tarkistaa, mitä tietoja sinusta on tallennettu kirjaston asiakasrekisteriin. Saat tiedot tarkistettavaksi kirjaston asiakaspalvelusta, kun olet todistanut 
        henkilöllisyytesi esittämällä kirjaston hyväksymän voimassa olevan henkilötodistuksen. Alle 15-vuotiaan vastuuhenkilöllä on oikeus saada tietoa vastattavansa myöhässä 
        olevista lainoista ja maksamattomista maksuista. Laitoksen tai yhteisön vastuuhenkilöllä on oikeus tarkistaa laitoksen tai yhteisön tiedot.</p>
      </div>
      <div id="lainaus" class="content-section">
        <h2>Lainaus, palautus ja uusiminen</h2>
        <p>Sinulla voi olla samanaikaisesti korkeintaan 100 lainaa. Laina-aika voi olla 1–28 vuorokautta. Tarkemmat laina-ajat löydät käyttösääntöjen liitteestä. Elokuvia tai pelejä ei 
        lainata asiakkaalle, joka ei täytä Kansallisen audiovisuaalisen instituutin (KAVI) mediakasvatus- ja kuvaohjelmayksikön (MEKU) hyväksymiä aineistokohtaisia ikärajoja.</p>
        <p>Eräpäivät näkyvät eräpäiväkuitissa, jonka saat lainauksen yhteydessä. Palauta lainat viimeistään eräpäivänä. Voit palauttaa aineiston mihin tahansa Helmet-kirjastoon toimipaikan 
        aukioloaikana. Palautuksesta saat halutessasi kuitin. Joissakin kirjastoissa on käytössä palautusluukku. Luukun kautta palautettu aineisto rekisteröidään palautetuksi seuraavana
        kirjaston aukiolopäivänä.</p>
        <p>Saat ilmoituksen lähestyvästä eräpäivästä kaksi (2) vuorokautta ennen eräpäivää, jos sinulla on toimiva sähköpostiosoite kirjaston asiakasrekisterissä.</p>
        <p>Voit uusia lainasi viisi (5) kertaa kirjastossa, kirjastoautossa tai kirjautumalla omiin tietoihisi <a href="/">www.helmet.finna.fi</a>-sivulla. Uusiminen ei 
        onnistu, jos aineistosta on varauksia tai olet menettänyt lainausoikeutesi. Aineiston uusimisessa voi olla rajoituksia. Esimerkiksi Bestseller-aineistoa ja useimpia lainattavia 
        esineitä ei voi uusia.</p>
        <p>Myöhässä olevasta aineistosta lähetetään ensimmäinen muistutus 14 vuorokauden ja toinen muistutus 28 vuorokauden kuluttua eräpäivästä. Ensimmäinen muistutus on mahdollista saada 
        sähköpostitse. Kirjastojärjestelmästä lähetetään lisäksi muistutuksia maksamattomista maksuista velan vanhenemisen katkaisemiseksi.</p>
        <p>Lainausoikeuden menetät, jos</p>
        <ul class="list-bullets">
          <li>lainasi ovat yli 28 vuorokautta myöhässä</li>
          <li>olet kadottanut tai vahingoittanut kirjaston aineistoa</li>
          <li>velkasaldosi on käyttösääntöjen liitteessä mainittu summa tai enemmän</li>
        </ul>
        <p>Poikkeuksena edellä mainittuihin on lainaajan velkajärjestelytilanne. Lainaajaan, joka on velkajärjestelyssä ja jonka kirjastoa koskeva velkasaatava on maksuohjelmassa, ei saa 
        kohdistaa tällaisen saatavan seurauksena lainausoikeuden menetystä.</p>
        <p>Lainausoikeuden saat takaisin, kun</p>
        <ul class="list-bullets">
          <li>palautat myöhässä olevan aineiston</li>
          <li>korvaat kadonneen tai vahingoittuneen aineiston</li>
          <li>maksat kertyneet maksut</li>
        </ul>
        <p>Jos maksu on annettu perintätoimiston tehtäväksi, lainausoikeus palautuu sen jälkeen, kun perintätoimisto on suorittanut maksun kirjaston tilille ja kirjasto on tarkistanut 
        maksusuorituksen.</p>
      </div>
      <div id="varaaminen" class="content-section">
        <h2>Varaaminen ja kaukolainat</h2>
        <p>Aineistoa voit varata joko kirjastossa tai kirjautumalla omiin tietoihisi <a href="/">helmet.finna.fi-sivulla</a>. Sinulla voi olla samanaikaisesti voimassa 
        100 varausta. Noudettavista varauksista saat ilmoituksen tekstiviestinä, sähköpostilla tai kirjeellä. Aineiston varaamisessa voi olla rajoituksia.</p>
        <p>Useimmissa kirjastoissa on käytössä itsepalveluvaraushylly. Varausten noudon järjestämisessä otetaan huomioon asiakkaan tietosuoja.</p>
        <p>Jos haluamaasi aineistoa ei löydy Helmet-kirjastoista, se voidaan kaukolainata muualta Suomesta tai ulkomailta. Palvelu on maksullinen. Kirjastot eivät kuitenkaan tilaa 
        kaukolainana aineistoa, joka on saatavilla jostakin pääkaupunkiseudun tieteellisestä kirjastosta tai erikoiskirjastosta.</p>
      </div>
      <div id="maksut" class="content-section">
        <h2>Maksut</h2>
        <p>Kirjaston käyttö on yleensä maksutonta. Myöhässä palautetusta tai uusitusta aineistosta, noutamattomasta varauksesta ja eräistä erityispalveluista peritään kuitenkin maksu. 
        Tärkeimmät kirjastossa perittävät maksut on lueteltu käyttösääntöjen liitteessä.</p>
        <p>Myöhästymismaksu kertyy kaikilta eräpäivän jälkeisiltä kalenteripäiviltä enimmäismäärään saakka. Lasten- ja nuortenosaston aineistosta myöhästymismaksua ei peritä. 
        Myöhästymismaksu peritään myös siinä tapauksessa, että lainojen uusiminen ei ole onnistunut tietoliikenteen häiriön tai muun teknisen häiriön vuoksi.
        <p>Varaushyllyyn toimitetusta noutamattomasta varauksesta peritään maksu 18 vuotta täyttäneeltä asiakkaalta. Maksu peritään myös siinä tapauksessa, että varausilmoitus ei ole 
        saapunut perille jakeluhäiriön, tietoliikenteen häiriön tai muun syyn vuoksi.</p>
        <p>Jos kadotat tai vahingoitat kirjaston omaisuutta, sinun on korvattava se. Ohjeet aineiston korvaamiseksi löytyvät käyttösääntöjen liitteestä. Huomaa, että kirjasto ei vastaa 
        niistä vahingoista, joita lainaamasi tallenteet ovat mahdollisesti aiheuttaneet laitteillesi, eikä niistä vahingoista, joita kirjaston laitteilla on aiheutettu kolmannelle henkilölle.</p>
        <p>Kirjasto käyttää saataviensa perimiseen perintätoimistoa. Kirjastojärjestelmästä saatavat siirretään kunkin kaupunginkirjaston käyttämän perintätoimiston perittäväksi noin 60 
        vuorokauden kuluttua eräpäivästä. Perintä koskee 18 vuotta täyttäneen asiakkaan lainaamaa aineistoa. Lisätietoa perinnästä löydät käyttösääntöjen liitteestä.</p>
      </div>
      <div id="kayttooikeuden-menetys" class="content-section">
        <h2>Käyttöoikeuden menetys</h2>
        <p>Voit menettää kirjaston käyttöoikeuden määräajaksi, jos huomautuksista huolimatta toistuvasti ja olennaisesti aiheutat häiriötä kirjaston toiminnalle tai vaarannat sen 
        turvallisuutta tai vahingoitat kirjaston omaisuutta.</p>
        <p>Kirjaston käyttökielto voi olla enintään 30 päivää. Käyttökiellosta tehdään viranhaltijapäätös, johon voit hakea oikaisua kuntalain mukaisesti. Ennen käyttökiellon antamista 
        sinulla on oikeus tulla kuulluksi. Kiellosta tulee merkintä kirjaston asiakasrekisteriin ja merkintä poistetaan, kun käyttöoikeus palautuu määräajan kuluttua.</p>
      </div>
      <div id="soveltaminen" class="content-section">
        <h2>Käyttösääntöjen soveltaminen ja voimassaolo</h2>
        <p>Sääntöjen muutos edellyttää yhtäpitävät päätökset. Kirjastoautoissa, laitoskirjastoissa ja kirjastojen kotipalvelussa noudatetaan näitä käyttösääntöjä soveltuvin osin.</p>
        <p>Näillä käyttösäännöillä kumotaan 1.2.2021 hyväksytyt käyttösäännöt. Nämä käyttösäännöt tulevat voimaan 1.2.2023 ja ovat voimassa toistaiseksi. 
        Irtisanomisaika on kuusi (6) kuukautta.</p>
      </div>
      <div id="lisatietoa" class="content-section">
        <h2>Käyttösääntöjen liite ja lisätietoa</h2>
        <ul class="list-bullets">
            <li><a href="/Content/asiakkaana-kirjastossa">Asiakkaana kirjastossa</a></li>
            <li><a href="/Content/laina-ajat-ja-maksut">Laina-ajat ja maksut</a></li>
            <li><a href="/Content/omatoimikirjaston-kayttosaannot">Omatoimikirjastojen käyttösäännöt</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet">Asiakastietokoneiden käyttösäännöt</a></li>
            <li><a href="/Content/kaukopalvelu">Kaukopalvelu</a></li>
        </ul>
      </div>
   </div>
</div>




