<? $this->headTitle($this->translate('Användningsregler (låneregler) för Helmet-biblioteken')); $this->content()->setHeading($this->translate('Användningsregler (låneregler) för Helmet-biblioteken'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="valkommen" class="content-section">
        <h2>Välkommen att använda Helmet-biblioteken!</h2>   
        <p>Helmet är förkortning av Helsinki Metropolitan Area Libraries. Helmet är en gemensam tjänst för stadsbiblioteken i Esbo, Helsingfors, Grankulla och Vanda. 
        Helmet-biblioteken har ett gemensamt användarregister och bibliotekssystem.</p>
        <p>Helmet-biblioteken är öppna för alla. Deras samlingar, tjänster och lokaler kan användas av alla som följer bibliotekets användningsregler. Som användare förbinder du dig att
        utnyttja bibliotekets samlingar, apparater och lokaler på ett ändamålsenligt sätt.</p>
        <p>Då du får ditt bibliotekskort (ditt personliga nummer i bibliotekssystemet), eller samtycker till att vara ansvarsperson, förbinder du dig att följa dessa användningsregler 
        inklusive eventuella ändringar.</p>
        <p>De gällande användningsreglerna samt särskilda instruktioner och regler angående bibliotekens apparater och rätten att använda dem finns på <a href="/Content/asiakkaana-kirjastossa?lng=sv">Biblioteksanvändare</a>.</p>
      </div>
     <div id="bibliotekskort" class="content-section">
        <h2>Bibliotekskort och PIN-kod</h2>
        <p>Bibliotekskortet är ett kort eller ett personligt nummer i något annat format (i fortsättningen används enbart ordet bibliotekskort i denna text).</p>
        <p>Du får ett personligt bibliotekskort, lånerätt och en PIN-kod i alla Helmet-bibliotek och bokbussar. Det första bibliotekskortet är gratis.</p>
        <p>Du får kortet när du anger din adress och visar upp ett giltigt identitetsbevis som biblioteket godkänner som innehåller ett fotografi och personbeteckning. Den som beviljas 
        bibliotekskort bör ha en adress i Finland. Om du inte har finländsk personbeteckning får du ditt bibliotekskort för ett år åt gången.</p>
        <p>En person som är under 15 år får ett bibliotekskort med vårdnadshavarens eller någon annan lagstadgad företrädares (senare används ordet ansvarsperson) skriftliga samtycke 
        och med att uppvisa ett identitetsbevis. Barnet ska vara på plats vid ansökan om kortet. Ansvarspersonen ansvarar för det material som lånats med den ungas bibliotekskort, 
        samt för hur den unga använder bibliotekets tjänster, apparater och lokaler.</p>
        <p>Daghem, skolor och andra inrättningar och samfund beviljas bibliotekskort för ett år i sänder. Kortet ska ha en ansvarsperson som ser till att kortet används på ett 
        ändamålsenligt sätt.</p><p>Bibliotekskortet är personligt. Detta gäller också då biblioteket används med självbetjäning. Du ansvarar för det material som lånas med ditt 
        bibliotekskort. I låneautomaterna är identiteten skyddad med din PIN-kod.</p>
        <p>Om ditt bibliotekskort försvinner bör du omedelbart anmäla detta till biblioteket. Detta gäller också ansvarspersoner. Då biblioteket är stängt kan meddelandet lämnas till 
        telefonsvararen på numret <a href="tel:0931085309">09 3108 5309</a>. Du är inte ansvarig för material som lånats med det försvunna kortet efter att du anmält det som försvunnet. 
        Ett bibliotekskort som anmälts försvunnet tas ur bruk.</p>
        <p>För att använda bibliotekets automater, webbtjänster, kunddatorer eller de meröppna biblioteken behöver du en PIN-kod vid sidan av bibliotekskortet. PIN-koden får du på biblioteket 
        eller i bokbussen då du uppvisar ett giltigt identitetsbevis som biblioteket godkänner. PIN-koder ges inte via e-post eller per telefon.</p>
        <p>Kom ihåg att uppdatera dina kontaktuppgifter. Meddela genast biblioteket om din adress, din e-postadress eller ditt namn förändrats. Du kan kontrollera dina kontaktuppgifter 
        genom att logga in på Dina uppgifter på adressen <a href="https://helmet.finna.fi/?lng=sv">www.helmet.finna.fi</a>.</p>
        <p>Förhållandet mellan biblioteket och användaren är konfidentiellt. Biblioteket ansvarar för att användarregistret är korrekt. Uppgifterna om låntagaren och ansvarspersonen 
        sparas i bibliotekets användarregister. Biblioteket ansvarar för att användarregistret överensstämmer med rådande lagar. Enligt personuppgiftslagen har biblioteket rätt att 
        registrera användarens personbeteckning. Registerbeskrivningen finns till påseende i biblioteken och på <a href="/Content/asiakkaana-kirjastossa?lng=sv">Biblioteksanvändare</a>.</p>
        <p>Du har rätt att kontrollera dina egna uppgifter i bibliotekets användarregister. Du får uppgifterna på biblioteket då du har styrkt din identitet genom att visa upp
        ett giltigt identitetsbevis som godkänns av biblioteket. En ansvarsperson för en person under 15 år har rätt att få information om försenade lån och obetalda avgifter 
        på den unga personens kort. En ansvarsperson för en inrättning eller ett samfund har rätt att kontrollera uppgifterna om inrättningen eller samfundet.</p>
      </div>
      <div id="att-lana" class="content-section">
        <h2>Att låna, returnera och förnya</h2>
        <p>Du kan samtidigt ha högst 100 lån. Lånetiden är mellan 1 och 28 dygn. Närmare information om lånetiderna finns i användningsreglernas bilaga. Biblioteket lånar inte ut filmer 
        och spel till personer som inte uppfyller de åldersgränser som Nationella audiovisuella institutets (KAVI) Enhet för mediefostran och bildprogram (MEKU) fastslagit för olika material.</p>
        <p>Då du lånar får du ett kvitto där förfallodagen framgår. Returnera dina lån senast på förfallodagen. Du kan returnera material till alla Helmet-bibliotek under deras öppettid. 
        Om du vill kan du få ett kvitto då du returnerat. En del bibliotek har en returlucka. Det material som returneras via returluckan registreras som återlämnat följande vardag då 
        biblioteket är öppet.</p>
        <p>Om du har en fungerande e-postadress i bibliotekets låntagarregister får du en påminnelse om förfallodagen två (2) dygn före förfallodagen.</p>
        <p>Lånen kan förnyas fem (5) gånger. Du kan förnya dem i biblioteket, i bokbussen eller genom att logga in på Dina uppgifter på adressen www.helmet.finna.fi. Du kan inte förnya ditt 
        lån ifall materialet är reserverat eller om du har förlorat din lånerätt. I vissa fall finns restriktioner, t.ex. kan bestsellermaterial och de flesta föremål inte förnyas.</p>
        <p>Den första påminnelsen om försenat material sänds 14 dygn efter förfallodagen och den andra då 28 dygn gått från förfallodagen. Du kan få den första påminnelsen per e-post. 
        Bibliotekssystemet skickar dessutom påminnelser om obetalda avgifter för att förhindra att skulden föråldras.</p>
        <p>Du förlorar rätten att låna</p>
        <ul class="list-bullets">
            <li>om dina lån är över 28 dygn försenade</li>
            <li>om du tappat bort eller skadat bibliotekets material</li>
            <li>om ditt skuldsaldo uppgår till eller överstiger det belopp som anges i bilagan för användningsreglerna</li>
        </ul>
        <p>Om låntagaren genomgår en skuldsanering görs ett undantag till det ovannämnda. Biblioteket får inte frånta lånerätten av en låntagare som beviljats skuldsanering och vars skuld 
        till biblioteket ingår i betalningsprogrammet.</p>
        <p>Du återfår din rätt att låna</p>
        <ul class="list-bullets">
            <li>genom att returnera det försenade materialet</li>
            <li>genom att ersätta det förlorade eller skadade materialet</li>
            <li>genom att betala vad du är skyldig</li>
        </ul>
        <p>Om indrivningen av avgiften överförts på ett inkassobolag, återställs lånerätten först då inkassobolaget betalat in avgiften på bibliotekets konto och biblioteket kontrollerat 
        inbetalningen.</p>
      </div>
      <div id="att-reservera" class="content-section">
        <h2>Att reservera material och fjärrlån</h2>
        <p>Du kan reservera material i biblioteket eller genom att logga in på Dina egna uppgifter på webbplatsen helmet.finna.fi. Du kan samtidigt ha högst 100 reservationer i kraft. 
        Vi meddelar per sms, e-post eller brev om de reservationer som är klara att hämta. Det kan finnas restriktioner i reserveringen av material.</p>
        <p>I de flesta bibliotek hämtas reservationerna i hyllor med självbetjäning. Vi beaktar låntagarnas integritetsskydd då reservationerna arrangeras.</p>
        <p>Material som inte finns i Helmet-bibliotekens samlingar kan beställas som fjärrlån från övriga bibliotek i Finland eller utomlands. Biblioteken beställer dock inte material 
        som finns tillgängliga i huvudstadsregionens vetenskapliga bibliotek eller specialbibliotek.</p>
      </div>
      <div id="avgifter" class="content-section">
        <h2>Avgifter</h2>
        <p>Att använda biblioteket är i huvudsak avgiftsfritt. Vi uppbär ändå avgifter för material som återlämnas eller förnyas efter förfallodagen, för reservationer som inte 
        hämtats, samt för vissa specialtjänster. De viktigaste avgifterna finns i en bilaga till användningsreglerna.</p>
        <p>Förseningsavgiften uppbärs för alla kalenderdagar, räknat från förfallodagen, upp till ett maximibelopp. För material som tillhör en barn- och ungdomsavdelning uppbärs 
        ingen förseningsavgift. Förseningsavgiften uppbärs också då du inte kunnat förnya lånet på grund av störningar i datakommunikationen eller p.g.a. något annat tekniskt fel.</p>
        <p>För material som kommit till en reservationshylla men inte hämtats uppbärs en avgift av alla som fyllt 18 år. Avgiften uppbärs också då informationen om reservationen inte 
        kommit fram p.g.a störningar i postutdelningen, datakommunikationen eller av någon annan orsak.</p>
        <p>Om du tappar bort eller skadar bibliotekets egendom måste du ersätta det. 
        Se instruktionerna i bilagan för användningsreglerna. Observera att biblioteket inte ersätter skador som materialet du lånat eventuellt orsakat din utrustning och inte 
        heller skador som bibliotekets utrustning eventuellt orsakat en tredje part.</p>
        <p>Biblioteket använder ett inkassobolag för att driva in sina fordringar. Bibliotekssystemet överför fordringarna efter ca 60 dygn räknat från förfallodagen till det inkassobolag 
        som ifrågavarande stadsbibliotek använder. Indrivningen gäller material som lånats av personer som fyllt 18 år. Mera information om 
        indrivningen i en bilaga till användningsreglerna.</p>
      </div>
      <div id="forlora-nyttjanderatt" class="content-section">
        <h2>Att förlora sin nyttjanderätt</h2>
        <p>Du kan förlora din nyttjanderätt till biblioteket för en viss tid om du trots anmärkningar upprepade gånger och väsentligt stört bibliotekets verksamhet eller äventyrat säkerheten 
        på biblioteket eller skadat bibliotekets egendom.</p>
        <p>En användare kan vara avstängd från biblioteket i högst 30 dagar. Beslut om att avstänga en användare görs som tjänstemannabeslut som kan överklagas i enlighet med kommunallagen. 
        Du har rätt att bli hörd innan du förlorar din nyttjanderätt. Användningsförbudet antecknas i användarregistret och anteckningen avlägsnas då du återfått din nyttjanderätt.</p>
      </div>
      <div id="tillampning" class="content-section">
        <h2>Användningsreglernas tillämpning och giltighetstid</h2>
        <p>För att ändra reglerna krävs samstämmiga beslut. I bokbussarna, anstaltsbiblioteken och bibliotekens hemservice följs dessa regler i tillämpliga delar.</p>
        <p>Dessa regler upphäver de tidigare användningsreglerna som fastställdes 1.2.2021. Reglerna träder i kraft 1.2.2023 och gäller tillsvidare. Uppsägningstiden är sex (6) månader.</p>
      </div>
      <div id="bilagor" class="content-section">
        <h2>Bilagor och mera uppgifter</h2>
        <ul class="list-bullets">
            <li><a href="/Content/asiakkaana-kirjastossa?lng=sv">Biblioteksanvändare</a></li>
            <li><a href="/Content/laina-ajat-ja-maksut?lng=sv">Lånetider och avgifter</a></li>
            <li><a href="/Content/omatoimikirjastot?lng=sv">Användningsregler för meröppetbiblioteken</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv">Regler för användning av kunddatorerna</a></li>
            <li><a href="/Content/kaukopalvelu?lng=sv">Fjärrlån</a></li>
        </ul>
      </div>
   </div>
</div>
