<? $this->headTitle($this->translate('Bokbussarna Helsingfors')); $this->content()->setHeading($this->translate('Bokbussarna Helsingfors'));?>
<h2>Tidtabeller</h2>
<p>De fina bokbussarna Stoori och Skidi betjänar under vardagar, med undantag för sommarpausen, helgdagar, samt dagarna före helgdagar.När du gör en reservation till bokbussen vänligen 
uppge även hållplatsen du vill avhämta ifrån.</p>
<p>Bokbussens nya tidtabell från och med den 31.10.2022: <a href="/themes/custom/files/hki_kirjastoauto_aikataulu_syksy2022.pdf" target="_blank">Uudet aikataulut 31.10.2022 alkaen (PDF)</a></p>