<? $this->headTitle($this->translate('Mobile library Helsinki')); $this->content()->setHeading($this->translate('Mobile library Helsinki'));?>
<h2>Route schedule</h2>
<p>The wonderful mobile libraries Stoori and Skidi take turns on the route. When reserving material to the mobile library, please also indicate the name of the pick-up stop. The mobile 
library makes its rounds on weekdays, except during the midsummer break, public holidays and on the days preceding public holidays.</p>
<p>New schedule of the mobile libraries from 31.10.2022: <a href="/themes/custom/files/hki_kirjastoauto_aikataulu_syksy2022.pdf" target="_blank">Uudet aikataulut 31.10.2022 alkaen (PDF)</a></p>
