<? $this->headTitle($this->translate('Selkoesittely: mikä kirjasto on?')); $this->content()->setHeading($this->translate('Selkoesittely: mikä kirjasto on?'));?>
<p>Tämä on selkokielinen esittely kirjastosta.</p><p>Jokaisessa Suomen kunnassa on yleinen kirjasto.<br>
Kirjasto on kohtaamispaikka ja kulttuurikeskus.<br>
Kirjasto on tarkoitettu lapsille, nuorille, naisille ja miehille.<br>
Kirjastossa voit lukea, viettää aikaa, tavata ystäviä<br>
ja osallistua tapahtumiin.<br>
Kirjaston henkilökunta auttaa sinua, vastaa kysymyksiin<br>
ja esittelee kirjastoa.</p>
<p>Kirjasto on kaikille asukkaille tarkoitettu maksuton palvelu.<br>
Kirjastossa voit</p>
<ul class="list-bullets">
  <li>lainata kirjoja, lehtiä, musiikkia ja videoita</li>
  <li>käyttää kirjaston tietokoneita ja muita elektronisia laitteita</li>
  <li>osallistua lukupiireihin, tapahtumiin ja kursseille</li>
  <li>pyytää henkilökunnalta asiantuntija-apua</li>
  <li>käyttää kirjaston tiloja, kuten lukusaleja.</li>
</ul>
<p>Saat lisätietoa kirjastoista ja kirjastojen verkkosivustoilta.</p>
<p>Melkein kaikki kirjaston palvelut ja tapahtumat ovat ilmaisia.</p>
<p>Lainaamista varten tarvitset voimassaolevan kirjastokortin.<br>
Useimpia muita palveluja voit käyttää myös ilman kirjastokorttia.</p>

<h2>Kirjastossa voi tehdä ja osallistua</h2>
<p>Kirjastossa on tapahtumia lapsille,<br>
nuorille ja aikuisille.<br>
Satutunneilla kuunnellaan satuja ja leikitään.<br>
Satutunteja pidetään useilla eri kielillä.<br>
Lapsille on myös teatteriesityksiä ja muita tilaisuuksia.</p>
<p>Kirjastossa järjestetään kirjallisuusiltoja,<br>
kirjailijatapaamisia, konsertteja sekä esitelmätilaisuuksia.<br>
Kirjaston järjestämät tilaisuudet ovat maksuttomia.</p>
<p>Useissa kirjastoissa on varattavia näyttelytiloja.<br>
Tietoa tapahtumista ja näyttelyistä saat<br>
kirjastoista ja kirjastojen kotisivuilta.<br>
Voit myös järjestää kirjastossa tapahtuman itse.</p>
<p>Kirjaston tietokoneilla voit lukea sähköpostisi,<br>
etsiä tietoa verkosta tai tulostaa.<br>
Tulostus on joissain kaupungeissa maksullista.<br>
Kaikissa koneissa on<br>
tekstinkäsittely- ja muita hyötyohjelmia.<br>
Joissakin kirjastoissa on myös skannereita<br>
ja näppäimistöjä eri kielillä.</p>
<p>Joissakin kirjastoissa voi myös askarrella<br>
tai tehdä käsitöitä, esimerkiksi ommella<br>
tai käyttää 3D-tulostinta.<br>
Näitä tiloja kutsutaan usein verstaiksi tai pajoiksi.</p>
<p>Voit käyttää kirjaston tiloja.<br>
Kaikissa kirjastoissa on pöytiä ja tuoleja,<br>
joita voit käyttää vapaasti työhön tai vapaa-aikaan.<br>
Monista kirjastoista voit myös varata erikseen tilan<br>
esimerkiksi kokousta varten.<br>
Joissakin kirjastoissa on musiikkihuone,<br>
jossa voi esimerkiksi soittaa pianoa.</p>
