<? $this->headTitle($this->translate('Kirjastoauto ja aikataulut Vantaa')); $this->content()->setHeading($this->translate('Kirjastoauto ja aikataulut Vantaa'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Vantaalla on kaksi kirjastoautoa, Haave ja Tarina. Soita meille arkisin kello 9-15 numeroon 043 825 1752 tai laita sähköpostia auto.kirjasto@vantaa.fi</p>
        <p>Ilmoita noutopysäkin nimi varatessasi aineistoa kirjastoautoon. Tervetuloa kirjastoautoon!</p>
        <p>Kirjastoautot palvelevat arkisin juhlapyhiä lukuunottamatta. Pysäkkejä kirjastoautoilla on yhteensä 119, joista iltapysäkkejä 41, kouluja 32, päiväkoteja 44 ja muita laitoksia 2. 
        Lisäksi kirjastoautoa käyttää 19 päiväkotia muiden pysäkkien yhteydessä.</p>
        <p>Kaikki pysäkkimme ovat <a href="https://www.google.fi/maps/@60.3158163,24.8788882,12z/data=!3m1!4b1!4m2!6m1!1s13Ovxv73Ct6u2qJV2kxyHpV-Mi041MPQR?hl=fi" target="_blank"
        aria-label="Google Mapsissa. Linkki aukeaa uudessa ikkunassa.">Google Mapsissa</a>.</p>
        <p>Kirjastoautot eivät valitettavasti ole esteettömiä. Hissiä tai invaluiskaa ei ole, eli sisään ei ole mahdollista päästä esimerkiksi pyörätuolin, rollaattorin tai 
        lastenvaunujen kanssa. Kaikki pysäkkimmekään eivät ole esteettömästi saavutettavissa. Tarvittaessa virkailija voi valita, lainata ja tuoda asiakkaan toivomat aineistot ulos.</p>
      </div>
     <div id="iltapysakit" class="content-section">
        <h2>Iltapysäkit 31.7.2023 alkaen</h2>
        <ul class="list-bullets">
          <li>Askisto Hirsikuja tiistaisin 17.00-17.15</li>
          <li>Askisto Askistontie 54 tiistaisin 17.20-17.40</li>
          <li>Etelä-Päiväkumpu Peijaksentie 18 keskiviikkoisin 18.10-18.30</li>
          <li>Hämeenkylä Ainontie 13 tiistaisin 16.20-16.45</li>
          <li>Ilola Nietoskuja 2 torstaisin 18.10-18.30</li>
          <li>Itä-Hakkilan koulu keskiviikkoisin 17.30-17.45</li>
          <li>Kaivoksela Kaivostie 4 maanantaisin 16.05-16.25</li>
          <li>Kannisto Kannistonkuja 2 maanantaisin 18.00-18.30</li>
          <li>Kanniston koulu Kenraalintie 6 maanantaisin 18.35-19.15</li>
          <li>Kivistön kirjasto Topaasikuja 11 maanantaisin 16.30-17.40</li>
          <li>Kivistö Maitorpantie 4 maanantaisin 15.50-16.10</li>
          <li>Koivikko Kesäkyläntie 20 maanantaisin 19.00-19.20</li>
          <li>Koivupää Runkotie 20 maanantaisin 17.15-17.35</li>
          <li>Kuninkaanmäki Merkkipuuntie 14 keskiviikkoisin 17.10-17.25</li>
          <li>Kuninkaanmäki Pohjolantie 34 keskiviikkoisin 16.50-17.05</li>
          <li>Kuusikko Hovitie 11 torstaisin 18.45-19.00</li>
          <li>Kylmäoja Ahdetie 2 torstaisin 17.45-18.05</li>
          <li>Leinelä Leineläntie 11 torstaisin 16.10-16.30</li>
          <li>Leppäkorpi Leppäkorventie 32 torstaisin 16.00-16.15</li>
          <li>Maarinkunnas Maarinkunnaantie 9 torstaisin 19.10-19.30</li>
          <li>Maarukanmetsä Maarukankuja 9 torstaisin 17.35-17.55</li>
          <li>Mikkola Marsinrinne 4 torstaisin 18.00-18.15</li>
          <li>Nikinmäki Paarmatie 2 torstaisin 17.00-17.25</li>
          <li>Nissas Nissaksentie 1 keskiviikkoisin 16.20-16.40</li>
          <li>Pohjois-Nikinmäki Pitkäsiima 33 torstaisin 16.30-16.50</li>
          <li>Päiväkumpu Laurintie 43 keskiviikkoisin 18.35-18.55</li>
          <li>Päiväkumpu Onervantie 1 keskiviikkoisin 19.00-19.20</li>
          <li>Reuna Reunakuja 1 maanantaisin 17.50-18.05</li>
          <li>Riipilä Mäntymäki 4 maanantaisin 18.10-18.30</li>
          <li>Ruskeasanta Mistelikuja 24 torstaisin 17.20-17.35</li>
          <li>Seutulan koulu Katriinantie 60 maanantaisin 18.35-18.55</li>
          <li>Simonmetsä Raatetie 25 torstaisin 15.40-16.00</li>
          <li>Simonsilta Sananjalantie 6 torstaisin 19.00-19.25</li>
          <li>Tammisto Rosendalinrinki 1 torstaisin 16.45-17.00</li>
          <li>Tarhurinpuisto Sipulitie 17 torstaisin 18.40-18.55</li>
          <li>Tolkinmetsä Kehävuorenkuja tiistaisin 18.10-18.30</li>
          <li>Vaarala Lähdepuistontie 8 keskiviikkoisin 15.50-16.10</li>
          <li>Vantaanlaakso Vanha Nurmijärventie 29 maanantaisin 16.35-16.55</li>
          <li>Varisto Luhtitie 14 tiistaisin 15.50-16.10</li>
          <li>Ylästö Isonmännyntie 38 tiistaisin 19.05-19.25</li>
          <li>Ylästö Ollaksentie 31 tiistaisin 18.35-19.00</li>
        </ul>
      </div>
      <div id="koulupysakit" class="content-section">
        <h2>Koulupysäkit  21.8.2023 alkaen</h2>
        <ul class="list-bullets">
          <li>Askiston koulu tiistaisin 11.20-11.50</li>
          <li>Aurinkokiven koulu torstaisin 10.10-10.40</li>
          <li>Hämeenkylän koulu tiistaisin 10.30-11.10</li>
          <li>Ilolan koulu perjantaisin 9.10-9.40</li>
          <li>Itä-Hakkilan koulu keskiviikkoisin 9.50-10.20</li>
          <li>Jokirannan opetuspiste keskiviikkoisin 10.20-10.45</li>
          <li>Jokivarren koulu tiistaisin 10.55-11.30</li>
          <li>Kaivokselan koulu kerran kuussa maanantaisin 28.8., 25.9. kello 9.25-10.00</li>
          <li>Kanniston koulu torstaisin 11.40-12.10</li>
          <li>Keimolanmäen koulu torstaisin 9.45-10.05</li>
          <li>Kivimäen koulu kerran kuussa maanantaisin 28.8., 25.9 kello 10.10-10.45</li>
          <li>Kulomäen opetuspiste maanantaisin 21.8., 4.9., 18.9., 2.10. kello 11.10-11.40</li>
          <li>Kuusikon koulu keskiviikkoisin 11.00-11.30</li>
          <li>Kytöpuiston koulu keskiviikkoisin 10.35-11.05</li>
          <li>Kyrkoby skola kaksi kertaa kuukaudessa keskiviikkoisin 23.8., 6.9., 20.9., 4.10., 25.10., 8.11., 22.11. kello 12.00-12.30</li>
          <li>Leppäkorven koulu kaksi kertaa kuukaudessa tiistaisin 29.8., 12.9., 26.9. kello 10.20-10.45</li>
          <li>Mikkolan koulu tiistaisin 9.40-10.10</li>
          <li>Nikinmäen opetuspiste tiistaisin 11.35-12.15</li>
          <li>Päiväkummun koulu perjantaisin 10.45-11.15</li>
          <li>Rajatorpan koulu tiistaisin 9.50-10.20</li>
          <li>Rekolan koulu perjantaisin 9.55-10.35</li>
          <li>Rekolanmäen koulu tiistaisin 9.00-9.30</li>
          <li>Seutulan koulu torstaisin 10.50-11.30</li>
          <li>Sotungin koulu keskiviikkoisin 11.45-12.15</li>
          <li>Steinerkoulu perjantaisin 12.10-12.35</li>
          <li>Tammiston opetuspiste kaksi kertaa kuukaudessa perjantaisin 18.8., 1.9., 15.9., 29.9. kello 9.45-10.10</li>
          <li>Uomarinteen koulu kerran kuussa maanantaisin 28.8., 25.9., kello 10.55-11.30 </li>
          <li>Viertolan Jokirannan opetuspiste keskiviikkoisin 10.20-10.45</li>
          <li>Viertolan Liljatien opetuspiste keskiviikkoisin  9.15-10.15</li>
          <li>Vierumäen koulu perjantaisin 11.35-12.05</li>
          <li>Västersundom skola joka toinen keskiviikko 30.8., 13.9., 27.9., 11.10., 1.11., 15.11., 29.11. kello 12.00-12.30</li>
          <li>Ylästön koulu parjantaisin 10.30-11.30</li>
        </ul>
      </div>
      <div id="paivakotipysakit" class="content-section">
        <h2>Päiväkotipysäkit syksyllä 2023</h2>
        <ul class="list-bullets">
          <li>Fazerin päiväkoti keskiviikkoisin 2.8., 6.9., 4.10. kello 14.35-15.05</li>
          <li>Hevoshaan päiväkoti keskiviikkoisin 23.8., 20.9. kello 9.15-9.40   </li>
          <li>Husaarin päiväkoti torstaisin 24.8., 21.9. kello 9.10-9.30</li>
          <li>Hämeenkylän päiväkoti tiistaisin  15.8. 12.9. kello 9.15-9.35</li>
          <li>Ilvespuiston päiväkoti torstaisin 24.8., 21.9. kello 14.25-14.50</li>
          <li>Isonmännyn päiväkoti maanantaisin 7.8., 4.9., 2.10. kello 14.45-15.05</li>
          <li>Itä-Hakkilan päiväkoti keskiviikkona 16.8. kello 9.45-10.05 ja keskiviikkona 6.9., 4.10 kello 9.15-9.40</li>
          <li>Kanniston päiväkoti torstaisin 7.9., 5.10 kello 9.10-9.30</li>
          <li>Karhunpesän päiväkoti tiistaina 15.8. kello 9.45-10.05 ja tiistaisin 5.9., 3.10. kello 9.15-9.35</li>
          <li>Kimaran päiväkoti tiistaisin 22.8., 19.9. kello 9.15-9.35</li>
          <li>Kivimäen ja Lintukallion päiväkoti maanantaisin 28.8., 25.9. kello 10.10-10.45</li>
          <li>Kivistön päiväkoti torstaisin 31.8., 28.9. kello 9.10-9.30</li>
          <li>Koivukylän päiväkotipaviljonki Talvikkitie torstaisin 24.8., 21.9. kello 14.25-14.50</li>
          <li>Kuusikkotien päiväkoti keskiviikkoisin 30.8., 27.9. kello 9.10-9.35</li>
          <li>Lauhatien päiväkoti maanantaisin 14.8., 11.9. kello 9.10-9.30</li>
          <li>Leinelän päiväkoti maanantaisin 14.8., 11.9. kello 10.10-10.30</li>
          <li>Leppäkorven päiväkoti tiistaisin 29.8., 12.9., 26.9. kello 10.20-10.45</li>
          <li>Lintukallion ja Kivimäen päiväkoti maanantaisin 28.8., 25.9. kello 10.10-10.45</li>
          <li>Lipunkantajan päiväkoti maanantaisin 14.8., 11.9. kello 14.45-15.05</li>
          <li>Maarukanmetsän päiväkoti keskiviikkona 16.8. kello 10.20-10.40 ja keskiviikkoisin 5.9., 3.10., kello 10.15-10.35</li>
          <li>Maitorpan päiväkoti tiistaina 15.8. kello 10.20-10.40 ja torstaina 14.9. kello 9.10-9.30</li>
          <li>Malminiityn päiväkoti maanantaisin 21.8., 18.9. kello 9.45-10.15 </li>
          <li>Mistelin päiväkoti tiistaina 8.8. ja maanantaisin 4.9., 2.10. kello 9.45-10.15</li>
          <li>Nikinmäen päiväkoti maanantaisin 21.8., 18.9. kello 10.35-11.00</li>
          <li>Nissaksen päiväkoti keskiviikkoisin 16.8., 13.9. kello 9.15-9.35</li>
          <li>Näätäpuiston päiväkoti keskiviikkoisin 22.8.19.9. kello 10.20-10.40</li>
          <li>Ollaksen päiväkoti perjantaisin 25.8., 22.9. kello 10.05-10.25</li>
          <li>Pakkalanrinteen päiväkoti perjantaisin 11.8., 8.9., 6.10. kello 9.45-10.10</li>
          <li>Peltovuoren päiväkoti perjantaisin 28.8., 22.9. kello 9.40-10.00</li>
          <li>Pilke luontopäiväkoti Kielo Simonkylä tiistaina 8.8. kello 9.15-9.35 ja maanantaisin 4.9., 2.10. kello 9.15-9.35</li>
          <li>Pilke tiedepäiväkoti Tähtisumu Leinelän päiväkodin luona maanantaisin 14.8., 11.9. kello 10.10-10.30</li>
          <li>Päiväkummun päiväkoti maanantaisin 21.8., 18.9. kello 11.55-12.20</li>
          <li>Riihipellon päiväkoti perjantaisin 1.9., 29.9. kello 9.15-9.35</li>
          <li>Seutulan päiväkoti (koululla) maanantaisin 21.8., 18.9. kello 14.45-15.05</li>
          <li>Siimapuiston päiväkoti torstaisin 17.8., 14.9. kello 14.25-14.50</li>
          <li>Simonkallion päiväkoti torstaisin 17.8., 14.9. kello 14.25-14.50</li>
          <li>Simonmetsän päiväkoti maanantaisin 14.8., 11.9. kello 9.40-10.00</li>
          <li>Tammistonrannan päiväkoti perjantaisin 18.8., 15.9. kello 9.15-9.35</li>
          <li>Touhulan Hiekkaharjun päiväkoti torstaisin 10.8., 7.9., 5.10. kello 14.25-14.50</li>
          <li>Touhulan Ilolan päiväkoti tiistaina 8.8. kello 10.25-10.45 ja maanantaisin 4.9., 2.10. kello 10.25-10.45</li>
          <li>Touhulan Veromiehen päiväkoti perjantaisin 11.8., 89.9., 6.10. kello 9.15-9.35</li>
          <li>Vallinojan päiväkoti torstaisin 10.8., 7.9., 5.10. kello 14.25-14.50</li>
          <li>Varistonniityn päiväkoti tiistaisin 29.8., 26.9. kello 9.15-9.35</li>
          <li>Vehnätien päiväkoti maanantaisin 21.8., 18.9. kello 9.10-9.30</li>
        </ul>
        <p>Näillä päiväkodeilla ei tällä hetkellä käydä remontin tai muun syyn vuoksi: Pähkinänsärkijän päiväkoti</p>
      </div>
      <div id="muut-pysakit" class="content-section">
        <h2>Muut pysäkit</h2>
        <ul class="list-bullets">
          <li>Foibekartano torstaisin 31.8., 28.9. kello 14.25-14.50</li>
          <li>Vantaan vankila </li>
        </ul>
      </div>
   </div>
</div>
