<? $this->headTitle($this->translate('Kirjastoauto Helsinki')); $this->content()->setHeading($this->translate('Kirjastoauto Helsinki'));?>
<p>Helsingin kaksi lastenkirjastoautoa, Stoori ja Skidi, kuljettavat arkisin lukemisen iloa ympäri Helsinkiä kouluille, päiväkodeille ja asuinalueille. Kesäisin kirjastoauton voi 
lisäksi bongata leikkipuistosta, torilta tai vaikkapa uimarannalta! Helsingin kirjastoautot ovat myös kysyttyjä vieraita erilaisiin kaupunginosatapahtumiin ja tempauksiin.</p>
<h2>Aikataulut</h2>
<p>Lastenkirjastoautot Skidi ja Stoori palvelevat arkisin, lukuun ottamatta keskikesän taukoa sekä juhlapyhiä ja niitä edeltäviä aattopäiviä.</p>
<p>Tästä linkistä löydät Helsingin lastenkirjastoautojen iltareittien aikataulut tiedostomuodossa. HUOM! Kalasatamassa kirjastoauto pysähtyy Capellanaukiolla Junonkadun sijaan.</p>
<p><a href="/themes/custom/files/hki_kirjastoauto_aikataulu_syksy2022.pdf" target="_blank">Uudet aikataulut 31.10.2022 alkaen (PDF)</a></p>
<p>Alla olevassa kalenterissa ovat kirjastoautojen päiväkohtaiset aikatalut. Aamupäivien koulu- ja päiväkotipysäkit saattavat muuttua äkillisesti koulujen ja päiväkotien tarpeiden mukaan, 
eikä niitä välttämättä tällöin ehditä päivittää kalenteriin. Punaisella merkityt reitit ajetaan Skidillä ja mustat Stoorilla, mutta muutokset ovat mahdollisia.</p>
<p>Linkki <a href="https://calendar.google.com/calendar/u/0/embed?src=5g82f0t4h0kvrrr6pj5mds5vp8@group.calendar.google.com&amp;ctz=Europe/Helsinki" target="_blank"
aria-label="Stoorin Google kalenteriin. Linkki aukeaa uudessa ikkunassa.">Stoorin kalenteriin</a></p>
<p>Linkki <a href="https://calendar.google.com/calendar/u/0/embed?src=6u77k4vkotfcdk4seb3lj7bgks@group.calendar.google.com&amp;ctz=Europe/Helsinki" target="_blank"
aria-label="Skidin Google kalenteriin. Linkki aukeaa uudessa ikkunassa.">Skidin kalenteriin</a></p>
<p>Linkki <a href="https://www.google.com/maps/d/u/1/embed?mid=1EMg2WQ7atJUumYx62rnBvDuK8VA&amp;ll=60.215492425668394%2C25.01022345547366&amp;z=12" target="_blank"
aria-label="Helsingin kirjastoautopysäkit. Linkki aukeaa Google Mapsissa.">Helsingin kirjastoautopysäkit</a></p>