<? $this->headTitle($this->translate('Kirjastokortti ja lainaaminen')); $this->content()->setHeading($this->translate('Kirjastokortti ja lainaaminen'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="kirjastokortti" class="content-section">
        <p>Kirjastokortin ja tunnusluvun saat mistä tahansa Helmet-kirjastosta ilmoittamalla osoitteesi ja esittämällä kirjaston hyväksymän voimassaolevan 
         henkilötodistuksen, jossa on valokuva ja henkilötunnus. Kirjastokortin myöntämiseen tarvitaan Suomessa oleva osoite.</p>
        <p>Kirjastossa käyvät seuraavat henkilötodistukset:</p>
        <ul class="list-bullets">
          <li>EU-maiden henkilötodistukset</li>
          <li>passi</li>
          <li>suomalainen ajokortti</li>
          <li>kuvallinen KELA-kortti, alle 18-vuotiailta myös kuvaton KELA-kortti</li>
          <li>Suomessa sijaitsevan vastaanottokeskuksen asukaskortti</li>
          <li>Maahanmuuttoviraston myöntämä oleskelulupakortti.</li>
        </ul>
        <p>Alle 15-vuotias saa kirjastokortin huoltajan kirjallisella suostumuksella. 
        Päiväkoti, koulu, muu laitos tai yhteisö saa kirjastokortin vuodeksi kerrallaan kortille asetettavan yhteyshenkilön (esimerkiksi opettajan) suostumuksella.</p>
        <p>Voit nopeuttaa uuden kirjastokortin saamista tuomalla kirjastoon valmiiksi täytetyn <a href="/themes/custom/files/kirjastokorttihakemus.pdf"
        target="_blank">kirjastokorttihakemuksen (PDF)</a>.</p>
        <p>Jos olet täyttänyt 15 vuotta, voit tallentaa tietojasi etukäteen kirjaston asiakasrekisteriin alla olevasta linkistä aukeavalla lomakkeella. 
        Lomakkeen täyttäminen etukäteen nopeuttaa kirjastokortin saamista. Kun olet tallentanut tietosi, voit käydä hakemassa kirjastokortin mistä tahansa Helmet-kirjastosta. 
        Ota voimassaoleva henkilöllisyystodistus mukaan. Jos kirjastokorttia ei ole haettu kolmen kuukauden kuluessa lomakkeen täyttämisestä, tiedot poistetaan.</p>
        <p><a href="https://luettelo.helmet.fi/selfreg*fin~S9" target="_blank" aria-label="Rekisteröidy kirjaston asiakkaaksi. Linkki aukeaa uudessa ikkunassa.">
        Rekisteröidy kirjaston asiakkaaksi</a></p>
        <p>Jos sinulla tai läheiselläsi on jokin sairaus, vamma tai muu este henkilökohtaiselle kirjastokäynnille, voitte hakea 
        <a href="/Content/kun-et-paase-kirjastoon#joustoasiakkuus">joustoasiakkuutta</a>. 
        Joustoasiakkuus tarkoittaa, että asiakas valtuuttaa jonkun muun hoitamaan kirjastoasioinnin puolestaan.</p>
        <p><a href="/themes/custom/files/joustoasiakas.pdf" target="_blank">Ilmoittautumislomake joustoasiakkaaksi (PDF)</a></p>
        <p>Helmet-kirjastokortti on Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjastojen yhteinen kortti. 
        Voit lainata, varata ja palauttaa sekä kaikkien muiden seudun kirjastojen kokoelmista että omasta lähikirjastostasi. Useimmat palvelumme ovat ilmaisia. 
        Seudun ulkopuolelta tilattavat kaukolainat ovat kuitenkin maksullisia, ja myöhästyneistä palautuksista peritään myöhästymismaksu. Varaaminen on maksutonta kaikissa kaupungeissa.</p>
        <p>Allekirjoittamalla kirjastokortin sitoudut noudattamaan Helmet-kirjaston <a href="/Content/kayttosaannot">käyttösääntöjä.</a></p>
     </div>
     
     <div id="tunnusluku" class="content-section">
        <h2>Tunnusluku ja omat asiakastiedot</h2>    
        <p>Tunnusluku on kirjastokorttiin liittyvä nelinumeroinen salasana. 
        Tunnusluvun avulla voit käyttää lainausautomaattia, katsoa omia lainojasi, uusia niitä tai varata aineistoa <a href="/">Helmet.finna.fi-sivuilla.</a> 
        Tunnusluku tarvitaan myös joitakin muita verkkopalveluita varten sekä asiakastietokoneiden käyttöön. Tunnusluvun saat henkilökohtaisesti kirjastosta tai kirjastoautosta.</p>
        <p>Jos olet antanut meille sähköpostiosoitteesi, voit käyttää kirjautumissivulta löytyvää tunnusluvun palautustoimintoa.</p>
        <p>Jos meillä ei ole sähköpostiosoitettasi, muutamme tunnusluvun kirjastossa. Ota henkilötodistus mukaan.</p>
      </div>
      
     <div id="valtakirja" class="content-section">
        <h2>Valtakirja</h2> 
        <p>Kirjastokortti on henkilökohtainen, mutta voit asioida toisen henkilön puolesta, 
        kun esität henkilön kirjastokortin ja valtakirjan sekä oman henkilötodistuksesi kirjaston asiakaspalvelussa. 
        Valtakirja voi olla kertaluonteinen tai toistaiseksi voimassa oleva, ja siihen on yksilöitävä, minkä asian hoitamista varten se on annettu. 
        Valtakirjalla ei voi teettää kirjastokorttia tai PIN-koodia.</p>
        <p>Valtakirjan tulee sisältää seuraavat tiedot:
        <ul class="list-bullets">
            <li>valtuutetun nimi ja syntymäaika</li>
            <li>asia, jonka hoitamiseen se on annettu (esimerkiksi varauksen nouto, lainan uusiminen, kirjastomaksun maksaminen)</li>
            <li>valtuuttajan nimi, syntymäaika, päiväys ja allekirjoitus</li>
            <li>valtakirjan voimassaoloaika.</li>
        </ul></p>
        <p>Varauksen voit noutaa toisen henkilön puolesta myös ilman valtakirjaa, kun esität varauksen saapumisilmoituksen. Silloin varaus lainataan sinun kirjastokortillesi.</p>
      </div> 
      
      <div id="lainaaminen" class="content-section">
          <h2>Lainaaminen</h2>
          <p>Suurin osa kirjastoaineistosta on lainattavissa. Tavallisin laina-aika on neljä viikkoa. Joillakin aineistoilla on kahden viikon laina-aika. 
          Esineiden ja e-aineistojen laina-aika vaihtelee päivästä neljään viikkoon. <a href="/Content/laina-ajat-ja-maksut">Katso kaikki laina-ajat.</a></p>
          <p>Sinulla voi olla samanaikaisesti korkeintaan 5 konsolipeliä. </p>
          <p>Lainatessasi saat eräpäiväkuitin. Laina-aika loppuu eräpäivänä, kun kirjastot suljetaan.</p>
      </div>
      
      <div id="palauttaminen" class="content-section">
          <h2>Palauttaminen</h2>
          <p>Jos palautat lainan myöhässä, joudut maksamaan myöhästymismaksun. Maksua peritään jokaiselta kalenteripäivältä, siis myös niiltä päiviltä, joina kirjasto on kiinni. 
          Jos sinulla on maksamattomia maksuja 30 € tai enemmän, et voi lainata etkä varata aineistoa etkä uusia lainojasi. 
          Lasten ja nuorten aineistosta tai alle 18-vuotiaiden lainaamasta aineistosta ei peritä myöhästymismaksua. 
          <a href="/Content/laina-ajat-ja-maksut">Ks. Helmet-kirjaston laina-ajat ja maksut</a>.</p>
          <p>Joissakin kirjastoissa on palautusluukku tai -laatikko, johon voit palauttaa aineistoa, kun kirjasto on suljettu. 
          Lainat kuitenkin palautetaan kirjastojärjestelmään vasta, kun kirjasto aukeaa eli siihen asti kertyy sakkomaksuja.</p>
          <p>Palautumattomien lainojen perintä siirtyy perintätoimistolle noin 60 vuorokautta eräpäivän jälkeen. Perintä koskee 18 vuotta täyttäneen asiakkaan lainaamaa aineistoa.</p>
      </div>
      
      <div id="uusiminen" class="content-section">
          <h2>Uusiminen</h2>
          <p>Lainojen uusiminen on kätevintä Helmet.finna.fi -sivuston <a href="/MyResearch/UserLogin">omissa tiedoissa</a>. Voit uusia lainat myös soittamalla tai tulemalla paikan päälle kirjastoon. 
          Lainat voi uusia viisi kertaa, ellei niihin ole varauksia. Jos sinulla on maksamattomia maksuja 30 euroa tai enemmän, et voi uusia lainojasi.</p>
      </div>
      
      <div id="varaaminen" class="content-section">
          <h2>Varaaminen</h2>
          <p>Jos haluat lainata aineistoa, joka on lainassa tai jota ei ole lähikirjastossasi, tee siihen varaus Helmetissä. 
          Varauksesi lähetetään valitsemaasi kirjastoon mahdollisimman nopeasti. Varaaminen on maksutonta. Sinulla voi olla enintään 100 varausta kerrallaan.</p>
          <p>Jos sinulla on maksamattomia maksuja 30 euroa tai enemmän, et voi tehdä varauksia.</p>
          <p>Varauksesi kohdistuu kaikkien Helmet-kirjastojen kokoelmiin. Järjestelmä valitsee ensimmäisen vapautuvan kirjan, levyn, DVD-levyn tms.</p>
          <p>Saat postitse tai sähköpostitse ilmoituksen, kun aineisto odottaa sinua noutokirjastossa. 
          Voit valita ilmoitustavan itse kirjautumalla asiakastietoihisi kohdassa Muuta tietojasi. Aineistoa säilytetään sinulle varattuna 6 arkipäivän ajan. 
          Viimeisen noutopäivän voit tarkistaa kirjautumalla asiakastietoihisi. 
          Jos olet valinnut noutopaikaksi kirjastoauton, varaamasi aineisto otetaan mukaan pysäkille kahdella seuraavalla käyntikerralla.</p>
          <p>Noutamattomista varauksista peritään maksu.</p>
          <p>Voit myös seurata varaustesi tilaa omien asiakastietojesi kautta.</p>
          <ul class="list-bullets">
              <li>Voit noutaa varaamasi aineiston, kun varauksen kohdalla lukee Noudettava viimeistään.</li>
              <li>Kun varauksesi kohdalla lukee Matkalla, varattu teos on matkalla kirjastosta toiseen.</li>
              <li>Varaamasi aineisto ei ole vielä noudettavissa, kun varauksen kohdalla lukee Hyllyssä.</li>
              <li>Jos varauksesi on jonossa, näet varauksesi järjestysnumeron tilakentästä.</li>
              <li>Voit jäädyttää varauksesi esimerkiksi loman ajaksi käyttämällä lukitse-toimintoa. Muista myös aktivoida varauksesi loman jälkeen.</li>
          </ul>
          <p>Joissakin kirjastoissa on käytössä varausten noutoon alias eli salanimi. Aliaksen hankkimisen jälkeen varauksissa ei näy nimeäsi vaan aliaksesi. 
          Jos noudat varaamaasi aineistoa kirjastosta, jossa on käytössä itsepalveluvaraushylly, voit hankkia aliaksen eli salanimen. 
          Aliaksen saat kirjaston asiakaspalvelutiskiltä esittämällä kirjaston hyväksymän voimassa olevan henkilöllisyystodistuksen. 
          Aliaksen hankkimisen jälkeen varauslipukkeessa ei näy nimeäsi vaan aliaksesi. Useissa kirjastoissa on siirrytty numeroituihin varaushyllyihin tai varauksiin.</p>
      </div>
      
      <div id="varaus-tavat" class="content-section">
          <h2>Voit varata aineistoa seuraavilla tavoilla:</h2>
          <p>Voit tehdä varauksen itse <a href="/">Helmet-haussa</a>.</p>
          <p>Henkilökunta voi tehdä varauksen puolestasi kirjastossa tai puhelimessa. Tällöin tarvitaan kirjastokorttisi tai sen numero.</p>
          <p>Voit myös soittaa kirjastoon ja varata siellä hyllyssä olevan teoksen. Tällöin tarvitaan kirjastokorttisi numero. 
          Puhelimitse varattua teosta ei lähetetä toiseen kirjastoon. Nouda varaus kirjastosta, johon olet soittanut.</p>
      </div>
      
      <div id="varaus-ilmoitus" class="content-section">
          <h2>Varausilmoitus, eräpäivätiedote, myöhästymismuistutus ja maksumuistutus</h2>
          <p>Helmet-kirjastot lähettävät ilmoituksia ja muistutuksia tekstiviestinä, sähköpostitse ja postitse. 
          Kirjautumalla omiin tietoihisi osoitteessa Helmet.finna.fi voit tarkistaa, että kaikki yhteystietosi ovat ajan tasalla (kohta Muuta tietojasi).</p>
          <p>Jos olet tallentanut asiakastietoihisi sähköpostiosoitteen, sinulle lähetetään eräpäivän lähestymisestä varoittava ilmoitus kaksi päivää ennen eräpäivää.</p>
          <p>Myöhässä olevasta aineistosta lähetetään ensimmäinen muistutus 14 vuorokauden kuluttua eräpäivästä joko sähköpostitse tai postitse. 
          Tarvittaessa toinen muistutus lähetetään 28 vuorokauden kuluttua eräpäivästä vain postitse.</p>
          <p>Jos olet tallentanut asiakastietoihisi matkapuhelinnumeron Suomen maakoodilla (esim. +358501234567), sinulle lähetetään varausilmoitus tekstiviestinä. 
          Muutoin varausilmoitus lähetetään joko sähköpostitse tai postitse.</p>
          <p>Säilytämme varaamasi aineistoa 6 arkipäivän ajan. Varauksen viimeisen noutopäivän voit tarkistaa kirjautumalla sisään asiakastietoihisi. 
          Jos olet valinnut noutopaikaksi kirjastoauton, varaamasi aineisto otetaan mukaan pysäkille kahdella seuraavalla käyntikerralla.</p>
          <p>Helmet-kirjaston järjestelmästä lähetetään myös erillisiä muistutuksia maksamattomista maksuista velan vanhenemisen katkaisemiseksi.</p>
      </div>
      <p>Viimeksi päivitetty 19.5.2023</p>
   </div>
</div>