<? $this->headTitle($this->translate('Bokbussarna Vanda')); $this->content()->setHeading($this->translate('Bokbussarna Vanda'));?>
<p>Vi har två bokbussar i Vanda, Haave och Tarina. Ring oss vardagar kl. 9-15 på tel. 043 825 1752 eller skicka e-post till adressen auto.kirjasto@vantaa.fi.</p>
<p>Välkommen till bokbussen!</p>
<p><a href="https://www.google.fi/maps/@60.3158163,24.8788882,12z/data=!3m1!4b1!4m2!6m1!1s13Ovxv73Ct6u2qJV2kxyHpV-Mi041MPQR?hl=fi" target="_blank"
aria-label="Tidtabeller i Google Maps. Länken öppnas i ett nytt fönster.">Tidtabeller i Google Maps</a>.</p>



