<h1>Ku soo dhowoow maktabadda Helmet</h1>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Magaalooyinka Espoo, Helsinki, Kauniainen iyo Vantaa maktabadohooga waxaa la isku yiraa maktabadahaa Helmet.</p>
        <p>Maktabadda Helmet:</p>
        <ul class="list-bullets">
            <li>66 maktabodood</li>
            <li>6 maktabadood oo ah gaadhiyo</li>
            <li>adeegga internetka (<a href="https://www.helmet.finna.fi">Helmet.finna.fi</a>) iyo e-maktabadda</li>
        </ul>
        
        <p>Maktabadda waxaad u iman kartaan sidii aad wakhti ugu qaadataan, uguna akhristaan buugag iyo wargeysyo, komputerkana u isticmaashiin ugana amaahataan waxyaabahan kala duwan:</p>
        <ul class="list-bullets">
            <li>buugaagta cilmiga</li>
            <li>buugaagta shekooyinka iyo kuwa gabayada</li>
            <li>buugaagta sawirada</li>
            <li>wargeysyada</li>
            <li>CDyada muusiga</li>
            <li>buugaagta muusiga</li>
            <li>DVD iyo BD filimmo</li>
            <li>darsiga luuqadaha</li>
            <li>buugaagta codadka</li>
            <li>buugaagta carruurta sida kuwa sawirrada, sheekada, muusiga iyo filimmada</li>
        </ul>
        
        <p>Waxyaabaha kala duwan ee maktabadda yaalla waa af finish, af swedish iyo afaf badan oo kala duwan. Hadii aanad ku helin afkaaga hooyo, waxaa ka codsan kartaa maktabadda in ay 
        dalbaan. Waxyaabaha la helayo way kala badanyihiin. Maktabadda tagisteda waxyaabaha laga ballansanayo ama laga amaahdo, isticmaalka komputerka kulli waa lacag la’aan.</p>
      </div>
     <div id="osa1" class="content-section">
        <h2>Sidan ayaad ku heleysaa kaarka maktabadda</h2>
        <p>Sida aad wax u amaahatid waxa aad u baahantahay kaarka maktabadda. Kaarka waxaa helikara kulli dadka Finland daggan. Kaarka waxaad ka heli kartaa maktabadaha Helmet, 
        marka aad tustit passporkaaga ama waraaqaha aqoonsiga ama kaarka dadka ku jira meelaha sharciga lagu sugo. Dadka da’da 15 ka yar waxa uu u baahanyahay saxeexa waalidka ama 
        qofka masuulka ah. Kaarka maktabadda qofka leh keliya ayaa isticmaali kara. Waxyaabaha lagu amaahdo kaarka qofka kaarka leh ayuu xil ka saaranyahay. Hadii uu kaa dhumo kaarku ama 
        adresskaaga uu is bedelo, sida ugu dhakhsaha badan ula soo socodsii maktabadda.</p>
      </div>
      <div id="osa2" class="content-section">
        <h2>Waxyaabaha la amaahdo iyo soo celintooda</h2>
        <p>Buugaagta wakhtiga aad haysan kartid waa 4 todobad. Muusiga, filimada, Bestseller waxyaabaha lagu qorey waxa laga yaabaa in wakhtiga amaahda ayka yartahay 4 todobad. 
        Haddii waxyaabaha aad amaahatid aad lasoo daahdid, wakhtiga soo celinta waxaa lagaa qaadayaa lacag soo daahista daradeed. Lacagtaas hadii aanad bixin ama aanad soo celin 
        waxyaabaha aad amaahatid waxaa lagula tiigsanaya xuquqda amahda.</p>
        <p>Wakhtiga amaahda waxa aad ku kordhisan kartaa hadii aad soo wacdid maktabadda ama komputerka <a href="https://www.helmet.finna.fi">Helmet.finna.fi</a>. Sida internetka aad 
        uga kordhisatid wakhtiga waxa aad u baahantahay afar nambar oo aad ka heleysidmaktabadda. Hadii qof kale uu ballansaday laakiin ma kordhisankartid wakhtiga amaahda.</p>
        <p>Waxa aad ku celinkartaa waxaa aad amaahatey maktabadaha oo dhan oo Helmetka ah. Marka so celinta uma baahnid kaarka maktabadda. Waxyaabaha e-amaahda wakhtigooda amaahda waa 
        dhowr maalmod kadib si automatic ah ayey u soo celismeyaan maalinta ay ku egyihiin.</p>
      </div>
      <div id="osa3" class="content-section">
        <h2>Ballansashada</h2>
        <p>Macmiil kale hadii uu haysto ama amaahdey waxa aad u baahantihid, waxaad ku ballansan kartaa Helmet.finna.fi ama maktadda. Marka aad soo doonanaysidna maktabadda ayaa ku 
        la soo socodsiinaysa.</p>
      </div>
      <div id="osa4" class="content-section">
        <h2>Helmet.finna.fi</h2>
        <p>Internetka <a href="https://www.helmet.finna.fi">www.Helmet.finna.fi</a> waxa aad ka heleysaa warka maktabadaha oo dhan iyo adeegooda, wakhtiyada ay furanyihiin iyo meesha 
        ay ku yaallaan. Xitaa waxyaabaha aad ka helikartid maktabaha HelMet ayad ka raadsankartaa meeshaas. Waxa kale ood suubin kartaa in aad ka amaahatid e-buugaag iyo wageysyo, 
        waxaad dhegeysankartaa muusig, filimmo ayaad dawaankartaa ama luuqado ayaad ka barankartaa.</p>
        <p>
      </div>
      <div id="osa5" class="content-section">
        <h2>Maktabadda afafka kala duwan (Monikielinen kirjasto)</h2>
        <p>Maktabadda afafka kala duwan waxa yaalla buugaag, muusig, fillimmo iyo wargeysyo illaa 80 luuqad. Waxyaabahaan waxaad ka heleysaa maktabadda Pasila oo Helsinki ku taalla 
        waxyabahana waad ka amaahankartaa. Maktabadaha kuu dhow waxa aad ka dalbankartaa in ay waxyaabo kaaga dalbaan maktabadda afafka kala duwan.</p>
      </div>
      <div id="osa6" class="content-section">
        <h2>Maktabadda afka Ruushka (Venäjänkielinen kirjasto)</h2>
        <p>Waxyaabahan waxa aad ka heleysaa maktabadda Sello oo ku taalla Espoo. Maktabadda afka ruushka waxa isticmaali kara macmiisha ruushka ah iyo kuwa waxyaabaha afka ruushka 
        xiiseeya. Waxyaabaha maktabadaan yaalla waxa laga dalban karaa maktabadaha dhan oo ku yaalla Finland.</p>
      </div>
      <div id="osa7" class="content-section">
        <h2>Barashada afka iyo isla cabidda kafeyga</h2>
        <p>Maktabadhaha Helmet waxa aad ku barankartaa afka finishka adiga oo la jooga koox. Afkaaga finishka hadii uu fiicneyn dhib ma jirto laakiin waxa fiican in aad ku hadli
        garaneysid waxyar. Warbixin ku saabsan arintan waxa aad ka heleysaa Helmet.finna.fi. Adiga ayaa doorsanaya kooxda aad rabtid in aad ku biirtid iyo mararka aad rabtid in 
        aad ka qeyb qaadatid. Kooxahaan lagu biirayo ee af barasho waa lacag la’aan.</p>
      </div>
      <div id="osa8" class="content-section">
        <h2>Qalabka laga barto afka finishka</h2>
        <p>Waxaad ka amaahan kartaa maktabadaha buugaagta laga barto afka finishka, qaamuusyo iyo buugag af finish ah oo aan adkeyn. Waxaad ka baran kartaa afka komputerka, 
        waxaanad ka fiirsan kartaa Helmet.finna.fi.</p>
      </div>
      <div id="osa9" class="content-section">
        <h2>PressDisplay</h2>
        <p>Waxaad ka heleysaa 2 700 oo wargeysyo ah iyo 1 700 wargeysyada joogtoda ah oo 100 wadan laga keeney oo 60 af ku qoran. Guriga ayaad ka isticmaalikartaa. Waxaad 
        u baahantahay marka aad geleysid inernetka iyo nambarka kaarkaaga maktabadda. Waxaad ka geli kartaa Helmet.finna.fi.</p>
      </div>
      <div id="osa10" class="content-section">
        <h2>Wi-fi</h2>
        <p>Maktabad kasta waxa ay leedahay internet macmiisha ay isticmaali karaan.</p>
      </div>
      <div id="osa11" class="content-section">
        <h2>Munaasabadaha maktabadda</h2>
        <p>Maktabadaha waxa laga dhigaa riwaayado iyo munaasabado kala duwan oo loogu talagaley dhamaan dadka dadoodu kala duwan tahay. Warbixinta waxa aad ka heleysaa maktabadda ama
        Helmet.finna.fi. Carruurtana waxa loogu akhriyaa sheekoyinka afaf kala duwan. Munaasbadahan waxaad weydiin kartaa maktabadaada.</p>
        <p>Ku soo dhowoow maktabadda!</p>
      </div>
   </div>
</div>