<? $this->headTitle($this->translate('Bibliotekskort och lån')); $this->content()->setHeading($this->translate('Bibliotekskort och lån'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="bibliotekskort" class="content-section">
        <p>Du kan få ett bibliotekskort i alla Helmet-bibliotek genom att uppge din adress och visa ett identitetsbevis som är godkänt av biblioteket och är försett med fotografi 
        och personnummer. För att få ett kort måste du ha en adress i Finland.</p>
        <p>I biblioteket godkänns följande identitetsbevis:</p>
        <ul class="list-bullets">
          <li>identitetskort utfärdade inom EU</li>
          <li>pass</li>
          <li>finskt körkort</li>
          <li>FPA-kort med foto, för personer under 18 år också utan foto</li>
          <li>boendeintyg utfärdat av en i Finland belägen mottagningscentral</li>
          <li>uppehållstillståndskort utfärdat av Migrationsverket.</li>
        </ul>
        <p>En person som inte fyllt 15 år får kortet då målsman gett sitt skriftliga samtycke. Daghem, skolor och andra inrättningar och samfund beviljas bibliotekskort för ett år i sänder. 
        Kortet ska ha en ansvarsperson (t.ex. en lärare) som ser till att kortet används på ett ändamålsenligt sätt.</p>
        <p>Du kan få ditt bibliotekskort snabbare om du fyller i blanketten på förhand, skriver ut den och tar utskriften med dig till biblioteket.</p>
        <p><a href="/themes/custom/files/kirjastokorttihakemus_swe.pdf" target="_blank">Anmälning som bibliotekets användare (PDF)</a></p>
        <p>Du som fyllt 15 år kan spara dina personuppgifter i förväg genom att fylla i blanketten i länken nedan. Om du använder blanketten går det snabbare att få ett bibliotekskort. 
        När du har sparat dina uppgifter kan du hämta ditt kort i vilket Helmet-bibliotek som helst. Ta med ett giltigt personbevis. 
        Om du inte hämtat ditt bibliotekskort inom tre månader raderas uppgifterna.</p>
        <p><a href="https://luettelo.helmet.fi/selfreg*swe~S9" target="_blank" aria-label="Registering av bibliotekskort. Länken öppnas i ett nytt fönster.">Registering av bibliotekskort</a></p>
        <p>Om du inte själv kan besöka biblioteket på grund av sjukdom, funktionsnedsättnig eller annan orska kan du anmäla dig som flexkund. </p>
        <p><a href="/themes/custom/files/joustoasiakas_swe.pdf" target="_blank">Anmäl dig som flexkund (PDF)</a></p>
        <p>Helmet-bibliotekskortet är gemensamt för Esbo, Grankulla, Helsingfors och Vanda stadsbibliotek. Du kan låna, reservera och lämna tillbaka material i alla bibliotek i regionen.</p>
        <p>De flesta tjänster är gratis. Men det kostar att beställa material som fjärrlån från bibliotek utanför regionen. Vi uppbär också en förseningsavgift om du lämnar tillbaka materialet för sent. 
        Reserveringarna är avgiftsfria.</p>
        <p>Då du undertecknar bibliotekskortet förbinder du dig att följa <a href="/Content/kayttosaannot?lng=sv">bibliotekets regler</a>.</p>
      </div>
      
     <div id="pin-kod" class="content-section">
        <h2>PIN-kod och egna uppgifter</h2> 
        <p>En PIN-kod är ett fyrsiffrigt tal som hör ihop med bibliotekskortet. Du behöver koden då du använder låneautomaten, 
        <a href="/">kontrollerar eller förnyar dina lån eller reserverar material via webbiblioteket Helmet</a>. 
        PIN-koden behövs också då du använder bibliotekets övriga webbtjänster samt vid kunddatorerna. PIN-koden får du personligen i biblioteket eller bokbussen.</p>
        <p>Om har glömt din PIN-kod får du en ny med hjälp av funktionen Har du glömt din PIN-kod? förutsatt att du har gett oss din e-postadress. 
        Ifall vi inte har din e-postadress kan du få en ny kod i biblioteket. Ta med identitetsbevis.</p>
      </div>
      
      <div id="fullmakt" class="content-section">
        <h2>Fullmakt</h2>
        <p>Bibliotekskortet är personligt, men du kan sköta ärenden åt en annan person 
        (t.ex. hämta en reservation) om du visar personens bibliotekskort och en fullmakt samt ditt eget identitetsbevis i kundtjänsten. 
        Fullmakten kan gälla en gång eller tillsvidare, och det bör framgå vilka ärenden fullmaktsinnehavaren får sköta. 
        Du kan inte få ett bibliotekskort eller en PIN-kod med fullmakt.</p>
        <p>Fullmakten ska innehålla följande uppgifter:</p>
        <ul class="list-bullets">
            <li>den befullmäktigades namn och födelsedatum</li>
            <li>ärendet för vilket det har givits (t.ex. avhämta en reservation, förnya ett lån, betala en biblioteksavgift)</li>
            <li>fullmaktsgivarens namn och födelsedatum samt datum och underskrift</li>
            <li>fullmaktens giltighetstid.</li>
        </ul>
        <p>Du kan avhämta en reservation för annan person också utan fullmakt när du visar meddelandet om att reservationen kan avhämtas. 
        Då lånas reservationen ut med ditt bibliotekskort.</p>
      </div>
      <div id="att-låna" class="content-section">
        <h2>Att låna</h2>
        <p>Största delen av bibliotekets material kan lånas. Den vanligaste lånetiden är fyra veckor. 
        En del av materialet har två veckors lånetid. Lånetiden för föremål och e-böcker varierar från en dag till fyra veckor. 
        <a href="/Content/laina-ajat-ja-maksut?lng=sv">Se alla lånetider.</a></p>
        <p>Du kan ha högst 5 konsolspel samtidigt. </p>
        <p>Då du lånar får du ett kvitto där förfallodagen framgår. Lånetiden upphör på förfallodagen då biblioteket stängs.</p>
      </div>
      <div id="att-returnera" class="content-section">
        <h2>Att returnera</h2>
        <p>Vissa bibliotek har luckor där du kan returnera dina lån då biblioteket är stängt. 
        De lån som kommit till luckan tas bort från ditt låneregister först den dag då biblioteket är öppet nästa gång.</p>
        <p>Om du lämnar tillbaka materialet du lånat för sent måste du betala en förseningsavgift. 
        Avgiften debiteras för alla dagar, också för de dagar då biblioteket är stängt. Om du har obetalda avgifter på 30 € eller mera kan du inte låna, reservera eller förnya lån. 
        För material som tillhör en barn- och ungdomsavdelning, eller för material som lånats av en person som inte fyllt 18 år, uppbärs ingen förseningsavgift. 
        <a href="/Content/laina-ajat-ja-maksut?lng=sv">Se Lånetider och avgifter.</a></p>
        <p>Lån som inte returnerats överförs till en inkassobyrå då 60 dygn gått sedan förfallodagen. Också material för barn och unga överförs till inkassobyrån.</p>
      </div>
      <div id="att-fornya-lan" class="content-section">
        <h2>Att förnya lån</h2>
        <p>Det är enklast att förnya lånen via <a href="/MyResearch/UserLogin">Mitt bibliotekskonto</a> i www.helmet.finna.fi. 
        Du kan också förnya dina lån genom att ringa eller då du besöker biblioteket. 
        Du kan förnya lånen fem gånger om ingen har reserverat materialet. Om du har obetalda avgifter på 30 € eller mera kan du inte förnya dina lån. </p>
      </div>
     <div id="att-reservera" class="content-section">
            <h2>Att reservera</h2>
            <p>Om du vill låna material som inte finns i ditt närbibliotek eller är utlånat kan du <a href="/">reservera det via Helmet</a>. 
            Materialet skickas så fort som möjligt till det bibliotek där du vill hämta det. Reserveringarna är avgiftsfria. 
            Du kan samtidigt ha högst 100 reserveringar. </p>
            <p>Du kan inte reservera material om du har obetalda avgifter på 30 euro eller mera.</p>
            <p>Din reservation riktas till alla Helmet-bibliotek. Systemet väljer det exemplar som först blir tillgängligt.</p>
            <p>Du får ett meddelande per post eller e-post då materialet du reserverat finns att hämta på biblioteket du valt. 
            Du kan välja postningssätt genom att logga in på Dina uppgifter och klicka på Ändra personliga uppgifter. 
            Materialet är reserverat för dig i 6 vardagar. IDina uppgifter ser du när du senast kan hämta reservationen. </p>
            <p>Din reservation tas med till bokbussen de följande två gånger bussen besöker din hållplats.</p>
            <p>Reservationer som inte hämtas är avgiftsbelagda. </p>
            <p>Du kan också följa dina reservationer via Dina uppgifter.</p>
            <ul class="list-bullets">
                <li>Du kan hämta din reservation då dess status ärMåste hämtas senast.</li>
                <li>Då status för din reservation är På väg är det reserverade materialet på väg från ett bibliotek till ett annat.</li>
                <li>Då status för din reservation ärInneär det reserverade materialet ännu inte klart att hämta.</li>
                <li>Om det är kö på materialet du beställt kan du se din plats i kön.</li>
            </ul>
            <p>Du kan reservera på följande sätt:
            <ol class="list-numbers">
                <li>Du kan göra reservationen själv via internet på adressen <a href="/">www.helmet.finna.fi</a></li>
                <li>Personalen kan göra reservationen åt dig i biblioteket eller per telefon. 
                Visa ditt bibliotekskort eller uppge dess nummer.</li>
                <li>Du kan också ringa till biblioteket och reservera material som finns inne. 
                För detta behövs ditt bibliotekskortsnummer. Material som reserveras per telefon skickas inte från ett bibliotek till ett annat, 
                utan du måste själv avhämta det från det bibliotek som du har ringt till.</li>
            </ol></p>
            <p>I vissa bibliotek används ett alias, en pseudonym för avhämtning av reservationer. 
            Ditt alias får du vid bibliotekets lånedisk efter att ha visat upp ett giltigt identitetsbevis som biblioteket godkänner. 
            Därefter då du avhämtar boken så syns inte ditt namn på reservationslappen, utan ditt alias. </p>
            <p>I flera bibliotek har man övergått till reserveringshyllor eller reserveringar med nummer.</p>
        </div>
        
        <div id="meddelanden" class="content-section">
            <h2>Meddelanden om reservationer och förfallodagar, påminnelser om förseningar och avgifter</h2>
            <p>Helmet-biblioteken skickar meddelanden och påminnelser som textmeddelanden, per e-post och per post. 
            Logga in på ditt bibliotekskonto och kontrollera under "Ändra personliga uppgifter" att alla dina uppgifter är korrekta.</p>
            <p>Om du har uppgett en e-postadress skickar vi en varning om att förfallodagen närmar sig två dagar före förfallodagen. 
            Om materialet blir försenat skickar vi den första påminnelsen 14 dagar efter förfallodagen. 
            Den andra påminnelsen skickas 28 dagar efter förfallodagen. Det är möjligt att få den första påminnelsen som e-post, 
            men den andra påminnelsen skickas alltid per post.</p>
            <p>Om du har uppgett ett mobiltelefonnummer med Finlands landskod (t.ex. +358501234567), 
            får du meddelanden om reservationer som textmeddelande.  Annars skickas meddelanden om reservationer antingen per e-post eller post.</p>
            <p>Materialet är reserverat för dig i 6 vardagar.  Du ser den sista avhämtningsdagen genom att logga in på ditt bibliotekskonto. 
            Om du har valt bokbussen som avhämtningsplats tar vi med ditt reserverade material de två följande gånger bussen besöker din hållplats.</p>
            <p>Helmet-biblioteket skickar också särskilda påminnelser om obetalda avgifter för att förhindra att skulden föråldras.</p>
        </div>
        <p>Senast uppdaterad 19-05-2023</p>
      </div>
   </div>
</div>