<? $this->headTitle($this->translate('Mobile Library Vantaa')); $this->content()->setHeading($this->translate('Mobile Library Vantaa'));?>
<p>There are two mobile libraries in Vantaa, Haave and Tarina. Call us weekdays 9am to 3pm on 043 825 1752 or send us email auto.kirjasto@vantaa.fi.</p>
<p>Welcome to the mobile library!</p>
<p><a href="https://www.google.fi/maps/@60.3158163,24.8788882,12z/data=!3m1!4b1!4m2!6m1!1s13Ovxv73Ct6u2qJV2kxyHpV-Mi041MPQR?hl=fi" target="_blank" 
aria-label="Route schedule on Google Maps. The link opens in a new window.">Route schedule on Google Maps</a>.</p>