<? $this->headTitle($this->translate('Library card and loans')); $this->content()->setHeading($this->translate('Library card and loans'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="library-card" class="content-section">
        <p>Helmet library card is joint card shared by Espoo, Helsinki, Kauniainen and Vantaa. 
        You may check out, reserve, and check in materials from the collections of all the other libraries in the district
        as well as your own neighbourhood library. Most of our services are free of charge. 
        However, the interlibrary loans outside the district have a fee, and the overdue loans are subject to overdue fees. 
        Reservations are free of charge.</p>
        <p>You can obtain a library card and PIN code from any Helmet library by providing your address and presenting a valid ID card
        with a photograph and personal identity number accepted by the library. 
        You need to have an address in Finland to get a library card.</p>
        <p>Helmet library accepts the following identification cards:</p>
        <ul class="list-bullets">
          <li>I.D. cards from EU countries</li>
          <li>passports</li>
          <li>Finnish driving licences</li>
          <li>Finnish SII cards with photos, for those under 18 years also without photos</li>
          <li>resident cards issued by any reception centre in Finland</li>
          <li>residence permit card issued by the Finnish Immigration Service.</li>
        </ul>
        <p>Anyone under 15 years of age can get a library card with a written approval by the guardian. 
        A day care centre, school, other institution or community can have a library card for twelve months at a time. 
        A contact person (e.g. a teacher) is appointed for the card. This person will oversee that the card is used appropriately.</p>
        <p>It is easier for us to make a new library card for you if you fill the form below, print it out and take it with you to the library.</p>
        <p><a href="/themes/custom/files/kirjastokorttihakemus_eng.pdf" target="_blank">Registration as a library user (.PDF)</a></p>
        <p>If you are 15 years old, you can save your own personal details in customer register in advance
        by filling the form by clicking the link below. You will get your library card quicker by filling the registration form beforehand. 
        Once you have saved your personal details, you can pick up your library card from any Helmet library. Take a valid ID card with you. 
        If you do not pick up your library card within three months from the date that you filled the registration form, 
        your personal details will be deleted.</p>
        <p><a href="https://luettelo.helmet.fi/selfreg~S9" target="_blank" aria-label="Library card pre-registration. The link opens in a new window.">
        Library card pre-registration</a></p>
        <p>By signing the library card, you commit to abiding by all <a href="/Content/kayttosaannot?lng=en-gb">Helmet Library user regulations.</a></p>
        <p>If you cannot visit the library due to illness, injury or other similar reason you can register as a flexi customer.</p>
        <p><a href="/themes/custom/files/joustoasiakas_eng.pdf" target="_blank" aria-label="">Registration as a flexi customer (PDF)</a></p>
      </div>
      
     <div id="pin-code" class="content-section">
        <h2>PIN code and your details</h2>
        <p>Your PIN or Personal Identification Code is a four-digit password linked to the library card. 
        The PIN code allows you to use a self-service automat, review your loan details, renew loans or reserve material on Helmet Web Library. 
        You will also need the PIN code for other web services and to use customer computers. 
        You can get the PIN code by visiting the library or mobile library in person.</p>
        <p>Provided you have given us your email address, 
        you can access the password recovery function you find on the page you use to log into your record.</p>
        <p>In the case we do not have your email address, we shall change your PIN code at the service desk of any Helmet library. 
        Please bring your ID with you. </p>
      </div>
      
      <div id="power-of-attorney" class="content-section">
        <h2>Power of attorney</h2>
        <p>Library card is personal but you can act on behalf of another person if you present their library card, a power of attorney, 
        and your identification card in the library. The power of attorney may be continuing or for one time use only. 
        You must include details on what the power of attorney covers. A power of attorney cannot be used to create a library card or PIN.</p>
        <p>The power of attorney must contain the following information:</p>
        <ul class="list-bullets">
            <li>assignee’s name and date of birth</li>
            <li>what it has been assigned for (e.g. picking up a reservation, renewing a loan, paying a library fee)</li>
            <li>assigner’s name, date of birth, date and signature</li>
            <li>validity of the power of attorney.</li>
        </ul>
        <p>You can also pick up a reservation on someone else’s behalf without a power of attorney if you present the arrival notification 
        for the reservation. In that case, the reservation will be borrowed with your library card.</p>
      </div>
      
      <div id="loans" class="content-section">
        <h2>Loans</h2>
        <p>Most library material can be borrowed. The loan time is normally four weeks. However, it varies from 1 day to 28 days. 
        You will be issued with a receipt upon borrowing. The loan time will expire on the day of expiry when the libraries close.</p>
        <p>You may have no more than 5 console games on loan at the same time.</p>
      </div>
      
      <div id="returning" class="content-section">
        <h2>Returning</h2>
        <p>Some libraries have return hatches where loans can be returned outside opening times. 
        However, loans returned through the return hatches will be updated in your loan details on the following day the library is open.</p>
        <p>If you return your loan late, you will need to pay a late return fee. 
        The fee is €0.20 per loan per day, and the maximum fee is €6 per loan. 
        The fee will be charged for each calendar day, including days when the library is closed. 
        If you have €30 or more in unpaid fees, you will not be able to borrow or reserve material or renew your loans. 
        Children's and young people's materials or materials borrowed by anyone under 18 years will not incur a late return fee.</p>
        <p>Recovery of unreturned loans will be transferred to a recovery agency approximately 60 days after the expiry day. 
        Unreturned children's and young people's material will also be recovered through a recovery agency.</p>
      </div>
      
      <div id="renewal" class="content-section">
        <h2>Renewal</h2>
        <p>Loan renewal is easiest to do through <a href="/">Helmet.finna.fi</a>. You can also renew your loans by telephoning or visiting the library. 
        Loans can be renewed up to five times, if they have no reservations pending. 
        If you have 30 euros or more in unpaid fees, you will not be able to renew your loans.</p>
        <p>Libraries also have materials that cannot be renewed, such as bestsellers, special collections and objects.</p>
      </div>
      
      <div id="reserving" class="content-section">
        <h2>Reserving</h2>
        <p>If you want to borrow material that is on loan or not available in your local library, make a reservation through <a href="/">Helmet</a>. 
        Your reservation will be sent to the library you have selected as quickly as possible. 
        You can have a maximum of 100 reservations at any one time.</p>
        <p>If you have 30 euros or more in unpaid fees, you will not be able to make reservations.</p>
        <p>You will receive a notification by email or post when the material is ready at your collection library. 
        You can select how you wish to be notified by logging in to your customer details in the section "Modify personal information". 
        The material will be kept reserved for you for 6 workdays. You can check the last collection day by logging in to your customer details. 
        If you have selected a mobile library for collection, your reserved material will be available for you at the mobile library stop 
        on two subsequent dates.</p>
        <p>A fee will be charged for uncollected reservations. You can also check the status of your reservations through your own customer details.</p> 
        <ul class="list-bullets">
            <li>You can collect the material you have reserved when your reservation status says "Must pick up by".</li>
            <li>When your reservation status says "In transit", the reserved item will be en route from one library to the other.</li>
            <li>Your reserved material will not be ready for collection, when the status says "On shelf".</li>
            <li>If your reservation is queued, you will see your reservation order number in the status field.</li>
            <li>You can freeze your reservations. e.g. during vacations, by using freeze function. 
            Please remember to activate your reservations after your vacation.</li>
        </ul>
        <p>You can reserve material in the following ways:</p>
        <ol class="list-numbers">
            <li>You can make a reservation yourself on <a href="/">Helmet.finna.fi.</a></li>
            <li>Library staff can make your reservation for your in the library or over the phone. 
            In that case, you will need your library card or library card number.</li>
            <li>You can also telephone the library and reserve material available on shelves. Your library card number is needed. 
            Material reserved by phone will not be sent to another library. Collect your reservation from the library you telephoned.</li>
        </ol>
        <p>At some libraries, you can pick up reservations under an alias (an assumed name). 
        You will get the alias from the customer service desk at the library, when you present a valid ID card accepted by the library. 
        After you have acquired the alias, the reservation pick up slip will no more show your name but your alias.</p>
        <p>Several libraries have switched to numbered reservation shelves or reservations.</p>
      </div>
      <div id="notification" class="content-section">
        <h2>Reservation notification, due date notification, late return reminder and payment reminder</h2>
        <p>The Helmet Library sends notifications and reminders as text messages, by email and post. 
        Please update your contact info by logging in on Helmet.fi.</p>
        <p>Should you have given us your email address, you will receive due date notification two days before the due date.</p>
        <p>You will receive the first reminder of overdue material 14 days after the due date by email or by post. 
        If necessary, the second reminder will be sent to you 28 days after the due date only by post.</p>
        <p>Should you have given us your mobile phone number with Finland’s land code (e.g. +358501234567), 
        you will receive notifications for your reservations by text message. Otherwise you receive notifications by email or by post.</p>
        <p>We hold your reservations for you for 6 workdays. You can check the last collection day by logging in on Helmet.fi. 
        If you have selected a mobile library for collection, your reservations will be available for you at the mobile library stop 
        of your choice on two subsequent dates.</p>
        <p>The Helmet Library system will send reminders of unpaid fees to prevent the debt from expiring.</p>
      </div>
      <p>Last updated 5/19/2023</p>
   </div>
</div>