<? $this->headTitle($this->translate('Biblioteket på avstånd')); $this->content()->setHeading($this->translate('Biblioteket på avstånd'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="boken-kommer" class="content-section">
        <h2>Boken kommer -servicen</h2>   
        <p>Via servicen Boken kommer körs böckerna direkt hem till dig. Servicen är avsedd som på grund av ålder, sjukdom, 
        rörelseförhinder eller invaliditet inte själva kan ta sig till biblioteket. Kunden får önskat material hemkört en gång i månaden. 
        Allt material inom HelMet-biblioteken får lånas: böcker, ljudböcker, tidningar, filmer och musik. Servicen är gratis för kunden.</p>
        <p>Om du vill ha stadsbibliotekets hemtjänst på svenska, kontakta <a href="tel:0405468091">040 546 8091</a>.</p>
      </div>
     <div id="flex" class="content-section">
        <h2>Bli flexkund om du har svårt att komma till biblioteket</h2>
        <p>I Helmet-biblioteken kan du nu bli s.k. flexkund. Så blir det lättare för dig att sköta dina biblioteksärenden om du har svårt att 
        själv ta dig till biblioteket.</p>
        <p>I vissa situationer kan det vara svårt eller t.o.m. omöjligt att besöka ett bibliotek. Sådana hinder kan t.ex. vara sjukdom, 
        funktionsnedsättning eller svårigheter att röra sig.</p>
        <p>Om du eller någon närstående inte kan besöka biblioteket personligen kan ni ansöka om att bli flexkunder. Det innebär att en låntagare 
        befullmäktigar en annan person att sköta biblioteksärendena i hens ställe.</p>
        <p>Den som är flexkund behöver inte betalaförseningsavgifter och lånen kan inte gå till indrivning. Däremot är lånetiderna samma som för alla
        andra och du kan förnya lånen enligt samma regler som för andra kunder.</p>
        <p>Du kan registrera dig som flexkund i vilket Helmet-bibliotek som helst. För registreringen behöver vi uppgifter både om den som 
        ger fullmakten och den som blir befullmäktigad. Du får blanketten på biblioteket eller via webbplatsen.</p>
        <p><a href="/themes/custom/files/joustoasiakas_swe.pdf" target="_blank" aria-label="Anmäl dig som flexkund (PDF).">Anmäl dig som flexkund (PDF)</a></p>
        <p>Det går fortfarande bra att sköta biblioteksärenden åt någon annan med hjälp av en skriven fullmakt. </p>
      </div>
      <div id="fraga" class="content-section">
        <h2>Fråga så klarnar det</h2>
        <p>Biblioteket erbjuder personlig informationssökning om vilket ämne som helst – oberoende om det är frågan om arbete, studier eller din hobby. 
        Du kanske söker något bra att läsa, den snabbaste cykelvägen, ett nytt konsolspel eller råd om hur du ska använda din dator? Vi står beredda att hjälpa dig i alla slags frågor. 
        Via biblioteket kan du också söka i ett stort antal mångsidiga databaser.</p>
      </div>
      <div id="lasa-och-lyssna" class="content-section">
        <h2>Läsa och lyssna på nätet</h2>
        <p>Biblioteket erbjuder tusentals böcker, ljudböcker, tidningar och tidskrifter i elektronisk format. I e-tjänsterna hittar du bland annat ny litteratur på finska och engelska 
        samt utländska tidningar och tidskrifter. För att använda tjänsterna behöver du ett Helmet-bibliotekskort, internetuppkoppling och en dator eller en mobil enhet.</p>
      </div>
      <div id="musik" class="content-section">
        <h2>Musik på nätet</h2>
        <p>Helmet-biblioteken ger sina kunder tillgång till tre Naxos-musiktjänster.</p>
        <ul class="list-bullets">
          <li>I Naxos Music Library hittar du klassisk musik, samt i någon mån folkmusik och äldre blues.</li>
          <li>Du kan lyssna på jazz också via Music Library Jazz.</li>
          <li>World Music Library ger dig tillgång till världsmusik.</li>
        </ul>
        <p>För att logga in i tjänsterna behöver du ett Helmet-bibliotekskort.</p>
        <p>I Medici.tv kan du titta på tusentals videor av högsta kvalitet, av såväl konserter, operor och baletter som dokumentärer och undervisningsmaterial.</p>
      </div>
   </div>
</div>





