<? $this->headTitle($this->translate('Library outside the library')); $this->content()->setHeading($this->translate('Library outside the library'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="flexi-customer" class="content-section">
        <h2>The flexi customer model allows you to use library services even when you can’t visit the library</h2>
        <p>Flexi customer model makes using library services easier when you are unable to go to the library yourself.</p>
        <p>Visiting the library may be difficult or even impossible in some situations. Illness, disability or impaired mobility may make it difficult to access the library.</p>
        <p>If you or your relative or friend have a hindrance that makes personal library visits difficult, you can apply for a flexi customer account. The flexi customer model means 
        that the customer will authorise someone else to visit the library on their behalf.</p>
        <p>Overdue fees will not be charged for the loans of flexi customers, and their outstanding fees will not be collected. However, the loan periods and renewals will be the same
        as for other customers.</p>
        <p>You can register as a flexi customer at any Helmet library. To register, you need the personal information of both the authoriser and the authorised person. You can fill the 
        <a href="/themes/custom/files/joustoasiakas_eng.pdf" target="_blank">registration form</a> at a library or home.</p>
        <p>It remains possible to use the library services on another person’s behalf under a power of attorney. Customers may also use the home library services.</p>
      </div>
     <div id="esim1" class="content-section">
        <h2>Ask and find out!</h2>
        <p>Whether it is your work, studies or hobbies, the library provides personalised information search for the subject you want to find more about. 
        We are here to help you to find something better to read, the fastest cycling route, a new console game, assist you with using your computer, or whatever else you need to know. 
        The library also gives you access to various databases.</p>
      </div>
     <div id="read-and-listen" class="content-section">
        <h2>Read and listen online</h2>
        <p>The library offers thousands of books, audiobooks, magazines and newspapers in electronic format. You can find, for example, new literature in English and Finnish
        as well as newspapers and magazines in many languages. To acces the e-resources you need a Helmet library card, internet access and a computer or mobile device.</p>
      </div>
      <div id="music" class="content-section">
        <h2>Find music online</h2>
        <p>Helmet libraries offer their customers three Naxos music services.</p>
        <ul class="list-bullets">
          <li>In Naxos Music Library you can find classical music as well as some folk music and older jazz and blues.</li>
          <li>Jazz has its own service, Music Library Jazz, which holds thousands of jazz albums from different eras.</li>
          <li>World Music Library holds world music.</li>
        </ul>
        <p>You need a Helmet library card to access the services.</p>
        <p>With Medici.tv's video service, you can watch thousands of top-quality videos of concerts, operas and ballets, as well as documentaries and teaching materials.</p>
      </div>
   </div>
</div>


