<? $this->headTitle($this->translate('Kun et pääse kirjastoon')); $this->content()->setHeading($this->translate('Kun et pääse kirjastoon'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="kotipalvelu" class="content-section">
        <h2>Kotipalvelu tuo kirjat kotiovellesi</h2>
        <p>Onko sinun hankalaa tulla kirjastoon iän, sairauden tai vamman takia? Oletko liikuntaesteinen? Ota yhteyttä kirjaston kotipalveluun ja kerro, mikä kirjaston tarjonnassa kiinnostaa. 
        Sen jälkeen kotipalvelun kuljetusauto kaartaa pihaasi kerran kuussa ja tuo tilaamasi aineiston kotiinkuljetuksena. Voit myös valtuuttaa jonkun 
        <a href="/Content/kirjastokortti-ja-lainaaminen#valtakirja">asioimaan puolestasi valtakirjalla.</a></p>
        <p>Ota yhteyttä oman kaupunkisi Kotikirjastoon:</p>
        <ul class="list-bullets">
            <li>Espoo: puhelimitse arkisin klo 9-14 <a href="tel:046 877 2986">046 877 2986</a> ja <a href="tel:046 877 2988">046 877 2988</a>
            tai sähköpostilla: <a href="mailto:kirjasto.kotipalvelu@espoo.fi">kirjasto.kotipalvelu@espoo.fi</a></li>
            <li>Helsinki: puhelimitse arkisin kello 12–15 <a href="tel:0931085214">(09) 3108 5214</a> tai sähköpostilla <a href="mailto:kotikirjasto@hel.fi">kotikirjasto@hel.fi</a>.</li>
            <li>Kauniainen: puhelimitse <a href="tel:050 411 6514">050 411 6514</a></li>
            <li>Vantaa: puhelimitse ti-to klo 9-16 <a href="tel:0503028449">050 302 8449</a> tai sähköpostilla <a href="kotikirjasto@vantaa.fi">kotikirjasto@vantaa.fi</a>.</li>
        </ul>
       </p>
      </div>
     <div id="joustoasiakkuus" class="content-section">
        <h2>Joustoasiakkuus</h2>
        <p>Helmet-kirjastoissa on käytössä joustoasiakkuus. Se helpottaa kirjastoasiointia silloin, kun ei pääse käymään kirjastossa.</p>
        <p>Kirjastossa käynti voi olla joissakin tilanteissa vaikeaa tai jopa mahdotonta. Esimerkiksi sairaus, vamma tai vaikeus liikkua voivat tehdä kirjastoon 
        pääsystä hankalaa.</p>
        <p>Jos sinulla tai läheiselläsi on jokin este henkilökohtaiselle kirjastokäynnille, voitte hakea joustoasiakkuutta. Joustoasiakkuus 
        tarkoittaa, että asiakas valtuuttaa jonkun muun hoitamaan kirjastoasioinnin puolestaan.</p>
        <p>Joustoasiakkaiden lainoille ei kerry myöhästymismaksuja eivätkä 
        heidän lainansa mene perintään. Laina-ajat ja uusinnat ovat kuitenkin samat kuin muilla asiakkailla.</p>
        <h3>Rekisteröidy joustoasiakkaaksi</h3>
        <p>Joustoasiakkaaksi voi rekisteröityä missä tahansa Helmet-kirjastossa. Rekisteröitymiseen tarvitaan valtuuttajan ja valtuutetun tiedot. 
        Rekisteröitymislomakkeen saa kirjastosta tai Helmet.finna.fi-sivulta 
        <a href="/themes/custom/files/joustoasiakas.pdf" target="_blank" aria-label="Ilmoittautumislomake joustoasiakkaaksi. Lataa PDF-tiedoston laitteellesi.">
        Ilmoittautumislomake joustoasiakkaaksi (PDF)</a>.</p>
      </div>
      <div id="lue-ja-kuuntele" class="content-section">
        <h2>Lue ja kuuntele verkossa</h2>
        <p>Kirjasto tarjoaa tuhansia kirjoja, äänikirjoja ja lehtiä sähköisessä muodossa. E-aineistoista löytyy muun muassa uutta suomen- ja englanninkielistä 
        kirjallisuutta sekä ulkomaisia sanoma- ja aikakauslehtiä. Niiden käyttämiseen tarvitset Helmet-kirjastokortin, verkkoyhteyden sekä tietokoneen, 
        tablettilaitteen tai älypuhelimen.</p>
      </div>
      <div id="musiikkia-verkossa" class="content-section">
        <h2>Musiikkia verkossa</h2>
        <p>Helmet-kirjastot tarjoavat asiakkailleen kolme Naxos-musiikkipalvelua.</p>
        <ul class="list-bullets">
          <li>Naxos Music Library -palvelusta löytyy klassista musiikkia, jonkin verran kansanmusiikkia sekä vanhempaa bluesia ja jazzmusiikkia.</li>
          <li>Jazzille on oma palvelunsa Music Library Jazz, jossa on tuhansien levyjen kokoelma eri aikakausien jazzia.</li>
          <li>Maailmanmusiikki löytyy World Music Library -palvelusta.</li>
        </ul>
        <p>Palveluihin kirjautumiseen tarvitset Helmet-kirjastokortin.</p>
        <p>Medici.tv:n videopalvelussa voit katsella tuhansia huippulaatuisia videoita konserteista, oopperoista ja baleteista sekä dokumentteja ja opetusmateriaalia.</p>
      </div>
   </div>
</div>

