<? $this->headTitle($this->translate('Lånetider och avgifter')); $this->content()->setHeading($this->translate('Lånetider och avgifter'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
    <div id="esim1" class="content-section">
        <h2>Lånetider för biblioteksmaterial</h2>
        <p>Normal lånetid 28 dygn</p>
        <ul class="list-bullets">
            <li>Bestsellermaterial 14 dygn</li>
            <li>CD-skivor med musik 14 dygn</li>
            <li>DVD-och BD-skivor 14 dygn</li>
            <li>Konsolspel 14 dygn</li>
            <li>Brädspel 14 dygn</li>
            <li>Föremål 1–28 dygn (beroende på föremålet)</li>
            <li>E-böcker 1–28 dygn (beroende på tjänst)</li>
        </ul>
        
        <h3>Begränsningar av lån och reservationer</h3>
        <ul class="list-bullets">
            <li>konsolspel 5 lån</li>
            <li>allt övrigt material 100 lån</li>
            <li>sammanlagt 100 reservationer</li>
        </ul>
      </div>
     <div id="gemensamma-avgifter" class="content-section">
        <h2>Gemensamma avgifter för Esbo, Grankulla, Helsingfors och Vanda stadsbibliotek</h2>
        <h3>Förseningsavgifter</h3>
        <ul class="list-bullets">
            <li>Förseningsavgift / material för vuxna / dygn 0,20 €</li>
            <li>Maximal förseningsavgift / lån 6,00 €</li>
            <li>Reservationer som inte hämtats 1,00 € / styck</li>
            <li>Förnyande av försvunnet eller skadat bibliotekskort 3,00 € (vuxna), 2,00 € (personer under 18 år)</li>
        </ul>
        <p>Avgifter för ohämtade reservationer och förseningsavgifter uppbärs inte av personer under 18 år och inte heller av flexkunder.</p>
        
        <h3>Maximibelopp för skuldsaldo</h3>
        <p>Du förlorar din lånerätt om ditt skuldsaldo är 30,00 euro eller större.</p>
        
        <h3>Att ersätta material och betala avgifter</h3>
        <p>Om du tappat bort eller skadat biblioteksmaterial måste du betala den ersättning som stadsbiblioteket i fråga fastställt. Du kan ersätta materialet med ett annat motsvarande verk. 
        Videokassetter, BD-skivor och DVD-skivor kan inte ersättas med motsvarande material, utan bör ersättas enligt de fastställda avgifterna. 
        Biblioteket återbetalar inte de avgifter du betalt även om du senare hittar det borttappade materialet. Ersättningen (gäller inte indrivning) kan betalas i Helmetbibliotek 
        som har en kassa eller via <a href="/">www.helmet.finna.fi</a>. Biblioteket återbetalar inga avgifter.</p>
        
        <h3>Kostnader för borttappat eller skadat material</h3>
        <ul class="list-bullets">
            <li>DVD-skiva, BD-skiva eller konsolspel för vuxna 42 € / st.</li>
            <li>DVD-skiva, BD-skiva eller konsolspel för barn 17 € / st.</li>
            <li>Enskilda tidningsnummer för vuxna 5 € / st.</li>
            <li>Enskilda tidningsnummer för barn 3 € / st.</li>
        </ul>
        <p>För övrigt material uppbärs det pris som uppges i bibliotekssystemets databas, dock minst 17 € för vuxenmaterial och 9 € för material från barnavdelningen.</p>
        
        <h3>Indrivning</h3>
        <p>Esbo, Helsingfors, Grankulla och Vanda stadsbibliotek överför sina fordringar till inkasseringsbyrån Lowell Oy ca 60 dygn räknat från förfallodagen. 
        Indrivningen gäller alla som fyllt 18 år från och med den 1.4.2014. Inkasseringsbyrån fakturerar de olika städernas ersättningar, sina egna indrivningskostnader och en lagenlig 
        förseningsränta.</p>
        
        <h3>Fjärrlåneavgift</h3>
        <p>Fjärrlåneavgifterna varierar i de olika biblioteken. Se <a href="/Content/kaukopalvelu?lng=sv#avgifter">Fjärrlåneavgifter</a>.</p>
      </div>
      <div id="ovriga-avgifter" class="content-section">
        <h2>Övriga avgifter</h2>
        <h3>Kopior och utskrifter</h3>
        <p>Avgifterna för kopior och utskrifter varierar mellan städerna.</p>
        <p>I Esbo är utskrifts- och kopieringsavgiften 0,20 e/sida. I vissa fall är utskrifter avgiftsfria, högst 20 st./uträttande av ärenden.</p>
        <p>Vanda: gratis utskrifter från kunddatorerna 20 st./kund.</p>
        <p>Helsingfors: utskrifter 0,40 € / st (3D-utskrifter 0,70 € / st). Biblioteket återbetalar inte oanvända pengar som lagrats i utskriftstjänsten.</p>
        <p>Grankulla: utskrifter 0,40 € / st.</p>
        <p>Biblioteken har lokaler som kan hyras för olika evenemang.</p>
        <h3>Varor till försäljning</h3>
        <ul class="list-bullets">
            <li>Kassar 1–5 € / st.</li>
            <li>Avskrivna böcker 0,20 € – 35,00 € / st.</li>
        </ul>
        <p>Biblioteken prissätter eventuella övriga varor separat.</p>
      </div>
   </div>
</div>
