<? $this->headTitle($this->translate('Loan periods and fees')); $this->content()->setHeading($this->translate('Loan periods and fees'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="loan-periods" class="content-section">
        <h2>Loan periods</h2>
        <p>General loan period 28 days</p>
        <ul class="list-bullets">
            <li>Bestsellers 14 days</li>
            <li>Music CDs 14 days</li>
            <li>DVDs and Blu-ray discs 14 days</li>
            <li>Console games 14 days</li>
            <li>Board games 14 days</li>
            <li>Objects 1-28 days (depending on the object)</li>
            <li>E-materials 1-28 days (depending on the service)</li>
        </ul>
        
        <h3>Limit on reservations and loans:</h3>
        <ul class="list-bullets">
            <li>Console games 5</li>
            <li>All other materials 100</li>
            <li>100 pending reservations at a time</li>
        </ul>
      </div>
     <div id="joint-fees" class="content-section">
        <h2>Joint fees charged by Espoo, Helsinki, Kauniainen and Vantaa City Libraries</h2>
        <h3>Overdue fees</h3>
        <ul class="list-bullets">
            <li>Overdue fee/day/adult item/loan €0,20</li>
            <li>Maximum overdue fee/loan €6,00</li>
            <li>Uncollected reservations €1,00/reservation</li>
            <li>Replacing a lost or damaged library card €3,00 (adults) / €2,00 (under 18 years of age)</li>
        </ul>
        <p>For materials reserved or borrowed by customers aged under 18 or included in the flexible customer model, the fee for uncollected reservations or overdue fees will not be charged.</p>
        
        <h3>Maximum outstanding debt</h3>
        <p>You will lose your borrowing rights if your outstanding debt is €30,00 or more.</p>
        
        <h3>Compensating for items and paying the fees</h3>
        <p>You will have to compensate for lost or damaged material by paying a price which is charged according to the item’s value registered in the library’s database.
        You can compensate for material with a similar item. You cannot substitute a similar item for a video cassette, BD disc, DVD disc or console game. 
        These must always be compensated for by paying the price mentioned below. The library will not refund the compensation price even if you later find the material you have compensated for.
        You can pay the fees (except for collection) at any Helmet library or online. 
        The library will not refund any fees paid.</p>
        
        <h3>Compensation prices for lost or damaged materials</h3>
        <ul class="list-bullets">
            <li>DVD, Blu-ray disc, console game / adults’ material €42,00 / item</li>
            <li>DVD, Blu-ray disc, console game / children’s material €17,00 / item</li>
            <li>Single magazine / adults’ material €5,00 / copy</li>
            <li>Single magazine / children’s material €3,00 / copy</li>
        </ul>
        <p>Compensation prices for all other materials will be charged according to the item’s value registered in the library’s database. 
        However, a minimum of €17,00 will be charged for items from the adults’ department, and a minimum of €9,00 for children’s material.</p>
        
        <h3>Collection</h3>
        <p>Espoo, Helsinki, Kauniainen and Vantaa City Libraries transfer their outstanding fees to be collected by the collection office Lowell Oy approximately 60 days after the due date. 
        With effect from 1st April 2014 the collection concerns items borrowed by a person 18 years of age or older. The collection office invoices city-specific compensation fees, 
        its own collection fees and the legal penalty interest for the item.</p>
        
        <h3>Interlibrary loan fee</h3>
        <p>Please check the library-specific <a href="/Content/kaukopalvelu?lng=en-gb#fees">Fees for interlibrary loans</a>.</p>
      </div>
      <div id="other-fees" class="content-section">
        <h2>Other fees</h2>
        <h3>Copies and prints</h3>
        <p>Printing costs are city-specific.</p>
        <p>In Espoo, the printing and copying fee is €0.20 per page. In some cases, customers may be offered up to 20 free printouts per visit.</p>
        <p>Vantaa free of charge 20 pages/customer.</p>
        <p>Helsinki: €0,40/page (3D prints €0,70). The library will not return any unused money left in the printing service.</p>
        <p>Kauniainen €0,40/page</p>
        <p>The libraries also have <a href="/Content/tyoskentele-ja-viihdy#space-for-work">rooms which can be rented for events</a>. You can find the rent prices for these rooms in each library's own services.</p>
        <h3>Products for sale</h3>
        <ul class="list-bullets">
            <li>Bags €1–5</li>
            <li>Books withdrawn from the collections €0,20 – €35,00 / item</li>
        </ul>
        <p>Other potential products for sale are priced separately by the library.</p>
      </div>
   </div>
</div>



