<? $this->headTitle($this->translate('Laina-ajat ja maksut')); $this->content()->setHeading($this->translate('Laina-ajat ja maksut'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="laina-ajat" class="content-section">
        <h2>Aineiston laina-ajat</h2>   
        <p>Yleinen laina-aika 28 vrk</p>
        <ul class="list-bullets">
            <li>Bestseller-aineisto 14 vrk</li>
            <li>Musiikki-CD:t 14 vrk</li>
            <li>DVD- ja BD-levyt 14 vrk</li>
            <li>Konsolipelit 14 vrk</li>
            <li>Lautapelit 14 vr</li>
            <li>Esineet 1–28 vrk (esinekohtainen)</li>
            <li>E-aineisto 1–28 vrk (palvelukohtainen)</li>
        </ul>
        
        <h3>Aineiston varaus- ja lainarajoitukset</h2>
        <ul class="list-bullets">
            <li>konsolipelit 5 lainaa</li>
            <li>kaikki muu aineisto 100 lainaa</li>
            <li>yhteensä 100 varausta</li>
        </ul>
      </div>
     <div id="yhteiset-maksut" class="content-section">
        <h2>Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjaston yhteiset maksut</h2>
        <h3>Myöhästymismaksut</h3>
        <ul class="list-bullets">
            <li>Myöhästymismaksu/vrk/aikuisten aineisto/laina 0,20 €</li>
            <li>Myöhästymismaksun enimmäismäärä/laina 6,00 €</li>
            <li>Noutamaton varaus/kpl 1,00 €</li>
            <li>Kadonneen tai vahingoittuneen kirjastokortin uusiminen 3,00 € (aikuiset) 2,00 € (alle 18-vuotiaat)</li>
        </ul>
        <p>Alle 18-vuotiaiden ja joustoasiakkaiden varaamasta ja lainaamasta aineistosta ei mene noutamattoman varauksen maksua eikä myöhästymismaksua.</p>
        
        <h3>Velkasaldon enimmäismäärä</h3>
        <p>Lainausoikeuden menetät, kun velkasaldosi on 30,00 euroa tai enemmän.</p>
        
        <h3>Aineiston korvaaminen ja maksujen maksaminen</h3>
        <p>Sinun on korvattava kadonnut tai vahingoittunut aineisto maksamalla aineiston omistavan kaupunginkirjaston määräämä korvausmaksu. Voit korvata aineiston toisella vastaavalla teoksella. 
        Videokasettia, BD-levyä ja DVD-levyä ei voi korvata vastaavalla teoksella, vaan ne korvataan maksamalla alla olevan listan mukainen korvausmaksu. 
        Kirjasto ei palauta maksamaasi korvausmaksua, vaikka myöhemmin löytäisit korvaamasi aineiston. Maksut (ei koske perintää) voit maksaa Helmet-kirjastoon, 
        jossa on kassa tai verkossa. Kirjasto ei palauta maksamiasi maksuja.</p>
        
        <h3>Kadonneen tai vahingoittuneen aineiston korvaushintoja</h3>
        <ul class="list-bullets">
            <li>Aikuisten aineiston DVD-levy, BD-levy tai konsolipeli 42 € / kpl</li>
            <li>Lasten aineiston DVD-levy, BD-levy tai konsolipeli 17 € / kpl</li>
            <li>Aikuisten aineiston yksittäiset lehtiniteet 5 € / kpl</li>
            <li>Lasten aineiston yksittäiset lehtiniteet 3 € / kpl</li>
        </ul>
        <p>Muusta aineistosta peritään kirjastojärjestelmän tietokannassa oleva teoksen hinta, kuitenkin vähintään 17 € aikuisten aineistosta ja 9 € lasten aineistosta.</p>
        
        <h3>Perintä</h3>
        <p>Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjastot siirtävät saatavansa perintätoimisto Lowell Oy:n perittäväksi noin 60 vuorokauden kuluttua eräpäivästä. 
        Perintä koskee 18 vuotta täyttäneitä 1.4.2014 alkaen. Perintätoimisto laskuttaa kaupunkikohtaisesti aineiston korvausmaksun, omat perintäkulunsa ja lainmukaisen viivästyskoron.</p>
        
        <h3>Kaukopalvelumaksu</h3>
        <p>Katso kirjastokohtaiset kaukopalvelumaksut sivulta <a href="/Content/kaukopalvelu#maksut">Kaukopalvelumaksut</a>.</p>
      </div>
      <div id="muut-maksut" class="content-section">
        <h2>Muut maksut</h2>
        <h3>Kopiot ja tulosteet</h3>
        <p>Tulostusmaksut ovat kaupunkikohtaisia.</p>
        <p>Espoossa tuloste- ja kopiomaksu on 0,20 € / sivu. Joissakin tapauksissa voi saada maksuttomia tulosteita enintään 20 kpl / asiointikerta.</p>
        <p>Vantaalla tulostaminen asiakaskoneilta on maksutonta 20 kpl / asiakas.</p>
        <p>Helsingissä tulosteet 0,40 € / kpl, 3D-tulosteet 0,70 € / kpl. Kirjasto ei palauta tulostuspalveluun tallennettua käyttämättä jäänyttä rahaa.</p>
        <p>Kauniaisissa tulosteet 0,40 € / kpl.</p>
        <p>Kirjastoissa on myös <a href="/Content/tyoskentele-ja-viihdy#tyotilat">vuokrattavia tiloja</a> tilaisuuksien järjestämistä varten. Näiden tilojen vuokrat löydät kunkin kirjaston omista palveluista.</p>
        <h3>Myytävät tuotteet</h3>
        <ul class="list-bullets">
            <li>Kassit 1–5 € / kpl</li>
            <li>Poistokirjat 0,20 € – 35,00 € / kpl</li>
        </ul>
        <p>Kirjastot hinnoittelevat muut mahdolliset myytävät tuotteet erikseen.</p>
      </div>
   </div>
</div>
