<h1>Lainattavat esineet</h1>
<p>Kirjastosta voit lainata myös esineitä ja laitteita, joita et tarvitse joka päivä. 
Voit lainata esimerkiksi porakoneita, tennismailoja, luistimia, ompelukoneita, kuulokkeita, suksia, sykemittareita tai soittimia.</p>
<p>Kaupunkiympäristössä asuva ihminen joutuu elämänsä aikana tekemisiin arviolta 20 000–30 000 esineen kanssa. 
Vältä turhien esineiden tulvaa ja lainaa kirjastosta mahdollisimman monta arjen työvälinettä ja esinettä. Helmet-kirjasto tarjoaa reilun valikoiman lainattavia esineitä. 
Jokaisen esineen löydät Helmet-hausta. Valikoima vaihtelee kirjastoittain.</p>
<p>Lainattavat esineet täytyy palauttaa siihen kirjastoon, josta ne on lainattu ja jonka kokoelmiin ne kuuluvat. Esineitä ei voi varata.</p>
<p>Ajantaiset tiedot Helmet-kirjaston kokoelmissa olevista esineistä löydät Helmet-hausta:</p><p>
<strong><a href="http://haku.helmet.fi/iii/encore/search/C__S%28*%29%20f%3Aq__Orightresult__U?lang=fin&amp;suite=cobalt">Esineet Helmet-haussa</a></strong></p>