<? $this->headTitle($this->translate('Hitta information')); $this->content()->setHeading($this->translate('Hitta information'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Bibliotekets personal visar dig gärna hur du söker information och hur du använder olika apparater. 
        Du kan få personlig undervisning, men det finns också stöd att få via nätet.</p>
      </div>
     <div id="helmet-sok" class="content-section">
        <h2>Vad ska jag skriva i Helmets sökruta?</h2>
        <p>Biblioteken använder ämnesord för att beskriva innehållet i olika verk. Ämnesord är särskilt utvalda ord, så för att göra en lyckad sökning måste du använda rätta ord. 
        T.ex. ordet reseguide är inget ämnesord, utan du måste använda resehandböcker. Om du skriver orden reseguide och Lappland får du inga resultat i Helmet, 
        utan du måste söka på resehandböcker Lappland.”</p>
        <p>Material på svenska söks med svenska ämnesord, medan material på andra språk söks med finska ämnesord.</p>
        <p>Du får hjälp att hitta de rätta ämnesorden i bibliotekens ordlistor, s.k. tesaurusar, på nätet:</p>
        <ul class="list-bullets">
          <li><a href="https://finto.fi/yso/sv/" target="_blank" aria-label="ALLFO. Länken öppnas i ett nytt fönster.">ALLFO</a>
          – allmän finländsk ontologi</li>
          <li><a href="https://finto.fi/kauno/sv/" target="_blank" aria-label="KAUNO. Länken öppnas i ett nytt fönster.">KAUNO</a>
          – ontologi för fiktivt material</li>
        </ul>
      </div>
      <div id="hylla" class="content-section">
        <h2>I vilken hylla ska jag leta?</h2>
        <p>Biblioteken använder s.k. klassifikationssystem som visar hur böckerna och övrigt material har ordnats i hyllorna. 
        Esbo, Grankulla och Vanda bibliotek använder Kab, de allmänna bibliotekens klassifikationssystem, medan Helsingfors stadsbibliotek har ett eget klassifikationssystem.</p>
        <ul class="list-bullets">
          <li><a href="https://finto.fi/ykl/sv/" target="_blank" aria-label="WebbKab. Länken öppnas i ett nytt fönster.">WebbKab</a>
          – de allmänna bibliotekets klassifikationssystem i webbversion</li>
          <li><a href="https://finto.fi/hklj/fi/" target="_blank" aria-label="WebbHSKS. Länken öppnas i ett nytt fönster.">WebbHSKS</a>
          – Helsingfors stadsbiblioteks klassifikationssystems webbversion.</li>
        </ul>
        <p>Också skönlitteraturen kan ordnas enligt tema, så att t.ex. deckare, fantasyböcker och romantik har egna kategorier. Vid Helmetsökning syns temat efter klassbeteckningen.</p>
      </div>
      <div id="fraga-bibliotekarien" class="content-section">
        <h2>Fråga bibliotekarien</h2>
        <p>Tjänsten <a href="http://beta.biblioteken.fi/fraga" target="_blank" 
        aria-label="Fråga bibliotekarien. Länken öppnas i ett nytt fönster.">Fråga bibliotekarien</a> startade år 1999. Idag besvarar personalen på ett tiotal allmänna bibliotek, 
        specialbibliotek och informationstjänster runt om i Finland dina frågor. Tjänsten fungerar på finska, svenska och engelska.</p>
      </div>
      <div id="esim2" class="content-section">
        <h2>Ta hjälp av länklistor</h2><p>
        <a href="https://www.makupalat.fi/sv" target="_blank" 
        aria-label="Makupalat vid Biblioteken.fi. Länken öppnas i ett nytt fönster.">Makupalat vid Biblioteken.fi</a>
        <p>En länklista som de allmänna biblioteken har skapat tillsammans. Länkarna är arrangerade enligt Kab, de allmänna bibliotekens klassifikationssystem.</p>
      </div>
   </div>
</div>
