<? $this->headTitle($this->translate('Löydä tietoa')); $this->content()->setHeading($this->translate('Löydä tietoa'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Kirjastossa henkilökunta opastaa mielellään tiedon etsinnässä ja laitteiden käytössä. Henkilökohtaisen opastuksen lisäksi tarjolla on tukea 
        tiedonhakuun myös netissä.</p>
      </div>
     <div id="helmet-haku" class="content-section">
        <h2>Mitä kirjoitan Helmet-hakulaatikkoon?</h2>
        <p>Kirjastot käyttävät asiasanoja teosten sisällönkuvailuun. Kaikki sanat eivät ole asiasanoja, joten onnistuneessa tiedonhaussa korostuu oikeiden hakusanojen käyttö. 
        Esimerkiksi matkaopas ei ole asiasana, vaan oikea hakusana on matkaoppaat.</p>
        <p>Apua oikean hakusanan löytämiseen saat kirjastojen verkkosanastoista.</p>
        <ul class="list-bullets">
          <li><a href="https://finto.fi/yso/fi/" target="_blank" aria-label="YSO. Linkki aukeaa uudessa ikkunassa.">YSO</a>
          - yleinen suomalainen ontologia</li>
          <li><a href="https://finto.fi/kauno/fi/" target="_blank" aria-label="KAUNO. Linkki aukeaa uudessa ikkunassa.">KAUNO</a>
          - fiktiivisen aineiston ontologia</li>
        </ul>
      </div>
      <div id="hyllyt" class="content-section">
        <h2>Mistä hyllystä mitäkin löytyy?</h2>
        <p>Kirjastoissa on käytössä luokitusjärjestelmä, jonka mukaan kirjat ja muu aineisto on järjestetty hyllyihin. 
        Espoon, Vantaan ja Kauniaisten kirjastoissa käytössä on Yleisten kirjastojen luokitusjärjestelmä (YKL). 
        Helsingin kaupunginkirjastossa on käytössä Helsingin kaupunginkirjaston luokitusjärjestelmä (HKLJ).</p>
        <ul>
          <li><a href="https://finto.fi/ykl/fi/" target="_blank" aria-label="Verkko-YKL. Linkki aukeaa uudessa ikkunassa.">Verkko-YKL </a>
          – Yleisten kirjastojen luokitusjärjestelmä</li>
          <li><a href="https://finto.fi/hklj/fi/" target="_blank" aria-label="Verkko-HKLJ. Linkki aukeaa uudessa ikkunassa.">Verkko-HKLJ</a>
          – Helsingin kaupunginkirjaston luokitusjärjestelmä</li>
        </ul>
        <p>Myös kaunokirjallisuutta järjestetään usein aihepiireittäin, siten että esim. dekkarit, fantasia ja romantiikka löytyvät kirjastossa omasta ryhmästään. 
        Kyseinen aihepiiri näkyy silloin Helmet-haussa kirjan tiedoissa luokkamerkinnän jälkeen.</p>
      </div>
     <div id="kysy-kirjastonhoitajalta" class="content-section">
        <h2>Kysy kirjastonhoitajalta</h2>
        <p><a href="https://www.kirjastot.fi/kysy?open-form=true" target="_blank" 
        aria-label="Kysy kirjastonhoitajalta. Linkki aukeaa uudessa ikkunassa.">Kysy kirjastonhoitajalta</a>-palvelu perustettiin vuonna 1999. 
        Kymmenet kunnankirjastot, erikoiskirjastot ja tietopalvelut ympäri Suomen vastaavat kysymyksiisi.</p>
      </div>
      <div id="linkkilistat" class="content-section">
        <h2>Lisäapua linkkilistoista</h2>
        <p><a href="http://www.makupalat.fi/" target="_blank" aria-label="Makupalat. Linkki aukeaa uudessa ikkunassa.">
        Makupaloissa</a> on yli 27 000 kirjastoammattilaisten valikoimaa ja kuvailemaa linkkiä laadukkaisiin 
        verkkosisältöihin eri aihealueilta.</p>
      </div>
   </div>
</div>