<? $this->headTitle($this->translate('How to find things')); $this->content()->setHeading($this->translate('How to find things'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>The library staff are happy to assist you in information searches or using equipment. In addition to personal assistance, 
        there is also online support for information searches available.</p>
      </div>
     <div id="helmet-search" class="content-section">
        <h2>What do I write in the Helmet search box?</h2>
        <p>Libraries use index words to describe the contents of works. Not all words are index words, so you need to use the correct index words to find information successfully. 
        For example, 'travel guide' is not an index word – the correct one is 'travel guides'. 
        If you write 'travel guide Lapland', you get a few search results, but the correct way of finding the books is to write 'travel guides Lapland'.</p>
        <p>Help for finding the correct index term is available in the library online glossaries.</p>
        <ul class="list-bullets">
          <li><a href="https://finto.fi/yso/en/" target="_blank" aria-label="YSO. The link opens in a new window.">YSO</a>
          - General Finnish ontology</li>
          <li><a href="https://finto.fi/kauno/en/" target="_blank" aria-label="KAUNO. The link opens in a new window.">KAUNO</a>
          - ontology for fiction</li>
        </ul>
      </div>
      <div id="esim2" class="content-section">
        <h2>Shelves and what they hold</h2>
        <p>Libraries use a classification system to organise books and other material on the shelves. 
        The libraries of Espoo, Vantaa and Kauniainen use the Finnish Public Libraries Classification System (PLC). 
        Helsinki City Library uses the Helsinki City Library Classification System (HCLCS).</p>
        <ul class="list-bullets">
          <li><a href="https://finto.fi/ykl/en/" target="_blank" aria-label="WebPLC. The link opens in a new window.">WebPLC</a>
          – Finnish Public Libraries Classification System</li>
          <li><a href="https://finto.fi/hklj/fi/" target="_blank" aria-label="WebHCLCS. The link opens in a new window.">WebHCLCS</a>
          – Helsinki City Library Classification System</li>
        </ul>
        <p>Fiction is also often classified by subject matter, so that detective stories, fantasy and romance, for example, are in their own group in the library. 
        In a Helmet search, the subject matter of an item is displayed in the item information, after the classification note.</p>
      </div>
      <div id="esim2" class="content-section">
        <h2>Ask a Librarian</h2>
        <p><a href="http://www.libraries.fi/en-GB/ask_librarian/" target="_blank" 
        aria-label="Ask a Librarian. The link opens in a new window.">Ask a Librarian</a> service was established 1999. Today, scores of municipal and special libraries and information services around Finland use the service to 
        answer your questions promptly. You can ask questions in Finnish, Swedish or English.</p>
      </div>
   </div>
</div>
