<? $this->headTitle($this->translate('Lukuvalmentaja Junior')); $this->content()->setHeading($this->translate('Lukuvalmentaja Junior'));?>
<p>Haluaisitko innostua lukemisesta? Onko sinun vaikea löytää kiinnostavia kirjoja? Tai oletko yksinkertaisesti lukenut jo ihan kaiken ja kaipaat uusia tarinoita?</p>
<p>Niin tai näin, olet tervetullut Lukuvalmentaja Juniorin vastaanotolle! Lukuvalmentaja tekee parhaansa, jotta juuri sinulle sopivat kirjat löytyisivät. Palvelu on tarkoitettu 
kaikille lasten- ja nuortenkirjallisuudesta kiinnostuneille – lapsille, nuorille, vanhemmille ja opettajille. Palvelu on ilmainen.</p>
<p>Voit valita itsellesi parhaiten sopivan valmennuksen:</p>
<p><strong>Sähköpostivalmennus</strong>
<br>
Valmentaja kokoaa toiveidesi pohjalta kirjalistan ja lähettää sen sinulle sähköpostilla. Voit valita 5, 10 tai 15 kirjan valmennuksen.</p>
<p><strong>Kirjakassi</strong>
<br>
Valmentaja kokoaa toiveidesi pohjalta kirjakassin, jonka voit lainata mukaasi kirjastosta. Palvelu on saatavilla Itäkeskuksen, Jätkäsaaren, Kallion, Kannelmäen, Kontulan, 
Lauttasaaren, Malmin, Oodin, Oulunkylän, Paloheinän, Pasilan, Puistolan, Pukinmäen, Rikhardinkadun,Tapanilan, Töölön, Viikin ja Vuosaaren kirjastoissa. 
Voit valita 5 tai 10 kirjan kassin.<br>

<h2>Kiinnostuitko?</h2>
<p>Palvelu on ensisijaisesti suunnattu vapaa-ajan lukuharrastuksen tukemiseen. Jotta voimme tarjota kaikille kiinnostuneille valmennuksen, voi yksi henkilö saada vuoden aikana 
korkeintaan kaksi valmennusta. Koulujen ja päiväkotien osalta valmennamme opettajia ja yksittäisiä oppilaita. Mikäli etsit lukusuosituksia koko ryhmällesi, otathan ensisijaisesti 
yhteyttä omaan lähikirjastoosi.</p>
<p>Voit tarkastaa rekisteriselosteesta (alla), millä tavalla käsittelemme palvelussa kerättyjä tietoja.</p>
<p>
<p>Lukuvalmentaja Junior löytyy myös Instagramista: @lukuvalmentajajunior</p>
<h2>Kirjaston Lukuvalmentaja junior –palvelun rekisteri</h2>
<p>Rekisteriseloste<br>
EU:n yleinen tietosuoja-asetus (2016/679)<br>
23.9.2020</p>

<h3>1. Rekisterinpitäjä</h3>
<p>Kulttuuri- ja vapaa-aikalautakunta on 27.3.2018 § 71 delegoinut rekisterinpitäjän tehtävät kirjastopalvelujen johtajalle.</p>

<h3>2. Rekisterin vastuuhenkilö</h3>
<p><strong>Tehtävänimike</strong><br>
Alueellisten kirjastopalvelujen johtaja</p>

<h3>3. Rekisterin yhteyshenkilö</h3>
<p><strong>Tehtävänimike</strong><br>
Keskisen alueen pedagoginen informaatikko<br>
<strong>Yhteystiedot</strong><br>
Helsingin kaupunki, Kirjaamo, PL 10 (Pohjoisesplanadi 11-13), 00099 Helsingin kaupunki</p>

<h3>4. Henkilötietojen käsittelyn tarkoitukset ja käsittelyn oikeusperuste</h3>
<p><strong>Käsittelyn tarkoitukset</strong><br>
Rekisterin tarkoituksena on kirjaston Lukuvalmentaja junior –palvelun mahdollistaminen.
Rekisteriin kerättyjen henkilötietojen avulla lukuvalmentajat voivat olla yhteydessä
valmennuksen tilanneisiin asiakkaisiin tai heidän huoltajiinsa ja toteuttaa
lukuvalmennuksen asiakkaan henkilökohtaisten lukumieltymysten perusteella.</p>

<p><strong>Käsittelyn oikeusperuste</strong><br>
Oikeusperusta on EU:n yleisen tietosuoja-asetuksen artikla 6:n kohta 1 a: Rekisteröity on
antanut suostumuksensa henkilötietojensa käsittelyyn yhtä tai useampaa erityistä
tarkoitusta varten.</p>
<p><strong>Keskeinen lainsäädäntö</strong></p>
<ul class="list-bullets">
    <li>EU:n yleinen tietosuoja-asetus (679/2016)</li>
    <li>Tietosuojalaki (1050/2018)</li>
    <li>Kirjastolaki (1492/2016)</li>
</ul>

<h3>5. Rekisterin tietosisältö</h3>
<p>Rekisteröity: etunimi ja sähköpostiosoite.<br>
Lukuvalmennuksen onnistumisen takaamiseksi kerätään tietoa myös lukumieltymyksistä ja
siitä minkä ikäisille suunnattuja kirjoja asiakas haluaa. Asiakas voi myös halutessaan
kuvailla vapaasti erityistoiveitaan tai esimerkiksi lukemiseen liittyviä rajoitteita.
Nuorimpien rekisteröityjen kohdalla sähköpostiosoite on usein huoltajan.</p>

<h3>6. Henkilötietojen säännönmukaiset luovutukset</h3>
<p>Ei tietojenluovutuksia, ei myöskään EU- tai ETA-maiden ulkopuolelle. Luovutukset
tilastointia varten anonyymisti.</p>

<h3>7. Tietojen säilytysajat</h3>
<p>Henkilötiedot säilytetään kalenterivuoden loppuun asti sen jälkeen, kun lukuvalmennus on tehty.</p>

<h3>8. Henkilötietojen tietolähteet</h3>
<p>Henkilötiedot saadaan rekisteröidyltä itseltään tai tämän huoltajalta.</p>
