<? $this->headTitle($this->translate('Lukudiplomit')); $this->content()->setHeading($this->translate('Lukudiplomit'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="lukudiplomi" class="content-section">
        <h2>Mikä ihmeen lukudiplomi?</h2>
        <p>Tuntuuko sinusta, että lukuharrastukseen olisi mukava saada kannustusta, jonkinlainen pieni porkkana? Etkö aina keksi, mitä lukisit? 
        Oletko valmis tutustumaan monenlaisiin kirjoihin? Jos näin on, kirjasto suosittelee sinulle lukudiplomin suorittamista.</p>
        <p>Lukudiplomin suorittamisen ideana on lisätä lukuintoa ja tutustuttaa kirjafani mahdollisimman erilaisiin hyviin kirjoihin. Kirjastojen 
        lukudiplomilistoissa on valittavina toisaalta paljon mukavaa uutta luettavaa, toisaalta lasten- ja nuortenkirjallisuuden nykyklassikoita. 
        Eri-ikäisille lukijoille on olemassa omat diplomilistat, joista löytyy juuri itselle sopivaa luettavaa. Kaikki diplomin suorittaneet saavat 
        suorituksestaan kunniakirjan, Diplomin.</p><p>Vaikka et haluaisi varsinaisesti suorittaa lukudiplomia, saat lukudiplomilistoilta tietysti hyviä 
        lukuvinkkejä.</p>
      </div>
     <div id="lukudiplomin-suorittaminen" class="content-section">
        <h2>Lukudiplomin suorittaminen</h2>
        <p>Voit valita kahdesta eri lukudiplomista. Pääkaupunkiseudulla on käytössä Vantaan kaupunginkirjaston kehittämä
        <a href="http://lukudiplomi.fi" target="_blank" aria-label="Helmet-lukudiplomi. Linkki aukeaa uudessa ikkunassa.">Helmet-lukudiplomi</a>
        Helmet-lukudiplomi sekä Espoossa kehitetty <a href="https://kunnarilukudiplomi.fi/" target="_blank"
        aria-label="Kunnari-lukudiplomi. Linkki aukeaa uudessa ikkunassa.">Kunnari-lukudiplomi</a>. Lukudiplomin voi suorittaa joko itsenäisesti tai 
        yhdessä koulun kanssa. Lukudiplomeja suoritetaan pääsääntöisesti koulussa.</p>
        <p><a href="http://lukudiplomi.fi" target="_blank" aria-label="lukudiplomi.fi. Linkki aukeaa uudessa ikkunassa.">Lukudiplomi.fi</a> 
        -sivulla on vuosittain päivittyvien kirjalistojen lisäksi ohjeita diplomin suorittajille ja opettajille. Kirjalistoja löytyy suomen, 
        ruotsin, englannin ja venäjän kielillä, ja niissä on selkeästi huomioitu erilaiset lukijat. Lukemisen lisäksi lukudiplomin suorittaja tekee 
        kirjoista erilaisia tehtäviä, jotka suoritetaan opettajan johdolla koulussa tai - jos diplomi suoritetaan poikkeuksellisesti itsenäisesti 
        - yhteistyössä oman kirjaston kanssa.</p>
        <p>Kunnari-lukudiplomi on valtakunnallinen lukudiplomisivusto eli käytössä ympäri Suomen. Kunnarin diplomilistojen päivittämiseen ja 
        ylläpitämiseen osallistuu Espoossa opettajien lisäksi joukko kirjastolaisia. Lukemisen lisäksi Kunnari-lukudiplomin suorittaja tekee 
        kirjoista erilaisia tehtäviä.</p>
        <p>Kunnari-lukudiplomikirjojen saatavuustiedot Helmet-kirjastoista <a href="https://www.kunnarilistat.fi/index.php" target="_blank"
        aria-label="Kunnarilistat.fi. Linkki aukeaa uudessa ikkunassa.">Kunnarilistat.fi</a></p>
        <p>Lisää tietoa lukudiplomeista saat myös kaikista HelMet-kirjaston toimipisteistä.</p>
        <p><a href="http://kirjasto.one/lohkandiploma" target="_blank"
        aria-label="Saamenkielinen lukudiplomi. Linkki aukeaa uudessa ikkunassa.">Saamenkielinen lukudiplomi</a></p>
      </div>
      <div id="satudiplomi" class="content-section">
        <h2>Satudiplomista lukuvinkkejä perheille ja ryhmille</h2>
        <p>Helmet-kirjastot haluavat kannustaa perheitä ja lapsiryhmiä lukemaan yhdessä. Satudiplomi on tarkoitettu 0-6-vuotiaille lapsille, 
        perheille ja varhaiskasvatuksessa käytettäväksi. Kirjalistasta löydät monipuolisia ja viihdyttäviä kirjavinkkejä yhteisiin lukuhetkiin 
        ja kirjat on jaoteltu aihealueisiin. Listalta löydät myös suuntaa antavat ikäsuositukset eri kirjoille. Satudiplomin suorittajat voivat 
        täyttää itse tulostettavaa Lukulokki-pohjaa kirjojen muistiin merkitsemiseen ja kymmenen (10) kirjaa lukenut saa noutaa kirjastosta 
        diplomin sekä Lukulokilleen kruunun.</p>
        <ul class="list-bullets">
            <li><a href="http://kirjasto.one/lukudiplomi/index.php?dipl=15" target="_blank" 
            aria-label="Satudiplomi. Linkki aukeaa uudessa ikkunassa.">Satudiplomi</a></li>
            <li><a href="http://kirjasto.one/lukudiplomi/index.php?dipl=57" target="_blank"
            aria-label="Sagodiplom. Linkki aukeaa uudessa ikkunassa.">Sagodiplom</a></li>
            <li><a href="http://kirjasto.one/lukudiplomi/index.php?dipl=68" target="_blank"
            aria-label="Venäjänkielinen Satudiplomi. Linkki aukeaa uudessa ikkunassa.">Venäjänkielinen Satudiplomi</a></li>
            <li><a href="http://kirjasto.one/lukudiplomi/index.php?dipl=72" target="_blank"
            aria-label="Story Diploma. Linkki aukeaa uudessa ikkunassa.">Story Diploma</a></li>
        </ul>
      </div>
      <div id="yhteystiedot" class="content-section">
        <h2>Kysy diplomeista</h2>
        <p>Onko sinulla kysyttävää lukudiplomeista? Ota yhteyttä meihin sähköpostilla:</p>
        <p>Helsinki: Helsingin kaupunginkirjasto, <a href="mailto:helsinki@lukudiplomi.fi">helsinki@lukudiplomi.fi</a> </p>
        <p>Espoo: Espoon kaupunginkirjasto, <a href="mailto:espoo@lukudiplomi.fi">espoo@lukudiplomi.fi</a></p>
        <p>Vantaa: Vantaan kaupunginkirjasto, <a href="mailto:vantaa@lukudiplomi.fi">vantaa@lukudiplomi.fi</a></p>
        <p>Kauniainen: Kauniaisten kirjasto, <a href="mailto:kauniainen@lukudiplomi.fi">kauniainen@lukudiplomi.fi</a></p>
      </div>
   </div>
</div>
