<? $this->headTitle($this->translate('Läs- och Sagodiplom')); $this->content()->setHeading($this->translate('Läs- och Sagodiplom'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <h2>Vad är Läsdiplomet för något?</h2>
        <p>Är du i behov av läsinspiration? Saknar du ibland lite uppmuntran och tycker att du behöver sporras lite? Känner du att du önskar tips 
        på bra böcker och är du i så fall redo att smaka på olika sorters böcker? I så fall är Helmet-bibliotekens 
        <a href="http://lasdiplom.fi" target="_blank" aria-label="läsdiplom något för dig. Länken öppnas i ett nytt fönster.">
        läsdiplom</a> något för dig.</p>
        <p>Idén med läsdiplomet är att öka läslusten hos bokentusiasten och erbjuda bra böcker i olika genrer och med olika teman. På boklistorna 
        finns såväl nyutkommen barn- och ungdomslitteratur som gamla favoriter och klassiker. Boklistorna är uppdelade enligt läsarnas ålder och 
        är totalt fyra till antalet. De riktar sig till barn i åk 1–2, 3–4, 5–6 och 7–9. Alla som avlägger diplomet får ett hederspris dvs ett diplom.</p>
        <p>Även om du inte vill avlägga läsdiplomet enligt konstens alla regler lönar det sig att ta en titt på boklistorna för du hittar en massa 
        bra boktips där och listorna uppdateras årligen.</p>
        <h3>Så här går det till:</h3>
        <p>Välj det diplom som riktar sig till din årskurs. Läs igenom alla boklistorna. Bestäm dig för vilka tio böcker du önskar läsa och välj 
        också några extra alternativ ifall de böcker du helst vill läsa är utlånade på biblioteket eller svåra att få tag på. Kontrollera också 
        ifall det finns begränsningar i ditt diplom (om en bok måste höra till en viss kategori, till exempel ”På vers”). Sen är det bara att sätta 
        i gång och läsa. Skriv upp vilka böcker du har läst på <a href="https://kirjasto.one/lukudiplomi/img/pdf/1ru.pdf" target="_blank">den här listan (PDF)</a>. 
        När listan är klar hämtar du den till biblioteket och där ser vi till att du får ditt diplom.</p>
        <p>Diplomet kan du avlägga på egen hand, i skolan eller med hjälp av en förälder eller en bibliotekarie. Många skolor använder läsdiplomen i 
        undervisningen, men också om din skola inte gör det kan du be din lärare om hjälp att avlägga diplomet. Det lönar sig att komma överens om hur 
        du ska redogöra för de böcker som du läst. Ska du till exempel skriva en läsdagbok eller berätta om böckerna på något sätt?</p>
        <p>Du kan läsa böckerna under vilken tid på året som helst, men i skolsammanhang delas diplomen ut på vårfesten.</p>
        <p>Om du önskar mer information om läsdiplomen får du veta mer vid varje enskilt Helmet-bibliotek.</p>
      </div>
     <div id="sagodiplomet" class="content-section">
        <h2>Vad är Sagodiplomet för något?</h2>
        <p>Är du och ditt barn eller din grupp i behov av läsinspiration? Vill ni ha tips på bra böcker att läsa högt och tillsammans? Är ni redo att smaka på olika sorters böcker? I så fall
        är <a href="http://kirjasto.one/lukudiplomi/index.php?dipl=57" target="_blank" aria-label="Helmet-bibliotekens sagodiplom. Länken öppnas i ett nytt fönster.">HelMet-bibliotekens 
        sagodiplom</a> något för er.</p>
        <p>Med sagodiplomet vill vi uppmuntra och öka läslusten hos barn i daghemsåldern eller åldern 0–6 år samt deras pedagoger och familjer. Framför allt vill vi betona vikten av 
        att läsa tillsammans med barnen som ännu inte lärt sig läsa själva eller är nybörjare ännu. Idén är att plocka fram bra böcker i olika genrer och med olika teman, både 
        nyutkomna barnböcker och gamla favoriter och klassiker. Diplomet är indelat i kategorierna: Favoriter och klassiker, Sagor, Högläsningsböcker, Bilderböcker och Dikter, rim och ramsor.</p>
        <p>De familjer och grupper som avlägger sagodiplomet kan själva skriva ut Läsmåsens botten och använda det till att anteckna de lästa böckerna på. Då tio (10) böcker är lästa kan du 
        avhämta ett sagodiplom från biblioteket samt en krona till din Läsmås. Sagodiplomet kan avläggas som ett gemensamt gruppdiplom eller för en enskild läsare. I så fall får 
        läsaren ett diplom med sitt eget namn. Även om du inte vill avlägga diplomet enligt konstens alla regler lönar det sig att ta en titt på boklistorna för där hittar du en massa 
        lockande lästips.</p>
        <h3>Så här går det till:</h3>
        <p>Klicka in dig på sidan <a href="http://kirjasto.one/lukudiplomi/index.php" target="_blank" aria-label="läsdiplom.fi. Länken öppnas i ett nytt fönster.">läsdiplom.fi</a> 
        och välj <a href="http://kirjasto.one/lukudiplomi/index.php?dipl=57" target="_blank" aria-label="Sagodiplom för 
        familjer och grupper. Länken öppnas i ett nytt fönster.">Sagodiplom för familjer och grupper</a>. Läs igenom alla boklistorna. Bestäm dig för vilka tio böcker du önskar läsa 
        och välj också några extra alternativ ifall de böcker du helst vill läsa är utlånade på biblioteket eller är svåra att få tag på. Sen är det bara att sätta i gång och läsa. Skriv upp 
        vilka böcker du har läst på <a href="https://kirjasto.one/lukudiplomi/img/pdf/KORJATTU_lukulokki_helmet_sve.pdf" target="_blank">Läsmåsen (PDF)</a> (eller 
        <a href="https://kirjasto.one/lukudiplomi/img/pdf/1ru.pdf" target="_blank">den här listan (PDF)</a>). När listan är klar hämtar du den till biblioteket som ser till att du får ditt 
        diplom samt ger en krona till din Läsmås.</p>
        <p>Du kan läsa böckerna under vilken tid på året som helst och diplomet får du med dig när du hämtar listan till biblioteket.</p>
      </div>
      <div id="ta-kontakt" class="content-section">
        <h2>Ta kontakt</h2>
        <p>Är det något du vill fråga oss om? Skicka i så fall ett mejl till någon av oss:</p>
        <p>Helsingfors: <a href="mailto:helsingfors@läsdiplom.fi">helsingfors@läsdiplom.fi</a><br>
        Esbo: <a href="mailto:esbo@läsdiplom.fi">esbo@läsdiplom.fi</a><br>
        Grankulla: <a href="mailto:grankulla@läsdiplom.fi">grankulla@läsdiplom.fi</a><br>
        Vanda: <a href="mailto:vanda@läsdiplom.fi">vanda@läsdiplom.fi</a></p>
      </div>
   </div>
</div>



