<? $this->headTitle($this->translate('Läsinspiratör Junior')); $this->content()->setHeading($this->translate('Läsinspiratör Junior'));?>
<p>Vill du få fart på din läsning? Har du svårt att hitta bra böcker? Känns det som att du läst allt och inte kan hitta något nytt?</p>
<p>Kanske kan vår Läsinspiratör Junior hjälpa dig? Läsinspiratören gör sitt bästa för att hitta böckerna som passar dig. Tjänsten är tänkt för alla med intresse för barn- och ungdomsböcker:
barn, ungdomar, föräldrar och lärare. Tjänsten är naturligtvis gratis.</p>
<p>Du kan få läsinspiration på två olika sätt:</p>
<strong>Boklista</strong>
<p>Läsinspiratören gör en lista efter dina önskemål och skickar den via epost.</p>
<strong>Bokpåse</strong>
<p>Läsinpiratören samlar böcker till dig efter dina önskemål och packar dem i en påse du kan hämta från biblioteket. Tjänsten är tillgänglig på följande bibliotek: 
Berghäll, Bocksbacka, Busholmen, Böle, Drumsö, Gamlas, Gårdsbacka, Malm, Mosabacka, Nordsjö, Ode, Parkstad, Richardsgatan, Svedängen, Tölö, Vik, Åggelby och Östra centrum.</p>

<h2>Blev du intresserad?</h2>
<p>Tjänsten är främst avsedd för att stödja barn som läser på sin fritid. För att vi ska kunna ge givande läsinspiration till så många som möjligt kan varje enskild person få max två 
läsinspirationer per år. För skolor och daghem erbjuder vi läsinspiration för pedagoger och enskilda elever. Ta i första hand kontakt med ditt närbibliotek om du önskar boktips för en 
hel grupp.</p>
<p>I registerbeskrivningen kan du läsa om hur vi använder oss av de uppgifter vi samlar in.</p>

<h2 id="register">Register för bibliotekets tjänst Läsinspiratör Junior</h2>
<p>Registerbeskrivning<br>
EU:s allmänna dataskyddsförordning (2016/679)<br>
23.9.2020</p>

<h3>1. Personuppgiftsansvarig</h3>
<p>Kultur- och fritidsnämnden har per den 27.3.2018 § 71 delegerat den
personuppgiftsansvariges uppgifter till direktören för bibliotekstjänster.</p>

<h3>2. Registeransvarig</h3>
<p><strong>Befattning</strong><br>
Direktören för regionala bibliotekstjänster</p>

<h3>3. Registrets kontaktperson</h3>
<p><strong>Befattning</strong><br>
Pedagogisk informatiker i det mellersta området</p>

<p><strong>Kontaktuppgifter</strong><br>
Helsingfors stad, Registratorskontoret, PB 10 (Norra esplanaden 11–13), 00099
Helsingfors stad</p>

<h3>4. Ändamålen med och den rättsliga grunden för behandlingen av personuppgifter</h3>
<p><strong>Ändamålen med behandlingen</strong><br>
Syftet med registret är att tillhandahålla bibliotekets tjänst Läsinspiratör Junior. Med hjälp
av personuppgifterna som samlas i registret kan läsinspiratörerna ta kontakt med de
kunder som har beställt handledning eller deras vårdnadshavare och genomföra
handledningen baserat på kundens individuella läsintressen.</p>

<p><strong>Den rättsliga grunden för behandlingen</strong><br>
Den rättsliga grunden är artikel 6.1 a i EU:s allmänna dataskyddsförordning: Den
registrerade har lämnat sitt samtycke till att dennes personuppgifter behandlas för ett eller
flera specifika ändamål.</p>

<p><strong>Relevant lagstiftning</strong></p>
<ul class="list-bullets">
    <li>EU:s allmänna dataskyddsförordning (679/2016)</li>
    <li>Dataskyddslagen (1050/2018)</li>
    <li>Bibliotekslagen (1492/2016)</li>
</ul>

<h3>5. Registrets datainnehåll</h3>
<p>Den registrerade: förnamn och e-postadress.<br>
För att garantera en lyckad läshandledning samlas information även om läsintressen och
kundens önskemål om vilken åldersgrupp böckerna ska passa för. Kunden kan också fritt
beskriva sina särskilda önskemål eller till exempel begränsningar i anslutning till läsningen.
För de yngsta registrerade är e-postadressen ofta vårdnadshavarens e-postadress.</p>

<h3>6. Regelmässigt utlämnande av personuppgifter</h3>
<p>Uppgifter lämnas inte ut; inte heller till länder utanför EU- eller EES-området. Utlämnande
av uppgifter för statistiska ändamål sker anonymt.</p>

<h3>7. Lagringstid av uppgifter</h3>
<p>Personuppgifterna lagras till utgången av det kalenderår under vilket läshandledningen
gavs.</p>

<h3>8. Uppgiftskällor för personuppgifter</h3>
<p>Personuppgifterna fås av den registrerade själv eller av hans eller hennes
vårdnadshavare.</p>
