<? $this->headTitle($this->translate('Yhteystiedot medialle')); $this->content()->setHeading($this->translate('Yhteystiedot medialle'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helmet on pääkaupunkiseudun yleisten kirjastojen kirjastoverkko (Helmet tulee sanoista Helsinki Metropolitan Area Libraries). 
        Helmet-kirjastoon kuuluvat Helsingin, Espoon, Kauniaisten ja Vantaan kaupunginkirjastot.</p>
      </div>
     <div id="helmet" class="content-section">
        <h2>Helmet.fi</h2>
        <p>Helmet-haku: Helmet-kirjaston sovelluspäällikkö Susanna Aakko, puh. 050 336 1968, <a href="mailto:susanna.aakko@hel.fi">susanna.aakko@hel.fi</a><br>
        Sisältösivut: Helmet-kirjaston verkkopäätoimittaja Iina Soininen, puh. 040 358 2780, <a href="mailto:iina.soininen@hel.fi">iina.soininen@hel.fi</a></p>
      </div>
      <div id="johtajat" class="content-section">
        <h2>Kirjastopalveluiden johtajat</h2>
        <p>Espoo: kirjastopalveluiden johtaja Ritva Nyberg, puh. 040 636 9207, <a href="mailto:ritva.nyberg@espoo.fi">ritva.nyberg@espoo.fi</a>.<br>
        Helsinki: kirjastopalvelujen johtaja Katri Vänttinen, puh. 040 554 8861, <a href="mailto:katri.vanttinen@hel.fi">katri.vanttinen@hel.fi</a><br>
        Kauniainen: kirjastotoimenjohtaja Jaakko Tiinanen, puh. 050 505 6403, <a href="mailto:jaakko.tiinanen@kauniainen.fi">jaakko.tiinanen@kauniainen.fi</a><br>
        Vantaa: kirjastopalveluiden päällikkö Leena Toivonen, puh. 040 357 5460, <a href="mailto:leena.toivonen@vantaa.fi">leena.toivonen@vantaa.fi</a></p>
      </div>
     <div id="viestinta" class="content-section">
        <h2>Viestintä</h2>
        <p>Espoo viestintäasiantuntija Marjut Saloniemi, puh. 050 303 6937, <a href="mailto:marjut.saloniemi@espoo.fi">marjut.saloniemi@espoo.fi</a><br>
        Helsinki: markkinointisuunnittelija Soila Leppäkangas, puh. 09 3108 5697, <a href="mailto:soila.leppakangas@hel.fi">soila.leppakangas@hel.fi</a><br>
        Kauniainen: informaatikko Maria Grundvall, puh. 09 505 6401, <a href="mailto:maria.grundvall@kauniainen.fi">maria.grundvall@kauniainen.fi</a><br>
        Vantaa: tiedottaja Minna Saastamoinen, puh. 050 312 1669, <a href="mailto:minna.saastamoinen@vantaa.fi">minna.saastamoinen@vantaa.fi</a></span></p>
      </div>
      <div id="esim2" class="content-section">
        <h2>Helmet-logon käyttäminen</h2>
        <p>Helmet-logo on Helmet-kirjastojen eli Helsingin, Espoon, Vantaan ja Kauniaisten kaupunginkirjastojen logo.
        <p>Logoa voivat käyttää viestinnässään media sekä kirjastojen yhteistyökumppanit, jotka viestivät esimerkiksi tapahtumasta, projektista tai hankkeesta.
        Logoa saa käyttää vain oheisen graafisen ohjeiston mukaisesti.</p>
        <p><strong>Kirjasto on aatteellisesti ja ideologisesti sitoutumaton toimija:</strong> aatteellisen, ideologisen tai kaupallisen viestinnän yhteydessä Helmet-logon 
        käytöstä on erikseen sovittava Helmet-viestintähenkilökunnan kanssa.</p>
        <p><a href="/themes/custom/files/helmet_logon_kaytto.pdf" target="_blank">Helmetin graafinen ohjeistus (PDF)</a> Lue ohjeet ennen logon käyttämistä.</p>
        <p><a href="/themes/custom/files/helmet_logo.png" target="_blank">Helmet-logo (.png)</a></p>
        <p><a href="/themes/custom/files/helmet_logo_tummatausta.png" target="_blank">Helmet-logo tummalle taustalle (.png)</a></p>
        <p><a href="/themes/custom/files/helmet_logo_mustavalkoinen.png" target="_blank">Helmet-logo mustavalkoinen (.png)</a></p>
      </div>
   </div>
</div>

