<? $this->headTitle($this->translate('Kontaktuppgifter för medierna')); $this->content()->setHeading($this->translate('Kontaktuppgifter för medierna'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helmet är ett biblioteksnätverk för de allmänna biblioteken i huvudstadsregionen (Helsinki Metropolitan Area Libraries). 
        Till nätverket hör Helsingfors, Esbo, Grankulla och Vanda stadsbibliotek.</p>
      </div>
     <div id="helmet" class="content-section">
        <h2>Helmet.fi</h2>
        <p>Helmet-sök: programchef Susanna Aakko, tfn 050 336 1968, <a href="mailto:susanna.aakko@hel.fi">susanna.aakko@hel.fi</a></p>
        <p>Huvudredaktör för webbplatsens innehåll: Iina Soininen, tfn 09 3108 5523, <a href="mailto:iina.soininen@hel.fi">iina.soininen@hel.fi</a></p>
      </div>
      <div id="chefer" class="content-section">
        <h2>Chefer för bibliotekstjänsterna</h2>
        <p>Esbo: chefen för bibliotekstjänsterna Ritva Nyberg, tfn 040 636 9207, <a href="mailto:ritva.nyberg@espoo.fi">ritva.nyberg@espoo.fi</a>.<br>
        Grankulla: biblioteksdirektör Jaakko Tiinanen, tfn 050 505 6403, <a href="mailto:jaakko.tiinanen@kauniainen.fi">jaakko.tiinanen@kauniainen.fi</a><br>
        Helsingfors: chef för bibliotekstjänsterna Katri Vänttinen, tfn 040 554 8861, <a href="mailto:katri.vanttinen@hel.fi">katri.vanttinen@hel.fi</a><br>
        Vanda: chef för biblioteksservicen Leena Toivonen, tfn 040 357 5460, <a href="mailto:leena.toivonen@vantaa.fi">leena.toivonen@vantaa.fi</a></p>
      </div>
     <div id="information" class="content-section">
        <h2>Information</h2>
        <p>Esbo: kommunikationsexpert Marjut Saloniemi, tfn 050 303 6937, marjut.saloniemi@espoo.fi<br>
        Grankulla: informatiker Maria Grundvall, tfn 09 505 6405, maria.grundvall@kauniainen.fi<br>
        Helsingfors: marknadsföringsplanerare Soila Leppäkangas, soila.leppakangas@hel.fi<br>
        Vanda: informatör Minna Saastamoinen, tfn 050 312 1669, minna.saastamoinen@vantaa.fi</p>
      </div>
      <div id="esim2" class="content-section">
        <h2>Att använda Helmets logo</h2>
        <p>Helmet-logon är Helmet-bibliotekens, dvs. Helsingfors, Esbo, Grankulla och Vanda stadsbiblioteks gemensamma logo. 
        Logon kan användas av medierna och av bibliotekens samarbetsparter då de informerar t.ex. om evenemang eller projekt.</p>
        <p>Logon får endast användas i enlighet med bifogade grafiska instruktioner.<br>
        <strong>Biblioteket fungerar oberoende av ideologier och är en ickekommersiell institution</strong>. I samband med kommersiell eller ideologisk kommunikation bör man komma överens 
        med Helmets informatörer om användningen av logon.</p>
        <p><a href="/themes/custom/files/helmet_logon_kaytto.pdf" target="_blank">Instruktioner om Helmet-logon (PDF på finska)</a></p>
        <p><a href="/themes/custom/files/helmet_logo.png" target="_blank">Helmet-logon</a> (.png)</p>
        <p><a href="/themes/custom/files/helmet_logo_mustavalkoinen.png" target="_blank">Helmet-logon, svartvit</a> (.png)</p>
        <p><a href="/themes/custom/files/helmet_logo_tummatausta.png" target="_blank">Helmet-logon med mörk bakgrund</a> (.png)</p>
      </div>
    </div>
</div>






