<? $this->headTitle($this->translate('Mikä Helmet on?')); $this->content()->setHeading($this->translate('Mikä Helmet on?'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="mika-on-helmet" class="content-section">
        <p>Helmet on pääkaupunkiseudun yleisten kirjastojen verkosto (Helsinki Metropolitan Area Libraries). Siihen kuuluvat Helsingin, Espoon, Kauniaisten ja Vantaan kaupunginkirjastot.</p>
        <p>Helmet-kirjaston asiakkaana käytössäsi on yli 60 olohuonetta, palveluksessasi yli 780 henkilöä ja kalenteriisi voit merkitä kirjaston tarjoamia tapahtumia vuoden jokaiselle viikolle. 
        Teemme sinulle asiat helpoiksi. Voit surffata verkkopalveluissa, ja aineistot kuljetetaan lähikirjastoosi. 
        Kysymyksiisi saat nopean vastauksen niin kasvotusten kuin sähköisestikin. Helmet-yhteistyöllä saavutamme tuloksia, joihin emme pystyisi yksin.</p>
        <p><a href="/Content/kirjasto-selkokielella">Selkokielinen Helmet-kirjaston esittely</a></p>
        <p><a href="/Content/tietosuoja">Tietosuoja ja tietoa sivustosta</a></p>
        <p><a href="/themes/custom/files/helmet-kirjastojen yhteistyosopimus.pdf" target="_blank">Helmet-kirjastojen yhteistyösopimus (PDF)</a></p>
      </div>
     <div id="yhteisia" class="content-section">
        <h2>Yhteisiä Helmet-kirjastossa</h2>
        <ul class="list-bullets">
          <li>kirjastojärjestelmä</li>
          <li>verkkokirjasto, e-kirjasto</li>
          <li>lainausoikeus ja kirjastokortti</li>
          <li>käyttösäännöt ja maksupolitiikka</li>
          <li>kokoelmat</li>
          <li>aineiston hankintajärjestelmä ja yhteisiä hankintapaikkoja</li>
          <li>aineistokuljetukset kuntien välillä</li>
          <li>lainaavat kirja- ja musiikkivarastot</li>
          <li>toimintaa koordinoivat ryhmät</li>
          <li>koulutuksia</li>
          <li>tiedotusta, kampanjoita ja asiakaskyselyitä</li>
        </ul>
      </div>
      <div id="tilastot" class="content-section">
        <h2>Tilastot</h2>
        <ul class="list-bullets">
          <li>66 kirjastoa, kuusi kirjastoautoa ja kirjastopyöriä</li>
          <li>8 potilaskirjastoa ja kotipalvelu</li>
          <li>780 työntekijää</li>
          <li>kokonaislainaus 15,8 miljoonaa</li>
          <li>käyntien määrä vuodessa 30 miljoonaa, joista verkkokäynnit yli 17 miljoonaa</li>
          <li>3,2 miljoonaa teosta</li>
          <li>palvelee yli miljoonaa pääkaupunkiseudun asukasta</li>
        </ul>
      </div>
        <div id="lisatietoja" class="content-section">
        <h2>Lisätietoja</h2>
        <ul class="list-bullets">
          <li><a href="https://www.espoo.fi/fi/kulttuuri-ja-vapaa-aika/kirjasto" target="_blank"
          aria-label="Espoon kaupunginkirjasto. Linkki aukeaa uudessa ikkunassa.">Espoon kaupunginkirjasto</a></li>
          <li><a href="http://www.kauniainen.fi/kirjasto/" target="_blank"
          aria-label="Kauniaisten kaupunginkirjasto. Linkki aukeaa uudessa ikkunassa.">Kauniaisten kaupunginkirjasto</a></li>
          <li><a href="http://www.vantaa.fi/fi/kirjasto" target="_blank"
          aria-label="Vantaan kaupunginkirjasto. Linkki aukeaa uudessa ikkunassa.">Vantaan kaupunginkirjasto</a></li>
          <li><a href="/Content/medialle"
          aria-label="Medialle. Linkki aukeaa uudessa ikkunassa.">Medialle</a></li>
        </ul>
      </div>
   </div>
</div>
