<? $this->headTitle($this->translate('Vad är Helmet?')); $this->content()->setHeading($this->translate('Vad är Helmet?'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="vad-ar" class="content-section">
        <p>Helmet är ett nätverk för de allmänna biblioteken i huvudstadsregionen (Helsinki Metropolitan Area Libraries). Till nätverket hör Helsingfors, Esbo, Grankulla och Vanda 
        stadsbibliotek.</p>
        <p>Du har över 60 vardagsrum till ditt förfogande, över 780 personer är beredda att ge dig service och vi arrangerar intressanta evenemang minst en 
        gång i veckan året runt. Vi gör det lätt för dig. Du får surfa på våra webbtjänster eller beställa material som transporteras till närmaste bibliotek. Ställ en fråga och 
        du får snabbt svar - ansikte mot ansikte eller elektroniskt.</p><p>Helmet-nätbiblioteket är ett av Finlands mest uppskattade nätvarumärken. Nättjänsten 
        <a href="/">www.helmet.finna.fi</a> är Finlands mest anlitade nätbibliotek. Via Helmet hittar du information om mer än tre miljoner verk som finns till för 
        alla som har ett bibliotekskort.</p><p>Genom Helmet-samarbetet får vi resultat som inget bibliotek klarar ensamt.</p>
        <p><a href="/Content/tietosuoja?lng=sv">Dataskydd och information om webbplatsen</a></p>
      </div>
     <div id="gemensamt" class="content-section">
      <h2>Gemensamt för alla Helmet-bibliotek</h2>
      <ul class="list-bullets">
          <li>bibliotekssystemet</li>
          <li>nätbiblioteket, e-biblioteket</li>
          <li>lånerätten och bibliotekskortet</li>
          <li>lånereglerna och avgiftspolitiken</li>
          <li>samlingarna</li>
          <li>systemet för materialanskaffning</li>
          <li>transport av material mellan kommunerna</li>
          <li>möjlighet att låna material ur bok- och musikmagasin</li>
          <li>grupper som koordinerar verksamheten</li>
          <li>olika utbildningar</li>
          <li>information, kampanjer och kundenkäter</li>
      </ul>
      </div>
      <div class="col-sm-9">
      <div id="statistik" class="content-section">
        <h2>Statistik</h2>
        <ul class="list-bullets">
          <li>66 bibliotek, sex bokbussar och bibliotekscyclar</li>
          <li>8 patientbibliotek samt Boken kommer-tjänst</li>
          <li>personal: 780 personer</li>
          <li>totalt antal lån: drygt 15,8 miljoner</li>
          <li>besök per år: ca 30 miljoner, varav drygt 17 miljoner är besök på nätet</li>
          <li>3,2 miljoner verk</li>
          <li>betjänar över en miljon invånare i huvudstadsregionen</li>
        </ul>
      </div>
     <div id="information" class="content-section">
        <h2>Mer information:</h2>
        <ul class="list-bullets">
          <li><a href="https://www.espoo.fi/sv/kultur-och-fritid/bibliotek" target="_blank"
          aria-label="Esbo stadsbibliotek. Länken öppnas i ett nytt fönster.">Esbo stadsbibliotek</a></li>
          <li><a href="http://www.kauniainen.fi/sv/service_och_blanketter/bibliotek/" target="_blank"
          aria-label="Grankulla stadsbibliotek. Länken öppnas i ett nytt fönster.">Grankulla stadsbibliotek</a></li>
          <li><a href="https://www.vantaa.fi/sv/tjanster/tjanst/bibliotekstjanster" target="_blank"
          aria-label="Vanda stadsbibliotek. Länken öppnas i ett nytt fönster.">Vanda stadsbibliotek</a></li>
        </ul>
      </div>
   </div>
</div>