<? $this->headTitle($this->translate('What is Helmet?')); $this->content()->setHeading($this->translate('What is Helmet?'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="what-is" class="content-section">
        <p>Helmet network (Helsinki Metropolitan Area Libraries) consists of the city libraries of Helsinki, Espoo, Kauniainen, and Vantaa.<br><br>
        As a customer of a Helmet library you have more than 60 living rooms at your disposal, 780 employees at your service, and you can mark every single page of your calendar with a library event.<br><br>
        We make everything easy for you: you can surf the web library and the materials you request are delivered close to you. Your questions are rapidly answered by mouth as well as electronically.</p>
        <p>Helmet web library is the most frequently used web library in Finland. Helmet service consists of information on more than three million items that are available to everybody living in the metropolitan area.<br><br>
        Helmet cooperation provides us with results that we could not achieve on our own.</p>
        <p><a href="/Content/tietosuoja?lng=en-gb">Data protection and information about this site</a>
      </div>
     <div id="offer" class="content-section">
        <h2>What Helmet libraries offer</h2>
        <ul class="list-bullets">
            <li>library system</li>
            <li>net library, e-library</li>
            <li>right to borrow material and library card</li>
            <li>user regulations and payment policy</li>
            <li>collections</li>
            <li>material acquisition system and joint acquisition places</li>
            <li>transfer of materials between municipalities</li>
            <li>book and music stockrooms that give out loans</li>
            <li>teams coordinating operations</li>
            <li>training</li>
            <li>information, campaigns, and customer surveys</li>
        </ul>
      </div>
      <div id="statistics" class="content-section">
        <h2>Statistics</h2>
        <ul class="list-bullets">
            <li>66 libraries, six bookmobiles and library bicycles</li>
            <li>8 patient libraries and home service</li>
            <li>staff: 780 library and media professionals</li>
            <li>total number of loans more than 15,8 million</li>
            <li>annual visits approx. 30 million, of which more than 17 million are net library visitors</li>
            <li>3.2 million items</li>
            <li>Helmet libraries serve more than a million customers in the metropolitan area.</li>
        </ul>
      </div>
      <div id="information" class="content-section">
        <h2>More information:</h2>
        <ul class="list-bullets">
          <li><a href="https://www.espoo.fi/en/culture-and-leisure/library" target="_blank" 
          aria-label="Espoo City Library. The link opens in a new window.">Espoo City Library</a></li>
          <li><a href="http://www.kauniainen.fi/en/public_services_and_forms/library" target="_blank"
          aria-label="Kauniainen Library. The link opens in a new window.">Kauniainen Library</a></li>
          <li><a href="https://www.vantaa.fi/en/services/service/library-services#tab-introduction" target="_blank"
          aria-label="Vantaa City Library. The link opens in a new window.">Vantaa City Library</a></li>
        </ul>
      </div>
   </div>
</div>

