<? $this->headTitle($this->translate('Ohjeet e-aineistojen käyttöön')); $this->content()->setHeading($this->translate('Ohjeet e-aineistojen käyttöön'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="e-kirjat-ja-aanikirjat" class="content-section">
        <h2>Ohjeet e-kirja- ja äänikirjapalveluihin</h2>
        <p>E-kirjojen lainaamiseen tarvitset kirjastokortin ja PIN-koodin, lukemiseen sopivan laitteen sekä verkkoyhteyden.</p>
        <p>Jos lataat kirjoja omalle laitteellesi, tarvitset myös sovelluksen tai lukuohjelman. Alta löydät laitekohtaiset ohjeet.</p>
        <h3>Lue nettiselaimessa</h3>
        <p>E-kirjoja on helpointa lukea suoraan nettiselaimessa. Silloin et tarvitse laitteellesi erillistä lukuohjelmaa etkä muita tunnuksia kuin kirjastokortin numeron ja PIN-koodin.</p>
        <p>Selainlukeminen onnistuu tietokoneella tai mobiililaitteella, jossa on verkkoyhteys ja päivitetty selain. Suosittelemme selainlukemiseen Firefoxia, Chromea tai Safaria 
        laitteesta riippuen.</p>
        <p>Suurinta osaa e-kirjoista voi lukea selaimessa, ei kuitenkaan PDF-muodossa tallennettuja kirjoja. Jos kirjaa ei voi lukea selaimessa, sen tiedoissa ei ole vaihtoehtoa 
        ”Lue” tai ”Lue selaimessa”. Näitä kirjoja voi lukea vain lataamalla ne omalle laitteelle.</p>
        
        <h3>Kuuntele äänikirjoja</h3>
        <p>Äänikirjoja voi kuunnella nettiselaimessa tai palvelun omassa sovelluksessa. Äänikirjat voi ladata sovellukseen, jolloin niitä voi kuunnella ilman nettiyhteyttä. 
        Lisää tietoa sovelluksista löydät alta.</p>
        <p>Katso myös <a href="#ulkomaalaiset-aanikirjat">Naxos Spoken Word Libraryn äänikirjojen ohjeet</a>.</p>
        <p>Katso kuinka saat käyttöön <a href="#lukemisesteisille">Celian äänikirjat lukemisesteisille</a>.</p>
        
        <h3>Lue ja kuuntele sovelluksessa</h3>
        <p>Kaikilla e-kirjapalveluilla on iOS ja Android mobiililaitteille tarkoitetut sovellukset. Sovellukset ovat maksuttomia ja voit ladata ne laitteesi sovelluskaupasta. 
        E-kirjapalvelusta riippuen sovelluksesta voi puuttua esimerkiksi e-kirjat tai osa PDF-muotoisista teoksista. Palvelun kaikki teokset löytyvät palvelun nettisivulta.</p>
        
        <p><strong>Ellibs-sovelluksella</strong> voi lainata ja käyttää e-kirjoja sekä äänikirjoja. Sovellukseen ladattuja äänikirjoja ja lainattuja e-kirjoja voi käyttää ilman verkkoyhteyttä. 
        <p><a href="https://youtu.be/NT57zoEMovA" target="_blank" aria-label="Ohjevideo e-äänikirjan kuunteluun Ellibs-sovelluksella. Linkki avautuu uudessa ikkunassa.">
        Ohjevideo e-äänikirjan kuunteluun Ellibs-sovelluksella</a></p>
        
        <p><strong>OverDrive-palvelua</strong> voi käyttää Libby-sovelluksella. <strong>Libby</strong> on erinomainen käytettävyydeltään. Siinä on tunnisteet toivelistojen ja 
        suosikkikirjojen seuraamiseen, push-ilmoitukset, äänikirjojen yhteensopivuus Applen CarPlay ja Android Auton kanssa, suora sovelluksen sisäinen tuki ja paljon muuta. 
        Sovellukseen voi myös ladata kirjoja käytettäväksi ilman verkkoyhteyttä.</p>
        
        <h3>E-kirjojen lataaminen omalle laitteelle</h3>
        <p>Omalle laitteelle ladattuja e-kirjoja voi lukea ilman nettiyhteyttä. Kaikissa Helmet-kirjastojen tarjoamissa e-kirjoissa on tekijänoikeussuojaus ja ne voi avata vain suojauksen 
        tunnistavalla lukuohjelmalla. Tarvittava lukuohjelma vaihtelee laitteen mukaan, katso tarkemmin alta. Laina-ajan päätyttyä e-kirja ei enää aukea lukuohjelmassa.</p>
        <p>OverDriven e-kirjoja voi ladata myös Libby-sovellukseen. <strong>Äänikirjoja voi ladata vain palveluiden omiin sovelluksiin</strong>.</p>
        <p>Suosittelemme käyttämään e-kirjojen lataamiseen Chrome-, Firefox- tai Safari-selainta. iOS-laitteissa suuret äänikirjatiedostot kannattaa ladata wifi-yhteydellä.</p>
        
        <h3>Adoben käyttäjätunnus</h3>
        <p>Lukuohjelman lisäksi tarvitset Adobe-käyttäjätunnuksen, joka sallii tekijänoikeussuojatun kirjan avaamisen. Tunnus kannattaa tallentaa lukuohjelmaan ennen e-kirjan lataamista. 
        Tunnuksen luominen on maksutonta ja onnistuu Adoben nettisivulla.</p>
        <p><a href="https://adobe.ly/2CNb77D" target="_blank" aria-label="Hanki Adobe-tunnus. Linkki aukeaa uudessa ikkunassa.">Hanki Adobe-tunnus</a></p>
        <p><a href="https://helpx.adobe.com/fi/x-productkb/global/adobe-id-account-change.html" target="_blank" 
        aria-label="Lisätietoa Adobe-tunnuksesta. Linkki aukeaa uudessa ikkunassa.">Lisätietoa Adobe-tunnuksesta</a></p>
        <p>Kun lukuohjelma käynnistyy laitteellasi ensimmäisen kerran, valtuuta ohjelma Adobe-tunnuksella ja salasanalla. Valtuutus tehdään vain kerran, ja jatkossa ohjelma avautuu 
        automaattisesti tunnuksillasi. Samaa Adobe-tunnusta voit käyttää kuudessa eri laitteessa tai ohjelmassa.</p>
        
        <h3>E-kirjojen lataaminen tabletille tai älypuhelimelle</h3>
        <p>Ellibsin kirjoja voit halutessasi ladata myös Aldiko Book Reader -ohjelmaan Android- ja iOS-laitteilla. Lataa ohjelma laitteesi sovelluskaupasta ja tallenna siihen Adobe-tunnus. 
        OverDrive-palvelun e-kirjoja ja äänikirjoja voi ladata vain palvelun omaan sovellukseen, joka ei vaadi Adobe-tunnusta.</p>
        <p>Windows-mobiililaitteilla ei voi käyttää OverDriven e-kirjoja Libby-sovelluksella, mutta voit käyttää Libby-sovellusta selaimellasi osoitteessa www.libbyapp.com.</p>
        
        <h3>E-kirjojen lataaminen tietokoneelle</h3>
        <p>Windows- ja Mac-tietokoneilla voit ladata e-kirjoja Adobe Digital Editions -lukuohjelmaan. Ohjelmaan täytyy tallentaa Adobe-tunnus.</p>
        <p><a href="http://www.adobe.com/fi/solutions/ebook/digital-editions/download.html" target="_blank" 
        aria-label="Lataa Adobe Digital Editions -ohjelma. Linkki aukeaa uudessa ikkunassa.">Lataa Adobe Digital Editions -ohjelma</a></p>
        <p><a href="https://www.ellibslibrary.com/instructions" target="_blank">Katso lukuohjelman asennusohjeet Ellibs-e-kirjapalvelun sivulta</a></p>
        
        <h3>E-kirjojen lukulaitteet</h3>
        <p>Kirjaston e-kirjoja voi lukea useimmilla e-kirjan lukulaitteilla. Kindlellä ei voi lukea kirjaston e-kirjoja, sillä se käyttää Amazonin omaa tekijänoikeussuojausta ja 
        tiedostomuotoa.</p>
        <p>E-kirja kopioidaan lukulaitteelle tietokoneen kautta tai suoraan e-kirjapalvelusta, jos lukulaitteessa on verkkoyhteys ja mahdollisuus verkosta lataamiseen. 
        Tarkista ohjeet lukulaitteen käyttöoppaasta.</p>
        <p>Jos kopioit kirjan lukulaitteellesi tietokoneen kautta, on sinun asennettava tietokoneellesi Adobe Digital Editions -ohjelma. Tarvitset myös Adobe-tunnuksen, 
        jolla valtuutat ohjelman. Ohjelma on valtuutettava samalla Adobe-tunnuksella kuin lukulaitteesikin. Lukulaitteesi käyttöoppaassa kerrotaan tarkemmin e-kirjan siirtämisestä laitteelle.</p>
        <p><a href="http://www.adobe.com/fi/solutions/ebook/digital-editions/download.html" target="_blank" 
        aria-label="Lataa Adobe Digital Editions -ohjelma. Linkki avautuu uudessa ikkunassa.">Lataa Adobe Digital Editions -ohjelma</a></p>
        
        <h3>Palveluiden ohjeet ja tuki</h3>
        <p><a href="https://www.ellibslibrary.com/fi/instructions" target="_blank" aria-label="Ellibs-palvelun ohjeet. Linkki avautuu uudessa ikkunassa.">
        Ellibs-palvelun ohjeet</a></p>
        <p>Lue <a href="https://help.overdrive.com/" target="_blank" aria-label="OverDrive-palvelun ohjeet. Linkki aukeaa uudessa ikkunassa.">OverDrive-palvelun ohjeet</a> 
        tai katso <a href="https://youtu.be/Ee6xbs0GBVw" target="_blank" aria-label="OverDrive-hjevideo. Linkki aukeaa uudessa ikkunassa.">OverDrive-ohjevideo</a></p>
        <p>Mikäli pulmia tulee vastaan, voit ottaa yhteyttä sähköpostitse osoitteeseen <a href="mailto:hki.ekirja@hel.fi">hki.ekirja@hel.fi</a>. Kuvaathan ongelman ja kerrot käyttämäsi 
        laitteet ja ohjelmistot. Ellibs-palvelun ongelmista voit kysyä suoraan Ellibsin tuesta osoitteesta <a href="mailto:support@ellibs.com">support@ellibs.com</a>.</p>
      </div>
      <div id="epress" class="content-section">
        <h2>Epress (ent. eMagz)</h2>
        <p>Epress-palvelu sisältää yli 80 kotimaista aikakauslehteä ja muutaman sanomalehden.</p>
        <h3>Epressin käyttö selaimella</h3>
        <p>Avaa <a href="https://helmet.emagz.fi/ext/login/helmet" target="_blank" aria-label="ePress-sivusto. Linkki aukeaa uudessa ikkunassa.">ePress-sivusto</a> ja kirjaudu 
        palveluun Helmet-kirjastokortilla ja PIN-koodilla. Voit lukea lehtiä mobiililaitteiden ja tietokoneiden yleisimmillä nettiselaimilla. Käytä selaimen uusinta versiota.</p>
        <p>Samaa lehteä voi lukea yhtä aikaa 1–10 käyttäjää. Lukuoikeuksien määrä vaihtelee lehdestä toiseen. Jos et pääse lukemaan haluamaasi lehteä, kokeile hetken kuluttua uudestaan.</p>
        <p>Voit lukea lehteä korkeintaan kaksi tuntia kerrallaan, jonka jälkeen järjestelmä kirjaa sinut automaattisesti ulos. Jos olet kirjautunut sisään, mutta et käytä palvelua 
        viiteentoista minuuttiin, järjestelmä kirjaa sinut ulos.</p>
        <p>Huomioi, että kirjautumalla palveluun kirjastokortilla palveluntarjoaja saa tietoonsa evästetiedosi (esimerkiksi IP-osoite tai selaimen versio).</p>
      </div>
      <div id="pressreader" class="content-section">
        <h2>PressReader</h2>
        <p>PressReader sisältää ulkomaisia aikakaus- ja sanomalehtiä. Voit lukea lehtiä joko laitteesi selaimessa tai mobiilisovelluksella. Tarvitset kirjautumista varten kirjastokorttisi 
        numeron ja PIN-koodin.</p>
        <h3>PressReaderin käyttö selaimella</h3>
        <p>Avaa <a href="https://www.pressreader.com/catalog" target="_blank" aria-label="PressReader-sivusto. Linkki aukeaa uudessa ikkunassa."> PressReader</a>-sivusto, napauta
        Sign in -kuvaketta sivuston oikeassa ylälaidassa ja valitse sen jälkeen Library or group -kirjautumisvaihtoehto. Kirjoita hakukenttään Helmet. Klikkaa hakutuloksesta 
        HELMET Helmet Libraries -kohtaa. Kirjoita kirjastokorttisi numero ja PIN-koodisi niille varattuihin kenttiin. Laita ruksi kohtaan ”I agree to allowing PressReader to verify and 
        exchange my registration with my public library” ja kirjaudu palveluun Log in -näppäimestä.</p>
        <p>Odota hetki PressReader HotSpot-ikkunan avautumista. Pääset selaamaan lehtivalikoimaa napauttamalla Select publication -painiketta. Voit selailla lehtiä maan, kielen, aihepiirin 
        tai lehtityypin mukaan tai hakea lehtiä nimellä. Lehti avautuu napauttamalla kansikuvaa.</p>
        <p>Pääset takaisin palvelun aloitusnäyttöön napauttamalla Catalog-painiketta.</p>
        <p>Huomioi, että kirjautumalla palveluun kirjastokortilla palveluntarjoaja saa tietoonsa evästetiedosi (esimerkiksi IP-osoite tai selaimen versio).</p>
        
        <h3>PressReaderin käyttö sovelluksella</h3>
        <p>Hae maksuton PressReader-sovellus mobiililaitteesi sovelluskaupasta. Jos olet ladannut sovelluksen jo aikaisemmin, tarkista, että käytössäsi on aina sovelluksen uusin versio.</p>
        <p>Avaa sovelluksen valikosta kohta Sign in. Valitse kirjastokorttikirjautuminen “Library or Group”. Valitse Select library -listasta Helmet tai kirjoita Helmet suoraan hakukenttään.
        Kirjoita kirjastokorttisi numero ja siihen liitetty tunnusluku (PIN) niille varattuihin kenttiin.</p>
        <p>Palvelu ehdottaa erillisten tunnusten luomista lisäominaisuuksia varten. Mikäli et halua luoda tunnuksia, voit ohittaa tämän ilmoituksen. Tarkista, että HotSpot asetus 
        (kahvikuppisymboli on vihreä) on päällä ja valitse Cancel kirjautumisnäytöllä.<br><br>
        Odota hetki, kunnes eteesi aukeaa PressReader HotSpot -ikkuna. Tämän jälkeen voit selailla lehtikokoelmaa, lukea lehtiä ja ladata niitä laitteesi muistiin luettavaksi ilman 
        verkkoyhteyttä. Lehtien lataamisen aikana tulee HotSpot olla päällä. Jos näytön alareunassa oleva kahvikuppisymboli ei ole vihreä, käynnistä HotSpot sovelluksen asetuksista.</p>
        <p>PressReaderin lehtiä voi käydä lataamassa myös Helsingin ja Espoon kirjastojen langattomissa verkoissa, jolloin sinun ei tarvitse kirjautua sovellukseen – riittää, että avaat 
        sovelluksen kirjaston langattomassa verkossa.</p>
        <p>Luetuimpia aikakauslehtiä ovat Auto Express, T3, Bloomberg Businessweek, Amateur Photographer, Mojo, Linux Format, Men’s Health, The GuardianWeekly, Apple Magazine, BBC Good 
        Food Magazine, What HI-Fi, Newsweek, Harper’s Bazaar, Elle ja Variety.</p>
        <p>Suosituimpia sanomalehtiä ovat HBL, The Guardian, Svenska Dagbladet, Aftonbladet, Corriere Della Sera, El Pais, The Washington Post, Daily Mail, Le Figaro, Liberation, G2, New York 
        Post, The Daily Telegraph, Der Tagesspiegel ja Daily Mirror.</p>
      </div>
      <div id="naxos" class="content-section">
        <h2>Naxos Spoken Word</h2>
        <p>Naxos Spoken Word -palvelusta löydät tuhansia e-äänikirjoja. Tarjolla on sekä kauno- että tietokirjallisuutta pääasiassa englanniksi: klassikoita, muistelmia, bisneskirjallisuutta 
        ja kielikursseja.</p>
        <p>Suurin osa Naxos Spoken Wordin äänikirjoista ja kuunnelmista on englanninkielisiä. Äänikirjojen lukijoiden joukossa on useita tunnettuja näyttelijöitä. Palvelussa on myös 
        jonkin verran ranskan-, saksan- ja portugalinkielistä kirjallisuutta. Voit selata palvelun sisältöä aihealueiden, kirjoittajien tai lukijoiden mukaan.</p>
        <h3>Näin käytät Naxos Spoken Wordia</h3>
        <p>Voit käyttää Naxos Spoken Wordia tietokoneen, tabletin tai älypuhelimen nettiselaimella. Kirjaudu sisään kirjastokorttisi numerolla. Valitse haluamasi äänikirja ja aloita 
        kuuntelu saman tien. Äänikirjoja ei tarvitse lainata tai varata. Nettiyhteyden täytyy olla päällä kuuntelun aikana.</p>
        <p><a href="https://helsinkilib.naxosspokenwordlibrary.com" target="_blank" aria-label="Kirjaudu Naxos Spoken Word Libraryyn. Linkki aukeaa uudessa ikkunassa.">Kirjaudu Naxos Spoken 
        Word Libraryyn</a></p>
        <p>Palvelussa voi samaan aikaan olla kirjautuneena 20 käyttäjää. Muutamia Naxos Spoken Wordin teoksia ei valitettavasti voi kuunnella Suomessa tekijänoikeussyistä.</p>
        <p>Tietokoneella suosittelemme käyttämään mahdollisimman uutta versiota Internet Explorer-, Chrome-, Firefox- tai Safari-selaimesta. Selaimessa on oltava Flash-tuki. 
        Tarkemmat tekniset vaatimukset löydät <a href="https://helsinkilib.naxosspokenwordlibrary.com/faqs.asp" target="_blank" 
        aria-label="Naxos Spoken Word Libraryn FAQ-osiosta. Linkki aukeaa uudessa ikkunassa.">Naxos Spoken Word Libraryn FAQ-osiosta</a>.</p>
        
        <h3>Naxos Spoken Word toimii myös mobiilisovelluksena</h3>
        <p>iOS- ja Android-laitteilla palvelua voi käyttää NSWL-sovelluksella, jonka löydät laitteesi sovelluskaupasta. Sovellukseen voit myös tallentaa äänikirjoja kuunneltavaksi ilman 
        verkkoyhteyttä. NSWL-sovelluksen käyttö edellyttää henkilökohtaisen käyttäjätilin luontia. Toimi näin:</p>
        <ol class="list-numbers">
          <li>Mene <a href="https://helsinkilib.naxosspokenwordlibrary.com" target="_blank" aria-label="Naxos Spoken Word Libraryn sivulle. Linkki aukeaa uudessa ikkunassa.">
            Naxos Spoken Word Libraryn sivulle.</a></li>
          <li>Syötä Helmet-kirjastokorttisi numero (ilman välilyöntejä) ja klikkaa Login.</li>
          <li>Klikkaa Create Student/member account linkkiä. Anna vaaditut tiedot. Saat vahvistuksen rekisteröitymisestä sähköpostiisi, toimi ohjeen mukaan.</li>
          <li>Lataa mobiililaitteesi sovelluskaupasta NSWL-sovellus.</li>
          <li>Kirjaudu sovellukseen luomallasi käyttäjätunnuksella ja nauti äänikirjoista.<br>
        	Muista sulkea sovellus, kun olet lopettanut kuuntelemisen. Palveluun voi olla kirjautuneena kerrallaan vain rajoitettu määrä kuuntelijoita.</li>
        </ol>
        <h3>Jatka kuuntelua kirjanmerkin avulla</h3>
        <p>Voit valita äänikirjasta kuunneltavaksi joko kappaleen kerrallaan tai koko äänikirjan. Jos haluat jatkaa kuuntelua myöhemmin, voit tehdä äänikirjaan kirjanmerkin napauttamalla 
        kirjanmerkkisymbolia. Merkki tulee sen kappaleen alkuun, jonka aikana teit kirjanmerkin.</p>
        <p>Pääset luomiisi kirjanmerkkeihin Bookmarks-välilehdeltä.</p>
        <p>Kun lopetat kuuntelun, kirjaudu ulos Naxos Spoken Wordista tai sulje NSWL-sovellus laitteesi muistista, jotta lisenssi vapautuu seuraavan kuuntelijan käyttöön.</p>
      </div>
      <div id="naxos-music" class="content-section">
          <h2>Naxos Music World</h2>
          <h3>Ohjeita Naxos-palveluiden käyttöön</h3>
          <p>Kirjautumiseen tarvitaan Helmet-kirjastokortti. Syötä kirjastokortin numero ilman välilyöntejä ja klikkaa Login-painiketta. Seuraa palvelun omia, englanninkielisiä 
          ohjeita.</p>
          <p>Palveluiden yhtäaikaista käyttäjämäärää on rajoitettu. Music Libraryssa voi olla samaan aikaan 25 käyttäjää ja muissa palveluissa jokaisessa 10 käyttäjää. Jos 
          maksimimäärä on täynnä, palveluun ei pääse sisälle. Kun lopetat, muista kirjautua palvelusta ulos, jotta seuraava käyttäjä pääsee kirjautumaan palveluun.</p>
         <p>Tarkemmat järjestelmävaatimukset näkyvät kirjautumissivulla. Jos et saa haluamaasi kappaletta kuulumaan, tietokoneen asetuksissa tulee sallia ponnahdusikkunat 
         Naxoksen verkkosivuilla, tai voit painaa ctrl-näppäintä, kun valitset kappaleen. Jos video puuttuu Video-palvelussa, Flash täytyy sallia nettiselaimessasi Naxos 
         Video Libraryn sivulla.</p>
         <h3>Ohjeet Naxos-sovelluksen käyttöön</h3>
         <p>Voit käyttää Naxos-palveluiden sovelluksia Android- ja iOS laitteilla. Tarvitset musiikin kuunteluun verkkoyhteyden. Sovelluksessa on myös offline-kuuntelumahdollisuus.
         Sovelluksen käyttö vaatii erillisen käyttäjätilin luomisen.</p>
         <ol class="list-numbers">
            <li>Mene <a href="http://helsinkilib.naxosmusiclibrary.com/" target="_blank" aria-label="Naxos Music Library. Linkki aukeaa uudessa ikkunassa.">Naxos Music Libraryn</a>, 
            <a href="http://helsinkilib.naxosmusiclibrary.com/jazz/page.library_cardno.asp" target="_blank" aria-label="Naxos Music Library Jazz. Linkki aukeaa uudessa ikkunassa.">
            Naxos Music Library Jazzin</a> tai <a href="http://helsinkilib.naxosmusiclibrary.com/World/homepage.asp" target="_blank" aria-label="Naxos Music Library World. 
            Linkki aukeaa uudessa ikkunassa.">Naxos Music Library Worldin</a> sivulle.</li>
            <li>Syötä Helmet-kirjastokorttisi numero (ilman välilyöntejä) ja klikkaa Login.</li>
            <li>Luo käyttäjätili Playlists-välilehdellä. Klikkaa kohdasta Student/member playlists account linkkiä Sign up. Anna vaaditut tiedot. Saat vahvistuksen rekisteröitymisestä sähköpostiisi, toimi ohjeen mukaan.</li>
            <li>Lataa mobiililaitteesi sovelluskaupasta NML- tai NML Jazz tai NML World -sovellus.</li>
            <li>Kirjaudu sovellukseen luomallasi käyttäjätunnuksella ja nauti musiikista.</li>
            <li>Muista sulkea sovellus, kun olet lopettanut kuuntelemisen. Palveluun voi olla kirjautuneena kerrallaan vain rajoitettu määrä kuuntelijoita.</li> 
         </ol>
         <p>Jos et ole käyttänyt sovellusta pitkään aikaan, kirjautuminen ei välttämättä onnistu. Saat silloin viestin sähköpostiosoitteeseen, joka toimii käyttäjätunnuksenasi. 
         Noudata sähköpostissa olevia ohjeita, jotta voit aktivoida tunnuksen uudelleen.</p>
         <p>Huomaathan, että kuhunkin palveluun täytyy erikseen tehdä henkilökohtainen tili mobiilikäyttöä varten. Tili (s-postiosoite ja salasana) voi kuitenkin olla kaikissa 
         Naxos-palveluissa sama.</p>
         <p>Henkilökohtaisen tilin luomisesta on hyötyä. Sen ansiosta voit tehdä mm. soitto- ja suosikkilistoja sekä mobiilisovelluksissa että selaimessa. Lisäksi henkilökohtaisilla 
         tunnuksilla voi kirjautua suoraan palveluiden pääsivuilla www.naxosmusiclibrary.com, www.naxosmusiclibrary.com/jazz ja www.naxosmusiclibrary.com/world. Sinun ei siis 
         tarvitse muistaa kirjaston omaa URLia tai käydä palvelussa kirjaston sivun linkin kautta.</p>
      </div>
      <div id="medici" class="content-section">
          <h2>Medici.tv</h2>
          <p>Kirjaudu palveluun Helmet-kirjastokorttisi numerolla. Palvelussa on rajoittamaton yhtäaikainen käyttö, ja se toimii kaikissa digitaalisissa laitteissa yleisimmillä, 
          päivitetyillä selaimilla. Tarkemmat ohjeet ja esittelyn löydät palvelun Tuki-osiosta.</p>
          <p>Voit hakea videoita esimerkiksi teoksen nimellä, esittäjällä tai säveltäjällä tai selata sisältöä lajityyppien mukaan. Kalenteri-osiosta näet uusien sisältöjen sekä 
          tulevien live-esitysten aikataulun.</p>
          <p>Sivustoa voi käyttää neljällä kielellä: englanti, ranska, espanja ja venäjä.</p>
          <h3>Palvelun lisäominaisuudet</h3>
          <p>Palveluun kirjautumisen yhteydessä voit myös halutessasi luoda sinne oman käyttäjätilin. Luomalla tilin voit mm. tallentaa suosikkivideosi, seurata katseluhistoriaasi 
          ja rakentaa soittolistoja.Tässä ovat kuvalliset ohjeet englanniksi <a href="https://www.canva.com/design/DAFOKSIh5fA/5Brch0cmeg44CjaCXvmeFw/view?utm_content=DAFOKSIh5fA&amp;utm_campaign=designshare&amp;utm_medium=link2&amp;utm_source=sharebutton" 
          target="_blank" aria-label="tilin luomiseksi. Linkki aukeaa uudessa ikkunassa.">tilin luomiseksi</a>.</p>
          <p>Medici.tv tarjoaa viisi erilaista videovirtaa, jotka sopivat kaiken tyyppisiin yhteyksiin 3G:stä kuituun. Videon bittinopeus on mukautuva, eli videon laatu perustuu 
          oletusarvoisesti internetyhteytesi nopeuteen. Äänen bittinopeus pysyy vakiona, joten äänenlaatu on aina paras. Voit valita videon laadun manuaalisesti napsauttamalla 
          soittimen oikeassa alakulmassa olevaa rataskuvaketta.</p>
          <p>Osassa videoista voi käyttää tekstitystä. Tekstityskielet vaihtelevat esitysten mukaan, mutta suomeksi on vain muutama tarjolla.</p>
                   
      </div>
      <div id=celia class="content-section">
        <h2>Celia - Äänikirjoja lukemisesteisille</h2>
        <p>Osassa Helmet-kirjastoista on mahdollista rekisteröityä erikoiskirjasto <a href="https://www.celia.fi/" target="_blank" 
        aria-label="Celian asiakkaaksi. Linkki avautuu uudessa ikkunassa.">Celian asiakkaaksi.</a></p>
        <p>Celian kirjoja voivat käyttää kaikki, joilla on lukemiseste ja tavallisen tekstin lukeminen hankalaa. Lukemisesteen syynä voi olla esimerkiksi luki- tai oppimisvaikeus, 
        keskittymisvaikeus, lihasheikkous, erilaiset sairaudet, oireet ja vammat, jotka vaikeuttavat tekstin lukemista tai kirjan käsittelyä.</p>
        <p><a href="https://www.celia.fi/palvelut/aanikirjat-yksityishenkiloille/tarkista-oikeus-palveluihin/" target="_blank" 
        aria-label="Lue lisää Celian asiakkuuteen oikeuttavista syistä. Linkki aukeaa uudessa ikkunassa.">Lue lisää Celian asiakkuuteen oikeuttavista syistä.</a></p>
        <p>Celian asiakkaaksi liittymiseen ei kirjastossa vaadita lääkärintodistusta, oma suullinen ilmoitus lukemisesteestä riittää. Celian toiminnan rahoittaa opetus- ja 
        kulttuuriministeriö ja sen käyttö on lainaajille maksutonta.</p>
        <p>Celian kokoelmassa on yli 45 000 äänikirjaa kaiken ikäisille asiakkaille. Valikoimassa on romaaneja, tietokirjoja, satuja, runoja, jännitystä ja viihdettä monilla kielillä sekä 
        oppikirjoja eri kouluasteille.</p>
        
        <h3>Rekisteröidy Celian verkkoasiakkaaksi tai CD-asiakkaaksi</h3>
        <p>Celian verkkoasiakkuus toimii verkon kautta ja palvelun käyttöön tarvitaan verkkoyhteys sekä kuunteluun käytettävä laite kuten tietokone, älypuhelin tai tabletti. 
        Kirjoja kuunnellaan joko selaimessa tai Pratsam Reader -sovelluksessa. Verkkoasiakkaana voit lainata yhteensä 300 kirjaa kuukaudessa.</p>
        <p>Celian CD-asiakkaaksi voit rekisteröityä silloin kun verkkopalveluiden käyttö ei ole mahdollista tai se on vaikeaa. CD-asiakkaana voit liittyä enintään viiteen kirjakerhoon 
        ja saada jokaisesta kerhosta yhden kirjan kuussa.</p>
        <p>Jos sinulla on käytössäsi sähköpostiosoite, voit kerhokirjojen sijasta valita ja tilata haluamasi CD-kirjat itse. Kerhokirjoja ja itse valitsemiasi kirjoja voit lainata 
        kuukaudessa yhteensä 14.</p>
        <p>Varaa aika rekisteröintiä varten lähimmästä Celian palveluita tarjoavasta Helmet-kirjastosta tai kysy lisätietoja lähikirjastostasi.</p>
        <p>Ohjeet Celian äänikirjojen kuunteluun löydät <a href="https://www.celianet.fi/ohjeet/" target="_blank" aria-label="Celianetin sivuilta. Linkki avautuu uudessa ikkunassa.">
        Celianetin sivuilta.</a></p>
      </div>
      <div id="ukk-ekirjat" class="content-section">
          <h2>Usein kysyttyä e-kirjoista</h2>
          <h3>Mitä tarvitsen?</h3>
          <p>Lukemiseen sopivan laitteen (älypuhelin, tabletti tai tietokone), kirjastokortin ja PIN-koodin sekä verkkoyhteyden. Jos lataat kirjoja omalle laitteellesi, tarvitset myös 
          lukuohjelman. Katso ohjeet e-kirjapalveluihin.</p>
          <h3>Mikä on e-kirjojen laina-aika?</h3>
          <p>E-kirjojen maksimi laina-aika on 14 vuorokautta.</p>
          <h3>Voiko e-kirjan lainaa uusia?</h3>
          <p>OverDrive-palvelun lainat voi uusia, jos kirjoihin ei ole varauksia. Muissa e-kirjapalveluissa lainan uusiminen ei ole mahdollista. Voit kuitenkin lainata kirjan 
          uudestaan heti laina-ajan loputtua, jos siihen ei ole varauksia.</p>
          <h3>Näenkö lainaamani e-kirjat omissa tiedoissani kirjaston verkkosivuilla?</h3>
          <p>Et näe. E-kirjapalveluiden kohdalla tiedot näkyvät vain kyseisen palvelun sivustolla tai sovelluksessa kirjautumisen jälkeen.</p>
          <h3>Miksi e-kirjaa on vain 1 kappale?</h3>
          <p>Hankimme e-kirjat samaan tapaan kuin painetut kirjat, eli jokaisesta e-kirjan kappaleesta (lisenssistä) maksetaan erikseen. Määrärahamme eivät riitä tarjoamaan 
          rajatonta lukuoikeutta kaikille yhtäaikaisesti.</p>
          <h3>Voiko palvelua käyttää ulkomailla?</h3>
          <p>Voit lainata e-kirjoja missä tahansa verkkoyhteyden kautta.</p>
          <h3>Voinko jäädyttää varauksen esimerkiksi lomamatkani ajaksi?</h3>
          <p>Voit jäädyttää varauksesi Ellibs- ja OverDrive-palveluissa. Silloin et saa varausta ennen kuin poistat jäädytyksen, mutta säilytät kuitenkin paikkasi varausjonossa.</p>
          <p>Varauksen jäädyttäminen Ellibsissä: Kirjaudu sisään nettisivulla ja napauta Omassa kirjahyllyssä varaamasi kirjan kohdalla ruutua "Lukitse paikkani varausjonossa". 
          Voit määritellä päivämäärän, jolloin jäädytys poistuu, tai poistaa jäädytyksen itse napauttamalla samaa kohtaa. Ellibs-sovelluksessa varauksia ei voi jäädyttää.</p>
          <p>Varauksen lukitseminen OverDrivessä: Kirjaudu sisään, mene kohtaan "Varaukset" ja napauta kohtaa "Lukitse varaus" haluamasi varauksen kohdalla. Tämän jälkeen määrittele 
          jäädytyksen kesto ja kuittaa valinta napauttamalla "Lukitse". Jos haluat muuttaa jäädytyksen kestoa tai poistaa jäädytyksen, napauta varaamasi kirjan alla kohtaa "Edit hold".</p>
          <h3>Miten selainlukeminen eroaa e-kirjan lataamisesta?</h3>
          <p>Selainlukemiseen et tarvitse Adobe-tunnusta tai erillistä lukuohjelmaa. PDF-muotoisia kirjoja ei voi lukea selaimessa. Lue lisää selainlukemisesta.</p>
          <h3>Onko mahdollista lainata ladattavia e-äänikirjoja?</h3>
          <p>Kyllä, Ellibs- ja OverDrive-palveluiden äänikirjoja voi ladata palveluiden omiin mobiilisovelluksiin.</p>
          <h3>Voiko kirjaston kirjoja lukea e-kirjan lukulaitteilla?</h3>
          <p>Kirjaston e-kirjoja voi lainata useimmilla myynnissä olevilla e-kirjan lukulaitteilla. Lukulaitteen täytyy tukea EPUB- ja PDF-tiedostomuotoja sekä Adoben 
          DRM-suojaustekniikkaa. Kindlellä ei voi lukea kirjaston e-kirjoja, sillä se käyttää Amazonin omaa tekijänoikeussuojausta ja tiedostomuotoa.</p>
          <h3>Miksi e-kirjan tiedoissa ei kerrota sivumäärää?</h3>
          <p>E-kirjan sivumäärä vaihtelee tekstin koon ja käytettävän laitteen näytön koon mukaan.</p>
          <h3>Kirjastokorttini vaihtui. Mitä e-kirjalainoilleni ja -varauksilleni tapahtuu?</h3>
          <p>Jos kirjastokorttisi vaihtuu, et pääse lukemaan e-kirjalainojasi selaimessa tai hallinnoimaan e-kirjavarauksiasi, sillä e-kirjojen lainat ja varaukset 
          eivät automaattisesti siirry uudelle kortille. Lukuohjelmaan tai -sovellukseen ladattuja kirjoja voit kuitenkin edelleen lukea laina-ajan loppuun asti.</p>
          <p>OverDriven ja Ellibsin lainat ja varaukset on mahdollista siirtää vanhalta kortilta uudelle. Siirtoa voit pyytää lähettämällä sähköpostin osoitteeseen hki.ekirja@hel.fi. 
          Kerro viestissäsi vanhan ja uuden kirjastokorttisi numerot. Huom! muista aivan ensiksi kirjautua uudella kirjastokortin numerollasi palveluun.</p>
          <h3>Olen menettänyt lainausoikeuteni. Voinko kuitenkin lainata e-kirjoja?</h3>
          <p>Jos olet menettänyt lainausoikeutesi, et pysty lainaamaan e-kirjoja OverDrive- tai Ellibs-palvelusta. Jos saat ilmoituksen lainauksen estosta, kirjaudu omiin tietoihisi 
          Helmet-sivustolla ja tarkista sakkojesi määrä tai kohta Viestit.</p>
          <h3>Miten teen hankintaehdotuksen e-kirjasta?</h3>
          <p>Voit ehdottaa e-kirjan hankintaa Helmet-kirjastojen hankintaehdotuslomakkeen kautta.</p>
          <h3>Miksi en pääse kirjautumaan palveluun?</h3>
          <p>Tarkista, että olet kirjoittanut kirjastokortin numeron (ilman välilyöntejä) ja PIN-koodin oikein. Jos saat ilmoituksen lainauksen estosta tai et pääse kirjautumaan 
          myöskään omiin tietoihisi Helmet-sivustolla, pyydä apua kirjaston asiakaspalvelusta.</p>
          <h3>Mistä saan tukea palvelun ongelmatilanteissa?</h3>
          <ul class="list-bullets">
              <li><a href="https://www.ellibslibrary.com/fi/instructions" target="_blank" aria-label="Ellibs-palvelun ohjeet. Linkki aukeaa uudessa ikkunassa.">
              Ellibs-palvelun ohjeet</a></li>
              <li><a href="https://help.overdrive.com/" target="_blank" aria-label=". Linkki aukeaa uudessa ikkunassa">OverDrive-palvelun ohjeet</a></li>
          </ul>
          <p>Ongelmatilanteissa voit ottaa yhteyttä sähköpostitse osoitteeseen hki.ekirja@hel.fi. Kuvaathan ongelman ja kerrot käyttämäsi laitteet ja ohjelmistot. 
          Ellibs-palvelun ongelmista voit kysyä suoraan Ellibsin tuesta osoitteesta support@ellibs.com.</p>
          <p>Voit aina kysyä apua myös henkilökunnaltamme kirjastoissa.</p>
          <h3>Mitä teen, kun palvelun nettisivu ei toimi oikein?</h3>
          <p>Kokeile eri selaimella. Suosittelemme käyttämään e-kirjapalveluita Chrome-, Firefox- tai Safari-selaimella. Tyhjennä selaimen välimuisti ja kokeile uudestaan. 
          Evästeet on sallittava.</p>
          <h3>Mitä teen, kun e-kirja tai äänikirja ei toimi oikein?</h3>
          <p>Jos kirjaan ei ole varauksia, palauta se ja lainaa uudelleen. Jos olet ladannut kirjan omalle laitteellesi, kokeile palauttaa tai poistaa se lukuohjelmasta ja ladata se 
          uudelleen. Jos luet tai kuuntelet selaimessa, kokeile käyttää eri selainta tai tyhjentää selaimen välimuisti. Jos käytät e-kirjapalvelun sovellusta mobiililaitteella, 
          kokeile poistaa sovellus ja asentaa se uudestaan.</p>
          <h3>Mitä teen, kun e-kirjan lataaminen ei onnistu?</h3>
          <p>Jos ongelma ilmenee nettiselaimessa kirjaa ladattaessa, kokeile eri selaimella tai tyhjennä selaimen välimuisti ja yritä uudestaan.</p>
          <p>Jos ongelma ilmenee lukuohjelmassa, tarkista, että ohjelmaan on tallennettu Adobe-tunnus. Kokeile ladata kirja uudestaan. Jos ohjelma antaa virheilmoituksen, 
          sen tekstillä hakemalla voit löytää neuvoja netistä.</p>
          <h3>Miksi varaukseni ovat hävinneet?</h3>
          <p>Jos kirjastokorttisi on vaihtunut, ongelma johtuu siitä, koska korttisi numero on vaihtunut. E-kirjapalvelussa tekemäsi lainat ja varaukset yhdistyvät siihen kortin 
          numeroon, jolla kirjauduit sisään.</p>
          <p>OverDriven sekä Ellibsin lainat ja varaukset on mahdollista siirtää vanhalta kortilta uudelle. Siirtoa voit pyytää lähettämällä sähköpostin osoitteeseen hki.ekirja@hel.fi. 
          Kerro viestissäsi vanhan ja uuden kirjastokorttisi numerot.</p>
          </div>
        <div id="ukk-elehdet" class="content-section">
            <h2>Usein kysyttyä e-lehdistä</h2>
            <h3>Mistä löydän tiedon kaikista kirjaston tarjoamista e-lehdistä?</h3>
            <p>Mitään lehtiä ei ole luetteloitu Helmet-tietokantaan. PressReaderin lehtivalikoiman sekä ePressin lehtivalikoimat näet vain palveluiden omilta sivuilta.</p>
            <h3>Kuinka pitkälle sanomalehtien arkistot ulottuvat?</h3>
            <p>Epressin arkisto on 2 vuotta. PressReaderissa arkiston pituus vaihtelee, mutta lehdet ovat luettavissa yleensä 2–4 kuukautta ilmestymispäivästään.</p>
            <h3>Milloin aikakauslehtien kokoelmaa päivitetään?</h3>
            <p>Kirjasto ei pysty vaikuttamaan PressReaderin lehtikokoelmiin. Epressin aikakauslehtivalikoimaa päivitetään noin kerran vuodessa.</p>
            <h3>Miksi PressReader kysyy joskus maksua lehdistä?</h3>
            <p>Jos kirjautuminen ei ole voimassa, PressReader pyytää maksua lehdistä. Voit aktivoida kirjautumisen kahdella tavalla:</p>
            <ol>
                <li>Mene käymään kirjastossa, kirjaudu laitteellasi kirjaston langattomaan verkkoon ja avaa PressReaderin nettisivu tai sovellus. Näin saat palvelun taas 
                  käyttöösi useiksi viikoiksi.</li>
                <li>Kirjaudu palveluun kirjastokortilla ja PIN-koodilla. Varmista myös, että HotSpot-käyttö on päällä: Jos käytät PressReaderia selaimessa, tarkista että 
                  kahvikuppi-ikoni sivuston yläreunassa on vihreä. Jos se ei ole, klikkaa sitä ja näin aktivoi HotSpot. Jos käytät PressReaderia sovelluksessa, mene asetuksissa 
                  kohtaan HotSpots ja laita HotSpot päälle. Jos lehtiä ei sittenkään pääse lukemaan, kirjaudu ulos ja uudestaan sisään.</li>
            </ol>
            <h3>Miksi PressReaderissa lukemani lehden tilaus ei ole jatkunut?</h3>
            <p>PressReaderin lehtiä tulee ja häviää kokoelmasta kesken vuottakin. Esimerkiksi kustantaja saattaa ottaa lehtensä pois palvelusta. Kirjasto ei saa tästä mitään 
            ilmoitusta eikä voi vaikuttaa kokoelman muutoksiin.</p>
            <h3>Miksi kirjastokortilla kirjautuminen ei onnistu PressReaderin sovelluksessa?</h3>
            <p>Jos sovellus ei tarjoa mahdollisuutta kirjautua kirjastokortilla, toimi näin: Mene selaimella PressReaderin nettisivulle, kirjaudu kirjastokortin numerolla ja 
            PIN-koodilla, klikkaa nimeäsi ja sitten kohtaa Manage account. Lisää tietoihisi sähköpostiosoite ja salasana. Käynnistä sovellus ja kirjaudu sisään käyttämällä 
            tunnuksena samaa sähköpostiosoitetta ja salasanaa.</p>
            <h3>Saan PressReaderiin kirjautuessani ilmoituksen, että tunnuksellani on jo kirjauduttu sisään. Mitä teen?</h3>
            <p>Joissakin tapauksissa PressReader ilmoittaa sisäänkirjautumisen yhteydessä, että tunnus on jo käytössä. Sisäänkirjautuminen ei tällöin onnistu. Ongelma ratkeaa, 
            kun tyhjennät käyttämäsi nettiselaimen välimuistin ja poistat evästeet.</p>
          </div>










      </div>
   </div>
</div>


