<? $this->headTitle($this->translate('Instructions for e-materials')); $this->content()->setHeading($this->translate('Instructions for e-materials'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>As Helmet libraries' customer you have access to two e-book services and three e-audiobook services.</p>
        <ul class="list-bullets">
          <li>Finnish e-books and e-audiobooks – <a href="https://www.ellibslibrary.com/en/helmet" target="_blank" aria-label="Ellibs. The link opens in a new window.">Ellibs</a></li>
          <li>Foreign e-books and e-audiobooks – <a href="https://helmet.overdrive.com/" target="_blank" aria-label="Overdrive. The link opens in a new window.">OverDrive</a></li>
          <li>English e-audiobooks – <a href="https://helsinkilib.naxosspokenwordlibrary.com/" target="_blank" aria-label="Naxos Spoken Word Library. The link opens in a new window.">
            Naxos Spoken Word Library</a></li>
        </ul>
        <p>To borrow e-books, you will need a Helmet library card and a PIN code, a device suitable for reading, and internet access. If you want to download e-books onto your own device, you 
        will also need an app or a reader application. Below you will find device specific instructions.</p>
      </div>
     <div id="ebooks-and-audiobooks" class="content-section">
        <h2>Instructions for e-books and audiobooks</h2>
        <h3>Read books in a browser</h3>
        <p>The easiest way to read e-books is directly in a web browser. Then you do not need any separate e-book reader software or application on your device, nor any other user account 
        besides your library card and PIN code.</p>
        <p>Browser reading is possible on computers and mobile devices with an internet connection and the latest version of your browser. We advise you to use either Firefox, Chrome or 
        Safari depending on your device.</p>
        <p>Most e-books are browser readable. However, the books in PDF format cannot be read in browsers. If browser reading is not possible, borrowing alternatives do not include 
        ”Read” or "Read in browser". These books you can read only by downloading them onto your device.</p>
        
        <h3>Listen to audiobooks</h3>
        <p>You can listen to e-audiobooks in the browser or in the different services' own applications. You can download audiobooks to an app and listen to them without an internet 
        connection. See below for more information about the apps.</p>
        <p>Also check out the <a href="http://www.helmet.fi/fi-FI/content/131798/2">instructions for audiobooks in Naxos Spoken Word Library</a>.</p>
        
        <h3>Read and listen in the app</h3>
        <p>All e-book services have apps designed for iOS and Android mobile devices. The apps are free and you can download them from your device’s app store. Depending upon the e-book 
        service, the app might not include e.g. e-books or some of the titles in PDF format. You can find all titles, however, on the website of each service.</p>
        <p>You can borrow and use Finnish e-books and audiobooks in the <strong>Ellibs app</strong>. Once you have downloaded an audiobook to the app or borrowed an e-book, you can also use
        them in the app when offline.</p>
        
        <p><strong>OverDrive</strong> service has an app called <strong>Libby.</strong> It has excellent usability and natutally works both on ebooks and e-audiobooks.</p>
        
        <h3>Downloading e-books onto your own device</h3>
        <p>When you have downloaded e-books onto your own device, you can read them without internet connection. All the e-books available through the Helmet library are copyright 
        protected and can only be opened with a reader application that recognizes the copyright protection used. The reader application you need depends on your device. You can read 
        further instructions below.</p>
        <p><strong>E-audiobooks can only be downloaded to each service's own app.</strong></p>
        <p>We recommend using Chrome, Firefox or Safari browser. If you have an iOS device, you need to download large e-audiobooks (over 100 MB) via wifi connection.</p>
        
        <h3>Adobe account</h3>
        <p>In addition to the reader application, you will need an Adobe account, which allows you to open the protected e-book file. We advise you to save the Adobe user ID to the reader 
        app before trying to download any books. You can create an Adobe account free of charge on the Adobe website.</p>
        <p><a href="https://adobe.ly/2GAn56h" target="_blank" aria-label="Create an Adobe account. The link opens in a new window.">Create an Adobe account</a><br>
        <a href="https://helpx.adobe.com/x-productkb/global/adobe-id-account-change.html" target="_blank" aria-label="More information about the Adobe account. The link opens in a new window.">
        More information about the Adobe account</a></p>
        <p>When you launch the e-book reader application for the first time, authorize the app with your Adobe user ID (email and password). The authorization is done only once and in the 
        future, the app opens automatically with your user ID. You can use the same Adobe user ID to log onto six different devices or reader applications.</p>
        
        <h3>Downloading e-books onto tablets or smartphones</h3>
        <p>With iOS and Android devices, you can download e-books onto the Aldiko Book Reader application if you want. Download the app from your device’s app store and authorize it with your 
        Adobe user ID. OverDrive’s books and audiobooks can also be downloaded into OverDrive’s own apps which do not need an Adobe account.</p>
        <p>On Windows tablets and phones you cannot use OverDrive app Libby but you can use Libby app in your browser: www.libbyapp.com.</p>
        
        <h3>Downloading e-books to computers</h3>
        <p>With Windows and Mac computers, you can download e-books onto Adobe Digital Editions ebook reader software. You must first authorize it with your Adobe user ID.</p>
        <p>
          <a href="https://www.adobe.com/solutions/ebook/digital-editions/download.html" target="_blank" aria-label="Download Adobe Digital Editions. The link opens in a new window.">
          Download Adobe Digital Editions</a><br>
          <a href="https://www.ellibslibrary.com/en/instructions" target="_blank">Read the Adobe Digital Editions installing instructions on the Ellibs website</a></p>
          
        <h3>E-book readers</h3>
        <p>You can read library's e-books with most of the e-reader devices currently available on the market. Kindle is incompatible with library’s e-books, as it uses Amazon's own 
        file and digital copyrights protection formats.</p>
        <p>E-books can be copied to e-book readers via your computer or directly from the particular e-book service, if your e-book reader has an internet connection and the possibility to 
        download from the internet. Please check the instructions in your e-book reader's manual.</p>
        <p>If you copy e-books to an e-book reader via your computer, you must first install Adobe Digital Editions to the computer. To authorize the Adobe Digital Editions software, you will 
        need an Adobe account. The software must be authorized with the same Adobe user ID you used to authorize your e-book reader with. Your e-book reader's manual will have detailed 
        instructions on how to transfer e-books to your reader.</p>
        
        <h3>Support</h3>
        <ul class="list-bullets">
          <li><a href="https://www.ellibslibrary.com/en/instructions" target="_blank" aria-label="Instructions for Ellibs service. The link opens in a new window.">
            Instructions for Ellibs service</a></li>
          <li><a href="https://help.overdrive.com/" target="_blank" aria-label="Instructions for OverDrive service. The link opens in a new window.">Instructions for OverDrive service</a></li>
        </ul>
        <p>If you run into any problems not covered by the instructions, you can reach us by email at <a href="mailto:hki.ekirjat@hel.fi">hki.ekirjat@hel.fi</a>. Please describe the problem 
        and also tell us what devices and software or apps you were using. In problems pertaining to Ellibs, you can contact Ellibs’ technical support directly at 
        <a href="mailto:support@ellibs.com">support@ellibs.com</a>.</p>
      </div>
      <div id="e-magazines" class="content-section">
        <h2>Instructions for remote access of e-magazines</h2>
        <p>You can read the newspapers and magazines available through PressReader in a library as well as outside the library using your own device.</p>
        <h3>PressReader</h3>
        <p>PressReader contains newspapers and magazines from around the world. You can read the publications either in your device’s browser or in the PressReader mobile app. To log in, 
        you need your Helmet library card number and PIN code.</p>
        <h4>Using PressReader in a web browser</h4>
        <p>Open the <a href="https://www.pressreader.com/catalog" target="_blank" aria-label="PressReader website. The link opens in a new window."> PressReader website</a>, 
        click Sign in and then choose the Library or group option. Next choosefrom the Select libraries list Library – Helmet libraries (offsite)
        and type in your library card number and PIN code. Wait a moment until a PressReader HotSpot window opens.</p>
        <p>You can browse the collection by tapping Select publication .Now you can browse the magazines according to country, language, category or publication type, or search by 
        title. Access the magazine by tapping on its cover.</p>
        
        <h4>Using PressReader via mobile app</h4>
        <p>Download thePressReader app from the App Store or Play store. If you have previously downloaded it, make sure you have the latest, updated version.</p>
        <p>Tap on Sign in, then tap Library or an icon resembling a library card. Choose from the Select libraries list Library – Helmet libraries (offsite) and enter your 
        library card number and PIN code. Wait a moment until a PressReader HotSpot window opens.</p>
        <p>After this, you can browse the selection, read magazines and newspapers as well as download them for offline use. The HotSpot must be active during downloading. 
        If the coffee cup symbol on the page is not green, activate the HotSpot in the app's settings.</p>
        <p>You can also download newspapers/magazines in the libraries’ wireless network in Helsinki and Espoo. This way you do not need to sign in to the PressReader app– 
        you just open the app and you are granted access automatically in the libraries’ wireless network.</p>
      </div>
      <div id="naxos" class="content-section">
        <h2>Audiobooks in different languages</h2>
        <p>In Naxos Spoken Word Library, you will find thousands of e-audiobooks. On offer are fiction and non-fiction titles mostly in English, including classics, memoirs, business 
        literature, and language courses.</p>
        <p>The service comprises mostly English audiobooks and radio plays as well as some French, German and Portuguese literature. There are several famous actors among the audiobook 
        readers. You can browse the collection by category, author or reader.</p>
        
        <h3>How to use Naxos Spoken Word Library</h3>
        <p>You can listen to NSWL e-audiobooks in a browser on your computer, tablet or smart phone. Log in with your library card number. Choose the book you want to listen to and start 
        listening straight away. You do not need to borrow or place holds on the books, they are all available all the time. You need to have internet access on while you are listening.</p>
        <p><a href="https://helsinkilib.naxosspokenwordlibrary.com" target="_blank" aria-label="Log in to Naxos Spoken Word Library. The link opens in a new window.">
        Log in to Naxos Spoken Word Library</a></p>
        <p>Up to 20 users can be logged in simultaneously to Naxos Spoken Word. Unfortunately, a small portion of the titles in Naxos Spoken Word Library cannot be accessed in Finland 
        due to copyright restrictions.</p>
        <p>On computers we recommend using the latest versions of Chrome, Firefox or Safari browsers. The browser must also support Flash. More detailed system requirements are available in 
        the <a href="https://helsinkilib.naxosspokenwordlibrary.com/faqs.asp" target="_blank" aria-label="Naxos Spoken Word Library’s FAQ section. The link opens in a new window.">
        Naxos Spoken Word Library’s FAQ section</a>.</p>
        
        <h3>Naxos Spoken Word also works on mobile devices</h3>
        <p>On iOS and Android devices, you can use the service via the NSWL application which you can get from your application store. You can also download e-audiobooks to the app for 
        listening offline. To use the apps, you need to create a personal user account. Do the following:</p>
        <ol class="list-bullets">
          <li>Go to the<a href="https://helsinkilib.naxosspokenwordlibrary.com"> Naxos Spoken World Library website.</a></li>
          <li>Log in with your Helmet library card number. Type the number without spaces.</li>
          <li>Click Create Student/member account link. Give the required data. You will get a confirmation by email, follow the instructions.</li>
          <li>Download the Naxos Spoken Word Library app to your mobile device.</li>
          <li>Log in to the app with the user account you created and enjoy the music.</li>
          <li>Remember to log outfrom the app when you are done with listening. The number of simultaneous users is limited.</li>
        </ol>
        <p>If you have not used the app for some time, signing in may fail. In that case, you will be sent an email to the email address you chose as your user name. Follow the 
        instructions in the email to reactivate the account.</p>
        
        <h3>Bookmark to continue listening later</h3>
        <p>When you have found a good e-audiobook from NSWL, you can choose to listen to the whole book (select all) or a chapter at a time. If you want to continue listening later, you 
        can bookmark the chapter by clicking the bookmark symbol. The bookmark is set to the beginning of the chapter you were just listening to.</p>
        <p>You can access the bookmarks you have created from the Bookmarks tab.</p><p>When you finish listening, log out from the service or close the NSWL app from your device’s cache. 
        In this way you enable other users to log in by freeing up the license for the next user.</p>
      </div>
   </div>
</div>


