<? $this->headTitle($this->translate('Instruktioner för tjänsterna som erbjuder e-böcker och e-ljudböcker')); $this->content()->setHeading($this->translate('Instruktioner för tjänsterna som erbjuder e-böcker och e-ljudböcker'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim" class="content-section">
        <p>Som låntagare vid Helmet-biblioteket kan du använda sammanlagt tre olika tjänster för e-böcker och e-ljudböcker.</p>
        <ul class="list-bullets">
          <li>Inhemska e-böcker och e-ljudböcker – <a href="https://www.ellibslibrary.com/sv/helmet" target="_blank" aria-label="Ellibs. Länken öppnas i ett nytt fönster.">Ellibs</a></li>
          <li>Utländska och svenska e-böcker och e-ljudböcker – <a href="https://helmet.overdrive.com/" target="_blank" aria-label="OverDrive. Länken öppnas i ett nytt fönster.">OverDrive</a></li>
          <li>E-ljudböcker på engelska – <a href="https://helsinkilib.naxosspokenwordlibrary.com/" target="_blank" aria-label="Naxos Spoken Word Library. Länken öppnas i ett nytt fönster.">
          Naxos Spoken Word Library</a></li>
        </ul>
        <p>För att låna e-böcker behöver du ett bibliotekskort och en PIN-kod, en lämplig apparat samt nätförbindelse.</p>
        <p>Om du laddar ner böcker på din egen apparat behöver du också ett läsprogram och en Adobe-kod. Nedan hittar du instruktioner enligt apparat.</p>
      </div>
     <div id="e-bocker" class="content-section">
        <h2>E-böcker och e-ljudböcker</h2>
        <h3>Läs på webbläsaren</h3>
        <p>Det är lättast att läsa e-böcker direkt på webbläsaren. Då behöver du inget särskilt läsprogram och inga andra koder än ditt bibliotekskorts nummer och PIN-kod.</p>
        <p>För att kunna läsa på webbläsaren behöver du en dator eller en mobil apparat med nätförbindelse, samt en uppdaterad webbläsare. Vi rekommenderar webbläsarna Firefox, 
        Chrome och Safari.</p><p>De flesta e-böcker, utom böcker som har sparats i PDF-format, kan läsas på en webbläsare. Om boken inte kan läsas på webbläsaren kan du inte se orden ”Läs” 
        eller ”Läs på webbläsaren” i dess information. Sådana böcker kan endast läsas genom att ladda ner dem på den egna apparaten.</p>
        
        <h3>Lyssna på ljudböcker</h3>
        <p>Du kan lyssna på ljudböcker via webbläsaren eller på tjänstens egen app. Du kan ladda ner ljudböckerna på appen så att du kan lyssna på dem utan nätförbindelse. Mera information 
        om apparna nedan.</p><p>Se även instruktionerna för ljudböcker i <a href="#pa-engelska">Naxos Spoken Word Library</a>.</p>
        <p>Se instruktioner för <a href="http://www.helmet.fi/sv-FI/content/54104/3" target="_blank">Celias talböcker för den som har svårt att läsa</a>.</p>
        
        <h3>Läs och lyssna via en app</h3>
        <p>Alla tjänster för e-böcker har appar som fungerar på iOS och Android mobila apparater. Apparna kan avgiftsfritt laddas ned från en appbutik. En del av verken som ingår i en tjänst 
        fungerar inte i tjänstens app. Det kan vara fråga om e-böcker eller vissa verk i PDF-format. Alla verk som ingår i en tjänst kan hittas via tjänstens webbsida.</p>
        <p>Via appen Ellibs kan du låna och läsa både e-böcker och e-ljudböcker. Du kan ladda ner verken i mobilappen och läsa eller lyssna på dem utan nätförbindelse.</p>
        <p>Tjänsten OverDrive kan användas via appen Libby. Libby är utmärkt att använda. Appen erbjuder många unika funktioner till exempel taggar för att spåra önskelistor och 
        favoritläsningar, push-meddelanden, ljudbokskompatibilitet med Apple CarPlay och Android Auto och direkt stöd i appen. Du kan även ladda ner böcker för att läsas utan nätförbindelse 
        via appen.</p>
        
        <h3>Att ladda ner e-böcker på din egen apparat</h3>
        <p>Du kan ladda ner e-böcker på din egen apparat och sedan läsa dem utan nätförbindelse. Alla e-böcker som kan lånas via Helmet-biblioteket är copyrightskyddade, så de kan endast 
        öppnas via ett läsprogram som identifierar skyddet. Olika apparater använder olika program, se noggrannare information nedan. Då lånetiden är slut kan boken inte längre öppnas i 
        läsprogrammet.</p><p>E-böckerna i OverDrive kan laddas ner på appen Libby. Ljudböcker kan endast laddas ner på tjänsternas egna appar.</p>
        <p>Vi rekommenderar att du använder webbläsarna Firefox, Chrome eller Safari då du laddar ner e-böcker. I apparater med iOS lönar det sig att ladda ner stora e-boksfiler via wifi.</p>
        <h3>Adobes användarkod</h3>
        <p>Utöver ett läsprogram behöver du en Adobe-användarkod som tillåter att du öppnar en copyrightskyddad bok. Det lönar sig att spara koden i ditt läsprogram innan du laddar ner e-boken. 
        Det kostar ingenting att skapa en kod och du kan göra det på Adobes webbplats.</p>
        <p><a href="https://adobe.ly/2CNb77D" target="_blank" aria-label="Skapa en Adobe-kod. Länken öppnas i ett nytt fönster.">Skapa en Adobe-kod</a></p>
        <p><a href="https://helpx.adobe.com/fi/x-productkb/global/adobe-id-account-change.html" target="_blank" aria-label="Mera info om Adobe-koden. Länken öppnas i ett nytt fönster.">
        Mera info om Adobe-koden</a></p>
        <p>Då ett läsprogram första gången startar på din apparat ska du auktorisera programmet med din Adobe-kod och ditt lösenord. Detta gör du endast en gång, i fortsättningen öppnas 
        programmet automatiskt med dina koder. Du kan använda samma Adobe-kod på sex olika apparater eller program.</p>
        
        <h3>Att ladda ner e-böcker på en surfplatta eller smarttelefon</h3>
        <p>På Android- eller iOS-apparater kan du ladda ner e-böcker från Ellibs på programmet Aldiko Book Reader. Ladda ner programmet från en appbutik och spara därefter din Adobe-kod i 
        programmet. E-böcker och e-ljudböcker i tjänsten OverDrive kan endast laddas ner i tjänstens egen app, vilken inte kräver Adobe-kod.</p>
        <p>Om du har en surfplatta eller mobiltelefon med Windows, kan du inte läsa OverDrives e-böcker på appen Libby, men du kan använda Libby via webbläsaren i addressen libbyapp.com.</p>
        
        <h3>Att ladda ner e-böcker på en dator</h3>
        <p>På datorer med Windows och Mac kan du ladda ner läsprogrammet Adobe Digital Editions. Du måste spara en Adobe-kod i programmet.</p>
        <p><a href="http://www.adobe.com/fi/solutions/ebook/digital-editions/download.html" target="_blank" aria-label="Ladda ner läsprogrammet Adobe Digital Editions. Länken öppnas i ett nytt fönster.">
        Ladda ner läsprogrammet Adobe Digital Editions</a></p>
        <p><a href="https://www.ellibslibrary.com/sv/instructions" target="_blank">Se instruktionerna hur du installerar läsprogrammet på e-boktjänsten Ellibs webbplats</a></p>
        
        <h3>Läsapparater för e-böcker</h3>
        <p>Du kan läsa bibliotekets e-böcker på de flesta läsapparater som är avsedda för e-böcker. Via läsplattan Kindle kan dy inte läsa bibliotekets e-böcker, eftersom den endast 
        stöder Amazons egna copyrightskydd och filformat.</p>
        <p>Ifall din läsapparat har nätförbindelse och möjlighet att ladda ner från nätet kan du kopiera e-böcker till läsapparaten via en dator eller direkt från en e-bokstjänst. Se 
        apparatens manual.</p>
        <p>Om du kopierar boken via en dator till din läsapparat måste du installera Adobe Digital Editions på datorn. Du behöver också en Adobe-kod med vilken du auktoriserar programmet. 
        Programmet skall auktoriseras med samma Adobe-kod som din läsapparat. I manualen för din läsapparat ser du hur e-boken överförs till apparaten.</p>
        
        <h3>Instruktioner och stöd</h3>
        <p><a href="https://www.ellibslibrary.com/sv/instructions" target="_blank" aria-label="Instruktioner för tjänsten Ellibs. Länken öppnas i ett nytt fönster.">
        Instruktioner för tjänsten Ellibs</a></p>
        <p><a href="https://help.overdrive.com/" target="_blank" aria-label="Instruktioner för tjänsten OverDrive. Länken öppnas i ett nytt fönster.">
        Instruktioner för tjänsten OverDrive</a></p>
        <p><a href="https://youtu.be/Ee6xbs0GBVw" target="_blank" aria-label="OverDrive-video på finska. Länken öppnas i ett nytt fönster.">OverDrive-video på finska</a></p>
        <p>Om du får problem ta kontakt på adressen <a href="mailto:hki.ekirja@hel.fi">hki.ekirja@hel.fi</a>. Beskriv problemet och berätta vilka apparater och program du använder. Om 
        problemen gäller tjänsten Ellibs kan du också ta kontakt med tjänstens stödfunktion på adressen <a href="mailto:support@ellibs.com">support@ellibs.com</a>.</p>

      </div>
      <div id="esim2" class="content-section">
        <h2>Instruktioner för e-tidningstjänsterna på distans</h2>
        <p>Du kan läsa inhemska tidskrifter och utländska tidningar och tidskrifter hemma eller annanstans utanför biblioteket.</p>
        <h3>Epress (eMagz)</h3>
        <p>Det finns över 80 tidningar i ePress, alla är på finska.</p>
        <h4>Att använda ePress på webbläsaren</h4>
        <p>Öppna <a href="https://helmet.emagz.fi/ext/login/helmet" target="_blank" aria-label="ePress. Länken öppnas i ett nytt fönster.">ePress</a> och logga in med ditt 
        Helmet-bibliotekskort och PIN-kod. Du kan läsa tjänstens tidskrifter i alla vanliga webbläsare. Använd läsarens nyaste version.</p>
        <p>Samma tidskrift kan samtidigt läsas av 1-10 personer. Läsarlicenserna varierar från tidskrift till tidskrift. Om du inte kan läsa den tidning du vill, vänta en stund och 
        försök på nytt.</p>
        <p>Du kan läsa en tidning högst två timmar åt gången, därefter loggar systemet ut dig automatiskt. Systemet loggar ut dig efter 15 minuter om du är inloggad, men inte 
        använder tjänsten.</p>
        
        <h3>PressReader</h3>
        <p>PressReader innehåller utländska tidningar och tidskrifter. Du kan läsa dem i webbläsaren eller i en mobilapp i din egen apparat. För att logga in behöver du ditt 
        bibliotekskorts nummer och PIN-kod.</p>
        <h4>Att använda PressReader på webbläsaren</h4>
        <p>Öppna webbplatsen <a href="https://www.pressreader.com/catalog" target="_blank" aria-label="PressReader. Länken öppnas i ett nytt fönster.">PressReader</a>, klicka på Sign in 
        och tryck på alternativet Library or group. Därefter väljer du Library - Helmet libraries (offsite) på listan Select Library. Skriv in ditt bibliotekskorts nummer och PIN-kod. 
        Om en stund öppnas fönstret PressReader HotSpot.</p>
        <p>Du kan bläddra i tidskriftsutbudet genom att klicka på Select Publication. Du kan också hitta tidskrifterna via knappen Publications. Därefter kan du bläddra enligt land, språk, 
        ämnesområde eller typ av tidskrift. Du kan också söka på tidskriftens namn. Tidskriften öppnas då du klickar på pärmbilden.</p>
        
        <h4>Att använda PressReader på en app</h4>
        <p>Sök fram den avgiftsfria appen PressReader på App Store eller i Google Play-butiken. Ifall du redan har laddat ner appen ska du kontrollera att du har den nyaste versionen!</p>
        <p>Öppna appen på Sign in och klicka på alternativet Library eller på en ikon som liknar ett bibliotekskort. Därefter väljer du Library - Helmet libraries (offsite) på listan 
        Select Library. Skriv in ditt bibliotekskorts nummer och PIN-kod. Om en stund öppnas fönstret PressReader HotSpot.</p>
        <p>Därefter kan du bläddra i tidningsutbudet, läsa publikationer eller ladda ner dem för att läsas utan nätförbindelse. När du laddar ner publikationer måste HotSpot vara aktiv. 
        Tryck på Publications. Om kaffekoppsymbolen i övre kant är inte grön, aktivera HotSpotten i appens inställningar.</p>
        <p>Du kan fortfarande ladda ner PressReader i de trådlösa nätverken i biblioteken i Helsingfors och Esbo. Då behöver du inte logga in på appen – det räcker att du öppnar 
        den i bibliotekets trådlösa nätverk.</p>
        
        <p>Om det går inte att logga in på appen med bibliotekskortet, gör så här: gå in på PressReaders webbplats, logga in med ditt bibliotekskorts nummer och PIN-kod, klicka 
        på ditt namn och därefter på Manage account. Skriv in din e-postadress och ett lösenord. Starta appen och logga in med din e-postadress och lösenordet.</p>

      </div>
      <div id="pa-engleska" class="content-section">
        <h2>E-ljudböcker på engelska</h2>
        <p>I tjänsten <a href="https://helsinkilib.naxosspokenwordlibrary.com" target="_blank" aria-label="Naxos Spoken Word. Länken öppnas i ett nytt fönster.">Naxos Spoken Word</a> 
        finns tusentals e-ljudböcker i huvudsak på engelska. Här finns skön- och facklitteratur: klassiker, memoarer, affärslitteratur och språkkurser.</p>
        <p>Största delen av ljudböckerna och hörspelen på Naxos Spoken Word är på engelska. Bland uppläsarna finns flera kända skådespelare. Dessutom finns en del litteratur på franska, 
        tyska och portugisiska. Du kan bläddra i innehållet enligt ämne, författare eller uppläsare.</p>
        <p>Använd Naxos Spoken Word via webbläsaren på en dator, surfplatta eller smarttelefon. Logga in med ditt bibliotekskorts nummer. Välj ljudbok och du kan genast börja lyssna. 
        Du behöver inte låna eller reservera ljudböckerna. Medan du lyssnar måste nätuppkopplingen fungera.</p>
        <p><a href="https://helsinkilib.naxosspokenwordlibrary.com" target="_blank" aria-label="Logga in på Naxos Spoken Word Library. Länken öppnas i ett nytt fönster.">
        Logga in på Naxos Spoken Word Library</a></p>
        <p>Endast 20 personer kan samtidigt vara inloggade i Naxos Spoken Word. En del av titlarna kan inte avlyssnas Finland av upphovsrättsliga skäl.<br>
        Om du använder en dator rekommenderar vi att du använder en så ny version av webbläsarna Internet Explorer, Chrome, Firefox eller Safari som möjligt. Webbläsaren bör stöda Flash. 
        Se noggrannare tekniska krav på <a href="https://helsinkilib.naxosspokenwordlibrary.com/faqs.asp" target="_blank" aria-label="Naxos Spoken Word Librarys FAQ. Länken öppnas i ett nytt fönster.">
        Naxos Spoken Word Librarys FAQ</a>.</p>
        <h4>Naxos Spoken Word fungerar också på mobilen</h4>
        <p>På apparater med iOS och Android kan du använda appen NSWL som finns i apparatens appbutik. Du kan ladda ner ljudböcker i appen och lyssna på dem senare utan nätförbindelse. 
        Du måste skapa ett personligt konto för att kunna använda appen NSWL Gör såhär:</p>
        <ol class="list-bullets">
          <li>Gå till Naxos Spoken Words hemsida</li>
          <li>Skriv in numret på ditt Helmet-bibliotekskort (utan mellanslag) och klicka på Login.</li>
          <li>Klicka på länken Student/member playlists account. Skriv in dina uppgifter. Du får en bekräftelse till din e-post. Följ instruktionerna.</li>
          <li>Ladda ner appen NSWL på din mobila apparat.</li>
          <li>Logga in i appen och njut av ljudböckerna. Kom ihåg att logga ut när du slutar lyssna. Endast en begränsad mängd lyssnare kan samtidigt vara inloggade i tjänsten.</li>
        </ol>
        <h4>Fortsätt lyssna med hjälp av bokmärke</h4>
        <p>När du lyssnar på en ljudbok kan du välja mellan att lyssna på ett avsnitt åt gången eller hela ljudboken i ett svep. Om du vill fortsätta ditt lyssnande senare kan du klicka 
        på bokmärkessymbolen för att lägga in ett bokmärke i ljudboken. Märket blir placerat i början av det avsnitt du lyssnade på när du klickade.</p>
        <p>Du kommer åt dina bokmärken via fliken Bookmarks.<br>
        När du slutat lyssna ska du logga ut ur Naxos Spoken Word eller stänga appen NSWL i din enhets cacheminne, så licensen blir ledig för nästa lyssnare.</p>
      </div>
      <div id="svart-att-lasa" class="content-section">
        <h2>Talböcker för den som har svårt att läsa</h2>
        <p>I en del av Helmet-biblioteken kan du registrera dig som användare av specialbiblioteket Celias talböcker. Tjänsten finansieras av Undervisnings. och kulturministeriet och den 
        är avgiftsfri för användarna</p>
        <p>Celias tjänster är avsedda för alla som har svårt att läsa tryckt text på grund av nedsatt syn, sjukdom, dyslexi eller motsvarande. Då du registrerar dig som användare 
        vid Celia via ett Helmet-bibliotek behöver du inget läkarintyg, det räcker att du muntligt anmäler att du har svårt att läsa.</p>
        <p><a href="https://www.celia.fi/palvelut/aanikirjat-yksityishenkiloille/tarkista-oikeus-palveluihin/" target="_blank" 
        aria-label="Läs mera om de orsaker som berättigar till medlemskap i Celia. Länken öppnas i ett nytt fönster.">Läs mera om de orsaker som berättigar till medlemskap i Celia</a>.</p>
        <p>Du kan antingen registrera dig som nätanvändare eller som medlem i cd-bokklubbar.</p>
        <p>I samlingen finns över 40 000 talböcker av vilka ca 8 500 är på svenska Du hittar deckare, underhållningsromaner, memoarer och biografier, klassiker och nyheter på många 
        språk och för alla åldrar. Celias talbokstjänst fungerar på nätet, så för att använda tjänsten behöver du internetanslutning och en dator, smarttelefon eller 
        surfplatta för avlyssning.</p>
        <p>Som medlem i Celias bokklubbar får hem du månadens bok som cd. Du kan höra till högst fem cd-bokklubbar och du kan få en bok per månad ur varje klubb.</p>
        <p>Ta kontakt med närmaste Helmet-bibliotek som erbjuder Celias tjänster, eller fråga mera på ditt närbibliotek. 
        
        <h3>Instruktioner</h3>
        <p>Instruktioner för att lyssna på Celias talböcker finns på <a href="http://www.celia.fi/sv/las-talbocker/" target="_blank">Celias webbplats</a>.</p>
      </div>
   </div>
</div>

