<? $this->headTitle($this->translate('Self-service libraries')); $this->content()->setHeading($this->translate('Self-service libraries'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Self-service libraries are equipped with a system that enables customers to use the library independently. You can also use these libraries 
        outside the opening hours.</p>
        <p>During the self-service hours, there is no staff in the library but the premises are monitored using technology like cameras. In a 
        self-service library, you can usually borrow and return materials, use customer computers, read magazines and newspapers, work or have meetings. 
        A wireless network is available. The staff service hours and self-service hours are listed on each library’s website.</p>
        <p>Customers can get into these libraries using their Helmet library card and PIN code.</p>
      </div>
     <div id="in-helmet-area" class="content-section">
        <h2>Self-service libraries in Helsinki Metropolitan Area</h2>
        <h3>Espoo</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84918">Haukilahti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84833">Kalajärvi</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84789">Karhusuo</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84790">Kauklahti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84793">Laajalahti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84794">Laaksolahti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84915">Nöykkiö</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#86654">Otaniemi</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84917">Saunalahti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#86407">Suurpelto</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84795">Viherlaakso</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=en-gb#espoo">Espoo self-service libraries' rules</a></p>
        <h3>Helsinki</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84911">Herttoniemi</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84848">Laajasalo</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84864">Lauttasaari</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84852">Paloheinä</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84871">Suomenlinna</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84919">Viikin</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=en-gb#helsinki" 
        >Helsinki self-service libraries' rules</a></p>
        <h3>Kauniainen</h3>.
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84779">Kauniainen</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=en-gb#kauniainen">Kauniainen self-service library rules</a></p>
        <h3>Vantaa</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home?lng=en-gb#86659">Kivistö</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84875">Länsimäki</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84882">Pointti</a></li>
            <li><a href="/OrganisationInfo/Home?lng=en-gb#84877">Pähkinärinne</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=en-gb#vantaa">Vantaa self-service libraries’ rules</a></p>
      </div>
      <div id="outside-opening-hours" class="content-section">
        <h2>Other use outside the opening hours</h2>
        <p>There are also libraries that do not have an actual self-service library system but are available to local communities outside the opening 
        hours by other means.</p>
        <p><a href="/OrganisationInfo/Home?lng=en-gb#84861">Käpylä library's</a> premises can be used by local associations outside the opening hours.</p
      </div>
   </div>
</div>






