<? $this->headTitle($this->translate('Meröppna bibliotek')); $this->content()->setHeading($this->translate('Meröppna bibliotek'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="helmet-regionen" class="content-section">
        <h2>Meröppna biblioteken i Helmet-regionen</h2>   
        <p>Ett meröppet bibliotek har ett system som gör att besökarna kan använda biblioteket på egen hand. Därför kan biblioteket användas också utanför 
        de egentliga öppettiderna.</p><p>Då ingen personal är på plats övervakas rummen med hjälp av kameror och annan teknisk utrustning. I ett meröppet 
        bibliotek kan du oftast låna, returnera, använda kunddatorer och läsa tidningar. Du kan också t.ex. arbeta eller hålla ett möte. Biblioteket har 
        trådlöst nätverk. På bibliotekets egna nätsidor ser du när personal är på plats och när biblioteket är meröppet.</p>
        <p>Du kommer in i de här biblioteken med ditt eget bibliotekskort och PIN-kod.</p>
        <p>Personer under 15 år kan använda sig av de meröppna bibliotekens tjänster i Helsingfors tillsammans med sin vårdnadshavare.</p>
        <h3>Grankulla</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home?lng=sv#84779">Grankulla</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=sv#grankulla">Användarregler för meröppetbiblioteket i Grankulla</a>
        <h3>Esbo</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84917">Bastvik</a></li>
            <li><a href="/OrganisationInfo/Home#84789">Björnkärr</a></li>
            <li><a href="/OrganisationInfo/Home#84793">Bredvik</a></li>
            <li><a href="/OrganisationInfo/Home#84794">Dalsvik</a></li>
            <li><a href="/OrganisationInfo/Home#84795">Gröndal</a></li>
            <li><a href="/OrganisationInfo/Home#84918">Gäddvik</a></li>
            <li><a href="/OrganisationInfo/Home#84833">Kalajärvi</a></li>
            <li><a href="/OrganisationInfo/Home#84790">Köklax</a></li>
            <li><a href="/OrganisationInfo/Home#84915">Nöykis</a></li>
            <li><a href="/OrganisationInfo/Home#86654">Otnäs</a></li>
            <li><a href="/OrganisationInfo/Home#86407">Storåkern</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=sv#esbo">Användarregler för meröppetbiblioteken i Esbo</a></p>
        <h3>Helsinki</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84848">Degerö</a></li>
            <li><a href="/OrganisationInfo/Home#84864">Drumsö</a></li>
            <li><a href="/OrganisationInfo/Home#84911">Hertonäs</a></li>
            <li><a href="/OrganisationInfo/Home#84871">Sveaborgs</a></li>
            <li><a href="/OrganisationInfo/Home#84852">Svedängens</a></li>
            <li><a href="/OrganisationInfo/Home#84919">Vik</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=sv#helsingfors">Användarregler för meröppetbiblioteken i Helsingfors</a></p>
        <h3>Vanda</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84877">Hasselbacken</a></li>
            <li><a href="/OrganisationInfo/Home#86659">Kivistö</a></li>
            <li><a href="/OrganisationInfo/Home#84882">Point</a></li>
            <li><a href="/OrganisationInfo/Home#84875">Västerkulla</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=sv#vanda">Användarregler för meröppna bibliotek i Vanda</a></p>
        <p>Det finns också bibliotek som har meröppet enligt andra principer. De har inte den tekniska utrustning som ett egentligt meröppet bibliotek 
        kräver, men den lokala befolkningen kan ändå använda dem utanför den egentliga öppettiden med hjälp av andra arrangemang. 
        <a href="/OrganisationInfo/Home?lng=sv#84861">Kottby bibliotek</a>, som kan användas av lokala organisationer också då biblioteket är 
        stängt, är exempel på den här typen av bibliotek.</p>
      </div>
     <div id="esim2" class="content-section">
        <h2>Självbetjäning inom den normala öppettiden</h2>
        <p>Vissa bibliotek fungerar med självbetjäning under en del av den egentliga öppettiden. Då är biblioteket öppet utan betjäning 
        (personalen är på plats, men sköter andra uppgifter). Du kommer in som vanligt, biblioteket har inga system som kräver inloggning. 
        Den här typen av självbetjäning förekommer oftast på vardagsmorgnar eller under veckoslut. Bl.a. 
        <a href="/OrganisationInfo/Home?lng=sv#84860">Berghälls</a>, <a href="/OrganisationInfo/Home?lng=sv#84920">Myrbacka</a> och 
        <a href="/OrganisationInfo/Home?lng=sv#84922">Dickursby</a> bibliotek fungerar på detta sätt.</p>
      </div>
   </div>
</div>
