<? $this->headTitle($this->translate('Omatoimikirjastot')); $this->content()->setHeading($this->translate('Omatoimikirjastot'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="helmet-alueella" class="content-section">
        <h2>Omatoimikirjastot Helmet-alueella</h2>
        <p>Omatoimikirjastoiksi kutsutaan kirjastoja, joihin on asennettu asiakkaiden omatoimikäytön mahdollistava järjestelmä. 
        Näitä kirjastoja voit käyttää myös varsinaisten aukioloaikojen ulkopuolella.</p>
        <p>Omatoimisen käytön aikana kirjastossa ei ole henkilökuntaa, mutta tiloja valvotaan teknisesti muun muassa kameroin. 
        Yleensä omatoimikirjastossa voi lainata, palauttaa, käyttää asiakastietokoneita, lukea lehtiä ja vaikkapa työskennellä tai kokoustaa. 
        Langaton verkko on käytettävissä. Henkilökunnan palveluajat ja omatoimisen käytön ajat kerrotaan kunkin kirjaston omilla sivuilla.</p>
        <p>Näihin kirjastoihin Helmet-kirjaston asiakas pääsee sisään omalla kirjastokortilla ja tunnusluvulla.</p>
        <p>Alle 15-vuotiaat pääsevät Helsingin omatoimikirjastoihin omatoimisen käytön aikana huoltajan seurassa.</p>
        <h3>Espoo</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84918">Haukilahti</a></li>
            <li><a href="/OrganisationInfo/Home#84833">Kalajärvi</a></li>
            <li><a href="/OrganisationInfo/Home#84789">Karhusuo</a></li>
            <li><a href="/OrganisationInfo/Home#84790">Kauklahti</a></li>
            <li><a href="/OrganisationInfo/Home#84793">Laajalahti</a></li>
            <li><a href="/OrganisationInfo/Home#84794">Laaksolahti</a></li>
            <li><a href="/OrganisationInfo/Home#84915">Nöykkiö</a></li>
            <li><a href="/OrganisationInfo/Home#86654">Otaniemi</a></li>
            <li><a href="/OrganisationInfo/Home#84917">Saunalahti</a></li>
            <li><a href="/OrganisationInfo/Home#86407">Suurpelto</a></li>
            <li><a href="/OrganisationInfo/Home#84795">Viherlaakso</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=fi#espoo">Espoon omatoimikirjaston käyttösäännöt</a></p>
        <h3>Helsinki</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84911">Herttoniemi</a></li>
            <li><a href="/OrganisationInfo/Home#84848">Laajasalo</a></li>
            <li><a href="/OrganisationInfo/Home#84864">Lauttasaari</a></li>
            <li><a href="/OrganisationInfo/Home#84852">Paloheinä</a></li>
            <li><a href="/OrganisationInfo/Home#84871">Suomenlinna</a></li>
            <li><a href="/OrganisationInfo/Home#84919">Viikin</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=fi#helsinki">
        Helsingin omatoimikirjaston käyttösäännöt
        </a></p>
        <h3>Kauniainen</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#84779">Kauniainen</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=fi#kauniainen">
        Kauniaisten omatoimikirjaston käyttösäännöt</a></p>
        <h3>Vantaa</h3>
        <ul class="list-bullets">
            <li><a href="/OrganisationInfo/Home#86659">Kivistö</a></li>
            <li><a href="/OrganisationInfo/Home#84875">Länsimäki</a></li>
            <li><a href="/OrganisationInfo/Home#84882">Pointti</a></li>
            <li><a href="/OrganisationInfo/Home#84877">Pähkinärinne</a></li>
        </ul>
        <p><a href="/Content/omatoimikirjaston-kayttosaannot?lng=fi#vantaa">
        Vantaan omatoimikirjaston käyttösäännöt</a></p>
      </div>    
      <div id="ulkopuolinen-kaytto" class="content-section">
        <h2>Muu aukiolojen ulkopuolinen käyttö</h2>
        <p>On myös kirjastoja, joissa ei ole varsinaista omatoimikirjaston teknistä järjestelmää, mutta joissa aukiolojen ulkopuolinen käyttö on 
        mahdollistettu paikallisille yhteisöille muilla keinoilla.</p>
        <p>Tällainen on Helsingissä <a href="/OrganisationInfo/Home#84861">Käpylän kirjasto</a>, jonka tiloja voivat käyttää aukiolojen 
        ulkopuolella paikalliset järjestöt.</p>
      </div>
      <div id="normaali-aukiolo" class="content-section">
         <h2>Omatoimikäyttö normaalin aukiolon puitteissa</h2> 
         <p>Joissakin kirjastoissa osa varsinaisesta aukioloajasta on omatoimiaikaa, jolloin kirjasto on avoinna ilman asiakaspalvelua 
        (henkilökuntaa on paikalla muissa tehtävissä). Sisään pääsee normaalisti, koska kirjautumista vaativaa järjestelmää ei ole. Yleensä 
        tämänkaltaista omatoimisen käytön aikaa on arkiaamuisin tai viikonloppuisin. Tällaisia kirjastoja ovat mm. 
        <a href="/OrganisationInfo/Home#84860">Kallion</a>, <a href="/OrganisationInfo/Home#84920">Myyrmäen </a>ja 
        <a href="/OrganisationInfo/Home#84922">Tikkurilan</a> kirjastot.</p>
      </div>
   </div>
</div>