<? $this->headTitle($this->translate("Omatoimikirjaston käyttösäännöt")); $this->content()->setHeading($this->translate("Omatoimikirjaston käyttösäännöt"));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="espoo" class="content-section">
        <h2>Espoon omatoimikirjaston käyttösäännöt</h2>   
        <h3>Mitä omatoimikirjasto tarkoittaa</h3>
        <p>Omatoimikirjasto tarkoittaa kirjastotilaa, johon on asennettu asiakkaiden omatoimikäytön mahdollistava järjestelmä. Asiakas pääsee 
        kirjastotilaan myös palveluajan ulkopuolella, mikäli hänellä on Helmet-kirjastokortti ja voimassa oleva tunnusluku.</p>
        <h3>Sisäänkirjautuminen ja poistuminen</h3>
        <p>Omatoimiaikana kirjastoon pääsee sisään Helmet-kirjastokortilla ja tunnusluvulla. Kirjastokortin ja tunnusluvun saa mistä tahansa 
        Helmet-kirjastosta todistamalla henkilöllisyytensä.</p>
        <p>Kirjastokortti on henkilökohtainen. Jokaisen asiakkaan on kirjauduttava sisään omalla kirjastokortillaan, poikkeuksena aikuisen 
        seurassa kirjastoon tulevat lapset.</p>
        <p>Asiakkaan tulee varmistaa, ettei kiinteistöön tai kirjastoon tule samalla ovenavauksella sisään muita henkilöitä.</p>
        <p>Kirjastotilassa omatoimiajasta kerrotaan kuulutuksella. Asiakkaan tulee poistua kirjastotilasta omatoimiajan päättyessä ja 
        kirjaston sulkeutuessa.</p>
        <h3>Mitä kirjastossa voi tehdä omatoimiaikana</h3>
        <p>Omatoimikirjastossa voi:</p>
        <ul class="list-bullets">
            <li>lainata ja palauttaa aineistoa automaateilla</li>
            <li>noutaa varauksensa</li>
            <li>lukea lehtiä ja paikalla olevaa aineistoa</li>
            <li>käyttää asiakastietokoneita</li>
            <li>käyttää kirjaston langatonta verkkoa</li>
            <li>työskennellä ja opiskella</li>
            <li>pitää pienen palaverin</li>
        </ul>
        <p>Kirjaston palvelut, jotka edellyttävät henkilökuntaa, eivät ole käytettävissä omatoimiaikana. Tällaisia palveluita ovat 
        esimerkiksi maksujen maksaminen ja uuden kirjastokortin hankinta. Muistathan, että kirjastomaksut voi hoitaa myös verkossa. Voit 
        nopeuttaa uuden kirjastokortin hankintaa täyttämällä esitietolomakkeen joko paperilla tai netissä.</p>
        <p>Jos lainauksessa tai palautuksessa on ongelmia, asiakas on velvollinen selvittämään epäselvyydet kirjaston henkilökunnan kanssa. 
        Asiakas on siihen saakka vastuussa kirjastokortilleen rekisteröityneestä aineistosta.</p>
        <h3>Vastuut ja velvollisuudet</h3>
        <p>Jokainen käyttäjä on omalta osaltaan velvollinen edistämään yhteistä siisteyttä, viihtyvyyttä ja turvallisuutta kirjastossa.</p>
        <p>Kirjaston käyttösääntöjen ja järjestyslain rikkominen voivat johtaa omatoimikirjaston käytön estoon. Rikkomuksista tehdään 
        tarvittaessa rikosilmoitus poliisille.</p>
        <p>Tiloissa on tallentava kameravalvonta.</p>
      </div>
     <div id="helsinki" class="content-section">
        <h2>Helsingin omatoimikirjaston käyttösäännöt</h2>
        <h3>Mikä on omatoimikirjasto</h3>
        <p>Omatoimikirjasto on kirjasto, jota asiakas voi käyttää omatoimisesti kirjaston varsinaisten aukioloaikojen ulkopuolella. 
        Omatoimikirjasto tarkoittaa kirjastotilaa, johon on asennettu asiakkaiden omatoimikäytön mahdollistava järjestelmä. Asiakas pääsee 
        kirjastotilaan myös palveluajan ulkopuolella, mikäli hänellä on Helmet-kirjastokortti ja voimassa oleva tunnusluku.</p>
        <p>Omatoimikirjasto laajentaa kirjaston aukioloaikoja ja palvelujen saantia tarjoamalla tilat ja aineistot asiakkaiden käyttöön myös 
        aamuisin, iltaisin ja viikonloppuisin. Omatoimikirjaston omatoimiaikana kirjastossa ei ole henkilökuntaa paikalla.</p>
        <p>Omatoimisen käytön ajat ja palvelut kerrotaan kunkin <a href="/OrganisationInfo/Home">omatoimikirjaston omilla verkkosivuilla</a>.
        Tarkista myös kirjastokohtaiset ohjeet kirjastotilassa.</p>
        <h3>Mitä omatoimikirjastossa voi tehdä</h3>
        <p>Omatoimiaikana voi lainata ja palauttaa aineistoa, noutaa omia varauksia itsepalveluhyllystä, lukea lehtiä ja työskennellä. 
        Käytössä ovat kirjaston tilat, aineistot, asiakastietokoneet ja avoin langaton verkko. Palvelut, jotka edellyttävät henkilökuntaa, 
        eivät ole käytettävissä omatoimiaikana.</p>
        <h3>Sisäänkirjautuminen ja poistuminen</h3>
        <p>Jokaisen asiakkaan on kirjauduttava sisään henkilökohtaisesti, poikkeuksena aikuisen seurassa kirjastoon tulevat lapset. 
        Sekä sisään tultaessa, että tilasta poistuttaessa asiakkaan tulee varmistaa, ettei kiinteistöön tai kirjastoon tule samalla 
        ovenavauksella muita henkilöitä.</p>
        <p>Kirjastotilassa omatoimiajan alkamisesta ja päättymisestä kerrotaan opasteissa. Asiakkaan tulee poistua kirjastotilasta 
        omatoimiajan päättyessä ja kirjaston sulkeutuessa.</p>
        <p>Tiloissa on tekninen valvonta, mm. kamera- ja kulunvalvonta. Tilaan jääminen aiheuttaa hälytyksen. Kirjasto laskuttaa asiakasta 
        aiheutetusta hälytyksestä. Kirjaston käyttösääntöjen tai järjestyslain rikkominen voivat johtaa omatoimikirjaston käytön estoon. 
        Rikkomuksista tehdään tarvittaessa rikosilmoitus poliisille.</p>
        <h3>Vastuut ja velvollisuudet</h3>
        <p>Helsingin kaupunginkirjaston omatoimiasiakkaaksi pääseminen edellyttää Helmet-kirjastokorttia ja pin-koodia sekä sitoutumista 
        omatoimikirjaston käyttösääntöihin ja <a href="/Content/kayttosaannot">kirjaston yleisiin käyttösääntöihin</a>.</p>
        <p>Jokainen käyttäjä on omalta osaltaan velvollinen ylläpitämään siisteyttä, viihtyvyyttä ja turvallisuutta kirjastossa.</p>
        <p>Kirjastolain (1492/2016) mukaan kirjaston käyttäjän on käyttäydyttävä kirjastossa asiallisesti. Kirjaston toiminnan häiritsemiseen ja 
        turvallisuuden vaarantamiseen sovelletaan järjestyslakia (612/2003). Kirjaston käyttäjän on käsiteltävä yleisen kirjaston aineistoa ja 
        muuta omaisuutta huolellisesti.</p>
        <p>Omatoimiaikana kirjastossa ei saa järjestää kokoontumislaissa (530/1999) tarkoitettuja yleisiä kokouksia tai yleisötilaisuuksia, 
        ellei näistä ole erikseen sovittu Helsingin kaupunginkirjaston kanssa.</p>
        <p>Asiakas on velvollinen korvaamaan aiheuttamansa aineelliset vahingot. Aiheutettujen vahinkojen osalta sovelletaan Helmet-kirjastojen 
        käyttösääntöjä ja lakia yleisistä kirjastoista (1492/2016).</p>
        <p>Asiakas on vastuussa kirjastokortilleen rekisteröityneestä aineistosta. Jos lainauksessa tai palautuksessa on ongelmia, 
        epäselvyydet on selvitettävä varsinaisena aukioloaikana henkilökunnan kanssa.</p>
        <p>Kirjasto on yleinen paikka, jossa noudatetaan järjestyslakia (612/2003). Järjestyslain nojalla kirjastossa on myös omatoimiajalla 
        kiellettyä muun muassa:</p>
        <ul class="list-bullets">
          <li>päihteiden käyttö</li>
          <li>järjestyksen häiritseminen esim. meluamalla</li>
          <li>toista henkilöä uhkaava käytös joko fyysisesti tai sanallisesti</li>
        </ul>
        <h3>Tiloissa on tallentava kulun- ja kameravalvonta</h3>
        <p>Omatoimikirjaston tiloissa on kulun- ja kameravalvonta, jotka muodostavat Tietosuojalaissa (1050/2018) määritellyn henkilörekisterin. 
        <a href="/Content/asiakasrekisteriseloste">Rekisteriseloste</a>  on nähtävillä kirjastoissa. Rekisterin ylläpitäjä on Helsingin 
        kaupunginkanslia.</p>
      </div>
     <div id="kauniainen" class="content-section">
        <h2>Kauniaisten omatoimikirjaston käyttösäännöt</h2>   
        <h3>Mikä on omatoimikirjasto</h3>
        <p>Omatoimikirjastolla tarkoitetaan kirjastoa, jonne pääsee kirjaston varsinaisten aukioloaikojen ulkopuolella (esim. aamuisin, 
        iltaisin, viikonloppuna ja pyhäpäivinä), mutta paikalla ei ole henkilökuntaa. Omatoimisen käytön ajoista kerrotaan tarkemmin 
        kirjaston internetsivuilla.</p>
        <h3>Mitä omatoimiaikana voi tehdä</h3>
        <p>Omatoimiaikana voi lainata ja palauttaa aineistoa, noutaa omia varauksia, lukea lehtiä, opiskella, työskennellä sekä muuten vaan 
        oleskella. Käytössä ovat kirjaston tilat, aineistot, asiakastietokoneet sekä avoin langaton verkko.</p>
        <h3>Mitä omatoimiaikana ei voi tehdä</h3>
        <p>Palvelut, jotka edellyttävät henkilökuntaa, eivät ole käytettävissä omatoimiaikana.
        Omatoimiaikana kirjastossa ei saa järjestää kokoontumislaissa (530/1990) tarkoitettuja yleisiä kokouksia tai
        yleisötilaisuuksia, ellei näistä ole erikseen sovittu Kauniaisten kaupunginkirjaston kanssa.</p>
        <h3>Sisäänkirjautuminen ja poistuminen</h3>
        <p>Omatoimiasiakkaaksi pääseminen edellyttää voimassa olevaa Helmet-kirjastokorttia. Omatoimiaikana kirjastoon pääsee sisään 
        tunnistautumalla kirjastokortilla ja pin-koodilla. Jokaisen asiakkaan on kirjauduttava sisään henkilökohtaisesti. Alle 15-vuotiaat 
        voivat käyttää omatoimikirjastoa yhdessä huoltajansa kanssa. Huoltaja voi myös myöntää alle 15-vuotiaalle luvan käyttää 
        omatoimikirjastoa yksin, allekirjoittamalla omatoimikirjaston käyttöoikeussopimuksen. Käyttöoikeussopimus tehdään kirjastossa huoltajan 
        läsnä ollessa ja huoltajan henkilöllisyys tarkistetaan. Kirjastotilassa omatoimiajan alkamisesta ja päättymisestä kerrotaan opasteissa 
        ja kuulutuksissa. Asiakkaan tulee poistua kirjastotilasta omatoimiajan päättyessä ja kirjaston sulkeutuessa.</p>
        <h3>Vastuut ja velvollisuudet</h3>
        <p>Kirjaston käyttösäännöt ovat voimassa myös kirjaston omatoimiaikana. Asiakas on velvollinen korvaamaan mahdolliset aiheuttamansa 
        aineelliset vahingot. Aiheutettujen vahinkojen osalta sovelletaan Helmetkirjastojen käyttösääntöjä, lakia yleisistä kirjastoista 
        (1492/2016) ja vahingonkorvauslakia (412/1974). Rikosoikeudellinen vastuuikäraja on Suomessa 15 vuotta. Lähtökohtaisesti alle 
        15-vuotias on kuitenkin velvollinen korvaamaan rikoksellaan aiheuttamansa vahingot, sillä vahingonkorvausvelvollisuudelle ei ole
        säädetty alaikärajaa.</p>
        <p>Asiakkaan tulee varmistaa, ettei kirjastoon tule samalla ovenavauksella sisään muita henkilöitä. Alle 15-vuotiaat voivat tulla 
        kirjastoon huoltajansa seurassa kirjautumatta.</p>
        <p>Asiakas on vastuussa kirjastokortilleen rekisteröityneestä aineistosta.</p>
        <p>Jos lainauksessa tai palautuksessa on ongelmia, epäselvyydet on selvitettävä varsinaisena aukioloaikana henkilökunnan kanssa.</p>
        <p>Kirjasto on yleinen paikka, jossa noudatetaan järjestyslakia (612/2003). Järjestyslain nojalla kirjastossa on myös omatoimiajalla 
        kiellettyä muun muassa:</p>
        <ul class="list-bullets">
            <li>päihteiden käyttö</li>
            <li>järjestyksen häiritseminen esim. meluamalla</li>
            <li>toista henkilöä uhkaava käytös joko fyysisesti tai sanallisesti.</li>
        </ul>
        <p>Jokainen käyttäjä on velvollinen edistämään siisteyttä, viihtyvyyttä ja turvallisuutta kirjastossa. Kirjastotilasta on poistuttava 
        välittömästi omatoimiajan päättyessä ja kirjaston sulkeutuessa. Tilaan jääminen aiheuttaa hälytyksen. Kirjasto laskuttaa asiakasta 
        aiheutetusta hälytyksestä. Kirjaston käyttösääntöjen tai järjestyslain rikkominen voivat johtaa omatoimikirjaston käytön estoon. 
        Rikkomuksista tehdään tarvittaessa rikosilmoitus poliisille.</p>
        <h3>Tilojen valvonta ja turvallisuus</h3>
        <p>Tilojen valvonta hoidetaan tallentavalla kulun- ja kameravalvonnalla. Kameravalvonnan avulla mm. kuvataan sisään tulijat, valvotaan 
        alueita, sekä tallennetaan liikkeen perusteella videota. Myös valaistus ja kuulutukset yms. hoidetaan ohjausjärjestelmän avulla. 
        Kirjaston palovaroitinjärjestelmä on suoraan yhteydessä hälytyskeskukseen. Poistumisteistä, varauloskäynneistä sekä sammutusvälineiden 
        paikoista löytyy tarkempaa tietoa kirjaston tiloista löytyvistä pohjakartoista. Poistumistiet ja varauloskäynnit ovat myös kirjaston 
        tiloissa asianmukaisesti merkitty. Vartijapalvelu tekee kirjastoon satunnaiskäyntejä sekä tarkistaa tilat omatoimen sulkeutuessa.</p>
        <p>Kulun- ja kameravalvonta muodostavat tietosuojalaissa (1050/2018) määritellyn henkilörekisterin. Kameravalvonnassa syntyviä 
        tallenteita saavat käsitellä vain henkilöt, joiden työtehtäviin se kuuluu. Työyksiköissä on nimetyt henkilöt, joille on annettu 
        käyttöoikeus käsitellä tallenteet. Lisäksi on nimetty mahdolliset muut henkilöt, joille on annettu katseluoikeus. Rekisteriselosteet 
        ovat nähtävillä kirjastossa sekä Helmet.finna.fi -sivustolla. Rekisterinpitäjä on Kauniaisten kaupunki.</p>
        <h3>Hätätilanne</h3>
        <p>Hätätilanteessa saa apua soittamalla hätänumeroon 112. Hätänumero sekä vartijapalvelun numero löytyvät
        mm. kirjaston pääoven läheisyydestä sekä ilmoitustaululta.</p>
      </div>
     <div id="vantaa" class="content-section">
        <h2>Vantaan omatoimikirjaston käyttösäännöt</h2>
        <h3>Mitä omatoimikirjasto tarkoittaa</h3>
        <p>Omatoimikirjasto tarkoittaa kirjastotilaa, johon on asennettu asiakkaiden omatoimikäytön mahdollistava järjestelmä. Asiakas pääsee 
        kirjastotilaan myös palveluajan ulkopuolella, mikäli hänellä on Helmet-kirjastokortti ja voimassa oleva tunnusluku. Omatoimiaikana kirjastossa 
        ei ole henkilökuntaa.</p>
        <h3>Sisäänkirjautuminen ja poistuminen</h3>
        <p>Omatoimiaikana kirjastoon pääsee sisään Helmet-kirjastokortilla ja tunnusluvulla. Kirjastokortin ja tunnusluvun saa mistä tahansa 
        Helmet-kirjastosta todistamalla henkilöllisyytensä.</p>
        <p>Kirjastokortti on henkilökohtainen. Jokaisen asiakkaan on kirjauduttava sisään omalla kirjastokortillaan, poikkeuksena aikuisen seurassa 
        kirjastoon tulevat lapset.</p>
        <p>Asiakkaan tulee varmistaa, ettei kiinteistöön tai kirjastoon tule samalla ovenavauksella sisään muita henkilöitä.</p>
        <p>Kirjastotilassa omatoimiajasta kerrotaan kuulutuksella. Asiakkaan tulee poistua kirjastotilasta omatoimiajan päättyessä ja kirjaston 
        sulkeutuessa.</p>
        <h3>Mitä kirjastossa voi tehdä omatoimiaikana</h3>
        <ul class="list-bullets">
          <li>lainata ja palauttaa aineistoa automaateilla</li>
          <li>noutaa varauksensa</li>
          <li>lukea lehtiä ja paikalla olevaa aineistoa</li>
          <li>käyttää asiakastietokoneita</li>
          <li>käyttää kirjaston langatonta verkkoa</li>
          <li>työskennellä ja opiskella</li>
        </ul>
        <p>Kirjaston palvelut, jotka edellyttävät henkilökuntaa, eivät ole käytettävissä omatoimiaikana. Tällainen palvelu on esimerkiksi uuden 
        kirjastokortin hankinta.</p>
        <p>Jos lainauksessa tai palautuksessa on ongelmia, asiakas on velvollinen selvittämään epäselvyydet kirjaston henkilökunnan kanssa. 
        Asiakas on siihen saakka vastuussa kirjastokortilleen rekisteröityneestä aineistosta.</p>
        <h3>Vastuut ja velvollisuudet</h3>
        <p>Jokainen käyttäjä on omalta osaltaan velvollinen edistämään yhteistä siisteyttä, viihtyvyyttä ja turvallisuutta kirjastossa.</p>
        <p>Kirjaston käyttösääntöjen ja järjestyslain rikkominen voivat johtaa omatoimikirjaston käytön estoon. Rikkomuksista tehdään tarvittaessa 
        rikosilmoitus.</p>
        <p>Omatoimikirjaston käytössä noudatetaan kirjaston käyttösääntöjä, vahingonkorvauslakia (412/1974), järjestyslakia (612/2003), ja 
        tietosuojalakia (1050/2018).</p>
        <p>Tiloissa on tallentava kameravalvonta.</p>
      </div>
   </div>
</div>
