<? $this->headTitle($this->translate("Self-service libraries' rules")); $this->content()->setHeading($this->translate("Self-service libraries' rules"));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="espoo" class="content-section">
        <h2>Espoo self-service libraries' rules</h2>   
        <h3>What is a self-service library</h3>
        <p>A self-service library refers to library premises with a system that
        allows customers to use the library by themselves. You can access the
        library premises also outside service hours, provided that you have a
        Helmet library card and valid PIN code.</p>
        <h3>Logging in and leaving the library premises</h3>
        <p>During self-service hours, you can access the library with a valid
        Helmet library card and PIN code, which you can acquire from any
        Helmet library. You must, however, verify your identity.</p>
        <p>The library card is personal. Customers must login by using their own
        library card, with the exception of children with an adult.</p>
        <p>When you enter the library during self-service hours, you must ensure
        that no other person enters the premises or the library when you open
        the door.</p>
        <p>The beginning and end of self-service hours as well as the library
        employees' presence will be announced on the library premises over
        loudspeakers. You must leave the library premises at the end of selfservice hours and when the library closes.</p>
        <h3>What can I do at the library during self-service hours</h3>
        <p>During self-service hours, you can pick up items you have reserved,
        borrow and return items using the checkout/check-in machine. You
        can study, work and use customer terminals. Furthermore, you have all
        the magazines and other material at your disposal. The library
        premises are covered by WLAN.</p>
        <p>There are some library services that you cannot use during self-service
        hours, because they require the presence of library personnel.
        Examples of these services consist of, among other things, paying fees
        and acquiring a new library card. You can now also pay library fees
        online. It is easier for us to make a new library card for you if you fill
        the form online.</p>
        <p>If there are problems with borrowing or returning items, you must
        clarify the issues with the personnel. You are responsible for the
        material registered on your library card.</p>
        <h3>Responsibilities and liabilities</h3>
        <p>Each user is obliged to promote general tidiness, coziness and safety at
        the library.</p>
        <p>If you breach the library rules and the Public Order Act, you may be
        banned from using the self-service library. When required, any
        breaches will be reported to the police.</p>
        <p>The self-service library premises are equipped with camera
        surveillance.</p>
      </div>
     <div id="helsinki" class="content-section">
        <h2>Helsinki self-service libraries' rules</h2>
        <h3>What is a self-service library?</h3>
        <p>Self-service library is a library that a customer can use independently outside the library’s actual service hours. Self-service library 
        refers to library premises that have been equipped with a system that enables the clients to use the library independently. The client can 
        also access the library premises outside the library’s service hours, if they have a Helmet library card and a valid PIN number.</p>
        <p>Self-service library extends the library’s service hours and the availability of its services by opening the premises and materials to 
        customer use also in the mornings, in the evenings and on weekends. Library staff is not present in the premises during the self-service 
        library’s self-service hours.</p>
        <p>The times and available services of self-service libraries are presented on the <a href="/OrganisationInfo/Home">website of each 
        self-service library</a>. Remember to also read through the library-specific guidelines in the premises.</p>
        <h3>What can you do in a self-service library?</h3>
        <p>During the self-service hours, you can loan and return materials, pick up your reserved books from the self-service shelf, read magazines 
        and work. The clients have access to the library premises, materials, customer computers and the public wireless network. The services that 
        require personnel are not available during the self-service hours.</p>
        <h3>Logging in and exiting</h3>
        <p>Each customer must log into the library personally, aside for children accompanied by adults. Additionally, the customer must ensure that 
        no other persons enter the premises when they open the door, both when coming in and leaving.</p>
        <p>The library premises are equipped with signs that show when the self-service hours start and end. The customer must leave the library 
        premises when the self-service hours end and the library closes.</p>
        <p>The premises are supervised with video surveillance and access control, for example. Staying in the premises will trigger an alarm. The 
        library will charge the costs of the alarm from the customer. Violating the library’s self-service rules or the Public Order Act may lead to 
        prohibiting the use of the self-service library. If necessary, any offences will be reporteto the police.</p>
        <h3>Responsibilities and obligations</h3>
        <p>Becoming a self-service customer of the Helsinki City Library requires you to have a Helmet library card and a PIN code. You will also need 
        to commit to the self-service library’s user regulations and the <a href="/Content/kayttosaannot?lng=en-gb">library’s general regulations</a>.</p>
        <p>Each user is obligated, in their own part, to maintain the cleanliness, comfort and safety of the library premises.</p>
        <p>According to the Public Libraries Act (1492/2016), a library user must behave in a sensible manner in the library. 
        The Public Order Act (612/2003) will be applied if the operations of the library are disrupted or safety is compromised. The library user must 
        handle the public library’s materials and other property with due care.</p>
        <p>During self-service hours, public assemblies or events defined in the Assembly Act (530/1999) cannot be held in the library, unless otherwise 
        agreed with the Helsinki City Library.</p>
        <p>The customer is liable for any material damage caused by them. The user regulations of Helmet libraries as well as the Public Libraries 
        Act (1492/2016) will be applied to cases where damage has occurred.</p>
        <p>The customer is liable for the materials registered onto their library card. If there are issues with the loan or return of these materials, 
        the matter must be reviewed with the staff during the library’s public opening hours.</p>
        <p>A library is a public place, where the Public Order Act (612/2003) must be followed. Based on the Public Order Act, the following actions, 
        among others, are prohibited in a library also during its self-service hours:</p>
        <ul class="list-bullets">
          <li>substance use</li>
          <li>disrupting the peace by e.g. excessive noise</li>
          <li>threatening behaviour towards others, both physical and verbal</li>
        </ul>
        <p>The premises are equipped with recording access control and camera surveillance systems</p>
        <p>The self-service library premises are equipped with access control and camera surveillance systems, which are counted as a personal data 
        register according to the Data Protection Act (1050/2018). <a href="/Content/asiakasrekisteriseloste">The register description</a> is available 
        in the library. The register administrator is the Helsinki City Executive Office.</p>
      </div>
      <div id="kauniainen" class="content-section">
        <h2>Kauniainen self-service libraries' rules</h2>
        <h3>What is a self-service library</h3>
        <p>A self-service library allows customers to use the library independently outside the library’s ordinary opening
        hours (e.g. in the mornings, evenings, weekends and on holidays), when there is no staff present.
        More information about the self-service library opening hours is available on our website.</p>
        <h3>What you can do at the library during self-service hours</h3>
        <p>During the self-service hours, you can borrow and return material, pick up your reservations, read newspapers
        and magazines, study, work or just spend time at the library. You have access to the library premises, the
        library collections, the customer computer terminals and our open Wi-Fi network.</p>
        <h3>What you cannot do at the library during self-service hours</h3>
        <p>Library services that require the presence of library staff are not available during self-service hours.
        During self-service hours, public assemblies or events defined in the Assembly Act (530/1999) cannot be held
        in the library, unless otherwise agreed with the Kauniainen City Library.</p>
        <h3>Logging in and leaving the library</h3>
        <p>During self-service hours, you can access the library if you have a valid Helmet library card. You log in to enter
        the library using your library card with PIN-code. Each customer must log in using his or her own library card.
        Children under the age of 15 are permitted to use the library during self-service hours in the company of their
        guardian. The child’s guardian can also sign a form permitting a child under 15 to use the library alone during
        self-service hours. The permission form must be completed at the library, where the guardian must be present
        in person so that his or her identity can be verified. The beginning and end of self-service hours will be
        announced on the library premises over loudspeakers, and information is also posted in the library. You must
        leave the library premises at the end of self-service hours and when the library closes.</p>
        <h3>Responsibilities and liabilities</h3>
        <p>The library rules apply during the self-service hours. The customer is liable for any damage he or she causes.
        The user regulations of Helmet libraries, the Public Libraries Act (1492/2016) and the Tort Liability Act
        (412/1974) apply to cases where damage has occurred. In Finland, the age limit for criminal liability is 15 years
        of age. In principle, however, persons under the age of 15 are liable to compensate for damages unlawfully
        caused, because there is no statutory lower age limit for the liability to compensate for damage.</p>
        <p>A client entering the library must ensure that no one else enters at the same time. Children under 15 are,
        however, allowed to enter with a guardian without logging in separately.</p>
        <p>Each client is responsible for the material registered to his or her library card.</p>
        <p>If problems occur with borrowing or returning items, the problems must be solved with library staff during the
        regular opening hours.</p>
        <p>A library is a public place where the Public Order Act (612/2003) applies. Under the Public Order Act, actions
        prohibited in a library include the following:</p>
        <ul class="list-bullets">
            <li>use of intoxicating substances</li>
            <li>making noise or causing other similar disturbance</li>
            <li>threatening behaviour towards others, both verbal and physical.</li>
        </ul>
        <p>Each library user must undertake to ensure that the library is tidy, pleasant and safe. You must leave the
        library premises at the end of self-service hours and when the library closes. If a customer remains in the
        library after closing, the alarm will be triggered. The library will invoice customers for triggering the alarm in
        this manner. You may be banned from using the self-service library if you break the library’s rules or violate
        the Public Order Act. Where necessary, offences will be reported to the police.</p>
        <h3>Surveillance and safety</h3>
        <p>The library has an access control system and recording camera surveillance. Camera surveillance includes
        footage of customers entering the library, surveillance of the premises and video footage based on motion
        detectors. The indoor lighting and the loudspeaker announcements are also operated by the control system.
        The library’s fire alarm system is linked directly to the emergency services. More information on exit routes,
        emergency exits and fire fighting equipment is posted on information sheets in the library. The exit routes and
        emergency exits are also signposted in the library. A security service makes occasional checks of the library
        premises and a security check when the library closes.</p>
        <p>The recordings from the access control system and recording camera surveillance constitute a personal data
        register under the Data Protection Act (1050/2018). Camera surveillance recordings can be handled only by
        persons authorized to do so as part of their work. The units have named persons authorized to handle
        recorded material. There are some additional staff authorized to view recorded material. 
        <a href="/Content/asiakasrekisteriseloste?lng=en-gb">The register
        description</a> is available at the library. The data controller is the City of Kauniainen.</p>
        <h3>Emergencies</h3>
        <p>In an emergency, call the emergency number, 112. The emergency number and the telephone number of the
        security guards are posted on signs near the library’s main doors and on the notice board.</p>
      </div>
     <div id="vantaa" class="content-section">
        <h2>Vantaa self-service libraries’ rules</h2>
        <h3>General about self-service library</h3>
        <p>A self-service library refers to library premises with a system that allows customers to use the library by themselves. You can access the 
        library premises also outside service hours, provided that you have a Helmet library card and valid PIN. No employees will be present during 
        self-service hours at the library.</p>
        <h3>Logging in and leaving the library premises</h3>
        <p>During the self-service hours, you can access the library with a Helmet library card and PIN. You can get a library card and PIN at any 
        Helmet library by verifying your identity. Remember that the library card is personal. Each customer must login with their own library card, 
        with the exception of children accompanied by an adult.</p>
        <p>When you enter the library during self-service hours, you must ensure that no other person enters the premises or the library when you open 
        the door.</p>
        <p>Self-service hours are announced at the library over loudspeakers. Customers shall exit the library premises when self-service hours end 
        and the library closes.</p>
        <h3>What you can do at the library during self-service hours</h3>
        <ul class="list-bullets">
          <li>borrow and return material using the check-out and check-in machines</li>
          <li>pick up your reserved items</li>
          <li>read magazines and other material on the spot</li>
          <li>use customer computers</li>
          <li>use the library's wireless network</li>
          <li>work and study</li>
        </ul>
        <p>There are some library services that you cannot use during self-service hours, because they require the presence of library personnel. An 
        example of such a service is acquiring a new library card.</p>
        <p>If there are problems with borrowing or returning items, you must clarify the issues with the personnel. You are responsible for the
        material registered on your library card.</p>
        <h3>Responsibilities and liabilities</h3>
        <p>Each user is obliged to promote general tidiness, coziness and safety at the library.</p>
        <p>If you breach the library rules and the Public Order Act, you may be banned from using the self-service library. When required, any 
        breaches will be reported to the police.</p>
        <p>The library’s rules, the Tort Liability Act (412/1974), the Public Order Act (612/2003), the Act on Public Libraries (1492/2016), and the 
        Data Protection Act (1050/2018) will be applied to using the self-service library.</p>
        <p>The library premises are equipped with recording camera surveillance.</p>
      </div>
   </div>
</div>



