<? $this->headTitle($this->translate("Användarregler för meröppetbiblioteken")); $this->content()->setHeading($this->translate("Användarregler för meröppetbiblioteken"));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esbo" class="content-section">
        <h2>Användarregler för meröppetbiblioteken i Esbo</h2>
        <h3>Vad betyder ett meröppet bibliotek?</h3>   
        <p>Meröppet bibliotek har ett system som gör att besökarna kan använda
        biblioteket på egen hand. Du kan använda biblioteket också utanför de
        egentliga öppettiderna med ditt eget Helmet-bibliotekskort och giltig
        PIN-kod.</p>
        <h3>Hur gör jag för att komma in under meröppet?</h3>
        <p>När biblioteket har meröppet kommer du in i biblioteket med ett giltigt
        Helmet-kort samt PIN-koden. Bibliotekskortet samt PIN-koden får du
        från vilket som helst Helmet-bibliotek genom att visa giltig
        legitimation.</p>
        <p>Bibliotekskortet är personligt. Du kommer in på meröppetbiblioteket
        med ditt eget bibliotekskort, med undantag för barn och ungdomar
        som är tillsammans med en vuxen person.</p>
        <p>Kunderna bör försäkra sig om att andra personer inte kommer in i
        fastigheten eller biblioteket samtidigt som dörren öppnas.
        I bibliotekets lokaliteter meddelas via högtalare/röststyrning när
        meröppettiden börjar och slutar samt när personalen är på plats. Du
        bör lämna biblioteket när meröppettiden slutar och biblioteket stängs.</p>
        <h3>Vad kan jag göra på biblioteket när det är meröppet?</h3>
        <p>Under meröppet kan du hämta reserverat material samt låna och
        returnera material med låneautomaten. Under meröppet har du också
        tillgång till tidningar, tidskrifter och övrigt material i biblioteket. Du kan
        använda kunddatorer, arbeta eller studera. Bibliotekslokaliteterna har
        ett trådlöst nät.</p>
        <p>Under meröppet kan du inte använda sådana bibliotekstjänster för
        vilka det krävs personal, som till exempel betala avgifter och skaffa dig
        ett nytt bibliotekskort. Kom ihåg, att du kan betala avgifter också på
        nätet. Du kan få ditt bibliotekskort snabbare om du fyller i blanketten
        på förhand på nätet.</p>
        <p>Om det uppstår problem med utlåning eller inlämning av utlånat
        material är du skyldig att reda ut oklarheterna med personalen. Fram
        till dess är du ansvarig för det material som registrerats på ditt
        bibliotekskort.</p>
        <h3>Ansvar och skyldigheter</h3>
        <p>Alla som besöker meröppetbiblioteket är skyldiga att hålla de
        gemensamma lokaliteterna snygga och trivsamma samt främja
        säkerheten i biblioteket.</p>
        <p>Om du bryter mot användarreglerna eller ordningslagen kan det leda
        till att användningen av meröppetbiblioteket spärras. Vid behov görs
        en brottsanmälan till polisen för förseelserna.</p>
        <p>Meröppetbiblioteken har kameraövervakning i sina lokaliteter.</p>
      </div>
     <div id="grankulla" class="content-section">
        <h2>Användarregler för meröppetbiblioteket i Grankulla</h2>
        <h3>Vad är ett meröppet bibliotek?</h3>
        <p>Med meröppet bibliotek avses ett bibliotek du kan besöka också utanför de ordinarie öppettiderna (t.ex. innan
        biblioteket öppnar på morgonen, efter att det har stängt på kvällen, på veckoslut och helgdagar) trots att
        personalen inte är på plats.</p>
        <p>Det finns närmare information om meröppettiderna på bibliotekets webbplats.</p>
        <h3>Vad kan man göra under meröppettiderna?</h3>
        <p>Då biblioteket är meröppet kan du låna och returnera material, avhämta material du har reserverat, läsa
        tidningar, studera, jobba eller annars tillbringa tid på biblioteket. Du har tillgång till bibliotekets lokaler,
        material, kunddatorer och det öppna trådlösa nätverket.</p>
        <h3>Vad kan man inte göra under meröppettiderna?</h3>
        <p>Under meröppettiden erbjuds inga sådana tjänster som kräver personal.
        Under meröppettiderna är det inte tillåtet att ordna sådana allmänna sammankomster eller offentliga
        tillställningar som avses i lagen om sammankomster (530/1999), om man inte separat har kommit överens om
        dem med Grankulla stadsbibliotek.</p>
        <h3>Hur du kommer och går på ett meröppet bibliotek</h3>
        <p>Du behöver ett giltigt Helmet-bibliotekskort för att kunna komma in på ett meröppet bibliotek. Under
        meröppettiden kommer du in på biblioteket med ditt bibliotekskort och pin-koden till kortet. Varje användare
        ska använda sina egna personliga koder för att logga in. Barn under 15 år kan använda ett meröppet bibliotek
        tillsammans med sin vårdnadshavare. Vårdnadshavaren kan också ge ett barn under 15 lov att ensam använda
        ett meröppet bibliotek. Det här görs då vårdnadshavaren undertecknar avtalet om användningsrätt av
        meröppet bibliotek. Avtalet om användningsrätt görs upp på biblioteket. Vårdnadshavaren ska vara
        personligen närvarande och hens identitet ska kontrolleras då avtalet undertecknas. I biblioteket ges
        information om när meröppet börjar eller slutar på informationsskyltar och via högtalare. Du ska lämna
        biblioteket när meröppettiden slutar och biblioteket stängs.</p>
        <h3>Ansvar och skyldigheter</h3>
        <p>Reglerna för biblioteket gäller också under meröppettiden. Kunden är skyldig att ersätta eventuella materiella
        skador hen har orsakat. På skadorna tillämpas reglerna för Helmet-biblioteken, lagen om allmänna bibliotek
        (1492/2016) och skadeståndslagen (412/1974). I Finland är åldersgränsen för straffrättsligt ansvar 15 år. I
        princip är dock också en person under 15 år skyldig att ersätta skador som hen orsakat genom brottslig
        verksamhet, eftersom ingen nedre åldersgräns har bestämts för skadeståndsskyldighet.</p>
        <p>Klienten ska försäkra sig om att ingen annan kommer in i biblioteket då hen öppnar dörren. Barn under 15 år
        kan komma till biblioteket med sin vårdnadshavare utan att själva logga in.</p>
        <p>Klienten är ansvarig för det material som registreras på hens bibliotekskort.</p>
        <p>Om det uppkommer problem då klienten lånar eller returnerar material ska problemen redas ut med
        personalen under bibliotekets ordinarie öppettid.</p>
        <p>Biblioteket är en offentlig plats, där ordningslagen (612/2003) tillämpas. Enligt ordningslagen är det även
        under meröppettiderna i biblioteket förbjudet att bl.a.:</p>
        <ul class="list-bullets">
            <li>använda rusmedel</li>
            <li>störa ordningen t.ex. genom att föra oljud</li>
            <li>hota någon fysiskt eller verbalt.</li>
        </ul>
        <p>Varje biblioteksbesökare är skyldig att se till att det är snyggt, trivsamt och tryggt i biblioteket. Du ska lämna
        biblioteket genast när meröppettiden slutar och biblioteket stängs. Om man stannar kvar efter stängningsdags
        utlöses larmet. Biblioteket fakturerar klienten som har utlöst larmet. Om du bryter mot användarreglerna eller
        ordningslagen kan det leda till att användningen av meröppetbiblioteket spärras. Vid behov görs en
        brottsanmälan till polisen för förseelserna.</p>
        <h3>Övervakning av lokalerna och säkerhet</h3>
        <p>Lokalerna har passerkontroll och kameraövervakning med inspelning. I kameraövervakningen ingår bl.a.
        filmmaterial av dem som kommer in i biblioteket, övervakning av områden och videofilm som startas av
        rörelsedetektorer. Också belysningen och högtalarmeddelandena mm. sköts via ett styrsystem. Bibliotekets
        brandvarnarsystem är kopplat direkt till nödcentralen. Närmare information om utrymningsvägarna,
        nödutgångarna och släckningsutrustningen finns på bottenplaner som är uppsatta inne i biblioteket.
        Utrymningsvägarna och nödutgångarna är också tydligt skyltade inne i biblioteket. En väktarfirma kontrollerar
        biblioteket emellanåt och säkrar lokalerna då meröppettiden slutar.</p>
        <p>Passerkontrollen och kameraövervakningen utgör ett personregister som avses i dataskyddslagen (1050/2018).
        Det inspelade materialet från kameraövervakningen får hanteras endast av de personer i vars arbetsuppgifter
        det ingår. I arbetsenheterna finns namngivna personer som har givits användarrättigheter att hantera det
        inspelade materialet. Det finns också andra namngivna personer som har rätt att ta del av materialet.
        <a href="/Content/asiakasrekisteriseloste?lng=sv">Registerbeskrivningarna</a> finns till påseende på biblioteket. 
        Registeransvarig är Grankulla stad.</p>
        <h3>Nödsituationer</h3>
        <p>Ring 112 för att kalla på hjälp vid nödsituationer. Nödnumret och väktarfirmans nummer finns på skyltar bl.a.
        vid huvudingången och på anslagstavlan.</p>
      </div>
      <div id="helsingfors" class="content-section">
        <h2>Användarregler för meröppna bibliotek i Helsingfors</h2>   
        <h3>Vad är ett meröppet bibliotek?</h3>
        <p>Ett meröppet bibliotek är ett bibliotek som kunden kan använda på egen hand utanför bibliotekets egentliga öppetider. Ett 
        meröppet bibliotek är ett bibliotek där man installerat ett system som gör det möjligt för kunden att använda biblioteket på egen hand. 
        Kunden kommer in i biblioteket även utanför servicetiderna med sit Helmet-bibliotekskort och en giltig PIN-kod.</p>
        <p>Meröppetbiblioteket utvidgar bibliotekets öppettider och tillgången till tjänster genom att göra lokalerna och materialet tillgängliga för 
        kunderna även morgnar, kvällar och veckoslut. Under meröppetbibliotekets självbetjäningstider finns det ingen personal på 
        plats på biblioteket.</p>
        <p>Tiderna för meröppet och vilka tjänster som erbjuds finns på de olika <a href="/OrganisationInfo/Home?lng=sv">meröppna bibliotekens 
        webbplatser</a>. Kontrollera även de biblioteksspecifika anvisningarna i biblioteket.</p>
        <h3>Vad kan jag göra på biblioteket när det är meröppet</h3>
        <p>Under meröppet kan man låna och returnera material, hämta reserveringar ur självbetjäningshyllan, läsa tidningar och arbeta. Du har tillgång 
        till bibliotekets lokaler, material, kunddatorer och det öppna trådlösa nätet. Tjänster som förutsätter personal kan inte användas under 
        meröppet.</p>
        <h3>Att logga in och lämna lokalerna</h3>
        <p>Varje kund ska logga in personligen, barn som följer med en vuxen till biblioteket utgör undantag. Kunden ska försäkra sig om att inga 
        andra personer kommer in i fastigheten eller biblioteket då kunden kommer till eller lämnar lokalerna.</p>
        <p>Skyltarna visar när meröppet börjar och slutar. Kunden ska lämna bibliotekslokalerna då meröppet upphör och biblioteket stänger.</p>
        <p>I lokalerna finns teknisk övervakning, bl.a. kameraövervakning och passagekontroll. Att bli kvar i lokalerna utlöser et larm. Biblioteket 
        fakturerar kunden för orsakade larm. Att bryta mot bibliotekets användarregler eller ordningslagen kan leda till att användningen av meröppet 
        förhindras. Överträdelserna anmäls vid behov till polisen.</p>
        <h3>Ansvar och skyldigheter</h3>
        <p>För att få bli meröppetkund hos Helsingfors stadsbibliotek förutsäts ett Helmet-bibliotekskort och en PIN-kod samt att kunden förbinder sig 
        vid användarreglerna för meröppet och <a href="/Content/kayttosaannot?lng=sv">bibliotekets allmänna användningsregler</a>.</p>
        <p>Varje användare är skyldig att ta hand om prydligheten, trivseln och säkerheten på biblioteket.</p>
        <p>Enligt bibliotekslagen (1492/2016) ska biblioteksanvändaren uppträda korrekt i biblioteket. På störningar i bibliotekets verksamhet och 
        äventyrandet av dess säkerhet tillämpas ordningslagen. Biblioteksanvändaren ska hantera det allmänna bibliotekets material och övriga 
        egendom varsamt.</p><p>Under meröppet får inte sådana allmänna sammankomster eller ofentliga tillställningar som avses i lagen om 
        sammankomster (530/1999) ordnas om dessa inte överenskommits separat med Helsingfors stadsbibliotek.</p>
        <p>Kunden är skyldig att ersätta de materiella skador som denne orsakar. På orsakade skador tillämpas Helmet-bibliotekens användningsregler 
        och lagen om allmänna bibliotek (1492/2016).</p>
        <p>Kunden ansvarar för material som registrerats med dennes bibliotekskort. Om det förekommer problem med lån eller returnering av material 
        ska oklarheterna redas ut under den egentliga öppetiden med personalen.</p>
        <p>Biblioteket är en allmän plats där ordningslagen (612/2003) tillämpas. Med stöd av ordningslagen är det under meröppet även bland annat 
        förbjudet att:</p>
        <ul class="list-bullets">
          <li>använda rusmedel</li>
          <li>störa ordningen t.ex. genom oljud</li>
          <li>hota någon annan antingen fysiskt eller verbalt</li>
        </ul>
        <h3>I lokalerna finns inspelande passagekontroll och kameraövervakning</h3>
        <p>I biblioteken finns passagekontroll och kameraövervakning som utgör ett personregister som avses i dataskyddslagen (1050/2018). 
        <a href="/Content/asiakasrekisteriseloste?lng=sv">Registerbeskrivningen</a> finns till påseende på biblioteket.</p>
      </div>
     <div id="vanda" class="content-section">
        <h2>Användarregler för meröppetbiblioteken i Vanda</h2>
        <h3>Vad är ett meröppetbibliotek?</h3>
        <p>Meröppetbibliotek är bibliotek där man har installerat system som gör självbetjäning möjlig för kunderna. För att kunna besöka biblioteket 
        även utanför de egentliga öppettiderna behöver du ett Helmet-bibliotekskort och en giltig PIN-kod. Under meröppet finns ingen bibliotekspersonal 
        på plats.</p>
        <h3>Hur gör jag för att komma in under meröppet?</h3>
        <p>För att komma in i biblioteket under meröppet ska du använda ditt Helmet-bibliotekskort och PIN-kod. Bibliotekskort samt PIN-koder får du 
        från vilket som helst Helmet-bibliotek genom att visa giltig legitimation. Bibliotekskortet är personligt. Det går att komma in i 
        meröppetbiblioteket med eget bibliotekskort, med undantag för barn som kommer till biblioteket med en vuxen.</p>
        <p>Du ska se till att inga andra personer kommer in i fastigheten eller biblioteket samtidigt med dig.</p>
        <p>Det meddelas om meröppettiden i bibliotekets högtalare. Du bör avlägsna dig från biblioteket när meröppettiden slutar och 
        biblioteket stängs.</p>
        <h3>Vad kan jag göra på biblioteket när det är meröppet?</h3>
        <ul class="list-bullets">
          <li>låna och återlämna material med låneautomaterna</li>
          <li>hämta din reservation</li>
          <li>läsa tidningar och annat material på plats</li>
          <li>använda kunddatorerna</li>
          <li>använda bibliotekets trådlösa nät</li>
          <li>jobba och studera</li>
        </ul>
        <p>Under meröppet kan du inte använda sådana bibliotekstjänster för vilka det krävs personal som till exempel att skaffa ett nytt 
        bibliotekskort.</p>
        <p>Om det uppstår problem med utlåning eller inlämning av utlånat material är du skyldig att reda ut oklarheterna med bibliotekets personal. 
        Fram till dess är du ansvarig för det material som registrerats på ditt bibliotekskort.</p>
        <h3>Ansvar och skyldigheter</h3>
        <p>Alla som besöker meröppetbiblioteket är skyldiga att hålla de gemensamma lokaliteterna snygga och trivsamma samt främja säkerheten i 
        biblioteket.</p>
        <p>Om du bryter mot användarreglerna eller ordningslagen kan det leda till att användningen av meröppetbiblioteket spärras. Vid behov görs 
        en brottsanmälan för förseelserna.</p>
        <p>Bibliotekets användarregler, skadeståndslagen (412/1974), ordningslagen (612/2003), lagen om allmänna bibliotek (1492/2016) och 
        dataskyddslagen (1050/2018) ska följas vid användningen av meröppetbiblioteket.</p>
        <p>Lokalerna har kameraövervakning med inspelning.</p>
      </div>
   </div>
</div>
