<? $this->headTitle($this->translate('Library makerspace')); $this->content()->setHeading($this->translate('Library makerspace'));?><div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="espoo" class="content-section">
        <h2>Espoo</h2>   
        <ul class="list-bullets">
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15321" target="_blank" aria-label="Entresse Library Makerspace. Link opens to Varaamo's site.">Entresse Library Makerspace</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=awe6z5u2hvea" target="_blank" aria-label="Iso Omena Library Makerspace. Link opens to Varaamo's site.">Iso Omena Library Makerspace</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A63115" target="_blank" aria-label="Lippulaiva Library Makerspace. Link opens to Varaamo's site.">Lippulaiva Library Makerspace</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15417" target="_blank" aria-label="Sello Library Makerspace. Link opens to Varaamo's site.">Sello Library Makerspace</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15311" target="_blank" aria-label="Tapiola Library Makerspace. Link opens to Varaamo's site.">Tapiola Library Makerspace</a></li>
        </ul>
      </div>
     <div id="helsinki" class="content-section">
        <h2>Helsinki</h2>
        <ul class="list-bullets">
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A51342" target="_blank" aria-label="Urban Workshop in Oodi. Link opens to Varaamo's site.">Urban Workshop in Oodi</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8178" target="_blank" aria-label="Kontulan Library. Link opens to Varaamo's site."> Kontulan Library</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8177" target="_blank" aria-label="Oulunkylän Library. Link opens to Varaamo's site.">Oulunkylän Library</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8269" target="_blank" aria-label="Pasila Library. Link opens to Varaamo's site.">Pasila Library</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8310" target="_blank" aria-label="Vuosaari Library. Link opens to Varaamo's site.">Vuosaari Library</a></li>
        </ul>  
      </div>
      <div id="vantaa" class="content-section">
        <h2>Vantaa</h2>
        <ul class="list-bullets">
            <li><a href="https://asp3.timmi.fi/WebTimmi/menuAction.do?logicalForward=weekView" target="_blank" aria-label="Lumo Library Makerspace. Link opens to Timmi's site.">Lumo Library Makerspace</a></li>
        </ul>
      </div>
   </div>
</div>