<? $this->headTitle($this->translate('Pajat ja verstaat')); $this->content()->setHeading($this->translate('Pajat ja verstaat'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="espoo" class="content-section">
        <h2>Espoo</h2> 
        <p>Espoon kirjastojen Pajat ovat kaikille avoimia maksuttomia työskentely- ja oppimispaikkoja.</p>
        <p>Espoon kirjaston Pajat löydät Entressestä, Isosta Omenasta, Lippulaivasta, Sellosta ja Tapiolasta. Kaikissa Pajoissa voit vaikkapa askarrella, ommella, tehdä omia projekteja ja osallistua 
        ohjattuun toimintaan. Pajojen ja laitteiden käyttö on maksutonta. Huomioithan, että Pajan laitteet ovat omatoimikäytössä. Löydät kattavat ohjeet Pajasta. Henkilökunta auttaa tarvittaessa.</p>
        <p>Espoon Kirjaston Pajojen varattavat laitteet tarkemmat tiedot ja saatavuuden löydät  <a href="https://varaamo.espoo.fi" aria-label="Linkki avautuu Espoon Varaamoon.">Varaamosta.</a></p>
        <ul class="list-bullets">
            <li><a href="https://varaamo.espoo.fi/search?&amp;municipality=espoo&amp;search=Entresse" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Entresse-haulla.">Entressen kirjaston Paja</a></li>
            <li><a href="https://varaamo.espoo.fi/search?&amp;municipality=espoo&amp;search=iso+omena" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Iso Omena-haulla.">Ison Omenan kirjaston Paja</a></li>
            <li><a href="https://varaamo.espoo.fi/search?&amp;municipality=espoo&amp;search=lippulaiva" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Lippulaiva-haulla.">Lippulaivan Paja</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15417" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Sellon kirjasto-haulla.">Sellon kirjaston Paja</a></li>
            <li><a href="https://varaamo.espoo.fi/search?municipality=espoo&unit=tprek%3A15311" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Tapiolan kirjasto-haulla.">Tapiolan kirjaston Paja</a></li>
        </ul>
      </div>
     <div id="helsinki" class="content-section">
        <h2>Helsinki</h2>
        <ul class="list-bullets">
            <li><a href="https://varaamo.hel.fi/search?municipality=helsinki&unit=tprek%3A51342" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Oodi-haulla.">Keskustakirjasto Oodi</a></li>
            <li><a href="https://varaamo.hel.fi/search?municipality=helsinki&unit=tprek%3A8178" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Kontulan kirjasto-haulla.">
            Kontulan kirjasto</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8177" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Oulunkylän kirjasto-haulla.">Oulunkylän kirjasto</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8269" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Pasilan kirjasto-haulla.">Pasilan Konehuone</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8310" target="_blank" aria-label="Linkki avautuu Varaamon sivuille Vuosaaren kirjasto-haulla.">Vuosaaren kirjaston verstaslaitteet</a></li>
        </ul>    
      </div>
      <div id="vantaa" class="content-section">
        <h2>Vantaa</h2>
        <ul class="list-bullets">
            <li><a href="https://asp3.timmi.fi/WebTimmi/menuAction.do?logicalForward=weekView" target="_blank" aria-label="Linkki avautuu Timmiin.">Lumon kirjaston paja</a></li>
        </ul>
      </div>
   </div>
</div>