<? $this->headTitle($this->translate('Verkstäder')); $this->content()->setHeading($this->translate('Verkstäder'));?>
<p>Vi erbjuder arbetsutrymmen, manicker, apparatur och hjälper dig gärna att förverkliga dina idéer.</p>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esbo" class="content-section">
        <h2>Esbo</h2>   
        <ul class="list-bullets">
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15321" target="_blank" aria-label="Entresses verkstad. Länken öppnas i ett nytt fönster till Varaamo.">Entresses verkstad</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15311" target="_blank" aria-label="Hagalunds verkstad. Länken öppnas i ett nytt fönster till Varaamo.">Hagalunds verkstad</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=awe6z5u2hvea" target="_blank" aria-label="Iso Omenas verkstad. Länken öppnas i ett nytt fönster till Varaamo.">Iso Omenas verkstad</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A63115" target="_blank" aria-label="Lippulaivas verkstad. Länken öppnas i ett nytt fönster till Varaamo.">Lippulaivas verkstad</a></li>
            <li><a href="https://varaamo.espoo.fi/search?unit=tprek%3A15417" target="_blank" aria-label="Sellos verkstad. Länken öppnas i ett nytt fönster till Varaamo.">Sellos verkstad</a></li>
        </ul>
      </div>
     <div id="helsinki" class="content-section">
        <h2>Helsingfors</h2>
        <ul class="list-bullets">
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8269" target="_blank" aria-label="Böle. Länken öppnas i ett nytt fönster till Varaamo.">Böle</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A51342" target="_blank" aria-label="Cityverkstaden i Ode. Länken öppnas i ett nytt fönster till Varaamo.">Cityverkstaden/Kaupunkiverstas i Ode</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8178" target="_blank" aria-label="Gårdsbacka bibliotek. Länken öppnas i ett nytt fönster till Varaamo.">Gårdsbacka bibliotek</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8310" target="_blank" aria-label="Nordsjö bibliotek. Länken öppnas i ett nytt fönster till Varaamo.">Nordsjö bibliotek</a></li>
            <li><a href="https://varaamo.hel.fi/search?unit=tprek%3A8177" target="_blank" aria-label="Åggelby bibliotek. Länken öppnas i ett nytt fönster till Varaamo.">Åggelby bibliotek</a></li>
        </ul>  
      </div>
      <div id="vantaa" class="content-section">
        <h2>Vantaa</h2>
        <ul class="list-bullets">
            <li><a href="https://asp3.timmi.fi/WebTimmi/menuAction.do?logicalForward=weekView" target="_blank" aria-label="Lumos verkstad. Länken öppnas i ett nytt fönster till Timma.">Lumos verkstad</a></li>
        </ul>
      </div>
   </div>
</div>