<? $this->headTitle($this->translate('Tjänster för samfund')); $this->content()->setHeading($this->translate('Tjänster för samfund'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Biblioteket samarbetar med daghem, skolor och servicecentraler.</p>
      </div>
     <div id="skolor" class="content-section">
        <h2>Skolor</h2>
        <p>Du är välkommen att besöka biblioteket med din skolklass eller grupp. En utflykt till biblioteket med klassen är ett sätt att väcka elevernas intresse för 
        berättelser, kunskap och inlärning. Eleverna kan under sitt besök få undervisning i informationssökning och biblioteksanvändning eller få boktips och hjälp att hitta 
        lämpliga böcker att låna hem. Biblioteket kan vid behov skräddarsy besöket för klassen; eleverna kan t.ex. söka efter information för ett projekt i modersmål eller 
        historia. Du kan också skaffa ett eget bibliotekskort till klassen.</p><p>Biblioteken deltar gärna i olika evenemang som skolorna ordnar 
        och kan hjälpa lärarna att hitta lämplig skön- och facklitteratur. Ta kontakt och föreslå ett samarbete.</p>
        <p>Senast uppdaterad 19-04-2022</p>
      </div>
      <div id="servicecentraler" class="content-section">
        <h2>Biblioteket i stadens servicecentraler</h2>
        <p>Helsingfors stadsbibliotek betjänar äldre helsingforsare i samarbete med fem servicecentraler. Servicecentralen är en öppen mötesplats för pensionärer och arbetslösa i 
        Helsingfors, som vill ha någon att prata med, något att göra eller stöd i vardagen.</p>
        
        <h3>Djurbergets servicecentral</h3>
        <p>Besöksadress: Stormyrvägen 28, 00320 Helsingfors<br>
        Öppettider: <a href="https://www.hel.fi/helsinki/sv/social-och-halso/aldre/centraler/" target="_blank" aria-label="som servicecentralen. Länken öppnas i ett nytt fönster.">
        som servicecentralen</a>. Bibliotekspersonalen är anträffbar tis. och
        tors. kl. 9–11 och 12–15. Annars självbetjäning. Du behöver ett Helmet-bibliotekskort och en pinkod för att låna.</p>
        <p>Postadress: PB 8580, 00099 HELSINGFORS STAD<p>
            
        <h3>Gustafsgård servicecentral</h3>
        <p>Besöksadress: Gevaldigervägen 16, byggnad E, 00620 Helsingfors<br>
        Öppettider: som servicecentralen. Bibliotekspersonalen är anträffbar mån. och ons. kl. 9–11 och 12–15. Annars självbetjäning. Du behöver ett Helmet-bibliotekskort och en 
        pinkod för att låna.</p>
        <p>Postadress: PB 8560, 00099 HELSINGFORS STAD</p>
        
        <h3>Gårdsbacka servicecentral</h3>
        <p>Besöksadress: Gårdsgränden 5, 00940 Helsingfors<br>
        Öppettider: som servicecentralen. Bibliotekspersonalen är anträffbar tis. och tors. kl. 9–11 ovh 12–15. Annars självbetjäning. Du behöver ett Helmet-bibliotekskort och en 
        pinkod för att låna.</p>
        <p>Postadress: PB 8570, 00099 HELSINGFORS STAD</p>
        
        <h3>Kasbergets servicecentral</h3>
        <p>Besöksadress: Rödluvans väg 16, 00820 Helsingfors<br>
        Öppettider: som servicecentralen. Bibliotekspersonalen är anträffbar mån. och ons. kl. 9–11 och 12–15. Annars självbetjäning. Du behöver ett Helmet-bibliotekskort och en pinkod 
        för att låna.</p>
        <p>Postadress: PB 8590, 00099 HELSINGFORS STAD</p>
        
        <h3>Kvarnbäckens servicecentral</h3>
        <p>Besöksadress: Kvarnfärdsvägen 4, 00920 Helsingfors<br>
        Öppettider: som servicecentralen. Bibliotekspersonalen är anträffbar mån. och ons. kl. 9–11 och 12–15. Annars självbetjäning. Du behöver ett Helmet-bibliotekskort och en pinkod 
        för att låna.
        </p>Postadress: PB 8563, 00099 HELSINGFORS STAD</p>

        <h3>Ge respons</h3>
        <p>De här servicepunkterna utgör en del av HelMet-biblioteket. Mer information: Juha Kortesluoma, tf. bibliotekschef, tel. 09 310 27885.</p>
        <p><a href="http://www.hel.fi/www/helsinki/sv/stad-och-forvaltning/delta/feedback/anna-palautetta-sv" target="_blank" aria-label="Ge respons. Länken öppnas i ett nytt fönster.">
        Ge respons</a></p>
      </div>
      <div id="ambulerande" class="content-section">
        <h2>Ambulerande samlingar för samfund</h2>
        <p>Helsingfors stadsbibliotek erbjuder ambulerande samlingar för samfund: servicecentraler och andra gruppboenden för t.ex. äldre. Leverans och avhämtning med 8 veckors mellanrum.</p>
        <p>Ta kontakt om du vill veta mera.</p><p>Anne Suvanto<br>
        09 310 85805<br>
        anne.suvanto@hel.fi</p>
      </div>
      <p>Senast uppdaterad 16-12-2021</p>
   </div>
</div>

