<? $this->headTitle($this->translate('Palvelut yhteisöille')); $this->content()->setHeading($this->translate('Palvelut yhteisöille'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Kirjasto tekee yhteistyötä päiväkotien, koulujen ja palvelukeskusten kanssa.</p>
      </div>
     <div id="palvelut-kouluille" class="content-section">
        <h2>Palvelut kouluille</h2>
        <ul class="list-bullets">
          <li><a href="/Content/helsingin-kirjasto-kouluille">Helsingin kirjastojen palvelut kouluille</a></li>
          <li><a href="/Content/vantaan-kirjasto-kouluille">Vantaan kirjastojen palvelut kouluille</a></li>
          <li><a href="https://kulps.espoonkirjastot.fi" target="_blank" aria-label="Espoon kirjastojen palvelut kouluille. Linkki avautuu uudessa ikkunassa.">
          Espoon kirjastojen palvelut kouluille</a></li>
        </ul>
        <p>Kirjastokäyntien avulla oppilaita innostetaan tarinoiden, tiedon ja oppimisen pariin. Ryhmille on tarjolla mm. tiedonhaun opastusta, kirjastonkäytön opetusta sekä 
        kirjavinkkausta. Käyntien teema voidaan tarvittaessa räätälöidä luokan tarpeiden mukaan: oppilaat voivat esimerkiksi hakea tietoa äidinkielen tai historian esitelmäänsä varten. 
        Voit myös hankkia luokallesi oman kirjastokortin.</p>
        <p>Ota yhteyttä kirjastoon hyvissä ajoin, jotta saat sovittua vierailun parhaiten sinulle sopivaan päivään ja aikaan. Tee yhteydenotto noin neljä viikkoa ennen suunniteltua 
        vierailua. Myöhemminkin tehty tiedustelu voi tuottaa tuloksen (ei alle kahden viikon), mutta todennäköisyys onnistumiseen pienenee.</p>
        <p>Kerro viestissäsi seuraavat asiat:</p>
        <ul class="list-bullets">
          <li>Toivottu vierailupäivä ja -aika (on hyvä ehdottaa useampia sopivia viikonpäiviä ja aikoja)</li>
          <li>Luokka-aste ja oppilaiden määrä</li>
          <li>Millaisia lukijoita ryhmässä on; millaisista kirjoista lapset ovat kiinnostuneita</li>
          <li>Vierailun tyyppi (esim. tiedonhaun opetus, kirjavinkkaus, kirjaston käytön opetus)</li>
          <li>Mahdolliset erityistoiveet (esim. lukudiplomikirjojen vinkkaus, esitelmän tekemiseen liittyvän aineiston hakeminen jostakin tietystä aiheesta jne.)</li>
          <li>Muut vierailuun vaikuttavat asiat (erityisluokka, S2-luokka, erilainen oppija ryhmässä jne.)</li>
        </ul>
        <p>Ryhmäkäynnin voi sopia joko puhelimitse tai sähköpostitse. Oman lähikirjastosi yhteystiedot löydät <a href="/OrganisationInfo/Home">
        Kirjastot ja palvelut</a>-osiosta.</p>
        <p>Lasten monilukemisen tukeminen on yksi kirjaston keskeisiä tavoitteita. <a href="/Content/lukudiplomi">Lukudiplomin</a> 
        suorittaminen lisää lukuintoa ja tutustuttaa koululaiset mahdollisimman erilaisiin hyviin kirjoihin. Kirjastojen lukudiplomilistoissa on valittavina toisaalta paljon mukavaa uutta 
        luettavaa, toisaalta lasten- ja nuortenkirjallisuuden nykyklassikoita.</p><p>Eri ikäisille lukijoille on olemassa omat diplomilistat, joista löytyy sopivaa luettavaa. 
        Kaikki diplomin suorittaneet saavat suorituksestaan kunniakirjat.</p><p>Kirjastot osallistuvat myös mielellään koulun organisoimiin tempauksiin ja auttavat opettajia mm. sopivan 
        kauno- ja tietokirjallisuuden valinnassa. Kannattaa siis ottaa rohkeasti yhteyttä ja ehdottaa yhteistyötä!</p>
        <p>Viimeksi päivitetty 10.5.2022</p>
      </div>
      <div id="palvelukeskusten-kirjastopisteet" class="content-section">
        <h2>Palvelukeskusten kirjastopisteet</h2>   
        <p>Helsingin kaupunginkirjasto palvelee ikääntyneitä helsinkiläisiä yhteistyössä palvelukeskusten kanssa. Palvelukeskukset ovat avoimia kohtaamispaikkoja 
        helsinkiläisille eläkeläisille ja työttömille, jotka kaipaavat juttuseuraa, tekemistä tai tukea arkeen. Kirjasto tarjoaa jalkautuvaa palveluneuvontaa sekä lainaus- ja 
        palautuspalveluita viiden palvelukeskuksen yhteydessä.</p>
        
        <h3>Kontulan palvelukeskus</h3>
        <p>Käyntiosoite: Kontukuja 5, 00940 Helsinki<br>
        Avoinna: palvelukeskuksen aukioloaikoina. Kirjaston henkilökunta tavattavissa tiistaisin ja torstaisin klo 9–11 ja 12–15. Muina aikoina omatoimikäyttö.</p>
        <p>Asiakaspalvelusta vastaa Anne Suvanto p. 09 310 85805. Lainaus edellyttää Helmet-kirjastokorttia ja tunnuslukua.</p>
        <p><a href="https://www.facebook.com/kontulanmonipuolinenpalvelukeskus" target="_blank">Kontulan palvelukeskus Facebookissa</a>
        <br>Postiosoite: PL 8570, 00099 HELSINGIN KAUPUNKI</p>
        
        <h3>Kustaankartanon palvelukeskus</h3>
        <p>Käyntiosoite: Oltermannintie 32, rakennus E, 00620 Helsinki<br>
        Avoinna: palvelukeskuksen aukioloaikoina. Kirjaston henkilökunta tavattavissa maanantaisin ja keskiviikkoisin klo 9–11 ja 12–15. Muina aikoina omatoimikäyttö.</p>
        <p>Asiakaspalvelusta vastaavat Sonja Eerikäinen p. 09 310 85217 ja Anita Sailo p. 09 310 15957. Lainaus edellyttää Helmet-kirjastokorttia ja tunnuslukua.</p>
        <p><a href="https://www.facebook.com/Kustaankartanon-monipuolinen-palvelukeskus-538070456387386/" target="_blank">Kustaankartanon palvelukeskus Facebookissa</a>
        <br>Postiosoite: PL 8560, 00099 HELSINGIN KAUPUNKI</p>
        
        <h3>Myllypuron seniorikeskus</h3>
        <p>Käyntiosoite: Myllymatkantie 4, 00920 Helsinki<br>
        Avoinna: palvelukeskuksen aukioloaikoina. Kirjaston henkilökunta tavattavissa maanantaisin ja keskiviikkoisin klo 9–11 ja 12–15. Muina aikoina omatoimikäyttö.</p>
        <p>Asiakaspalvelusta vastaa Anne Suvanto p. 09 310 85805. Lainaus edellyttää Helmet-kirjastokorttia ja tunnuslukua.</p>
        <p><a href="https://www.facebook.com/seniorikeskusmyllypuro" target="_blank">Myllypuron seniorikeskus Facebookissa</a><br>
        Postiosoite: PL 8563, 00099 HELSINGIN KAUPUNKI</p>
        
        <h3>Riistavuoren palvelukeskus</h3>
        <p>Käyntiosoite: Isonnevantie 28, 00320 Helsinki<br>
        Avoinna: palvelukeskuksen aukioloaikoina. Kirjaston henkilökunta tavattavissa tiistaisin ja torstaisin klo 9–11 ja 12–15. Muina aikoina omatoimikäyttö.</p>
        <p>Asiakaspalvelusta vastaavat Sonja Eerikäinen p. 09 310 85217 ja Anita Sailo p. 09 310 15957. Lainaus edellyttää Helmet-kirjastokorttia ja tunnuslukua.<br><br>
        <a href="https://www.facebook.com/Riistavuoren-monipuolinen-palvelukeskus-1609321132627922/" target="_blank">Riistavuoren palvelukeskus Facebookissa</a><br>
        Postiosoite: PL 8580, 00099 HELSINGIN KAUPUNKI</p>
        
        <h3>Roihuvuoren palvelukeskus</h3>
        <p>Käyntiosoite: Punahilkantie 16, 00820 Helsinki<br>
        Avoinna: palvelukeskuksen aukioloaikoina. Kirjaston henkilökunta tavattavissa maanantaisin ja keskiviikkoisin klo 9–11 ja 12–15. Muina aikoina omatoimikäyttö.</p>
        <p>Asiakaspalvelusta vastaa Anne Suvanto p. 09 310 85805. Lainaus edellyttää Helmet-kirjastokorttia ja tunnuslukua.</p>
        <p><a href="https://www.facebook.com/roihuvuorenpalvelukeskus/" target="_blank">Roihuvuoren palvelukeskus Facebookissa</a><br>
        Postiosoite: PL 8590, 00099 HELSINGIN KAUPUNKI</p>
        
        <h3>Anna palautetta</h3>
        <p>Palvelukeskusten yhteydessä sijaitsevista Helsingin kaupunginkirjaston palvelupisteistä vastaa Koti- ja palvelukirjaston vs. johtaja Juha Kortesluoma p. 09 310 27885.
        Palvelupisteet ovat osa Helmet-kirjastoa.</p>
        <p><a href="http://www.hel.fi/www/helsinki/fi/kaupunki-ja-hallinto/osallistu-ja-vaikuta/palaute" target="_blank" aria-label="Anna palautetta. Linkki aukeaa uudessa ikkunassa.">
        Anna palautetta</a></p>
      </div>

     <div id="yhteisolainat" class="content-section">
        <h2>Toivekokoelmia lainaksi</h2>   
        <p>Helsingin kaupunginkirjasto lainaa ja toimittaa kirjastoaineistoa kiinnostuneille palvelu- ja ryhmäkodeille. Palvelun tarkoitus on edistää helsinkiläisten yhdenvertaisia 
        mahdollisuuksia kulttuuriin ja elinikäiseen oppimiseen sekä tukea lukemiskulttuuria yhteistyössä palvelu- ja ryhmäkotien kanssa.</p>
        <p>Kirjaston yhteyshenkilö kokoaa palvelu/ryhmäkodin toiveiden perusteella noin 30 kirjan paketin. Myös elokuvia, musiikkia ja pelejä voi lainata. Aineisto toimitetaan ja palautukset 
        noudetaan kahdeksan viikon välein.<br>Palvelua varten tulee palvelu-/ryhmäkodissa olla nimetty vastuuhenkilö.</p>
        <p>Myös poistokirjoja voi tiedustella.<br><strong>Lisätietoja: </strong>Anne Suvanto, puh. 09 310 85805, <a href="mailto:anne.suvanto@hel.fi">anne.suvanto@hel.fi</a></p>
      </div>
     <div id="kirjavinkkaus" class="content-section">
        <h2>Ikäihmisille suunnattua vinkkausta ja palveluneuvontaa</h2>
        <p>Kiinnostuneille yhteisöasiakkaille, ryhmille yms. tarjoamme vinkkausta ja neuvomme esim. Helmet.fi:n käytössä. Myös vapaaehtoisia ääneenlukijoita, ns. 
        lukulähettiläitä, voi tiedustella.</p>
        <p><strong>Lisätietoja: </strong>Liisa Värri, puh. 09 310 85911, <a href="mailto:liisa.varri@hel.fi">liisa.varri@hel.fi</a></p>
      </div>
   </div>
</div>


