<? $this->headTitle($this->translate('Patientbibliotek i Helsingfors')); $this->content()->setHeading($this->translate('Patientbibliotek i Helsingfors'));?>
<p>Helsingfors stadsbibliotek samarbetar med tre sjukhus.</p>
<h2>Aurora sjukhus</h2>
<p>Besöksadress: Nordenskiöldsgatan 20, byggnad 3 B, 2 vån, 00250 Helsingfors<br>
Postadress: PB 25402, 00099 HELSINGFORS STAD<br>
Öppet: tis och ons kl. 9–12 och 13–15<br>
Tel. 09 3106 5642</p>
<p>I bibliotekets utbud finns skönlitteratur och faktaböcker, men också ljudböcker, tidskrifter och musik (cd-skivor). Samlingen omfattar ca 3 000 böcker. Patienterna har också tillgång till 
bibliotekets kunddator.</p>
<p>För kundbetjäningen ansvarar Kati Hussein tfn 040 648 3046.</p>

<h2>Psykiatricentret</h2>
<p>Besöksadress: Fältskärsgatan 12, 2 vån, korridoren för administration, 00250 Helsingfors<br>
Postadress: PB 590, 00029 HNS<br>
Öppet: mån och tors kl. 12–15<br>
Tel. 09 4716 3716</p>
<p>I biblioteket utbud finns skönlitteratur och faktaböcker, men också ljudböcker. Samlingen omfattar ca 2 500 böcker. Patienterna har också tillgång till bibliotekets kunddator.</p>
<p>För kundbetjäningen ansvarar Kati Hussein tfn 040 648 3046.</p>

<h2>Nya barnsjukhuset</h2>
<p>I Nya Barnsjukhuset betjänar biblioteket i enlighet med ett nytt servicekoncept. I samarbetet ingår ett Läsebibliotek i Vardagsrummet för anhöriga samt gemensamma evenemang.</p>

<h2>Ge respons</h2>
<p>De här servicepunkterna utgör en del av HelMet-biblioteket. Mer information: Boken kommer/Juha Kortesluoma, tf. bibliotekschef, tel. 09 310 27885</p>
<p><a href="http://www.hel.fi/www/helsinki/sv/stad-och-forvaltning/delta/feedback/anna-palautetta-sv" target="_blank" aria-label="Ge gärna respons. Länken öppnas i ett nytt fönster.">
Ge gärna respons.</a></p>
