<? $this->headTitle($this->translate('Helsingin Koti- ja palvelukirjasto')); $this->content()->setHeading($this->translate('Helsingin Koti- ja palvelukirjasto'));?>
<p>Helsingin kaupunginkirjasto tekee palveluyhteistyötä kolmen sairaalan kanssa: Auroran sairaala, Psykiatriakeskus ja Uusi Lastensairaala. Potilaskirjastopalvelut on tarkoitettu vain potilaiden ja heidän 
läheistensä sekä henkilökunnan käyttöön.</p>
<h2>Potilaskirjastot</h2>
<h3>Auroran sairaalan potilaskirjastopalvelut</h3>
<p>Käyntiosoite: Nordenskiöldinkatu 20, rak. 3 B, 2. kerros, 00250 Helsinki<br>
Postiosoite: PL 25402, 00099 HELSINGIN KAUPUNKI<br>
Puh. 09 3106 5642<br>
Avoinna: ti ja ke 9–12 ja 13–15</p>
<p>Kirjaston valikoimassa on kauno- ja tietokirjallisuuden ohella äänikirjoja, aikakauslehtiä ja musiikkia (cd-levyjä). Kokoelma sisältää noin 3 000 kirjaa. Potilaiden käytössä on myös kirjaston 
asiakastietokone.<br>
<p>Asiakaspalvelusta vastaa Kati Hussein p. 040 648 3046.</p>

<h3>Psykiatriakeskuksen potilaskirjastopalvelut</h3>
<p>Käyntiosoite: Välskärinkatu 12, 2. kerros, toimistokäytävällä, 00250 Helsinki<br>
Postiosoite: PL 590, 00029 HUS<br>
Puh. 09 4716 3716<br>
Avoinna: ma ja to klo 12–15</p>
<p>Kirjaston valikoimassa on kauno- ja tietokirjallisuuden ohella äänikirjoja. Kokoelma sisältää noin 2 500 kirjaa. Potilaiden käytössä on myös kirjaston asiakastietokone.</p>
<p>Asiakaspalvelusta vastaa Kati Hussein p. 040 648 3046.</p>

<h3>Uusi Lastensairaala</h3>
<p>Uuteen lastensairaalaan Helsingin kaupunginkirjasto jalkautuu konseptilla, johon kuuluu Lukukirjasto ja tapahtumayhteistyö. Varsinaista lainaus- tai palautustoimintaa ei ole, vaan perheet voivat 
valita luettavaa silloin kun heille sopii, omatoimiperiaatteella.</p>
<p>Lukukirjasto löytyy vanhempien olohuoneesta. Lukukirjaston kirjoja perheet voivat napata mukaan useimpiin huoneisiin.</p>
<p><a href="http://www.hus.fi/sairaanhoito/sairaalat/Uusi-lastensairaala/Sivut/default.aspx" target="_blank" 
aria-label="Lisätietoja Uudesta lastensairaalasta. Linkki aukeaa uudessa ikkunassa.">Lisätietoja Uudesta lastensairaalasta.</a></p>

<h2>Anna palautetta</h2>
<p>Helsingin kaupunginkirjaston potilaskirjastopalveluista vastaa Koti- ja palvelukirjaston vs. johtaja Juha Kortesluoma, p. 09 310 27885. Palvelupisteet ovat osa Helmet-kirjastoa.</p>
<p><a href="http://www.hel.fi/www/helsinki/fi/kaupunki-ja-hallinto/osallistu-ja-vaikuta/palaute" target="_blank" aria-label="Anna palautetta. Linkki aukeaa uudessa ikkunassa.">
Anna palautetta.</a></p>

