<h1>Helmet-kirjaston käyttösäännöt viron kielellä</h1>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Tere tulemast Helmeti raamatukogu lugejaks!</p>
        <p>Lugeja on kohustatud tutvuma raamatukogu kasutuseeskirjaga ja kohustub seda täitma.</p>
      </div>
     <div id="helmet" class="content-section">
        <h2>Mis on Helmet?</h2>
        <p>Helmeti raamatukogud asuvad Helsingis, <br>
        Espoos, Kauniainenis ja Vantaas. <br>
        Helmet on nende linnade ühine raamatukoguvõrgustik <br>
        <br>
        Sõna Helmet on moodustatud ingliskeelsest nimetusest <br>
        Helsinki Metropolitan Area Libraries, <br>
        st Suur-Helsingi raamatukogud. <br>
        <br>
        Helmeti raamatukogudel on ühine <br>
        kasutajate andmebaas ja raamatukogusüsteem. <br>
        See tähendab, et <br>
        kui sul on Helmeti raamatukogukaart, <br>
        võid laenutada kõikidest Helmeti raamatukogudest. <br>
        <br>
        Helmeti raamatukogud on kõigile avatud. <br>
        Kasutajal on võimalus laenutada raamatuid ja muid materjale<br>
        ning kasutada raamatukogu teenuseid ja ruume. <br>
        Raamatukogu kasutajana <br>
        vastutad ka sina selle <br>
        kogude, vara ja ruumide eest. </p>
      </div>
      <div id="kirjaston-saannot" class="content-section">
        <h2>Pea kinni raamatukogu kasutuseeskirjast</h2>
        <p>Raamatukogukaardi saamisega <br>
        kaasneb kohustus pidada kinni raamatukogu kasutuseeskirjast.</p><p>Sama kasutuseeskiri kehtib ka kontaktisikule. <br>
        Kontaktisik on näiteks kooli <br>
        või mõne asutuse töötaja, <br>
        kellele on väljastatud selle kooli või asutuse raamatukogukaart. <br>
        Kontaktisik vastutab selle eest, <br>
        et kõik selle asutuse töötajad <br>
        kasutavad raamatukogukaarti õigesti.</p>
      </div>
      <div id="raamatukogukaart" class="content-section">
        <h2>Raamatukogukaart ja PIN-kood</h2>
        <h3>Raamatukogukaart</h3>
        <p>Raamatukogukaardi olemasolu korral <br>
        on sul õigus laenutada <br>
        raamatuid ja teisi materjale. <br>
        Raamatukogukaardi saad ükskõik millisest <br>
        Helmeti raamatukogust või raamatukogubussist. <br>
        <br>
        Koos raamatukogukaardiga saad PIN-koodi, <br>
        mille abil pääsed ligi erinevatele teenustele. <br>
        Esmane raamatukogukaart on tasuta. </p>
        <h3>Raamatukogukaart on isiklik</h3>
        <p>Raamatukogukaart on isiklik.</p>
        <p>Seda ei või kasutada keegi teine. <br>
        Raamatukogukaarti ei tohi anda teisele inimesele ka siis, <br>
        kui kasutad iseteenindust. <br>
        Iseteeninduses ei ole koha peal <br>
        raamatukogu töötajat, lugeja laenutab <br>
        ja tagastab materjalid iseseisvalt. <br>
        Kui märkad või kahtlustad, <br>
        et keegi teine kasutab sinu lugejakaarti, <br>
        pöördu raamatukogu töötaja poole.<br>
        <br>
        Raamatukogu töötaja võib küsida isikut tõendavat dokumenti, <br>
        kui keegi laenutab sinu kaardiga. <br>
        Mitte keegi teine ei tohi kasutada sinu kaarti. <br>
        <br>
        Kui laenutad raamatukogust raamatuid <br>
        või muud materjali, vastutad laenutatud materjali eest. <br>
        Laenatud materjalid tuleb tagastada heas seisukorras. <br>
        <br>
        Kui sinu kaart on kooli <br>
        või mõne asutuse ühine kaart, <br>
        võivad seda kasutada ka teised töötajad. <br>
        Kaardi eest vastutab kontaktisik, <br>
        kes annab loa selle kasutamiseks.<br>
        <br>
        Kui märkad või kahtlustad, <br>
        et keegi teine kasutab sinu raamatukogukaarti, <br>
        pöördu raamatukogu töötaja poole.<br>
        <br>
        Raamatukogu töötaja võib küsida isikut tõendavat dokumenti, <br>
        kui märkab, et keegi laenab teavikuid sinu kaardiga. <br>
        Mitte keegi teine ei tohi kasutada sinu kaarti. <br>
        <br>
        Kui laenutad raamatukogust raamatuid <br>
        või muud materjali, vastutad laenutatud materjali eest. <br>
        Laenutatud raamatud või esemed tuleb tagastada heas seisukorras. <br>
        <br>
        Kui sinu kaart on kooli <br>
        või mõne asutuse ühine kaart, <br>
        võivad seda kasutada ka teised töötajad. <br>
        Kaardi eest vastutab kontaktisik, <br>
        kes annab loa selle kasutamiseks.</p>
        
        <h3>Lugejaks registreerimine</h3>
        <p>Raamatukogukaardi saad kehtivaisikut tõendava dokumendi <br>
        ja aadressi esitamisel. <br>
        Raamatukogukaardi saad ükskõik millisest <br>
        Helmeti raamatukogust või raamatukogubussist. <br>
        <br>
        Raamatukogukaardi saad ainult sel juhul, <br>
        kui sul on Soomes aadress. <br>
        Pead esitama ka dokumendi, <br>
        millel on sinu foto ja isikukood. <br>
        Sobivad järgmised dokumendid: </p>
        <ul class="list-bullets">
          <li>ELi riigi isikut tõendav dokument</li>
          <li>pass</li>
          <li>Soome juhiluba</li>
          <li>fotoga Kela kaart, alla 18aastasel ka fotota Kela kaart</li>
          <li>Soome vastuvõtukeskuse elaniku kaart</li>
          <li>migratsiooniameti välja antud elamisluba.</li>
        </ul><p>Kui sul ei ole Soome isikukoodi, <br>
        on raamatukogukaardi kehtivusaeg 1 aasta. <br>
        <br>
        Alla 15aastane laps saab raamatukogukaardi ainult <br>
        hooldaja nõusolekul. <br>
        Hooldaja on enamasti kas ema või isa, <br>
        vahel ka keegi teine vastutav isik. <br>
        Hooldaja peab esitama kirjaliku nõusoleku selle kohta, <br>
        et laps saab isikliku raamatukogukaardi.                                           Last lugejaks registreerides peab ka laps ise kohal olema.<br>
        Kui alla 15aastane laenutab raamatukogust midagi, <br>
        vastutab nende materjalide eest lapse hooldaja. <br>
        Näiteks kui laps kaotab raamatukogu teaviku <br>
        peab hooldaja selle hüvitama. <br>
        <br>
        Raamatukogukaarte väljastatakse ka näiteks <br>
        lasteaedadele, koolidele või muudele asutustele ja kollektiividele. <br>
        Kaart väljastatakse kontaktisikule, <br>
        kes vastutab kaardi kasutamise eest. <br>
        Kontaktisiku ülesanne on jälgida, <br>
        et teised kasutaksid raamatukogukaarti õigesti. <br>
        Asutuse raamatukogukaart kehtib korraga ühe aasta.</p>
        
        <h3>Raamatukogukaardi kaotamine</h3>
        <p>Raamatukogukaardi kaotamise korral <br>
        teavita sellest kohe raamatukogu. <br>
        Kui kaob asutuse raamatukogukaart, <br>
        peab kontaktisik sellest teavitama. <br>
        <br>
        Kui raamatukogu on suletud, võid raamatukogule <br>
        jätta sõnumi kaardi kaotamise kohta kõnepostile. <br>
        Selleks helista numbrile 09 3108 5309. <br>
        <br>
        Raamatukogukaardi kaotusest teavitamise järel <br>
        kõrvaldab raamatukogu selle kasutusest. <br>
        Kui keegi teine proovib pärast kaardi kaotusest teadaandmist sellega laenutada, <br>
        ei vastuta sina laenutatud materjalide eest.</p>
        
        <h3>PIN-kood</h3>
        <p>Raamatukogukaardi kasutamiseks vajad PIN-koodi. <br>
        Selle abil saad kasutada </p>
        <ul class="list-bullets">
          <li>raamatukogu võrguteenuseid, </li>
          <li>automaate, </li>
          <li>arvuteid </li>
          <li>ja iseteenindust. </li>
        </ul><p>Koodi vajad ennekõike siis, <br>
        kui laenutad automaadist. <br>
        Automaati ei saa ilma PIN-koodi sisestamata kasutada. <br>
        <br>
        PIN-koodi saad raamatukogust või raamatukogubussist <br>
        isikut tõendava dokumendi alusel. <br>
        PIN-koodi ei saadeta e-posti teel ega anta telefoni teel. </p>
        
        <h3>Isikuandmed</h3>
        <p>Hoolitse selle eest, <br>
        et raamatukogul on sinu kehtivad kontaktandmed. <br>
        Teavita raamatukogu sellest, kui sinu aadress, <br>
        e-posti aadress või nimi muutub. <br>
        Oma andmeid saad kontrollida <br>
        sisselogituna raamatukogu veebilehel <br>
        aadressil www.helmet.finna.fi. <br>
        Oma andmed leiad alalehelt „Omat tiedot“ (kasutaja andmed). <br>
        <br>
        Laenutajate andmeid säilitatakse <br>
        raamatukogu kasutajate andmebaasis.<br>
        Seal on ka asutuste vastutavate <br>
        ja kontaktisikute andmed. <br>
        <br>
        Raamatukogu hoolitseb selle eest, <br>
        et raamatukogule edastatud teave <br>
        on klientide andmebaasis korrektne. <br>
        <br>
        Raamatukogu järgib klientide andmebaasi <br>
        haldamisel andmekaitseseadust. <br>
        Andmekaitseseaduse kohaselt on raamatukogul <br>
        õigus salvestada kasutaja isikukood. <br>
        <br>
        Sul on õigus kontrollida, <br>
        millised isikuandmed on raamatukogu andmebaasis sinu kohta. <br>
        Seda teavet saad raamatukogu klienditeenindusest <br>
        isikut tõendava dokumendi alusel. <br>
        Alla 15aastase lapse hooldaja <br>
        näeb tema kohta salvestatud teavet, <br>
        näiteks hilinenud tagastuste kohta. <br>
        Peale selle näed teavet maksmata tasude kohta. <br>
        Asutuse kontaktisikul on õigus <br>
        näha teavet oma asutuse kohta. <br>
        <br>
        Kasutajate andmebaasi kohta saad rohkem teavet <br>
        andmebaasi kirjeldusest. <br>
        Andmebaasi kirjeldus on väljas raamatukogudes ja veebilehel osas<br>
        "“ (andmebaasi kirjeldus). <br>
        Andmebaasi kirjeldus ei ole esitatud lihtsas keeles.</p>
      </div>
      <div id="laenutamine" class="content-section">
        <h2>Laenutamine, tagastamine ja pikendamine</h2>
        <h3>Laenutamine</h3>
        <p>Laenutusaeg on 1‒28 päeva. <br>
        Eri materjalidel on erinev laenutusaeg. <br>
        Täpsem teave laenutusaja kohta <br>
        on toodud kasutuseeskirjades. <br>
        Korraga võid laenutada kuni 100 teavikut. <br>
        <br>
        Raamatu või muu materjali laenutamisel <br>
        antakse sulle alati tagastustähtaeg. <br>
        Tagastustähtaeg on päev, <br>
        millal pead teaviku tagastama. <br>
        Tagastustähtaeg on kirjas kviitungil, <br>
        mille saad koos teavikuga. <br>
        <br>
        Filme ja mänge ei laenutata määratud vanusepiirangust <br>
        noorematele. <br>
        Näiteks alla 15aastane ei saa laenutada <br>
        filme või mänge, millel on vanusepiirang 15 aastat. <br>
        Vanusepiirangu kehtestamise eest vastutab Soome riiklik<br>
        audiovisuaalne instituut Kavi <br>
        ning selle meediahariduse ja videosalvestiste esitamise üksus MEKU.</p>
        
        <h3>Tagastamine</h3>
        <p>Tagasta laenatud raamat hiljemalt tagastustähtajal. <br>
        Raamatut ei pea viima tagasi sinna raamatukogusse, <br>
        kust selle laenutasid. <br>
        Võid selle viia ükskõik millisesse <br>
        Helmeti raamatukogusse. <br>
        <br>
        Soovi korral saad tagastamiskviitungi. <br>
        <br>
        Osades raamatukogudes on kasutusel tagastusluuk. <br>
        Kui raamatukogu on suletud, on võimalus laenutused tagastada ka<br>
        tagastusluugi kaudu. <br>
        Raamatukogu registreerib teose tagastatuks <br>
        järgmisel tööpäeval. <br>
        Kui tagastusluugi kaudu tagastatud materjal kaob, <br>
        pead selle hüvitama. <br>
        <br>
        Tagastustähtaja lähenemisel võid saada selle kohta kaks päeva varem <br>
        meeldetuletuse. <br>
        Teavitus saadetakse e-posti teel, <br>
        kui raamatukogul on sinu e-posti aadress. <br>
        Kui soovid saada e-posti teel meeldetuletust, <br>
        teavita sellest raamatukogu.</p>
        
        <h3>Pikendamine</h3>
        <p>Laenutusaega saab pikendada <br>
        viis korda. <br>
        Pikendada saad raamatukogus, raamatukogubussis <br>
        või internetis veebilehel www.helmet.finna.fi. <br>
        Laenutusaja pikendamiseks veebis pead sisse logima. <br>
        Sisselogimiseks vajad raamatukogukaardi numbrit <br>
        ja PIN-koodi. <br>
        <br>
        Laenutusaega ei saa pikendada, kui keegi <br>
        on end pannud samale teavikule järjekorda. <br>
        Tähtaega ei saa pikendada ka sel juhul, <br>
        kui sinu laenutusõigus on peatatud. <br>
        <br>
        Kõikide raamatute laenutusaega ei saa pikendada. <br>
        Näiteks ei saa pikendada menukite tagastusaega <br>
        ja enim laenutatud teavikuid<br>
        ei saa uuesti laenutada.</p>
      </div>
      <div id="jarjekorda-lisamine" class="content-section">
        <h2>Järjekorda lisamine ja raamatukogude vaheline laenutus</h2>
        <h3>Järjekorda lisamine</h3>
        <p>Raamatukogus saad end teose <br>
        laenutusjärjekorda panna. <br>
        Järjekorda võid end lisada ka <br>
        raamatukogu veebilehel www.helmet.fi. <br>
        Selleks pead kasutajana sisse logima. <br>
        Sisselogimiseks vajad raamatukogukaardi numbrit <br>
        ja PIN-koodi. <br>
        <br>
        Korraga võid olla kuni 100teavikut järjekorras. <br>
        Kui järjekord jõuab sinuni, <br>
        saadetakse sulle selle kohta teavitus. <br>
        Teavitus saadetakse kas posti, <br>
        e-posti või lühisõnumiga. <br>
        <br>
        Asjade, näiteks töövahendite ja uiskude, <br>
        laenutusjärjekorda ei saa end panna. <br>
        Mõlemaid saab laenutada raamatukogust.</p>
        
        <h3>Raamatukogude vaheline laenutus</h3>
        <p>Kui soovid panna end selliste teoste järjekorda, <br>
        mida ei ole Helmeti raamatukogudes, <br>
        saab raamatukogu selle laenutada <br>
        mõnest muust Soome või välismaa raamatukogust. <br>
        Raamatukogude vaheline laenutus on tasuline. <br>
        <br>
        Raamatukogude vahelise laenutuse teenus <br>
        ei laiene teostele, mida saab teistest pealinna<br>
        piirkonna raamatukogudest, <br>
        näiteks teadus- <br>
        või erialaraamatukogust.</p>
      </div>
      <div id="raamatukogu-tasud" class="content-section">
        <h2>Raamatukogu tasud</h2>
        <p>Raamatukogu kasutamine on üldjuhul tasuta.<br>
        Kui aga ületad laenutustähtaja,<br>
        pead maksma viivist.<br>
        Kui sa ei tule järjekorda pandud teosele järele,<br>
        pead selle eest tasuma.<br>
        Ning kui kaotad raamatukogu materjali,<br>
        pead selle hüvitama.<br>
        Ka eriteenused, näiteks raamatukogude vaheline laenutamine,<br>
        on tasulised.<br>
        <br>
        Teave kõikide raamatukogu<br>
        kehtestatud tasude kohta<br>
        on <a href="www.helmet.fi/fi-FI/content/37588/1" target="_top">toodud kasutuseeskirjades</a>.<br>
        <br>
        Raamatukogu ei vastuta selle eest,<br>
        kui laenutatud materjal kahjustab sinu seadet.<br>
        Raamatukogu ei korva sinu seadme kahju.<br>
        Raamatukogu ei vastuta ka kahjude eest,<br>
        mille põhjustad raamatukogust<br>
        laenutatud töövahendiga.</p>
        
        <h3>Viivis ja hüvitamine</h3>
        <p>Kui ületad laenutustähtaja,<br>
        pead maksma viivist.<br>
        Viivist pead maksma iga ületatud päeva eest,<br>
        kuni on saavutatud maksimaalne viivise määr.<br>
        <br>
        Laste ja noorte osakonna materjalide eest<br>
        ei pea maksma viivist.<br>
        <br>
        Viivist ei pea maksma juhul,<br>
        kui sul ei õnnestu tehnilise vea tõttu<br>
        laenutusaega pikendada.<br>
        Tehniline viga on näiteks<br>
        internetiühenduse tõrge.<br>
        <br>
        Kui kahjustad või kaotad raamatukogu vara,<br>
        pead selle hüvitama.<br>
        Täpse teabe materjalide hüvitamise kohta<br>
        leiad kasutuseeskirjadest.</p>
        
        <h3>Laenutusaja ületamine ja viivis</h3>
        <p>Kui sa ei tagasta teost tähtajaks,<br>
        saadetakse sulle kaks meeldetuletust.<br>
        Esimene meeldetuletus saadetakse<br>
        14 päeva pärast laenutustähtaega.<br>
        Teine meeldetuletus saadetakse<br>
        28 päeva pärast laenutustähtaega.<br>
        Esimese meeldetuletuse võib saada<br>
        e-posti teel.<br>
        <br>
        Meeldetuletuse saamisel<br>
        pead tagastama laenutatud materjalid raamatukokku<br>
        ja tasuma viivise.</p>
        
        <h3>Mis juhtub, kui sa ei tasu viivist?</h3>
        <p>Kui sa ei maksa nõutud viivist,<br>
        kasutab raamatukogu inkassoteenust.<br>
        Raamatukogu annab võla üle inkassofirmale,<br>
        kui maksetähtpäeva on ületatud 60 päeva.<br>
        <br>
        Inkassofirmale antakse edasi vaid täiskasvanute võlad.<br>
        Kui klient on alla 18aastane,<br>
        ei anta võlgu edasi inkassofirmale.<br>
        <br>
        Lisateavet inkassoteenuse kohta<br>
        leiad <a href="www.helmet.fi/fi-FI/content/37588/1" target="_top">kasutuseeskirjadest</a>.</p>
        
        <h3>Kasutusõiguse kaotamine</h3>
        <p>Kui sa ei tasu oma võlga raamatukogule,<br>
        võidakse sinu kasutusõigus kaotada.<br>
        Sel juhul kaotad laenutusõiguse <br>
        ehk sa ei saa enam raamatukogu materjale laenutada.<br>
        <br>
        Laenutusõigusest jääd ilma, kui</p>
        <ul class="list-bullets">
          <li>oled ületanud laenutustähtaega 28 päeva;</li>
          <li>oled kaotanud raamatukogu materjali;</li>
          <li>oled kahjustanud raamatukogu materjali;</li>
          <li>oled raamatukogule võlgu suurima võimaliku summa.</li>
        </ul><p>Võimaliku suurima summa kohta saad teavet<br><a href="www.helmet.fi/fi-FI/content/37588/1" target="_top">kasutuseeskirjadest</a>.<br>
        <br>
        Siinjuures kehtib üks erand:<br>
        kui sinu võlgade tasumise suhtes on vormistatud kokkulepe,<br>
        mis sisaldab ka võlga raamatukogule,<br>
        ei kaota sa laenutusõigust.</p>
        
        <h3>Laenutusõiguse taastamine</h3>
        <p>Sinu õigus laenutada taastub,<br>
        kui tagastad raamatukogule tähtaja ületanud materjali,<br>
        hüvitad kadunud või kahjustunud materjali<br>
        tasud oma võla raamatukogule.<br>
        Kui tasutud summa on korras,<br>
        saad uuesti raamatukogust laenutada.<br>
        <br>
        Kui sinu võlg on inkassos,<br>
        tegeleb sinu võlaga inkassofirma.<br>
        Sel juhul pead tasuma võlasumma inkassofirmale,<br>
        kes maksab selle raamatukogule.<br>
        Raamatukogu kontrollib laekunud makse.<br>
        Kui kõik on korras,<br>
        saad uuesti raamatukogust laenutada.</p>
      </div>
      <div id="kasutuskeeld" class="content-section">
        <h2>Raamatukogu kasutuskeeld</h2>
        <p>Võid kaotada õiguse raamatukogu kasutada,<br>
        kui sa ei pea kinni selle kasutuseeskirjadest.<br>
        Kasutuskeelu võid saada näiteks,<br>
        kui häirid teisi raamatukogu kasutajaid,<br>
        tekitad raamatukogus ohtliku olukorra<br>
        või kahjustad raamatukogu vara.<br>
        Kasutuskeeld on ajutine,<br>
        kõige rohkem 30 päeva.<br>
        <br>
        Raamatukogu esitab kasutuskeelu kohta ametliku otsuse.<br>
        Sul on õigus otsus edasi kaevata<br>
        ja taotleda selle muutmist.<br>
        Enne kasutuskeelu jõustumist<br>
        on sul õigus esitada<br>
        oma nägemus olukorrast.<br>
        <br>
        Kasutuskeelu kohta tehakse märge<br>
        raamatukogu klientide andmebaasi.<br>
        Raamatukogu eemaldab selle märke,<br>
        kui kasutusõigus taastatakse.</p>
      </div>
      <div id="kasutuseeskirjad" class="content-section">
        <h2>Kasutuseeskirjad</h2>
        <p>Kasutuseeskirju muudetakse vaid<br>
        ametliku otsuse alusel.<br>
        Samad eeskirjad kehtivad ka raamatukogubussides,<br>
        haruraamatukogudes ja laenutuse koduteenuse puhul<br>
        nii palju kui see on võimalik.<br>
        <br>
        Need eeskirjad kehtivad alates 1. veebruarist 2023<br>
        tähtajatult.<br>
        Eeskirjade tühistamisest tuleb ette teatada kuus kuud.<br>
        Need eeskirjad asendavad 1. veebruaril 2021. aastal vastu võetud<br>
        eeskirju.</p>
      </div>
      <div id="lisateave" class="content-section">
        <h2>Lisateave</h2>
        <p>Kasutuseeskirjade faili ja lisateavet soome keeles<br>
        leiad Helmeti veebilehelt osast "<a href="https://www.helmet.fi/fi-FI/Info/Asiakkaana_kirjastossa" target="_top">Asiakkaana kirjastossa</a>“ (raamatukogu kasutamine)</p>
      </div>
   </div>
</div>
