<? $this->headTitle($this->translate('Tillgänglighetsutlåtande')); $this->content()->setHeading($this->translate('Tillgänglighetsutlåtande'));?>
<p>Detta tillgänglighetsutlåtande gäller webbplats "Helmet". Webbplatsens adress är https://www.helmet.fi.</p>

<h2>Lagbestämmelser som gäller webbplatsen</h2>
<p>Denna webbplats har offentliggjorts tidigare än 23.9.2018. Webbplatsen ska uppfylla lagens krav på tillgänglighet efter övergångstiden som slutar 23.9.2020.</p>

<h2>Fullgörandestatus</h2>
<p>Denna webbplats uppfyller lagstadgade kritiska tillgänglighetskrav enligt nivå AA i WCAG v2.1 med följande observerade brister.</p>

<h2>Icke tillgängligt innehåll</h2>
<p>Nedan angivet innehåll uppfyller ännu ej alla lagstadgade tillgänglighetskrav.</p>
<h3>Upptäckta brister</h3>
<ul class="list-bullets">
    <li><b>Beskrivningarna av vissa länkar på webbplatsen är bristfälliga. (2.4.4 Länkens syfte (i kontext))</b> Rättning av brister: 
    De bristfälliga länkarna i artiklarna åtgärdas. Webbplatsens innehållsproducenter har fått anvisningar för hur de beskriver länkarna korrekt.</li>
    <li><b>På webbplatsen finns textinnehåll som inte översatts. (3.1.2 Delarnas språk)</b> Rättning av brister: Orsaken till bristerna i översättningen 
    av tjänstemenyn är ett tekniskt fel, som leder till att alla översatta texter inte visas korrekt på språkversionerna av sidorna. Serviceproducenten 
    har ombetts att åtgärda felet så snabbt som möjligt.</li>
    <li><b>På webbplatsen finns pdf-dokument som inte är tillgängliga för en skärmläsare. (1.1.1 Icke-textuellt innehåll, 4.1.2 Namn, roll, värde)</b> Rättning av brister: 
    De upptäckta bristerna åtgärdas genom att pdf-dokumenten konverteras, i första hand till html-format.</li>
    <li><b> Webbplatsens chattfunktion är inte tillgänglig med teknologiska hjälpmedel. (4.1.3 Meddelanden om status)</b> Rättning av brister: En begäran om offert på ett tillgängligt 
    alternativ till chattjänsten har skickats till leverantören av chattjänsten. Webbplatsen övergår till en tillgänglig chatt så snart det är möjligt.</li>
</ul>

<h3>Få uppgifter i tillgänglig form</h3>
<p>Innehåll som inte kan nås på grund av nämnda brister kan begäras från upprätthållaren av denna webbplats.</p>
<p>e-post <u><a href="mailto:palaute@helmetkirjasto.fi">palaute@helmetkirjasto.fi</a></u></p>
<p>responsformulär <a href="http://www.helmet.fi/respons">www.helmet.fi/respons</a></p>

<h2>Utarbetande av tillgänglighetsutlåtande</h2>
<p>Detta utlåtande har utarbetats 17.9.2020.</p>

<h3>Bedömning av tillgänglighet</h3>
<p>Vid bedömning av tillgänglighet har följts Helsingfors stads arbetsanvisning och metoder som siktar till att säkerställa webbplatsens tillgänglighet i alla arbetsfaser.</p>
<p>Tillgängligheten är kontrollerad genom revision av en extern expert samt som egen bedömning.</p>
<p>Tillgängligheten är kontrollerad med hjälp av automatisk tillgänglighetskontroll samt manuell kontroll av webbplatsen och innehållet. 
Automatiska kontroller har utförts med användning av webbläsartillägget Siteimprove.</p>

<h3>Uppdatering av tillgänglighetsutlåtande</h3>
<p>Webbplatsens tillgänglighet kontrolleras genom kontinuerlig tillsyn när tekniken eller innehållet förändras, samt granskning med regelbundna intervall. 
Detta utlåtande uppdateras i samband med ändringar av webbplatsen samt granskningar av tillgänglighet.</p>

<h2>Återkoppling och kontaktuppgifter</h2>
<p>För webbplatsens tillgänglighet svarar Helsingfors, Esbo, Vanda och Grankulla stadsbibliotek.</p>
<p>e-post <u><a href="mailto:palaute@helmetkirjasto.fi">palaute@helmetkirjasto.fi</a></u></p>
<p>responsformulär <a href="http://www.helmet.fi/respons">www.helmet.fi/respons</a></p>

<h3>Anmälan om ej tillgängligt innehåll</h3>
<p>Om användaren upplever att kraven på tillgänglighet ändå inte uppfylls kan detta anmälas per e-post <a href="mailto:palaute@helmet-kirjasto.fi">palaute@helmet-kirjasto.fi</a> 
eller med responsformulär på <a href="http://www.helmet.fi/respons">www.helmet.fi/respons</a>.</p>

<h3>Begäran om uppgifter i tillgänglig form</h3><p>Om användaren inte upplever sig få webbplatsens innehåll i tillgänglig form, kan användaren begära dessa uppgifter per e-post 
<a href="mailto:palaute@helmet-kirjasto.fi">palaute@helmet-kirjasto.fi</a> eller med responsformulär på <a href="http://www.helmet.fi/respons">www.helmet.fi/respons</a>.</p>

<h2>Rättsskydd för tillgänglighet, Verkställighetsförfarande</h2>
<p>Om en person upplever att svar inte har erhållits på hans eller hennes anmälan eller förfrågan, eller om svaret inte är tillfredsställande, 
kan saken anmälas till regionförvaltningsverket i Södra Finland. På webbplatsen för regionförvaltningsverket i Södra Finland finns detaljerad information om hur saken behandlas.</p>
<p>Regionförvaltningsverket i Södra Finland<br>
Enheten för tillgänglighetstillsyn<br><a href="https://www.xn--tillgnglighetskrav-ptb.fi/">https://www.xn--tillgnglighetskrav-ptb.fi/</a><br>
<a href="mailto:webbtillganglighet@rfv.fi">webbtillganglighet@rfv.fi</a><br>
Telefonväxel 0295 016 000<br>
Öppet: må–fr kl. 8.00–16.15</p>

<h2>Godkännande av tillgänglighetsutlåtande</h2>
<p>Detta utlåtande har godkänts 22.9.2020</p>
<p>Helmet-bibliotek</p><p>Helsingfors, Esbo, Vanda och Grankulla stadsbibliotek</p>