<? $this->headTitle($this->translate('Saavutettavuusseloste')); $this->content()->setHeading($this->translate('Saavutettavuusseloste'));?>
<p>Tämä saavutettavuusseloste koskee Helsingin, Espoon, Vantaan ja Kauniaisten kaupunginkirjastojen Helmet-verkkosivua. Sivuston osoite on https://www.helmet.fi/fi-FI.</p>
<h2>Sivustoa koskevat lain säädökset</h2>
<p>Tämä sivusto on julkaistu aiemmin kuin 23.9.2018. Sivuston tulee täyttää lain edellyttämät saavutettavuuden vaatimukset 23.9.2020 päättyvän siirtymäajan jälkeen.</p>

<h2>Vaatimustenmukaisuustilanne</h2>
<p>Tämä verkkosivusto täyttää lain asettamat kriittiset saavutettavuusvaatimukset WCAG v2.1 -tason AA mukaisesti seuraavin havaituin puuttein.</p>
<h2>Ei-saavutettava sisältö</h2>
<p>Jäljempänä mainittu sisältö ei vielä täytä kaikkia lain asettamia saavutettavuusvaatimuksia.</p>

<h3>Havaitut puutteet</h3>
<ul class="list-bullets">
  <li><b>Sivuston joidenkin linkkien kuvaukset ovat puutteellisia. (2.4.4 Linkin tarkoitus (kontekstissa))</b> Puutteiden korjaus: Puutteellisia linkkejä artikkeleissa korjataan. 
Sivuston sisällöntuottajia on ohjeistettu kuvaamaan linkit oikein.</li>
  <li><b>Sivustolla on kääntämätöntä tekstisisältöä. (3.1.2 Osien kieli)</b> Puutteiden korjaus: Palveluvalikon käännöspuutteiden syynä on tekninen virhe, 
jonka vuoksi kaikki käännetyt tekstit eivät näy kieliversiosivuilla oikein. Palvelun tuottajaa on pyydetty korjaamaan virhe mahdollisimman pian.</li>
  <li><b>Sivustolla on pdf-dokumentteja, jotka eivät ole ruudunlukijalla saavutettavia. (1.1.1 Ei-tekstuaalinen sisältö, 4.1.2 Nimi, rooli, arvo)</b> 
  Puutteiden korjaus: Havaitut puutteet korjataan muuntamalla pdf-dokumentteja ensisijaisesti html-muotoon.</li>
  <li><b>Sivuston chat-toiminto ei ole avustavalla teknologialla saavutettava. (4.1.3 Tilasta kertovat viestit)</b> Puutteiden korjaus: Chat-palvelun tarjoajalta on pyydetty tarjousta 
  saavutettavasta vaihtoehdosta chat-toiminnolle. Sivustolla siirrytään saavutettavaan chatiin niin pian kuin se on mahdollista.</li>
</ul>
  
<h3>Tiedon saanti saavutettavassa muodossa</h3>
<p>Mainituista puutteista johtuen saavuttamatta jäävää sisältöä voi pyytää tämän sivuston ylläpitäjältä sähköpostitse 
<a href="mailto:palaute@helmetkirjasto.fi">palaute@helmetkirjasto.fi</a> tai <a href="https://www.helmet.fi/fi-FI/Palaute(3938)">palautelomakkeella</a>.

<h2>Saavutettavuusselosteen laatiminen</h2>
<p>Tämä seloste on laadittu 17.09.2020.</p>
<h3>Saavutettavuuden arviointi</h3>
<p>Saavutettavuuden on arvioinut Palvelukeskus Helsinki. Arvioinnissa on noudatettu Helsingin kaupungin työohjetta ja menetelmiä, 
jotka pyrkivät varmistamaan sivuston saavutettavuuden kaikissa työvaiheissa.</p>
<p>Saavutettavuus on tarkistettu ulkopuolisen asiantuntijan suorittamana auditointina sekä itsearviona.</p>
<p>Saavutettavuus on tarkistettu käyttäen ohjelmallista saavutettavuustarkistusta sekä sivuston ja sisällön manuaalista tarkistusta. 
Ohjelmallinen tarkistus on suoritettu käyttäen Siteimproven saavutettavuuden automaattista testaustyökalua ja selainlaajennusta.</p>

<h2>Saavutettavuusselosteen päivittäminen</h2>
<p>Sivuston saavutettavuudesta huolehditaan jatkuvalla valvonnalla tekniikan tai sisällön muuttuessa, sekä määräajoin suoritettavalla tarkistuksella. 
Tätä selostetta päivitetään sivuston muutosten ja saavutettavuuden tarkistusten yhteydessä.</p>

<h3>Palaute ja yhteystiedot</h3>
<p>Sivuston saavutettavuudesta vastaavat Helsingin, Espoon, Vantaan ja Kauniaisten kaupunginkirjastot. Voit antaa palautetta <a href="mailto:palaute@helmet-kirjasto.fi">
sähköpostilla</a> tai <a href="https://www.helmet.fi/fi-FI/Palaute(3938)">palautelomakkeella</a>.</p>

<h3>Ilmoittaminen ei-saavutettavasta sisällöstä</h3>
<p>Mikäli käyttäjä kokee, etteivät saavutettavuuden vaatimukset kuitenkaan täyty, voi tästä tehdä ilmoituksen sähköpostilla palaute@helmetkirjasto.fi tai 
palautelomakkeella <a href="https://www.helmet.fi/fi-FI/Palaute(3938)" target="_blank">www.helmet.fi/palaute</a>.</p>

<h3>Tietojen pyytäminen saavutettavassa muodossa</h3>
<p>Mikäli käyttäjä ei koe saavansa sivuston sisältöä saavutettavassa muodossa, voi käyttäjä pyytää näitä tietoja sähköpostilla palaute@helmet-kirjasto.fi tai palautelomakkeella 
<a href="https://www.helmet.fi/fi-FI/Palaute(3938)" target="_blank">www.helmet.fi/palaute</a>. Tiedusteluun pyritään vastaamaan kohtuullisessa ajassa.</p>

<h2>Saavutettavuuden oikeussuoja, Täytäntöönpanomenettely</h2>
<p>Mikäli henkilö kokee, ettei hänen ilmoitukseensa tai tiedusteluunsa ole vastattu tai vastaus ei ole tyydyttävä, voi asiasta tehdä ilmoituksen Etelä-Suomen aluehallintovirastoon. 
Etelä-Suomen aluehallintoviraston sivulla kerrotaan tarkasti, miten asia käsitellään.</p><p>Etelä-Suomen aluehallintovirasto</p>
<p>Saavutettavuuden valvonnan yksikkö</p>
<p><a href="https://www.saavutettavuusvaatimukset.fi/" target="_blank">www.saavutettavuusvaatimukset.fi</a></p>
<p>saavutettavuus@avi.fi</p>
<p>Puhelinvaihde: 0295 016 000</p>
<p>Avoinna: ma-pe klo 8.00 – 16.15</p>

<h2>Saavutettavuusselosteen hyväksyntä</h2>
<p>Tämän selosteen on hyväksynyt 22.9.2020</p>
<p>Helmet-kirjasto</p>
<p>Helsingin, Espoon, Vantaan ja Kauniaisten kaupunginkirjastot</p>
