<? $this->headTitle($this->translate('Accessibility statement')); $this->content()->setHeading($this->translate('Accessibility statement'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>This accessibility statement applies to the website “Helmet” of the city libraries of Helsinki, Espoo, Vantaa and Kauniainen. 
        The site address is <a href="https://www.helmet.fi">https://www.helmet.fi</a>.</p>
      </div>
     <div id="statutory-provisions" class="content-section">
        <h2>Statutory provisions applicable to the website</h2>
        <p>This website was published prior to 23 September 2018. The website must fulfil the statutory accessibility requirements after the transitional period ending on 23 September 2020.</p>
      </div>
      <div id="compliance-status" class="content-section">
        <h2>Compliance status</h2>
        <p>This website meets the statutory critical accessibility requirements in accordance with Level AA of the WCAG v2.1 with following deficiencies.</p>
      </div>
      <div id="non-accessible-content" class="content-section">
        <h2>Non-accessible content</h2>
        <p>The content mentioned below does not yet meet all of the statutory accessibility requirements.</p>
        <h3>Deficiencies found:</h3>
        <ul class="list-bullets">
            <li><b>The descriptions of some of the website’s links are inadequate. (2.4.4 Link Purpose (In Context))</b> Correcting deficiencies: 
            Defective links in articles are being corrected. The website’s content provider has issued instructions on how to describe links correctly.</li>
            <li><b>The website has untranslated text content. (3.1.2 Language of Parts)</b> Correcting deficiencies: The service menu’s translation shortcomings 
            are caused by a technical error as a result of which not all translated text is displayed correctly on the different language versions of pages. 
            The service provider has been asked to correct the error as soon as possible.</li>
            <li><b>The website has PDF files that are not accessible with screen readers. (1.1.1 Non-text Content, 4.1.2 Name, Role, Value)</b> Correcting deficiencies: 
            The observed shortcomings will be fixed by converting PDF documents primarily into HTML format.</li>
            <li><b>The website’s chat function is inaccessible with assistive technology. (4.1.3 Status Messages)</b> Correcting deficiencies: The provider of the chat service 
            has been asked for a quote for an accessible alternative to the chat function. An accessible chat will be implemented on the website as soon as possible.</li>
        </ul>
        
        <h3>Obtaining information in an accessible form</h3>
        <p>Due to the deficiencies, you can request the non-accessible content from the administrator of this website.</p>
        <p>City libraries of Helsinki, Espoo, Vantaa and Kauniainen</p>
        <p>e-mail <a href="mailto:palaute@helmetkirjasto.fi">palaute@helmetkirjasto.fi</a></p>
        <p>feedback form <a href="http://www.helmet.fi/feedback">www.helmet.fi/feedback</a></p>
      </div>
      <div id="preparing-statement" class="content-section">
        <h2>Preparing an accessibility statement</h2><p>This statement was prepared on 17.9.2020.</p>
        <h3>Assessment of accessibility</h3>
        <p>The working instruction and procedures of the City of Helsinki were followed when evaluating the accessibility of the site, with the aim of ensuring that websites 
        are accessible in all stages of the work process.</p>
        <p>Accessibility was evaluated by means of an audit by a third-party expert as well as self-evaluation.</p>
        <p>Accessibility was evaluated using a programmatic accessibility auditing tool as well as by manually reviewing the site and content. 
        Programmatic evaluations were carried out using the Siteimprove browser extension.</p>
        
        <h3>Updating the accessibility statement</h3>
        <p>When website technology or content changes, its accessibility must be ensured through constant monitoring and periodic checks. 
        This statement will be updated in conjunction with website changes and accessibility evaluations.</p>
      </div>
      <div id="feedback" class="content-section">
        <h2>Feedback and contact information</h2>
        <p>The entity responsible for site accessibility:</p>
        <p>Helmet Library</p>
        <p>City libraries of Helsinki, Espoo, Vantaa and Kauniainen</p>
        <p><a href="mailto:palaute@helmetkirjasto.fi">palaute@helmetkirjasto.fi</a></p>
        <p><a href="http://www.helmet.fi/feedback">www.helmet.fi/feedback</a></p>
        
        <h3>Reporting non-accessible content</h3>
        <p>If a user feels that accessibility requirements have not been met, they can report the issue by e-mail to <a href="mailto:palaute@helmet-kirjasto.fi">palaute@helmet-kirjasto.fi</a>
         or through the feedback form at <a href="https://www.helmet.fi/feedback">https://www.helmet.fi/feedback</a>.</p>
        
        <h3>Requesting information in an accessible format</h3>
        <p>If a user feels that content on a website is not available in an accessible format, they can request for this information by e-mail at 
        <a href="mailto:palaute@helmet-kirjasto.fi">palaute@helmet-kirjasto.fi</a> or through the feedback form at <a href="https://www.helmet.fi/feedback">https://www.helmet.fi/feedback</a>.</p>
      </div>
      <div id="legal-protection" class="content-section">
        <h2>Legal protection of accessibility, Enforcement procedure</h2>
        <p>If a user feels that their report or enquiry has not received a response or that the response is unsatisfactory, they can report the issue to the Regional State Administrative Agency
        of Southern Finland. The website of the Regional State Administrative Agency of Southern Finland explains in detail how the matter will be processed.</p>
        <p>Regional State Administrative Agency of Southern Finland<br>
        Accessibility monitoring unit<br>
        <a href="http://www.saavutettavuusvaatimukset.fi">www.saavutettavuusvaatimukset.fi</a><br>
        <a href="mailto:saavutettavuus@avi.fi">saavutettavuus@avi.fi</a><br>
        Telephone exchange +358 295 016 000<br>
        Open: Mon-Fri at 8:00–16:15</p>
      </div>
      <div id="approval" class="content-section">
        <h2>Approval of the accessibility statement</h2>
        <p>This statement was approved by 22.9.2020</p><p>Helmet Library</p>
        <p>City libraries of Helsinki, Espoo, Vantaa and Kauniainen</p>
      </div>
   </div>
</div>




