<? $this->headTitle($this->translate("Helmet Library in social media")); $this->content()->setHeading($this->translate("Helmet Library in social media"));?>
<p>You can find us in Facebook, Youtube and Flickr. HelMet Facebook is in Finnish but you can also ask and give feedback in English. 
You are welcome to join us!</p>
<ul class="list-bullets">
  <li><a href="http://www.facebook.com/helmetkirjasto" target="_blank">Helmet Facebook</a></li>
  <li><a href="http://www.youtube.com/user/helmetkirjasto?feature=results_main" target="_blank">Helmet Youtube</a></li>
  <li><a href="http://www.flickr.com/photos/helmetkirjasto/" target="_blank">Helmet Flickr</a></li>
  <li><a href="https://twitter.com/HelMet_kirjasto" target="_blank">Helmet Twitter</a></li>
</ul>