<? $this->headTitle($this->translate("Helmet-biblioteket i sociala medier")); $this->content()->setHeading($this->translate("Helmet-biblioteket i sociala medier"));?>
<p>Helmet-bibliotekets tjänster och personal hittar du också i sociala medier. T.ex. Helmet-Facebook erbjuder de senaste nyheterna angående 
bibliotekets tjänster och aktuella evenemang. Du kan också ge oss feedback och träffa andra biblioteksvänner och -människor.</p>
<p>Välkommen med!</p>
<ul class="list-bullets">
  <li><a href="https://www.facebook.com/pages/HelMet-bibban-p%C3%A5-svenska/125611384120947" target="_blank">Helmet-bibban på svenska på 
  Facebook</a></li>
  <li><a href="http://www.facebook.com/helmetkirjasto" target="_blank">Helmet-kirjasto Facebookissa</a> (på finska)</li>
  <li><a href="http://www.youtube.com/user/helmetkirjasto?feature=results_main" target="_blank">Helmet Youtube</a></li>
  <li><a href="http://www.flickr.com/photos/helmetkirjasto/" target="_blank">Helmet Flickr</a></li>
  <li><a href="https://twitter.com/HelMet_kirjasto" target="_blank">Helmet Twitter</a> (på finska)</li>
</ul>