<? $this->headTitle($this->translate("Helmet-kirjasto sosiaalisessa mediassa")); $this->content()->setHeading($this->translate("Helmet-kirjasto sosiaalisessa mediassa"));?>
<p>Helmet-kirjaston palvelut ja työntekijät löydät myös sosiaalisesta mediasta. Esimerkiksi Helmet-facebook tarjoaa tuoreimmat uutiset kirjaston 
palveluista ja ajankohtaisista tapahtumista. Voit myös antaa meille palautetta sekä tavata muita kirjaston ystäviä ja kirjastolaisia. 
Tervetuloa mukaan!</p>
<ul class="list-bullets">
    <li><a href="http://www.facebook.com/helmetkirjasto" target="_blank">Helmet Facebook</a></li>
    <li><a href="http://www.youtube.com/user/helmetkirjasto?feature=results_main" target="_blank">Helmet Youtube</a></li>
    <li><a href="http://www.flickr.com/photos/helmetkirjasto/" target="_blank">Helmet Flickr</a></li>
    <li><a href="https://twitter.com/HelMet_kirjasto" target="_blank">Helmet Twitter</a></li>
</ul>