<? $this->headTitle($this->translate('Registerbeskrivning av informationssystemet enligt ofentlighetslagen')); 
$this->content()->setHeading($this->translate('Registerbeskrivning av informationssystemet enligt ofentlighetslagen'));?>
<p>(Lag om offentlighet i myndigheternas verksamhet 21.5.1999/621)</p>

<h2>Informationssystemets namn</h2>
<p>HelMet-bibliotekens bibliotekskatalog och kundregister</p>

<h2>Informationssystemets upprätthållare</h2>
<p>Esbo, Grankulla, Helsingfors och Vanda stadsbibliotek</p>

<h2>Enhet och person som ansvarar för informationssystemet</h2>
<p>Susanna Aakko, Helsingfors stadsbibliotek, enheten för bibliotekssystemet, PL4100, 00099 Hel-singfors stad, tel: 09 3107 1312, e-post: susanna.aakko@hel.fi</p>

<h2>Avsikten med informationssystemet</h2>
<p>Att upprätthålla bibliotekens kataloger och kundregister samt föra statistik. Mera information finns i kundregisterbeskrivningen.</p>

<h2>Informationskällor</h2>
<p>Exemplar som införts i eller avskrivits ur samlingarna. Katalogiseringsposter ur Nationalbibliografin eller ur övriga källor inköpta eller plockade poster. 
Data genererad av bibliotekens låneverksamhet. Information av kunderna och ur befolkningsdatasystemet. Mera information finns i 
<a href="/Content/asiakasrekisteriseloste?lng=sv">kundregister-beskrivningen</a>.</p>

<h2>Uppgifterna finns från åren/med början från år</h2>
<p>Samlingsdatabasen och kundregistret ingår i bibliotekssystemet Millennium, som togs i bruk år 2003. När man grundade systemet flyttade man över uppgifter från de 
tidigare systemen Plussa, i bruk åren 1993–2003 och Pääsky 1978–1994.</p>

<h2>Uppdatering av uppgifterna</h2>
<p>Realtid</p>

<h2>Uppgifternas offentlighet/sekretess</h2>
<p>Uppgifter om bibliotekens kunder är sekretessbelagda. Mera information finns i kundregisterbe-skrivningen.</p>

<h2>Offentliga uppgifter gruppvis</h2>
<p>Beskrivning av och tillgången på material i bibliotekens samlingar.</p>

<h2>Sekretessbelagda uppgifter</h2>
<p>Alla uppgifter om bibliotekens kunder. Mera information i <a href="/Content/asiakasrekisteriseloste?lng=sv">kundregister-beskrivningen</a>.</p>
 
<h2>Informationssystemets offentliga adress</h2>
<p>www.helmet.finna.fi</p>
