<? $this->headTitle($this->translate('Data protection and information about the site')); $this->content()->setHeading($this->translate('Data protection and information about the site'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>The Helmet website is a joint online service for the city libraries of Espoo, Helsinki, Kauniainen and Vantaa. 
        The service includes the city libraries' contact information, opening hours and events, as well as information about their services. 
        Through the Helmet.fi website, you can also access the online library, where you can see the collection list, retrieve data and use your own data.</p>
        <p>The online service is published in Finnish, Swedish, English and Russian. The Finnish site is the most extensive.</p>
     </div>
     <div id="service-environment" class="content-section">
        <h2>Service environment</h2>
        <p>The Helmet website (libraries’ contact information, services and events) is an online service produced jointly by the city libraries in the Helsinki Metropolitan Area. 
        The publication system is provided by Fujitsu Finland Oy, which is also responsible for the website's management service. 
        The content of the website is the responsibility of the website editor and the layout of the website is seen to by a graphic designer/webmaster. 
        The Helmet web service is responsive, which means that it adapts to the user's terminal device.</p>
     </div>
     <div id="cookies" class="content-section">
        <h2>Online service cookies</h2> 
        <p>A cookie is a small text file that the browser saves on your computer or mobile device when you visit an online service. Necessary cookies are needed for the website to function. 
        Subject to the user’s consent, cookies that are not necessary for the operation of the site may also be used. 
        Users can delete the cookies stored on the device in the settings of the browser they use. The cookies are used to collect data about the visitors to the Helmet online service. 
        These data are used to improve the user interface and experience and to create user count statistics.</p>
        
        <p>The data collected to create user statistics are anonymised and cannot be linked to an individual person. Such data includes the page from which you arrived at the address of the 
        online service, the service pages you have browsed and when, the browser you are using, the resolution of your screen, the operating system of your device and the IP address and 
        regional location of your computer.</p>
        <p>The site may include content by service providers not affiliated with the Helmet online service, such as embedded map services or social media channels. 
        You can prevent the collection of these cookies.</p>
     </div>
     <div id="managing2" class="content-section">
        <h2>Managing cookies</h2>
        <p>The Helmet online service features a cookie tool. You can access the cookie tool when entering the site (pop-up window) or by clicking on the gear icon at the bottom left of the page.
        When you enter the online service, you can allow all cookies or block cookies that are not necessary for the operation of the service. 
        You can edit your preferences at any time through the <a class="ch2-open-settings-btn" href="#">cookie settings tab of the cookie tool</a>.</p>
        <p>The cookies used in the online service are categorised into necessary cookies, preferences and analytical cookies. A cookie may be session-specific, in which case it will be 
        deleted after you close the browser, or it may be stored on your device for longer. Cookies may be first-party or third-party cookies. First-party cookies are set by the website 
        you are using (the Helmet online service). Third-party cookies are set by an external party.</p>
        <ul class="list-bullets">
          <li>The cookies necessary for the operation of the Helmet online service enable e.g. the maintenance of user sessions. You cannot disable necessary cookies.</li>
          <li>Preference cookies are set by the video services Vimeo and YouTube. They are needed for you to be able to watch videos embedded on the pages. 
          You can block preference cookies in the cookie tool.</li>
          <li>Analytical (statistical) cookies are used to develop the website. Helmet libraries use the Matomo visitor statistics service. Matomo cookies collect data on online visits and 
          the visitors’ activities on the website. You can block analytical cookies in the cookie tool.</li>
        </ul>
        <p>You can find more detailed information about the Helmet online service’s cookie categories, the cookies in them and the validity period of each cookie by going to 
        <a class="ch2-open-settings-btn" href="#">the cookie tool</a>.</p>
     </div>
     <div id="privacy-statement" class="content-section">
        <h2>Privacy statement of Helmet.fi website</h2>
        <p>EU General Data Protection Regulation (2016/679)</p>
        <p>Helmet is a network of the public libraries in the Helsinki Metropolitan Area (Helsinki Metropolitan Area Libraries). It includes the city libraries of Helsinki, Espoo, Kauniainen 
        and Vantaa, which act as joint controllers of the personal data processing.</p>
        
        <h3>Register controller</h3>
        <p>City of Espoo</p>
        <p>The City of Helsinki Culture and Leisure Committee, which delegated the controller’s tasks to the Director of Library Services on 27 March 2018, § 71.</p>
        <p>City of Kauniainen</p>
        <p>Vantaa Education Committee</p>
        
        <h3>Whom to contact in matters related to processing of your personal data</h3>
        <p>In Espoo, the person in charge of the register is the Director of Library Services. The contact person is the Library Service Manager of Espoo City Library. 
        Contact information: City of Espoo, Registry Office P.O. Box 1, 02070 CITY OF ESPOO.</p>
        <p>In Helsinki, the person in charge of the register is the Director of Library Services. The contact person is the Service Manager of Pasila Library of Helsinki City Library. 
        Contact information: City of Helsinki, Registry Office P.O. Box 10 (Pohjoisesplanadi 11–13), 00099 CITY OF HELSINKI.</p>
        <p>In Kauniainen, the person in charge of the register is the Chief Librarian. The contact person is the Information Specialist of Kauniainen City Library. 
        Contact information: City of Kauniainen, Registry Office P.O. Box 52 (Kauniaistentie 10), 02701 KAUNIAINEN.</p>
        <p>In Vantaa, the person in charge of the register is the Director of Library Services. The contact person is the Special Librarian of Vantaa City Library. 
        Contact information: City of Vantaa, Registry Office, Asematie 7, 01300 VANTAA.</p>
        
        <h3>Why do we process your personal data?</h3>
        <p>The purpose of processing personal data is to organise the Helmet library services.</p>
        
        <h3>What is the legal basis for processing your personal data?</h3>
        <p>The processing of personal data is based on the EU’s General Data Protection Regulation, Article 6(1c): processing is necessary for compliance with a legal obligation to 
        which the controller is subject.</p><p>The collection of cookies on the website is based on Point (a) of Article 6(1) of the EU General Data Protection Regulation: the data 
        subject has given consent to the processing of his or her personal data for one or more specific purposes.</p>
        <p>Essential legislation:</p>
        <ul class="lis-bullets">
          <li>EU General Data Protection Regulation (679/2016)</li>
          <li>Public Libraries Act (1492/2016)</li>
          <li>Act on the Openness of Government Activities (621/1999)</li>
          <li>Data Protection Act (1050/2018)</li>
        </ul>
        
        <h3>What information do we collect about you with cookies?</h3>
        <p>The Helmet.fi website uses cookies to maintain the user session. The cookies are used to collect data about the visitors to the Helmet online service. 
        These data are used to improve the user interface and experience and to create user count statistics.</p><p>We collect the following data to create user statistics:</p>
        <ul class="list-bullets">
          <li>the page from which you accessed the online service address</li>
          <li>the service pages you have browsed and when</li>
          <li>the browser you use</li>
          <li>your screen resolution and the operating system of your device</li>
          <li>the IP address and regional location of your device</li>
        </ul>
        <p>The data collected to create user statistics are anonymised and cannot be linked to an individual person.</p>
        
        <h3>To whom do we disclose your personal data?</h3>
        <p>We do not disclose personal data to anyone.</p>
        
        <h3>Personal data processors</h3>
        <p>Personal data is processed by the providers of the website and statistics services.</p>
        <p>In order to provide the above-mentioned functions, we use external service providers that process personal data (anonymised IP address) on behalf of the Helmet website.</p>
        
        <h3>Is your personal data transferred outside the EU and EEA and what are the grounds for the transfer?</h3>
        <p>We do not transfer personal data outside the EU or EEA.</p>
        
        <h3>How long do we store your data?</h3>
        <p>We store personal data (anonymised IP address) for a maximum of five years.</p>
        
        <h3>From what sources do we collect your data?</h3>
        <p>The data (IP address) is obtained from the terminal used by the customer and from the Internet service provider.</p>
        
        <h3>Profiling and automated decision-making</h3>
        <p>Your personal data is not used for profiling or automated decision-making.</p>
        
        <h3>Data subject's rights</h3>
        <p>Read more about the rights of the data subject and the instructions for enforcing them on the data protection pages of your city.</p>
        <p><a href="https://www.espoo.fi/en/city-espoo/data-protection" target="_blank">City of Espoo: Data protection</a></p>
        <p><a href="https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/tietoa-helsingista/tietosuoja/tietosuojasta-tarkemmin" target="_blank">City of Helsinki: Data protection (in Finnish)</a></p>
        <p><a href="https://www.kauniainen.fi/tietosuoja" target="_blank">City of Kauniainen: Data protection (in Finnish; machine translations to several languages available)</a></p>
        <p><a href="https://www.vantaa.fi/en/city-and-decision-making/paatoksenteko/processing-personal-data" target="_blank">City of Vantaa: Data protection</a></p>
        
        <h3>Right to lodge a complaint with a supervisory authority</h3>
        <p>You have the right to lodge a complaint with a supervisory authority if you believe that the processing of your personal data violates the EU General Data Protection Regulation (EU) 
        2016/679. You have also the right to exercise other administrative and judicial remedies.</p>
        <p><a href="https://tietosuoja.fi/en/home" target="_blank">Data Protection Ombudsman's office</a></p>
        <p>Street address: Lintulahdenkuja 4</p><p>Postal address: P.O. Box 800, 00531 Helsinki</p>
        <p>Email: <a href="mailto:tietosuoja@om.fi">tietosuoja@om.fi</a></p>
        <p>Switchboard: +358 29 56 66700</p>
        
        <h3>Data protection officer:</h3>
        <p>Espoo: <a href="mailto:%20tietosuoja@espoo.fi">tietosuoja@espoo.fi</a></p>
        <p>Helsinki: <a href="mailto:tietosuoja@hel.fi">tietosuoja@hel.fi</a></p>
        <p>Kauniainen: <a href="mailto:tietosuoja@kauniainen.fi">tietosuoja@kauniainen.fi</a></p>
        <p>Vantaa: <a href="mailto:tietosuojavastaava@vantaa.fi">tietosuojavastaava@vantaa.fi</a></p>
        <p>Last updated 6/3/2023</p>
      </div>
   </div>
</div>

