<? $this->headTitle($this->translate('Description of information system provided by act on the openness of government activities')); 
$this->content()->setHeading($this->translate('Description of information system provided by act on the openness of government activities'));?>
<p>(Act on the Openness of Government Activities 21.5.1999/621)</p>
<p>February 10, 2014</p>
<h2>Name of the information system</h2>
<p>Collections database and customer register of the Helmet libraries</p>

<h2>Organizations responsible for the information system</h2>
<p>Espoo, Helsinki, Kauniainen and Vantaa City Libraries</p>

<h2>Unit and person responsible for the information system</h2>
<p>Application Manager for Helmet libraries, Helsinki City Library</p>

<h2>End use / purpose of the information system</h2>
<p>Maintenance of and compilation of statistics on library collections data and customer information.<br>
Further information in the customer registration report.</p>

<h2>Sources of information</h2>
<p>Items acquired into and withdrawn from the collections.<br>
Catalogue records purchased or extracted from the National bibliography or elsewhere.<br>
Information retrieved from the lending functions of the libraries.<br>
Information retrieved from customers and population register. Further information in the customer registration report.</p>

<h2>Time period covered</h2>
<p>The collections database and the customer register are part of the Sierra library system intro-duced in 2013. At the implementation phase the information content was transferred from the previous library system. The Millennium system was used in 2003 through 2013, the Plussa system was used in 1993 through 2003 and the Pääsky system in 1978 through 1994.</p>

<h2>Updating of information</h2>
<p>Real time.</p>

<h2>Openness / confidentiality of information</h2>
<p>Information on the items belonging to the library collections and on their availability is open.<br>
Information on library customers is confidential. Further information in <a href="/Content/asiakasrekisteriseloste?lng=en-gb">the customer registration report</a>.</p>

<h2>Open information grouped</h2>
<p>Descripition and availability of library material.</p>

<h2>Confidential information</h2>
<p>Information on library customers. Further information in <a href="/Content/asiakasrekisteriseloste?lng=en-gb">the customer registration report</a>.</p>

<h2>Public address of the information system</h2>
<p>www.helmet.finna.fi</p>
