<? $this->headTitle($this->translate('Julkisuuslain mukainen tietojärjestelmäseloste')); $this->content()->setHeading($this->translate('Julkisuuslain mukainen tietojärjestelmäseloste'));?>
<p>(Laki viranomaisten toiminnan julkisuudesta 21.5.1999/621)</p>
<p>10.2.2014</p>
<h2>Tietojärjestelmän nimi</h2>
<p>Helmet-kirjastojen kokoelmatietokanta ja asiakasrekisteri</p>

<h2>Tietojärjestelmän vastuutaho</h2>
<p>Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjastot</p>

<h2>Tietojärjestelmän vastuuyksikkö ja -henkilö</h2>
<p>Helmet-kirjaston sovelluspäällikkö, Helsingin kaupunginkirjasto</p>

<h2>Tietojärjestelmän käyttötarkoitus</h2>
<p>Kirjastojen kokoelmatietojen ja asiakastietojen ylläpito sekä tilastointi. Lisätietoja asiakasrekisteriselosteessa.</p>

<h2>Tietolähteet</h2>
<p>Kokoelmiin hankitut ja kokoelmista poistetut niteet. Kansallisbibliografiasta tai muualta ostetut tai poimitut luettelointitietueet. Kirjastojen lainaustoiminnan tuottama tieto. 
Asiakkailta ja väestötietojärjestelmästä saadut tiedot. Lisätietoja asiakasrekisteriselosteessa.</p>

<h2>Tiedot ovat vuosilta/alkaen vuodesta</h2>
<p>Kokoelmatietokanta ja asiakasrekisteri ovat osa vuonna 2013 käyttöönotettua Sierra-kirjastojärjestelmää. Perustamisvaiheessa järjestelmään siirrettiin tiedot 
aikaisemmasta järjestel-mästä. Millennium-järjestelmä oli käytössä vuosina 2003 – 2013, Plussa-järjestelmä oli käytössä vuosina 1993 – 2003 ja Pääsky-järjestelmä vuosina 1978 – 1994.</p>

<h2>Tietojen päivitystiheys</h2>
<p>Tosiaikainen</p>

<h2>Tietojen julkisuus/salassa pidettävyys</h2>
<p>Tiedot kirjastojen kokoelmiin kuuluvista niteistä ja niiden saatavuudesta ovat julkisia. Tiedot kirjastojen asiakkaista ovat salassa pidettäviä. 
Lisätietoja <a href="/Content/asiakasrekisteriseloste?lng=fi">asiakasrekisteriselosteessa</a>.</p>

<h2>Julkiset tiedot ryhmittäin</h2>
<p>Kirjastojen kokoelmiin kuuluvan aineiston kuvailu- ja saatavuustiedot.</p>

<h2>Salassa pidettävät tiedot</h2>
<p>Kirjastojen asiakkaita koskevat tiedot. Lisätietoja <a href="/Content/asiakasrekisteriseloste?lng=fi">asiakasrekisteriselosteessa</a>.</p>

<h2>Tietojärjestelmän julkinen osoite</h2>
<p>www.helmet.finna.fi</p>
