<? $this->headTitle($this->translate('Tietosuoja ja tietoa sivustosta')); $this->content()->setHeading($this->translate('Tietosuoja ja tietoa sivustosta'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helmet-sivusto on Espoon, Helsingin, Kauniaisten ja Vantaan kaupunginkirjastojen yhteinen verkkopalvelu. 
        Palvelu sisältää kaupunginkirjastojen yhteystiedot, aukioloajat, tapahtumat ja tietoa palveluista. Lisäksi Helmet.fi-sivuston kautta pääset myös verkkokirjastoon, joka sisältää mm. 
        kokoelmaluettelon, tiedonhaun ja asiakkaan omien tietojen käytön.</p>
        <p>Verkkopalvelua julkaistaan suomen-, ruotsin-, englannin- ja venäjänkielisenä. Suomenkielinen sivusto on laajin.</p>
      </div>
      <div id="palveluymparisto" class="content-section">
        <h2>Palveluympäristö</h2>
        <p>Helmet-sivusto (kirjastojen yhteystiedot, palvelut ja tapahtumat) on pääkaupunkiseudun kaupunginkirjastojen yhdessä tuottama verkkopalvelu. 
        Julkaisujärjestelmän toimittaja on Fujitsu Finland Oy, joka vastaa myös sivuston käyttöpalvelusta. Sivuston sisällöstä vastaa verkkopäätoimittaja ja ulkoasusta graafikko/webmaster. 
        Helmet-verkkopalvelu on responsiivinen, eli se mukautuu käyttäjän päätelaitteen mukaan.</p>
      </div>
     <div id="evasteet" class="content-section">
        <h2>Verkkopalvelun evästeet</h2>
        <p>Eväste (cookie) on pieni tekstitiedosto, jonka selain tallentaa tietokoneellesi tai mobiililaitteellesi, kun vierailet verkkopalvelussa. 
        Välttämättömiä evästeitä tarvitaan, jotta verkkosivusto toimii. Kävijän suostumuksella voidaan käyttää myös evästeitä, jotka eivät ole välttämättömiä sivuston toiminnalle. 
        Laitteelle tallennetut evästeet voi myös poistaa käyttämänsä selaimen asetuksissa. Evästeillä kerätään tietoa Helmet-verkkopalvelun kävijöistä. 
        Näitä tietoja käytetään käyttöliittymän ja käyttökokemuksen parantamiseen sekä kävijämäärien tilastolliseen seurantaan.</p>
        <p>Kävijätilastointia varten kerätyt tiedot anonymisoidaan, joten niitä ei voi liittää yksittäiseen henkilöön. Tällaisia tietoja ovat miltä sivulta olet siirtynyt verkkopalvelun 
        osoitteeseen, mitä sivujamme olet selannut ja milloin, mitä selainta käytät, mikä on näyttösi resoluutio ja käyttöjärjestelmä, 
        mikä on tietokoneesi IP-osoite ja alueellinen sijainti.</p>
        <p>Sivusto voi sisältää Helmet-verkkopalvelun ulkopuolisten palveluntarjoajien sisältöjä, kuten upotuksia karttapalveluista tai sosiaalisen median kanavista. 
        Voit estää kyseisten evästeiden keräämisen.</p>
      </div>
      <div id="hallinnointi" class="content-section">
        <h2>Evästeiden hallinnointi</h2>
        <p>Helmet-verkkopalvelussa on käytössä evästetyökalu. Voit käyttää evästetyökalua tullessasi sivustolle (ponnahdusikkuna) tai siirtyä siihen napsauttamalla sivun vasemmassa 
        alareunassa näkyvää hammasratasta. Verkkopalveluun tullessasi voit sallia kaikki evästeet tai estää muut kuin palvelun toiminnan kannalta välttämättömät evästeet. 
        Voit muokata valintojasi milloin tahansa <a class="ch2-open-settings-btn" href="#">evästetyökalun Evästeasetukset-välilehdellä</a>.</p>
        
        <p>Verkkopalvelussa käytetyt evästeet on ryhmitelty välttämättömiin evästeisiin, mieltymyksiin ja analyyttisiin evästeisiin. Eväste voi olla istuntokohtainen, 
        jolloin se poistuu selaimen sulkemisen jälkeen, tai se voidaan tallentaa laitteellesi pidemmäksi aikaa. Eväste voi olla ensimmäisen osapuolen eväste tai kolmannen osapuolen eväste. 
        Ensimmäisen osapuolen eväste asetetaan käyttämältäsi sivustolta (Helmet-verkkopalvelusta). Kolmannen osapuolen evästeen asettaa ulkopuolinen taho.</p>
        <ul class="list-bullets">
          <li>Helmet-verkkopalvelun toiminnan kannalta välttämättömät evästeet mahdollistavat esimerkiksi käyttäjäistunnon ylläpitämisen. Et voi estää välttämättömiä evästeitä.</li>
          <li>Mieltymys-evästeitä asettavat videopalvelut Vimeo ja YouTube. Niitä tarvitaan, jotta pystyt katsomaan sivuille upotettuja videoita. Mieltymys-evästeet voit estää evästetyökalussa.</li>
          <li>Analyyttisia (tilastollisia) evästeitä käytetään verkkosivujen kehittämiseen. Matomo on Helmet-kirjastojen käyttämä kävijätilastointipalvelu. Matomon evästeillä kerätään dataa verkkokäynneistä ja kävijöiden toiminnasta verkkosivustolla. Analyyttiset evästeet voit estää evästetyökalussa.</li>
        </ul>
        <p>Tarkemmat tiedot Helmet-verkkopalvelun evästeryhmistä, niihin kuuluvista evästeistä ja kunkin evästeen voimassaoloajasta näet siirtymällä <a class="ch2-open-settings-btn" href="#">
        evästetyökaluun</a>.</p>
      </div>
      <div id="tietosuojaseloste" class="content-section">
        <h2>Helmet.fi-sivuston tietosuojaseloste</h2>
        <p>EU:n yleinen tietosuoja-asetus (2016/679)</p>
        <p>Helmet on pääkaupunkiseudun yleisten kirjastojen kirjastoverkko (Helsinki Metropolitan Area Libraries). Siihen kuuluvat Helsingin, Espoon, Kauniaisten ja Vantaan kaupunginkirjastot, 
        jotka toimivat henkilötietojen käsittelyn osalta yhteisrekisterinpitäjinä.</p>
        
        <h3>Rekisterinpitäjä</h3>
        <p>Espoon kaupunki</p>
        <p>Helsingin kaupungin kulttuuri- ja vapaa-aikalautakunta, joka on delegoinut rekisterinpitäjän tehtävät 27.3.2018, § 71, kirjastopalvelujen johtajalle</p>
        <p>Kauniaisten kaupunki</p>
        <p>Vantaan opetuslautakunta</p>
        
        <h3>Yhteydenotto henkilötietojesi käsittelyyn liittyvissä kysymyksissä</h3>
        <p>Espoossa rekisterin vastuuhenkilönä toimii kirjastopalveluiden johtaja.<br>
        Yhteyshenkilönä toimii Espoon kaupunginkirjaston kirjastopalvelupäällikkö.<br>
        Yhteystiedot: Espoon kaupunki, Kirjaamo PL 1, 02070 ESPOON KAUPUNKI.</p>
        <p>Helsingissä rekisterin vastuuhenkilönä toimii kirjastopalvelujen johtaja.<br>
        Yhteyshenkilönä toimii Helsingin kaupunginkirjaston Pasilan kirjaston palveluesimies.<br>
        Yhteystiedot: Helsingin kaupunki, Kirjaamo PL 10 (Pohjoisesplanadi 11–13), 00099 HELSINGIN KAUPUNKI.</p>
        <p>Kauniaisissa rekisterin vastuuhenkilönä toimii kirjastonjohtaja.<br>
        Yhteyshenkilönä toimii Kauniaisten kaupunginkirjaston informaatikko.<br>
        Yhteystiedot: Kauniaisten kaupunki, Kirjaamo PL 52 (Kauniaistentie 10), 02701 KAUNIAINEN.</p>
        <p>Vantaalla rekisterin vastuuhenkilönä toimii kirjastopalveluiden johtaja.<br>
        Yhteyshenkilönä toimii Vantaan kaupunginkirjaston erikoiskirjastovirkailija.<br>
        Yhteystiedot: Vantaan kaupunki, Kirjaamo, Asematie 7, 01300 VANTAA.</p>
        
        <h3>Miksi käsittelemme henkilötietojasi?</h3>
        <p>Henkilötietojen käsittelyn tarkoituksena on Helmet-kirjastopalveluiden järjestäminen.</p>
        
        <h3>Mikä on henkilötietojesi käsittelyn lainmukainen peruste?</h3>
        <p>Henkilötietojen käsittely perustuu EU:n yleisen tietosuoja-asetuksen 6 artiklan 1 c-kohtaan: käsittely on tarpeen rekisterinpitäjän lakisääteisen velvoitteen noudattamiseksi.</p>
        <p>Verkkosivustolla keräämiemme evästeiden osalta käsittelyperusteena on EU:n yleisen tietosuoja-asetuksen 6 artiklan 1 a-kohta: rekisteröity on antanut suostumuksensa 
        henkilötietojensa käsittelyyn yhtä tai useampaa erityistä tarkoitusta varten.</p>
        <p>Keskeinen lainsäädäntö:</p>
        <ul class="list-bullets">
          <li>EU:n yleinen tietosuoja-asetus (679/2016)</li>
          <li>Laki yleisistä kirjastoista (1492/2016)</li>
          <li>Laki viranomaisten toiminnan julkisuudesta (621/1999)</li>
          <li>Tietosuojalaki (1050/2018)</li>
        </ul>
        
        <h3>Mitä tietoja sinusta keräämme evästeillä?</h3>
        <p>Helmet.fi-sivustolla käytetään evästeitä (cookies) käyttäjäistunnon ylläpitämiseksi. Evästeillä kerätään tietoa Helmet-verkkopalvelun kävijöistä. 
        Näitä tietoja käytetään käyttöliittymän ja käyttökokemuksen parantamiseen sekä kävijämäärien tilastolliseen seurantaan.</p>
        <p>Keräämme palvelun kävijätilastointia varten seuraavat tiedot:</p>
        <ul class="list-bullets">
          <li>miltä sivulta olet siirtynyt verkkopalvelun osoitteeseen</li>
          <li>mitä sivujamme olet selannut ja milloin</li>
          <li>mitä selainta käytät</li>
          <li>mikä on näyttösi resoluutio ja käyttöjärjestelmä</li>
          <li>mikä on tietokoneesi IP-osoite ja alueellinen sijainti</li>
        </ul>
        <p>Kävijätilastointia varten kerätyt tiedot (IP-osoite) anonymisoidaan, jonka jälkeen tietoja ei voida liittää yksittäiseen henkilöön.</p>
        
        <h3>Kenelle luovutamme henkilötietojasi?</h3>
        <p>Emme luovuta henkilötietoja kenellekään.</p>
        
        <h3>Henkilötietojen käsittelijät</h3>
        <p>Henkilötietoja käsittelevät verkkosivuston ja -tilastointipalvelun toimittajat.</p>
        <p>Käytämme edellä mainittujen toimintojen tuottamiseksi ulkopuolisia palveluntarjoajia, jotka käsittelevät henkilötietoja (anonymisoitu IP-osoite) Helmet-sivuston lukuun.</p>
        
        <h3>Siirretäänkö henkilötietojasi EU- ja ETA-alueiden ulkopuolelle ja mitkä ovat siirtoperusteet?</h3>
        <p>Emme siirrä henkilötietojasi EU- tai ETA-alueiden ulkopuolelle.</p>
        
        <h3>Kuinka kauan säilytämme tietojasi?</h3>
        <p>Säilytämme henkilötietoja (anonymisoitu IP-osoite) korkeintaan viisi vuotta.</p>
        
        <h3>Mistä lähteistä keräämme henkilötietosi?</h3>
        <p>Tiedot (IP-osoite) saadaan asiakkaan käyttämältä yhteyspäätteeltä ja internet-palveluntarjoajalta.</p>
        
        <h3>Profilointi ja automaattinen päätöksenteko</h3>
        <p>Henkilötietojasi ei käytetä profilointiin tai automaattiseen päätöksentekoon.</p>
        
        <h3>Rekisteröidyn oikeudet</h3>
        <p>Tutustu rekisteröidyn oikeuksiin ja niiden käyttöä koskeviin ohjeisiin oman kaupunkisi tietosuojasivuilla.</p>
        <p>Espoo: <a href="https://www.espoo.fi/fi/espoon-kaupunki/tietosuoja" target="_blank" 
        aria-label="Espoon kaupunki: Tietosuoja. Linkki aukeaa uudessa ikkunassa.">Espoon kaupunki: Tietosuoja</a></p>
        <p>Helsinki: <a href="https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/tietoa-helsingista/tietosuoja/tietosuojasta-tarkemmin" 
        target="_blank" aria-label="Helsingin kaupunki: 
        EU:n yleisen tietosuoja-asetuksen mukaisista oikeuksista tarkemmin. Linkki aukeaa uudessa ikkunassa.">Helsingin kaupunki: 
        EU:n yleisen tietosuoja-asetuksen mukaisista oikeuksista tarkemmin</a></p>
        <p>Kauniainen: <a href="https://www.kauniainen.fi/tietosuoja/" target="_blank"
        aria-label="Kauniaisten kaupunki: Tietosuoja. Linkki aukeaa uudessa ikkunassa.">Kauniaisten kaupunki: Tietosuoja</a></p>
        <p>Vantaa: <a href="https://www.vantaa.fi/fi/kaupunki-ja-paatoksenteko/paatoksenteko/henkilotietojen-kasittely" target="_blank"
        aria-label="Vantaan kaupunki: Henkilötietojen käsittely. Linkki aukeaa uudessa ikkunassa.">Vantaan kaupunki: Henkilötietojen käsittely</a></p>
        
        <h3>Oikeus tehdä valitus valvontaviranomaiselle</h3>
        <p>Sinulla on oikeus tehdä valitus valvontaviranomaiselle, jos katsot, että henkilötietojesi käsittelyssä rikotaan EU:n yleistä tietosuoja-asetusta (EU) 2016/679. 
        Tämän lisäksi sinulla on oikeus käyttää muita hallinnollisia muutoksenhakukeinoja sekä oikeussuojakeinoja.</p>
        <p><a href="https://www.tietosuoja.fi/" target="_blank"
        aria-label="Tietosuojavaltuutetun toimisto. Linkki aukeaa uudessa ikkunassa.">Tietosuojavaltuutetun toimisto</a><br>
        Käyntiosoite: Lintulahdenkuja 4<br>
        Postiosoite: PL 800, 00531 Helsinki<br>
        Sähköposti: <a href="mailto:tietosuoja@om.fi">tietosuoja@om.fi</a><br>
        Puhelinvaihde: 029 56 66700</p>
        
        <h3>Tietosuojavastaava</h3>
        <p>Espoo: <a href="mailto:%20tietosuoja@espoo.fi">tietosuoja@espoo.fi</a></p>
        <p>Helsinki: <a href="mailto:tietosuoja@hel.fi">tietosuoja@hel.fi</a></p>
        <p>Kauniainen: <a href="mailto:tietosuoja@kauniainen.fi">tietosuoja@kauniainen.fi</a></p>
        <p>Vantaa: <a href="mailto:tietosuojavastaava@vantaa.fi">tietosuojavastaava@vantaa.fi</a></p>
        <p>Viimeksi päivitetty 6.3.2023</p>
      </div>
   </div>
</div>


