<? $this->headTitle($this->translate('Dataskydd och information om webbplatsen')); $this->content()->setHeading($this->translate('Dataskydd och information om webbplatsen'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Webbplatsen Helmet är en gemensam webbtjänst för stadsbiblioteken i Esbo, Grankulla, Helsingfors och Vanda. 
        Tjänsten innehåller stadsbibliotekens kontaktuppgifter, öppettider och evenemang samt information om deras tjänster. Via webbplatsen Helmet.fi har du dessutom tillgång till webbiblioteket,
        som bland annat innehåller ett samlingsregister, informationssökning och användning av kundens egna uppgifter.</p>
        <p>Webbtjänsten publiceras på finska, svenska, engelska och ryska. 
        Webbplatsen på finska är den mest omfattande.</p>
      </div>
     <div id="servicemiljo" class="content-section">
        <h2>Servicemiljö</h2>
        <p>Webbplatsen Helmet (bibliotekens kontaktuppgifter, tjänster och evenemang) är en webbtjänst som produceras gemensamt av huvudstadsregionens stadsbibliotek. 
        Publiceringssystemets leverantör är Fujitsu Finland Oy, som också ansvarar för webbplatsens drifttjänst. Webbchefredaktören ansvarar för innehållet på webbplatsen och 
        grafikern/webmastern för utseendet. Webbtjänsten Helmet är responsiv, vilket innebär att den anpassar sig till användarens terminal.</p>
      </div>
      <div id="kakor" class="content-section">
        <h2>Webbtjänstens kakor</h2>
        <p>En kaka (cookie) är en liten textfil som webbläsaren lagrar på din dator eller mobilenhet när du besöker en webbtjänst. Nödvändiga kakor behövs för att webbplatsen ska fungera. 
        Med besökarens samtycke kan också kakor som inte är nödvändiga för webbplatsens funktion användas. De kakor som lagras på enheten kan också raderas från inställningarna för den 
        webbläsare man använder. Kakor används för att samla in uppgifter om besökarna i Helmets webbtjänst. Dessa uppgifter används för att förbättra användargränssnittet och 
        användarupplevelsen samt för statistisk uppföljning av antalet besökare.</p>
        <p>Uppgifterna som samlas in för besöksstatistik anonymiseras så att de inte kan kopplas till enskilda personer. Sådana uppgifter omfattar från vilken webbplats du har kommit 
        till webbplatsens adress, vilka sidor på vår webbplats du har besökt och när, vilken webbläsare du använder, vilken skärmresolution och vilket operativsystem du har, 
        din dators IP-adress och geografiska läge.</p>
        <p>På webbplatsen kan det finnas innehåll som producerats av andra serviceleverantörer än Helmets webbtjänst, till exempel inbäddade element från karttjänster eller sociala medier. 
        Du kan förhindra att dessa kakor samlas in.</p>
      </div>
     <div id="hantering" class="content-section">
        <h2>Hantering av kakor</h2>
        <p>Helmets webbtjänst använder ett kakverktyg. Du kan använda kakverktyget när du besöker webbplatsen (extrafönster) eller öppna det genom att klicka på kugghjulet nere till
        vänster på sidan. När du kommer in i webbtjänsten, kan du tillåta alla kakor eller blockera alla andra kakor förutom dem som är nödvändiga för tjänstens funktion. 
        Du kan ändra dina val när som helst på fliken <a class="ch2-open-settings-btn" href="#">Kakinställningar i kakverktyget</a>.</p>
        <p>Kakorna som används i webbtjänsten är delade i nödvändiga kakor, preferenser och analytiska kakor. En kaka kan vara sessionsspecifik, i vilket fall den raderas efter att du 
        stängt av webbläsaren. En sådan kaka kan också lagras på din enhet för en längre tid. En kaka kan vara en förstapartskaka eller en tredjepartskaka. Förstapartskakor lagras av den 
        webbplats du använder (Helmets webbtjänst). Tredjepartskakor lagras av en utomstående aktör.</p>
        <ul class="list-bullets">
          <li>Kakor som är nödvändiga för funktionen av Helmets webbtjänst möjliggör till exempel upprätthållande av en användarsession. Du kan inte blockera nödvändiga kakor.</li>
          <li>Preferenskakor lagras av videotjänsterna Vimeo och YouTube. Dessa kakor behövs för att du kan titta på videor som är inbäddade på sidorna. Du kan blockera preferenskakor i
          kakverktyget.</li>
          <li>Analytiska (statistiska) kakor används för att utveckla webbplatsen. Matomo är en besöksstatistiktjänst som används av Helmet-biblioteken. 
          Matomos kakor används för att samla in data om webbesök och om besökarnas aktiviteter på webbplatsen. Du kan blockera analytiska kakor i 
          <a class="ch2-open-settings-btn" href="#">kakverktyget</a>.</li>
        </ul>
        <p>Mer detaljerad information om kakgrupperna i Helmets webbtjänst, kakorna som tillhör grupperna och giltighetstiden för varje kaka får du genom att gå till 
        <a class="ch2-open-settings-btn" href="#">kakverktyget</a>.</p>
      </div>
      <div id="dataskyddsbeskrivning" class="content-section">
        <h2>Dataskyddsbeskrivning för Helmet.fi</h2>
        <p>EU:s allmänna dataskyddsförordning (2016/679)</p>
        <p>Helmet är biblioteksnätet för huvudstadsregionens allmänna bibliotek (Helsinki Metropolitan Area Libraries). Det omfattar Helsingfors, Esbo, Grankulla och Vanda stadsbibliotek, 
        som är gemensamt personuppgiftsansvariga när det gäller behandlingen av personuppgifter.</p>
        
        <h3>Personuppgiftsansvarig</h3>
        <p>Esbo stad</p>
        <p>Helsingfors stads kultur- och fritidsnämnd som per den 27.3.2018 § 71 har delegerat den personuppgiftsansvariges uppgifter till chefen för bibliotekstjänsterna.</p>
        <p>Grankulla stad</p>
        <p>Vanda utbildningsnämnd</p>
        
        <h3>Kontakt i frågor kring behandlingen av dina personuppgifter</h3>
        <p>I Esbo är direktören för bibliotekstjänsterna registeransvarig. Kontaktperson är biblioteksservicechefen på Esbo stadsbibliotek. Kontaktuppgifter: Esbo stad, Registratorskontoret, 
        PB 1, 02070 ESBO STAD.</p>
        <p>I Helsingfors är chefen för bibliotekstjänsterna registeransvarig. Kontaktperson är servicechefen för Böle bibliotek vid Helsingfors stadsbibliotek. 
        Kontaktuppgifter: Helsingfors stad, Registratorskontoret, PB 10 (Norra Esplanaden 11–13), 00099 HELSINGFORS STAD.</p><p>I Grankulla är bibliotekschefen registeransvarig. 
        Kontaktperson är informatikern på Grankulla stadsbibliotek. Kontaktuppgifter: Grankulla stad, Registratorskontoret, PB 52 (Grankullavägen 10), 02701 GRANKULLA.</p>
        <p>I Vanda är chefen för bibliotekstjänsterna registeransvarig. Kontaktperson är specialbibliotekarien på Vanda stadsbibliotek. Kontaktuppgifter: Vanda stad, Registratorskontoret, 
        Stationsvägen 7, 01300 VANDA.</p>
        
        <h3>Varför behandlar vi dina personuppgifter?</h3>
        <p>Syftet med behandlingen av personuppgifter är att ordna Helmet-bibliotekstjänsterna.</p>
        
        <h3>Vad är den rättsliga grunden för behandlingen av dina personuppgifter?</h3>
        <p>Behandlingen av personuppgifter grundar sig på artikel 6.1 c i EU:s allmänna dataskyddsförordning: behandlingen är nödvändig för att fullgöra en rättslig förpliktelse som åvilar 
        den personuppgiftsansvarige.</p><p>Vad gäller de kakor som vi samlar in på webbsidan är grunden för behandlingen artikel 6.1 a i EU:s allmänna dataskyddsförordning: den registrerade 
        har lämnat sitt samtycke till att dennes personuppgifter behandlas för ett eller flera specifika ändamål.</p>
        <p>Relevant lagstiftning:</p>
        <ul class="list-bullets">
          <li>EU:s allmänna dataskyddsförordning (679/2016)</li>
          <li>Lagen om allmänna bibliotek (1492/2016)</li>
          <li>Lagen om offentlighet i myndigheternas verksamhet (621/1999)</li>
          <li>Dataskyddslagen (1050/2018)</li>
        </ul>
        
        <h3>Vilka uppgifter om dig samlar vi in med kakor?</h3>
        <p>På webbplatsen Helmet.fi används kakor (cookies) för att upprätthålla användarsessionen. Kakor används för att samla in uppgifter om besökarna i Helmets webbtjänst. 
        Dessa uppgifter används för att förbättra användargränssnittet och användarupplevelsen samt för statistisk uppföljning av antalet besökare.</p>
        <p>Vi samlar in följande uppgifter för besöksstatistik om tjänsten:</p>
        <ul class="list-bullets">
          <li>från vilken webbplats du har kommit till webbplatsens adress</li>
          <li>vilka sidor på vår webbplats du har besökt och när</li>
          <li>vilken webbläsare du använder</li>
          <li>vilken skärmresolution och vilket operativsystem du har</li>
          <li>din dators IP-adress och geografiska läge.</li>
        </ul>
        <p>Uppgifterna som samlas in för besöksstatistik (IP-adress) anonymiseras, efter vilket uppgifterna inte kan kopplas till enskilda personer.</p>
        
        <h3>Till vem lämnar vi ut dina personuppgifter?</h3>
        <p>Vi lämnar inte ut personuppgifter till någon.</p>
        
        <h3>Personer som behandlar personuppgifterna</h3>
        <p>Personuppgifterna behandlas av leverantörerna av webbplatsen och statistiktjänsten.</p>
        <p>För att tillhandahålla de ovan nämnda funktionerna använder vi externa tjänsteleverantörer som behandlar personuppgifter (anonymiserad IP-adress) för Helmet-webbplatsens räkning.</p>
        
        <h3>Överförs dina personuppgifter utanför EU- och EES-områden och vilken är grunden för överföringen?</h3>
        <p>Vi överför inte dina personuppgifter utanför EU- och EES-områden.</p>
        
        <h3>Hur länge sparar vi dina uppgifter?</h3>
        <p>Vi sparar personuppgifter (anonymiserad IP-adress) i högst fem år.</p>
        
        <h3>Från vilka källor samlar vi in dina personuppgifter?</h3>
        <p>Uppgifterna (IP-adressen) erhålls från den terminal som används av kunden och från internetleverantören.</p>
        
        <h3>Profilering och automatiskt beslutsfattande</h3>
        <p>Dina personuppgifter används inte för profilering eller automatiskt beslutsfattande.</p>
        
        <h3>Den registrerades rättigheter</h3>
        <p>Läs mer om den registrerades rättigheter och anvisningarna för deras användning på din stads webbplats om dataskydd.</p>
        <p><a href="https://www.espoo.fi/sv/esbo-stad/dataskydd" target="_blank".
        aria-label="Esbo stad: Dataskydd. Länken öppnas i ett nytt fönster.">Esbo stad: Dataskydd</a></p>
        <p><a href="https://www.hel.fi/helsinki/sv/stad-och-forvaltning/information/dataskydd/noggrannare-om-rattigheter-dataskyddsforordning" 
        target="_blank" aria-label="Helsingfors stad: 
        Mer om rättigheterna enligt EU:s allmänna dataskyddsförordning. Länken öppnas i ett nytt fönster.">Helsingfors stad: 
        Mer om rättigheterna enligt EU:s allmänna dataskyddsförordning</a></p>
        <p><a href="https://www.kauniainen.fi/sv/dataskydd/" target="_blank" aria-label="Grankulla stad: Dataskydd. Länken öppnas i ett nytt fönster.">
        Grankulla stad: Dataskydd</a></p>
        <p><a href="https://www.vantaa.fi/sv/staden-och-beslutsfattandet/beslutsfattande/behandling-av-personuppgifter" target="_blank"
        aria-label="Vanda stad: Behandling av personuppgifter. Länken öppnas i ett nytt fönster.">Vanda stad: Behandling av personuppgifter</a></p>
        
        <h3>Rätt att lämna in ett klagomål till tillsynsmyndigheten</h3>
        <p>Du har rätt att lämna in ett klagomål till tillsynsmyndigheten om du anser att behandlingen av dina personuppgifter strider mot EU:s allmänna dataskyddsförordning (EU) 2016/679. 
        Dessutom har du rätt att använda andra administrativa medel för sökande av ändring samt rättsskyddsmedel.</p>
        <p><a href="http://www.tietosuoja.fi/sv/" target="_blank" aria-label="Dataombudsmannens byrå. Länken öppnas i ett nytt fönster.">Dataombudsmannens byrå</a></p>
        <p>Besöksadress: Fågelviksgränden 4</p><p>Postadress: PB 800, 00531 Helsingfors</p>
        <p>E-post: <a href="mailto:tietosuoja@om.fi">tietosuoja@om.fi</a></p>
        <p>Telefonväxel: 029 566 6700</p>
        
        <h3>Dataskyddsombud</h3>
        <p>Esbo: <a href="mailto:tietosuoja@espoo.fi">tietosuoja@espoo.fi</a>&nbsp;</p>
        <p>Helsingfors: <a href="mailto:tietosuoja@hel.fi">tietosuoja@hel.fi</a></p>
        <p>Grankulla: <a href="mailto:tietosuoja@kauniainen.fi">tietosuoja@kauniainen.fi</a></p>
        <p>Vanda: <a href="mailto:tietosuojavastaava@vantaa.fi">tietosuojavastaava@vantaa.fi</a></p>
        <p>Senast uppdaterad 6.3.2023</p>
      </div>
   </div>
</div>