<? $this->headTitle($this->translate('Asiakastietokoneet ja tulostaminen')); $this->content()->setHeading($this->translate('Asiakastietokoneet ja tulostaminen'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Voit varata asiakastietokoneen itse internetin kautta. Ajanvarausjärjestelmä myös valvoo koneelle kirjautumista. Kirjautuminen edellyttää tunnusluvun käyttöä, joka tarkistetaan 
        kirjastojärjestelmästä.</p>
        <p>Henkilökunta opastaa tarvittaessa tietokoneiden käytössä. Kirjastossa järjestetään myös tietokoneen ja internetin käytön peruskursseja. Kysy lisätietoa omasta kirjastostasi.</p>
        <p><a href="http://varaus.lib.hel.fi" target="_blank" aria-label="Tietokoneiden varaus Helsingissä. Linkki avautuu uudessa ikkunassa.">Tietokoneiden varaus Helsingissä</a>.
        Espoossa ja Vantaalla koneille mennään ilman ajanvarausta. Käyttäjätunnus on kirjastokorttisi numero ja salasana PIN-koodisi.</p>
      </div>
      <div id="espoo" class="content-section">
        <h2>Tulostaminen Espoossa</h2>
        <p>Espoon kirjastoissa tulostamiseen käytetään Princh-tulostusohjelmaa. Tulostus on tietoturvallista, koska paperit tulostuvat vasta, kun asiakas itse vapauttaa tulosteet 
        kertakäyttöisellä tunnusluvulla. Tulostusohjelma mahdollistaa tulostamisen myös omalta tietokoneelta verkon kautta tai älylaitteelta.</p>
        <p>Tulostaminen maksaa 0,20 €/sivu. Voit maksaa tulosteet kassalla kortilla tai sähköisesti. Tulosteita ei voi maksaa käteisellä.</p>
        <p>Maksua ei peritä, jos tuloste on välttämätön työllistymiseen, toimeentuloon, sosiaalietuuksiin tai maahanmuuttoon liittyvässä asioinnissa. Näiden maksuttomien 
        tulosteiden maksimimäärä yhdellä tulostuskerralla on 20 kappaletta ja onnistuu henkilökunnan avulla asiakaspalveluaikoina. Lapset (alle 18-vuotiaat) saavat tulostaa 
        20 sivua maksutta.</p>
        <p>Kirjastossa voi tulostaa vain kirjaston tarjoamalle kopiopaperille.</p>
        
        <h3>Tulostaminen kirjaston tietokoneilla</h3>
        <p>Kirjastoissa voit tulostaa asiakastietokoneilta. Tulostus aloitetaan tietokoneella normaalisti käytetyn ohjelman tulostustoiminnolla. Kun lähetät tulosteen tietokoneelta 
        tulostimelle eli painat Tulosta-painiketta, tietokone lataa tulosteen Princh-tulostusohjelmaan ja avaa Princh-ikkunan. Tiedoston lataamisen jälkeen tiedostonimen vierestä 
        valitaan mustavalkoinen tai värillinen tulostus, kopioiden määrä ja lisävalinnat. Lähtökohtaisesti tuloste on värillinen ja yksipuolinen.</p>
        <p>Kun olet tyytyväinen asetuksiin, hyväksy järjestelmän käyttösäännöt ja siirry seuraavaan vaiheeseen valitsemaan maksutapa. Voit maksaa tulosteen etukäteen 
        pankkikortilla, MobilePaylla tai PayPalilla. Maksu palautuu automaattisesti 72 tunnin jälkeen, jos et vapautta tulostusta 24 tunnin sisällä. Huomaathan, että 
        MobilePay veloittaa maksukerrasta 0,16 euroa palvelumaksuja.</p>
        <p>Jos haluat maksaa kirjastossa kortilla tai tulostaa välttämättömiä papereita maksutta, voit valita maksun tiskillä. Sivu kysyy nimeäsi, jotta voit kertoa 
        kirjastovirkailijalle nimesi ja pyytää tulostuksen vapauttamista.</p>
        <p>Maksun hoidon jälkeen sivu antaa sinulle nelinumeroisen tunnusluvun. Kirjoita tunnus muistiin. Syötä tunnusluku tulostimen viereiselle tabletille ja työsi vapautuu. 
        Tulostaminen ei ole mahdollista ilman nelinumeroista tunnuslukua. Jos olet valinnut maksun tiskillä, sinun pitää suorittaa maksu ennen kuin tunnusluku toimii.</p>
        <p>Jos haluat tulostaa useita tiedostoja samalla kertaa, se on mahdollista. Kun ensimmäinen tiedosto on latautunut Princh-tulostusohjelmaan, pienennä Princh-tulostusohjelman 
        ikkuna ennen maksutavan valintaan siirtymistä. Tämän jälkeen voit lähettää uuden tiedoston Princh-tulostusohjelmaan.</p>
        <p>Henkilökunta opastaa sinua tarvittaessa tulostamisessa.</p>
        
        <h3>Tulostus omalta tietokoneelta</h3>
        <p>Verkon kautta tulostus onnistuu <a href="https://print.princh.com/" target="_blank">Princh-tulostussivulta (print.princh.com)</a>. Ensin sivulla syötetään 
        kuusinumeroinen halutun kirjaston tulostinnumero. Tämän jälkeen sivulle ladataan tulostettava tiedosto. Tiedoston koko voi olla korkeintaan 30 megatavua.</p>
        <p>Kirjastokohtaisten tulostinten numerot ovat seuraavat:</p>
        <ul class="list-bullets">
          <li>Entresse, tulostin 1: 103479 </li>
          <li>Entresse, tulostin 2: 103496 </li>
          <li>Haukilahti: 103474 </li>
          <li>Iso Omena, tulostin 1: 103494 </li>
          <li>Iso Omena, tulostin 2: 103499</li>
          <li>Iso Omena, tulostin 3: 103495 </li>
          <li>Kalajärvi: 103498 </li>
          <li>Karhusuo: 103484 </li>
          <li>Kauklahti: 103478 </li>
          <li>Laajalahti: 103490 </li>
          <li>Laaksolahti: 103489 </li>
          <li>Lippulaiva, tulostin 1: 103497</li>
          <li>Lippulaiva, tulostin 2: 103493</li>
          <li>Nöykkiö: 103492 </li>
          <li>Otaniemi: 103481 </li>
          <li>Saunalahti: 103491 </li>
          <li>Sello, tulostin 1: 103480 </li>
          <li>Sello, tulostin 2: 103483 </li>
          <li>Sello, tulostin 3: 103488 </li>
          <li>Suurpelto: 103487 </li>
          <li>Tapiola: 103486 </li>
          <li>Viherlaakso: 103485 </li>
        </ul>
        <p>Tiedoston lataamisen jälkeen tiedostonimen vierestä valitaan mustavalkoinen tai värillinen tulostus, kopioiden määrä ja lisävalinnat. Lähtökohtaisesti tuloste on 
        värillinen ja yksipuolinen.</p>
        <p>Seuraavaksi tulostus maksetaan. Voit maksaa tulosteen etukäteen pankkikortilla, MobilePaylla ja PayPalilla. Maksu palautuu automaattisesti 72 tunnin jälkeen, jos et 
        käy kirjastossa vapauttamassa tulostusta 24 tunnin sisällä. Huomaathan, että MobilePay veloittaa maksukerrasta 0,16 euroa palvelumaksuja.</p>
        <p>Jos haluat maksaa kirjastossa kortilla tai tulostaa välttämättömiä papereita maksutta, voit valita maksun tiskillä. Sivu kysyy nimeäsi, jotta voit kertoa 
        kirjastovirkailijalle nimesi ja pyytää tulostuksen vapauttamista. </p>
        <p>Maksun hoidon jälkeen sivu antaa sinulle nelinumeroisen tunnusluvun. Kirjoita tunnus muistiin. Kirjastossa syötä tunnusluku tulostimen viereiselle tabletille 
        ja työsi vapautuu. Tulostaminen ei ole mahdollista ilman nelinumeroista tunnuslukua. Jos olet valinnut maksun tiskillä, sinun pitää suorittaa maksu ennen kuin tunnusluku 
        toimii.</p>
        
        <h3>Tulostaminen mobiilisovelluksella tai kirjastossa </h3>
        <p>Voit asentaa älylaitteeseesi Princh-sovelluksen, joka löytyy <a href="https://play.google.com/store/apps/details?id=princh.princh" target="_blank">
        Googlen Play Storesta</a> ja <a href="https://apps.apple.com/gb/app/princh/id999408628" target="_blank">Apple App Storesta</a>. Tämän jälkeen omalla puhelimella olevia 
        tiedostoja tulostetaan käyttämällä puhelimen "Jaa" -valintaa ja valitsemalla jakotavaksi Princh-ohjelma. Ohjelma kertoo tarkemmat ohjeet käyttöön.</p>
        <h4>Kopiointi</h4>
        <p>Voit kopioida 20 sivua maksutta. Yli 20 sivua ylittävistä kopioista peritään 0,20 €/sivu jokaisesta 20 sivua ylittävästä sivusta. Maksa kopiot kirjaston henkilökunnalle.</p>
        <h4>Skannaus</h4>
        <p>Voit skannata dokumentteja ja kuvia kirjaston monitoimilaitteilla maksutta. Monitoimilaite tallentaa skannauksen laitteeseen kytketylle muistitikulle. Voit käyttää omaa 
        muistitikkuasi tai lainata kirjaston henkilökunnalta muistitikun kirjastokortilla.</p>
      </div>
      <div id="helsinki" class="content-section">
        <h2>Tulostaminen Helsingissä</h2>
        <h3>Tulostaminen asiakastietokoneilta</h3>
        <p>Luo käyttäjätunnus tulostuspalveluun klikkaamalla työpöydällä olevaa linkkiä YSoft SafeQ tai osoitteessa asiakastulostus.hel.fi.</p>
        <p>Aktivoi tunnuksesi sähköpostiisi saapuneesta linkistä Activate your account ja ota talteen viestissä oleva PIN-koodi. Tätä samaa PIN-koodia voit käyttää asiakaskoneilta 
        tulostamiseen kaikissa Helsingin kaupunginkirjaston toimipisteissä.</p>
        <p>Omalta laitteelta tulostaessasi tarvitset PIN-koodin lisäksi käyttäjätunnuksesi sähköpostiosoitteen ja salasanan.</p>
        <p>Asiakastietokoneella: </p>
        <ol class="list-numbers">
            <li>Valitse tulostettava tiedosto tai etsi nettisivu, jonka haluat tulostaa ja klikkaa Tulosta. Tulostusasetukset-ikkuna avautuu. Voit muuttaa tulostusasetuksia, 
            esimerkiksi valita tulostettavaksi vain tietyn sivun. Oikean tulostimen valinta on automaattinen.</li>
            <li>Klikkaa Tulostusasetukset-ikkunassa Tulosta. PIN-koodin syöttöikkuna avautuu.</li>
            <li>Syötä tunnuksesi PIN-koodi ja paina Kirjaudu sisään tai Enter.</li>
        </ol>
        <p>Voit noutaa kaikki lähettämäsi tulosteet kerralla. Lukitse tietokone tulosteiden noudon ajaksi, jos haluat jatkaa työskentelyä.</p>
        <p>Kirjaudu ulos, jollet enää tarvitse tietokonetta.</p>
        <p>Maksa tulosteet kirjaston asiakaspalvelupisteessä. Tulosteen hinta on 0,40 € kpl.</p>
        
        <h3>Tulostaminen omalta laitteelta</h3>
        <p>Luo käyttäjätunnus tulostuspalveluun osoitteessa <a href="https://asiakastulostus.hel.fi" target="_blank">asiakastulostus.hel.fi</a>.</p>
        <p>Aktivoi tunnuksesi sähköpostiisi saapuneesta Activate your account -linkistä. Ota talteen viestissä oleva PIN-koodi ja salasanasi. Samaa PIN-koodia voit käyttää 
        tulosteiden vapauttamiseen kaikissa Helsingin kaupunginkirjaston toimipisteissä.</p>
        <p>Voit tulostaa omalta laitteeltasi kaikkia yleisimpiä tiedostomuotoja (PDF, DOCX, JPG...). </p>
        <p>Tulosteiden hinta on 0,40 € / arkki.</p>
        <p>Omalla laitteella:</p>
        <ol class="list-numbers">
            <li>Kirjaudu tulostuspalveluun osoitteessa <a href="https://asiakastulostus.hel.fi" target="_blank">asiakastulostus.hel.fi</a>. Voit vaihtaa kielen Valikosta.</li>
            <li>Avaa Valikko ja valitse Lataa työ.</li>
            <li>Napauta Lisää tulostustyö -kuvaketta ja etsi haluamasi tiedosto laitteeltasi. Laitteestasi riippuen voit valita kerralla useamman tiedoston.</li>
            <li>Lähetä tiedosto valitsemalla Lataa. Voit lisätä tiedostoja valitsemalla Lisää tiedosto.</li>
        </ol>
      </div>
      <div id="vantaa" class="content-section">
        <h2>Tulostaminen Vantaalla</h2>
        <p>Vantaan kirjastoissa tulostus, kopiointi ja skannaus on maksutonta. Tulosteita tai kopioita voi ottaa päivässä enintään 20 mustavalkoista tai 2 värillistä sivua.</p>
        <p>Tarvitset tulostamiseen, kopiointiin ja skannaukseen kirjastokortin. Kirjastokortin avulla voit helposti rekisteröityä tulostusjärjestelmään. Rekisteröinti tarvitsee 
        tehdä vain kerran, ja se on voimassa toistaiseksi. Henkilökunta auttaa sinua tarvittaessa.</p>
        
        <p>Tulostus tapahtuu kirjaston tietokoneilta. Tarvitset tulostamiseen kirjastokortin. Tulostaminen omasta laitteesta ei ole mahdollista.</p>
        <p>Tulosteet tulevat A4-kokoisille paperiarkeille.</p>
        
        <h3>Kopiointi ja skannaus</h3>
        <p>Tarvitset kopiointiin ja skannaukseen kirjastokortin. Voit valita kopioitavan sivun kooksi A4 tai A3. Voit myös skannata paperisia asiakirjoja digitaaliseen muotoon. 
        Skannatut tiedostot lähetetään suoraan sähköpostiosoitteeseen, jonka olet antanut rekisteröinnin yhteydessä. Skannaus muistitikulle ei ole mahdollista.</p>
      </div>
           <div id="käyttösäännöt" class="content-section">
        <h2>Asiakastietokoneiden käyttösäännöt</h2>
        <p>Tervetuloa asiakaskoneen käyttäjäksi HelMet-kirjastoon!</p>
        <ol class="list-numbers">
            <li>Asiakaskoneen käyttö on maksutonta. Tarkista tulostemaksut kirjastosi maksutaulukosta.</li>
            <li>Käytä vain omia tunnuksiasi. Ne ovat henkilökohtaiset ja olet vastuussa niiden käytöstä.</li>
            <li>Henkilökunta auttaa sinua mielellään. Muista kuitenkin, että olet itse vastuussa nettiasioimisestasi.</li>
            <li>Kunnioita muita verkonkäyttäjiä ja kirjaston asiakkaita.</li>
            <li>Kunnioita kuntalaisten yhteistä omaisuutta.</li>
            <li>Kirjasto ei vastaa tietokoneilla aiheutetuista vahingoista.</li>
            <li>Viranomaisilla on oikeus saada koneen käyttäjätietoja rikostutkintatapauksissa.</li>
            <li>Kirjasto ei vastaa vahingoista, jotka aiheutuvat teknisestä viasta, muista verkonkäyttäjistä tai käyttäjän toiminnasta.</li>
            <li>Kirjasto määrittelee ajanvarauksen ehdot.</li>
            <li>Kirjaston asiakastietokoneiden, tietoverkkojen ja järjestelmien käyttäjänä olet sitoutunut noudattamaan näitä sääntöjä. Ellei sääntöjä noudateta, kirjasto voi evätä 
            koneiden käyttöoikeuden määräajaksi. Menettelynä sovelletaan HelMet-kirjaston käyttösääntöjen kohtaa käyttöoikeuden menetyksestä.</li>
          </ol>
          <p>Tutustu myös:</p>
          <ul class="list-bullets">
            <li><a href="http://www.internetopas.com/netiketti" target="_blank" aria-label="Netiketti. Linkki avautuu uudessa ikkunassa.">Netiketti</a></li>
            <li><a href="https://kopiraittila.fi/" target="_blank" aria-label="Tekijänoikeus. Linkki avautuu uudessa ikkunassa.">Tekijänoikeus</a></li>
          </ul>
      </div>
   </div>
</div>
