<? $this->headTitle($this->translate('Kunddatorer och utskrift')); $this->content()->setHeading($this->translate('Kunddatorer och utskrift'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Du kan själv boka en kunddator via internet. Bokningssystemet sköter också inloggningen på datorerna. Du måste ha en PIN-kod för att logga in.
        Personalen hjälper dig vid behov att använda datorerna. I biblioteken arrangeras också grundkurser i datorkunskap och internet. 
        Fråga mera på ditt eget bibliotek.</p>
        <p><a href="https://varaus.lib.hel.fi/default.aspx?cid=sv-FI" target="_blank" 
        aria-label="Boka en dator i  Helsingfors. Länken öppnas i ett nytt fönster.">Boka en dator i  Helsingfors</a>. I Esbo och i Vanda kan du 
        använda datorerna utan tidsbeställning. Ditt bibliotekskorts nummer fungerar som användarnamn och din PIN-kod som lösenord.</p>
      </div>
      <div id="esbo" class="content-section">
        <h2>Utskrivning, kopiering och scanning i Esbo stadsbibliotek </h2>
        <p>Du kan kopiera, skriva ut och scanna med multifunktionsskrivare som hittas i Esbo bibliotek. Du kan använda bibliotekets dator, 
        din egen dator eller mobil apparat för att skriva ut.</p>
        <h3>Utskrivning</h3>
        <p>Man använder ett Princh-utskrivningsprogram för att skriva ut i Esbo bibliotek. Det är datasäkert att skriva ut, eftersom papperen 
          skrivs ut först då när kunden själv frigör utskrifterna med en engångs-sifferkod. Utskrivningsprogrammet möjliggör utskrivning även 
          från egen dator via nätet eller smartapparat.</p>
          <p>At skriva ut dokument kostar 0,20 euro per sida. Utskrifterna kan betalas med kort eller genom elektronisk betalning. Vi tar 
          inte emot kontantbetalning.</p>
          <p>Det är fortsättningsvis gratis att skriva ut då ärendet gäller arbetssökning, utkomststöd, sociala förmåner eller invandring. 
          Det maximala antalet avgiftsfria utskrivningar är 20 sidor per gång. För barn (under 18 år) är det också gratis att skriva ut 20 sidor 
          per gång.</p>
          <p>I biblioteket kan man bara skriva ut på kopieringspapper som erbjuds av biblioteket.</p>
          <h4>Att skriva ut med hjälp av bibliotekens datorer</h4>
          <p>I biblioteket kan man skriva ut från kunddatorerna. Utskrivningen påbörjas normalt på kunddatorn med utskrivingsfunktionen som finns i 
          programmet som man använder. När du skickar utskriften från datorn till skrivaren, det vill säga när du trycker på Skriv ut-knappen, 
          så laddar datorn utskriften till Princh-utskrivningsprogrammet och öppnar Princh-fönstret. Efter att du laddat upp dokumentet väljer du 
          (bredvid dokumentets namn) om du vill ha svartvit eller färg-utskrift, antal utskrifter och tilläggsval.</p>
          <p>Utgångspunkten är att utskriften är färgutskrift och enkelsidig.</p>
          <p>När du är nöjd med inställningarna, så godkänn systemets användningsregler och flytta dig till nästa steg för att välja betalningssätt.
          Betalningen kan göras på förhand med bankkort, MobilePay eller PayPal. Betalningen återbetalas automatiskt efter 72 timmar ifall du valt 
          att inte befria utskriften på biblioteket inom 24 timmar. Märk väl att MobilePay tar en avgift på 0,16 euro som serviceavgift.</p>
          <p>Om du vill betala utskriften på biblioteket med kort eller skriva ut nödvändiga dokument gratis, välj alternativet att betala 
          vid kassan. Sidan ber om ditt namn så att du kan be personalen befria ditt dokument.</p>
          <p>När betalningen är genomförd ger systemet dig en fyra-siffrig kod. Lägg koden på minnet. Skriv in koden i surfplattan som är 
          bredvid printern och ditt arbete befrias. Det är inte möjligt att skriva ut utan ett sifferkod med fyra siffror. Om du har valt att 
          betala vid disken så bör du betala innan sifferkoden fungerar.</p>
          <p>Om du vill skriva ut flera dokument på samma gång, så är det möjligt. När det första dokumentet har laddats till 
          Princh-utskrivningsprogrammet, så förminska Princh-utskrivningsprogrammets fönster innan du övergår till att välja betalningssätt. 
          Efter det här kan du skicka det nya dokumentet till Princh-utskrivningsprogrammet.</p>
          <p>Personalen hjälper dig vid behov.</p>
          
          <h4>Utskrifter från egen dator</h4>
          <p>Via nätet går det att skriva ut via <a href="https://print.princh.com/" target="_blank" 
          aria-label="Princh-utskrivningssidan. Länken öppnas i ett nytt fönster.">Princh-utskrivningssidan (print.princh.com)</a>. 
          Först skriver du in den valda printerns sexsiffriga printerkod. Efter detta laddar du upp dokumentet du vill skriva ut. Dokumentets 
          storleksgräns är 30 megabyte.</p>
          <p>Numren för de olika printrarna på biblioteken är enligt följande: </p>
          <ul class="list-bullets">
            <li>Bastvik: 103491</li>
            <li>Björnkärr: 103484</li>
            <li>Bredvik: 103490</li>
            <li>Dalsvik: 103489</li>
            <li>Entresse, printer 1: 103479</li>
            <li>Entresse, printer 2: 103496</li>
            <li>Gröndal: 103485</li>
            <li>Gäddvik: 103474</li>
            <li>Hagalund: 103486</li>
            <li>Iso Omena, printer 1: 103494</li>
            <li>Iso Omena, printer 2:103499</li>
            <li>Iso Omena, printer 3 : 103495</li>
            <li>Kalajärvi: 103498</li>
            <li>Köklax: 103478</li>
            <li>Lippulaiva, printer 1: 103497</li>
            <li>Lippulaiva, printer2: 103493</li>
            <li>Nöykis: 103492</li>
            <li>Otnäs: 103481</li>
            <li>Sello, printer 1: 103480</li>
            <li>Sello, printer 2: 103483</li>
            <li>Sello, printer 3: 103488</li>
            <li>Storåkern: 103487</li>
          </ul>
          <p>Efter att du laddat upp dokumentet väljer du (bredvid dokumentets namn) om du vill ha svartvit eller färg-utskrift, antal utskrifter och 
          tilläggsval.</p>
          <p>Utgångspunkten är att utskriften är färgutskrift och enkelsidig.</p>
          <p>Till näst betalas utskriften. Betalningen kan göras på förhand med bankkort, MobilePay eller PayPal. Betalningen återbetalas automatiskt 
          efter 72 timmar ifall du valt att inte befria utskriften på biblioteket inom 24 timmar. Märk väl att MobilePay tar en avgift på 0,16 euro 
          som serviceavgift.</p>
          <p>Om du vill betala utskriften på biblioteket med kort eller skriva ut nödvändiga dokument gratis, välj alternativet att betala vid kassan. 
          Sidan ber om ditt namn så att du kan be personalen befria ditt dokument.</p>
          <p>När betalningen är genomförd ger systemet dig en fyra-siffrig kod. Lägg koden på minnet. På biblioteket används koden för att skriva ut 
          dokumenten vid printern. Det är inte möjligt att skriva ut utan ett sifferkod med fyra siffror. Om du har valt att betala vid disken så 
          bör du betala innan sifferkoden fungerar.</p>
          <h4>Utskrifter via en mobil-app</h4>
          <p>Du kan ladda ner Princh-appen till din smartapparat. Den hittas på 
          <a href="https://play.google.com/store/apps/details?id=princh.princh" target="_blank" 
          aria-label="Google Play Store. Länken öppnas i ett nytt fönster.">Google Play Store</a> och 
          <a href="https://apps.apple.com/gb/app/princh/id999408628" target="_blank" 
          aria-label="Apple App Store. Länken öppnas i ett nytt fönster.">Apple App Store</a>. Efter detta kan du skriva ut dokument från din 
          apparat genom att använda apparatens ”Dela”-funktion och välja Princh-programmet. Programmet ger noggrannare instruktioner.</p>
          <h3>Kopiering</h3>
          <p>Du kan kopiera 20 sidor avgiftsfritt. För kopior som överskrider 20 sidor debiteras 0,20 €/sida för varje sida som överskrider 20 sidor. 
          Betala kopiorna åt bibliotekets personal.</p>
          <h3>Scanning</h3>
          <p>Du kan scanna dokument och bilder avgiftsfritt med bibliotekets multifunktionsskrivare. Multifunktionsskrivaren lagrar scanningen 
          till minnessticka som är anslutad till apparaten. Du kan använda din egen minnessticka eller låna en minnessticka med bibliotekskort av 
          bibliotekets personal.</p>
      </div>
      <div id="helsinfors" class="content-section">
        <h2>Utskrivning i Helsingfors stadsbibliotek </h2>
        <h3>Utskrift vid kunddatorer</h3>
        <p>Skapa ett användarkonto för utskrift genom att klicka på länken på skrivbordet YSoft SafeQ eller på adressen asiakastulostus.hel.fi
        Aktivera ditt användarnamn genom länken du får till din e-post genom att trycka på länken Activate your account och spara den PIN-kod du 
        får i meddelandet. Samma PIN-kod kan användas för att skriva ut dokument vid alla kunddatorer i alla Helsingfors stadsbibliotek. 
        Om du skriver ut från egen apparat behöver du dessutom användarnamn, e-postadress och lösenord.</p>
        <p>Vid kunddatorer:</p>
        <ol class="list-numbers">
            <li>Välj den fil eller den nätsida du vill skriva ut och klicka Skriv ut/Tulosta. Fönstret för utskriftsinställningar öppnas. Du kan 
            ändra utskriftsinställningar, exempelvis skriva ut endast en vald sida. Val av utskrivare sker automatiskt.</li>
            <li>Klicka på Skriv ut/Tulosta. Fönster för att skriva PIN-kod öppnar sig.</li>
            <li>Skriv din PIN-kod och tryck på Logga in eller Enter. Du kan hämta alla dina utskriftsarbeten på en gång. Lås datorn medan du 
            hämtar dina dokument från utskrivaren om du vill fortsätta jobba.</li>
            <li>Logga ut då du ej längre använder datorn.</li>
            <li>Betala de utskrivna dokumenten vid servicedisken, de kostar 0,40€ styck.</li>
        </ol>
        
        <h3>Utskrift från egen apparat</h3>
        <p>Skapa ett användarkonto för utskrift på adressen <a href="https://asiakastulostus.hel.fi" target="_blank" 
        aria-label="asiakastulostus.hel.fi. Länken öppnas i ett nytt fönster.">asiakastulostus.hel.fi</a>. Aktivera ditt användarnamn genom 
        länken du får till din e-post genom att trycka på länken Activate your account och spara den PIN-kod och det lösenord du får i meddelandet.
        Samma PIN-kod kan användas för att skriva ut dokument vid alla kunddatorer i alla Helsingfors stadsbibliotek. Du kan skriva ut alla 
        vanliga filformat (PDF, DOCX, JPEG...). De utskrivna dokumenten kostar 0,40€ styck och betalas vid servicedisken.</p>
        <p>Vid egen apparat</p>
        <ol class="list-numbers">
            <li>Logga in på adressen <a href="https://asiakastulostus.hel.fi" target="_blank"
            aria-label="asiakastulostus.hel.fi. Länken öppnas i ett nytt fönster.">asiakastulostus.hel.fi</a>. Du kan ändra språk i Menyn.</li>
            <li>Öppna Menyn och välj Överför jobb.</li>
            <li>Klicka på Tryck här för att lägga till utskriftsjobb  -symbolen och sök framden önskade filen från din dator. 
            Beroende på apparat kan du välja flera filer på en gång.</li>
            <li>Skicka filen genom att välja Överför.  Du kan lägga till filer genom att välja Lägg till fil.</li>
        </ol>
      </div>
      <div id="vanda" class="content-section">
        <h2>Utskrift och kopiering vid biblioteken i Vanda </h2>
        <p>Du behöver ett bibliotekskort för att skriva ut, kopiera eller skanna dokument. Med ditt bibliotekskort kan du enkelt 
        registrera dig som användare i systemet. Du behöver endast registrera dig en gång och registreringen gäller tills vidare. 
        Personalen hjälper dig vid behov.</p>
        <p>Du får göra 20 svartvita utskrifter eller 2 färgutskrifter eller kopior per dag. Utskrivningen och kopieringen är avgiftsfria.</p>
        <p>Utskrifterna görs från bibliotekets datorer. Du kan inte skriva ut dokument från din egen dator.</p>
        <p>Du kan också skanna pappershandlingar till digitalt format. De skannade filerna skickas direkt till den e-postadress som du har lämnat i 
        samband med registreringen. Du kan inte skanna dokument till ett USB-minne.</p>
      </div>
      <div id="regler" class="content-section">
        <h2>Regler för användning av kunddatorerna</h2>
        <p>Välkommen att använda kunddatorerna!</p>
      <ol class="list-numbers">
        <li>Det är gratis att använda kunddatorerna. Kontrollera vad en utskrift kostar i avgiftstabellen på ditt bibliotek.</li>
        <li>Använd endast dina egna användarlösen. De är personliga och du ansvarar för användningen av dem.</li>
        <li>Personalen hjälper gärna till. Du ska ändå komma ihåg att du själv ansvarar för din internetanvändning.</li>
        <li>Respektera andra internetanvändare och besökare på biblioteket.</li>
        <li>Respektera kommuninvånarnas gemensamma egendom.</li>
        <li>Biblioteket svarar inte för skador som orsakats av datoranvändningen.</li>
        <li>Myndigheterna har rätt att vid brottsutredningar få reda på vem som använt datorerna.</li>
        <li>Biblioteket svarar inte för skador som beror på tekniskt fel eller orsakats av internetanvändare.</li>
        <li>Biblioteket sätter upp villkoren för tidsbokning.</li>
        <li>Som användare av bibliotekets kunddatorer, datanät och system har du förbundit dig till att följa dessa regler. Om reglerna inte följs kan biblioteket för en viss
        tid förvägra rätten att använda datorerna. Då tillämpas punkten Att förlora sin nyttjanderätt i HelMet-bibliotekets låneregler.</li>
      </ol>
      <p>Se även:</p>
      <ul class="list-bullets">
        <li><a href="https://kopiraittila.fi/sv/" target="_blank" aria-label="Upphovsrätt. Länken öppnas i ett nytt fönster.">Upphovsrätt</a></li>
      </ul>
      </div>
   </div>
</div>
