<? $this->headTitle($this->translate('Customer computers and printing')); $this->content()->setHeading($this->translate('Customer computers and printing'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>You can reserve a customer computer online. The reservation system also monitors logging in to the computer. Logging in requires a PIN code that will be checked in the
        library system. The staff provides guidance in using computers, as needed. The library also organises beginners' computer and internet courses. Ask your library for more information.</p>
        
        <p><a href="https://varaus.lib.hel.fi/default.aspx?cid=en-GB" target="_blank" aria-label="Book a computer in Helsinki. The link opens in a new window">
        Book a computer in Helsinki</a>. In Espoo and in Vantaa computers are available without reservation. our user ID is your library card number and the password your PIN code.</p>
      </div>
      <div id="espoo" class="content-section">
        <h2>Copying, printing, and scanning at the Espoo city library</h2>
        <p>You can copy, print, and scan with the multifunction devices in Espoo libraries. You can use computers at the library, your own computer or mobile device to print.</p>
        <h3>Copying</h3>
        <p>You can copy up to 20 pages free of charge. If you copy more than 20 pages, you are charged 0,20€ for every page over 20. You can pay them to library staff.</p>
        <h3>Scanning</h3>
        <p>You can scan documents and photos with the multifunction device at the library. The device saves scanned documents to a memory stick. You can use your own memory stick or
        borrow one from library staff with your library card.</p>
        <h3>Printing</h3>
        <p>Libraries in Espoo use printing application Princh. Printing is secure for users as the prints are released only when the user themself is at the printer and enters 
        their four-digit code. With the printing application you can also print over internet from your own computer or from a mobile device.</p>
        <p>Printing costs 0,20 € per page. The prints can be paid either with a card at the library or via online payment.</p>
        <p>There is no fee if the print is necessary for employment, sustenance, social assistance and benefits, or immigration. The maximum for free prints is 20 pages and it is 
        offered during customer service hours. Printing up to 20 pages is also free for children (under the age of 18).</p>
        <p>You can print only to the copy paper provided by the library.</p>
        
        <h4>Printing at the library</h4>
        <p>At the library you can print from the customer computers. Start printing as usual with the program you are using. When you send the print from the computer to the printer 
        by clicking the print button, the computer will upload the file to the printing application Princh and open a new window. After uploading the file, next to the file name 
        there is a selection for grayscale or color print, number of copies and additional options. By default, the prints are in color and one sided.</p>
        <p>When you are happy with the settings, accept the terms of service and move forward to choosing the payment method. You can pay via a card, with PayPal or MobilePay. 
        The payment will be refunded automatically after 72 hours if you do not release the print at the library within 24 hours. Please note that MobilePay charges additional, 
        0,16 euros transaction fee for the payments.</p>
        <p>If you wish to pay with a card at a library or print necessary papers without fee, you can select “pay at checkout”. The page will ask your name so you can tell the 
        library staff your name for them to identify and release your print.</p>
        <p>After the payment selection page, the website will give you a four-digit code for your print. Write the code up. Enter the code to a tablet next to the printer 
        to print your document. You cannot print without the four-digit code. If you have chosen to pay at checkout, you need to first pay your print to the staff before the 
        code will work.</p>
        <p>If you want to print multiple files at once, that is also possible. When the first file has been uploaded to the Princh printing application, minimize the Printch 
        window before you move forward to choosing a payment method. After this you can send another file to Princh.</p>
        <p>The library staff will assist you in printing at the library.</p>
        
        <h4>Printing using your own computer</h4>
        <p>You can send prints from your computer at <a href="https://print.princh.com/" target="_blank">the Princh printing site (print.princh.com)</a>. At first you will enter 
        a six-digit printer number of the library you want to send the print to. After that you can upload the file to the page. Size limitation is 30 megabytes.</p>
        <p>The printer numbers for libraries are the following:</p>
        <ul class="list-bullets">
          <li>Entresse, printer 1: 103479</li>
          <li>Entresse, printer 2: 103496</li>
          <li>Haukilahti: 103474</li>
          <li>Iso Omena, printer 1: 103494</li>
          <li>Iso Omena, printer 2: 103499</li>
          <li>Iso Omena, printer 3: 103495</li>
          <li>Kalajärvi: 103498</li>
          <li>Karhusuo: 103484</li>
          <li>Kauklahti: 103478</li>
          <li>Laajalahti: 103490</li>
          <li>Laaksolahti: 103489</li>
          <li>Lippulaiva, printer 1: 103497</li>
          <li>Lippulaiva, printer 2: 103493</li>
          <li>Nöykkiö: 103492</li>
          <li>Otaniemi: 103481</li>
          <li>Saunalahti: 103491</li>
          <li>Sello, printer 1: 103480</li>
          <li>Sello, printer 2: 103483</li>
          <li>Sello, printer 3: 103488</li>
          <li>Suurpelto: 103487</li>
          <li>Tapiola: 103486</li>
          <li>Viherlaakso: 103485</li>
        </ul>
        <p>After uploading the file, next to the file name there is a selection for grayscale or color print, number of copies and additional options. By default, the prints 
        are in color and one sided.</p>
        <p>Following this the print will be paid. You can pay at your own computer via a debit card, with PayPal or MobilePay. The payment will be refunded automatically after 
        72 hours if you do not release the print at the library within 24 hours. Please note that MobilePay charges additional, 0,16 euros transaction fee for the payments.</p>
        <p>If you wish to pay with a debit card at a library or print necessary papers without fee, you can select “pay at checkout”. The page will ask your name so you can 
        tell the library staff your name for them to identify and release your print.</p>
        <p>After the payment selection page, the website will give you a four-digit code for your print. Write the code up. At the library, enter the code to a tablet next 
        to the printer to print your document. You cannot print without the four-digit code. If you have chosen to pay at checkout, you need to first pay your print to the 
        staff before the code will work.</p>
        
        <h4>Printing with the mobile app</h4>
        <p>You can insta the Princh printing app to your smart device from <a href="https://play.google.com/store/apps/details?id=princh.princh" target="_blank">Google Play Store</a> 
        or <a href="https://apps.apple.com/gb/app/princh/id999408628" target="_blank">Apple App Store</a>. Then you can print files from your phone by viewing the files at your 
        smart device, use the “share to” tool and select to share with Princh. The app will give more specific instructions.</p>
      </div>
      <div id="helsinki" class="content-section">
          <h2>Printing from your own device in Helsinki City Library</h2>
          <p>Create a user account at <a href="https://asiakastulostus.hel.fi" target="_blank">asiakastulostus.hel.fi</a>.</p>
          <p>Activate your account by clicking Activate your account link in the email you received. Save the personal PIN code given in the email and the password for 
          your account. The same PIN code is used for printing in all branches of Helsinki City Library. The printouts cost €0.40 per sheet. After printing, pay for the 
          printouts at the library customer service. <p>On your own device</p>
          <ul class="list-bullets">
              <li>Log in to the printing service at <a href="https://asiakastulostus.hel.fi" target="_blank">asiakastulostus.hel.fi</a>. You can change the interface language from the Dropdown menu.</li>
              <li>Open the Dropdown menu and click Upload job.</li>
              <li>Click Tap here to add print job and find the files you want to print from your device. You can select multiple files at once, if your device supports this option.</li>
              <li>Click Upload to send the files to the printing queue. You can select more files by clicking Add file. Enter your PIN code on the library printer to release your printouts.</li>
          </ul>
      </div>
      <div id="vantaa" class="content-section">
        <h2>Printing and photocopying at Vantaa libraries</h2>
        <p>You need a library card for printing, photocopying, and scanning documents. You can easily register for the printing system with your library card. 
        You only need to register once, and your identifiers will be valid until further notice. The employees help you when required.</p>
        <p>You can photocopy up to 20 black-and-white or two color sheets per day. Printing and copying are free of charge.</p>
        <p>You can only print from library computers. It is not possible to print using your own device.</p>
        <p>You can also scan paper documents into digital form. The scanned files will be directly sent to the email address you specified in connection with registering. It 
        is not possible to scan to a USB flash drive.</p>
      </div>
      <div id="user-regulations" class="content-section">
        <h2>User regulations for customer computers</h2>
        <p>Welcome to use customer computers at Helmet Library!</p>
        <ol class="list-numbers">
            <li> Use of customer computers is free of charge. Fees for printouts are itemized in the library's table of prices.</li>
            <li>Use your own IDs only. They are personal, and you are responsible for their use.</li>
            <li>Library employees are happy to help you. Keep in mind, however, that you are responsible for your net transactions.</li>
            <li>Respect other network users and other library customers.</li>
            <li>Respect the citizens' joint property.</li>
            <li>The library is not responsible for any damages caused by computer use.</li>
            <li>In case of criminal investigation, authorities are entitled to user data.</li>
            <li>The library is not responsible for damages caused by technical malfunctions, other network users, or users' actions.</li>
            <li>The library specifies the terms for reservation.</li>
            <li>As a user of the library's customer computers, data networks and systems, you are obliged to adhere to these rules. If you fail to comply with the rules, the library can 
            temporarily bar you from using the computers. The procedure applied is User Regulations for the HelMet Library, Loss of user rights.</li>
          </ol>
      </div>
   </div>
</div>

