<? $this->headTitle($this->translate('Work and have fun')); $this->content()->setHeading($this->translate('Work and have fun'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="customer-computers" class="content-section">
        <h2>Customer computers and printing</h2>
        <p>You can reserve a customer computer online. The reservation system also monitors logging in to the computer. Logging in requires a PIN code that will be checked in the 
        library system.</p>
        <p>The staff provides guidance in using computers, as needed. The library also organises beginners' computer and internet courses. Ask your library for more information.</p>
        <p><a href="https://varaus.lib.hel.fi/default.aspx?cid=en-GB" target="_blank" aria-label="Book a computer in Helsinki. The link opens in a new window.">
        Book a computer in Helsinki</a></p>
        <p>In Espoo and in Vantaa computers are available without reservation.</p>
        <p>Your user ID is your library card number and the password your PIN code.</p>
        <h3>Printing</h2>
        <ul class="list-bullets">
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb#user-regulations">User regulations for customer computers</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb#espoo">Printing and photocopying at Espoo libraries</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb#helsinki">Printing and photocopying at Helsinki libraries</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb#vantaa">Printing and photocopying at Vantaa libraries</a></li>
        </ul>
     </div>
     <div id="for-musicians" class="content-section">
        <h2>Musician's toolkit</h2>   
        <p>Do you feel like singing? Do you want to be a musician? HelMet libraries offer a wide range of services for music enthusiasts and 
        professionals. You can practise undisturbed in the playing rooms and record your work to be enjoyed by others in the music studios. 
        Your own copyright-free recordings may also be included in the collections of the library. Once your playing starts to flow after 
        practice, pick up the microphone and bring your band to the library stage.</p>
        <h3>Instruments:</h3>
        <ul class="list-bullets">
            <li>Banjo: Itäkeskus</li>
            <li>Bass guitar (electric): Entresse, Iso Omena, Maunula, Oodi, Sello, Tapiola</li>
            <li>Bass guitar (acoustic): Sello</li>
            <li>Bongos: Itäkeskus</li>
            <li>Cajón: Itäkeskus, Kallio, Oulunkylä</li>
            <li>Drums (acoustic): Entresse, Maunula, Oodi</li>
            <li>Drums (electric): Iso Omena, Sello, Tapiola, Töölö</li>
            <li>Glockenspiel: Itäkeskus</li>
            <li>Guitalele: Itäkeskus</li>
            <li>Guitar (electric): Entresse, Iso Omena, Itäkeskus, Maunula, Oodi, Sello, Tapiola, Tikkurila</li>
            <li>Guitar (acoustic, with steel strings): Iso Omena (lendable, link to Helmet search), Itäkeskus, Oodi, Pasila, Sello (electro-acoustic), Tapiola</li>
            <li>Guitar (with nylon strings): Itäkeskus</li>
            <li>Guitar (semi-acoustic): Pasila</li>
            <li>Kantele: Itäkeskus, Kallio, Oodi, Töölö</li>
            <li>Keyboard (synthesizer / MIDI): Entresse, Itäkeskus, Maunula, Oodi, Sello, Tapiola</li>
            <li>Mandolin: Itäkeskus</li>
            <li>Percussion: Oodi, Tapiola</li>
            <li>Piano (acoustic): Oodi, Sello, Tikkurila</li>
            <li>Piano (digital): Entresse, Etelä-Haaga, Itäkeskus, Iso Omena, Kivenlahti, Laajasalo, Myllypuro, Oodi, Pasila, Oulunkylä, Sello, Tapiola, Töölö</li>
            <li>Pump organ: Sello</li>
            <li>Rhythm instruments in a bag: Itäkeskus</li>
            <li>Ukulele, lendable: Entresse, Itäkeskus, Kallio, Oulunkylä, Pasila, Sello, Töölö, Arabianranta, Tikkurila</li>
        </ul>
        <h3>Music rooms:</h3>
        <ul class="list-bullets">
            <li>Etelä-Haaga</li>
            <li>Iso Omena</li>
            <li>Maunula</li>
            <li>Oodi</li>
            <li>Pasila</li>
            <li>Sello</li>
            <li>Tikkurila</li>
            <li>Töölö</li>
        </ul>
        <h3>Recording studios:</h3>
        <ul class="list-bullets">
            <li>Entresse</li>
            <li>Iso Omena</li>
            <li>Oodi</li>
            <li>Pasila</li>
            <li>Sello</li>
            <li>Tapiola</li>
            <li>Tikkurila</li>
        </ul>
     </div>
     <div id="for-event-organisers" class="content-section">
        <h2>Event and exhibition organiser's toolkit</h2>
        <p>Do you need space for your art or to organise an event? You can bring your own team to perform in the library, easily reaching a wide 
        audience. Library staff will guide you with the arrangements. Depending on the nature and organiser of the event, the use of the premises 
        may incur a fee. Contact the library where you want to organise your event.</p>
        <p>The library is also your canvas to showcase your work or your collection. Several libraries offer the possibility to organise smaller 
        art and other exhibitions. Depending on the nature and organiser of the event, the use of the exhibition premises may incur a fee. 
        Contact the library where you want to stage your exhibition.</p>
      </div>
      <div id="for-students" class="content-section">
        <h2>Student's and researcher's toolkit</h2>
        <p>An exam coming up and nowhere to study in peace? In the library, there is study and work space for various uses. In a quiet reading 
        room your studies progress on schedule. All libraries give you access to updated customer workstations with an internet connection and a 
        WiFi network. The most important reference works, dictionaries and databases are within your reach and the information service staff are 
        always ready to help. The reference library can be helpful when all exam books are reserved.</p>
        <p><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=en-gb#user-regulations">Customer computers</a></p>
      </div>
      <div id="space-for-work" class="content-section">
        <h2>Space for work</h2>
        <p>A free moment between business meetings and nowhere to put down the laptop? The library has peaceful areas for working alone or in group.</p>
        <p>Through Varaamo and Timmi, you can reserve library premises and equipment for your own use</p>
        <ul class="list-bullets">
            <li><a href="https://varaamo.espoo.fi/" target="_blank" aria-label="Varaamo Espoo. The link opens in a new window.">Varaamo Espoo</a></li>
            <li><a href="https://varaamo.hel.fi/" target="_blank" aria-label="Varaamo Helsinki. The link opens in a new window.">Varaamo Helsinki</a></li>
            <li><a href="https://asp3.timmi.fi/WebTimmi/index_v2.html#/826"target="_blank" aria-label="Timmi 360 Vantaa. The link opens in a new window.">Timmi 360 Vantaa</a></li>
        </ul>
      </div>
   </div>
</div>