<? $this->headTitle($this->translate('Työskentele ja viihdy')); $this->content()->setHeading($this->translate('Työskentele ja viihdy'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="asiakastietokoneet-ja-tulostaminen" class="content-section">
        <h2>Asiakastietokoneet ja tulostaminen</h2>
        <p>Voit varata asiakastietokoneen itse internetin kautta. Ajanvarausjärjestelmä myös valvoo koneelle kirjautumista. Kirjautuminen 
        edellyttää tunnusluvun käyttöä, joka tarkistetaan kirjastojärjestelmästä.</p>
        <p>Henkilökunta opastaa tarvittaessa tietokoneiden käytössä. Kirjastossa järjestetään myös tietokoneen ja internetin käytön peruskursseja.
        Kysy lisätietoa omasta kirjastostasi.</p>
        <p>Espoossa ja Vantaalla koneille mennään ilman ajanvarausta.</p>
        <p>Käyttäjätunnus on kirjastokorttisi numero ja salasana PIN-koodisi.</p>
        <ul class="list-bullets">
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet#käyttösäännöt">Asiakastietokoneiden käyttösäännöt</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet#espoo">Tulostaminen Espoossa</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet#helsinki">Tulostaminen Helsingissä</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet#vantaa">Tulostaminen Vantaalla</a></li>
        </ul>
        <p>Viimeksi päivitetty 30.3.2023</p>
      </div>
     <div id="muusikon-tyokalupakki" class="content-section">
        <h2>Muusikon työkalupakki</h2>
        <p>Laulattaako? Haluatko muusikoksi? Helmet-kirjasto tarjoaa laajan valikoiman palveluja musiikin harrastajille ja ammattilaisille. 
        Soittotiloissa voit harjoitella rauhassa ja studioissa voit äänittää tuotoksesi 
        muidenkin nautittavaksi. Kun soitto ahkeran harjoittelun jälkeen kulkee mallikkaasti, tartu mikkiin ja tuo bändisi kirjaston lavalle.</p>
        
        <h3>Soittimia:</h3>
        <ul class="list-bullets">
            <li>Banjo: Itäkeskus</li>
            <li>Bassokitara (sähkö-): Entresse, Iso Omena, Maunula, Oodi, Sello, Tapiola</li>
            <li>Bassokitara (akustinen): Sello (nuortenosastolla soitettavissa, ei lainata)</li>
            <li>Bongorummut: Itäkeskus</li>
            <li>Cajon: Itäkeskus, Kallio, Oulunkylä</li>
            <li>Guitalele: Itäkeskus</li>
            <li>Kantele: Itäkeskus, Kallio, Oodi (myös lainattavissa kotiin), Töölö</li>
            <li>Kellopeli: Itäkeskus</li>
            <li>Kitara (sähkö-): Entresse, Iso Omena, Itäkeskus, Maunula, Oodi, Sello, Tapiola, Tikkurila</li>
            <li>Kitara (akustinen, teräskielinen): Iso Omena (lainattavissa), Itäkeskus, Oodi, Pasila, Sello (elektroakustinen), Tapiola</li>
            <li>Kitara (nailonkielinen): Itäkeskus</li>
            <li>Kitara (puoliakustinen, ei lainata): Pasila</li>
            <li>Kosketinsoitin (syntetisaattori / MIDI-): Entresse, Itäkeskus, Maunula, Oodi, Sello, Tapiola</li>
            <li>Lyömäsoittimia: Oodi, Tapiola</li>
            <li>Mandoliini: Itäkeskus</li>
            <li>Piano (akustinen): Oodi, Sello, Tikkurila</li>
            <li>Piano (digitaalinen): Entresse, Etelä-Haaga, Itäkeskus, Iso Omena, Kivenlahti, Laajasalo, Myllypuro, Oodi, Oulunkylä, Pasila, Sello, Tapiola, Töölö</li>
            <li>Rummut (akustiset): Entresse, Maunula, Oodi</li>
            <li>Rummut (sähkö-): Entresse, Iso Omena, Sello, Tapiola, Töölön kirjasto</li>
            <li>Rytmikassi: Itäkeskus</li>
            <li>Samaanirumpu: Itäkeskus</li>
            <li>Ukulele (lainattavissa): Entresse, Itäkeskus, Kallio, Oulunkylä, Pasila, Sello, Töölö, Arabianranta, Tikkurila</li>
            <li>Urkuharmoni: Sello</li>
        </ul>

        <h3>Soittohuoneita:</h3>
        <ul class="list-bullets">
            <li>Etelä-Haaga</li>
            <li>Iso Omena</li>
            <li>Maunula</li>
            <li>Oodi</li>
            <li>Pasila</li>
            <li>Sello</li>
            <li>Tikkurila</li>
            <li>Töölö</li>
        </ul>

        <h3>Musiikkistudioita</h3>
        <ul class="list-bullets">
            <li>Entresse</li>
            <li>Iso Omena</li>
            <li>Oodi</li>
            <li>Pasila</li>
            <li>Sello</li>
            <li>Tapiola</li>
            <li>Tikkurila</li>
        </ul>
      </div>
     <div id="opiskelijan-tyokalupakki" class="content-section">
        <h2>Opiskelijan ja tutkijan työkalupakki</h2>
        <p>Kirjastossa on opiskelu- ja työskentelytiloja monenlaiseen käyttöön. Rauhallisessa lukusalissa opinnot etenevät aikataulussa.</p>
        <p>Kaikissa kirjastoissa käytettävissäsi ovat ajanmukaiset asiakastyöasemat internet-yhteyksineen sekä langaton verkko.</p>
        <p>Tärkeimmät hakuteokset, sanakirjat ja tietokannat ovat kätesi ulottuvilla ja tietopalvelun ammattilaiset valmiina auttamaan. 
        Käsikirjastosta voi löytyä apu silloin, kun kaikki tenttikirjat ovat varattuja.</p>
        <p><a href="/Content/tulostaminen-ja-asiakastietokoneet">Asiakastietokoneet ja tulostaminen</a></p>
      </div>
      <div id="tapahtumajarjestajalle" class="content-section">
        <h2>Tapahtuma- ja näyttelyjärjestäjän työkalupakki</h2>
        <p>Tarvitsetko tilaa taiteellesi tai tapahtuman järjestämiseen?</p>
        <p>Kirjastoon voit tuoda oman porukkasi esiintymään, tavoitat helposti laajan yleisön. Kirjaston henkilökunta neuvoo järjestelyissä.
        Kirjastossa saat myös esille tekemäsi teokset tai keräilemäsi kokoelman. Useissa kirjastoissa on mahdollisuus järjestää pieniä taide- ja 
        muita näyttelyitä.</p>
        <p>Tapahtuman luonteesta ja järjestäjästä riippuen tilojen käyttö voi olla maksullista. Ota yhteyttä kirjastoon, jossa haluat järjestää 
        näyttelysi tai tapahtumasi.</p>
        
        <h3>Näyttelytilojen varaaminen</h3>
        <ul class="list-bullets">
            <li>Espoo ja Vantaa: Kysy lisätietoja siitä kirjastosta, johon haluaisit järjestää näyttelyn.</li>
            <li>Helsinki: <a href="/themes/custom/files/helsingin_kaupunginkirjaston_nayttelytilahakemus.doc" target="_blank">Helsingin kaupunginkirjaston 
            näyttelytilahakemus (.doc)</a></li>
        </ul>
      </div>
      <div id="tyotilat" class="content-section">
        <h2>Työtilat</h2>
        <p>Hetki aikaa työtapaamisten välissä eikä paikkaa mihin laskea läppäri? Kirjastosta löytyy rauhallista tilaa yksin tai ryhmässä 
        työskentelyyn.</p>
        <p>Varaamon ja Timmin kautta voit varata useiden kirjastojen tiloja ja laitteita omaan käyttöösi.</p>
        <ul class="list-bullets">
            <li><a href="https://varaamo.espoo.fi/" target="_blank" aria-label="Varaamo Espoo. Linkki aukeaa uudessa ikkunassa.">Varaamo Espoo</a></li>
            <li><a href="https://varaamo.hel.fi/" target="_blank" aria-label="Varaamo Helsinki. Linkki aukeaa uudessa ikkunassa.">Varaamo Helsinki</a></li>
            <li><a href="https://asp3.timmi.fi/WebTimmi/index_v2.html#/826" target="_blank" aria-label="Timmi 360 Vantaa. Linkki aukeaa uudessa ikkunassa.">Timmi 360 Vantaa</a></li>
        </ul>
      </div>
   </div>
</div>