<? $this->headTitle($this->translate('Jobba och trivs i biblioteket')); $this->content()->setHeading($this->translate('Jobba och trivs i biblioteket'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="kunddatorer" class="content-section">
        <h2>Kunddatorer och utskrift</h2>
        <p>Du kan själv boka en kunddator via internet. Bokningssystemet sköter också inloggningen på datorerna. Du måste ha en PIN-kod för att logga in.</p>
        <p>Personalen hjälper dig vid behov att använda datorerna. I biblioteken arrangeras också grundkurser i datorkunskap och internet. Fråga mera på ditt eget bibliotek.</p>
        <p>I Esbo och i Vanda kan du använda datorerna utan tidsbeställning.</p>
        <p>Ditt bibliotekskorts nummer fungerar som användarnamn och din PIN-kod som lösenord.</p>
        <ul class="list-bullets">
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv#regler">Regler för användning av kunddatorerna</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv#esbo">Utskrift i Esbobiblioteken</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv#helsinfors">Utskrift i Helsingfors bibliotek</a></li>
            <li><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv#vanda">Utskrift och kopiering i Vanda</a></li>
        </ul>
     <div id="för-musiker" class="content-section">
        <h2>Verktygslåda för musiker</h2>   
        <p>Har du lust att sjunga? Vill du bli musiker? HelMet-biblioteket har en hel del tjänster för den som har musik som hobby eller 
        yrke. I spelrummen kan du öva i lugn och ro och i bibliotekets studior kan du spela in dina alster så andra kan njuta av dem. Du kan också få synlighet om dina copyrightfria 
        inspelningar finns i bibliotekets samlingar. När du och ditt band har övat tillräckligt kan ni få spela på bibliotekets estrad.</p>
        <h3>Instrument:</h3>
        <ul class="list-bullets">
            <li>Banjo: Östra centrum</li>
            <li>Basgitarr (elektrisk): Entresse, Hagalund, Iso Omena bibliotek, Månsas, Ode, Sello</li>
            <li>Basgitarr (akustisk): Sello</li>
            <li>Bongo: Östra centrum</li>
            <li>Cajon: Berghäll, Åggelby, Östra centrum</li>
            <li>Gitarr (elektrisk): Dickursby, Entresse, Hagalund, Iso Omena bibliotek, Månsas, Ode, Sello, Östra centrum</li>
            <li>Gitarr (akustisk, stålsträngar): Böle, Hagalund, Iso Omena bibliotek (lånbar, direktlänk till Helmet-sök), Ode, Sello (elektroakustisk), Östra centrum</li>
            <li>Gitarr (nylonsträngar): Östra centrum</li>
            <li>Gitarr (halvakustisk): Böle</li>
            <li>Guitalele: Östra centrum</li>
            <li>Kantele: Berghäll, Ode (lånbar), Östra centrum</li>
            <li>Klockspel: Östra centrum</li>
            <li>Mandolin: Östra centrum</li>
            <li>Orgelharmonium: Sello</li>
            <li>Piano (akustisk): Dickursby, Ode, Sello</li>
            <li>Piano (digital): Böle, Degerö, Entresse, Iso Omena bibliotek, Kvarnbäcken, Ode, Sello, Stensvik, Södra Haga, Åggelby, Östra centrum</li>
            <li>Rytmpåse: Östra centrum</li>
            <li>Shamantrumma: Östra centrum</li>
            <li>Slaginstrument: Hagalund, Ode</li>
            <li>Tangentinstrument (syntetisator / MIDI-): Entresse, Hagalund, Månsas, Ode, Sello, Östra centrum</li>
            <li>Trummor (akustiska): Entresse, Månsas, Ode</li>
            <li>Trummor (elektriska): Hagalund, Iso Omena bibliotek, Sello</li>
            <li>Ukulele (lånbar): Arabiastrand, Berghäll, Böle, Entresse, Sello, Åggelby, Östra centrum</li>
        </ul>
        <h3>Musikrum:</h3>
        <ul class="list-bullets">
            <li>Böle</li>
            <li>Dickursby</li>
            <li>Iso Omena bibliotek</li>
            <li>Månsas</li>
            <li>Ode</li>
            <li>Sello</li>
            <li>Södra Haga</li>
        </ul>
        <h3>Musikstudior:</h3>
        <ul class="list-bullets">
            <li>Böle</li>
            <li>Dickursby</li>
            <li>Entresse</li>
            <li>Hagalund</li>
            <li>Ode</li>
            <li>Sello</li>
        </ul>
      </div>
      <div id="för-studerande" class="content-section">
        <h2>Verktygslåda för studerande eller forskare</h2>
        <p>I biblioteket finns rum för studier och arbete. I den tysta läsesalen går studierna framåt enligt tidtabellen.</p>
        <p>Alla bibliotek har moderna kunddatorer med internet samt ett trådlöst nätverk. Du kan bara sträcka ut handen efter de viktigaste uppslagsverken, ordböckerna och databaserna. 
        Professionell personal finns till för att hjälpa dig. Referensbiblioteket kan kanske hjälpa dig också.</p>
        <p><a href="/Content/tulostaminen-ja-asiakastietokoneet?lng=sv">Kunddatorer</a></p>
      </div>
      <div id="för-evenemang" class="content-section">
        <h2>Verktygslåda för evenemang eller utställningar</h2>
        <p>Behöver du en plats för din konst eller ditt evenemang? Kom till biblioteket för att uppträda tillsammans med dina kumpaner – ett bra sätt att få publik. Bibliotekets 
        personal kan ge råd när det gäller praktiska arrangemang. Kostnaderna varierar beroende på typ av evenemang och vem som arrangerar dem. Det är ofta avgiftsfritt. 
        Ta kontakt med det bibliotek där du vill arrangera ditt evenemang.</p>
        <p>Du kan också ställa ut din konst eller din samling på biblioteket. De flesta biblilotek har möjlighet att arrangera små konstutställningar eller liknande, Kostnaderna 
        varierar beroende på typ av evenemang och vem som arrangerar dem. Det är ofta avgiftsfritt. Ta kontakt med det bibliotek där du vill arrangera ditt evenemang.</p>
        <h3>Att reservera rum för en utställning</h3>
        <ul class="list-bullets">
            <li>Esbo och Vanda: Fråga i det bibliotek där du vill hålla din utställning.</li>
            <li>Helsingfors: Blankett för att anhålla om utställningsrum (endast på finska).
            <a href="/themes/custom/files/helsingin_kaupunginkirjaston_nayttelytilahakemus.doc" target="_blank">Helsingin kaupunginkirjaston näyttelytilahakemus (.doc)</a></li>
        </ul>
      </div>
      <div id="arbetsrum" class="content-section">
        <h2>Arbetsrum</h2>
        <p>En stund mellan två möten, men ingen plats att sätta ner laptopen? På biblioteket finns rum där du kan jobba ensam eller i grupp.</p>
        <p>Med Varaamo och Timmi kan du boka offentliga utrymmen och apparater för privat bruk.</p>
        <ul class="list-bullets">
            <li>Esbo: <a href="https://varaamo.espoo.fi/" target="_blank" aria-label="Varaamo Espoo. Länken öppnas i ett nytt fönster.">Varaamo Espoo</a></li>
            <li>Helsingfors: <a href="https://varaamo.hel.fi/" target="_blank" aria-label="Varaamo Helsinki. Länken öppnas i ett nytt fönster.">Varaamo Helsinki</a></li>
            <li>Vanda: <a href="https://asp3.timmi.fi/WebTimmi/index_v2.html#/826" target="_blank" aria-label="Timmi 360 Vantaa. Länken öppnas i ett nytt fönster.">Timmi 360 Vantaa</a></li>
        </ul>
      </div>
   </div>
</div>