<? $this->headTitle($this->translate('Usein kysyttyä')); $this->content()->setHeading($this->translate('Usein kysyttyä'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="Ongelmatilanteet" class="content-section">
        <h2>Ongelmatilanteet</h2>   
        <h3>Unohdin tunnuslukuni, mitä teen?</h3>
        <p>Jos olet antanut meille sähköpostiosoitteesi, voit käyttää tunnusluvun palautustoimintoa painamalla "Kirjaudu" oikeasta yläkulmasta ja sen jälkeen "Unoditko tunnuslukusi?</p>
        <p>Tunnusluku voidaan muuttaa kirjastossa. Ota henkilötodistus mukaan.</p>
        <h3>Kirjastokorttini katosi, mitä teen?</h3>
        <p>Ilmoita kadonneesta kortista heti kirjastoosi. Kirjastojen ollessa suljettuna voit soittaa numeroon 09 3108 5309. Kerro vastaajan nauhalle, miksi soitat, 
        nimesi ja henkilötunnuksesi.</p>
        <p>Et ole vastuussa lainoista, jotka on otettu kadonneelle kortille sen jälkeen kun ilmoitus katoamisesta on tehty. Kuoletettua korttia ei voi ottaa uudelleen käyttöön.
        Uusi kirjastokortti on maksullinen.</p>
        <p>Jos kadonneella tai varastetulla kortillasi on lainattu luvatta, varmista, että korttisi on kuoletettu. Tee tarvittaessa rikosilmoitus josta käy ilmi, että 
        korttia on käytetty luvatta, ja mitä vahinkoja on aiheutunut.</p>
        <p>Sääntöjemme mukaan olet vastuussa kaikesta kortillasi lainatusta aineistosta. Siksi joudut maksamaan niiden kulut ja korvaushinnan, vaikka joku 
        muu olisikin ne aiheuttanut.</p>
        <h3>Kirjaston kirja meni rikki tai CD-levy hukkaan. Mitä teen?</h3>
        <p>Jos mahdollista, ota yhteyttä sen kaupungin kirjastoon, joka omistaa rikkoutuneen tai hukkaan menneen aineiston. Voit kuitenkin hoitaa asian myös muissa kaupungeissa.</p>
        <p>Rikkoutunutta, sotkeentunutta tai kadonnutta aineistoa ei voi tietenkään enää laittaa lainattavaksi. 
        Siksi joudut korvaamaan sen hankintahinnan tai kiinteän korvaushinnan.</p>
        <p>Yleensä voit myös sopia kirjaston kanssa hankkivasi uuden kappaleen korvattavan tilalle. Elokuvat ovat kuitenkin poikkeus, koska kirjasto on ostanut 
        lainattaviin kappaleisiin lainausoikeudet.</p>
        <h3>Miksi sain ilmoituksen, vaikka olen jo palauttanut lainani tai hakenut varaukseni?</h3>
        <p>Jos olet tilannut kirjaston ilmoitukset kirjeinä etkä sähköpostina, voi käydä niin, että olet ehtinyt hakea varauksesi tai palauttaa lainasi ennen postin saapumista. 
        Kirjeposti lähtee 2. luokan kirjeinä.</p>
        <h3>Sain perintätoimistolta kirjeen palauttamattomista lainoista. Mitä teen?</h3>
        <p>Palauttamatta jääneet lainat siirtyvät perittäviksi noin 60 päivää eräpäivän jälkeen. Tässä vaiheessa olet myös menettänyt lainausoikeutesi.</p>
        <p>Lue kirjeen ohjeet huolellisesti. Maksettavaksesi jäävä summa on erisuuruinen riippuen siitä, voitko vielä palauttaa lainasi. Ota tällöin palautuksestasi kuitti.</p>
        <p>Maksa perintätoimiston saatavat. Lainausoikeutesi palautuu, kun kirjasto saa perintätoimistolta tiedon maksustasi.</p>
      </div>
     <div id="asiointi-kirjastossa" class="content-section">
        <h2>Asiointi kirjastossa</h2>
        <h3>Voinko rekisteröityä kirjaston asiakkaaksi sähköisesti?</h3>
        <p>Jos olet täyttänyt 15 vuotta, voit tallentaa tietojasi etukäteen kirjaston asiakasrekisteriin <a href="https://luettelo.helmet.fi/selfreg*fin~S9" target="_blank">
        lomakkeella</a>. Lomakkeen täyttäminen etukäteen nopeuttaa kirjastokortin saamista. Kun olet tallentanut tietosi, voit käydä hakemassa kirjastokortin mistä tahansa 
        Helmet-kirjastosta.</p>
        <p>Ota voimassaoleva henkilöllisyystodistus mukaan. Jos kirjastokorttia ei ole haettu kolmen kuukauden kuluessa lomakkeen täyttämisestä, tiedot poistetaan.</p>
        <h3>Missä voin käyttää Helmet-kirjastokorttia?</h3>
        <p>Voit käyttää Helmet-kirjastokorttia Espoossa, Helsingissä, Kauniaisissa ja Vantaalla kuin omassa lähikirjastossasi. Voit lainata, varata, uusia, palauttaa ja hoitaa 
        asioitasi missä kirjastossa tahansa kaupunkien rajoista välittämättä.</p>
        <h3>Voiko joku muu asioida puolestani?</h3>
        <p>Kyllä voi, katso ohjeet <a href="/fi-FI/content/1048/1" target="_top">joustoasiakkuuteen</a> tai <a href="/fi-FI/content/37/1" target="_top">valtakirjan käyttämiseen</a>.</p>
        <h3>Onko Helmet-kirjastolla chat-palvelua?</h3>
        <p>Kyllä on. Chat-ruutu on näkyvissä Helmet-sivustolla, kun kirjaston työntekijä on paikalla vastaamassa. Chat on avoinna arkisin noin kello 12–17 (perjantaisin 12–16).</p>
        <h3>Miten lopetan kirjaston asiakkuuden?</h3>
        <p>Jos et enää tarvitse omaa kirjastokorttiasi tai kyseessä on kuolleen omaisen kirjastokortti, voit pyytää, että asiakastiedot poistetaan kirjaston asiakasrekisteristä.</p>
        <p>Ota yhteyttä minkä tahansa Helmet-kirjaston asiakaspalveluun käymällä kirjastossa tai soittamalla. Kirjastossa tarkistetaan, ettei kortilla ole palauttamattomia lainoja, 
        maksamattomia maksuja tai muita selvittämättömiä asioita. Sen jälkeen asiakastiedot poistetaan. Hävitä kortti leikkaamalla se kahtia. Kirjastoon ei tarvitse toimittaa 
        kuolintodistusta.</p>
        <h3>Miksi kirjastokorttini ei enää toimi?</h3>
        <p>Rekisteristä poistetaan myös asiakastiedot, joita asiakas ei ole käyttänyt kolmeen vuoteen ja joihin ei liity selvittämättömiä asioita, esimerkiksi maksamattomia maksuja. 
        Poistot tehdään kerran vuodessa.</p>
        <h3>Voinko saada kirjaston ilmoitukset sähköpostiin tai tekstiviestinä?</h3>
        <p>Kyllä voit. Katso <a href="https://luettelo.helmet.fi/screens/e_help_fin.html#varausilmoitus" target="_top">ohje Helmet-haussa</a>.</p>
        <h3>Kasvavatko myöhästymismaksut korkoa?</h3>
        <p>Myöhästymismaksut eivät kasva korkoa.</p>
        <h3>Kasvavatko muut maksut korkoa?</h3>
        <p>Perintätoimistot perivät viivästyskorkoa niiden perittäviksi jätetyistä maksuista.</p>
        <h3>Voiko myöhästymismaksut maksaa netin kautta?</h3>
        <p>Kyllä voi. <a href="http://www.helmet.fi/maksukaista/" target="_blank">Maksusovellukseen pääsee tästä linkistä</a>.</p>
      </div>
      <div id="aineisto ja varaaminen" class="content-section">
        <h2>Aineisto ja varaaminen</h2>   
        <h3>Miten voin jättää hankintaehdotuksen?</h3>
        <p>Voit täyttää <a href="/Content/hankintaehdotus">hankintaehdotuksen</a> verkossa. Voit toki kertoa hankintatoiveesi myös kirjaston henkilökunnalle.</p>
        <h3>Miksi en löydä uutuusteosta Helmetistä?</h3>
        <p>Uutuusteosten hankintapäätökset tehdään yleensä jo kuukausia etukäteen. Teos löytyy Helmetistä, kun sen tiedot on tallennettu kirjaston tietokantaan. Voit halutessasi 
        varmistaa henkilökunnalta, onko teos jo tilattu kirjastoon. <a href="/Content/hankintaehdotus">Hankintatoiveita</a> voit esittää verkossa tai kirjastohenkilökunnalle.</p>
        <h3>En löydä Helmetistä erästä teosta. Voinko tilata sen jostain muusta kirjastosta itselleni?</h3>
        <p>Kyllä voit. Tee tilaus siinä kirjastossa, josta haluat teoksen noutaa. Voit täyttää <a href="/Content/kaukopalvelu">kaukopalvelupyynnön </a>myös verkossa.
        Kaukopalvelu on maksullista</a>.</p>
        <h3>Miten varaan hyllyssä olevan teoksen?</h3>
        <p>Voit tehdä varauksen Helmet-verkkopalvelussa. Saat ilmoituksen tekstiviestinä, sähköpostitse tai postitse, kun aineisto odottaa sinua noutokirjastossa. Jos haluat heti 
        noutaa teoksen kirjastosta, jossa se on hyllyssä, soita ensin kyseiseen kirjastoon ja pyydä, että teos varataan sinulle. Puhelinvarausta varten tarvitset kirjastokortin 
        numeron. Verkkopalvelussa tarvitset kirjastokortin numeron ja PIN-koodin.</p>
        <h3>En pääse hakemaan varaustani. Voiko joku muu hakea sen?</h3>
        <p>Jos et pääse itse noutamaan varaustasi, voit pyytää toista henkilöä lainaamaan varatun teoksen omalle kirjastokortilleen kirjaston asiakaspalvelussa. Lainaajan on 
        esitettävä kirjastosta tekstiviestinä, sähköpostitse tai postitse saamasi varausilmoitus, joten välitä varausilmoituksesi hänelle. Jos haluat, että varauksesi lainataan 
        sinun kirjastokortillesi, varauksen noutajalla on oltava mukanaan valtakirja, johon olet yksilöinyt sen käyttötarkoituksen, sinun kirjastokorttisi sekä varauksen noutajan
        oma henkilötodistus.<br><br>
        Jos et tarvitse enää varaamaasi aineistoa, peruuta varauksesi mahdollisimman pian. Näin se vapautuu seuraavalle asiakkaalle. Varauksen voit perua milloin tahansa ennen 
        noutoajan päättymistä. Varausjonossa olevan varauksen voit myös lukita esimerkiksi loman tai muun poissaolon ajaksi. Voit lukita varauksesi vain ennen kuin se on matkalla 
        tai saapunut varaushyllyyn.</p>
        <h3>Olen lähdössä lomamatkalle ja minulla on varauksia. En haluaisi, että varaukset tulevat matkani aikana kirjastoon. Voisiko asialle tehdä jotain?</h3>
        <p>Voit lukita varaukset kirjautumalla omiin tietoihisi Helmet-sivulla. Pystyt lukitsemaan sellaisen varauksen, jossa olet vielä jonossa. Lukitsemalla varmistat, että se ei 
        tule kirjastoon noudettavaksi ennen kuin olet poistanut lukituksen. Liikut varausjonossa eteenpäin vaikka varauksesi olisi lukittuna. Lukituksen saat pois samalla tavalla 
        kuin lukitsitkin varauksen. Lukituksen poistamisen jälkeen varaus saapuu noudettavaksi kirjastostasi, kun on sinun vuorosi varausjonossa.</p>
        <h3>En haluaisi, että koko nimeni näkyy varaushyllyssä. Kuinka voin estää sen?</h3>
        <p>Useimmissa kirjastoissa on siirrytty numeroituihin varauksiin tai varaushyllyihin.</p>
        <p>Joissakin kirjastoissa on käytössä varausten noutoon alias eli salanimi. Aliaksen voit saada käymällä kirjastossa ja esittämällä voimassa olevan henkilöllisyystodistuksen. 
        Aliaksen hankkimisen jälkeen varauksissa ei näy nimeäsi vaan aliaksesi.</p>
        <h3>Voinko ostaa itselleni kirjaston hyllyssä olevan teoksen?</h3>
        <p>Valitettavasti emme ota vastaan ostotarjouksia kokoelmaamme kuuluvista teoksista. Voit ostaa kirjastojen poistamia teoksia. Poistopäätöksiin vaikuttavat muun 
        muassa teoksen ikä, huono kunto, vanhentunut sisältö ja lainaamattomuus.</p>
        <h3>Voinko lahjoittaa kirjastolle omia kirjojani?</h3>
        <p>Kyllä, kirjastot ottavat vastaan kirjalahjoituksia tarpeen mukaan. Kirjastot voivat halutessaan ohjata lahjoituksia eteenpäin, esim. kierrätyskärryyn, 
        josta muut asiakkaat voivat poimia teoksia itselleen. Kysy asiasta tarkemmin omasta lähikirjastostasi. Huom! Keskustakirjasto Oodi ei ota vastaan aineistolahjoituksia.</p>
        <h3>Miten aineisto valitaan?</h3>
        <p>Helmet-kirjasto on Espoon, Helsingin, Kauniaisten ja Vantaan kirjastojen kokonaisuus.</p>
        <p>Kirjastossa on kirjoja, lehtiä, musiikkia, elokuvia, äänikirjoja ja pelejä sekä perinteisissä että digitaalisissa muodoissa. Osa lehdistä on lainattavissa ja varattavissa. 
        Käytössä on myös runsaasti digilehtiä.</p>
        <p>Aineistoa hankitaan kaiken ikäisille pääkaupunkiseudulla eniten puhutuilla kielillä. Kirjasto hankkii sellaisia elokuvia, joilla on lainausoikeus. Kirjasto maksaa 
        tekijänoikeuskorvaukset.</p>
        <p>Erityisen kallista tai sellaista aineistoa, jonka käytön arvioidaan olevan vähäistä, mutta hankinnan silti tarpeellista, valitaan vain muutamia kappaleita.</p>
        <p>Suurin osa suomalaisesta kirjallisuudesta hankitaan ilman eri toivetta.<a href="/Content/hankintaehdotus">Hankintaehdotuksen</a> voit täyttää verkossa tai kertoa 
        hankintatoiveesi kirjaston henkilökunnalle.</p>
        <p>Voit varata aineistoa tai uusia lainojasi verkkopalvelussamme. Varatun aineiston kuljetamme perille haluttuun kirjastoon koko Helmet-alueella. Kirjastot ottavat 
        lahjoituksia vastaan harkintansa mukaan.</p><p>
      </div>
     <div id="verkkomaksaminen" class="content-section">
        <h2>Verkkomaksaminen</h2>
        <h3>Mitä maksuja voi maksaa verkon kautta?</h3>
        <p>Voit maksaa verkossa lähes kaikki kirjastomaksut. Verkossa voi maksaa muun muassa myöhästymismaksut sekä muut yleisimmät maksut. Myös kadonneen ja vahingoittuneen 
        aineiston korvausmaksun voi maksaa verkossa. Ota kuitenkin ensin yhteyttä omaan kirjastoosi. Yli 60 päivää myöhässä olevien teosten korvausmaksuja verkossa ei voi maksaa.</p>
        <h3>Onko muita maksuja, joita ei voi maksaa verkossa?</h3>
        <p>Perinnässä olevia lainoja ei voi maksaa verkossa. Perintätoimisto hoitaa näiden lainojen perinnän, eikä kirjasto tämän vuoksi voi ottaa kyseisiä maksuja vastaan.</p>
        <h3>Onko maksettaville summille alarajaa?</h3>
        <p>Helmet.finna.fi:n käyttämässä järjestelmässä ei ole rajoituksia maksujen suuruudelle, mutta pankeilla tai korttiyhtiöillä saattaa olla omia rajoituksia. 
        Tarkista nämä omasta pankistasi tai maksukortin myöntäjältä.</p>
        <h3>Miten kirjastomaksut näkyvät tiliotteellani?</h3>
        <p>Tiliotteella ja luottokorttilaskulla maksun vastaanottajana näkyy Visma/Helmet-kirjasto.</p>
        <h3>Miksi sähköpostissani ei näy maksuvahvistusta?</h3>
        <p>Jotkut sähköpostiohjelmat saattavat tulkita maksuvahvistuksen roskapostiksi. Tarkista siis kaikki saapuvan postin kansiosi ja salli jatkossa viestien vastaanottaminen 
        kuitin lähettäjältä.</p>
        <h3>Miksi maksuja ei voi maksaa suoraan Helmet-haun omista tiedoista ja miksi maksaminen vaatii uuden kirjautumisen?</h3>
        <p>Kirjastomaksujen verkkomaksaminen tapahtuu verkkokauppasovelluksessa, joka ei ole osa Helmet-hakua. Verkkokauppaan kuitenkin kirjaudutaan samoilla tunnuksilla 
        kuin Helmet-hakuun ja tiedot maksettavista kirjastomaksuista haetaan Helmet-järjestelmästä.</p>
        <h3>Voinko maksaa Visa Electronilla?</h3>
        <p>Visa Electron käy maksamiseen, mikäli kortinmyöntäjä on sallinut verkkomaksamisen Electronilla. Käytännössä useat Electronit käyvät verkkomaksamisessa.</p>
        <h3>Voinko maksaa mobiililompakolla?</h3>
        <p>Kyllä voit.</p>
        <h3>Miten voin tehdä debit-maksun?</h3>
        <p>Mikäli käytössäsi on credit/debit-maksukortti, voit tehdä debit-maksun käyttämällä kortin debit-numeroa ja -CVV-koodia. Debit-numero sijaitsee yleensä kortin 
        taustapuolella alalaidassa. Debit-numeroa käytettäessä tulee käyttää vieressä olevaa 3-4 numeroa pitkää debit-CVV-koodia. Huomaathan, että kaikki debit-kortit eivät 
        salli verkkomaksamista.</p>
        <h3>Mikä on CVV-koodi?</h3>
        <p>CVV-koodi on 3-4 merkkiä pitkä numerosarja, jonka löydät kortin taustapuolelta allekirjoituskentän vierestä.</p>
        <h3>Olen maksanut maksut verkon kautta, mutta maksu näkyy edelleen omissa tiedoissa Helmet-haussa.</h3>
        <p>Tietojen päivittymisessä voi olla viivettä. Jos ongelma pitkittyy, ota yhteyttä kirjastoon.</p>
        <h3>Miten toimin vikatilanteissa ja miten voin antaa palautetta verkkomaksamisesta?</h3>
        <p>Vikailmoitukset ja palautteen voit lähettää <a href="/fi-FI/content/92767/1" target="_top">palautelomakkeella</a>. 
        Voit myös olla yhteydessä suoraan kirjastoosi: <a href="/fi-FI/Kirjastot_ja_palvelut" target="_top">Kirjastot</a>.</p>
      </div>
      <div id="taskukirjasto" class="content-section">
        <h2>Taskukirjasto</h2>   
        <h3>Mikä on Taskukirjasto?</h3>
        <p>Taskukirjasto on mobiilisovellus Helmet-kirjastojen asiakkaille. Taskukirjastossa uusit lainasi, haet aineistoa ja teet varaukset muutamalla hipaisulla. 
        Saat myös lukusuosituksia ja voit tarkistaa kirjastojen aukioloajat ja yhteystiedot. Taskukirjastoa voit käyttää suomeksi, ruotsiksi, englanniksi ja venäjäksi.</p>
        <h3>Kuinka varaan kirjan Taskukirjastossa?</h3>
        <p>Kirjaudu sovellukseen kirjastokorttisi numerolla ja tunnusluvulla.</p>
        <p>Kirjoita hakuriville kirjan nimi, tekijän nimi, ISBN-koodi tai suuntaa haun kamera kirjan EAN-koodiin. Paina suurennuslasin kuvaa.</p>
        <p>Valitse listasta haluamasi kirja ja paina sen alla olevaa varauskuvaketta (kuva, jossa kirja putoaa kädelle).</p>
        <p>Valitse noutokirjasto painamalla hakuriviä ja valitse avautuvasta valikosta kirjaston nimi. Vahvista varaus painamalla lähetä-painiketta. Saat viestin varauksen 
        onnistumisesta.</p>
        <p>Jollei varaus onnistu, voit kirjautua omiin tietoihisi Helmet.finna.fi:ssä ja tarkistaa onko sinulla lainoja myöhässä tai ovatko kirjastomaksusi ylittäneet 30 euroa. 
        Voit myös soittaa lähikirjastosi asiakaspalveluun.</p>
        <h3>Kuinka muutan varauksen noutopaikan, lisään oletusnoutopaikan tai lukitsen varauksen?</h3>
        <p>HUOM! Varauksen lukitus -toiminto ei ole tällä hetkellä käytössä Taskukirjastossa vaan ainoastaan Helmet-verkkopalvelussa.</p>
        <p>Taskukirjastossa voi perua, lukita ja vapauttaa varauksen. Peruaksesi varauksen Taskukirjastossa paina roskakorin kuvaa. Lukitaksesi varauksen Taskukirjastossa 
        napsauta Lukitse-painiketta. Jos varaus on lukittu, samalta kohdalta löytyy Vapauta-painike.</p>
        <p>Varauksen noutopaikan voi muuttaa vain kirjautumalla Helmet.fi:ssä omiin tietoihin. 
        <a href="http://luettelo.helmet.fi/screens/e_help_fin.html#varaustenmuuttaminen">Varausten muuttaminen, lukitseminen ja peruuttaminen Helmet.fi:ssä</a>.</p>
        <h3>Miksei automaatti lue kirjastokortin viivakoodia Taskukirjastosta?</h3>
        <p>Kirjastokortin viivakoodia Taskukirjastossa on suurennettu ja tarkennettu. Jollei lähikirjastosi lainausautomaatti lue kortin viivakoodia puhelimen näytöltä, 
        koeta ensin nostaa puhelimesi näytön kirkkautta. Jollei vieläkään toimi, voit pyytää henkilökuntaa lukemaan viivakoodin palvelupisteen lukijalla.</p>
        <h3>Kuinka lainaan e-kirjan?</h3>
        <p>E-kirjoja voi lukea joko selaimessa tai kustantajien omilla sovelluksilla. <a href="/fi-FI/Ekirjasto/Ohjeet" target="_top">Katso ohjeet Helmet.fi:n e-kirjastosta</a>.</p>
        <h3>Miten otan lainaushistorian käyttöön?</h3>
        <p>Kirjaudu Helmet.fi:ssä omiin tietoihin.</p>
        <p>Valitse</p>
        <ul class="list-bullets">
          <li>Omat tietoni </li>
          <li>Lainaushistoria </li>
          <li>Aloita lainaushistorian seuraaminen</li>
        </ul>
        <p>Tämän jälkeen päivitä Taskukirjasto-sovellus uuteen versioon ja kirjaudu sisään. Lainaushistoria näkyy valikossa.</p>
        <p>Lainaushistoriaasi kertyvät vain ne lainat, jotka olet tehnyt aloitettuasi lainaushistoriasi tallentamisen. Muut lainaajat ja kirjaston henkilökunta eivät voi 
        tarkastella lainaushistoriaasi eivätkä muuttaa sitä. Taskukirjastossa voit tyhjentää koko lainaushistorian, mutta Helmet.fi:ssä voit poistaa lainaushistoriasta myös 
        yksittäisiä teoksia. Lainaushistorian voi tulostaa tai lähettää sähköpostiin vain Helmet.fi:ssä.</p>
        <h3>Miten kaverilaina tehdään?</h3>
        <p>Kirjautukaa Taskukirjastoon ja menkää osioon Kaverilaina.</p>
        <p>Avautuvaan kenttään lainaaja skannaa tai kirjoittaa kaverilla lainassa olevan kirjan kirjastoviivakoodin (ei kustantajan koodia) ja painaa enter.</p>
        <p>Sovellus ottaa yhteyttä lainan antajaan (voi kestää hetken) ja pyytää hyväksyntää lainalle. Jos aikaraja ylittyy, kirjoita viivakoodi uudelleen.</p>
        <p>Hyväksynnän jälkeen sovellus päivittää lainan kaverin kortille ja lainaan tulee uusi eräpäivä. Luetun kirjan voi palauttaa normaalisti kirjaston palautusautomaattiin.</p>
        <p>Kaverilaina ei onnistu, jos</p>
        <ul class="list-bullets">
          <li>teoksesta on varauksia,</li>
          <li>teosta ei voi varata (esim. Bestsellerit),</li>
          <li>teoksen uusimiskerrat ovat täynnä tai</li>
          <li>uusi lainaaja ei sovi teoksen ikärajaan.</li>
        </ul>
        <h3>Onko kaverilainoissa ikärajat?</h3>
        <p>Joissakin kuvaohjelmissa (elokuvat, tv-ohjelmat ja digitaaliset pelit) on <a href="https://kavi.fi/ikarajat/" target="_blank" 
        aria-label="KAVI. Linkki aukeaa uudessa ikkunassa.">KAVI </a>ja <a href="https://pegi.info/fi" target="_blank" 
        aria-label="PEGI. Linkki aukeaa uudessa ikkunassa.">PEGI </a>-ikärajoja, joita Helmet-kirjasto noudattaa. Voit lainata ikärajallisia teoksia edelleen vain kaverille, 
        jolle niiden lainaaminen on ikärajan mukaan sallittu.</p>
        <h3>Kuinka teen yhteystietojeni muutoksen?</h3>
        <p>Omien tietojen muutokset voi toistaiseksi tehdä vain kirjautumalla Helmet.fi:hin. Kirjaudu omiin tietoihin, klikkaa omaa nimeäsi ja valitse Muuta yhteystietoja.</p>
        <p>Huom! Nimenmuutosta ei voi tehdä verkkopalvelun kautta. Käy missä tahansa Helmet-kirjastossa ja esitä uudella nimelläsi varustettu henkilötodistus 
        (tai henkilötodistus vanhalla nimelläsi ja erillinen todistus nimenmuutoksesta). Saat uuden kirjastokortin maksutta.</p>
      </div>
     <div id="noutamattomat-varaukset" class="content-section">
        <h2>Noutamattomien varausten maksu</h2>
        <h3>Miksi noutamattomille varauksille tulee maksu?</h3>
        <p>Varauksia käsitellään Helmet-kaupungeissa eli Helsingissä, Espoossa, Vantaalla ja Kauniaisissa yli 2,8 miljoonaa kappaletta vuosittain. Varausmäärän kasvaessa myös 
        kirjastoista noutamatta jäävien varausten määrä kasvaa. Helmet-kaupungeissa keskimäärin 14 prosenttia varauksista eli vuodessa yhteensä noin 400 000 kappaletta 
        jää noutamatta.</p>
        <h3>Minkä suuruinen maksu on?</h3>
        <p>1 euro / noutamaton varaus (esimerkiksi kirja tai levy).</p>
        <h3>Mitä haittaa siitä on, että varauksia jää noutamatta?</h3>
        <p>Varausjonot liikkuvat hitaasti, kun aineisto odottaa useita päiviä hyllyssä. Kirjoja ja muita varauksia joudutaan myös turhaan kuljettamaan kirjastosta toiseen.</p>
        <h3>Mitä hyötyä maksusta on?</h3>
        <p>Maksun tavoitteena on kannustaa asiakkaita huolehtimaan varaustensa noudosta tai peruuttamisesta, niin että kirjojen kierto nopeutuu ja varausjonot lyhenevät.</p>
        <h3>En ole saanut varauksistani ajoissa ilmoitusta tekstiviestillä tai sähköpostilla tai kirjeellä. Pitääkö minun silti maksaa varauksista maksu?</h3>
        <p>Maksu peritään myös siinä tapauksessa, että varausilmoitus ei ole saapunut perille jakeluhäiriön, tietoliikenteen häiriön tai muun syyn vuoksi. Voit seurata varausten 
        tilaa myös Helmet-haun Omissa tiedoissa ja Taskukirjastossa. Voit myös tiedustella varaustesi tilanteesta kirjaston henkilökunnalta kirjastossa tai puhelimitse.</p>
        <h3>Miten tilaan saapuneesta varauksesta tekstiviesti-ilmoituksen?</h3>
        <p>Jos olet tallentanut asiakastietoihisi matkapuhelinnumeron Suomen maakoodilla (esim. +358501234567), sinulle lähetetään varausilmoitus tekstiviestinä.</p>
        <h3>Voisiko varauksen lukitsemistoimintoa muuttaa niin, että voisin lukita myös sellaisen teoksen, joka on hyllyssä vapaana?</h3>
        <p>Tällaista muutosta ei ole näköpiirissä. Varauksen voi lukita vain sen ollessa varausjonossa. Vapaiden teosten lukitseminen vaikeuttaisi varaustilanteen ja siten
        myös uusien hankintojen tarpeen arviointia kirjastossa. Jos haluat merkitä kiinnostavan teoksen itsellesi muistiin, voit käyttää muistilistat-toimintoa ja varata teoksen
        myöhemmin sinulle sopivaan aikaan.</p>
        <h3>Kirjastoauto ei tullut pysäkille. Joudunko maksamaan maksun? / Sain eilen ilmoituksen varauksesta kirjastoautoon, enkä pääse tänään pysäkille. Varauksen viimeinen
        noutopäivä on ennen seuraavaa kirjastoauton käyntiä. Joudunko maksamaan maksun?</h3>
        <p>Et. Kirjastoautoissa, potilaskirjastoissa ja palvelukeskusten kirjastoissa ei peritä noutamattoman varauksen maksua. Varaukset säilytetään autossa kahden käyntikerran 
        ajan järjestelmän automaattisesti antamasta noutoajasta riippumatta. Jos kirjastoauto ei saavu pysäkille, varauksia ei poisteta noutamattomina, vaan ne ovat mukana
        seuraavalla viikolla.</p>
        <h3>Varaukseni oli kadonnut varaushyllystä. Pitääkö minun maksaa?</h3>
        <p>Ota yhteyttä henkilökuntaan. Henkilökunta voi perua varaushyllyssä olevan varauksen niin, ettei maksua muodostu, ja palauttaa varauksesi jonon kärkeen.</p>
        <h3>Meneekö noutamattomasta lasten aineistosta maksu, jos se on varattu aikuisten kortille?</h3>
        <p>Menee. Maksu peritään 18 vuotta täyttäneiltä.</p>
        <h3>Koskeeko maksu lapsen kirjastokortilla varattuja aineistoja?</h3>
        <p>Ei koske. Maksua ei peritä alle 18-vuotiailta, kotipalvelun asiakkailta, joustoasiakkailta tai yhteisöasiakkailta kuten koulut ja päiväkodit.</p>
        <h3>Olen ollut sairaana enkä ole päässyt hoitamaan asioitani. Voinko saada vapautuksen maksuista?</h3>
        <p>Kirjastomaksuista voi hakea vapautusta. Ota yhteyttä kirjastoon asian selvittämiseksi.</p>
        <h3>En pääse hakemaan varaustani. Voiko joku muu hakea sen?</h3>
        <p>Jos et pääse itse noutamaan varaustasi, voit pyytää toista henkilöä lainaamaan varatun teoksen omalle kirjastokortilleen kirjaston asiakaspalvelussa. Lainaajan on
        esitettävä kirjastosta tekstiviestinä, sähköpostitse tai postitse saamasi varausilmoitus, joten välitä varausilmoituksesi hänelle.</p>
        <p>Jos haluat, että varauksesi lainataan sinun kirjastokortillesi, varauksen noutajalla on oltava mukanaan valtakirja, johon olet yksilöinyt sen käyttötarkoituksen, 
        sinun kirjastokorttisi sekä varauksen noutajan oma henkilötodistus.</p>
        <p>Varausten noutopisteet ovat eri kaupungeissa erilaiset. Vantaalla joissakin kirjastoissa käytössä on älyhylly, josta noutamiseen tarvitaan varaajan kirjastokortin 
        numero ja PIN-koodi.<br><br>
        Jos et tarvitse enää varaamaasi aineistoa, peruuta varauksesi mahdollisimman pian. Näin se vapautuu seuraavalle asiakkaalle. Varauksen voit perua milloin tahansa 
        ennen noutoajan päättymistä.</p>
        <p>Varausjonossa olevan varauksen voit myös lukita esimerkiksi loman tai muun poissaolon ajaksi. Voit lukita varauksesi vain ennen kuin se on matkalla tai saapunut 
        varaushyllyyn.</p>
        <h3>Voisiko varausten yleistä noutoaikaa pidentää / lyhentää?</h3>
        <p>Noutoaika on sama kaikissa Helmet-kirjastoissa. Toiveita sekä noutoajan lyhentämiseksi että pidentämiseksi tulee silloin tällöin, mutta lyhyempi aika on käytännössä 
        todettu liian lyhyeksi ja pidempi noutoaika taas pidentää varausjonoja. Noutoajan pituuden päättävät Helmet-kirjastojen johtajat yhteisesti käyttösääntöjen muutosten 
        yhteydessä pidemmäksi aikaa kerrallan.</p>
        <h3>Eikö kirjaston pitäisi olla maksuton palvelu? Perustuuko tämä maksu lakiin?</h3>
        <p>Suomen yleisistä kirjastoista annetun lain (1492/2016) mukaisesti kirjastojen peruspalvelut ovat asiakkaalle maksuttomia. Lain 12 §:n mukaan kunta voi periä maksun 
        muun muassa myöhässä palautetusta aineistosta ja varatun aineiston noutamatta jättämisestä.</p>
        <h3>Missä muissa kirjastoissa kuin Helmet-kirjastoissa noutamattomista varauksista täytyy maksaa?</h3>
        <p>Esimerkiksi Joensuussa, Oulussa ja Pirkanmaan PIKI-kirjastoissa (1 euro) sekä Jyväskylässä, Kuopiossa, Rovaniemellä ja Varsinais-Suomen VASKI-kirjastoissa (2 euroa).</p>
      </div>
   </div>
</div>