<? $this->headTitle($this->translate('FAQ')); $this->content()->setHeading($this->translate('FAQ'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="problemsituationer" class="content-section">
        <h2>Problemsituationer</h2>   
        <h3>Jag har glömt min PIN-kod, vad ska jag göra?</h3>
        <p>Om vi har din e-postadress kan du använda funktionen:</p>
        <p>  <a href="https://luettelo.helmet.fi/pinreset~S9*swe" target="_blank">Byt ut PIN-koden</a></p>
        <p>Om vi inte har din e-postadress kan vi ge dig en ny kod i biblioteket. Ta med identitetsbevis.</p>
        <h3>Mitt bibliotekskort har försvunnit, vad ska jag göra?</h3>
        <p>Anmäl omedelbart om ditt bibliotekskort har försvunnit, så det blir spärrat. Då biblioteken är stängda kan du ringa telefonsvararen på numret 09 - 310 85309. 
        Berätta varför du ringer och ge ditt namn och personnummer.</p>
        <p>Du ansvarar inte för material som lånats på ditt kort efter att kortet spärrats. Ett kort som anmälts försvunnet och spärrats kan inte tas i bruk på nytt. 
        Det nya bibliotekskortet är avgiftsbelagt.</p><p>Om någon har lånat med ditt försvunna eller stulna kort ska du först kontrollera att kortet är spärrat. 
        Gör vid behov en brottsanmälan där det framgår att ditt kort har använts utan lov och vilka skador detta har förorsakat.</p>
        <p>Enligt våra regler är du ansvarig för alla lån på ditt kort om det inte är spärrat. Därför måste du betala alla avgifter också om någon annan har förorsakat skadan.</p>
        <p>Ta reda på om din hemförsäkring ersätter skadan.</p>
        <h3>En biblioteksbok har gått sönder eller en CD-skiva har försvunnit, vad ska jag göra?</h3>
        <p>Ta om möjligt kontakt med ett bibliotek i den stad som äger materialet som gått sönder eller försvunnit. Men vid behov kan du vända dig till vilket bibliotek som helst 
        inom Helmet.</p>
        <p>Trasigt, smutsigt eller försvunnet material kan naturligtvis inte lånas. Därför måste du ersätta materialet med dess inköpspris eller med ett fast ersättningspris.</p>
        <p>Det går ofta att ersätta materialet med ett nytt exemplar. Kom överens med personalen. Filmer kan ändå inte ersättas så, eftersom varje exemplar måste ha en egen 
        lånerättighet.</p>
        <h3>Varför får jag ett meddelande fastän jag redan har returnerat mina lån eller avhämtat mina beställningar?</h3>
        <p>Ifall du valt att få dina meddelande från biblioteket per vanlig post i stället för epost, kan det hända att du hinner returnera eller hämta dina reservationer 
        innan brevet anländer till dig hem. Vanliga brev skickas alltid med 2:a klassens post.</p>
        <h3>Jag fick ett brev från en inkassobyrå om lån jag inte lämnat tillbaka, vad ska jag göra?</h3>
        <p>Lån som inte returnerats övergår till en inkassobyrå då ca 60 dagar gått efter förfallodagen. I det skedet har du också förlorat din lånerätt.</p>
        <p>Läs instruktionerna i brevet noggrant. Om du kan returnera dina lån blir avgiften mindre. Om du returnerar lånen ska du spara kvittot.</p>
        <p>Betala de avgifter inkassobyrån kräver. Då biblioteket registrerat att du har betalat får du tillbaka din rätt att låna.</p>
      </div>
     <div id="arenden" class="content-section">
        <h2>Att sköta ärenden i biblioteket</h2>
        <h3>Kan jag registrera mig elektroniskt i biblioteket?</h3>
        <p>Du som fyllt 15 år kan spara dina personuppgifter i förväg genom att fylla i <a href="https://luettelo.helmet.fi/selfreg*swe~S9" target="_blank">
        blanketten i den här länken</a>. Om du använder blanketten går det snabbare att få ett bibliotekskort. När du har sparat dina uppgifter kan du hämta ditt kort i 
        vilket Helmet-bibliotek som helst. Ta med ett giltigt personbevis. Om du inte hämtat ditt bibliotekskort inom tre månader raderas uppgifterna.</p>
        <h3>Var kan jag använda Helmet-bibliotekskortet?</h3>
        <p>Du kan använda ditt Helmet-bibliotekskort i alla allmänna bibliotek i Esbo, Grankulla, Helsingfors och Vanda. Du kan låna, reservera, förnya eller returnera dina lån, 
        samt sköta ärenden i vilket bibliotek som helst, oberoende av gränser.</p>
        <h3>Kan någon annan sköta mina biblioteksärenden?</h3>
        <p>Ja, se anvisningar för att bli <a href="/Content/kun-et-paase-kirjastoon?lng=sv#flex">flexkund</a> eller för att använda en 
        <a href="/Content/kirjastokortti-ja-lainaaminen#fullmakt">fullmakt</a>.</p>
        <h3>Hur avslutar jag kundrelationen med biblioteket?</h3>
        <p>Om du inte längre behöver ditt bibliotekskort eller om det är fråga om ett kort för en avliden anhörig kan du be att kunduppgifterna raderas i bibliotekets 
        kundregister. Kontakta kundtjänsten på vilket Helmetbibliotek som helst genom att besöka eller ringa upp den. Biblioteket kontrollera att kortet inte har några 
        icke-återlämnade lån, obetalda avgifter eller andra outredda saker. Därefter raderas kunduppgifterna. Förstör kortet genom att klippa det itu på mitten. Man behöver 
        inte ge biblioteket någon dödsattest.</p>
        <p>Kunduppgifter som kunden inte har använt på tre år och som inte förknippas med outredda ärenden, t.ex. obetalda avgifter, raderas ur registret. Raderingarna görs 
        en gång om året.</p>
        <h3>Kan jag få meddelanden från biblioteket till min e-post eller per textmeddelande?</h3>
        <p>Ja. Se <a href="https://luettelo.helmet.fi/screens/e_help_swe.html#varausilmoitus" target="_blank">anvisningar här</a>.</p>
        <h3>Växer det ränta på förseningsavgifterna?</h3>
        <p>Nej, det gör det inte.</p>
        <h3>Växer det ränta på övriga avgifter?</h3>
        <p>Nej, det gör det inte.</p>
        <h3>Kan jag betala mina förseningsavgifter via webben?</h3>
        <p>Ja, <a href="http://www.helmet.fi/maksukaista/?lang=sv" target="_blank">man kan betala förseningsavgifterna här</a>.</p>
      </div>
      <div id="material" class="content-section">
        <h3>Material</h3>   
        <h3>Hur kan jag lämna in ett inköpsförslag?</h3>
        <p>Du kan fylla i <a href="/Content/hankintaehdotus?lng=sv">blanketten för inköpsförslag</a>. Naturligtvis kan du också ge ditt förslag direkt till bibliotekets personal.</p>
        <h3>Varför hittar jag inte nyheten jag söker i Helmet?</h3>
        <p>Biblioteket gör oftast sina inköpsbeslut flera månader innan nytt material utkommer. Ett verk finns i Helmet då dess uppgifter har registrerats i databasen. Om du vill 
        kan du fråga personalen om ett verk redan har beställts till biblioteket. Du kan ge <a href="/Content/hankintaehdotus?lng=sv">inköpsförslag</a> via webben eller till 
        bibliotekets personal.</p>
        <h3>Jag hittar inte ett bestämt verk i Helmet. Kan jag beställa det från något annat bibliotek?</h3>
        <p>Ja, om verket inte finns i något bibliotek i huvudstadsregionen. Gör beställningen i det bibliotek där du vill hämta verket. 
        <a href="/Content/kaukopalvelu">Läs ;om fjärrlåneavgifter här</a>.</p>
        <h3>Kan jag köpa en bok som står i bibliotekets hylla?</h3>
        <p>Nej, vi säljer inte verk som ingår i våra samlingar. Du kan köpa material som biblioteket har avskrivit. Biblioteket avgör vilka verk som ska avskrivas på basen av 
        verkets ålder och skick, om det har föråldrat innehåll eller om det inte har blivit utlånat.</p>
        <h3>Kan jag donera mina egna böcker till biblioteket?</h3>
        <p>Ja, biblioteken tar emot bokdonationer efter behov. Biblioteken har rätt att föra böckerna vidare, t.ex. till en återvinningshylla. Centrumbiblioteket Ode tar 
        inte emot donationer.</p>
        <h3>Hur väljs materialet?</h3>
        <p>Helmet-biblioteket är en helhet av biblioteken i Esbo, Grankulla, Helsingfors och Vanda.</p>
        <p>Biblioteket innehåller böcker, tidningar, musik, filmer, ljudböcker och spel i både traditionella och digitala format. En del av tidningarna kan lånas och reserveras. 
        Det finns också gott om digitidningar.</p>
        <p>Material skaffas på de mest talade språken i huvudstadsregionen för alla åldrar. Biblioteket skaffar filmer som har utlåningsrätt. Biblioteket betalar ersättningar 
        för upphovsrätten. Endast ett fåtal exemplar av särskilt dyrt material eller material som bedöms att ska användas i ringa omfattning men som ännu behöver skaffas väljs ut.</p>
        <p>Största delen av den finska litteraturen skaffas utan särskild önskan. Du kan fylla i ett <a href="/Content/hankintaehdotus?lng=sv">anskaffningsförslag</a> på 
        nätet eller informera bibliotekets personal om ditt anskaffningsönskemål.</p>
        <p>Du kan reservera material eller förnya dina lån på vår <a href="/">webbtjänst</a>. Det reserverade materialet levereras kostnadsfritt till önskat bibliotek i hela 
        Helmet-området. Bibliotek tar emot donationer efter övervägande.</p>
      </div>
     <div id="natbetalning" class="content-section">
        <h2>Nätbetalning</h2>
        <h3>Vilka avgifter kan jag betala via nätet?</h3>
        <p>Du kan betala nästan alla biblioteksavgiftervia nätet. Via nätet kan du betala bl.a. förseningsavgifter samt många av de vanligaste avgifterna. 
        Du kan också betala ersättning för material som försvunnit eller skadats. Ta först kontakt med ditt eget bibliotek. Ersättningsavgift kan inte betalas för material 
        som är mer än 60 dagar försenat.</p>
        <h3>Finns det andra avgifter som jag inte kan betalavia nätet?</h3>
        <p>Lån som överförts till indrivning kan inte betalasvia nätet. Inkassobyrån sköter indrivningen av dessa lån och biblioteket kan därför inte ta emot 
        betalning för dessa lån.</p>
        <h3>Finns det en nedre gräns för små betalningar?</h3>
        <p>Systemet Visma som används av Helmet.fi har ingen nedre gräns för hur små betalningar man kan göra, men bankerna eller kreditkortsbolagen kan ha sina egna 
        begränsningar. Kontrollera saken med din egen bank eller kortleverantör.</p>
        <h3>Hur syns bibiblioteksavgifterna i mitt kontoutdrag?</h3>
        <p>I kontoutdraget och på kreditkortsräkningen stårVisma/Helmet-biblioteksom mottagare.</p>
        <h3>Varför syns inte betalningsbekräftelsen i min e-post?</h3>
        <p>En del e-postprogram kan uppfatta din betalningsbekräftelse som skräppost. Kontrollera därför alla dina filer för inkommande post och tillåt i fortsättningen 
        mottagning av meddelanden från kvittots avsändare.</p>
        <h3>Varför kan avgifterna inte betalas direkt i de egna uppgifterna via Helmet-sök och varför kräver betalningen en ny inloggning?</h3>
        <p>Nätbetalningen av biblioteksavgifterna sker via en nätbutiksapplikation som inte är en del av HelMet-sök. För att logga in i nätbutiken används ändå samma 
        Pin-kod som i Helmet-sök och uppgifterna om biblioteksavgifterna som ska betalas hämtas ur Helmet-systemet.</p>
        <h3>Kan jag betala med Visa Electronic?</h3>
        <p>Visa Electonic går som betalningsmedel ifall instansen som beviljat kortet godkänner nätbetalning med Electronic. I praktiken passar de flesta 
        Electronkorten för nätbetalning.</p>
        <h3>Hur kan jag betala med debit?</h3>
        <p>Om du har ett credit/debit-betalningskort kan du betala via debit genom att använda kortets debitnummer och CVV-koden. Debitnummret finns vanligen i nedre 
        kanten på kortets baksida. Vid användning av debitnummer krävs den 3-4 siffror långa debit-CVV-koden invid. Kom ihåg att alla debitkort inte tillåter nätbetalning.</p>
        <h3>Vad är en CVV-kod?</h3>
        <p>CVV-koden är en 3-4 märken lång sifferserie som du hittar på baksidan av kortet invid underskriftsfältet.</p>
        <h3>Jag har betalat avgiften via nätet, men avgiften syns ännu i mina egna uppgifter i Helmet-sök?</h3>
        <p>Det kan förekomma dröjsmål i uppdateringen. Om problemet fortsätter, ta kontakt med biblioteket.</p>
      </div>
      <div id="taskukirjasto" class="content-section">
        <h2>Taskukirjasto - Pocketbibban</h2>   
        <h3>Vad är Taskukirjasto?</h3>
        <p>Taskukirjasto är en mobilapp för Helmetbibliotekets kunder. I Taskukirjasto förnyar du dina lån, söker och reserverar material med några svep med fingret. 
        Du får också lästips och kan kontrollera bibliotekens öppettider och kontaktinformation.Taskukirjasto kan användas på finska, svenska,engelska och ryska.</p>
        <h3>Hur reserverar jag en bok i Taskukirjasto?</h3>
        <p>Logga in dig i appen med ditt bibliotekskorts nummer och din PIN-kod.</p>
        <p>Skriv in bokens namn, författarens namn, ISBN-koden i sökfältet eller rikta den kamera som finns vid sökfältet mot bokens EAN-kod. Tryck på bilden med förstoringsglaset.</p>
        <p>Välj den bok du önskar från listan och tryck på reservationsikonen (bilden där en bok faller ner i en hand).</p>
        <p>Välj det bibliotek där du vill hämta det reserverade materialet genom att först trycka på sökfältet och sedan välja bibliotekets namn från den meny som öppnas. 
        Bekräfta reservationen genom att trycka på sändknappen. Du får ett meddelande om att reservationen har lyckats.</p>
        <p>Om reservationen inte lyckas, kan du logga in i de egna uppgifterna på Helmet.fi och kontrollera om du har försenade lån eller om dina biblioteksavgifter har 
        överstigit 30 euro. Du kan också ringa kundtjänsten på ditt närbibliotek.</p>
        <h3>Hur ändrar jag hämtstället för en reservation, lägger till ett standardställe för hämtning eller frysa mina reservationer?</h3>
        <p>OBS! Man kan inte frysa reservationer i Taskukirjasto för tillfället, bara på Helmet.fi.</p>
        <p>Du kan annullera, frysa och släppa dina reservationer i Taskukirjasto. Välj papperskorgikonen i Taskukirjasto för att annullera reservationen. Välj frysikonen i 
        Taskukirjasto för att frysa reservationen. Om reservationen har frusits så hittar man släppikonen på samma plats.</p>
        <p>Man kan bara byta reservationens avhämtningsplats genom att logga in på sitt bibliotekskonto i Helmet.finna.fi.</p>
        <h3>Varför avläser inte automaten bibliotekskortets streckkod från Taskukirjasto?</h3>
        <p>I Taskukirjasto har bibliotekskortets streckkod förstorats och fokuserats. Om låneautomaten i ditt närbibliotek inte avläser kortets streckkod från telefonskärmen, 
        kan du begära att personalen avläser streckkoden med den läsare som finns vid kundtjänststället. Vi försöker ta fram en bättre lösning.</p>
        <h3>Hur lånar jag en e-bok?</h3>
        <p>E-böcker kan läsas antingen via webbläsaren eller de olika bokförlagens egna appar. <a href="/Content/ohjeet-eaineiston-kayttoon">
        Se instruktionerna under E-bibban i Helmet.finna.fi</a>.</p>
        <h3>Hur lånar jag vidare till en vän?</h3>
        <p>Logga in dig i Taskukirjasto och gå till Kompislån.</p>
        <p>Låntagaren skannar eller skriver in bibliotekets streckkod (inte förläggarens kod) för den bok som lånats av en kompis i det fält som öppnar sig och trycker på enter.</p>
        <p>Appen tar kontakt med långivaren (det kan dröja en stund) och begär att lånet godkänns. Om tidsgränsen överskrids så skriver du in streckkoden på nytt.</p>
        <p>Efter att lånet godkänts uppdaterar appen lånet på vännens kort och lånet får en ny förfallodag. Boken kan återlämnas som vanligt i bibliotekets återlämningsautomat 
        när den har lästs.</p><p>Kompislån kan inte göras, om</p>
        <ul class="list-bullets">
          <li>verket har reserverats,</li>
          <li>verket inte kan reserveras (t.ex. Bestsellers) eller om</li>
          <li>verket har förnyats maximalt antal gånger.</li>
        </ul>
        <h3>Hur ändrar jag mina personliga uppgifter?</h3>
        <p>Tillsvidare kan man endast göra ändringar i de egna uppgifterna genom att logga in i Helmet.finna.fi. Logga in i de egna uppgifterna, klicka på ditt namn och välj 
        Ändra personliga uppgifter.</p>
        <p>Obs! Du kan inte ändra ditt namn via webbtjänsten. Visa ditt identitetsbevis med ditt nya namn i något Helmet-bibliotek (eller ett identitetsbevis med ditt gamla 
        namn samt ett bevis om namnändringen). Du får ett nytt bibliotekskort avgiftsfritt.</p>
        <h3>En fråga till dig:Hur skulle du vilja utveckla den del i Taskukirjasto som är avsedd för favoriter?</h3>
        <p>Berätta vad du har för önskemål på den responsblankett som finns i Taskukirjasto.</p>
      </div>
     <div id="reserveringar" class="content-section">
        <h2>Avgiften för reserveringar som inte avhämtats</h2>
        <h3>Varför införs det en avgift för reserveringar som inte avhämtats?</h3>
        <p>Över 2,8 miljoner reserveringar behandlas varje år i Helmet-städerna, det vill säga i Helsingfors, Esbo, Vanda och Grankulla. I och med att antalet 
        reserveringar ökar, ökar också mängden reserveringar som inte avhämtats. I Helmet-städerna hämtas i genomsnitt 14 procent av alla reserveringar inte, det vill säga 
        sammanlagt cirka 400 000 verk.</p>
        <h3>Hur stor är avgiften?</h3>
        <p>1 euro / reservering som inte avhämtats (t.ex. en bok eller skiva).</p>
        <h3>Varför är det ett problem att man inte hämtar sin reservering?</h3>
        <p>Reserveringskön rör sig långsamt då materialet väntar i flera dagar på hyllan. Man måste också i onödan transportera böcker och annat reserverat material 
        mellan biblioteken.</p>
        <h3>Vad är nyttan med avgiften?</h3>
        <p>Målet med avgiften är att uppmuntra våra klienter att se till att de hämtar eller avbokar sina reserveringar, så att böckerna kan cirkulera snabbare och 
        reserveringskön blir kortare.</p>
        <h3>Jag fick inte något meddelande om min reservering i tid, vare sig genom textmeddelande, e-post eller brevpost. Måste jag ändå betala avgiften för reserveringen?</h3>
        <p>Avgiften bör betalas även om meddelandet om reserveringen inte anlänt på grund av ett problem med distributionen, en störning i datakommunikationen eller någon 
        annan orsak. Du kan följa med läget för din reservering genom Helmet-sidans Egna uppgifter och via Taskukirjasto. Du kan också fråga om läget för dina 
        reserveringar av bibliotekspersonalen på biblioteket eller via telefon.</p>
        <h3>Jag vill ha ett textmeddelande när min reservering kan avhämtas, hur beställer jag det?</h3>
        <p>Om du har sparat ditt mobiltelefonnummer med finsk landskod (t.ex. +358501234567) i dina kunduppgifter får du ett meddelande om din reservering per textmeddelande.</p>
        <h3>Kunde man ändra på Taskukirjasto så att det går att frysa reserveringar direkt i appen?</h3>
        <p>Frys reservering-funktionen har i juni 2021 tillförts den senaste versionen av Taskukirjasto. Du kan ta funktionen i bruk när du uppdaterar appen.</p>
        <h3>Kunde man ändra på låsningsfunktionen för reserveringar så att man också kan låsa ett verk som finns tillgänglig på hyllan?</h3>
        <p>Ingen sådan ändring planeras. Man kan enbart låsa en reservering när den är i reserveringskön. Att låsa lediga verk skulle göra reserveringssituationen mer komplicerad, 
        och därmed också bedömningen av behovet av nya anskaffningar i biblioteket. Om du vill komma ihåg ett verk du är intresserad av kan du använda minneslistan-funktionen och 
        reservera verket senare när det passar dig.</p>
        <h3>Bokbussen anlände inte till hållplatsen. Måste jag betala avgiften? / Jag fick igår meddelande om att reserveringen är i bokbussen, men kan inte komma till 
        hållplatsen idag. Reserveringens sista avhämtningsdag infaller innan bokbussen kommer nästa gång. Måste jag betala avgiften?</h3>
        <p>Nej. För bokbussen, patientbiblioteken och servicecentrens bibliotek avkrävs ingen avgift för reserveringar som inte avhämtats. Reserveringarna förvaras i 
        bussen under två besök oberoende av den automatiska avhämtningstiden som systemet anvisar. Om bokbussen inte anländer till hållplatsen avlägsnas reserveringen 
        inte som icke avhämtad, utan den kommer med nästa vecka.</p>
        <h3>Min reservering har försvunnit ur reserveringshyllan. Måste jag betala avgiften?</h3>
        <p>Kontakta personalen. Personalen kan avboka en reservering i reserveringshyllan utan att en avgift uppstår, och flytta din reservering till början av kön.</p>
        <h3>Gäller avgiften också barnmaterial som inte avhämtats, om det reserverats med en vuxens kort?</h3>
        <p>Ja. Avgiften uppbärs av alla som fyllt 18 år.</p>
        <h3>Berör avgiften material som reserverats med ett barns bibliotekskort?</h3>
        <p>Nej. Avgiften uppbärs inte av användare under 18 år, hemservicens kunder, flexkunder eller sammanslutningskunder som skolor och daghem.</p>
        <h3>Jag har varit sjuk och har inte kunnat uträtta mina ärenden. Kan jag få befrielse från avgifterna?</h3>
        <p>Du kan ansöka om befrielse från betalning av biblioteksavgifter. Kontakta biblioteket för att reda ut frågan.</p>
        <h3>Jag kan inte själv hämta min reservering. Kan någon annan hämta den åt mig?</h3>
        <p>Om du inte själv kan hämta din reservering kan du be en annan person att låna det reserverade verket på sitt eget bibliotekskort vid bibliotekets kundtjänst. 
        Personen som lånar verket för din räkning måste visa upp reserveringsmeddelandet som du fått av biblioteket i form av ett textmeddelande, e-post eller brev, så du 
        bör vidareförmedla det. Om du vill att din reservering lånas på ditt eget bibliotekskort ska den som hämtar reserveringen ha en fullmakt som beskriver ärendet samt 
        ditt bibliotekskort och sitt eget identitetsbevis.<br><br>
        Om du inte behöver det material du reserverat, avboka din reservering så snart som möjligt. På så sätt blir den ledig för nästa kund. Du kan avboka din reservering 
        när som helst innan avhämtningstiden upphör. Om du ännu står i kö för din reservering kan du också frysa den, om du till exempel ska på semester eller är borta av 
        någon annan orsak. Du kan enbart frysa din reservering innan den är på väg eller innan den kommit till reserveringshyllan. Man kan inte frysa reserveringen med 
        Taskukirjasto-appen.</p>
        <h3>Kunde man förlänga / förkorta avhämtningstiden för en reservering?</h3>
        <p>Avhämtningstiden är samma i alla Helmet-bibliotek. Önskemål om att förkorta eller förlänga avhämtningstiden kommer då och då, men kortare tider har i praktiken 
        konstaterats vara för korta, medan längre avhämtningstider förlänger reserveringskön. Längden på avhämtningstiden beslutas gemensamt av Helmet-bibliotekens chefer.</p>
        <h3>Är det inte meningen att biblioteket ska vara en avgiftsfri tjänst? Grundar sig den här avgiften på lag?</h3>
        <p>En lagen om allmänna bibliotek (1492/2016) ska bibliotekens bastjänster vara avgiftsfria för kunderna. Enligt 12 § i lagen kan kommunen ta ut en avgift för 
        material som bland annat återlämnas för sent, och för reserverat material som inte avhämtas.</p>
        <h3>I vilka andra bibliotek än Helmet-bibilioteken måste man betala för reserveringar som inte avhämtats?</h3>
        <p>Till exempel i Joensuus, Uleåborgs och Birkalands PIKI-bibliotek (1 euro) samt i Jyväskyläs, Kuopios, Rovaniemis och Egentliga Finlands VASKI-bibliotek (2 euro).</p>
      </div>
   </div>
</div>