<? $this->headTitle($this->translate('Frequently asked questions')); $this->content()->setHeading($this->translate('Frequently asked questions'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="troubleshooting" class="content-section">
        <h2>Troubleshooting</h2>   
        <h3>I forgot my PIN code, what should I do?</h3>
        <p>Provided you have given us your email address, you can access the password recovery function:</p>
        <p><a href="https://luettelo.helmet.fi/pinreset~S9" target="_blank">Reset PIN </a></p>
        <p>In the case we do not have your email address, we shall change your PIN code at the service desk of any Helmet library. Please bring your ID with you.</p>
        <h3>I lost my library card, what should I do?</h3>
        <p>Report the loss of your library card immediately to any Helmet library. When libraries are closed, you can phone the number 09-3108509. Leave a message 
        on the answerphone giving your name, social security number, and the reason you are calling.</p>
        <p>You are not responsible for the loans that have been checked out on your card after you have reported the card lost. A cancelled card cannot be reissued. 
        A new card is liable to charge.</p>
        <p>If items have been checked out on your lost or stolen library card without your permission, make sure to cancel your card. If necessary, report the crime 
        to police with a report of an offence that states the unlawful use of your card, and list the damages that have been caused.</p>
        <p>Our user regulations state that you are responsible for all items checked out on your card. Therefore you must compensate for lost or damaged items checked 
        out on your card even if the damages are caused by another if they have been checked out before you have cancelled your library card. Check whether your home 
        insurance covers the damages.</p>
        <h3>A library book was damaged or CD was lost, what should I do?</h3>
        <p>Contact a Helmet library in the city that owns the damaged or lost item. If that is inconvenient to you, you may also attend to the matter in the Helmet libraries
        of the other cities of the capital region.</p>
        <p>A damaged or lost item is no longer viable for checking out, so it must be compensated with the purchase price or a 
        <a href="/Content/laina-ajat-ja-maksut?lng=en-gb#joint-fees"> firm compensation price</a>.</p>
        <p>In most cases it is possible to arrange to compensate the item with a new copy of the item. However, films are an exception because these require lending rights.</p>
        <h3>Why did I receive a notice concerning an item I have returned or a reservation I have already checked out?</h3>
        <p>Library notice letters are delivered in 2nd class mail. Therefore, if you have chosen to get your library notifications by post and not by email, they can occasionally
        arrive after you have returned your loans or checked out your reservations.</p>
        <h3>I received a letter from a collection agency concerning unreturned loans. What should I do?</h3>
        <p>Unreturned loans are transferred to a collection agency ca. 60 days after due date. At this stage you have also lost the right to check out library material.</p>
        <p>Read carefully the instructions in the letter. The sum you have to pay depends on whether or not you are still able to return your loan. Make sure you receive a 
        receipt from your returned loans.</p>
        <p>Pay the collection agency what you owe. You will regain the right to loan material when the collection agency notifies library that you have settled the payment.</p>
      </div>
     <div id="using.library" class="content-section">
        <h2>Using the Helmet Library</h2>
        <h3>Can I register as a library patron online?</h3>
        <p>Anyone under 15 years of age can get a library card with a written approval by the guardian or another person responsible for the young person. It is easier for us to 
        make a new library card for you if you <a href="https://luettelo.helmet.fi/selfreg~S9" target="_blank">fill the form via this link</a>, print it out and take it with you 
        to the library.</p>
        <h3>Where can I use the Helmet library card?</h3>
        <p>You can use the Helmet library card in all the public libraries of Espoo, Helsinki, Kauniainen and Vantaa. You can check out, reserve, renew and return material and 
        take care of your affairs in any of these libraries regardless of city limits.</p>
        <h3>Can somebody else visit the library on my behalf?</h3>
        <p>Yes, see instructions how to become a <a href="/Content/kun-et-paase-kirjastoon#flexi-customer">flexi customer</a> and how to use a 
        <a href="/Content/kirjastokortti-ja-lainaaminen?lng=en-gb#power-of-attorney">power of attorney</a>.</p>
        <h3>How do I unsubscribe from the library customership?</h3>
        <p>If you no longer need your own library card or you need to cancel a deceased relative's library card, you can request that the customer data be removed from the 
        library's customer register. Contact the customer service of Helmet libraries by visiting one of the libraries or by phone. The library will check that the card has no 
        unreturned loans, unpaid fees or other unresolved issues. The customer data will then be deleted. Discard the card by cutting it in half. It is not necessary to submit a 
        death certificate to the library.</p>
        <p>Customer data that has not been used by the customer for three years and that do not involve unresolved issues (e.g. open payments) will also be removed from the 
        customer register. Data is removed from the register once a year.</p>
        <h3>Can I have library notices sent to my email or as text messages?</h3>
        <p>Yes you can. <a href="https://luettelo.helmet.fi/screens/e_help.html#varausilmoitus" target="_blank">See instructions here</a>.</p>
        <h3>Do you charge interest on overdue fees?</h3>
        <p>No, there’s no interest on overdue fees.</p>
        <h3>Is there an interest on other payments?</h3>
        <p>Collection agencies charge interest on the payments they collect.</p>
        <h3>Can I pay overdue fees online?</h3>
        <p>Yes. You can <a href="http://www.helmet.fi/maksukaista/?lang=en" target="_blank">pay your fees online here</a>.</p>
      </div>
      <div id="library-material" class="content-section">
        <h2>Library material</h2>   
        <h3>How may I leave acquisition proposals?</h3>
        <p>You can fill in <a href="/Content/hankintaehdotus">an acquisition proposal form.</a> Naturally, you are always welcome to leave requests directly to the library staff.</p>
        <h3>Why can't I find a new publication in Helmet?</h3>
        <p>Acquisitions of new material are often decided months in advance. You can find the material in Helmet online catalogue as soon as the material has been registered into
        the database. Our staff are also happy to check whether material has already been acquired. You can leave 
        <a href="/Content/hankintaehdotus">acquisition proposals</a> online or directly with our staff.</p>
        <h3>Can I borrow material from closed storage?</h3>
        <p>Yes, the library staff will fetch the material you want. The material in closed depositories can also be reserved online in the same way as all other library material. 
        A comprehensive book depository shared by all Helmet libraries resides in the Pasila Library. The Pasila Book Depository has a lot of culturally significant and often out 
        of print material.</p>
        <h3>I can't find a work in Helmet catalogue. Can I reserve it from another library?</h3>
        <p>Yes, you can. Make the reservation in the library from which you wish to fetch your material. Please note, that <a href="/Content/kaukopalvelu#fees">interlibrary loans are 
        liable to fees</a>.</p>
        <h3>How can I reserve a work that is available on the shelf?</h3>
        <p>You can reserve a work in the Helmet online service or Taskukirjasto. You will be notified by text message, e-mail or post when the material is ready for pick up in the 
        pick-up library. If you would like to pick up the work immediately from the library where it is available on the shelf, please call the library in question first and ask the 
        work to be reserved for you. You will need your library card number for the phone reservation. In the online service, you will need your library card number and PIN code.</p>
        <h3>I am unable to pick up my reservation. Can someone else pick it up for me?</h3>
        <p>If you are unable to pick up your reservation yourself, you can ask another person to borrow the reserved item on their own library card at the library’s customer
        service desk. The person borrowing the item must present the reservation notification you received from the library by text message, e-mail or post, so please forward
        your notification to this person. If you would like the reservation to be borrowed on your own library card, the person picking up the item must bring their own ID, your 
        library card and a power of attorney where the intended use is specified.</p>
        <p>If you no longer need the materials you have reserved, please cancel your reservation as soon as possible. This way, the item will become available for the next customer 
        in the queue. You can cancel the reservation any time before the end of the reservation period. You can also freeze a queued reservation for the duration of a holiday or other 
        absence. You can only freeze your reservation before it is on the way to the shelf or has arrived at the shelf.</p>
        <p>The fee for uncollected reservations also applies to reservations made before 1 June that are removed from the reservation section on or after 1 June because they have 
        not been picked up.</p>
        <h3>I am going on holiday and I have reservations. I do not want my reservations to arrive at the library during my trip. Is there something I can do?</h3>
        <p>You can freeze your reservations by signing in to your personal information on the Helmet page. You can freeze a reservation that you are still in the queue for. 
        By freezing your reservation, you ensure that the reserved work will not be ready for pick up at the library until after you have unfrozen it. You will move up in the 
        reservation queue even if your reservation is frozen.</p>
        <p>You can unfreeze your reservation in the same way as you froze it. After you have unfrozen your reservation, it will be ready for pick up at your library once it is 
        your turn in the reservation queue.</p>
        <h3>I do not want my full name to be visible on the reservation shelf. How can I prevent it?</h3>
        <p>Most libraries have switched to numbered reservation shelves or reservations.</p>
        <p>At some libraries, you can pick up reservations under an alias. You can get an alias, i.e. a pseudonym by visiting the library and presenting a valid ID. After getting 
        an alias, your alias will be visible in the reservations instead of your name.</p>
        <h3>Is it possible to buy material from library shelves?</h3>
        <p>Unfortunately we are not open to offers concerning the material that is currently part of our collection. It is possible to buy material that has been removed from 
        the collection. Material might be removed from the collection due to its age, poor condition, outdated contents, or low usage.</p>
        <h3>May I donate my books to library?</h3>
        <p>Yes, libraries accept material donations according to their needs. Libraries reserve the right to further channel the donations e.g. to recycling shelves from where 
        customers can take books for themselves. Feel free to contact the library of your choice on the matter. NB! Cetntral Library Oodi does not accept donations.</p>
        <h3>How are materials chosen?</h3>
        <p>Helmet library comprises the libraries of Espoo, Helsinki, Kauniainen and Vantaa.</p>
        <p>We offer materials for the residents of the Helsinki Metropolitan Area in order to support freedom of speech and active citizenship as well as provide joy and 
        experiences.</p>
        <p>The library has books, magazines, music, movies, audio books and games in both traditional and electronic formats. Some of the magazines can be borrowed and reserved. 
        Plenty of online magazines are also available.</p>
        <p>All material acquisitions are put out to tender. The materials are usually chosen by the local libraries. Materials are purchased for people of all ages in the 
        languages with the most speakers in the Helsinki Metropolitan Area. The library purchases movies and games that are covered by public lending right. The library pays 
        the copyright remuneration.</p>
        <p>Materials that are particularly expensive or expected to have a limited number of users but the purchase of which is still necessary are only selected for 
        some libraries.</p>
        <p>Most Finnish literature is purchased without a separate request. You can fill in an acquisition request online or inform library personnel about the work you would 
        like the library to purchase.</p>
        <p>For quick readers, we have bestsellers that you can borrow for two (2) weeks from your local library. The most popular new music is also loaned out for two (2) weeks.</p>
        <p>You can borrow materials or renew your loans in our online service. We deliver the reserved materials to the desired library throughout the Helmet area. Libraries 
        accept donations at their own discretion.</p>
        <p>The library’s collection lives and changes, and its condition and use are monitored continuously. Materials are removed from the collections due to low demand, 
        poor condition or outdated content. Materials removed from the library are sold to customers, donated or recycled.</p>
      </div>
     <div id="online-payment" class="content-section">
        <h2>Online payment</h2>
        <h2>Paying library fees online</h2>
        <h3>Which fees can be paid online?</h3>
        <p>You can pay almost all library fees online e.g. overdue fees and other general fees. You can also pay for damaged or lost items online. However, contact your nearest
        library first. Fees for books which are more than 60 days overdue cannot be paid online.</p>
        <h3>Are there other fees that cannot be paid online?</h3>
        <p>Loans that are in debt collection cannot be paid online. Debt collection agency is in charge of collecting these fees and therefore library cannot accept 
        these payments.</p>
        <h3>Is there a minimum amount in online paying?</h3>
        <p>There is no minimum amount for payments in Visma payment service. However, your bank or credit card issuer may have a minimum.</p>
        <h3>How are library fees shown on my bank statement?</h3>
        <p>Visma is shown as the recipient of the fees on your bank statement and credit card invoice.</p>
        <h3>Why isn’t the confirmation shown in my e-mail?</h3>
        <p>Some e-mail softwares may interpret the confirmation as spam. You should therefore check all incoming e-mail files and allow the library to send the confirmation to 
        your e-mail in the future.</p>
        <h3>Why can’t I pay the fees directly from my account in the Helmet-search and why do I have to log in again to pay the fees?</h3>
        <p>Library fees e-payment is possible only via online shopping application which is not a part of the Helmet-search. However, you log in to the online shopping application 
        with your library card username and PIN-code and the information about the due payments will be retrieved from the Helmet-database.</p>
        <h3>Can I pay with Visa Electron?</h3>
        <p>You can pay with Visa Electron if the e-payment function is activated in your Visa Electron. In practice most Visa Electrons allow e-payments.</p>
        <h3>How can I make a debit payment?</h3>
        <p>If you have a payment card with credit/debit, you can make a debit payment by using the debit number located on the back side of the card, normally at the bottom. 
        Debit CVV number is located at the end of the debit number and is 3-4 digits long. Please note that not all debit cards allow online payments.</p>
        <h3>What is the CVV number?</h3>
        <p>The CVV number is a 3-4 digit number on the back side of the card, on the end of the signature field.</p>
        <h3>I have paid online but the fee is still listed in my Helmet-account.</h3>
        <p>There might be some delay in the updating. If the problem continues, please contact the library.</p>
        <h3>What should I do in a fault situation and how can I give feedback concerning the e-payments?</h3>
        <p>Send us fault <a href="http://www.helmet-kirjasto.fi/helmet-palaute/index_en.html" target="_blank">notices and feedback</a>. You can also contact your 
        <a href="https://helmet.finna-pre.fi/OrganisationInfo/Home">library</a>.</p>
      </div>
      <div id="taskukirjasto" class="content-section">
        <h2>Taskukirjasto</h2>   
        <h3>What is Taskukirjasto?</h3>
        <p>Taskukirjasto™ is a mobile application for customers of Helmet library. Taskukirjasto allows you to renew your loans, search for material, and make reservations 
        with just a few screen touches. You will also get suggestions for material to read, and you can check the opening hours and contact information of libraries. 
        You can use Taskukirjasto in Finnish, Swedish and English.</p>
        <h3>How do I reserve a book using Taskukirjasto?</h3>
        <p>Log in the application by entering your library card number and PIN.</p>
        <p>Write the name of the book, the author's name or ISBN code on the search line, or direct the search camera on the book’s EAN code. Press the image of the 
        magnifying glass.</p>
        <p>Choose from the list the book you want and press the reserve button under it (icon where the book falls on a hand).</p>
        <p>Choose the pickup library by pressing the search line and choose the name of the library on the menu that opens. Confirm your reservation by pressing the Send button. 
        You will get a message of a successful reservation.</p>
        <p>If the reservation does not succeed, you can log in your own information on Helmet.fi and check whether you have overdue loans or whether your library fees exceed 
        30 euros. You can also call your local library's customer service.</p>
        <h3>How can I change the pickup place, add a default pickup place or freeze my reservation?</h3>
        <p>NB! It is not possible to freeze reservations in the Taskukirjasto app at the moment, only in Helmet.fi.</p>
        <p>In Taskukirjasto you can cancel, freeze and unfreeze your reservations. To cancel a reservation through Taskukirjasto, tap the trash can icon. To freeze a reservation 
        through Taskukirjasto, tap the Freeze button. If the reservation is already freezed you see the Unfreeze button in the same location.</p>
        <p>Changing the pickup place for a reservation can only be done by logging in to Helmet.finna.fi.</p>
        <h3>Why does the automaton not read the library card's barcode in Taskukirjasto?</h3>
        <p>If your local library's checkout machine does not read the card's barcode from your phone, increase the display's brightness level. If it doesn't help, you can 
        ask an employee to read the barcode on the service point's reader. We are trying to devise a better solution.</p>
        <h3>How do I borrow an e-book?</h3>
        <p>You can read e-books either by a browser or with publishers’ own applications. <a href="/Content/ohjeet-eaineiston-kayttoon">See instructions on Helmet.finna.fi´s 
        eLibrary</a>.</p>
        <h3>How do I make a friend loan?</h3>
        <p>Log in Taskukirjasto and go to Friend loan.</p>
        <p>The borrower scans or writes in the opening field the library barcode of the book that his/her friend has currently loaned (not the publisher's code) and presses enter.</p>
        <p>The application contacts the lender (this may take a while) and asks for approval to the loan. If the time limit is exceeded, re-write the barcode.</p>
        <p>After approval, the application updates the loan on your friend’s card and puts a new due date for the loan. After reading the book, you can return it to the 
        library’s check-in machine as usual.</p>
        <p>Friend loan will not succeed if</p>
        <ul class="list-bullets">
            <li>there are reservations for the item</li>
            <li>if the item cannot be reserved (e.g., bestsellers) or</li>
            <li>if the item has been renewed for the maximum number of times.</li>
        </ul>
        <h3>How do I change my contact information?</h3>
        <p>For the time being, you can only change your own information by logging in Helmet.fi. Log in your own information, click on your name and choose 
        Change contact information.</p>
        <p>NB. You cannot change your name via the web service. Please visit any Helmet library and present an ID card with your new name (or an ID card with your old name 
        plus a certificate of changing your name). You will get a new library card free of charge.</p>
      </div>
     <div id="uncollected-reservations" class="content-section">
        <h2>The fee for uncollected reservations</h2>
        <h3>Why are you introducing a fee for uncollected reservations?</h3>
        <p>More than 2.8 million reservations are processed in the Helmet cities – Helsinki, Espoo, Vantaa and Kauniainen – every year. As the reservation volumes increase, 
        so does the number of reservations that no one picks up from the libraries. In the Helmet cities, 14 per cent of reservations, on average, meaning about 400,000 items,
        are left uncollected every year.</p>
        <h3>How high is the fee?</h3>
        <p>EUR 1 per uncollected reservation (such as a book or a record)</p>
        <h3>Where is the harm in leaving reservations uncollected?</h3>
        <p>The reservation queues move slowly when the materials sit on the shelves for several days. We also need to transport books and other reservations unnecessarily 
        between libraries.</p>
        <h3>What good does the fee do?</h3>
        <p>The aim of the fee is to encourage customers to pick up or cancel their reservations so that the books circulate faster and the queues become shorter.</p>
        <h3>I did not receive a text message, e-mail notification or letter about my reservations in time. Do I still need to pay the fee for the reservations?</h3>
        <p>The fee will be charged even if the pick-up notification has not arrived due to a delivery error, a fault in the telecommunications, or another reason. You can 
        also check the status of your reservations via your profile in the Helmet search or Taskukirjasto. You can also ask about your reservations by calling or 
        visiting the library.</p>
        <h3>How do I subscribe to notifications about reservations?</h3>
        <p>If you have saved your phone number in your customer information using the country code for Finland (e.g. +358 501 234 567), you will receive a text message 
        notification about the reservation.</p>
        <h3>Could we have the option to freeze reservations in Taskukirjasto?</h3>
        <p>Freezing holds functionality was added to the latest version of the Taskukirjasto app in July 2021. You can start using this functionality by updating the app.</p>
        <h3>Could you change the option to freeze a reservation so that I could freeze an item that is available on the shelf?</h3>
        <p>No such changes are being planned. You can only freeze a reservation when it is in the queue. Freezing available items would make it more difficult for libraries 
        to monitor the reservation situation and the need for new materials. If you would like to make a note of an interesting item, you can use the ‘reminder list’ option 
        and reserve the item at a more suitable time.</p>
        <h3>The mobile library did not show up. Do I still need to pay the fee? / I received a notification that a reservation was on the mobile library yesterday, and I 
        cannot make it to the stop today. The last pick-up date for the reservation is before the next mobile library visit. Do I need to pay the fee?</h3>
        <p>No. The mobile library, patient libraries and service centre libraries do not charge the fee for uncollected reservations. The reservations will be stored on the 
        mobile library for two visits, regardless of the pick-up date provided automatically by the system. If the mobile library does not show up at the stop, the 
        reservations will not be removed. Instead, they will remain available during the next weeks.</p>
        <h3>My reservation is gone from the reservation shelf. Do I need to pay?</h3>
        <p>Please contact the staff. The staff can cancel a reservation on the shelf so that the fee is not charged. They will also return your reservation to the 
        top of the list.</p>
        <h3>Will the fee be charged for uncollected children’s materials if they were reserved using an adult’s card?</h3>
        <p>Yes. The fee will be charged to customers aged over 18.</p>
        <h3>Does the fee apply to materials reserved using a child’s library card?</h3>
        <p>No. The fee will not be charged to customers aged under 18, home services customer, <a href="/Content/kun-et-paase-kirjastoon#flexi-customer">flexi customers</a> 
        or community customers, such as schools or daycare centres.</p>
        <h3>Why is the fee being introduced from 1 June 2021, even though the COVID-19 restrictions are still in effect?</h3>
        <p>We will introduce the fee for uncollected reservations on 1 June, as planned, since customers are able to visit the libraries even while the COVID-19 
        restrictions are in place. However, the libraries do not want their customers to incur extra fees caused by the pandemic. If you cannot make it to the 
        library, you can freeze or cancel your reservation via the Helmet online service or by contacting the library by phone, for example.</p>
        <h3>I have been ill and therefore unable to run errands. Can I be exempted from the fees?</h3>
        <p>You can be exempted from library fees. Please contact your library to resolve the matter.</p>
        <h3>I am unable to pick up my reservation. Can someone else pick it up for me?</h3>
        <p>If you are unable to pick up your reservation yourself, you can ask another person to borrow the reserved item on their own library card at the library’s 
        customer service desk. The person borrowing the item must present reservation notification you received from the library by text message, e-mail or post, so 
        please forward your notification to this person. If you would like the reservation to be borrowed on your own library card, the person picking up the item must 
        have with them your library card, a power of attorney where the intended use is specified and their own identity card.<br><br>
        If you no longer need the materials you have reserved, please cancel your reservation as soon as possible. This way, the item will become available for the next customer 
        in the queue. You can cancel the reservation any time before the end of the reservation period. You can also freeze a queued reservation for the duration of a holiday 
        or other absence. You can freeze your reservation before it is on the way to the shelf or it has arrived at the shelf. Reservations cannot be frozen in the 
        Taskukirjasto app.</p>
        <h3>Could you extend/shorten the collection periods of reservations?</h3>
        <p>The reservation periods are the same for all Helmet libraries. Customers occasionally request that we either reduce or extend the reservation periods, but in practice, 
        we have noticed that the shorter periods are too short, while longer periods also lengthen the queues. The directors of the Helmet libraries decide on the length 
        of the reservation periods jointly.</p>
        <h3>Shouldn’t libraries offer the services for free? Is this fee based on law?</h3>
        <p>As specified in the Public Libraries Act (1492/2016), the basic services of libraries are offered to customers free of charge. However, according to Section 
        12 of the Act, municipalities may charge fees for materials returned late or uncollected reserved materials.</p>
        <h3>Are there other libraries than the Helmet ones that charge a fee for uncollected reservations?</h3>
        <p>The libraries of Joensuu, Oulu and Pirkanmaa (1 euro), as well as Jyväskylä, Kuopio, Rovaniemi and Southwestern Finland (2 euros), for example, charge a 
        fee for uncollected reservations.</p>
      </div>
   </div>
</div>
