<? $this->headTitle($this->translate('Koulujen ja päiväkotien alueet Vantaalla')); $this->content()->setHeading($this->translate('Koulujen ja päiväkotien alueet Vantaalla'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="kirjastovierailu" class="content-section">
        <h2>Sovi kirjastovierailu koulu- tai päiväkotiryhmällesi</h2>
        <p>Omaan lähikirjastoon kannattaa olla yhteydessä muutamaa viikkoa ennen ajankohtaa. Sovi kirjastovierailu ottamalla yhteyttä joko sähköpostitse tai soittamalla.</p>
        
      </div>
     <div id="kirjastoauto" class="content-section">
        <h2>Kirjastoauton palvelut kouluille Vantaalla</h2>
        <p>Lisätiedot ja yhteydenotot/Kirjastoauto Vantaa:</p>
        <p>Juha Pönni <a href="mailto:juha.ponni@vantaa.fi">juha.ponni@vantaa.fi</a><br>
        Maria Miettunen <a href="mailto:maria.miettunen@vantaa.fi">maria.miettunen@vantaa.fi</a></p>
        
        <h3>Aineiston varaaminen</h3>
        <p>Isot aineistotilaukset ja aineistopakettitilaukset kannattaa tehdä <a href="https://link.webropol.com/s/peruskoulut" target="_blank"
        aria-label="verkkolomakkeella. Linkki aukeaa uudessa ikkunassa.">verkkolomakkeella täällä</a>
        tai sähköpostitse. Aineistopakettilomakkeella voi varata esimerkiksi pulpettikirjoja, lukupiirikirjoja tai kirjaston henkilökunnan valitsemia, luokkatasolle sopivia 
        kirjoja esimerkiksi Helmet-lukudiplomista. Paketin valmistuminen kestää viikosta muutamaan viikkoon. Ilmoitamme sähköpostitse, milloin paketti on valmiina noudettavaksi 
        kirjastoautosta.</p>
        <p>Yksittäiset aineistovaraukset on helpoin tehdä kirjaston Helmet.finna.fi-verkkopalvelun kautta. Kirjoittakaa tekemänne varauksen lisähuomautuskenttään noutopysäkki, 
        jotta osaamme tuoda varaukset oikealle pysäkille.</p>
        
        <h3>1.-luokkalaisten tutustumiskäynti</h3>
        <p>Ekaluokkalaiset ovat tervetulleita opettajiensa kanssa lyhyelle tutustumiskäynnille kirjastoautoon, jonka aikana kerromme heille kirjastonkäytöstä ja esittelemme kirjastoautoa. 
        Tutustumiskäynnin voi tilata <a href="https://link.webropol.com/s/peruskoulut" target="_blank"
        aria-label="verkkolomakkeella. Linkki aukeaa uudessa ikkunassa.">verkkolomakkeella</a> tai ottamalla yhteyttä kirjastoautoon.</p>
        
        <h3>Ekaluokkalaiskampanja</h3>
        <p>Helmet-kirjastot lahjoittavat vuosittain yhden helppolukuisen lastenkirjan kaikille koulunsa aloittaville pääkaupunkiseudun 1.-luokkalaisille.Tervetuloa noutamaan 
        ekaluokkalaiskirjat kirjastoautosta tai lähikirjastostasi.</p>
        
        <h3>Helmet-lukudiplomi</h3>
        <p>Lukudiplomi motivoi oppilaita säännölliseen lukemiseen ja toimii oivana vinkkipankkina myös opettajille, kun valitaan luokkatasolle sopivia kirjoja. 
        Helmet-lukudiplomit löydät <a href="http://www.lukudiplomi.fi" target="_blank" 
        aria-label="verkosta. Linkki aukeaa uudessa ikkunassa.">verkosta täältä.</a></p>
        
        <h3>Kirjastokortti</h3>
        <p>Kirjastokortti kannattaa hankkia viimeistään ensimmäisen luokan alussa. Lähetämme lukuvuoden alussa kirjastokortin hakemuslomakkeita ja käyttösääntöjä jaettavaksi 
        ekaluokkalaisille ja heidän vanhemmilleen. Oppilaiden on helppo hankkia kirjastokortti vanhempiensa kanssa lähikirjastosta, mutta se onnistuu myös kirjastoautokäynnillä. 
        Myös luokalle voidaan tehdä yhteinen kirjastokortti, jolla esimerkiksi pulpettikirjojen lainaus käy näppärästi.</p>
        
        <h3>Tapahtumat</h3>
        <p>Jos haluatte kirjastoauton mukaan koulunne tapahtumaan, olkaa yhteydessä mahdollisimman ajoissa. Kirjastoauto saapuu tapahtumiin mielellään, jos se sopii muuhun aikatauluun. 
        Jos ette pääse kirjastoautoon koulun oman erityisohjelman takia, ilmoittaisitteko siitä etukäteen.</p>

      </div>
      <div id="koulujako" class="content-section">
        <h2>Koulujako 2022–2023</h2>
        <p>Tästä listauksesta voit tarkistaa, minkä kirjaston alueelle oma koulusi tai päiväkotisi kuuluu.</p>
        <p>Listasta näet, pysähtyykö kirjastoauto koulullasi tai päiväkodillasi. Tarkista kirjastoauton aikataulut 
        <a href="/Content/kirjastoauto-vantaa">Vantaan kirjastoauton sivuilta.</a><br>
        <h3>Hakunilan kirjasto:</h3>
        <p>Itä-Hakkilan koulu (kirjastoauton pysäkki)<br>
        Lehtikuusen koulu<br>
        Sotungin koulu</p>
        <h3>Kivistön kirjasto:</h3>
        <p>Aurinkokiven koulu (kirjastoauton pysäkki)<br>
        Kanniston koulu (kirjastoauton pysäkki)<br>
        Keimolanmäen koulu (kirjastoauton pysäkki)<br>
        Seutulan koulu (kirjastoauton pysäkki)</p>
        <h3>Koivukylän kirjasto:</h3>
        <p>Havukoskien koulu<br>
        Koivukylän koulu<br>
        Kytöpuiston koulu (kirjastoauton pysäkki)<br>
        Päiväkummun koulu (kirjastoauton pysäkki)<br>
        Rekolan koulu (kirjastoauton pysäkki)<br>
        Rekolanmäen koulu (kirjastoauton pysäkki)</p>
        <h3>Lumon kirjasto:</h3>
        <p>Jokivarren koulu (kirjastoauton pysäkki)<br>
        Leppäkorven koulu<br>
        Mikkolan koulu (kirjastoauton pysäkki)<br>
        Ruusuvuoren koulu<br>
        Vierumäen koulu (kirjastoauton pysäkki)</p>
        <h3>Länsimäen kirjasto:</h3>
        <p>Länsimäen koulu<br>
        Rajakylän koulu</p>
        <h3>Martinlaakson kirjasto:</h3>
        <p>Askiston koulu (kirjastoauton pysäkki)<br>
        Kivimäen koulu<br>
        Martinlaakson koulu</p>
        <h3>Myyrmäen kirjasto:</h3>
        <p>Hämeenkylän koulu (kirjastoauton pysäkki)<br>
        Kaivokselan koulu (kirjastoauton pysäkki)<br>
        Kilterin koulu<br>
        Rajatorpan koulu (kirjastoauton pysäkki)<br>
        Uomarinteen koulu<br>
        Pähkinärinteen koulu</p>
        <h3>Pointin kirjasto:</h3>
        <p>Kartanokosken koulu<br>
        Vantaan kansainvälinen koulu<br>
        Veromäen koulu<br>
        Ylästön koulu (kirjastoauton pysäkki)</p>
        <h3>Tikkurilan kirjasto:</h3>
        <p>Hiekkaharjun koulu<br>
        Ilolan koulu (kirjastoauton pysäkki)<br>
        Jokiniemen koulu<br>
        Kuusikon koulu (kirjastoauton pysäkki)<br>
        Peltolan koulu<br>
        Simonkallion koulu<br>
        Simonkylän koulu<br>
        Viertolan koulu (kirjastoauton pysäkki)</p>
      </div>
      <div id="paivakoti" class="content-section">
        <h2>Päiväkotijako 2022-2023</h2>
        <h3>Hakunilan kirjasto</h3>
        <p>Avoin päiväkoti Pikku-Hepo<br>
        Hakunilanrinteen päiväkoti<br>
        Hepopuiston päiväkoti<br>
        Hevoshaan päiväkoti (kirjastoauton pysäkki)<br>
        Itä-Hakkilan päiväkoti (kirjastoauton pysäkki)<br>
        Kannuskujan päiväkoti<br>
        Kimokujan päiväkoti<br>
        Nissaksen päiväkoti (kirjastoauton pysäkki)<br>
        Norlandia Karuselli<br>
        Nuppula päiväkoti<br>
        Pikkuravurin päiväkoti<br>
        Ravurin päiväkoti<br>
        Ravurinpuiston päiväkoti<br>
        Suitsikujan päiväkoti<br>
        Tik Tak Vaarala<br>
        Vaaralanpuiston päiväkoti</p>
        <h3>Kivistön kirjasto</h3>
        <p>Aurinkokiven päiväkoti<br>
        Avoin päiväkoti Auringonkukka<br>
        Husaaritien päiväkoti (kirjastoauton pysäkki)<br>
        Kanniston päiväkoti<br>
        Keimolanmäen päiväkoti (kirjastoauton pysäkki koululla)<br>
        Kivistön päiväkoti<br>
        Lipunkantajan päiväkoti (kirjastoauton pysäkki)<br>
        Maitorpan päiväkoti (kirjastoauton pysäkki)<br>
        Norlandia Luontopäiväkoti Kaarna<br>
        Pilke tiedepäiväkoti Hohto<br>
        Seutulan päiväkoti (kirjastoauton pysäkki)<br>
        Touhula Jalokivi</p>
        <h3>Koivukylän kirjasto</h3>
        <p>Hansin päiväkoti<br>
        Havukallion päiväkoti<br>
        Koskimyllyn päiväkoti<br>
        Kustaantien päiväkoti<br>
        Leinelän päiväkoti (kirjastoauton pysäkki)<br>
        Piilipuun päiväkoti<br>
        Pilke Ilmaisupäiväkoti Illusia<br>
        Pilke tiedepäiväkoti Oivallus<br>
        Pilke tiedepäiväkoti Tähtisumu<br>
        Päiväkummun päiväkoti<br>
        Rautkallion päiväkoti<br>
        Rautpihan päiväkoti<br>
        Rautpihan avoin päiväkoti<br>
        Rekolanmäen päiväkoti<br>
        Seljapolun päiväkoti<br>
        Tarhapuiston päiväkoti<br>
        Ulrikan päiväkoti (kirjastoauton pysäkki)<br>
        Valtikan päiväkoti</p>
        <h3>Lumon kirjasto</h3>
        <p>Ankkalammen päiväkoti<br>
        Ilvespuiston päiväkoti (kirjastoauton pysäkki)<br>
        Kiirunatien päiväkoti<br>
        Korson päiväkoti<br>
        Leppäkorven päiväkoti (kirjastoauton pysäkki)<br>
        Maauuninpolun päiväkoti<br>
        Maarukan päiväkoti<br>
        Matarin päiväkoti</p>
        Metsolan päiväkoti<br>
        Metsolanmäen päiväkoti<br>
        Metsälinnun päiväkoti<br>
        Nikinmäen päiväkoti (kirjastoauton pysäkki)<br>
        Näätäpuiston päiväkoti<br>
        Pilke tiedepäiväkoti Oivallus<br>
        Saturnuksen päiväkoti<br>
        Saturnuksen avoin päiväkoti<br>
        Siimapuiston päiväkoti (kirjastoauton pysäkki)<br>
        Touhula Aarrekallio<br>
        Touhula Korso<br>
        Tähdenlennon päiväkoti<br>
        Tähdenlennon avoin päiväkoti<br>
        Vallinojan päiväkoti (kirjastoauton pysäkki)</p>
        
        <h3>Länsimäen kirjasto</h3>
        <p>Fazerin päiväkoti (kirjastoauton pysäkki)<br>
        Keihäspuiston päiväkoti<br>
        Latukujan päiväkoti<br>
        Latupuiston päiväkoti<br>
        Linnoituskujan päiväkoti<br>
        Länsimäen avoin päiväkoti<br>
        Länsimäen päiväkoti<br>
        Pallastunturin päiväkoti<br>
        Rajakylän päiväkoti<br>
        Vartiokujan päiväkoti</p>
        
        <h3>Martinlaakson kirjasto</h3>
        <p>Fyndet Ingefära<br>
        Fyndet Kanel<br>
        Jokiuoman päiväkoti<br>
        Kimaran päiväkoti<br>
        Kivimäen päiväkoti (kirjastoauton pysäkki)<br>
        Kukinpolun päiväkoti<br>
        Laajavuoren päiväkoti<br>
        Lintukallion päiväkoti<br>
        Louhelan päiväkoti<br>
        Martinlaakson päiväkoti<br>
        Suomalais-venäläinen päiväkoti Matrjoshka<br>
        Metsikköpolun päiväkoti<br>
        Norlandia Luontopäiväkoti Kaarna<br>
        Patotien päiväkoti<br>
        Raikupolun päiväkoti<br>
        Soittorasian Avoin päiväkoti<br>
        Vantaanlaakson päiväkoti<br>
        Varistonniityn päiväkoti<br>
        Taidepäiväkoti Sininen Kuu</p>
        
        <h3>Myyrmäen kirjasto</h3>
        <p>Autioniityn päiväkoti<br>
        Fyndet Kardemumma<br>
        Hämeenkylän päiväkoti (kirjastoauton pysäkki)<br>
        Hämevaaran päiväkoti<br>
        Jönsaksen päiväkoti<br>
        Kaivokselan päiväkoti (kirjastoauton pysäkki)<br>
        Karhunpesän päiväkoti<br>
        Kilterin päiväkoti<br>
        Koskikujan päiväkoti<br>
        Niittyvillan avoin päiväkoti<br>
        Nikkarin päiväkoti<br>
        Ojahaan päiväkoti<br>
        Pilke Tiedepäiväkoti Pikkukarhu<br>
        Pähkinänsärkijän päiväkoti (kirjastoauton pysäkki)<br>
        Pähkinärinteen päiväkoti<br>
        Simpukan päiväkoti<br>
        Solkikujan päiväkoti<br>
        Touhula Kaivoksela<br>
        Vapaalan päiväkoti<br>
        Variston päiväkoti<br>
        Vaskikellon avoin päiväkoti<br>
        Vaskivuoren päiväkoti<br>
        Päiväkoti Villikatti<br>
        Päiväkoti Leijonamieli<br>
        Virtatien päiväkoti</p>
        
        <h3>Pointin kirjasto</h3>
        <p>Avoin päiväkoti Karhunkolo<br>
        Illenpihan päiväkoti<br>
        Illenpuiston päiväkoti<br>
        Isonmännyn päiväkoti (kirjastoauton pysäkki)<br>
        Kartanonkosken päiväkoti<br>
        Lystilän päiväkoti<br>
        Ollaksen päiväkoti (kirjastoauton pysäkki)<br>
        Pakkalan päiväkoti<br>
        Pakkalan avoin päiväkoti<br>
        Pakkalanrinteen päiväkoti (kirjastoauton pysäkki)<br>
        Pehtoorin päiväkoti<br>
        Peltovuoren päiväkoti (kirjastoauton pysäkki)<br>
        Riihipellon päiväkoti (kirjastoauton pysäkki)<br>
        Tammiston päiväkoti<br>
        Tammistonrannan päiväkoti (kirjastoauton pysäkki)<br>
        Touhula LoistoVekara<br>
        Touhula Veromies (kirjastoauton pysäkki)<br>
        Y.E.S. päiväkoti<br>
        Ylästön päiväkoti</p>
        
        <h3>Tikkurilan kirjasto</h3>
        <p>Eppilän päiväkoti<br>
        Fyndet Nejlika<br>
        Hiekkaharjun päiväkoti<br>
        Ilolan päiväkoti<br>
        Jokiniemen päiväkoti<br>
        Krassitien päiväkoti<br>
        Kurjenpolven päiväkoti<br>
        Kukkopillin päiväkoti<br>
        Kuusikon päiväkoti<br>
        Kuusikkotien päiväkoti (kirjastoauton pysäkki)<br>
        Kämmekkäpuiston päiväkoti<br>
        Linnean Päiväkoti<br>
        Lehdokin päiväkoti<br>
        Lummepolun päiväkoti<br>
        Lyckoslanten folkhälsans daghem<br>
        Malminiityn päiväkoti (kirjastoauton pysäkki)<br>
        Mistelin päiväkoti (kirjastoauton pysäkki)<br>
        Montessoripäiväkoti Montsa<br>
        Montessoripäiväkoti Rantakaisla<br>
        Peltolan päiväkoti<br>
        Pilke luontopäiväkoti Kielo (kirjastoauton pysäkki)<br>
        Pilke Musiikkipäiväkoti Kaniini<br>
        Pilke Päiväkoti Käpälämäki<br>
        Pilke Pohjantähti<br>
        Päiväkoti Emilia<br>
        Ristipuron päiväkoti (kirjastoauton pysäkki)<br>
        Ruokopillin päiväkoti<br>
        Satomäen päiväkoti<br>
        Simonkallion päiväkoti (kirjastoauton pysäkki)<br>
        Simonmetsän päiväkoti<br>
        Sinirikon päiväkoti<br>
        Tiedonjyvän päiväkoti<br>
        Tikkurilan päiväkoti<br>
        Touhula Hiekkaharju (kirjastoauton pysäkki)<br>
        Touhula Ilola (kirjastoauton pysäkki)<br>
        Ukko-Pekan avoin päiväkoti<br>
        Urheilupuiston päiväkoti<br>
        Vehnätien päiväkoti (kirjastoauton pysäkki)<br>
        Veturin päiväkoti<br>
        Yrttitien päiväkoti</p>
        </div>
      </div>
   </div>
</div>





