<? $this->headTitle($this->translate('Volontärarbete på biblioteket')); $this->content()->setHeading($this->translate('Volontärarbete på biblioteket'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Som volontär på Helmet-biblioteken kan du vara med och organisera en mångsidig och varierande verksamhet.</p>
        <p>På biblioteket kan volontärer till exempel hålla en bokcirkel eller en språkklubb för vuxna, läsa sagor eller böcker för barn, ordna verksamhet för ungdomar (till exempel spelkvällar), 
        leda en handarbetsgrupp eller ordna diskussionskvällar.</p>
        <p>Volontärerna är till exempel ledare för litteraturcirklar, biblioteksmormor eller -farfar, hundförare för läshundar, högläsare av noveller och sagor samt ledare för handarbets- och spelkvällar. 
        På biblioteket kan du också pröva på nya former av frivilligverksamhet. Du kan också ordna verksamhet på ditt eget modersmål.</p>
        <p>Genom att erbjuda möjligheter till ideell verksamhet stöder biblioteket aktivt medborgarskap, delaktighet och gemenskap. Som volontär får du dela med dig av ditt kunnande, du lär dig nya färdigheter 
        och möter nya människor. Den verksamhet som ordnas av frivilliga på biblioteket ersätter inte det arbete som utförs av bibliotekets yrkesanställda.</p>
      </div>
     <div id="espoo" class="content-section">
        <h2>Kom med som frivillig till biblioteken i Esbo</h2>
        <h3>På språkcaféet eller kaffetillfällen med lättlästa nyheter</h3>
        <p>På språkcaféet diskuterar vi på finska om överenskomna ämnen. Som frivillig har du möjlighet att hjälpa olika länders invandrare, som övar sig på att lära ett nytt språk. Du kan lyssna och 
        fråga, ge råd och uppmuntra. Språkcaféet hålls i Iso Omena biblioteket på tisdagar kl. 17-18.30.<br><br>
        Lättlästa nyheter hör vi och läser tillsammans över en kopp kaffe. Deltagarna är fullvuxna invandrare, som övar sig på att förstå finskspråkiga texter och också att diskutera aktuella ämnen. 
        De här tillfällena ordnas i Entresse bilblioteket på torsdagar kl. 10-12.<br><br>
        Kom med! Mera uppgifter om språkcaféverksamheten och tillfällena med lättlästa nyheter ger <a href="mailto:jasmin.lappalainen@espoo.fi">jasmin.lappalainen@espoo.fi</a>.</p>
        <h3>Ledare för bokcirkel</h3>
        <p>Läser du gärna mycket? Tycker du det är naturligt att diskutera det du har läst? I bibliotekens bokcirklar möts människor som är intresserade av litteratur. I bokcirkeln läser man ett verk som är 
        gemensamt bestämt på förhand och med hjälp av ledaren förs diskussion om boken i fråga. Det hålls bokcirklar i olika bibliotek på olika tidpunkter.<br><br>
        Vi söker både ledare och hjälpledare till dessa bokcirklar. Också andra än finskspråkiga är välkomna. Rollen som ledare för bokcirkeln innebär att öppna diskussionen och föra den framåt, 
        samt att se till att var och en rättvist får delta i samtalet.<br><br>
        Om du blev intresserad, tag kontakt med <a href="mailto:satu.nylund@espoo.fi">satu.nylund@espoo.fi</a> så berättar vi gärna mera!</p>
        <h3>Ledare för läshund eller läskeldjur</h3>
        <p>Att med assistens av djur stödja läsandet är viktigt frivilligarbete. Har du ett keldjur, som du tillsammans skulle vilja utvecklas med i den här uppgiften? Hund, katt, kanin, sköldpadda eller 
        något annat ljuvligt djur? Du har kontroll över ditt keldjur, som inte är rädd för oväsen i biblioteket och som tycker om människor, speciellt barn. Ditt keldjur får vara livligt och ivrigt och 
        själv är du intresserad av att hjälpa barn, som kämpar med att börja lära sig läsa. Både bibliotek och tidtabell som passar era önskemål skräddarsyr vi, och vi ger också till en början handledning 
        i uppgiften. Biblioteket önskar att läskeldjuren har deltagit i lämplighetstest före de börjar med frivilligarbetet. Skolning samt tester arrangeras av bl.a. 
        <a href="https://suomenkarvakaverit.fi/" target="blank" aria-label="Finlands Lurviga Kompisar. Länken öppnas i ett nytt fönster.">Finlands Lurviga Kompisar</a> och <a href="https://www.kennelliitto.fi/sv/hundar/lashundar" target="blank" 
        aria-label="Kennelklubben. Länken öppnas i ett nytt fönster.">Kennelklubben.</a><br><br>
        Tag kontakt och fråga mera <a href="mailto:kirjasto.lukukoira@espoo.fi">kirjasto.lukukoira@espoo.fi</a></p>
        <h3>Handledare för läxklubben</h3>
        <p>Biblioteket är en plats för många skolelever att fördriva tiden på och också en naturlig plats där man tillsammans kan göra sina läxor. Ibland kan det dock vara viktigt att få stöd. 
        Kom med och hjälp till!<br><br>
        Hjälpen med läxläsning är ett öppet tillfälle, då skoleleverna kan be om hjälp av frivilliga. Biblioteket ordnar denna hjälp med läxorna på överenskomna dagar i olika bibliotek och de frivilliga 
        vuxna förbinder sig att vara med i verksamheten en termin i taget.<br><br>
        Om du blev intresserad, tag kontakt med <a href="mailto:ira.cottier@espoo.fi">ira.cottier@espoo.fi</a> så berättar vi gärna mera!</p>
        <h3>Handledare för verkstaden (paja)</h3>
        <p>I bibliotekens verkstäder får man fixa allt möjligt! Kan du sy, virka, tova, teckna, måla, pyssla, bygga eller nåt annat? Skulle du vilja dela med dig av ditt kreativa kunnande genom att 
        instruera och visa andra?<br><br>
        Vi söker handledare som leder verksamheten speciellt med barn-, ungdoms- och invandrargrupper. Du kan också hjälpa till med att visa hur man använder verkstadens olika apparater, som vinylskärare, 
        3d-skrivare eller symaskiner.<br><br>
        Mera uppgifter om verksamheten med verkstäderna ger <a href="mailto:marja.uosukainen@espoo.fi">marja.uosukainen@espoo.fi</a>.</p>
        <h3>Med i organisationernas frivilligverksamhet</h3>
        <p>Har du kanske inte hittat något lämpligt? I biblioteken i Esbo verkar också många olika föreningar och organisationer, och genom dessa kan du komma med i frivilligverksamhet. Vi läser 
        tillsammans -nätverket, Finlands Röda Kors och Finlands Flyktinghjälp ordnar verksamhet för att stöda invandrarnas finska språkkunskaper. Enter ry erbjuder gratis handledning till seniorer med 
        digiproblem. För verksamheten med läshundar ansvarar Finlands kennelklubb.</p>
        <h4>Mera information:</h4>
        <p><a href="https://luetaanyhdessa.fi/tule-mukaan/vapaaehtoiseksi/" target="_blank" aria-label="Luetaan yhdessä -verkosto. Länken öppnas i ett nytt fönster.">Luetaan yhdessä -verkosto</a></p>
        <p><a href="http://rednet.punainenristi.fi/keskiespoo" target="_blank" aria-label="Suomen Punainen Risti, Keski-Espoon osasto. Länken öppnas i ett nytt fönster.">Suomen Punainen Risti, Keski-Espoon osasto</a></p>
        <p><a href="https://pakolaisapu.fi/vapaaehtoistyo/" target="_blank" aria-label="Suomen Pakolaisapu. Länken öppnas i ett nytt fönster.">Suomen Pakolaisapu</a></p>
        <p><a href="https://www.entersenior.fi/yhdistys/tule-vapaaehtoiseksi/" target="_blank" aria-label="Enter ry. Länken öppnas i ett nytt fönster.">Enter ry</a></p>
        <p><a href="https://www.kennelliitto.fi/sv/hundar/lashundar" target="_blank" aria-label="Finska kennelklubben ry. Länken öppnas i ett nytt fönster.">Suomen kennelliitto - Finska kennelklubben ry</a></p>
      </div>
      <div id="helsinki" class="content-section">
        <h2>Volontäruppdrag på Helsingfors stadsbibliotek</h2>
        <h3>Ledare för bokcirkel</h3>
        <p>I bokcirklarna, som träffas en gång i månaden, läser man böcker och diskuterar litteratur. Bibliotekspersonalen introducerar dig i uppgiften och kan åtminstone i början vara med och leda gruppen.</p>
        <p>De volontärer som deltar i bokcirklarna ska vara intresserade av litteratur, ingen annan erfarenhet krävs.</p>
        <h3>Ledare för eftermiddagsverksamhet för barn och unga</h3>
        <p>Bibliotekens mor- och farföräldrar och andra ledare för eftermiddagsverksamheten spelar, läser och ritar eller annars umgås med barnen efter skolan. Som bibliotekens mor- och farförälder kan
        du arbeta på ett sätt som passar just dig. De tillbringar cirka 2–2½ timmar i veckan på biblioteket under den överenskomna dagen.</p>
        <h3>Ledare för det finska språkkaféet</h3>
        <p>På språkkaféerna kan du vara med och stödja inlärningen av finska eller leda språkkafé för invandrare. Kravet är att du är bra på det finska språket, har goda samspelsfärdigheter och vill lyssna på
        och förstå finska som talas på olika sätt. På språkkaféerna finns ibland bibliotekspersonal som gruppledare. Volontärerna introduceras i uppgifterna.</p>
        <p>Syftet med verksamheten är att stärka deltagarnas språkkunskaper i finska, ge information om det finländska samhället, hjälpa med integrationen och ge möjlighet att lära känna nya människor.</p>
        <p>Språkkaféerna träffas i regel en gång i veckan, några mer sällan.</p>
        <h3>Högläsare</h3>
        <p>Gillar du att läsa? Vill du förmedla glädjen av att läsa? Kom med i läskamraterna! Som läskamrat stödjer du läsintresset i Helsingfors genom att högläsa för äldre personer eller andra som behöver 
        hjälp med läsning. Läsningen sker till exempel i servicehus.</p>
        <p>Biblioteken i Helsingfors stödjer läskamraterna. Biblioteken ordnar möten för läskamraterna, där man ger tips om böcker som lämpar sig för högläsning, förmedlar läsinspiration och diskuterar 
        frågor och erfarenheter kring läsning.</p>
        <p>Följ evenemangskalendern på webbplatsen för Helmet för att se när läskamraterna träffas. Mer information får du genom att skicka e-post till <a href="mailto:lukulahettilas@hel.fi">lukulahettilas@hel.fi</a>
        och på biblioteken.</p>
        <p>Som högläsare kan du också delta i olika evenemang på biblioteken, till exempel i Novellkaféer.</p>
        <h3>Övrig verksamhet</h3>
        <p>På biblioteken finns flera möjligheter att delta i volontärverksamhet – kom med egna idéer eller engagera dig i befintliga aktiviteter! Vi erbjuder stöd för att organisera evenemang, leda 
        grupper eller för annan aktivitet i den mån det är möjligt.</p>
        <h3>Så här kommer du med</h3>
        <p>Om du blev intresserad, kontakta kontaktpersonerna för volontärverksamheten eller fråga personalen på biblioteket.</p>
        <p>Som volontär på biblioteket undertecknar du ett avtal om volontärverksamhet och under verksamheten är du försäkrad av Helsingfors stad. Du åtar dig att arbeta som volontär så länge eller under en så 
        kort tid du vill. Deltagande i vissa volontäruppdrag avtalas för en termin i taget.</p>
        <h4>Kontaktpersoner:</h4>
        <p><strong>Södra området:</strong> Busholmens, Drumsö, Lillhoplax, Richardsgatans, Tölö och Sveaborgs bibliotek</p><p>Leeni van Tulder leeni.vantulder@hel.fi<br>
        Vappu Nurmi (Läskamraterna) vappu.nurmi@hel.fi</p>
        <p><strong>Östra området:</strong> Hertonäs, Östra centrums, Gårdsbacka, Degerö, Kvarnbäckens, Kasbergets, Östersundom och Nordsjö bibliotek</p><p>Romana Mázerová romana.mazerova@hel.fi</p>
        <p><strong>Mellersta området:</strong> Arabiastrandens, Berghälls, Kottby, Månsas, Åggelby, Svedängens och Vallgårds bibliotek</p>
        <p>Eeva Karhunen eeva.karhunen@hel.fi<br>
        Johanna Laaksonen johanna.laaksonen@hel.fi</p>
        <p><strong>Västra området:</strong> Södra Haga, Gamlas, Malmgårds, Munksnäs, Böle, Sockenbacka och Norra Haga bibliotek</p><p>Sari Langdon sari.langdon@hel.fi</p>
        <p><strong>Norra området: </strong>Jakobacka, Malms, Parkstads, Bocksbacka, Skomakarböle, Mosabacka, Stapelstadens och Viks bibliotek</p>
        <p>Tuula Rönkä tuula.ronka@hel.fi<br>
        Iiro Laukola iiro.laukola@hel.fi</p>
        <p><strong>Centrumbiblioteket Ode</strong></p>
        <p>Ulla Leinikka ulla.leinikka@hel.fi<br>
        Leena Eskelinen leena.eskelinen@hel.fi</p>
      </div>
      <div id="vantaa" class="content-section">
        <h2>Frivilligarbete på biblioteken i Vanda</h2>
        <p>Som frivillig på Vanda stadsbibliotek kan du delta i att organisera mångsidig och varierande verksamhet. Du kan också organisera verksamhet på ditt eget modersmål. Du kan anmäla ditt intresse att 
        arbeta som frivillig på biblioteket via länken nedan eller genom att kontakta ett bibliotek.</p>
        <p>På biblioteken kan du som frivillig till exempel hålla en bokcirkel eller en språkkurs för vuxna, läsa sagor eller böcker för barn, ordna verksamhet för ungdomar (till exempel spelkvällar), 
        leda en handarbetsgrupp eller ordna diskussionskvällar.</p>
        <p>Du kan delta i frivilligverksamheten precis så lång eller kort tid som du själv vill. Som frivillig på biblioteket får du skriva under ett avtal på frivilligverksamhet, varefter du är 
        försäkrad av Vanda stad under den tid som du arbetar som frivillig.</p>
        <h3>Så här kan du delta</h3>
        <p>Om du blev intresserad av frivilligverksamheten på biblioteken, kan du kontakta ditt närbibliotek. Du kan också anmäla dig via länken nedan, så kontaktar vi dig.</p>
        <p><a href="https://link.webropolsurveys.com/S/B5CE0D32DFB8CE2C" target="_blank" aria-label="Anmäl dig som frivillig på biblioteket. Länken öppnas i ett nytt fönster.">Anmäl dig som frivillig på biblioteket</a></p>
      </div>
   </div>
</div>
