<? $this->headTitle($this->translate('Volunteer at a library')); $this->content()->setHeading($this->translate('Volunteer at a library'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>As a volunteer at a Helmet library, you can participate in arranging myriad activities.</p>
        <p>Volunteers at libraries can, for example, head a book club or a language club for adults, read fairy tales or books to children, arrange activities for the young (for example, gaming evenings), 
        oversee a handicraft club, or arrange discussion evenings.</p>
        <p>Volunteers act as, for example, supervisors of reading circles, library grannies and grandpas, handlers of reading education assistance dogs, readers of novels and fairy tales, as well as supervisors 
        of handicraft and gaming clubs. You can also try out new forms of volunteer activities at the library. You can, furthermore, arrange activities in your mother tongue.</p>
        <p>By providing volunteer activities, the library supports civic activity, participation, and sense of community. As a volunteer, you get to share your skills, learn new ones, and meet new people. 
        Activities arranged by volunteers at the library will not replace the work conducted by library professionals.</p>
      </div>
     <div id="espoo" class="content-section">
        <h2>Volunteering at Espoo libraries</h2>
        <h3>Language café or easy language café</h3>
        <p>The language café is a place for Finnish conversation on a chosen topic. As a volunteer you will be helping immigrants from different countries to practise Finnish. You can listen and make 
        questions, advise and encourage. The language café is organised every Tuesday at Iso Omena Library at 5-6.30 p.m.<br><br>
        In the easy language café easy language news are read and listened to together. The participants are adult immigrants who practise understanding Finnish texts and talking about current topics. 
        The easy language café is organised at Entresse Library on Thursdays 10 a.m. - noon.<br><br>
        Join in! For more information on the language café and the easy language café: <a href="mailto:jasmin.lappalainen@espoo.fi">jasmin.lappalainen@espoo.fi</a>.</p>
        <h3>Book club host</h3>
        <p>Do you like to read a lot? Do you find it natural to discuss about what you’ve read? Library’s book clubs are gathering places for people interested in literature. We read a book that’s 
        decided together and discuss it with a host. There are book clubs in different libraries at different times.<br><br>
        We’re searching for hosts and co-hosts. You don’t have to speak Finnish to join. The role of the host is to open the conversation, lead it on and make sure that everyone gets the chance to speak.<br><br>
        If you’re interested, contact us at <a href="mailto:satu.nylund@espoo.fi">satu.nylund@espoo.fi</a> and we’ll gladly tell you more!</p>
        <h3>Reading dog or reading pet owner</h3>
        <p>Animal-assisted reading is an important form of volunteer work. Do you have a pet who would be suitable? A dog, a cat, a bunny, a tortoise, any other pet? Your pet should be in your control, 
        should not be afraid of the noise of the library and should like humans (particularly children). Your pet can be perky and peppy. Personally, you should be interested in helping children struggling with 
        reading in their early attempts. The schedule and the suitable library are agreed upon according to your wishes. You’ll get an introduction to the task. The library hopes your pet has taken some sort of 
        an aptitude test to ensure they are happy to work as a volunteer. Please see <a href="https://suomenkarvakaverit.fi/" target="_blank" 
        aria-label="Suomen Karvakaverit. The link opens in a new window.">Suomen Karva-Kaverit </a>or 
        <a href="https://www.kennelliitto.fi/en/dogs/reading-dogs" target="_blank" 
        aria-label="Kennelliitto. The link opens in a new window.">The Finnish Kennel Club</a> for further details. For further questions contact 
        <a href="mailto:kirjasto.lukukoira@espoo.fi">kirjasto.lukukoira@espoo.fi</a>.</p>
        <h3>Homework club instructor</h3>
        <p>The library is a place to spend time and do homework in for many school children. Sometimes, though, the children need help with the homework. Why don’t you come and help!<br><br>
        The homework club is an open club, where school children can ask help with their homework from the volunteers. The homework club is organised in different libraries on agreed dates. Volunteers commit 
        to the club for one term at a time.</p>
        <p>If you’re interested, contact ira.cottier@espoo.fi and we’ll gladly tell you more!</p>
        <h3>Makerspace instructor</h3>
        <p>The library’s makerspaces are meant for making! Can you sew, knit, crochet, felt, draw, make handicrafts, build or something else? Would you like to share your know-how by guiding others?<br><br>
        We’re looking for makerspace instructors to help especially children, young people and immigrant groups. You can also help patrons with machines in the makerspace, such as the vinyl cutter, 3D printers 
        and sewing machines. We’ll give you an introduction to the machines. Join us!</p>
        <p>More information on the makerspace: <a href="mailto:marja.uosukainen@espoo.fi">marja.uosukainen@espoo.fi</a>.</p>
        <h3>Volunteering with organisations</h3>
        <p>Couldn’t find anything suitable for you? There are also different organisations and societies through which you can volunteer. Activities relating to learning and practising Finnish is organised by 
        Luetaan yhdessä -network, The Finnish Red Cross and The Finnish Refugee Council. Digital support for the elderly is provided by Enter ry. Reading dog activity is organised by The Finnish Kennel Club.</p><p>
        <h4>More information:</h4>
        <ul class="list-bullets">
            <li><a href="https://luetaanyhdessa.fi/tule-mukaan/vapaaehtoiseksi/" target="_blank" aria-label="Luetaan yhdessä -network. The link opens in a new window.">Luetaan yhdessä -network</a></li>
            <li><a href="https://rednet.punainenristi.fi/keskiespoo" target="_blank" aria-label="The Finnish Red Cross, central Espoo branch. The link opens in a new window.">The Finnish Red Cross, central Espoo branch</a></li>
            <li><a href="https://pakolaisapu.fi/vapaaehtoistyo/" target="_blank" aria-label="The Finnish Refugee Council. The link opens in a new window.">The Finnish Refugee Council</a></li>
            <li><a href="https://www.entersenior.fi/yhdistys/tule-vapaaehtoiseksi/" target="_blank" aria-label="Enter ry. The link opens in a new window.">Enter ry</a></li>
            <li><a href="https://www.kennelliitto.fi/koirat/lukukoirat" target="_blank" aria-label="The Finnish Kennel Club. The link opens in a new window.">The Finnish Kennel Club</a></li>
        </ul>
      </div>
      <div id="helsinki" class="content-section">
        <h2>Volunteer at Helsinki City Library</h2>
        <h3>Book club instructor</h3>
        <p>Our book clubs get together once a month to read books and discuss literature. Our staff will familiarise you with the task and can also help you get started on leading the club.</p>
        <p>Book club volunteers are expected to have an interest in literature, but no other experience is required.</p>
        <h3>After-school activity instructor for children and young people</h3>
        <p>Library grandmas and grandpas and other after-school activity instructors play games, read aloud stories, draw pictures and just spend time with children after school. As a library grandma or 
        grandpa, you can take part in activities that you enjoy. The volunteers spend approximately 2–2.5 hours at the library on an agreed day every week.</p>
        <h3>Finnish language café instructor</h3>
        <p>At Finnish language cafés, you can help immigrants learn Finnish or act as the café instructor. You are required to have a good command of the Finnish language, good communication skills and patience 
        to listen and understand various levels of spoken Finnish. Library staff are sometimes also involved as language café instructors. All volunteers are trained for the task.</p>
        <p>The purpose of the activities is to strengthen the participants’ Finnish language skills, provide them with information about the Finnish society, help them integrate into our society and give them 
        the opportunity to meet new people.</p>
        <p>Language cafés are usually held once a week, some less often.</p>
        <h3>Reading ambassador</h3>
        <p>Do you enjoy reading? Would you like to pass on the joy of reading to others? Why not join our reading ambassador activities! As a reading ambassador, you will support reading as a hobby by 
        reading aloud to senior citizens or others who need help with reading. The reading usually takes place at service homes.</p>
        <p>Helsinki libraries will support you in your role as a reading ambassador. The libraries organise get-togethers for reading ambassadors where they give tips on books that are suitable for 
        reading aloud, share the joy of reading, and discuss questions and experiences related to reading.</p>
        <p>Keep an eye on our event calendar on the Helmet.fi website to see when the reading ambassadors will next meet. For further information, please email 
        <a href="mailto:lukulahettilas@hel.fi">lukulahettilas@hel.fi</a> or contact your local library staff.</p>
        <p>You can also act as a reader in various library events, such as Novellikoukku (Hooked on short stories).</p>
        <h3>Other activities</h3>
        <p>Libraries offer many volunteering opportunities – come up with your own idea or get involved in our existing activities! Where possible, we offer support in organising events, instructing groups or 
        hosting other activities.</p>
        <p>As a library volunteer, you will sign a volunteering agreement, and the City of Helsinki will insure you during your voluntary work. You can commit to volunteering for as long or short period of time as 
        you wish. In certain tasks, volunteers commit to the activities for one semester at a time.</p>
        <h3>How to get involved</h3>
        <p>If you are interested in volunteering, please get in touch with our contact persons for voluntary work or your local library.</p>
        <h4>Contact persons</h4>
        <p><strong>Southern Helsinki:</strong> Jätkäsaari, Lauttasaari, Pikku-Huopalahti, Rikhardinkatu, Töölö and Suomenlinna libraries</p>
        <p>Leeni van Tulder leeni.vantulder@hel.fi<br>
        Vappu Nurmi (Reading Ambassadors) vappu.nurmi@hel.fi</p>
        <p><strong>Eastern Helsinki:</strong> Herttoniemi, Itäkeskus, Kontula, Laajasalo, Myllypuro, Roihuvuori, Sakarinmäki and Vuosaari libraries</p>
        <p>Romana Mázerová romana.mazerova@hel.fi</p>
        <p><strong>Central Helsinki:</strong> Arabianranta, Kallio, Käpylä, Maunula, Oulunkylä, Paloheinä and Vallila libraries</p>
        <p>Eeva Karhunen eeva.karhunen@hel.fi<br>
        Johanna Laaksonen johanna.laaksonen@hel.fi</p><p>
        <strong>Western Helsinki:</strong> Etelä-Haaga, Kannelmäki, Malminkartano, Munkkiniemi, Pasila, Pitäjänmäki and Pohjois-Haaga libraries</p><p>Sari Langdon sari.langdon@hel.fi</p><p>
        <strong>Northern Helsinki:</strong> Jakomäki, Malmi, Puistola, Pukinmäki, Suutarila, Tapanila, Tapulikaupunki and Viikki libraries</p>
        <p>Tuula Rönkä tuula.ronka@hel.fi<br>
        Iiro Laukola iiro.laukola@hel.fi</p>
        <p><strong>Helsinki Central Library Oodi</strong></p>
        <p>Ulla Leinikka ulla.leinikka@hel.fi<br>
        Leena Eskelinen leena.eskelinen@hel.fi</p>
      </div>
      <div id="vantaa" class="content-section">
        <h2>Volunteer at Vantaa libraries</h2>
        <p>As a volunteer at a Vantaa city library, you can participate in arranging many different activities. You can also arrange activities in your mother tongue. Inform us about your interest in 
        acting as a volunteer at the library through the link below, or by contacting a library.</p>
        <p>Volunteers at libraries can, for example, head a book club or a language club for adults, read story books to children, arrange activities for the young (for example, gaming evenings), 
        oversee a handicraft club, or arrange discussion evenings.</p>
        <p>You can join library volunteer activities for as long as you like. As a library volunteer, you will sign an agreement on volunteer activities, and the City of Vantaa will insure you for the 
        duration of your volunteer work.</p>
        <h3>How to join</h3>
        <p>If you are interested in acting as a volunteer at the library, contact your own local library. You can also enroll through the link below, and we will contact you.</p>
        <p><a href="https://link.webropolsurveys.com/S/972C9BE873B539C9" target="_blank" aria-label="Enroll as a library volunteer. The link opens in a new window.">Enroll as a library volunteer</a></p>
      </div>
   </div>
</div>

