<? $this->headTitle($this->translate('Vapaaehtoiseksi kirjastoon')); $this->content()->setHeading($this->translate('Vapaaehtoiseksi kirjastoon'));?>
<div class="row">
   <div class="col-sm-3 sidebar">
     <div class="content-navigation-menu">
     </div>
   </div>
   <div class="col-sm-9">
     <div id="esim1" class="content-section">
        <p>Helmet-kirjastoissa voit osallistua vapaaehtoisena monenlaisen toiminnan järjestämiseen.</p>
        <p>Kirjastossa vapaaehtoiset toimivat esimerkiksi lukupiirien vetäjinä, kirjastomummoina ja -vaareina, lukukoiran ohjaajina, novellien ja satujen lukijoina sekä käsityö- ja pelikerhojen vetäjinä. 
        Kirjastossa on myös mahdollista kokeilla uusia vapaaehtoistoiminnan muotoja. Voit myös järjestää toimintaa omalla äidinkielelläsi.</p>
        <p>Vapaaehtoistoiminnan mahdollisuuksia tarjoamalla kirjasto tukee aktiivista kansalaisuutta, osallisuutta ja yhteisöllisyyttä. Vapaaehtoisena pääset jakamaan osaamistasi, opit uusia taitoja ja tapaat uusia 
        ihmisiä. Vapaaehtoisten järjestämä toiminta kirjastossa ei korvaa kirjastoammattilaisten tekemää työtä.</p>
        <p>Voit tulla mukaan vapaaehtoistoimintaan niin pitkäksi tai lyhyeksi aikaa kuin itse haluat. Jos kiinnostuit vapaaehtoistoiminnasta kirjastossa, ota yhteyttä omaan lähikirjastoosi.</p>
      </div>
     <div id="espoo" class="content-section">
        <h2>Vapaaehtoiseksi Espoon kirjastoihin</h2>
        <h3>Kielikahvilaan tai selkouutiskahveille</h3>
        <p>Kielikahvilassa keskustellaan suomeksi sovitusta aiheesta. Vapaaehtoisena pääset auttamaan kieltä harjoittelevia aikuisia maahanmuuttajia eri maista. Osaat kuunnella ja kysyä, neuvot ja kannustat.
        Kielikahvila kokoontuu Ison Omenan kirjastossa tiistaisin klo 17–18.30.<br><br>
        Selkouutiskahveilla kuunnellaan ja luetaan selkokielellä toteutettuja uutisia yhdessä. Osallistujat ovat aikuisia maahanmuuttajia, jotka harjoittelevat suomenkielisen tekstin ymmärtämistä ja 
        keskustelua ajankohtaisista aiheista. Selkouutiskahvit järjestetään Entressen kirjastossa torstaisin klo 10–12.<br><br>
        Tule mukaan! Lisätietoja kielikahvilatoiminnasta ja selkouutiskahveista: <a href="mailto:jasmin.lappalainen@espoo.fi">jasmin.lappalainen@espoo.fi</a></p>
        <h3>Lukupiirin vetäjäksi</h3>
        <p>Luetko mielelläsi paljon? Onko sinusta luontevaa keskustella lukemastasi? Kirjastojen lukupiireissä kokoontuu kirjallisuudesta innostuneita ihmisiä. Lukupiirissä luetaan ennalta yhdessä sovittu 
        teos ja keskustellaan siitä vetäjän johdolla. Lukupiirejä kokoontuu eri kirjastoissa eri kellonaikoihin.<br><br>
        Etsimme näihin lukupiireihin vetäjiä ja apuvetäjiä. Myös muut kuin suomenkieliset ovat tervetulleita. Lukupiirin vetäjän rooli on avata keskustelu ja johdatella sitä eteenpäin, ja pitää huoli 
        siitä, että jokainen saa tasapuolisesti puheenvuoron.<br><br>
        Jos kiinnostuit, ota yhteyttä <a href="mailto:satu.nylund@espoo.fi">satu.nylund@espoo.fi</a> ja kerromme mielellämme lisää!</p>
        <h3>Lukukoiran tai lukulemmikin ohjaajaksi</h3>
        <p>Lukemisen tukeminen eläinavusteisesti on tärkeää vapaaehtoistyötä. Onko sinulla lemmikki, joka haluaisi kanssasi kehittyä tähän tehtävään? Koira, kissa, pupu, kilpikonna, jokin muu ihanuus?
        Lemmikkisi on hallinnassasi, ei pelkää kirjaston melua ja pitää ihmisistä, erityisesti lapsista. Lemmikkisi saa olla vilkas ja innokas, itse olet kiinnostunut auttamaan lukemisen kanssa 
        kamppailevia lapsia lukemisen alkutaipaleella. Sopiva aikataulu sekä kirjasto räätälöidään teidän toiveidenne mukaan, ja saat alkuperehdytyksen tehtävään. Kirjasto toivoo lukulemmikkien 
        käyneen soveltuvuustestissä ennen vapaaehtoistyöhön ryhtymistä. Koulutusta sekä testejä järjestää mm. <a href="https://suomenkarvakaverit.fi/" target="_blank"
        aria-label="Suomen Karva-Kaverit Ry. Linkki aukeaa uudessa ikkunassa.">Suomen Karva-Kaverit Ry</a> sekä 
        <a href="https://www.kennelliitto.fi/koirat/lukukoirat" target="_blank" aria-label="Kennelliitto. Linkki aukeaa uudessa ikkunassa.">Kennelliitto</a>.<br><br>
        Ole yhteydessä ja kysy lisää <a href="mailto:kirjasto.lukukoira@espoo.fi">kirjasto.lukukoira@espoo.fi</a></p>
        <h3>Läksykerhon ohjaajaksi</h3>
        <p>Kirjasto on monelle koululaiselle ajanviettopaikka ja luontainen paikka tehdä yhdessä läksyjä. Joskus tehtävien kanssa kaivataan kuitenkin tukea. Tule mukaan auttamaan!<br><br>
        Kirjaston läksyapu on avoin hetki, jolloin koululaiset voivat kysyä apua vapaaehtoisilta läksyissään. Läksyapua järjestetään sovittuina päivinä eri kirjastoissa ja vapaaehtoiset aikuiset 
        sitoutuvat toimintaan lukukausi kerrallaan.<br><br>
        Jos kiinnostuit, ota yhteyttä <a href="mailto:ira.cottier@espoo.fi">ira.cottier@espoo.fi</a>, kerromme mielellämme lisää!</p>
        <h3>Pajaohjaajaksi</h3>
        <p>Kirjaston pajoissa saa tehdä! Osaatko ommella, neuloa, virkata, huovuttaa, piirtää, maalata, askarella, rakentaa tai jotakin muuta? Haluaisitko jakaa luovaa osaamistasi opastamalla muita?<br><br>
        Etsimme pajaohjaajia vetämään toimintaa erityisesti lapsi-, nuoriso- ja maahanmuuttaja-ryhmille. Voit myös opastaa pajassa olevien laitteiden, kuten vinyylileikkurin, 3d-tulostimien 
        tai ompelukoneiden käytössä. Perehdytämme sinut laitteiden käyttöön. Tule mukaan!<br><br>
        Lisätietoja pajatoiminnasta: <a href="mailto:marja.uosukainen@espoo.fi">marja.uosukainen@espoo.fi</a></p>
        <h3>Mukaan järjestöjen vapaaehtoistoimintaan</h3>
        <p>Etkö löytänyt mitään sinulle sopivaa? Espoon kirjastoissa toimii myös monia erilaisia yhdistyksiä ja järjestöjä, joiden kautta voit tulla mukaan vapaaehtoistoimintaan. Suomen kielen oppimiseen 
        ja harjoitteluun liittyvää toimintaa järjestävät Luetaan yhdessä -verkosto, Suomen Punainen Risti ja Suomen Pakolaisapu. Ikäihmisten digiopastusta tarjoaa Enter ry. Lukukoira-toiminnasta vastaa 
        Suomen kennelliitto.</p>
        <h4>Lisätietoja:</h4>
        <ul class="list-bullets">
            <li><a href="https://luetaanyhdessa.fi/tule-mukaan/vapaaehtoiseksi/" target="_blank" aria-label="Luetaan yhdessä -verkosto. Linkki aukeaa uudessa ikkunassa.">Luetaan yhdessä -verkosto</a></li>
            <li><a href="http://rednet.punainenristi.fi/keskiespoo" target="_blank" aria-label="Suomen Punainen Risti, Keski-Espoon osasto. Linkki aukeaa uudessa ikkunassa.">Suomen Punainen Risti, Keski-Espoon osasto</a></li>
            <li><a href="https://pakolaisapu.fi/vapaaehtoistyo/" target="_blank" aria-label="Suomen Pakolaisapu. Linkki aukeaa uudessa ikkunassa.">Suomen Pakolaisapu</a></li>
            <li><a href="https://www.entersenior.fi/yhdistys/tule-vapaaehtoiseksi/" target="_blank" aria-label="Enter ry. Linkki aukeaa uudessa ikkunassa.">Enter ry</a></li>
            <li><a href="https://www.kennelliitto.fi/koirat/lukukoirat" target="_blank" aria-label="Suomen kennelliitto ry. Linkki aukeaa uudessa ikkunassa.">Suomen kennelliitto ry</a></li>
        </ul>
      </div>
      <div id="helsinki" class="content-section">
        <h2>Vapaaehtoiseksi Helsingin kirjastoihin</h2>   
        <h3>Lukupiirin ohjaaja</h3>
        <p>Kuukausittain kokoontuvissa lukupiireissä luetaan kirjoja ja keskustellaan kirjallisuudesta. Kirjaston henkilökunta voi auttaa kirjojen valinnassa ja hankinnassa ja voi olla ainakin alussa 
        mukana ryhmän vetämisessä.</p>
        <p>Lukupiireihin osallistuvilta vapaaehtoisilta vaaditaan kiinnostusta kirjallisuuteen ja ihmisten kohtaamiseen, muuta kokemusta ei vaadita.</p>
        <h3>Lasten ja nuorten iltapäivätoiminnan ohjaaja</h3>
        <p>Kirjastomummot ja -vaarit ja muut iltapäivätoiminnan ohjaajat pelaavat, lukevat ja piirtelevät tai ovat muuten vain lasten seurana koulupäivän jälkeen. Kirjastomummona ja -vaarina voi toimia 
        itselle sopivalla tavalla. He viettävät aikaa kirjastolla viikoittain noin 2-2½ tuntia sovittuna päivänä.</p>
        <h3>Suomenkielisen kielikahvilan ohjaaja</h3>
        <p>Kielikahviloissa voit olla mukana tukemassa suomen oppimista tai ohjaamassa kielikahvilaa maahanmuuttajille. Vaatimuksena on hyvä suomen kieli, hyvät vuorovaikutustaidot ja 
        halu kuunnella ja ymmärtää eri tavoin puhuttua suomea. Kielikahviloissa on joskus mukana kirjaston työtekijöitä ryhmien ohjaajina. Vapaaehtoiset perehdytetään tehtävään.</p>
        <p>Toiminnan tarkoituksena on vahvistaa osallistujien suomen kielen taitoa, antaa tietoa suomalaisesta yhteiskunnasta, auttaa kotoutumaan ja antaa mahdollisuus tutustua uusiin ihmisiin.</p>
        <p>Kielikahvilat kokoontuvat pääsääntöisesti kerran viikossa, jotkut harvemmin.</p>
        <h3>Ääneenlukija</h3>
        <p>Pidätkö lukemisesta? Haluatko välittää lukuiloa muillekin? Tule mukaan lukulähettilästoimintaan! Lukulähettiläänä tuet Helsingissä lukuharrastuksen säilymistä lukemalla ääneen 
        ikääntyneille tai muille, jotka tarvitsevat apua lukemisessa. Lukeminen tapahtuu esimerkiksi palvelutaloissa.</p>
        <p>Helsinkiläisistä kirjastoista saat tukea lukulähettilään tehtävään. Kirjastoissa järjestetään lukijoille tapaamisia, joissa annetaan vinkkejä ääneen lukemiseen sopivista kirjoista, 
        välitetään lukuinspiraatiota sekä keskustellaan lukemiseen liittyvistä kysymyksistä ja kokemuksista.</p>
        <p>Seuraa helmet-sivuston tapahtumakalenterista, milloin lukulähettiläät tapaavat. Lisätietoja sähköpostilla <a href="mailto:lukulahettilas@hel.fi">lukulahettilas@hel.fi</a> sekä suoraan kirjastoista.</p>
        <p>Voit osallistua lukijana myös erilaisiin tapahtumiin kirjastoissa kuten Novellikoukkuun.</p>
        <h3>Asiakasyhteisö Kirjastoheimon jäsen</h3>
        <p>Onko sinulla ajatuksia ja ideoita siitä, miten kirjastoista tehtäisiin entistäkin hauskempia ja toimivampia paikkoja ihan kaikille? Haluatko tutustua muihin kirjastoaktiiveihin? 
        Jos vastauksesi on kyllä, tule ihmeessä mukaan Kirjastoheimon toimintaan!</p>
        <p>Kirjastoheimo on Helsingin kaupunginkirjaston asiakasyhteisö, jonka kanssa on muun muassa arvioitu ja suunniteltu uusia kirjastotiloja, hahmoteltu tulevaisuuden kirjastoa työpajoissa ja 
        verkkokyselyin, sekä vierailtu inspiroivissa kohteissa.</p>
        <p>Kirjastoheimon toimintaan voit osallistua joustavasti omien aikataulujesi mukaan. Liity mukaan hauskaan porukkaan lähettämällä sähköpostia osoitteeseen <a href="mailto: paivi.grondahl@hel.fi">
        paivi.grondahl@hel.fi</a></p>
        <h3>Muu toiminta</h3>
        <p>Kirjastoissa on monia mahdollisuuksia osallistua vapaaehtoistoimintaan – tule mukaan olemassa olevaan toimintaan tai ideoi itse!</p>
        <p>Toiminta voi olla kertaluontoista tai jatkuvaa. Voit järjestää yksittäisen tapahtuman tai ohjata harrastuspiiriä oman osaamisesi ja kiinnostuksesi mukaan. Myös lapset ja nuoret ovat 
        tervetulleita esimerkiksi vetämään lukupiiriä tai suosittelemaan kirjoja, pelejä tai elokuvia kirjastossa! Ole rohkeasti yhteydessä kirjastoon, mietitään yhdessä, onko ideasi mahdollista toteuttaa!</p>
        <h3>Lisätietoja</h3>
        <p>Kirjaston vapaaehtoisena allekirjoitat vapaaehtoistoiminnan sopimuksen, ja sinut on vakuutettu Helsingin kaupungin puolesta vapaaehtoistoiminnan aikana. Voit sitoutua mukaan niin pitkäksi tai 
        lyhyeksi aikaa kuin itse haluat. Joissakin vapaaehtoistehtävissä osallistumisesta sovitaan lukukaudeksi kerrallaan.</p>
        <h3>Näin pääset mukaan</h3>
        <p>Jos kiinnostuit, ota yhteyttä vapaaehtoistoiminnan yhteyshenkilöihin tai kysy suoraan omasta kirjastostasi.</p>
        <h4>Yhteyshenkilöt:</h4>
        <p>Eteläinen alue: Leeni van Tulder <a href="mailto:leeni.vantulder@hel.fi">leeni.vantulder@hel.fi</a>, Vappu Nurmi (Lukulähettiläät) <a href="mailto:vappu.nurmi@hel.fi">vappu.nurmi@hel.fi</a></p>
        <ul class="list-bullets">
            <li>Jätkäsaaren</li>
            <li>Lauttasaaren</li>
            <li>Pikku-Huopalahden</li>
            <li>Rikhardinkadun</li>
            <li>Töölön</li>
            <li>ja Suomenlinnan kirjastot</li>
        </ul>
        <p>Itäinen alue: Romana Mázerová <a href="mailto:romana.mazerova@hel.fi">romana.mazerova@hel.fi</a></p>
        <ul class="list-bullets">
            <li>Herttoniemen</li>
            <li>Itäkeskuksen</li>
            <li>Kontulan</li>
            <li>Laajasalon</li>
            <li>Myllypuron</li>
            <li>Roihuvuoren</li>
            <li>Sakarinmäen</li>
            <li>ja Vuosaaren kirjastot</li>
        </ul>
        <p>Keskinen alue: Eeva Karhunen <a href="mailto:eeva.karhunen@hel.fi">eeva.karhunen@hel.fi</a>, Johanna Laaksonen <a href="mailto:johanna.laaksonen@hel.fi">johanna.laaksonen@hel.fi</a></p>
        <ul class="list-bullets">
            <li>Arabianrannan</li>
            <li>Kallion</li>
            <li>Käpylän</li>
            <li>Maunulan</li>
            <li>Oulunkylän</li>
            <li>Paloheinän</li>
            <li>ja Vallilan kirjastot</li>
        </ul>
        <p>Läntinen alue: Sari Langdon <a href="mailto:">sari.langdon@hel.fi</a></p>
        <ul class="list-bullets">
            <li>Etelä-Haagan</li>
            <li>Kannelmäen</li>
            <li>Malminkartanon</li>
            <li>Munkkiniemen</li>
            <li>Pasilan</li>
            <li>Pitäjänmäen</li>
            <li>ja Pohjois-Haagan kirjastot</li>
        </ul>
        <p>Pohjoinen alue: Tuula Rönkä <a href="mailto:tuula.ronka@hel.fi">tuula.ronka@hel.fi</a>, Iiro Laukola <a href="mailto:iiro.laukola@hel.fi">iiro.laukola@hel.fi</a></p>
        <ul class="list-bullets">
            <li>Jakomäen</li>
            <li>Malmin</li>
            <li>Puistolan</li>
            <li>Pukinmäen</li>
            <li>Suutarilan</li>
            <li>Tapanilan</li>
            <li>Tapulikaupungin </li>
            <li>ja Viikin kirjastot</li>
        </ul>
        <p>Keskustakirjasto Oodi: Ulla Leinikka <a href="mailto:ulla.leinikka@hel.fi">ulla.leinikka@hel.fi</a>, Leena Eskelinen <a href="mailto:leena.eskelinen@hel.fi">leena.eskelinen@hel.fi</a></p>
      </div>
      <p>Viimeksi päivitetty 24.3.2023</p>
     <div id="vantaa" class="content-section">
        <h2>Vapaaehtoiseksi kirjastoon Vantaalla</h2>
        <h3>Kirjastomummo, -vaari tai -kummi</h3>
        <p>Kirjastokummina vietät aikaa kirjastossa koulun jälkeen oleskelevien lasten ja nuorten kanssa. Kirjastokummi voi auttaa läksyissä, pelata lautapelejä, askarrella, lukea sekä keskustella ja kuunnella. 
        Tulet hyvin toimeen lasten ja nuorten kanssa, kohtaat ennakkoluulottomasti erilaisista taustoista tulevia ihmisiä ja haluat viettää heidän kanssaan aikaa.</p>
        <p>Kirjastokummina tarjoat lapsille ja nuorille turvallisen aikuisen seuraa ja kuuntelevaa korvaa mukavassa ympäristössä. Läsnäolollasi teet kirjastosta yhteisöllisemmän ja mukavamman paikan 
        kaikenikäisille.</p>
        <p>Saat tarvittaessa kirjastosta tukea lasten ja nuorten kohtaamiseen. Kirjasto voi myös auttaa askartelun tai muuhun ohjattuun toimintaan tarvittavien materiaalien hankinnassa.</p>
        <h3>Kotikirjaston vapaaehtoinen</h3>
        <p>Kotikirjaston vapaaehtoisena toimitat kirjastosta lainattuja kirjoja ja muuta aineistoa asiakkaille, jotka eivät esimerkiksi korkean iän, sairauden tai vamman takia voi itse asioida kirjastossa. 
        Asiakas voi olla yksityishenkilö tai esimerkiksi palvelutalo. Kirjasto etsii kotipalvelua toivoville asiakkaille sopivan vapaaehtoisen.</p>
        <p>Sovit itse asiakkaan kanssa, kuinka usein toimitat hänelle kirjoja tai muuta aineistoa. Kirjat lainataan kotipalvelun kirjastokortilla, jonka saat kirjastosta. Asiakas voi itse toivoa 
        lainattavaa aineistoa, ja kirjaston henkilökunta auttaa sinua tarvittaessa kirjojen valinnassa.</p>
        <p>Vapaaehtoisena autat jakamaan lukemisen riemua myös heille, jotka eivät itse pääse kirjastoon. Tapaat erilaisia ihmisiä ja lievität yksinäisyyttä. Kotikirjaston vapaaehtoisena luot runsaasti 
        hyvää mieltä pienelläkin panoksella.</p>
        <h3>Lukukoiran ohjaaja</h3>
        <p>Lukukoiran ohjaajana pidät kirjastossa lukukoiratuokioita. Lukukoiratoiminnassa lapsi tai muu lukemaan tai kieltä opetteleva henkilö lukee koiralle ääneen ja saa positiivisen kokemuksen lukemisesta. 
        Ohjaajana pidät huolta koirastasi ja lukutuokioiden sujumisesta.</p>
        <p>Lukukoiraohjaajan tulee olla täysi-ikäinen ja Kennelliiton jäsen. Katso <a href="https://www.kennelliitto.fi/koirat/lukukoirat" target="_blank">lisätietoa lukukoiraohjaajana toimimisesta 
        Kennelliiton sivuilta.</a></p>
        <p>Lukukoiran ohjaajana tuet lukutaidon kehittymistä ainutlaatuisella ja hauskalla tavalla. Saat mielekästä ja kiinnostavaa tekemistä koirasi kanssa, ja lukukoira saa loputtomasti huomiota ja 
        rapsutuksia.</p>
        <h3>Lukupiirin ohjaaja</h3>
        <p>Lukupiirin ohjaajana vedät kirjastossa lukupiiriä. Toimit ohjaajana joko yksin tai yhdessä kirjaston henkilökunnan tai muiden vapaaehtoisten lukupiiriläisten kanssa. Olet kiinnostunut 
        lukemisesta ja kirjoista, haluat tavata muita ihmisiä ja keskustella kirjallisuudesta.</p>
        <p>Valitset lukupiirin aikataulun ja luettavat itse tai yhdessä lukupiiriläisten kanssa. Voit halutessasi pitää lukupiiriä jollain tietyllä teemalla 
        (esim. <a href="https://ilmastolukupiiri.fi/" target="_blank" aria-label="ilmastolukupiiri. Linkki aukeaa uudessa ikkunassa.">ilmastolukupiiri</a>, 
        tasa-arvolukupiiri jne.) tai tietylle kohdeyleisölle (eläkeläiset, pikkulasten vanhemmat jne.).
        Kirjaston henkilökunta voi tarvittaessa auttaa kirjojen valinnassa ja hankinnassa.</p>
        <p>Voit toimia vapaaehtoisena lukupiirissä myös etänä.</p>
        <h3>Pelikaveri</h3>
        <p>Toimit ohjaajana tai pelikaverina lapsille ja nuorille suunnatuissa konsolipelituokioissa tai lautapelikerhossa. Pelaat yhdessä lasten kanssa tai autat pelin alkuun pääsemisessä, 
        juttelet peleistä ja varmistat, että jokainen pääsee pelaamaan vuorollaan. Lisäksi olet kiinnostunut lasten pelaamisesta ja suhtaudut siihen myönteisesti. Digitaalisten pelien kohdalla tunnet 
        ikärajat ja niihin liittyvän lainsäädännön tai olet valmis tutustumaan niihin. Kirjasto antaa tarvittaessa tukea pelikasvatuksessa ja pelien valinnassa.</p>
        <p>Pelikaverina tarjoat mielekästä, ohjattua tekemistä kirjastossa aikaa viettäville lapsille ja nuorille. Samalla annat heille tilaisuuden keskustella peleistä ja pelaamisesta turvallisessa 
        ympäristössä. Pääset myös itse pelaamaan hauskoja pelejä ja voit vaikuttaa kirjaston pelivalikoimaan omilla suosituksillasi.</p>
        <h3>Suomen- tai muunkielisen kielikahvilan vetäjä tai puhekaveri</h3>
        <p>Kielikahvilan vapaaehtoisena keskustelet suomea tai muuta kieltä opettelevien osallistujien kanssa. Keskustelijoina on kieltä osaavia ja sitä opettelevia. Erityisiä opetustaitoja ei tarvita. 
        Kirjastoissa toimii kieliryhmien vetäjinä myös Luetaan yhdessä -verkoston vapaaehtoisia. Katso lisää: <a href="https://luetaanyhdessa.fi/" target="_blank" 
        aria-label="Luetaan yhdessä -verkosto. Linkki aukeaa uudessa ikkunassa.">Luetaan yhdessä -verkosto.</a></p>
        <p>Voit toimia vapaaehtoisena kielikahvilassa myös etänä.</p>
        <h3>Suomen kielen lukupiirin vetäjä</h3>
        <p>Suomen kielen lukupiirin tavoitteena on tukea aikuisten maahanmuuttajien suomen kielen lukutaitoa sekä kielen oppimista, tutustuttaa osallistujia suomalaiseen kirjallisuuteen ja 
        kirjaston kokoelmiin. Lukupiirissä käsitellään erilaisia tekstejä kuten romaaneja, runoja, novelleja tai laulun sanoja. Lukupiiri on avoin kaikille, ja siihen voi osallistua, vaikka teksti ei olisi 
        ennestään tuttu. Lukupiirin vapaaehtoisena selität teksteissä esiintyviä vaikeita sanoja, esität kysymyksiä tekstistä ja ohjaat keskustelua. Kirjaston henkilökunta auttaa tarvittaessa sopivien tekstien 
        valinnassa.</p>
        <p>Voit toimia vapaaehtoisena suomen kielen lukupiirissä myös etänä.</p>
        <h3>Tietotekniikan vertaisopastaja</h3>
        <p>Tietotekniikan opastajana autat erilaisia asiakkaita tietokoneiden, tablettien ja matkapuhelinten käytössä. Digiopastajalla ei tarvitse olla aiheesta erityistaitoja, vaan perustiedot riittävät. 
        Kirjastossa toimivat tietotekniikan vertaisopastajat ovat Enter ry:n vapaaehtoisia. Pääset mukaan Enterin toimintaan ottamalla yhteyttä toiminnan koordinaattoriin. Katso 
        <a href="https://www.entersenior.fi/yhdistys/yhteystiedot/" target="_blank" aria-label="Enter ry. Linkki aukeaa uudessa ikkunassa.">lisätietoa ja yhteystiedot Enterin sivuilta</a>.</p>
        <h3>Toimintaa omalla kielellä</h3>
        <p>Onko äidinkielesi muu kuin suomi? Haluaisitko järjestää toimintaa omalla kielelläsi? Voit järjestää kirjastossa toimintaa tai tapahtumia haluamallasi kielellä, esimerkiksi lasten askartelua 
        englanniksi, satutunnin somaliksi tai lukupiirin arabiaksi. Kirjaston henkilökunta auttaa sinua tarvittaessa toiminnan ideoimisessa.</p>
        <h3>Ääneenlukija</h3>
        <p>Nautitko ääneen lukemisesta muiden iloksi? Lukijana voit osallistua esimerkiksi aikuisille suunnattuihin Novellikoukku-tapahtumiin tai päiväkoti- tai alakouluikäisille pidettäviin satutunteihin.
        Sovit yhdessä kirjaston henkilökunnan kanssa, millaisessa toiminnassa voisit olla mukana lukemassa.</p>
        <h3>Muu toiminta</h3>
        <p>Etkö löytänyt listasta sinulle sopivaa vapaaehtoistehtävää? Tule ehdottamaan kirjastoon, millaisessa roolissa haluaisit toimia vapaaehtoisena kirjastossa! Kokeilemme mielellämme uusia 
        vapaaehtoistoiminnan muotoja.</p>
        <h3>Lisätietoja</h3>
        <p>Kirjaston vapaaehtoisena allekirjoitat vapaaehtoistoiminnan sopimuksen, ja sinut on vakuutettu Vantaan kaupungin puolesta vapaaehtoistoiminnan aikana. Sitoudut mukaan vapaaehtoistoimintaan niin pitkäksi 
        tai lyhyeksi aikaa kuin itse haluat. Joissakin vapaaehtoistehtävissä osallistumisesta sovitaan lukukaudeksi kerrallaan.</p>
        <p>Vapaaehtoisena on mahdollista toimia myös etänä. Kirjasto tarjoaa etätoiminnan järjestämiseen tarvittaessa tukea ja tekniset puitteet.</p>
        <p>Jos kiinnostuit, ota yhteyttä omaan kirjastoosi. Voit myös ilmoittautua alla olevan linkin kautta, niin me otamme sinuun yhteyttä.</p><p>
        <a href="https://link.webropolsurveys.com/S/1A2F1E0A7BD89974" target="_blank" 
        aria-label="Ilmoittaudu kirjaston vapaaehtoiseksi. Linkki aukeaa uudessa ikkunassa.">Ilmoittaudu kirjaston vapaaehtoiseksi</a></p>
      </div>
   </div>
</div>
